-- ============================================
-- WATERS - Data Import
-- GUDBRO Database Standards v1.3
-- Total: 64 waters
-- ============================================

INSERT INTO waters (id, slug, name, description, category, status, brand, carbonation, source_type, tds_mg_l, ph_level, serving_size_ml, bottle_types, calcium_mg_l, magnesium_mg_l, sodium_mg_l, potassium_mg_l, bicarbonate_mg_l, silica_mg_l, flavor, has_real_fruit, calories_per_serving, sugar_g, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, tags, popularity, origin_country, origin_region) VALUES

-- ============================================
-- STILL NATURAL (12 items)
-- ============================================
('WTR_EVIAN', 'evian', 'Evian', 'Premium French mineral water from the Cachat Spring in the French Alps, known for its pure, clean taste', 'still_natural', 'premium', 'Evian', 'none', 'spring', 309, 7.2, 500, ARRAY['pet', 'glass'], 80, 26, 6.5, 1, 360, 15, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'alps', 'premium', 'iconic'], 95, 'France', 'Haute-Savoie'),
('WTR_FIJI', 'fiji', 'Fiji Water', 'Artesian water from an underground aquifer in the remote Yaqara Valley of Viti Levu, Fiji', 'still_natural', 'premium', 'Fiji Water', 'none', 'artesian', 222, 7.7, 500, ARRAY['pet'], 18, 15, 18, NULL, NULL, 93, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['artesian', 'tropical', 'premium', 'silica-rich'], 92, 'Fiji', 'Yaqara Valley'),
('WTR_ACQUA_PANNA', 'acqua-panna', 'Acqua Panna', 'Tuscan natural spring water, ideal for fine dining with its smooth, velvety texture', 'still_natural', 'premium', 'Acqua Panna', 'none', 'spring', 188, 8.0, 750, ARRAY['glass', 'pet'], 32, 6.4, 6.5, NULL, 106, 8.2, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'tuscan', 'fine-dining', 'premium'], 88, 'Italy', 'Tuscany'),
('WTR_VOSS_STILL', 'voss-still', 'Voss Still', 'Norwegian artesian water from a pristine aquifer, known for its iconic cylindrical bottle', 'still_natural', 'premium', 'Voss', 'none', 'artesian', 44, 6.0, 375, ARRAY['glass', 'pet'], 5, 1, 5, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['norwegian', 'design', 'ultra-pure', 'luxury'], 85, 'Norway', 'Iveland'),
('WTR_VITTEL', 'vittel', 'Vittel', 'French natural mineral water from the Vosges mountains, rich in calcium and magnesium', 'still_natural', 'classic', 'Vittel', 'none', 'spring', 405, 7.4, 500, ARRAY['pet', 'glass'], 94, 20, 7.3, NULL, 248, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'calcium-rich', 'classic'], 80, 'France', 'Vosges'),
('WTR_VOLVIC', 'volvic', 'Volvic', 'Volcanic mineral water naturally filtered through six layers of volcanic rock in the Auvergne region', 'still_natural', 'classic', 'Volvic', 'none', 'volcanic', 130, 7.0, 500, ARRAY['pet'], 12, 8, 12, NULL, NULL, 32, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'volcanic', 'silica-rich'], 82, 'France', 'Auvergne'),
('WTR_LEVISSIMA', 'levissima', 'Levissima', 'Light Italian Alpine water from the Stelvio Natural Park, known for its exceptionally low mineral content', 'still_natural', 'classic', 'Levissima', 'none', 'glacier', 80, 7.8, 500, ARRAY['pet', 'glass'], 21, 2, 1.9, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'alpine', 'light', 'low-sodium'], 78, 'Italy', 'Lombardy'),
('WTR_SANT_ANNA', 'sant-anna', 'Sant''Anna', 'Ultra-light Italian mineral water from 2000m altitude in the Maritime Alps, ideal for babies', 'still_natural', 'popular', 'Sant''Anna', 'none', 'spring', 48, 6.8, 500, ARRAY['pet'], 10, 0.5, 1.5, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'ultra-light', 'baby-friendly', 'low-sodium'], 75, 'Italy', 'Piedmont'),
('WTR_MOUNTAIN_VALLEY', 'mountain-valley', 'Mountain Valley Spring Water', 'Historic American spring water from the Ouachita Mountains, served at the White House since 1928', 'still_natural', 'premium', 'Mountain Valley', 'none', 'spring', 220, 7.8, 500, ARRAY['glass'], 68, 8, 2.5, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'historic', 'premium', 'glass-only'], 72, 'USA', 'Arkansas'),
('WTR_CRYSTAL_GEYSER', 'crystal-geyser', 'Crystal Geyser Alpine Spring Water', 'American spring water sourced from protected springs near Mt. Shasta', 'still_natural', 'active', 'Crystal Geyser', 'none', 'spring', 95, 6.9, 500, ARRAY['pet'], 15, 4, 3, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'affordable', 'alpine'], 68, 'USA', 'California'),
('WTR_HILDON', 'hildon', 'Hildon', 'British natural mineral water from the chalk hills of Hampshire, served in Buckingham Palace', 'still_natural', 'premium', 'Hildon', 'none', 'spring', 312, 7.2, 750, ARRAY['glass'], 97, 2, 8, NULL, 242, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['british', 'royal', 'premium', 'calcium-rich'], 70, 'UK', 'Hampshire'),
('WTR_SMERALDINA', 'smeraldina', 'Smeraldina', 'Sardinian mineral water filtered through granite for 25 years, exceptionally low in sodium', 'still_natural', 'premium', 'Smeraldina', 'none', 'spring', 171, 7.6, 750, ARRAY['glass', 'pet'], 30, 4, 5.6, NULL, NULL, 12, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'sardinian', 'granite-filtered', 'premium'], 68, 'Italy', 'Sardinia'),

-- ============================================
-- SPARKLING NATURAL (8 items)
-- ============================================
('WTR_GEROLSTEINER', 'gerolsteiner', 'Gerolsteiner', 'German naturally sparkling mineral water from volcanic Eifel region, rich in calcium and magnesium', 'sparkling_natural', 'classic', 'Gerolsteiner', 'natural', 'mineral', 2527, 5.9, 500, ARRAY['glass', 'pet'], 348, 108, 118, 11, 1816, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['german', 'volcanic', 'mineral-rich', 'calcium-rich'], 88, 'Germany', 'Eifel'),
('WTR_BADOIT', 'badoit', 'Badoit', 'French naturally sparkling water with fine bubbles from Saint-Galmier, Loire Valley', 'sparkling_natural', 'premium', 'Badoit', 'natural', 'spring', 1200, 6.0, 750, ARRAY['glass', 'pet'], 190, 85, 165, NULL, 1300, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'fine-bubbles', 'fine-dining', 'premium'], 82, 'France', 'Loire Valley'),
('WTR_FERRARELLE', 'ferrarelle', 'Ferrarelle', 'Italian naturally effervescent water from volcanic springs of Roccamonfina, rich in calcium', 'sparkling_natural', 'classic', 'Ferrarelle', 'natural', 'volcanic', 1280, 6.2, 500, ARRAY['glass', 'pet'], 441, 17, 50, 52, 1435, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'volcanic', 'naturally-sparkling', 'calcium-rich'], 85, 'Italy', 'Campania'),
('WTR_APOLLINARIS', 'apollinaris', 'Apollinaris', 'Historic German naturally sparkling mineral water from the Eifel volcanic region since 1852', 'sparkling_natural', 'classic', 'Apollinaris', 'natural', 'mineral', 2622, 5.8, 500, ARRAY['glass', 'pet'], 100, 120, 460, NULL, 1800, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['german', 'historic', 'volcanic', 'mineral-rich'], 75, 'Germany', 'Rhineland-Palatinate'),
('WTR_SELTERS', 'selters', 'Selters', 'Historic German naturally sparkling water, the original seltzer dating back to 1536', 'sparkling_natural', 'classic', 'Selters', 'natural', 'mineral', 1620, 5.6, 500, ARRAY['glass', 'pet'], 109, 30, 279, NULL, 930, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['german', 'historic', 'original-seltzer'], 70, 'Germany', 'Hesse'),
('WTR_BORJOMI', 'borjomi', 'Borjomi', 'Georgian naturally sparkling volcanic mineral water with very high TDS, known since 1820', 'sparkling_natural', 'premium', 'Borjomi', 'natural', 'volcanic', 5000, 6.0, 500, ARRAY['glass', 'pet'], 35, 20, 1500, NULL, 3500, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['georgian', 'volcanic', 'ultra-mineral', 'therapeutic'], 78, 'Georgia', 'Borjomi'),
('WTR_WATTWILLER', 'wattwiller', 'Wattwiller', 'French naturally sparkling water from the Vosges mountains, known for delicate effervescence', 'sparkling_natural', 'premium', 'Wattwiller', 'natural', 'spring', 156, 7.1, 500, ARRAY['glass', 'pet'], 288, 19, 3, NULL, 258, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'light-effervescence', 'low-sodium'], 65, 'France', 'Alsace'),
('WTR_LAURETANA', 'lauretana', 'Lauretana Sparkling', 'Italian naturally sparkling water from the Alps, one of the lightest mineral waters in Europe', 'sparkling_natural', 'premium', 'Lauretana', 'natural', 'glacier', 14, 6.3, 500, ARRAY['glass'], 2, 0.4, 1, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'ultra-light', 'alpine', 'premium'], 68, 'Italy', 'Piedmont'),

-- ============================================
-- SPARKLING ADDED (9 items)
-- ============================================
('WTR_SAN_PELLEGRINO', 'san-pellegrino', 'San Pellegrino', 'Italian sparkling mineral water from the Alps near Bergamo, the quintessential fine dining water', 'sparkling_added', 'premium', 'San Pellegrino', 'added', 'mineral', 948, 7.7, 750, ARRAY['glass', 'pet', 'can'], 181, 52, 35, NULL, 445, 7.1, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'fine-dining', 'iconic', 'premium'], 95, 'Italy', 'Lombardy'),
('WTR_PERRIER', 'perrier', 'Perrier', 'Iconic French sparkling mineral water from Vergèze, known for its distinctive green bottle', 'sparkling_added', 'premium', 'Perrier', 'added', 'mineral', 475, 5.5, 330, ARRAY['glass', 'can', 'pet'], 155, 6, 11, NULL, 430, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'iconic', 'green-bottle', 'mixer'], 92, 'France', 'Occitanie'),
('WTR_TOPO_CHICO', 'topo-chico', 'Topo Chico', 'Mexican sparkling mineral water from Monterrey, legendary for cocktails and the cult following', 'sparkling_added', 'popular', 'Topo Chico', 'added', 'mineral', 630, 5.8, 355, ARRAY['glass', 'can'], 95, 15, 105, NULL, 370, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['mexican', 'cult-following', 'cocktail-mixer', 'ranch-water'], 88, 'Mexico', 'Nuevo León'),
('WTR_SCHWEPPES_SODA', 'schweppes-soda', 'Schweppes Soda Water', 'Classic carbonated water for mixing, the original since 1783', 'sparkling_added', 'classic', 'Schweppes', 'added', 'well', 200, 4.5, 200, ARRAY['glass', 'can', 'pet'], NULL, NULL, 60, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['mixer', 'classic', 'cocktail', 'bar-essential'], 85, 'UK', 'London'),
('WTR_VOSS_SPARKLING', 'voss-sparkling', 'Voss Sparkling', 'Norwegian artesian water with added carbonation in the iconic cylindrical bottle', 'sparkling_added', 'premium', 'Voss', 'added', 'artesian', 44, 6.0, 375, ARRAY['glass', 'pet'], 5, 1, 5, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['norwegian', 'design', 'ultra-pure', 'luxury'], 82, 'Norway', 'Iveland'),
('WTR_SARATOGA', 'saratoga', 'Saratoga Sparkling Spring Water', 'Historic American sparkling water from the springs of Saratoga, NY, served since 1872', 'sparkling_added', 'premium', 'Saratoga', 'added', 'spring', 580, 7.4, 355, ARRAY['glass'], 90, 30, 35, NULL, 370, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'historic', 'premium', 'blue-bottle'], 72, 'USA', 'New York'),
('WTR_LURISIA', 'lurisia', 'Lurisia Sparkling', 'Italian sparkling water from the Maritime Alps, awarded for taste and purity', 'sparkling_added', 'premium', 'Lurisia', 'added', 'spring', 36, 6.6, 500, ARRAY['glass', 'pet'], 4, 0.7, 1.4, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'alpine', 'award-winning', 'ultra-pure'], 70, 'Italy', 'Piedmont'),
('WTR_PEJO', 'pejo', 'Acqua Pejo Sparkling', 'Italian alpine water from Val di Sole, Trentino, naturally low in sodium', 'sparkling_added', 'classic', 'Pejo', 'added', 'glacier', 156, 7.8, 500, ARRAY['glass', 'pet'], 27, 12, 1.3, NULL, 150, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'alpine', 'low-sodium', 'dolomites'], 68, 'Italy', 'Trentino'),
('WTR_POLAR_SELTZER', 'polar-seltzer', 'Polar Seltzer', 'New England classic carbonated water, the original American seltzer since 1882', 'sparkling_added', 'classic', 'Polar', 'added', 'well', 50, 4.8, 355, ARRAY['can', 'pet'], NULL, NULL, 5, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'new-england', 'classic', 'strong-carbonation'], 75, 'USA', 'Massachusetts'),

-- ============================================
-- MINERAL RICH (7 items)
-- ============================================
('WTR_CONTREX', 'contrex', 'Contrex', 'French high-mineral water rich in calcium and magnesium, popular for wellness', 'mineral_rich', 'classic', 'Contrex', 'none', 'mineral', 2078, 7.4, 500, ARRAY['pet'], 486, 84, 9, NULL, 372, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'high-calcium', 'wellness', 'slimming'], 78, 'France', 'Vosges'),
('WTR_HEPAR', 'hepar', 'Hépar', 'French magnesium-rich mineral water, the highest magnesium content of all French waters', 'mineral_rich', 'classic', 'Hépar', 'none', 'mineral', 2513, 7.2, 500, ARRAY['pet'], 549, 119, 14, NULL, 383, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'magnesium-rich', 'digestive', 'therapeutic'], 72, 'France', 'Vosges'),
('WTR_ULIVETO', 'uliveto', 'Uliveto', 'Italian mineral water from Tuscany, known since 1835 for digestive properties', 'mineral_rich', 'classic', 'Uliveto', 'natural', 'mineral', 1050, 5.8, 500, ARRAY['glass', 'pet'], 171, 29, 91, NULL, 568, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'tuscan', 'digestive', 'therapeutic'], 75, 'Italy', 'Tuscany'),
('WTR_ROCCHETTA', 'rocchetta', 'Rocchetta', 'Italian mineral water from Umbria, known for purifying and diuretic properties', 'mineral_rich', 'classic', 'Rocchetta', 'none', 'spring', 157, 7.82, 500, ARRAY['pet', 'glass'], 56, 4, 5, NULL, 192, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'umbrian', 'diuretic', 'purifying'], 70, 'Italy', 'Umbria'),
('WTR_DONAT_MG', 'donat-mg', 'Donat Mg', 'Slovenian natural mineral water with extremely high magnesium, used therapeutically', 'mineral_rich', 'premium', 'Donat Mg', 'natural', 'mineral', 13000, 6.6, 500, ARRAY['glass', 'pet'], 375, 1060, 1500, NULL, 7790, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['slovenian', 'ultra-magnesium', 'therapeutic', 'medicinal'], 68, 'Slovenia', 'Rogaska Slatina'),
('WTR_VICHY_CATALAN', 'vichy-catalan', 'Vichy Catalan', 'Spanish naturally sparkling mineral water from Catalonia, rich in bicarbonates', 'mineral_rich', 'classic', 'Vichy Catalan', 'natural', 'mineral', 2900, 6.1, 500, ARRAY['glass', 'pet'], 32, 10, 1097, NULL, 2120, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['spanish', 'catalonian', 'bicarbonate-rich', 'digestive'], 72, 'Spain', 'Catalonia'),
('WTR_ARARAT', 'ararat', 'Ararat', 'Armenian mineral water from the slopes of Mount Ararat, high in electrolytes', 'mineral_rich', 'premium', 'Ararat', 'natural', 'volcanic', 2400, 6.5, 500, ARRAY['glass', 'pet'], 150, 80, 450, NULL, 1200, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['armenian', 'volcanic', 'electrolyte-rich', 'post-workout'], 65, 'Armenia', 'Ararat'),

-- ============================================
-- LOW MINERAL (7 items)
-- ============================================
('WTR_PENTA', 'penta', 'Penta Ultra Purified Water', 'American ultra-purified water with virtually no minerals, 13-step purification process', 'low_mineral', 'premium', 'Penta', 'none', 'well', 0, 7.0, 500, ARRAY['pet'], NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'ultra-pure', 'zero-tds', 'athletes'], 65, 'USA', 'California'),
('WTR_SMARTWATER', 'smartwater', 'Smartwater', 'Vapor-distilled water with added electrolytes for taste, popular lifestyle brand', 'low_mineral', 'popular', 'Smartwater', 'none', 'well', 20, 7.0, 591, ARRAY['pet'], 0, 0, 0, 10, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'lifestyle', 'electrolytes', 'celebrity'], 85, 'USA', NULL),
('WTR_CORE', 'core-hydration', 'CORE Hydration', 'American ultra-purified water with minerals added for perfect pH balance of 7.4', 'low_mineral', 'popular', 'CORE', 'none', 'well', 35, 7.4, 591, ARRAY['pet'], 2, 1, NULL, 3, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'balanced-ph', 'lifestyle', 'fitness'], 78, 'USA', NULL),
('WTR_AQUAFINA', 'aquafina', 'Aquafina', 'PepsiCo purified drinking water with a 7-step purification system', 'low_mineral', 'active', 'Aquafina', 'none', 'well', 10, 6.0, 500, ARRAY['pet'], NULL, NULL, 0, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'purified', 'mainstream', 'affordable'], 82, 'USA', NULL),
('WTR_DASANI', 'dasani', 'Dasani', 'Coca-Cola purified water enhanced with minerals for a pure, fresh taste', 'low_mineral', 'active', 'Dasani', 'none', 'well', 25, 5.6, 500, ARRAY['pet'], NULL, 2, 5, 2, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'purified', 'mainstream', 'affordable'], 80, 'USA', NULL),
('WTR_DEER_PARK', 'deer-park', 'Deer Park', 'American spring water from the Appalachian Mountains, naturally low in minerals', 'low_mineral', 'classic', 'Deer Park', 'none', 'spring', 55, 6.8, 500, ARRAY['pet'], 8, 2, 3, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'spring', 'appalachian', 'regional'], 72, 'USA', 'Appalachian Mountains'),
('WTR_PURE_LIFE', 'pure-life', 'Pure Life', 'Purified water with added minerals for taste, one of the world best-selling brands', 'low_mineral', 'active', 'Pure Life', 'none', 'well', 45, 6.5, 500, ARRAY['pet'], 5, 3, 6, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['global', 'purified', 'mainstream', 'best-seller'], 85, 'USA', NULL),

-- ============================================
-- ALKALINE (6 items)
-- ============================================
('WTR_ESSENTIA', 'essentia', 'Essentia', 'Ionized alkaline water with 9.5+ pH, the leading alkaline water brand in the US', 'alkaline', 'popular', 'Essentia', 'none', 'well', 70, 9.5, 591, ARRAY['pet'], NULL, 3, 10, 8, 50, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'ionized', 'high-ph', 'electrolytes'], 88, 'USA', 'Washington'),
('WTR_WAIAKEA', 'waiakea', 'Waiakea Hawaiian Volcanic Water', 'Naturally alkaline volcanic water from Hawaii, filtered through 14,000 feet of lava rock', 'alkaline', 'premium', 'Waiakea', 'none', 'volcanic', 95, 8.2, 500, ARRAY['pet'], 4, 4, 14, 3, NULL, 35, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['hawaiian', 'volcanic', 'sustainable', 'naturally-alkaline'], 78, 'USA', 'Hawaii'),
('WTR_ICELANDIC_GLACIAL', 'icelandic-glacial', 'Icelandic Glacial', 'Naturally alkaline water from Iceland Ölfus Spring, filtered through lava for 5,000 years', 'alkaline', 'premium', 'Icelandic Glacial', 'none', 'glacier', 62, 8.4, 500, ARRAY['pet', 'glass'], 15, 4, 11, NULL, NULL, 15, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['icelandic', 'glacier', 'naturally-alkaline', 'carbon-neutral'], 82, 'Iceland', 'Ölfus'),
('WTR_EVAMOR', 'evamor', 'Evamor', 'Naturally alkaline artesian water from Louisiana with high pH and rare mineral profile', 'alkaline', 'premium', 'Evamor', 'none', 'artesian', 180, 9.0, 591, ARRAY['pet'], 35, 2, 20, NULL, 155, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'artesian', 'naturally-alkaline', 'louisiana'], 68, 'USA', 'Louisiana'),
('WTR_FLOW', 'flow', 'Flow Alkaline Spring Water', 'Canadian naturally alkaline spring water in eco-friendly paper-based carton', 'alkaline', 'popular', 'Flow', 'none', 'spring', 285, 8.1, 500, ARRAY['pet'], 60, 28, 3, NULL, 250, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['canadian', 'sustainable', 'eco-packaging', 'naturally-alkaline'], 72, 'Canada', 'Ontario'),
('WTR_JUST_WATER', 'just-water', 'JUST Water', 'Sustainably sourced alkaline spring water in plant-based packaging by Will Smith', 'alkaline', 'popular', 'JUST Water', 'none', 'spring', 45, 8.0, 500, ARRAY['pet'], 5, 2, 2, NULL, NULL, NULL, NULL, false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'sustainable', 'celebrity', 'eco-packaging'], 75, 'USA', 'New York'),

-- ============================================
-- FLAVORED (15 items)
-- ============================================
('WTR_LACROIX_LIME', 'lacroix-lime', 'LaCroix Lime', 'Classic lime-flavored sparkling water, the flavor that started the LaCroix revolution', 'flavored', 'popular', 'LaCroix', 'added', 'well', 10, 4.5, 355, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Lime', false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'classic', 'citrus', 'zero-calorie'], 90, 'USA', 'Wisconsin'),
('WTR_LACROIX_PAMPLEMOUSSE', 'lacroix-pamplemousse', 'LaCroix Pamplemousse', 'Grapefruit-flavored sparkling water, the iconic French-named bestseller', 'flavored', 'popular', 'LaCroix', 'added', 'well', 10, 4.5, 355, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Grapefruit', false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'bestseller', 'citrus', 'zero-calorie'], 92, 'USA', 'Wisconsin'),
('WTR_LACROIX_PASSIONFRUIT', 'lacroix-passionfruit', 'LaCroix Passionfruit', 'Tropical passionfruit-flavored sparkling water with exotic sweetness', 'flavored', 'popular', 'LaCroix', 'added', 'well', 10, 4.5, 355, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Passionfruit', false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'tropical', 'exotic', 'zero-calorie'], 85, 'USA', 'Wisconsin'),
('WTR_SPINDRIFT_LEMON', 'spindrift-lemon', 'Spindrift Lemon', 'Sparkling water with real squeezed lemon juice, the Cadillac of seltzers', 'flavored', 'premium', 'Spindrift', 'added', 'well', 15, 3.5, 355, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Lemon', true, 3, 1, true, true, true, true, true, true, true, ARRAY['american', 'real-fruit', 'premium', 'citrus'], 88, 'USA', 'Massachusetts'),
('WTR_SPINDRIFT_RASPBERRY_LIME', 'spindrift-raspberry-lime', 'Spindrift Raspberry Lime', 'Sparkling water with real raspberry and lime juice, bold fruit flavor', 'flavored', 'premium', 'Spindrift', 'added', 'well', 15, 3.4, 355, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Raspberry Lime', true, 9, 2, true, true, true, true, true, true, true, ARRAY['american', 'real-fruit', 'premium', 'berry'], 85, 'USA', 'Massachusetts'),
('WTR_SPINDRIFT_GRAPEFRUIT', 'spindrift-grapefruit', 'Spindrift Grapefruit', 'Sparkling water with real grapefruit juice, refreshingly tart', 'flavored', 'premium', 'Spindrift', 'added', 'well', 15, 3.3, 355, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Grapefruit', true, 15, 3, true, true, true, true, true, true, true, ARRAY['american', 'real-fruit', 'premium', 'citrus'], 82, 'USA', 'Massachusetts'),
('WTR_HINT_WATERMELON', 'hint-watermelon', 'Hint Watermelon', 'Fruit-infused water with a hint of watermelon, no sweeteners or calories', 'flavored', 'popular', 'Hint', 'none', 'well', 5, 4.0, 473, ARRAY['pet'], NULL, NULL, NULL, NULL, NULL, NULL, 'Watermelon', false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'still', 'subtle', 'zero-calorie'], 80, 'USA', 'California'),
('WTR_HINT_BLACKBERRY', 'hint-blackberry', 'Hint Blackberry', 'Still water with a subtle hint of blackberry flavor, unsweetened', 'flavored', 'popular', 'Hint', 'none', 'well', 5, 4.0, 473, ARRAY['pet'], NULL, NULL, NULL, NULL, NULL, NULL, 'Blackberry', false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'still', 'subtle', 'zero-calorie'], 78, 'USA', 'California'),
('WTR_PELLEGRINO_ESSENZA_LEMON', 'san-pellegrino-essenza-lemon', 'San Pellegrino Essenza Lemon & Lemon Zest', 'Italian sparkling mineral water with natural lemon and lemon zest flavors', 'flavored', 'premium', 'San Pellegrino', 'added', 'mineral', 948, 5.6, 330, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Lemon', false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'premium', 'citrus', 'mineral'], 82, 'Italy', 'Lombardy'),
('WTR_PELLEGRINO_ESSENZA_CHERRY', 'san-pellegrino-essenza-cherry', 'San Pellegrino Essenza Dark Morello Cherry', 'Italian sparkling mineral water with dark morello cherry and pomegranate', 'flavored', 'premium', 'San Pellegrino', 'added', 'mineral', 948, 5.6, 330, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Dark Cherry', false, 0, 0, true, true, true, true, true, true, true, ARRAY['italian', 'premium', 'berry', 'mineral'], 78, 'Italy', 'Lombardy'),
('WTR_PERRIER_LIME', 'perrier-lime', 'Perrier Lime', 'Iconic French sparkling water with natural lime flavor', 'flavored', 'popular', 'Perrier', 'added', 'mineral', 475, 5.5, 330, ARRAY['can', 'glass'], NULL, NULL, NULL, NULL, NULL, NULL, 'Lime', false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'iconic', 'citrus', 'mineral'], 85, 'France', 'Occitanie'),
('WTR_PERRIER_GRAPEFRUIT', 'perrier-pink-grapefruit', 'Perrier Pink Grapefruit', 'French sparkling mineral water with pink grapefruit essence', 'flavored', 'popular', 'Perrier', 'added', 'mineral', 475, 5.5, 330, ARRAY['can', 'glass'], NULL, NULL, NULL, NULL, NULL, NULL, 'Pink Grapefruit', false, 0, 0, true, true, true, true, true, true, true, ARRAY['french', 'citrus', 'pink', 'mineral'], 82, 'France', 'Occitanie'),
('WTR_WATERLOO_PEACH', 'waterloo-peach', 'Waterloo Peach', 'Texas-based sparkling water with bold, authentic peach flavor', 'flavored', 'popular', 'Waterloo', 'added', 'well', 10, 4.2, 355, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Peach', false, 0, 0, true, true, true, true, true, true, true, ARRAY['american', 'texas', 'bold-flavor', 'zero-calorie'], 78, 'USA', 'Texas'),
('WTR_SANZO_YUZU', 'sanzo-yuzu', 'Sanzo Yuzu', 'Asian-inspired sparkling water with real yuzu juice, unique citrus flavor', 'flavored', 'premium', 'Sanzo', 'added', 'well', 12, 3.8, 355, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Yuzu', true, 10, 2, true, true, true, true, true, true, true, ARRAY['asian-inspired', 'real-fruit', 'japanese-citrus', 'premium'], 72, 'USA', 'New York'),
('WTR_SANZO_LYCHEE', 'sanzo-lychee', 'Sanzo Lychee', 'Asian-inspired sparkling water with real lychee juice, delicate floral sweetness', 'flavored', 'premium', 'Sanzo', 'added', 'well', 12, 3.8, 355, ARRAY['can'], NULL, NULL, NULL, NULL, NULL, NULL, 'Lychee', true, 10, 2, true, true, true, true, true, true, true, ARRAY['asian-inspired', 'real-fruit', 'tropical', 'premium'], 70, 'USA', 'New York')

ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    status = EXCLUDED.status,
    brand = EXCLUDED.brand,
    carbonation = EXCLUDED.carbonation,
    source_type = EXCLUDED.source_type,
    tds_mg_l = EXCLUDED.tds_mg_l,
    ph_level = EXCLUDED.ph_level,
    serving_size_ml = EXCLUDED.serving_size_ml,
    bottle_types = EXCLUDED.bottle_types,
    calcium_mg_l = EXCLUDED.calcium_mg_l,
    magnesium_mg_l = EXCLUDED.magnesium_mg_l,
    sodium_mg_l = EXCLUDED.sodium_mg_l,
    potassium_mg_l = EXCLUDED.potassium_mg_l,
    bicarbonate_mg_l = EXCLUDED.bicarbonate_mg_l,
    silica_mg_l = EXCLUDED.silica_mg_l,
    flavor = EXCLUDED.flavor,
    has_real_fruit = EXCLUDED.has_real_fruit,
    calories_per_serving = EXCLUDED.calories_per_serving,
    sugar_g = EXCLUDED.sugar_g,
    tags = EXCLUDED.tags,
    popularity = EXCLUDED.popularity,
    origin_country = EXCLUDED.origin_country,
    origin_region = EXCLUDED.origin_region,
    updated_at = NOW();

-- Verify count
SELECT COUNT(*) as total_waters FROM waters;
