/**
 * GUDBRO Pizza Ingredients Database
 *
 * Comprehensive ingredient list for pizza preparation including:
 * - Dough components
 * - Sauces & bases
 * - Cheeses
 * - Meats & proteins
 * - Vegetables & toppings
 * - Herbs & seasonings
 * - Premium/gourmet ingredients
 *
 * All ingredients have Sistema 5 Dimensioni data for allergen computation
 */

import type { IngredientMaster } from '../../types';

export const pizzaIngredients: IngredientMaster[] = [
  // ============================================================================
  // DOUGH INGREDIENTS
  // ============================================================================
  {
    id: 'ING_PIZZA_FLOUR_00',
    slug: 'pizza-flour-00',
    name: {
      en: '00 Pizza Flour',
      it: 'Farina 00 per Pizza',
      vi: 'Bột Pizza 00',
    },
    description: {
      en: 'Fine Italian flour for Neapolitan pizza dough',
      it: 'Farina italiana fine per impasto pizza napoletana',
    },
    category: { main: 'baking', sub: 'flour' },
    allergens: { gluten: true, wheat: true },
    intolerances: { gluten: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: false,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 11, carbs_g: 73, fat_g: 1, calories_kcal: 340 },
    version: 1,
  },
  {
    id: 'ING_SEMOLINA_FLOUR',
    slug: 'semolina-flour',
    name: {
      en: 'Semolina Flour',
      it: 'Semola di Grano Duro',
      vi: 'Bột Semolina',
    },
    description: {
      en: 'Durum wheat semolina for Sicilian style pizza',
      it: 'Semola di grano duro per pizza siciliana',
    },
    category: { main: 'baking', sub: 'flour' },
    allergens: { gluten: true, wheat: true },
    intolerances: { gluten: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: false,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 13, carbs_g: 72, fat_g: 1, calories_kcal: 360 },
    version: 1,
  },
  {
    id: 'ING_YEAST_FRESH',
    slug: 'fresh-yeast',
    name: {
      en: 'Fresh Yeast',
      it: 'Lievito Fresco',
      vi: 'Men Tuoi',
    },
    category: { main: 'baking', sub: 'leavening' },
    allergens: {},
    intolerances: { yeast: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 8, carbs_g: 4, fat_g: 1, calories_kcal: 50 },
    version: 1,
  },

  // ============================================================================
  // SAUCES & BASES
  // ============================================================================
  {
    id: 'ING_SAN_MARZANO_TOMATOES',
    slug: 'san-marzano-tomatoes',
    name: {
      en: 'San Marzano Tomatoes DOP',
      it: 'Pomodori San Marzano DOP',
      vi: 'Ca Chua San Marzano DOP',
    },
    description: {
      en: 'Protected designation of origin tomatoes from Mount Vesuvius',
      it: 'Pomodori a denominazione di origine protetta del Vesuvio',
    },
    category: { main: 'vegetables', sub: 'tomatoes' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 4, fat_g: 0, calories_kcal: 18 },
    version: 1,
  },
  {
    id: 'ING_TOMATO_PASSATA',
    slug: 'tomato-passata',
    name: {
      en: 'Tomato Passata',
      it: 'Passata di Pomodoro',
      vi: 'Sot Ca Chua',
    },
    category: { main: 'sauces', sub: 'tomato' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 5, fat_g: 0, calories_kcal: 24 },
    version: 1,
  },
  {
    id: 'ING_BBQ_SAUCE',
    slug: 'bbq-sauce',
    name: {
      en: 'BBQ Sauce',
      it: 'Salsa BBQ',
      vi: 'Sot BBQ',
    },
    category: { main: 'sauces', sub: 'specialty' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 1 },
    nutrition: { protein_g: 0, carbs_g: 25, fat_g: 0, calories_kcal: 100 },
    version: 1,
  },
  {
    id: 'ING_PESTO_GENOVESE',
    slug: 'pesto-genovese',
    name: {
      en: 'Pesto Genovese',
      it: 'Pesto alla Genovese',
      vi: 'Sot Pesto Genovese',
    },
    description: {
      en: 'Traditional Ligurian basil pesto with pine nuts and Parmigiano',
      it: 'Pesto tradizionale ligure con pinoli e Parmigiano',
    },
    category: { main: 'sauces', sub: 'pesto' },
    allergens: { tree_nuts: true, milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: false,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 4, carbs_g: 3, fat_g: 50, calories_kcal: 480 },
    version: 1,
  },
  {
    id: 'ING_BUFFALO_SAUCE',
    slug: 'buffalo-sauce',
    name: {
      en: 'Buffalo Sauce',
      it: 'Salsa Buffalo',
      vi: 'Sot Buffalo',
    },
    category: { main: 'sauces', sub: 'hot' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 3 },
    nutrition: { protein_g: 0, carbs_g: 2, fat_g: 0, calories_kcal: 10 },
    version: 1,
  },

  // ============================================================================
  // CHEESES
  // ============================================================================
  {
    id: 'ING_MOZZARELLA_FIOR_DI_LATTE',
    slug: 'mozzarella-fior-di-latte',
    name: {
      en: 'Fior di Latte Mozzarella',
      it: 'Mozzarella Fior di Latte',
      vi: 'Pho Mai Mozzarella Fior di Latte',
    },
    description: {
      en: 'Fresh cow milk mozzarella for pizza',
      it: 'Mozzarella fresca di latte vaccino per pizza',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 22, carbs_g: 2, fat_g: 22, calories_kcal: 280 },
    version: 1,
  },
  {
    id: 'ING_MOZZARELLA_BUFALA_DOP',
    slug: 'mozzarella-bufala-dop',
    name: {
      en: 'Buffalo Mozzarella DOP',
      it: 'Mozzarella di Bufala Campana DOP',
      vi: 'Pho Mai Mozzarella Trau Nuoc',
    },
    description: {
      en: 'Protected designation buffalo milk mozzarella from Campania',
      it: 'Mozzarella di bufala a denominazione di origine protetta',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 18, carbs_g: 1, fat_g: 24, calories_kcal: 288 },
    version: 1,
  },
  {
    id: 'ING_BURRATA',
    slug: 'burrata',
    name: {
      en: 'Burrata',
      it: 'Burrata',
      vi: 'Pho Mai Burrata',
    },
    description: {
      en: 'Fresh Italian cheese with creamy stracciatella center',
      it: 'Formaggio fresco italiano con cuore cremoso di stracciatella',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 14, carbs_g: 2, fat_g: 26, calories_kcal: 300 },
    version: 1,
  },
  {
    id: 'ING_RICOTTA',
    slug: 'ricotta',
    name: {
      en: 'Ricotta Cheese',
      it: 'Ricotta',
      vi: 'Pho Mai Ricotta',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 11, carbs_g: 3, fat_g: 13, calories_kcal: 174 },
    version: 1,
  },
  {
    id: 'ING_GORGONZOLA_DOP',
    slug: 'gorgonzola-dop',
    name: {
      en: 'Gorgonzola DOP',
      it: 'Gorgonzola DOP',
      vi: 'Pho Mai Gorgonzola DOP',
    },
    description: {
      en: 'Italian blue cheese from Piedmont and Lombardy',
      it: 'Formaggio erborinato italiano del Piemonte e Lombardia',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 21, carbs_g: 0, fat_g: 29, calories_kcal: 353 },
    version: 1,
  },
  {
    id: 'ING_PARMIGIANO_REGGIANO_DOP',
    slug: 'parmigiano-reggiano-dop',
    name: {
      en: 'Parmigiano Reggiano DOP',
      it: 'Parmigiano Reggiano DOP',
      vi: 'Pho Mai Parmesan DOP',
    },
    description: {
      en: 'King of cheeses, aged Italian hard cheese',
      it: 'Re dei formaggi, formaggio stagionato italiano',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: false }, // Very low lactose due to aging
    dietary_restrictions: {
      vegan: false,
      vegetarian: false, // Contains animal rennet
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 36, carbs_g: 0, fat_g: 26, calories_kcal: 392 },
    version: 1,
  },
  {
    id: 'ING_PECORINO_ROMANO_DOP',
    slug: 'pecorino-romano-dop',
    name: {
      en: 'Pecorino Romano DOP',
      it: 'Pecorino Romano DOP',
      vi: 'Pho Mai Pecorino Romano',
    },
    description: {
      en: 'Aged sheep milk cheese from Lazio',
      it: 'Formaggio stagionato di pecora del Lazio',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: false },
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 32, carbs_g: 0, fat_g: 27, calories_kcal: 387 },
    version: 1,
  },
  {
    id: 'ING_PROVOLONE',
    slug: 'provolone',
    name: {
      en: 'Provolone',
      it: 'Provolone',
      vi: 'Pho Mai Provolone',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 26, carbs_g: 2, fat_g: 28, calories_kcal: 352 },
    version: 1,
  },
  {
    id: 'ING_SCAMORZA',
    slug: 'scamorza',
    name: {
      en: 'Scamorza',
      it: 'Scamorza',
      vi: 'Pho Mai Scamorza',
    },
    description: {
      en: 'Italian stretched curd cheese, similar to mozzarella but drier',
      it: 'Formaggio italiano a pasta filata, simile alla mozzarella ma più asciutto',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 25, carbs_g: 1, fat_g: 26, calories_kcal: 334 },
    version: 1,
  },
  {
    id: 'ING_FETA',
    slug: 'feta-cheese',
    name: {
      en: 'Feta Cheese',
      it: 'Feta',
      vi: 'Pho Mai Feta',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 14, carbs_g: 4, fat_g: 21, calories_kcal: 264 },
    version: 1,
  },
  {
    id: 'ING_GOAT_CHEESE',
    slug: 'goat-cheese',
    name: {
      en: 'Goat Cheese',
      it: 'Formaggio di Capra',
      vi: 'Pho Mai De',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 22, carbs_g: 1, fat_g: 30, calories_kcal: 364 },
    version: 1,
  },
  {
    id: 'ING_VEGAN_MOZZARELLA',
    slug: 'vegan-mozzarella',
    name: {
      en: 'Vegan Mozzarella',
      it: 'Mozzarella Vegana',
      vi: 'Pho Mai Mozzarella Chay',
    },
    category: { main: 'vegan', sub: 'cheese-alternative' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 7, fat_g: 22, calories_kcal: 230 },
    version: 1,
  },

  // ============================================================================
  // MEATS & PROTEINS
  // ============================================================================
  {
    id: 'ING_PEPPERONI',
    slug: 'pepperoni',
    name: {
      en: 'Pepperoni',
      it: 'Pepperoni Americano',
      vi: 'Xuc Xich Pepperoni',
    },
    description: {
      en: 'American-style spicy cured salami',
      it: 'Salame americano piccante stagionato',
    },
    category: { main: 'meat', sub: 'cured' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 2 },
    nutrition: { protein_g: 23, carbs_g: 0, fat_g: 44, calories_kcal: 494 },
    version: 1,
  },
  {
    id: 'ING_PROSCIUTTO_CRUDO_DOP',
    slug: 'prosciutto-crudo-dop',
    name: {
      en: 'Prosciutto Crudo DOP',
      it: 'Prosciutto Crudo DOP',
      vi: 'Thit Heo Muoi Prosciutto',
    },
    description: {
      en: 'Italian dry-cured ham (Parma or San Daniele)',
      it: 'Prosciutto stagionato italiano (Parma o San Daniele)',
    },
    category: { main: 'meat', sub: 'cured' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 26, carbs_g: 0, fat_g: 18, calories_kcal: 270 },
    version: 1,
  },
  {
    id: 'ING_PROSCIUTTO_COTTO',
    slug: 'prosciutto-cotto',
    name: {
      en: 'Cooked Ham',
      it: 'Prosciutto Cotto',
      vi: 'Thit Heo Chin',
    },
    category: { main: 'meat', sub: 'cured' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 21, carbs_g: 1, fat_g: 7, calories_kcal: 145 },
    version: 1,
  },
  {
    id: 'ING_SALAME_PICCANTE',
    slug: 'salame-piccante',
    name: {
      en: 'Spicy Salami',
      it: 'Salame Piccante',
      vi: 'Xuc Xich Y Cay',
    },
    category: { main: 'meat', sub: 'cured' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 2 },
    nutrition: { protein_g: 22, carbs_g: 2, fat_g: 41, calories_kcal: 472 },
    version: 1,
  },
  {
    id: 'ING_NDUJA',
    slug: 'nduja',
    name: {
      en: 'Nduja',
      it: 'Nduja Calabrese',
      vi: 'Xuc Xich Nduja',
    },
    description: {
      en: 'Spicy spreadable Calabrian salami',
      it: 'Salame spalmabile piccante calabrese',
    },
    category: { main: 'meat', sub: 'cured' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 4 },
    nutrition: { protein_g: 20, carbs_g: 1, fat_g: 43, calories_kcal: 470 },
    version: 1,
  },
  {
    id: 'ING_MORTADELLA',
    slug: 'mortadella',
    name: {
      en: 'Mortadella',
      it: 'Mortadella Bologna IGP',
      vi: 'Thit Nguoi Mortadella',
    },
    category: { main: 'meat', sub: 'cured' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: false, // Contains pistachios
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 14, carbs_g: 2, fat_g: 25, calories_kcal: 288 },
    version: 1,
  },
  {
    id: 'ING_SAUSAGE_ITALIAN',
    slug: 'italian-sausage',
    name: {
      en: 'Italian Sausage',
      it: 'Salsiccia Italiana',
      vi: 'Xuc Xich Y',
    },
    category: { main: 'meat', sub: 'sausage' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 1 },
    nutrition: { protein_g: 16, carbs_g: 2, fat_g: 28, calories_kcal: 320 },
    version: 1,
  },
  {
    id: 'ING_BACON',
    slug: 'bacon',
    name: {
      en: 'Bacon',
      it: 'Bacon',
      vi: 'Thit Xong Khoi',
    },
    category: { main: 'meat', sub: 'cured' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 37, carbs_g: 1, fat_g: 42, calories_kcal: 541 },
    version: 1,
  },
  {
    id: 'ING_GUANCIALE',
    slug: 'guanciale',
    name: {
      en: 'Guanciale',
      it: 'Guanciale',
      vi: 'Thit Ma Heo Muoi',
    },
    description: {
      en: 'Italian cured pork jowl',
      it: 'Guancia di maiale stagionata italiana',
    },
    category: { main: 'meat', sub: 'cured' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 10, carbs_g: 0, fat_g: 69, calories_kcal: 655 },
    version: 1,
  },
  {
    id: 'ING_CHICKEN_GRILLED',
    slug: 'grilled-chicken',
    name: {
      en: 'Grilled Chicken',
      it: 'Pollo alla Griglia',
      vi: 'Ga Nuong',
    },
    category: { main: 'meat', sub: 'poultry' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 31, carbs_g: 0, fat_g: 4, calories_kcal: 165 },
    version: 1,
  },
  {
    id: 'ING_GROUND_BEEF',
    slug: 'ground-beef',
    name: {
      en: 'Ground Beef',
      it: 'Carne Macinata',
      vi: 'Thit Bo Xay',
    },
    category: { main: 'meat', sub: 'beef' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 26, carbs_g: 0, fat_g: 15, calories_kcal: 250 },
    version: 1,
  },
  {
    id: 'ING_ANCHOVIES',
    slug: 'anchovies',
    name: {
      en: 'Anchovies',
      it: 'Acciughe',
      vi: 'Ca Com',
    },
    category: { main: 'seafood', sub: 'fish' },
    allergens: { fish: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 29, carbs_g: 0, fat_g: 10, calories_kcal: 210 },
    version: 1,
  },
  {
    id: 'ING_TUNA',
    slug: 'tuna',
    name: {
      en: 'Tuna',
      it: 'Tonno',
      vi: 'Ca Ngu',
    },
    category: { main: 'seafood', sub: 'fish' },
    allergens: { fish: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 30, carbs_g: 0, fat_g: 1, calories_kcal: 130 },
    version: 1,
  },
  {
    id: 'ING_SHRIMP',
    slug: 'shrimp',
    name: {
      en: 'Shrimp',
      it: 'Gamberi',
      vi: 'Tom',
    },
    category: { main: 'seafood', sub: 'shellfish' },
    allergens: { shellfish: true, crustaceans: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 24, carbs_g: 0, fat_g: 1, calories_kcal: 99 },
    version: 1,
  },

  // ============================================================================
  // VEGETABLES & TOPPINGS
  // ============================================================================
  {
    id: 'ING_MUSHROOMS_CHAMPIGNON',
    slug: 'champignon-mushrooms',
    name: {
      en: 'Champignon Mushrooms',
      it: 'Funghi Champignon',
      vi: 'Nam Mo',
    },
    category: { main: 'vegetables', sub: 'mushrooms' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 3, fat_g: 0, calories_kcal: 22 },
    version: 1,
  },
  {
    id: 'ING_MUSHROOMS_PORCINI',
    slug: 'porcini-mushrooms',
    name: {
      en: 'Porcini Mushrooms',
      it: 'Funghi Porcini',
      vi: 'Nam Porcini',
    },
    description: {
      en: 'Premium Italian wild mushrooms',
      it: 'Funghi selvatici italiani pregiati',
    },
    category: { main: 'vegetables', sub: 'mushrooms' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 5, carbs_g: 7, fat_g: 0, calories_kcal: 40 },
    version: 1,
  },
  {
    id: 'ING_ARTICHOKES',
    slug: 'artichokes',
    name: {
      en: 'Artichokes',
      it: 'Carciofi',
      vi: 'Atiso',
    },
    category: { main: 'vegetables', sub: 'artichoke' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 11, fat_g: 0, calories_kcal: 47 },
    version: 1,
  },
  {
    id: 'ING_OLIVES_BLACK',
    slug: 'black-olives',
    name: {
      en: 'Black Olives',
      it: 'Olive Nere',
      vi: 'O Liu Den',
    },
    category: { main: 'vegetables', sub: 'olives' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 6, fat_g: 11, calories_kcal: 115 },
    version: 1,
  },
  {
    id: 'ING_OLIVES_GREEN',
    slug: 'green-olives',
    name: {
      en: 'Green Olives',
      it: 'Olive Verdi',
      vi: 'O Liu Xanh',
    },
    category: { main: 'vegetables', sub: 'olives' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 4, fat_g: 15, calories_kcal: 145 },
    version: 1,
  },
  {
    id: 'ING_BELL_PEPPER_RED',
    slug: 'red-bell-pepper',
    name: {
      en: 'Red Bell Pepper',
      it: 'Peperone Rosso',
      vi: 'Ot Chuong Do',
    },
    category: { main: 'vegetables', sub: 'peppers' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 6, fat_g: 0, calories_kcal: 31 },
    version: 1,
  },
  {
    id: 'ING_BELL_PEPPER_YELLOW',
    slug: 'yellow-bell-pepper',
    name: {
      en: 'Yellow Bell Pepper',
      it: 'Peperone Giallo',
      vi: 'Ot Chuong Vang',
    },
    category: { main: 'vegetables', sub: 'peppers' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 6, fat_g: 0, calories_kcal: 27 },
    version: 1,
  },
  {
    id: 'ING_JALAPENO',
    slug: 'jalapeno',
    name: {
      en: 'Jalapeno Pepper',
      it: 'Peperoncino Jalapeno',
      vi: 'Ot Jalapeno',
    },
    category: { main: 'vegetables', sub: 'peppers' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 3 },
    nutrition: { protein_g: 1, carbs_g: 4, fat_g: 0, calories_kcal: 28 },
    version: 1,
  },
  {
    id: 'ING_PEPERONCINO',
    slug: 'peperoncino',
    name: {
      en: 'Italian Hot Pepper',
      it: 'Peperoncino',
      vi: 'Ot Cay Y',
    },
    category: { main: 'vegetables', sub: 'peppers' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 4 },
    nutrition: { protein_g: 2, carbs_g: 10, fat_g: 0, calories_kcal: 40 },
    version: 1,
  },
  {
    id: 'ING_ONION_RED',
    slug: 'red-onion',
    name: {
      en: 'Red Onion',
      it: 'Cipolla Rossa',
      vi: 'Hanh Tay Do',
    },
    category: { main: 'vegetables', sub: 'onions' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 9, fat_g: 0, calories_kcal: 40 },
    version: 1,
  },
  {
    id: 'ING_ONION_CARAMELIZED',
    slug: 'caramelized-onion',
    name: {
      en: 'Caramelized Onions',
      it: 'Cipolle Caramellate',
      vi: 'Hanh Tay Caramel',
    },
    category: { main: 'vegetables', sub: 'onions' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 12, fat_g: 3, calories_kcal: 75 },
    version: 1,
  },
  {
    id: 'ING_SPINACH',
    slug: 'spinach',
    name: {
      en: 'Spinach',
      it: 'Spinaci',
      vi: 'Rau Chan Vit',
    },
    category: { main: 'vegetables', sub: 'leafy' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 4, fat_g: 0, calories_kcal: 23 },
    version: 1,
  },
  {
    id: 'ING_ARUGULA',
    slug: 'arugula',
    name: {
      en: 'Arugula',
      it: 'Rucola',
      vi: 'Rau Rocket',
    },
    category: { main: 'vegetables', sub: 'leafy' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 1 },
    nutrition: { protein_g: 3, carbs_g: 4, fat_g: 1, calories_kcal: 25 },
    version: 1,
  },
  {
    id: 'ING_EGGPLANT',
    slug: 'eggplant',
    name: {
      en: 'Eggplant',
      it: 'Melanzane',
      vi: 'Ca Tim',
    },
    category: { main: 'vegetables', sub: 'nightshade' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 6, fat_g: 0, calories_kcal: 25 },
    version: 1,
  },
  {
    id: 'ING_ZUCCHINI',
    slug: 'zucchini',
    name: {
      en: 'Zucchini',
      it: 'Zucchine',
      vi: 'Bi Ngoi',
    },
    category: { main: 'vegetables', sub: 'squash' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 3, fat_g: 0, calories_kcal: 17 },
    version: 1,
  },
  {
    id: 'ING_CHERRY_TOMATOES',
    slug: 'cherry-tomatoes',
    name: {
      en: 'Cherry Tomatoes',
      it: 'Pomodorini',
      vi: 'Ca Chua Bi',
    },
    category: { main: 'vegetables', sub: 'tomatoes' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 4, fat_g: 0, calories_kcal: 18 },
    version: 1,
  },
  {
    id: 'ING_SUN_DRIED_TOMATOES',
    slug: 'sun-dried-tomatoes',
    name: {
      en: 'Sun-Dried Tomatoes',
      it: 'Pomodori Secchi',
      vi: 'Ca Chua Phoi Kho',
    },
    category: { main: 'vegetables', sub: 'tomatoes' },
    allergens: {},
    intolerances: { sulphites: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 6, carbs_g: 24, fat_g: 3, calories_kcal: 139 },
    version: 1,
  },
  {
    id: 'ING_CORN',
    slug: 'corn',
    name: {
      en: 'Sweet Corn',
      it: 'Mais',
      vi: 'Bap Ngot',
    },
    category: { main: 'vegetables', sub: 'corn' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 19, fat_g: 1, calories_kcal: 86 },
    version: 1,
  },
  {
    id: 'ING_PINEAPPLE',
    slug: 'pineapple',
    name: {
      en: 'Pineapple',
      it: 'Ananas',
      vi: 'Dua',
    },
    category: { main: 'fruits', sub: 'tropical' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 13, fat_g: 0, calories_kcal: 50 },
    version: 1,
  },
  {
    id: 'ING_CAPERS',
    slug: 'capers',
    name: {
      en: 'Capers',
      it: 'Capperi',
      vi: 'Nut Bao Cap',
    },
    category: { main: 'vegetables', sub: 'preserved' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 2, carbs_g: 5, fat_g: 1, calories_kcal: 23 },
    version: 1,
  },

  // ============================================================================
  // HERBS & SEASONINGS
  // ============================================================================
  {
    id: 'ING_BASIL_FRESH',
    slug: 'fresh-basil',
    name: {
      en: 'Fresh Basil',
      it: 'Basilico Fresco',
      vi: 'Hung Que Tuoi',
    },
    category: { main: 'herbs', sub: 'basil' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 3, fat_g: 1, calories_kcal: 23 },
    version: 1,
  },
  {
    id: 'ING_OREGANO',
    slug: 'oregano',
    name: {
      en: 'Oregano',
      it: 'Origano',
      vi: 'La Oregano',
    },
    category: { main: 'herbs', sub: 'dried' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 9, carbs_g: 69, fat_g: 4, calories_kcal: 265 },
    version: 1,
  },
  {
    id: 'ING_GARLIC',
    slug: 'garlic',
    name: {
      en: 'Garlic',
      it: 'Aglio',
      vi: 'Toi',
    },
    category: { main: 'vegetables', sub: 'allium' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 1 },
    nutrition: { protein_g: 6, carbs_g: 33, fat_g: 0, calories_kcal: 149 },
    version: 1,
  },
  {
    id: 'ING_ROSEMARY',
    slug: 'rosemary',
    name: {
      en: 'Rosemary',
      it: 'Rosmarino',
      vi: 'Huong Thao',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 21, fat_g: 6, calories_kcal: 131 },
    version: 1,
  },

  // ============================================================================
  // PREMIUM INGREDIENTS
  // ============================================================================
  {
    id: 'ING_TRUFFLE_BLACK',
    slug: 'black-truffle',
    name: {
      en: 'Black Truffle',
      it: 'Tartufo Nero',
      vi: 'Nam Truffle Den',
    },
    description: {
      en: 'Precious black truffle from Umbria or Piedmont',
      it: 'Prezioso tartufo nero dell\'Umbria o Piemonte',
    },
    category: { main: 'premium', sub: 'truffle' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 6, carbs_g: 13, fat_g: 0, calories_kcal: 70 },
    version: 1,
  },
  {
    id: 'ING_TRUFFLE_OIL',
    slug: 'truffle-oil',
    name: {
      en: 'Truffle Oil',
      it: 'Olio al Tartufo',
      vi: 'Dau Truffle',
    },
    category: { main: 'oils', sub: 'flavored' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 0, carbs_g: 0, fat_g: 100, calories_kcal: 884 },
    version: 1,
  },
  {
    id: 'ING_PISTACHIO',
    slug: 'pistachio',
    name: {
      en: 'Pistachio',
      it: 'Pistacchio',
      vi: 'Hat De Cuoi',
    },
    category: { main: 'nuts', sub: 'pistachio' },
    allergens: { tree_nuts: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: false,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 20, carbs_g: 28, fat_g: 45, calories_kcal: 560 },
    version: 1,
  },
  {
    id: 'ING_PINE_NUTS',
    slug: 'pine-nuts',
    name: {
      en: 'Pine Nuts',
      it: 'Pinoli',
      vi: 'Hat Thong',
    },
    category: { main: 'nuts', sub: 'pine' },
    allergens: { tree_nuts: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: false,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 14, carbs_g: 13, fat_g: 68, calories_kcal: 673 },
    version: 1,
  },
  {
    id: 'ING_HONEY',
    slug: 'honey',
    name: {
      en: 'Honey',
      it: 'Miele',
      vi: 'Mat Ong',
    },
    category: { main: 'sweeteners', sub: 'natural' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 0, carbs_g: 82, fat_g: 0, calories_kcal: 304 },
    version: 1,
  },
  {
    id: 'ING_BALSAMIC_GLAZE',
    slug: 'balsamic-glaze',
    name: {
      en: 'Balsamic Glaze',
      it: 'Glassa Balsamica',
      vi: 'Nuoc Sot Balsamic',
    },
    category: { main: 'condiments', sub: 'vinegar' },
    allergens: {},
    intolerances: { sulphites: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 0, carbs_g: 47, fat_g: 0, calories_kcal: 188 },
    version: 1,
  },

  // ============================================================================
  // OILS
  // ============================================================================
  {
    id: 'ING_OLIVE_OIL_EVO',
    slug: 'extra-virgin-olive-oil',
    name: {
      en: 'Extra Virgin Olive Oil',
      it: 'Olio Extra Vergine di Oliva',
      vi: 'Dau Olive Nguyen Chat',
    },
    category: { main: 'oils', sub: 'olive' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 0, carbs_g: 0, fat_g: 100, calories_kcal: 884 },
    version: 1,
  },

  // ============================================================================
  // EGGS
  // ============================================================================
  {
    id: 'ING_EGG',
    slug: 'egg',
    name: {
      en: 'Egg',
      it: 'Uovo',
      vi: 'Trung',
    },
    category: { main: 'eggs', sub: 'chicken' },
    allergens: { eggs: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 13, carbs_g: 1, fat_g: 11, calories_kcal: 155 },
    version: 1,
  },
];

export default pizzaIngredients;
