packages:
  - 'apps/*'
  - 'apps/coffeeshop/*'
  - 'apps/gym/*'
  - 'apps/laundry/*'
  - 'apps/wellness/*'
  - 'apps/rentals/*'
  - 'apps/waiter'
  - 'shared/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - 'core-js'
  - 'esbuild'
  - 'prisma'
  - 'protobufjs'
  - 'sharp'
  - 'supabase'
  - 'unrs-resolver'
