-- ============================================
-- CHINESE DATA IMPORT
-- ============================================
-- Total: 73 Chinese dishes
-- stir-fries.ts: 10
-- noodles.ts: 8
-- dim-sum.ts: 10
-- rice-dishes.ts: 6
-- roasted.ts: 6
-- soups.ts: 7
-- braised.ts: 6
-- seafood.ts: 7
-- appetizers.ts: 7
-- desserts.ts: 6
-- ============================================

BEGIN;

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_KUNG_PAO_CHICKEN',
  'kung-pao-chicken',
  'Kung Pao Chicken',
  'Spicy Sichuan stir-fry with chicken, peanuts, and dried chilies in a savory-sweet sauce',
  'Gong Bao Ji Ding',
  '宫保鸡丁',
  'stir_fries',
  'classic',
  'sichuan',
  'sichuan',
  'chicken',
  'stir_fried',
  false,
  false,
  ARRAY['ING_CHICKEN_THIGH', 'ING_PEANUTS', 'ING_DRIED_CHILIES', 'ING_SICHUAN_PEPPERCORN', 'ING_SOY_SAUCE', 'ING_RICE_VINEGAR', 'ING_GARLIC', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_SHAOXING_WINE'],
  ARRAY['peanuts', 'soy', 'gluten'],
  false,
  true,
  false,
  false,
  false,
  true,
  false,
  380,
  28,
  18,
  22,
  4,
  ARRAY['sichuan', 'spicy', 'peanuts', 'classic'],
  95
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_MAPO_TOFU',
  'mapo-tofu',
  'Mapo Tofu',
  'Silky tofu in spicy, numbing sauce with fermented black beans and ground pork',
  'Ma Po Dou Fu',
  '麻婆豆腐',
  'stir_fries',
  'classic',
  'sichuan',
  'sichuan',
  'tofu',
  'stir_fried',
  false,
  false,
  ARRAY['ING_TOFU_SILKEN', 'ING_PORK_GROUND', 'ING_DOUBANJIANG', 'ING_SICHUAN_PEPPERCORN', 'ING_FERMENTED_BLACK_BEANS', 'ING_GARLIC', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_CHILI_OIL', 'ING_SOY_SAUCE'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  320,
  18,
  12,
  24,
  5,
  ARRAY['sichuan', 'spicy', 'numbing', 'tofu'],
  90
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SWEET_SOUR_PORK',
  'sweet-and-sour-pork',
  'Sweet and Sour Pork',
  'Crispy battered pork pieces in tangy sweet and sour sauce with pineapple and bell peppers',
  'Gu Lao Rou',
  '咕噜肉',
  'stir_fries',
  'classic',
  'cantonese',
  'cantonese',
  'pork',
  'deep_fried',
  false,
  false,
  ARRAY['ING_PORK_LOIN', 'ING_PINEAPPLE', 'ING_BELL_PEPPER', 'ING_ONION', 'ING_KETCHUP', 'ING_RICE_VINEGAR', 'ING_SUGAR', 'ING_CORNSTARCH', 'ING_EGG', 'ING_SOY_SAUCE'],
  ARRAY['egg', 'soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  450,
  22,
  45,
  20,
  0,
  ARRAY['cantonese', 'sweet', 'crispy', 'classic'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_BEEF_BROCCOLI',
  'beef-and-broccoli',
  'Beef and Broccoli',
  'Tender sliced beef stir-fried with crisp broccoli in savory oyster sauce',
  'Xi Lan Hua Niu Rou',
  '西兰花牛肉',
  'stir_fries',
  'popular',
  'cantonese',
  'american_chinese',
  'beef',
  'stir_fried',
  false,
  false,
  ARRAY['ING_BEEF_FLANK', 'ING_BROCCOLI', 'ING_OYSTER_SAUCE', 'ING_SOY_SAUCE', 'ING_GARLIC', 'ING_GINGER', 'ING_CORNSTARCH', 'ING_SESAME_OIL', 'ING_SHAOXING_WINE'],
  ARRAY['shellfish', 'soy', 'gluten', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  350,
  30,
  15,
  18,
  0,
  ARRAY['american-chinese', 'beef', 'broccoli'],
  92
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_MONGOLIAN_BEEF',
  'mongolian-beef',
  'Mongolian Beef',
  'Crispy beef strips in sweet and savory sauce with green onions',
  'Meng Gu Niu Rou',
  '蒙古牛肉',
  'stir_fries',
  'popular',
  'northeastern',
  'american_chinese',
  'beef',
  'stir_fried',
  false,
  false,
  ARRAY['ING_BEEF_FLANK', 'ING_GREEN_ONION', 'ING_SOY_SAUCE', 'ING_BROWN_SUGAR', 'ING_GARLIC', 'ING_GINGER', 'ING_CORNSTARCH', 'ING_VEGETABLE_OIL', 'ING_HOISIN_SAUCE'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  420,
  28,
  32,
  20,
  1,
  ARRAY['american-chinese', 'sweet', 'crispy'],
  85
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_TWICE_COOKED_PORK',
  'twice-cooked-pork',
  'Twice Cooked Pork',
  'Sichuan classic with boiled then stir-fried pork belly, leeks, and fermented bean paste',
  'Hui Guo Rou',
  '回锅肉',
  'stir_fries',
  'classic',
  'sichuan',
  'sichuan',
  'pork',
  'stir_fried',
  false,
  false,
  ARRAY['ING_PORK_BELLY', 'ING_LEEK', 'ING_DOUBANJIANG', 'ING_FERMENTED_BLACK_BEANS', 'ING_GARLIC', 'ING_GINGER', 'ING_SOY_SAUCE', 'ING_SHAOXING_WINE', 'ING_SUGAR'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  480,
  20,
  12,
  38,
  3,
  ARRAY['sichuan', 'pork-belly', 'classic'],
  82
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_MU_SHU_PORK',
  'mu-shu-pork',
  'Mu Shu Pork',
  'Stir-fried shredded pork with wood ear mushrooms, eggs, and vegetables, served with thin pancakes',
  'Mu Xu Rou',
  '木须肉',
  'stir_fries',
  'classic',
  'beijing',
  'beijing',
  'pork',
  'stir_fried',
  false,
  false,
  ARRAY['ING_PORK_LOIN', 'ING_WOOD_EAR_MUSHROOMS', 'ING_EGG', 'ING_CABBAGE', 'ING_BAMBOO_SHOOTS', 'ING_HOISIN_SAUCE', 'ING_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_MANDARIN_PANCAKES'],
  ARRAY['egg', 'soy', 'gluten', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  380,
  24,
  28,
  18,
  0,
  ARRAY['beijing', 'pancakes', 'classic'],
  78
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_GENERAL_TSO_CHICKEN',
  'general-tso-chicken',
  'General Tso',
  'Crispy fried chicken in sweet, slightly spicy sauce - American-Chinese favorite',
  'Zuo Zong Tang Ji',
  '左宗棠鸡',
  'stir_fries',
  'popular',
  'hunan',
  'american_chinese',
  'chicken',
  'deep_fried',
  false,
  false,
  ARRAY['ING_CHICKEN_THIGH', 'ING_DRIED_CHILIES', 'ING_SOY_SAUCE', 'ING_RICE_VINEGAR', 'ING_SUGAR', 'ING_GARLIC', 'ING_GINGER', 'ING_CORNSTARCH', 'ING_EGG', 'ING_SESAME_SEEDS'],
  ARRAY['egg', 'soy', 'gluten', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  520,
  26,
  48,
  24,
  2,
  ARRAY['american-chinese', 'crispy', 'sweet'],
  94
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_ORANGE_CHICKEN',
  'orange-chicken',
  'Orange Chicken',
  'Crispy battered chicken in tangy orange-flavored sauce',
  'Chen Pi Ji',
  '陈皮鸡',
  'stir_fries',
  'popular',
  'cantonese',
  'american_chinese',
  'chicken',
  'deep_fried',
  false,
  false,
  ARRAY['ING_CHICKEN_BREAST', 'ING_ORANGE_ZEST', 'ING_ORANGE_JUICE', 'ING_SOY_SAUCE', 'ING_RICE_VINEGAR', 'ING_SUGAR', 'ING_GARLIC', 'ING_GINGER', 'ING_CORNSTARCH', 'ING_EGG'],
  ARRAY['egg', 'soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  490,
  24,
  52,
  20,
  1,
  ARRAY['american-chinese', 'orange', 'crispy'],
  93
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CASHEW_CHICKEN',
  'cashew-chicken',
  'Cashew Chicken',
  'Tender chicken stir-fried with roasted cashews and vegetables in savory sauce',
  'Yao Guo Ji Ding',
  '腰果鸡丁',
  'stir_fries',
  'popular',
  'cantonese',
  'cantonese',
  'chicken',
  'stir_fried',
  false,
  false,
  ARRAY['ING_CHICKEN_BREAST', 'ING_CASHEWS', 'ING_BELL_PEPPER', 'ING_CELERY', 'ING_ONION', 'ING_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_GARLIC', 'ING_GINGER', 'ING_SESAME_OIL'],
  ARRAY['tree_nuts', 'soy', 'gluten', 'shellfish', 'sesame'],
  false,
  true,
  false,
  false,
  false,
  true,
  false,
  420,
  28,
  22,
  26,
  0,
  ARRAY['cantonese', 'cashews', 'mild'],
  86
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CHOW_MEIN',
  'chow-mein',
  'Chow Mein',
  'Stir-fried egg noodles with vegetables and choice of protein in savory sauce',
  'Chao Mian',
  '炒面',
  'noodles',
  'classic',
  'cantonese',
  'cantonese',
  'mixed',
  'stir_fried',
  true,
  false,
  ARRAY['ING_EGG_NOODLES', 'ING_CABBAGE', 'ING_BEAN_SPROUTS', 'ING_CARROT', 'ING_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_SESAME_OIL', 'ING_GARLIC', 'ING_GINGER', 'ING_GREEN_ONION'],
  ARRAY['egg', 'gluten', 'soy', 'shellfish', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  450,
  18,
  58,
  16,
  0,
  ARRAY['noodles', 'stir-fried', 'classic'],
  92
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_LO_MEIN',
  'lo-mein',
  'Lo Mein',
  'Soft wheat noodles tossed with vegetables and meat in brown sauce',
  'Lao Mian',
  '捞面',
  'noodles',
  'classic',
  'cantonese',
  'american_chinese',
  'mixed',
  'stir_fried',
  true,
  false,
  ARRAY['ING_LO_MEIN_NOODLES', 'ING_CABBAGE', 'ING_CARROT', 'ING_MUSHROOM', 'ING_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_SESAME_OIL', 'ING_GARLIC', 'ING_GINGER'],
  ARRAY['gluten', 'soy', 'shellfish', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  480,
  16,
  62,
  18,
  0,
  ARRAY['noodles', 'american-chinese'],
  90
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_DAN_DAN_NOODLES',
  'dan-dan-noodles',
  'Dan Dan Noodles',
  'Sichuan street food classic with spicy sesame sauce, minced pork, and preserved vegetables',
  'Dan Dan Mian',
  '担担面',
  'noodles',
  'classic',
  'sichuan',
  'sichuan',
  'pork',
  'boiled',
  true,
  false,
  ARRAY['ING_WHEAT_NOODLES', 'ING_PORK_GROUND', 'ING_SESAME_PASTE', 'ING_CHILI_OIL', 'ING_SICHUAN_PEPPERCORN', 'ING_SOY_SAUCE', 'ING_YA_CAI', 'ING_GARLIC', 'ING_GREEN_ONION', 'ING_PEANUTS'],
  ARRAY['gluten', 'soy', 'sesame', 'peanuts'],
  false,
  true,
  false,
  false,
  false,
  false,
  false,
  520,
  22,
  48,
  28,
  4,
  ARRAY['sichuan', 'spicy', 'street-food'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_ZHAJIANG_NOODLES',
  'zhajiang-noodles',
  'Zha Jiang Mian',
  'Beijing-style noodles with thick fermented bean paste sauce and julienned vegetables',
  'Zha Jiang Mian',
  '炸酱面',
  'noodles',
  'classic',
  'beijing',
  'beijing',
  'pork',
  'boiled',
  true,
  false,
  ARRAY['ING_WHEAT_NOODLES', 'ING_PORK_GROUND', 'ING_SWEET_BEAN_PASTE', 'ING_CUCUMBER', 'ING_BEAN_SPROUTS', 'ING_RADISH', 'ING_SOY_SAUCE', 'ING_SHAOXING_WINE', 'ING_GARLIC'],
  ARRAY['gluten', 'soy'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  480,
  20,
  56,
  18,
  1,
  ARRAY['beijing', 'bean-paste', 'classic'],
  82
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_BEEF_NOODLE_SOUP',
  'beef-noodle-soup',
  'Taiwanese Beef Noodle Soup',
  'Rich braised beef shank soup with hand-pulled noodles and bok choy',
  'Niu Rou Mian',
  '牛肉面',
  'noodles',
  'signature',
  'taiwanese',
  'fusion',
  'beef',
  'braised',
  false,
  false,
  ARRAY['ING_BEEF_SHANK', 'ING_WHEAT_NOODLES', 'ING_BOK_CHOY', 'ING_STAR_ANISE', 'ING_SOY_SAUCE', 'ING_DOUBANJIANG', 'ING_GINGER', 'ING_GARLIC', 'ING_GREEN_ONION', 'ING_TOMATO'],
  ARRAY['gluten', 'soy'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  580,
  38,
  52,
  22,
  2,
  ARRAY['taiwanese', 'soup', 'beef'],
  90
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_LANZHOU_NOODLES',
  'lanzhou-hand-pulled-noodles',
  'Lanzhou Hand-Pulled Noodles',
  'Hand-pulled noodles in clear beef broth with tender beef slices and radish',
  'Lan Zhou La Mian',
  '兰州拉面',
  'noodles',
  'classic',
  'xinjiang',
  'fusion',
  'beef',
  'boiled',
  true,
  false,
  ARRAY['ING_HAND_PULLED_NOODLES', 'ING_BEEF_SLICES', 'ING_BEEF_BROTH', 'ING_WHITE_RADISH', 'ING_CHILI_OIL', 'ING_CILANTRO', 'ING_GREEN_ONION', 'ING_GARLIC'],
  ARRAY['gluten'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  450,
  28,
  48,
  16,
  2,
  ARRAY['lanzhou', 'hand-pulled', 'halal'],
  85
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_WONTON_NOODLES',
  'wonton-noodles',
  'Wonton Noodles',
  'Cantonese egg noodles with shrimp wontons in clear broth or dry with oyster sauce',
  'Yun Tun Mian',
  '云吞面',
  'noodles',
  'classic',
  'cantonese',
  'cantonese',
  'shrimp',
  'boiled',
  true,
  false,
  ARRAY['ING_EGG_NOODLES', 'ING_WONTONS', 'ING_SHRIMP', 'ING_PORK_GROUND', 'ING_CHICKEN_BROTH', 'ING_BOK_CHOY', 'ING_GREEN_ONION', 'ING_SESAME_OIL', 'ING_SOY_SAUCE'],
  ARRAY['shellfish', 'egg', 'gluten', 'soy', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  420,
  24,
  46,
  14,
  0,
  ARRAY['cantonese', 'wontons', 'soup'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SINGAPORE_NOODLES',
  'singapore-noodles',
  'Singapore Noodles',
  'Curry-flavored rice vermicelli with shrimp, char siu, and vegetables',
  'Xing Zhou Mi Fen',
  '星洲米粉',
  'noodles',
  'popular',
  'hong_kong',
  'fusion',
  'mixed',
  'stir_fried',
  true,
  false,
  ARRAY['ING_RICE_VERMICELLI', 'ING_SHRIMP', 'ING_CHAR_SIU', 'ING_EGG', 'ING_CURRY_POWDER', 'ING_BEAN_SPROUTS', 'ING_BELL_PEPPER', 'ING_ONION', 'ING_SOY_SAUCE', 'ING_SESAME_OIL'],
  ARRAY['shellfish', 'egg', 'soy', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  380,
  22,
  42,
  14,
  2,
  ARRAY['curry', 'rice-noodles', 'fusion'],
  84
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SIU_MAI',
  'siu-mai',
  'Siu Mai',
  'Open-topped pork and shrimp dumplings with a distinctive yellow wrapper',
  'Shao Mai',
  '烧卖',
  'dim_sum',
  'classic',
  'cantonese',
  'dim_sum',
  'pork',
  'steamed',
  false,
  true,
  ARRAY['ING_PORK_GROUND', 'ING_SHRIMP', 'ING_WONTON_WRAPPER', 'ING_SHIITAKE_MUSHROOM', 'ING_WATER_CHESTNUTS', 'ING_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_GINGER', 'ING_WHITE_PEPPER'],
  ARRAY['shellfish', 'gluten', 'soy', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  180,
  12,
  14,
  8,
  0,
  ARRAY['dim-sum', 'dumplings', 'classic'],
  95
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_HAR_GOW',
  'har-gow',
  'Har Gow',
  'Translucent crystal shrimp dumplings - the gold standard of dim sum',
  'Xia Jiao',
  '虾饺',
  'dim_sum',
  'signature',
  'cantonese',
  'dim_sum',
  'shrimp',
  'steamed',
  false,
  true,
  ARRAY['ING_SHRIMP', 'ING_WHEAT_STARCH', 'ING_TAPIOCA_STARCH', 'ING_BAMBOO_SHOOTS', 'ING_PORK_FAT', 'ING_SESAME_OIL', 'ING_WHITE_PEPPER', 'ING_SALT'],
  ARRAY['shellfish', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  150,
  10,
  12,
  6,
  0,
  ARRAY['dim-sum', 'shrimp', 'signature'],
  96
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CHAR_SIU_BAO',
  'char-siu-bao',
  'Char Siu Bao',
  'Fluffy steamed buns filled with sweet BBQ pork',
  'Cha Shao Bao',
  '叉烧包',
  'dim_sum',
  'classic',
  'cantonese',
  'dim_sum',
  'pork',
  'steamed',
  true,
  true,
  ARRAY['ING_CHAR_SIU', 'ING_FLOUR', 'ING_SUGAR', 'ING_YEAST', 'ING_OYSTER_SAUCE', 'ING_HOISIN_SAUCE', 'ING_SOY_SAUCE', 'ING_SESAME_OIL'],
  ARRAY['gluten', 'soy', 'shellfish', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  220,
  10,
  32,
  6,
  0,
  ARRAY['dim-sum', 'buns', 'bbq-pork'],
  94
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CHEUNG_FUN',
  'cheung-fun',
  'Cheung Fun',
  'Silky rice noodle rolls filled with shrimp, beef, or char siu, served with sweet soy',
  'Chang Fen',
  '肠粉',
  'dim_sum',
  'classic',
  'cantonese',
  'dim_sum',
  'shrimp',
  'steamed',
  true,
  true,
  ARRAY['ING_RICE_FLOUR', 'ING_SHRIMP', 'ING_SWEET_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_GREEN_ONION', 'ING_VEGETABLE_OIL'],
  ARRAY['shellfish', 'soy', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  160,
  8,
  22,
  4,
  0,
  ARRAY['dim-sum', 'rice-noodles', 'classic'],
  90
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_XIAOLONGBAO',
  'xiaolongbao',
  'Xiao Long Bao',
  'Delicate soup dumplings filled with pork and rich broth - Shanghai specialty',
  'Xiao Long Bao',
  '小笼包',
  'dim_sum',
  'signature',
  'jiangsu',
  'shanghai',
  'pork',
  'steamed',
  false,
  true,
  ARRAY['ING_PORK_GROUND', 'ING_PORK_ASPIC', 'ING_FLOUR', 'ING_GINGER', 'ING_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_SHAOXING_WINE', 'ING_SUGAR'],
  ARRAY['gluten', 'soy', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  200,
  10,
  20,
  10,
  0,
  ARRAY['shanghai', 'soup-dumplings', 'signature'],
  98
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_TURNIP_CAKE',
  'turnip-cake',
  'Lo Bak Go (Turnip Cake)',
  'Pan-fried radish cake with Chinese sausage and dried shrimp',
  'Luo Bo Gao',
  '萝卜糕',
  'dim_sum',
  'classic',
  'cantonese',
  'dim_sum',
  'pork',
  'stir_fried',
  true,
  true,
  ARRAY['ING_WHITE_RADISH', 'ING_RICE_FLOUR', 'ING_CHINESE_SAUSAGE', 'ING_DRIED_SHRIMP', 'ING_SHIITAKE_MUSHROOM', 'ING_GREEN_ONION', 'ING_WHITE_PEPPER', 'ING_SOY_SAUCE'],
  ARRAY['shellfish', 'soy'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  180,
  6,
  24,
  8,
  0,
  ARRAY['dim-sum', 'pan-fried', 'new-year'],
  85
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CHICKEN_FEET',
  'chicken-feet',
  'Feng Zhua (Chicken Feet)',
  'Braised chicken feet in black bean sauce - dim sum delicacy',
  'Feng Zhua',
  '凤爪',
  'dim_sum',
  'classic',
  'cantonese',
  'dim_sum',
  'chicken',
  'braised',
  false,
  true,
  ARRAY['ING_CHICKEN_FEET', 'ING_FERMENTED_BLACK_BEANS', 'ING_GARLIC', 'ING_CHILI', 'ING_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_SUGAR', 'ING_STAR_ANISE'],
  ARRAY['soy', 'gluten', 'shellfish'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  150,
  14,
  8,
  8,
  2,
  ARRAY['dim-sum', 'braised', 'delicacy'],
  75
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SPRING_ROLLS',
  'chinese-spring-rolls',
  'Chun Juan (Spring Rolls)',
  'Crispy fried rolls filled with vegetables and pork or shrimp',
  'Chun Juan',
  '春卷',
  'dim_sum',
  'classic',
  'cantonese',
  'cantonese',
  'pork',
  'deep_fried',
  true,
  true,
  ARRAY['ING_SPRING_ROLL_WRAPPERS', 'ING_PORK_GROUND', 'ING_CABBAGE', 'ING_CARROT', 'ING_BEAN_SPROUTS', 'ING_SHIITAKE_MUSHROOM', 'ING_SOY_SAUCE', 'ING_SESAME_OIL'],
  ARRAY['gluten', 'soy', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  220,
  8,
  22,
  12,
  0,
  ARRAY['dim-sum', 'fried', 'appetizer'],
  92
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_EGG_TART',
  'egg-tart',
  'Dan Tat (Egg Tart)',
  'Flaky pastry shell filled with silky sweet egg custard',
  'Dan Ta',
  '蛋挞',
  'dim_sum',
  'classic',
  'hong_kong',
  'dim_sum',
  'egg',
  'roasted',
  true,
  true,
  ARRAY['ING_EGG', 'ING_SUGAR', 'ING_MILK', 'ING_FLOUR', 'ING_BUTTER', 'ING_VANILLA'],
  ARRAY['egg', 'gluten', 'dairy'],
  false,
  false,
  true,
  false,
  true,
  true,
  true,
  180,
  4,
  22,
  10,
  0,
  ARRAY['dim-sum', 'dessert', 'pastry'],
  94
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_STEAMED_SPARE_RIBS',
  'steamed-spare-ribs',
  'Pai Gu (Steamed Spare Ribs)',
  'Tender pork ribs steamed with fermented black beans and garlic',
  'Dou Chi Zheng Pai Gu',
  '豆豉蒸排骨',
  'dim_sum',
  'classic',
  'cantonese',
  'dim_sum',
  'pork',
  'steamed',
  false,
  true,
  ARRAY['ING_PORK_SPARE_RIBS', 'ING_FERMENTED_BLACK_BEANS', 'ING_GARLIC', 'ING_CHILI', 'ING_SOY_SAUCE', 'ING_CORNSTARCH', 'ING_SHAOXING_WINE', 'ING_SUGAR'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  280,
  18,
  8,
  20,
  1,
  ARRAY['dim-sum', 'ribs', 'steamed'],
  86
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_FRIED_RICE',
  'chinese-fried-rice',
  'Yangzhou Fried Rice',
  'Classic fried rice with shrimp, char siu, eggs, and vegetables',
  'Yang Zhou Chao Fan',
  '扬州炒饭',
  'rice_dishes',
  'classic',
  'jiangsu',
  'shanghai',
  'mixed',
  'stir_fried',
  true,
  false,
  ARRAY['ING_JASMINE_RICE', 'ING_SHRIMP', 'ING_CHAR_SIU', 'ING_EGG', 'ING_GREEN_PEAS', 'ING_CARROT', 'ING_GREEN_ONION', 'ING_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_WHITE_PEPPER'],
  ARRAY['shellfish', 'egg', 'soy', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  480,
  22,
  58,
  18,
  0,
  ARRAY['fried-rice', 'classic', 'yangzhou'],
  95
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CLAYPOT_RICE',
  'claypot-rice',
  'Claypot Rice',
  'Rice cooked in clay pot with Chinese sausage, chicken, and crispy rice crust',
  'Bao Zai Fan',
  '煲仔饭',
  'rice_dishes',
  'signature',
  'cantonese',
  'cantonese',
  'chicken',
  'clay_pot',
  true,
  false,
  ARRAY['ING_JASMINE_RICE', 'ING_CHICKEN_THIGH', 'ING_CHINESE_SAUSAGE', 'ING_BOK_CHOY', 'ING_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_SESAME_OIL'],
  ARRAY['soy', 'shellfish', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  550,
  28,
  62,
  20,
  0,
  ARRAY['claypot', 'cantonese', 'crispy-rice'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CONGEE',
  'congee',
  'Congee (Rice Porridge)',
  'Silky rice porridge, often served with century egg and lean pork',
  'Zhou',
  '粥',
  'rice_dishes',
  'classic',
  'cantonese',
  'cantonese',
  'pork',
  'boiled',
  true,
  true,
  ARRAY['ING_JASMINE_RICE', 'ING_PORK_SLICES', 'ING_CENTURY_EGG', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_WHITE_PEPPER', 'ING_CHICKEN_BROTH'],
  ARRAY['egg', 'soy', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  280,
  16,
  38,
  8,
  0,
  ARRAY['porridge', 'comfort-food', 'breakfast'],
  85
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_HAINANESE_CHICKEN_RICE',
  'hainanese-chicken-rice',
  'Hainanese Chicken Rice',
  'Poached chicken served with fragrant rice cooked in chicken fat and broth',
  'Hai Nan Ji Fan',
  '海南鸡饭',
  'rice_dishes',
  'signature',
  'cantonese',
  'cantonese',
  'chicken',
  'boiled',
  true,
  false,
  ARRAY['ING_CHICKEN_WHOLE', 'ING_JASMINE_RICE', 'ING_CHICKEN_FAT', 'ING_GINGER', 'ING_GARLIC', 'ING_PANDAN_LEAVES', 'ING_CUCUMBER', 'ING_CHILI_SAUCE', 'ING_GINGER_SAUCE', 'ING_SOY_SAUCE'],
  ARRAY['soy'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  580,
  35,
  52,
  24,
  1,
  ARRAY['chicken-rice', 'hainanese', 'signature'],
  92
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_STICKY_RICE_LOTUS',
  'sticky-rice-lotus-leaf',
  'Lo Mai Gai',
  'Sticky rice with chicken, Chinese sausage, and mushrooms wrapped in lotus leaf',
  'Nuo Mi Ji',
  '糯米鸡',
  'rice_dishes',
  'classic',
  'cantonese',
  'dim_sum',
  'chicken',
  'steamed',
  false,
  true,
  ARRAY['ING_STICKY_RICE', 'ING_CHICKEN_THIGH', 'ING_CHINESE_SAUSAGE', 'ING_SHIITAKE_MUSHROOM', 'ING_LOTUS_LEAF', 'ING_DRIED_SHRIMP', 'ING_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_SESAME_OIL'],
  ARRAY['shellfish', 'soy', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  420,
  18,
  52,
  16,
  0,
  ARRAY['sticky-rice', 'dim-sum', 'lotus-leaf'],
  86
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_ZONGZI',
  'zongzi',
  'Zongzi (Sticky Rice Dumpling)',
  'Pyramid-shaped sticky rice wrapped in bamboo leaves with savory or sweet fillings',
  'Zong Zi',
  '粽子',
  'rice_dishes',
  'seasonal',
  'cantonese',
  'cantonese',
  'pork',
  'boiled',
  true,
  false,
  ARRAY['ING_STICKY_RICE', 'ING_PORK_BELLY', 'ING_SALTED_EGG_YOLK', 'ING_MUNG_BEANS', 'ING_BAMBOO_LEAVES', 'ING_SHIITAKE_MUSHROOM', 'ING_SOY_SAUCE', 'ING_FIVE_SPICE'],
  ARRAY['egg', 'soy'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  380,
  14,
  48,
  16,
  0,
  ARRAY['sticky-rice', 'dragon-boat', 'festival'],
  80
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_PEKING_DUCK',
  'peking-duck',
  'Peking Duck',
  'Imperial Beijing specialty - crispy lacquered duck served with pancakes, scallions, and hoisin',
  'Bei Jing Kao Ya',
  '北京烤鸭',
  'roasted',
  'signature',
  'beijing',
  'beijing',
  'duck',
  'roasted',
  false,
  false,
  ARRAY['ING_DUCK_WHOLE', 'ING_MANDARIN_PANCAKES', 'ING_HOISIN_SAUCE', 'ING_GREEN_ONION', 'ING_CUCUMBER', 'ING_MALTOSE', 'ING_FIVE_SPICE', 'ING_RICE_VINEGAR'],
  ARRAY['gluten', 'soy'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  680,
  42,
  32,
  42,
  0,
  ARRAY['beijing', 'imperial', 'signature'],
  98
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CHAR_SIU',
  'char-siu',
  'Char Siu (BBQ Pork)',
  'Cantonese honey-glazed roasted pork with distinctive red edges',
  'Cha Shao',
  '叉烧',
  'roasted',
  'classic',
  'cantonese',
  'cantonese',
  'pork',
  'roasted',
  true,
  false,
  ARRAY['ING_PORK_SHOULDER', 'ING_HONEY', 'ING_HOISIN_SAUCE', 'ING_SOY_SAUCE', 'ING_FIVE_SPICE', 'ING_SHAOXING_WINE', 'ING_GARLIC', 'ING_RED_FOOD_COLORING'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  380,
  32,
  18,
  20,
  0,
  ARRAY['cantonese', 'bbq', 'roasted'],
  94
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_ROAST_DUCK',
  'cantonese-roast-duck',
  'Cantonese Roast Duck',
  'Crispy-skinned roast duck with rich, savory flavor - Cantonese style',
  'Shao Ya',
  '烧鸭',
  'roasted',
  'classic',
  'cantonese',
  'cantonese',
  'duck',
  'roasted',
  true,
  false,
  ARRAY['ING_DUCK_WHOLE', 'ING_FIVE_SPICE', 'ING_SOY_SAUCE', 'ING_HONEY', 'ING_STAR_ANISE', 'ING_GINGER', 'ING_GARLIC', 'ING_SHAOXING_WINE'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  520,
  38,
  8,
  38,
  0,
  ARRAY['cantonese', 'roast', 'duck'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SIU_YUK',
  'siu-yuk',
  'Siu Yuk (Roast Pork Belly)',
  'Crispy-skinned roast pork belly with crackling - Cantonese BBQ essential',
  'Shao Rou',
  '烧肉',
  'roasted',
  'classic',
  'cantonese',
  'cantonese',
  'pork',
  'roasted',
  true,
  false,
  ARRAY['ING_PORK_BELLY', 'ING_FIVE_SPICE', 'ING_WHITE_PEPPER', 'ING_SALT', 'ING_SOY_SAUCE', 'ING_SHAOXING_WINE', 'ING_RICE_VINEGAR'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  580,
  28,
  2,
  52,
  0,
  ARRAY['cantonese', 'crackling', 'pork-belly'],
  90
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_ROAST_GOOSE',
  'roast-goose',
  'Roast Goose',
  'Hong Kong specialty - succulent roast goose with crispy skin and plum sauce',
  'Shao E',
  '烧鹅',
  'roasted',
  'premium',
  'hong_kong',
  'cantonese',
  'duck',
  'roasted',
  false,
  false,
  ARRAY['ING_GOOSE', 'ING_FIVE_SPICE', 'ING_SOY_SAUCE', 'ING_MALTOSE', 'ING_PLUM_SAUCE', 'ING_STAR_ANISE', 'ING_GINGER', 'ING_SHAOXING_WINE'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  620,
  42,
  10,
  46,
  0,
  ARRAY['hong-kong', 'goose', 'premium'],
  85
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_WHITE_CUT_CHICKEN',
  'white-cut-chicken',
  'White Cut Chicken',
  'Poached whole chicken served cold with ginger-scallion oil',
  'Bai Qie Ji',
  '白切鸡',
  'roasted',
  'classic',
  'cantonese',
  'cantonese',
  'chicken',
  'boiled',
  true,
  false,
  ARRAY['ING_CHICKEN_WHOLE', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_VEGETABLE_OIL', 'ING_SALT', 'ING_SOY_SAUCE', 'ING_SESAME_OIL'],
  ARRAY['soy', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  380,
  35,
  2,
  26,
  0,
  ARRAY['cantonese', 'cold', 'simple'],
  82
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_HOT_SOUR_SOUP',
  'hot-and-sour-soup',
  'Hot and Sour Soup',
  'Tangy, spicy soup with tofu, mushrooms, bamboo shoots, and silky egg ribbons',
  'Suan La Tang',
  '酸辣汤',
  'soups',
  'classic',
  'sichuan',
  'sichuan',
  'tofu',
  'boiled',
  false,
  false,
  ARRAY['ING_TOFU_FIRM', 'ING_WOOD_EAR_MUSHROOMS', 'ING_BAMBOO_SHOOTS', 'ING_EGG', 'ING_RICE_VINEGAR', 'ING_WHITE_PEPPER', 'ING_SOY_SAUCE', 'ING_CHILI_OIL', 'ING_CORNSTARCH', 'ING_CHICKEN_BROTH'],
  ARRAY['soy', 'egg', 'gluten', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  true,
  true,
  150,
  8,
  14,
  8,
  3,
  ARRAY['sichuan', 'spicy', 'sour'],
  90
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_WONTON_SOUP',
  'wonton-soup',
  'Wonton Soup',
  'Clear chicken broth with delicate pork and shrimp wontons',
  'Hun Tun Tang',
  '馄饨汤',
  'soups',
  'classic',
  'cantonese',
  'cantonese',
  'mixed',
  'boiled',
  true,
  false,
  ARRAY['ING_WONTONS', 'ING_PORK_GROUND', 'ING_SHRIMP', 'ING_CHICKEN_BROTH', 'ING_BOK_CHOY', 'ING_GREEN_ONION', 'ING_GINGER', 'ING_SESAME_OIL', 'ING_WHITE_PEPPER'],
  ARRAY['shellfish', 'gluten', 'soy', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  220,
  14,
  18,
  10,
  0,
  ARRAY['cantonese', 'wontons', 'comfort'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_EGG_DROP_SOUP',
  'egg-drop-soup',
  'Egg Drop Soup',
  'Simple, comforting soup with silky egg ribbons in chicken broth',
  'Dan Hua Tang',
  '蛋花汤',
  'soups',
  'classic',
  'cantonese',
  'cantonese',
  'egg',
  'boiled',
  false,
  false,
  ARRAY['ING_EGG', 'ING_CHICKEN_BROTH', 'ING_CORNSTARCH', 'ING_GREEN_ONION', 'ING_SESAME_OIL', 'ING_WHITE_PEPPER', 'ING_SALT'],
  ARRAY['egg', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  80,
  6,
  4,
  4,
  0,
  ARRAY['simple', 'comfort', 'light'],
  85
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CORN_SOUP',
  'corn-soup-with-crab',
  'Corn Soup with Crab',
  'Creamy sweet corn soup with crab meat - Cantonese banquet favorite',
  'Su Mi Xie Rou Geng',
  '粟米蟹肉羹',
  'soups',
  'classic',
  'cantonese',
  'cantonese',
  'crab',
  'boiled',
  false,
  false,
  ARRAY['ING_CORN', 'ING_CRAB_MEAT', 'ING_EGG', 'ING_CHICKEN_BROTH', 'ING_CORNSTARCH', 'ING_GINGER', 'ING_SHAOXING_WINE', 'ING_WHITE_PEPPER'],
  ARRAY['shellfish', 'egg'],
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  180,
  12,
  22,
  6,
  0,
  ARRAY['cantonese', 'banquet', 'creamy'],
  82
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_WINTER_MELON_SOUP',
  'winter-melon-soup',
  'Winter Melon Soup',
  'Light, refreshing soup with winter melon, ham, and dried scallops',
  'Dong Gua Tang',
  '冬瓜汤',
  'soups',
  'classic',
  'cantonese',
  'cantonese',
  'pork',
  'boiled',
  false,
  false,
  ARRAY['ING_WINTER_MELON', 'ING_HAM', 'ING_DRIED_SCALLOPS', 'ING_CHICKEN_BROTH', 'ING_GINGER', 'ING_GOJI_BERRIES', 'ING_WHITE_PEPPER'],
  ARRAY['shellfish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  120,
  10,
  8,
  6,
  0,
  ARRAY['cantonese', 'light', 'refreshing'],
  75
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SICHUAN_HOT_POT',
  'sichuan-hot-pot',
  'Sichuan Hot Pot',
  'Fiery, numbing broth for cooking meats, vegetables, and noodles at the table',
  'Si Chuan Huo Guo',
  '四川火锅',
  'soups',
  'signature',
  'sichuan',
  'sichuan',
  'mixed',
  'hot_pot',
  false,
  false,
  ARRAY['ING_BEEF_SLICES', 'ING_LAMB_SLICES', 'ING_TOFU_FIRM', 'ING_BOK_CHOY', 'ING_ENOKI_MUSHROOM', 'ING_DOUBANJIANG', 'ING_SICHUAN_PEPPERCORN', 'ING_DRIED_CHILIES', 'ING_GARLIC', 'ING_GINGER'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  450,
  35,
  15,
  28,
  5,
  ARRAY['sichuan', 'hot-pot', 'spicy', 'numbing'],
  95
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_HERBAL_SOUP',
  'chinese-herbal-soup',
  'Chinese Herbal Chicken Soup',
  'Nourishing soup with goji berries, red dates, and medicinal herbs',
  'Yao Shan Ji Tang',
  '药膳鸡汤',
  'soups',
  'classic',
  'cantonese',
  'cantonese',
  'chicken',
  'boiled',
  false,
  false,
  ARRAY['ING_CHICKEN_WHOLE', 'ING_GOJI_BERRIES', 'ING_RED_DATES', 'ING_GINGER', 'ING_DANG_GUI', 'ING_ASTRAGALUS', 'ING_CODONOPSIS', 'ING_SALT'],
  '{}'::TEXT[],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  280,
  28,
  12,
  14,
  0,
  ARRAY['medicinal', 'herbal', 'nourishing'],
  78
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_RED_BRAISED_PORK',
  'red-braised-pork-belly',
  'Hong Shao Rou (Red Braised Pork)',
  'Mao Zedong favorite - meltingly tender pork belly braised in soy, sugar, and spices',
  'Hong Shao Rou',
  '红烧肉',
  'braised',
  'classic',
  'hunan',
  'shanghai',
  'pork',
  'braised',
  false,
  false,
  ARRAY['ING_PORK_BELLY', 'ING_SOY_SAUCE', 'ING_DARK_SOY_SAUCE', 'ING_ROCK_SUGAR', 'ING_SHAOXING_WINE', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_GINGER', 'ING_GREEN_ONION'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  580,
  22,
  18,
  48,
  0,
  ARRAY['shanghai', 'pork-belly', 'braised'],
  92
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_DONGPO_PORK',
  'dongpo-pork',
  'Dongpo Pork',
  'Hangzhou classic - slow-braised pork belly named after poet Su Dongpo',
  'Dong Po Rou',
  '东坡肉',
  'braised',
  'signature',
  'zhejiang',
  'shanghai',
  'pork',
  'braised',
  false,
  false,
  ARRAY['ING_PORK_BELLY', 'ING_SOY_SAUCE', 'ING_SHAOXING_WINE', 'ING_ROCK_SUGAR', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_STAR_ANISE'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  620,
  20,
  22,
  52,
  0,
  ARRAY['hangzhou', 'literary', 'pork-belly'],
  85
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SOY_SAUCE_CHICKEN',
  'soy-sauce-chicken',
  'Soy Sauce Chicken',
  'Whole chicken poached in aromatic master stock - Cantonese BBQ shop staple',
  'Si You Ji',
  '豉油鸡',
  'braised',
  'classic',
  'cantonese',
  'cantonese',
  'chicken',
  'braised',
  true,
  false,
  ARRAY['ING_CHICKEN_WHOLE', 'ING_SOY_SAUCE', 'ING_DARK_SOY_SAUCE', 'ING_ROCK_SUGAR', 'ING_STAR_ANISE', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_SHAOXING_WINE'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  380,
  35,
  8,
  22,
  0,
  ARRAY['cantonese', 'master-stock', 'classic'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_BRAISED_BEEF_BRISKET',
  'braised-beef-brisket',
  'Braised Beef Brisket',
  'Tender beef brisket slow-cooked with chu hou paste and radish',
  'Zhu Hou Niu Nan',
  '柱候牛腩',
  'braised',
  'classic',
  'cantonese',
  'cantonese',
  'beef',
  'braised',
  true,
  false,
  ARRAY['ING_BEEF_BRISKET', 'ING_CHU_HOU_PASTE', 'ING_WHITE_RADISH', 'ING_STAR_ANISE', 'ING_GINGER', 'ING_GARLIC', 'ING_SOY_SAUCE', 'ING_SHAOXING_WINE'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  420,
  38,
  12,
  24,
  0,
  ARRAY['cantonese', 'beef', 'comfort'],
  86
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_LIONS_HEAD_MEATBALLS',
  'lions-head-meatballs',
  'Lion',
  'Giant pork meatballs braised with napa cabbage - Shanghai comfort food',
  'Shi Zi Tou',
  '狮子头',
  'braised',
  'classic',
  'jiangsu',
  'shanghai',
  'pork',
  'braised',
  false,
  false,
  ARRAY['ING_PORK_GROUND', 'ING_NAPA_CABBAGE', 'ING_WATER_CHESTNUTS', 'ING_GINGER', 'ING_SOY_SAUCE', 'ING_SHAOXING_WINE', 'ING_EGG', 'ING_CORNSTARCH'],
  ARRAY['soy', 'egg', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  380,
  24,
  14,
  26,
  0,
  ARRAY['shanghai', 'meatballs', 'comfort'],
  80
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_BRAISED_EGGPLANT',
  'braised-eggplant',
  'Yu Xiang Eggplant',
  'Silky eggplant in savory-sweet fish-fragrant sauce - actually no fish!',
  'Yu Xiang Qie Zi',
  '鱼香茄子',
  'braised',
  'classic',
  'sichuan',
  'sichuan',
  'vegetables',
  'braised',
  false,
  false,
  ARRAY['ING_EGGPLANT', 'ING_PORK_GROUND', 'ING_DOUBANJIANG', 'ING_GARLIC', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_SOY_SAUCE', 'ING_RICE_VINEGAR', 'ING_SUGAR'],
  ARRAY['soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  280,
  10,
  22,
  18,
  3,
  ARRAY['sichuan', 'eggplant', 'fish-fragrant'],
  84
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_STEAMED_FISH',
  'cantonese-steamed-fish',
  'Cantonese Steamed Fish',
  'Whole fish steamed to perfection with ginger, scallions, and hot oil',
  'Qing Zheng Yu',
  '清蒸鱼',
  'steamed',
  'signature',
  'cantonese',
  'cantonese',
  'fish',
  'steamed',
  false,
  false,
  ARRAY['ING_SEA_BASS', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_SOY_SAUCE', 'ING_SHAOXING_WINE', 'ING_VEGETABLE_OIL', 'ING_CILANTRO'],
  ARRAY['fish', 'soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  true,
  true,
  280,
  38,
  4,
  12,
  0,
  ARRAY['cantonese', 'steamed', 'whole-fish'],
  92
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_KUNG_PAO_SHRIMP',
  'kung-pao-shrimp',
  'Kung Pao Shrimp',
  'Sichuan stir-fry with plump shrimp, peanuts, and dried chilies',
  'Gong Bao Xia Ren',
  '宫保虾仁',
  'stir_fries',
  'popular',
  'sichuan',
  'sichuan',
  'shrimp',
  'stir_fried',
  false,
  false,
  ARRAY['ING_SHRIMP', 'ING_PEANUTS', 'ING_DRIED_CHILIES', 'ING_SICHUAN_PEPPERCORN', 'ING_SOY_SAUCE', 'ING_RICE_VINEGAR', 'ING_GARLIC', 'ING_GINGER', 'ING_GREEN_ONION'],
  ARRAY['shellfish', 'peanuts', 'soy', 'gluten'],
  false,
  true,
  false,
  false,
  false,
  true,
  true,
  320,
  26,
  14,
  18,
  4,
  ARRAY['sichuan', 'spicy', 'shrimp'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SALT_PEPPER_SQUID',
  'salt-and-pepper-squid',
  'Salt and Pepper Squid',
  'Crispy fried squid tossed with salt, pepper, garlic, and chilies',
  'Jiao Yan You Yu',
  '椒盐鱿鱼',
  'appetizers',
  'popular',
  'cantonese',
  'cantonese',
  'squid',
  'deep_fried',
  true,
  false,
  ARRAY['ING_SQUID', 'ING_SALT', 'ING_WHITE_PEPPER', 'ING_SICHUAN_PEPPERCORN', 'ING_GARLIC', 'ING_CHILI', 'ING_CORNSTARCH', 'ING_GREEN_ONION'],
  ARRAY['shellfish'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  280,
  22,
  18,
  14,
  2,
  ARRAY['cantonese', 'crispy', 'spicy'],
  86
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_LOBSTER_GINGER_SCALLION',
  'lobster-ginger-scallion',
  'Lobster with Ginger and Scallion',
  'Premium Cantonese dish - wok-fried lobster with aromatic ginger-scallion sauce',
  'Jiang Cong Long Xia',
  '姜葱龙虾',
  'stir_fries',
  'premium',
  'cantonese',
  'cantonese',
  'lobster',
  'stir_fried',
  false,
  false,
  ARRAY['ING_LOBSTER', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_GARLIC', 'ING_SOY_SAUCE', 'ING_SHAOXING_WINE', 'ING_SESAME_OIL', 'ING_CORNSTARCH'],
  ARRAY['shellfish', 'soy', 'gluten', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  true,
  true,
  380,
  32,
  8,
  24,
  0,
  ARRAY['cantonese', 'premium', 'lobster'],
  90
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_CRAB_XO_SAUCE',
  'crab-with-xo-sauce',
  'Crab with XO Sauce',
  'Stir-fried crab in rich, spicy XO sauce - Hong Kong delicacy',
  'XO Jiang Chao Xie',
  'XO酱炒蟹',
  'stir_fries',
  'premium',
  'hong_kong',
  'cantonese',
  'crab',
  'stir_fried',
  false,
  false,
  ARRAY['ING_CRAB', 'ING_XO_SAUCE', 'ING_GARLIC', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_SHAOXING_WINE', 'ING_SOY_SAUCE'],
  ARRAY['shellfish', 'soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  false,
  true,
  350,
  28,
  10,
  22,
  3,
  ARRAY['hong-kong', 'xo-sauce', 'premium'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SHRIMP_EGGS',
  'shrimp-with-scrambled-eggs',
  'Shrimp with Scrambled Eggs',
  'Silky scrambled eggs with succulent shrimp - Cantonese comfort classic',
  'Hua Dan Xia Ren',
  '滑蛋虾仁',
  'stir_fries',
  'classic',
  'cantonese',
  'cantonese',
  'shrimp',
  'stir_fried',
  false,
  false,
  ARRAY['ING_SHRIMP', 'ING_EGG', 'ING_GREEN_ONION', 'ING_SHAOXING_WINE', 'ING_SESAME_OIL', 'ING_WHITE_PEPPER', 'ING_SALT'],
  ARRAY['shellfish', 'egg', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  280,
  24,
  4,
  18,
  0,
  ARRAY['cantonese', 'eggs', 'comfort'],
  82
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_STEAMED_PRAWNS',
  'steamed-garlic-prawns',
  'Steamed Garlic Prawns',
  'Giant prawns steamed with garlic, vermicelli, and soy sauce',
  'Suan Rong Zheng Xia',
  '蒜蓉蒸虾',
  'steamed',
  'popular',
  'cantonese',
  'cantonese',
  'shrimp',
  'steamed',
  false,
  false,
  ARRAY['ING_PRAWNS', 'ING_GARLIC', 'ING_RICE_VERMICELLI', 'ING_SOY_SAUCE', 'ING_SHAOXING_WINE', 'ING_GREEN_ONION', 'ING_VEGETABLE_OIL'],
  ARRAY['shellfish', 'soy', 'gluten'],
  false,
  true,
  true,
  false,
  false,
  true,
  true,
  320,
  28,
  22,
  12,
  0,
  ARRAY['cantonese', 'steamed', 'garlic'],
  85
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SCALLION_PANCAKES',
  'scallion-pancakes',
  'Cong You Bing (Scallion Pancakes)',
  'Flaky, crispy layered pancakes studded with green onions',
  'Cong You Bing',
  '葱油饼',
  'appetizers',
  'classic',
  'beijing',
  'beijing',
  'vegetables',
  'stir_fried',
  true,
  false,
  ARRAY['ING_FLOUR', 'ING_GREEN_ONION', 'ING_SESAME_OIL', 'ING_VEGETABLE_OIL', 'ING_SALT'],
  ARRAY['gluten', 'sesame'],
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  280,
  6,
  36,
  12,
  0,
  ARRAY['street-food', 'vegetarian', 'crispy'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_POTSTICKERS',
  'potstickers',
  'Guo Tie (Potstickers)',
  'Pan-fried dumplings with crispy bottoms and juicy pork filling',
  'Guo Tie',
  '锅贴',
  'appetizers',
  'classic',
  'northeastern',
  'beijing',
  'pork',
  'stir_fried',
  true,
  false,
  ARRAY['ING_PORK_GROUND', 'ING_CABBAGE', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_FLOUR', 'ING_RICE_VINEGAR'],
  ARRAY['gluten', 'soy', 'sesame'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  320,
  16,
  28,
  16,
  0,
  ARRAY['dumplings', 'pan-fried', 'classic'],
  92
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_JIANBING',
  'jianbing',
  'Jian Bing (Chinese Crepe)',
  'Beijing street breakfast - crispy crepe with egg, scallions, cilantro, and crunchy crackers',
  'Jian Bing',
  '煎饼',
  'appetizers',
  'street_food',
  'beijing',
  'beijing',
  'egg',
  'stir_fried',
  true,
  false,
  ARRAY['ING_MUNG_BEAN_FLOUR', 'ING_EGG', 'ING_GREEN_ONION', 'ING_CILANTRO', 'ING_SWEET_BEAN_PASTE', 'ING_CHILI_SAUCE', 'ING_FRIED_DOUGH'],
  ARRAY['egg', 'gluten', 'soy'],
  false,
  true,
  true,
  false,
  true,
  true,
  true,
  350,
  12,
  42,
  14,
  1,
  ARRAY['street-food', 'breakfast', 'beijing'],
  90
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_COLD_NOODLES',
  'sichuan-cold-noodles',
  'Liang Mian (Sichuan Cold Noodles)',
  'Chilled wheat noodles in spicy, numbing sesame sauce',
  'Liang Mian',
  '凉面',
  'appetizers',
  'classic',
  'sichuan',
  'sichuan',
  'vegetables',
  'raw',
  true,
  false,
  ARRAY['ING_WHEAT_NOODLES', 'ING_SESAME_PASTE', 'ING_CHILI_OIL', 'ING_SOY_SAUCE', 'ING_RICE_VINEGAR', 'ING_GARLIC', 'ING_CUCUMBER', 'ING_PEANUTS'],
  ARRAY['gluten', 'sesame', 'soy', 'peanuts'],
  false,
  true,
  false,
  true,
  true,
  true,
  true,
  380,
  12,
  48,
  16,
  4,
  ARRAY['cold', 'spicy', 'sichuan'],
  84
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SMASHED_CUCUMBER',
  'smashed-cucumber-salad',
  'Pai Huang Gua (Smashed Cucumber)',
  'Refreshing cold appetizer with garlic, vinegar, and chili oil',
  'Pai Huang Gua',
  '拍黄瓜',
  'appetizers',
  'classic',
  'sichuan',
  'sichuan',
  'vegetables',
  'raw',
  true,
  false,
  ARRAY['ING_CUCUMBER', 'ING_GARLIC', 'ING_CHILI_OIL', 'ING_RICE_VINEGAR', 'ING_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_SUGAR', 'ING_SALT'],
  ARRAY['soy', 'sesame', 'gluten'],
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  80,
  2,
  8,
  5,
  2,
  ARRAY['cold', 'refreshing', 'vegan'],
  86
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_THOUSAND_YEAR_EGG',
  'century-egg-tofu',
  'Pi Dan Tofu (Century Egg with Tofu)',
  'Cold silken tofu topped with century egg, soy, and sesame',
  'Pi Dan Dou Fu',
  '皮蛋豆腐',
  'appetizers',
  'classic',
  'cantonese',
  'cantonese',
  'tofu',
  'raw',
  false,
  false,
  ARRAY['ING_TOFU_SILKEN', 'ING_CENTURY_EGG', 'ING_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_GREEN_ONION', 'ING_CILANTRO', 'ING_DRIED_SHRIMP'],
  ARRAY['soy', 'egg', 'sesame', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  180,
  14,
  6,
  12,
  0,
  ARRAY['cold', 'tofu', 'appetizer'],
  75
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_DRUNKEN_CHICKEN',
  'drunken-chicken',
  'Zui Ji (Drunken Chicken)',
  'Cold poached chicken marinated in Shaoxing wine - Shanghai specialty',
  'Zui Ji',
  '醉鸡',
  'appetizers',
  'classic',
  'jiangsu',
  'shanghai',
  'chicken',
  'boiled',
  false,
  false,
  ARRAY['ING_CHICKEN_LEG', 'ING_SHAOXING_WINE', 'ING_GINGER', 'ING_GREEN_ONION', 'ING_SALT', 'ING_GOJI_BERRIES'],
  ARRAY['alcohol'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  280,
  28,
  4,
  14,
  0,
  ARRAY['cold', 'shanghai', 'wine'],
  78
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_MANGO_PUDDING',
  'mango-pudding',
  'Mango Pudding',
  'Silky chilled mango pudding with evaporated milk - Hong Kong dim sum favorite',
  'Mang Guo Bu Ding',
  '芒果布丁',
  'desserts',
  'popular',
  'hong_kong',
  'cantonese',
  'egg',
  'raw',
  false,
  true,
  ARRAY['ING_MANGO', 'ING_EVAPORATED_MILK', 'ING_SUGAR', 'ING_GELATIN', 'ING_COCONUT_MILK'],
  ARRAY['dairy'],
  true,
  false,
  true,
  false,
  true,
  true,
  true,
  180,
  4,
  32,
  6,
  0,
  ARRAY['dim-sum', 'cold', 'mango'],
  92
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_SESAME_BALLS',
  'sesame-balls',
  'Jian Dui (Sesame Balls)',
  'Crispy fried glutinous rice balls filled with sweet red bean paste',
  'Jian Dui',
  '煎堆',
  'desserts',
  'classic',
  'cantonese',
  'dim_sum',
  'vegetables',
  'deep_fried',
  true,
  true,
  ARRAY['ING_GLUTINOUS_RICE_FLOUR', 'ING_RED_BEAN_PASTE', 'ING_SESAME_SEEDS', 'ING_SUGAR', 'ING_VEGETABLE_OIL'],
  ARRAY['sesame'],
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  220,
  4,
  38,
  8,
  0,
  ARRAY['dim-sum', 'fried', 'red-bean'],
  85
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_TANGYUAN',
  'tangyuan',
  'Tang Yuan (Sweet Rice Balls)',
  'Glutinous rice balls in sweet ginger soup - Lantern Festival tradition',
  'Tang Yuan',
  '汤圆',
  'desserts',
  'seasonal',
  'cantonese',
  'cantonese',
  'vegetables',
  'boiled',
  true,
  false,
  ARRAY['ING_GLUTINOUS_RICE_FLOUR', 'ING_BLACK_SESAME_PASTE', 'ING_PEANUT_BUTTER', 'ING_GINGER', 'ING_ROCK_SUGAR', 'ING_WATER'],
  ARRAY['sesame', 'peanuts'],
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  250,
  4,
  48,
  8,
  0,
  ARRAY['festival', 'glutinous', 'traditional'],
  88
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_MOONCAKE',
  'mooncake',
  'Yue Bing (Mooncake)',
  'Traditional Mid-Autumn pastry with lotus seed paste and salted egg yolk',
  'Yue Bing',
  '月饼',
  'desserts',
  'seasonal',
  'cantonese',
  'cantonese',
  'egg',
  'roasted',
  false,
  false,
  ARRAY['ING_LOTUS_SEED_PASTE', 'ING_SALTED_EGG_YOLK', 'ING_FLOUR', 'ING_GOLDEN_SYRUP', 'ING_VEGETABLE_OIL', 'ING_LYE_WATER'],
  ARRAY['egg', 'gluten'],
  false,
  true,
  true,
  false,
  true,
  true,
  true,
  380,
  8,
  52,
  16,
  0,
  ARRAY['mid-autumn', 'traditional', 'pastry'],
  90
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_DOUBLE_SKIN_MILK',
  'double-skin-milk',
  'Shuang Pi Nai (Double Skin Milk)',
  'Silky steamed milk custard with a delicate skin - Shunde specialty',
  'Shuang Pi Nai',
  '双皮奶',
  'desserts',
  'signature',
  'cantonese',
  'cantonese',
  'egg',
  'steamed',
  false,
  true,
  ARRAY['ING_MILK', 'ING_EGG_WHITE', 'ING_SUGAR'],
  ARRAY['dairy', 'egg'],
  true,
  false,
  true,
  false,
  true,
  true,
  true,
  150,
  6,
  20,
  6,
  0,
  ARRAY['cantonese', 'custard', 'silky'],
  82
);

INSERT INTO chinese (
  id, slug, name, description, chinese_name, chinese_script,
  category, status, region, cuisine_style, protein_type, cooking_method,
  is_street_food, is_dim_sum,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'CHINESE_RED_BEAN_SOUP',
  'red-bean-soup',
  'Hong Dou Tang (Red Bean Soup)',
  'Sweet warm soup with red beans and lotus seeds - classic Cantonese dessert',
  'Hong Dou Tang',
  '红豆汤',
  'desserts',
  'classic',
  'cantonese',
  'cantonese',
  'vegetables',
  'boiled',
  true,
  false,
  ARRAY['ING_RED_BEANS', 'ING_LOTUS_SEEDS', 'ING_ROCK_SUGAR', 'ING_DRIED_TANGERINE_PEEL', 'ING_WATER'],
  '{}'::TEXT[],
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  180,
  6,
  38,
  1,
  0,
  ARRAY['soup', 'warm', 'traditional'],
  80
);

COMMIT;

-- Verify
SELECT category, COUNT(*) as count FROM chinese GROUP BY category ORDER BY count DESC;
SELECT COUNT(*) as total_chinese_dishes FROM chinese;
