-- Argentinian Cuisine Database - Script 03: Insert Dishes
-- GUDBRO Database Standards v1.7
-- Date: 2025-12-26
-- Total: 47 dishes

INSERT INTO argentinian (id, slug, name, description, category, status, region, protein_type, cooking_method, prep_time_min, spice_level, dietary, allergens, tags, popularity) VALUES

-- ASADO (8)
('ARG_ASADO_COMPLETO', 'asado-completo', 'Asado Completo', 'Traditional Argentine BBQ platter with various cuts of beef, chorizo, morcilla, and chimichurri', 'asado', 'iconic', 'Buenos Aires', 'beef', 'grilled', 120, 1, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['signature', 'sharing', 'weekend'], 98),
('ARG_COSTILLAS', 'costillas-asado', 'Costillas de Asado', 'Slow-grilled beef ribs with crispy exterior and juicy meat', 'asado', 'iconic', 'Buenos Aires', 'beef', 'grilled', 90, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['ribs', 'slow-cooked', 'classic'], 95),
('ARG_VACIO', 'vacio', 'Vacío', 'Flank steak grilled to perfection, tender and flavorful', 'asado', 'iconic', 'Buenos Aires', 'beef', 'grilled', 60, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['steak', 'tender', 'popular'], 94),
('ARG_ENTRAÑA', 'entrana', 'Entraña', 'Skirt steak with intense beefy flavor, grilled medium-rare', 'asado', 'iconic', 'Buenos Aires', 'beef', 'grilled', 30, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['skirt-steak', 'flavorful', 'quick'], 93),
('ARG_CHORIZO_CRIOLLO', 'chorizo-criollo', 'Chorizo Criollo', 'Fresh Argentine sausage grilled and served with chimichurri', 'asado', 'iconic', 'Buenos Aires', 'pork', 'grilled', 20, 1, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['sausage', 'appetizer', 'classic'], 92),
('ARG_MORCILLA', 'morcilla', 'Morcilla', 'Argentine blood sausage, crispy outside, creamy inside', 'asado', 'classic', 'Buenos Aires', 'pork', 'grilled', 20, 0, '{"gluten_free": false}'::jsonb, ARRAY['gluten'], ARRAY['blood-sausage', 'traditional', 'offal'], 78),
('ARG_PROVOLETA', 'provoleta', 'Provoleta', 'Grilled provolone cheese with oregano and chili flakes', 'asado', 'iconic', 'Buenos Aires', 'vegetable', 'grilled', 10, 1, '{"vegetarian": true, "gluten_free": true}'::jsonb, ARRAY['dairy'], ARRAY['cheese', 'appetizer', 'vegetarian'], 90),
('ARG_MATAMBRE_ARROLLADO', 'matambre-arrollado', 'Matambre Arrollado', 'Rolled flank steak stuffed with vegetables, eggs, and herbs', 'asado', 'classic', 'Buenos Aires', 'beef', 'grilled', 90, 0, '{"gluten_free": true}'::jsonb, ARRAY['egg'], ARRAY['stuffed', 'elegant', 'special-occasion'], 82),

-- EMPANADAS (7)
('ARG_EMPANADA_CARNE', 'empanada-carne', 'Empanada de Carne', 'Classic beef empanada with onions, olives, and hard-boiled egg', 'empanada', 'iconic', 'Buenos Aires', 'beef', 'baked', 45, 1, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'egg'], ARRAY['signature', 'street-food', 'classic'], 98),
('ARG_EMPANADA_SALTEÑA', 'empanada-saltena', 'Empanada Salteña', 'Salta-style empanada with juicy beef, potato, and spices, baked in wood oven', 'empanada', 'iconic', 'Salta', 'beef', 'baked', 50, 2, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'egg'], ARRAY['regional', 'juicy', 'traditional'], 95),
('ARG_EMPANADA_TUCUMANA', 'empanada-tucumana', 'Empanada Tucumana', 'Tucumán-style fried empanada with hand-cut beef and paprika', 'empanada', 'iconic', 'Tucumán', 'beef', 'deep_fried', 45, 1, '{"gluten_free": false}'::jsonb, ARRAY['gluten'], ARRAY['fried', 'regional', 'crispy'], 92),
('ARG_EMPANADA_POLLO', 'empanada-pollo', 'Empanada de Pollo', 'Chicken empanada with bell peppers and onions', 'empanada', 'classic', 'Buenos Aires', 'chicken', 'baked', 45, 0, '{"gluten_free": false}'::jsonb, ARRAY['gluten'], ARRAY['chicken', 'mild', 'family-friendly'], 88),
('ARG_EMPANADA_JAMON_QUESO', 'empanada-jamon-queso', 'Empanada de Jamón y Queso', 'Ham and cheese empanada, a popular snack option', 'empanada', 'classic', 'Buenos Aires', 'pork', 'baked', 30, 0, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'dairy'], ARRAY['ham', 'cheese', 'snack'], 90),
('ARG_EMPANADA_HUMITA', 'empanada-humita', 'Empanada de Humita', 'Sweet corn empanada with creamy corn filling and white sauce', 'empanada', 'classic', 'Salta', 'vegetable', 'baked', 40, 0, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'dairy'], ARRAY['vegetarian', 'sweet-corn', 'creamy'], 85),
('ARG_EMPANADA_VERDURA', 'empanada-verdura', 'Empanada de Verdura', 'Vegetable empanada with Swiss chard, onion, and cheese', 'empanada', 'classic', 'Buenos Aires', 'vegetable', 'baked', 40, 0, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'dairy'], ARRAY['vegetarian', 'healthy', 'light'], 82),

-- MAINS (7)
('ARG_MILANESA_NAPOLITANA', 'milanesa-napolitana', 'Milanesa a la Napolitana', 'Breaded beef cutlet topped with ham, tomato sauce, and melted mozzarella', 'main', 'iconic', 'Buenos Aires', 'beef', 'deep_fried', 30, 0, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'egg', 'dairy'], ARRAY['signature', 'comfort-food', 'cheesy'], 96),
('ARG_MILANESA_CLASICA', 'milanesa-clasica', 'Milanesa Clásica', 'Traditional breaded and fried beef cutlet, served with lemon', 'main', 'iconic', 'Buenos Aires', 'beef', 'deep_fried', 25, 0, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'egg'], ARRAY['classic', 'crispy', 'everyday'], 94),
('ARG_BIFE_CHORIZO', 'bife-de-chorizo', 'Bife de Chorizo', 'Thick-cut sirloin steak, the king of Argentine steaks', 'main', 'iconic', 'Buenos Aires', 'beef', 'grilled', 20, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['steak', 'premium', 'restaurant'], 95),
('ARG_OJO_BIFE', 'ojo-de-bife', 'Ojo de Bife', 'Ribeye steak, marbled and flavorful, grilled to perfection', 'main', 'iconic', 'Buenos Aires', 'beef', 'grilled', 20, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['ribeye', 'marbled', 'juicy'], 93),
('ARG_LOMO', 'lomo', 'Lomo', 'Beef tenderloin, the most tender cut, grilled medium-rare', 'main', 'classic', 'Buenos Aires', 'beef', 'grilled', 20, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['tenderloin', 'premium', 'elegant'], 90),
('ARG_POLLO_GRILLADO', 'pollo-grillado', 'Pollo a la Parrilla', 'Grilled chicken marinated with herbs and lemon', 'main', 'classic', 'Buenos Aires', 'chicken', 'grilled', 45, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['chicken', 'healthy', 'everyday'], 82),
('ARG_MATAMBRE_PIZZA', 'matambre-a-la-pizza', 'Matambre a la Pizza', 'Thin flank steak topped with tomato, mozzarella, and oregano like a pizza', 'main', 'classic', 'Buenos Aires', 'beef', 'grilled', 30, 0, '{"gluten_free": true}'::jsonb, ARRAY['dairy'], ARRAY['creative', 'cheesy', 'fun'], 85),

-- PASTA (6)
('ARG_NOQUIS_29', 'noquis-del-29', 'Ñoquis del 29', 'Traditional potato gnocchi served on the 29th of each month for good luck', 'pasta', 'iconic', 'Buenos Aires', 'vegetable', 'boiled', 60, 0, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'egg', 'dairy'], ARRAY['tradition', 'lucky', 'monthly'], 95),
('ARG_SORRENTINOS', 'sorrentinos', 'Sorrentinos', 'Large round ravioli stuffed with ham, cheese, and ricotta', 'pasta', 'iconic', 'Buenos Aires', 'pork', 'boiled', 90, 0, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'egg', 'dairy'], ARRAY['stuffed-pasta', 'creamy', 'sunday'], 92),
('ARG_RAVIOLES', 'ravioles', 'Ravioles', 'Fresh ravioli with ricotta and spinach filling in tomato sauce', 'pasta', 'classic', 'Buenos Aires', 'vegetable', 'boiled', 75, 0, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'egg', 'dairy'], ARRAY['fresh-pasta', 'sunday-lunch', 'family'], 90),
('ARG_TALLARINES_SALSA', 'tallarines-con-salsa', 'Tallarines con Salsa', 'Fresh tagliatelle with slow-cooked meat sauce (tuco)', 'pasta', 'iconic', 'Buenos Aires', 'beef', 'boiled', 90, 0, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'egg'], ARRAY['sunday', 'family', 'hearty'], 93),
('ARG_CANELONES', 'canelones', 'Canelones', 'Pasta tubes filled with beef and spinach, baked with béchamel', 'pasta', 'classic', 'Buenos Aires', 'beef', 'baked', 90, 0, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'egg', 'dairy'], ARRAY['baked', 'creamy', 'comfort'], 88),
('ARG_LASAGNA', 'lasagna-argentina', 'Lasaña Argentina', 'Argentine-style lasagna with meat sauce, béchamel, and lots of cheese', 'pasta', 'classic', 'Buenos Aires', 'beef', 'baked', 120, 0, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'egg', 'dairy'], ARRAY['baked', 'layered', 'special-occasion'], 90),

-- SOUPS (5)
('ARG_LOCRO', 'locro', 'Locro', 'Traditional corn and white bean stew with meat, eaten on national holidays', 'soup', 'iconic', 'Salta', 'mixed', 'simmered', 180, 1, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['national-dish', 'holiday', 'winter'], 95),
('ARG_CARBONADA', 'carbonada', 'Carbonada', 'Sweet and savory beef stew with peaches, corn, and squash, served in a pumpkin', 'soup', 'classic', 'Buenos Aires', 'beef', 'simmered', 90, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['sweet-savory', 'unique', 'autumn'], 80),
('ARG_GUISO_LENTEJAS', 'guiso-de-lentejas', 'Guiso de Lentejas', 'Hearty lentil stew with chorizo, vegetables, and potatoes', 'soup', 'classic', 'Buenos Aires', 'legume', 'simmered', 60, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['lentils', 'winter', 'economical'], 85),
('ARG_PUCHERO', 'puchero', 'Puchero', 'Boiled dinner with beef, chicken, vegetables, and broth served separately', 'soup', 'traditional', 'Buenos Aires', 'mixed', 'boiled', 120, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['boiled-dinner', 'sunday', 'grandmother'], 78),
('ARG_CAZUELA_MONDONGO', 'cazuela-de-mondongo', 'Cazuela de Mondongo', 'Tripe stew with vegetables and chickpeas in tomato broth', 'soup', 'traditional', 'Buenos Aires', 'beef', 'simmered', 180, 0, '{"gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['offal', 'traditional', 'slow-cooked'], 65),

-- APPETIZERS (5)
('ARG_CHIMICHURRI', 'chimichurri', 'Chimichurri', 'Fresh herb sauce with parsley, oregano, garlic, and vinegar', 'appetizer', 'iconic', 'Buenos Aires', 'vegetable', 'raw', 10, 1, '{"vegetarian": true, "vegan": true, "gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['sauce', 'essential', 'fresh'], 98),
('ARG_SALSA_CRIOLLA', 'salsa-criolla', 'Salsa Criolla', 'Fresh tomato and onion salsa with bell peppers and vinegar', 'appetizer', 'iconic', 'Buenos Aires', 'vegetable', 'raw', 15, 0, '{"vegetarian": true, "vegan": true, "gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['salsa', 'fresh', 'accompaniment'], 90),
('ARG_PAPAS_FRITAS', 'papas-fritas', 'Papas Fritas', 'Classic Argentine french fries, thick-cut and crispy', 'appetizer', 'classic', 'Buenos Aires', 'vegetable', 'deep_fried', 30, 0, '{"vegetarian": true, "vegan": true, "gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['fries', 'side', 'classic'], 88),
('ARG_ENSALADA_MIXTA', 'ensalada-mixta', 'Ensalada Mixta', 'Simple mixed salad with lettuce, tomato, and onion', 'appetizer', 'classic', 'Buenos Aires', 'vegetable', 'raw', 10, 0, '{"vegetarian": true, "vegan": true, "gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['salad', 'fresh', 'light'], 75),
('ARG_TORTILLA_PAPA', 'tortilla-de-papa', 'Tortilla de Papa', 'Argentine-style potato omelette with onions', 'appetizer', 'classic', 'Buenos Aires', 'egg', 'pan_fried', 30, 0, '{"vegetarian": true, "gluten_free": true}'::jsonb, ARRAY['egg'], ARRAY['omelette', 'comfort', 'brunch'], 82),

-- DESSERTS (9)
('ARG_DULCE_LECHE', 'dulce-de-leche', 'Dulce de Leche', 'Thick caramelized milk spread, the soul of Argentine sweets', 'dessert', 'iconic', 'Buenos Aires', 'dairy', 'simmered', 120, 0, '{"vegetarian": true, "gluten_free": true}'::jsonb, ARRAY['dairy'], ARRAY['essential', 'sweet', 'spread'], 99),
('ARG_ALFAJORES', 'alfajores', 'Alfajores', 'Sandwich cookies filled with dulce de leche, coated in chocolate or powdered sugar', 'dessert', 'iconic', 'Buenos Aires', 'dairy', 'baked', 60, 0, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'dairy', 'egg'], ARRAY['cookies', 'dulce-de-leche', 'gift'], 98),
('ARG_FLAN_MIXTO', 'flan-mixto', 'Flan Mixto', 'Caramel custard served with dulce de leche and whipped cream', 'dessert', 'iconic', 'Buenos Aires', 'dairy', 'baked', 60, 0, '{"vegetarian": true, "gluten_free": true}'::jsonb, ARRAY['dairy', 'egg'], ARRAY['custard', 'classic', 'restaurant'], 95),
('ARG_PANQUEQUES_DDL', 'panqueques-dulce-de-leche', 'Panqueques con Dulce de Leche', 'Thin crepes filled with dulce de leche and topped with whipped cream', 'dessert', 'iconic', 'Buenos Aires', 'dairy', 'pan_fried', 30, 0, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'dairy', 'egg'], ARRAY['crepes', 'indulgent', 'popular'], 92),
('ARG_CHOCOTORTA', 'chocotorta', 'Chocotorta', 'No-bake chocolate cake with cream cheese and dulce de leche layers', 'dessert', 'iconic', 'Buenos Aires', 'dairy', 'raw', 30, 0, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'dairy'], ARRAY['no-bake', 'chocolate', 'party'], 94),
('ARG_VIGILANTE', 'vigilante', 'Vigilante', 'Classic dessert pairing of quince paste with fresh cheese', 'dessert', 'classic', 'Buenos Aires', 'dairy', 'raw', 5, 0, '{"vegetarian": true, "gluten_free": true}'::jsonb, ARRAY['dairy'], ARRAY['simple', 'traditional', 'pairing'], 80),
('ARG_ARROZ_LECHE', 'arroz-con-leche', 'Arroz con Leche', 'Creamy rice pudding with cinnamon and dulce de leche', 'dessert', 'classic', 'Buenos Aires', 'dairy', 'simmered', 45, 0, '{"vegetarian": true, "gluten_free": true}'::jsonb, ARRAY['dairy'], ARRAY['rice-pudding', 'comfort', 'grandmother'], 85),
('ARG_FACTURAS', 'facturas', 'Facturas', 'Argentine pastries including medialunas, vigilantes, and cañoncitos', 'dessert', 'iconic', 'Buenos Aires', 'dairy', 'baked', 120, 0, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'dairy', 'egg'], ARRAY['pastry', 'breakfast', 'cafe'], 93),
('ARG_MEDIALUNAS', 'medialunas', 'Medialunas', 'Sweet croissant-like pastries glazed with sugar syrup', 'dessert', 'iconic', 'Buenos Aires', 'dairy', 'baked', 180, 0, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'dairy', 'egg'], ARRAY['croissant', 'breakfast', 'cafe-culture'], 95),

-- BEVERAGES (5)
('ARG_MATE', 'mate', 'Mate', 'Traditional yerba mate infusion, the national drink of Argentina', 'beverage', 'iconic', 'Buenos Aires', 'vegetable', 'steeped', 5, 0, '{"vegetarian": true, "vegan": true, "gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['national-drink', 'social', 'daily'], 99),
('ARG_MATE_COCIDO', 'mate-cocido', 'Mate Cocido', 'Yerba mate brewed like tea, served in a cup with milk or lemon', 'beverage', 'classic', 'Buenos Aires', 'vegetable', 'steeped', 5, 0, '{"vegetarian": true, "vegan": true, "gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['tea-style', 'breakfast', 'mild'], 75),
('ARG_FERNET_COLA', 'fernet-con-coca', 'Fernet con Coca', 'Fernet Branca mixed with cola, Argentina''s signature cocktail', 'beverage', 'iconic', 'Córdoba', 'beverage', 'mixed', 2, 0, '{"vegetarian": true, "vegan": true, "gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['cocktail', 'nightlife', 'cordoba'], 92),
('ARG_CLERICO', 'clerico', 'Clericó', 'Argentine sangria with white wine and fresh fruit', 'beverage', 'classic', 'Mendoza', 'beverage', 'mixed', 15, 0, '{"vegetarian": true, "vegan": true, "gluten_free": true}'::jsonb, ARRAY[]::TEXT[], ARRAY['sangria', 'summer', 'party'], 80),
('ARG_SUBMARINO', 'submarino', 'Submarino', 'Hot milk with a chocolate bar that melts inside', 'beverage', 'classic', 'Buenos Aires', 'dairy', 'heated', 5, 0, '{"vegetarian": true, "gluten_free": true}'::jsonb, ARRAY['dairy'], ARRAY['hot-chocolate', 'kids', 'cafe'], 85);

-- Success message
SELECT 'Inserted 47 Argentinian dishes' AS status;
