-- Indo-Chinese Database - Script 03: Insert Dishes
-- GUDBRO Database Standards v1.7
-- Date: 2025-12-25
-- Total: 35 dishes

INSERT INTO indochinese (id, slug, name, description, category, status, protein_type, cooking_method, prep_time_min, spice_level, dietary, allergens, tags, popularity) VALUES

-- MANCHURIAN (6)
('IND_GOBI_MANCHURIAN_DRY', 'gobi-manchurian-dry', 'Gobi Manchurian Dry', 'Crispy cauliflower florets tossed in spicy, tangy Manchurian sauce with bell peppers', 'manchurian', 'iconic', 'vegetable', 'deep_fried', 30, 3, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['signature', 'crispy', 'street-food'], 98),
('IND_GOBI_MANCHURIAN_GRAVY', 'gobi-manchurian-gravy', 'Gobi Manchurian Gravy', 'Crispy cauliflower in rich, glossy Manchurian gravy with onions and peppers', 'manchurian', 'iconic', 'vegetable', 'deep_fried', 35, 3, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['gravy', 'comfort-food', 'popular'], 95),
('IND_CHICKEN_MANCHURIAN_DRY', 'chicken-manchurian-dry', 'Chicken Manchurian Dry', 'Crispy chicken pieces tossed in tangy-spicy Manchurian sauce', 'manchurian', 'iconic', 'chicken', 'deep_fried', 35, 3, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['chicken', 'crispy', 'popular'], 96),
('IND_CHICKEN_MANCHURIAN_GRAVY', 'chicken-manchurian-gravy', 'Chicken Manchurian Gravy', 'Fried chicken in luscious Manchurian gravy, served with steamed rice', 'manchurian', 'classic', 'chicken', 'deep_fried', 40, 3, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'soy', 'egg'], ARRAY['chicken', 'gravy', 'main-course'], 92),
('IND_VEG_MANCHURIAN', 'veg-manchurian', 'Veg Manchurian', 'Mixed vegetable balls in tangy Manchurian sauce', 'manchurian', 'classic', 'vegetable', 'deep_fried', 40, 3, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['vegetable', 'balls', 'classic'], 88),
('IND_PANEER_MANCHURIAN', 'paneer-manchurian', 'Paneer Manchurian', 'Crispy paneer cubes in spicy Manchurian sauce', 'manchurian', 'classic', 'paneer', 'deep_fried', 30, 3, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy', 'dairy'], ARRAY['paneer', 'indian-chinese', 'popular'], 90),

-- CHILLI (6)
('IND_CHILLI_CHICKEN_DRY', 'chilli-chicken-dry', 'Chilli Chicken Dry', 'Crispy fried chicken tossed with green chillies, bell peppers, and spicy sauce', 'chilli', 'iconic', 'chicken', 'stir_fried', 30, 4, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'soy', 'egg'], ARRAY['signature', 'spicy', 'street-food'], 98),
('IND_CHILLI_CHICKEN_GRAVY', 'chilli-chicken-gravy', 'Chilli Chicken Gravy', 'Fried chicken in rich, spicy gravy with onions and peppers', 'chilli', 'classic', 'chicken', 'stir_fried', 35, 4, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'soy', 'egg'], ARRAY['gravy', 'spicy', 'main-course'], 90),
('IND_CHILLI_PANEER_DRY', 'chilli-paneer-dry', 'Chilli Paneer Dry', 'Crispy paneer cubes stir-fried with green chillies and colorful peppers', 'chilli', 'iconic', 'paneer', 'stir_fried', 25, 4, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy', 'dairy'], ARRAY['paneer', 'vegetarian', 'popular'], 95),
('IND_CHILLI_PANEER_GRAVY', 'chilli-paneer-gravy', 'Chilli Paneer Gravy', 'Paneer cubes in spicy Indo-Chinese gravy', 'chilli', 'classic', 'paneer', 'stir_fried', 30, 4, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy', 'dairy'], ARRAY['paneer', 'gravy', 'vegetarian'], 88),
('IND_CHILLI_POTATO', 'chilli-potato', 'Chilli Potato', 'Crispy potato fingers tossed in spicy chilli sauce with peppers', 'chilli', 'iconic', 'vegetable', 'deep_fried', 25, 3, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['potato', 'crispy', 'street-food'], 92),
('IND_CHILLI_GARLIC_NOODLES', 'chilli-garlic-noodles', 'Chilli Garlic Noodles', 'Spicy noodles with loads of garlic and green chillies', 'chilli', 'classic', 'vegetable', 'stir_fried', 20, 4, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['noodles', 'spicy', 'garlic'], 85),

-- NOODLES (6)
('IND_VEG_HAKKA_NOODLES', 'veg-hakka-noodles', 'Veg Hakka Noodles', 'Stir-fried noodles with cabbage, carrots, bell peppers, and Indo-Chinese sauces', 'noodles', 'iconic', 'vegetable', 'stir_fried', 20, 2, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['signature', 'street-food', 'popular'], 98),
('IND_CHICKEN_HAKKA_NOODLES', 'chicken-hakka-noodles', 'Chicken Hakka Noodles', 'Hakka noodles stir-fried with chicken strips and vegetables', 'noodles', 'iconic', 'chicken', 'stir_fried', 25, 2, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['chicken', 'popular', 'main-course'], 95),
('IND_EGG_HAKKA_NOODLES', 'egg-hakka-noodles', 'Egg Hakka Noodles', 'Hakka noodles with scrambled eggs and vegetables', 'noodles', 'classic', 'egg', 'stir_fried', 20, 2, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy', 'egg'], ARRAY['egg', 'quick', 'popular'], 90),
('IND_SCHEZWAN_NOODLES', 'schezwan-noodles', 'Schezwan Noodles', 'Spicy noodles tossed in fiery Schezwan sauce with vegetables', 'noodles', 'iconic', 'vegetable', 'stir_fried', 20, 4, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['spicy', 'schezwan', 'popular'], 92),
('IND_TRIPLE_SCHEZWAN_NOODLES', 'triple-schezwan-noodles', 'Triple Schezwan Noodles', 'Noodles, fried rice, and Manchurian combined with Schezwan sauce', 'noodles', 'modern', 'vegetable', 'stir_fried', 30, 4, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['combo', 'spicy', 'indulgent'], 85),
('IND_SINGAPORE_NOODLES', 'singapore-noodles', 'Singapore Noodles', 'Curry-flavored rice noodles with vegetables and Indo-Chinese spices', 'noodles', 'classic', 'vegetable', 'stir_fried', 25, 3, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['curry', 'rice-noodles', 'fusion'], 80),

-- RICE (5)
('IND_VEG_FRIED_RICE', 'veg-fried-rice', 'Veg Fried Rice', 'Classic Indo-Chinese fried rice with mixed vegetables and soy sauce', 'rice', 'iconic', 'vegetable', 'stir_fried', 20, 2, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['soy'], ARRAY['signature', 'popular', 'quick'], 95),
('IND_CHICKEN_FRIED_RICE', 'chicken-fried-rice', 'Chicken Fried Rice', 'Fried rice with diced chicken and Indo-Chinese seasonings', 'rice', 'iconic', 'chicken', 'stir_fried', 25, 2, '{"gluten_free": false}'::jsonb, ARRAY['soy'], ARRAY['chicken', 'popular', 'main-course'], 93),
('IND_EGG_FRIED_RICE', 'egg-fried-rice', 'Egg Fried Rice', 'Fried rice with scrambled eggs and vegetables', 'rice', 'classic', 'egg', 'stir_fried', 20, 1, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['soy', 'egg'], ARRAY['egg', 'quick', 'classic'], 90),
('IND_SCHEZWAN_FRIED_RICE', 'schezwan-fried-rice', 'Schezwan Fried Rice', 'Spicy fried rice with fiery Schezwan sauce', 'rice', 'iconic', 'vegetable', 'stir_fried', 20, 4, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['soy'], ARRAY['spicy', 'schezwan', 'popular'], 92),
('IND_MANCHURIAN_FRIED_RICE', 'manchurian-fried-rice', 'Manchurian Fried Rice', 'Fried rice topped with vegetable Manchurian balls', 'rice', 'classic', 'vegetable', 'stir_fried', 35, 3, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['soy', 'gluten'], ARRAY['combo', 'manchurian', 'popular'], 88),

-- SOUP (5)
('IND_VEG_HOT_SOUR_SOUP', 'veg-hot-sour-soup', 'Veg Hot and Sour Soup', 'Tangy soup with vegetables, tofu, and a spicy kick', 'soup', 'iconic', 'vegetable', 'simmered', 20, 3, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['soy', 'gluten'], ARRAY['signature', 'tangy', 'popular'], 92),
('IND_CHICKEN_HOT_SOUR_SOUP', 'chicken-hot-sour-soup', 'Chicken Hot and Sour Soup', 'Classic hot and sour soup with shredded chicken', 'soup', 'iconic', 'chicken', 'simmered', 25, 3, '{"gluten_free": false}'::jsonb, ARRAY['soy', 'gluten'], ARRAY['chicken', 'tangy', 'warming'], 90),
('IND_SWEET_CORN_SOUP_VEG', 'sweet-corn-soup-veg', 'Sweet Corn Soup (Veg)', 'Creamy corn soup with vegetables, Indo-Chinese style', 'soup', 'classic', 'vegetable', 'simmered', 15, 1, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten'], ARRAY['sweet', 'corn', 'mild'], 85),
('IND_SWEET_CORN_CHICKEN_SOUP', 'sweet-corn-chicken-soup', 'Sweet Corn Chicken Soup', 'Creamy corn soup with shredded chicken', 'soup', 'classic', 'chicken', 'simmered', 20, 1, '{"gluten_free": false}'::jsonb, ARRAY['gluten'], ARRAY['chicken', 'corn', 'creamy'], 88),
('IND_MANCHOW_SOUP', 'manchow-soup', 'Manchow Soup', 'Spicy vegetable soup topped with crispy fried noodles', 'soup', 'iconic', 'vegetable', 'simmered', 25, 3, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['soy', 'gluten'], ARRAY['spicy', 'crispy-noodles', 'signature'], 90),

-- STARTERS (7)
('IND_SPRING_ROLLS_VEG', 'spring-rolls-veg', 'Veg Spring Rolls', 'Crispy rolls stuffed with cabbage, carrots, and noodles', 'starter', 'iconic', 'vegetable', 'deep_fried', 30, 1, '{"vegetarian": true, "vegan": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['crispy', 'appetizer', 'popular'], 92),
('IND_CHICKEN_SPRING_ROLLS', 'chicken-spring-rolls', 'Chicken Spring Rolls', 'Crispy rolls with minced chicken and vegetable filling', 'starter', 'classic', 'chicken', 'deep_fried', 35, 1, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['chicken', 'crispy', 'appetizer'], 88),
('IND_CRISPY_HONEY_CHILLI_POTATO', 'crispy-honey-chilli-potato', 'Honey Chilli Potato', 'Crispy potato fingers glazed with sweet honey and spicy chilli sauce', 'starter', 'iconic', 'vegetable', 'deep_fried', 25, 2, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['sweet-spicy', 'crispy', 'popular'], 94),
('IND_DRAGON_CHICKEN', 'dragon-chicken', 'Dragon Chicken', 'Crispy chicken in fiery dragon sauce with dried red chillies', 'starter', 'classic', 'chicken', 'deep_fried', 30, 5, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'soy', 'egg'], ARRAY['extra-spicy', 'crispy', 'bold'], 85),
('IND_GOLDEN_FRIED_PRAWNS', 'golden-fried-prawns', 'Golden Fried Prawns', 'Crispy battered prawns served with sweet chilli sauce', 'starter', 'classic', 'shrimp', 'deep_fried', 25, 1, '{"gluten_free": false}'::jsonb, ARRAY['shellfish', 'gluten', 'egg'], ARRAY['prawns', 'crispy', 'seafood'], 82),
('IND_AMERICAN_CHOPSUEY', 'american-chopsuey', 'American Chopsuey', 'Crispy fried noodles topped with sweet and sour vegetable gravy', 'starter', 'iconic', 'vegetable', 'deep_fried', 35, 2, '{"vegetarian": true, "gluten_free": false}'::jsonb, ARRAY['gluten', 'soy'], ARRAY['sweet-sour', 'crispy-noodles', 'classic'], 88),
('IND_DRUMS_OF_HEAVEN', 'drums-of-heaven', 'Drums of Heaven', 'Crispy chicken lollipops in spicy Indo-Chinese sauce', 'starter', 'iconic', 'chicken', 'deep_fried', 40, 3, '{"gluten_free": false}'::jsonb, ARRAY['gluten', 'soy', 'egg'], ARRAY['chicken-lollipop', 'signature', 'party-food'], 95);

-- Success message
SELECT 'Inserted 35 Indo-Chinese dishes' AS status;
