-- BURGERS Batch 3
-- Items: 21 to 30 of 45
-- Generated: 2025-12-15T12:53:40.038Z

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-brisket-burger', 'smoked-brisket-burger', '{"en":"Smoked Brisket Burger","it":"Burger con Brisket Affumicato","vi":"Burger Thịt Bò Ức Hun Khói"}'::jsonb, '{"en":"Beef patty topped with 12-hour smoked brisket, coleslaw, and tangy BBQ sauce","it":"Hamburger di manzo con brisket affumicato 12 ore, coleslaw e salsa BBQ piccante","vi":"Thịt bò với brisket hun khói 12 giờ, salad bắp cải và sốt BBQ chua ngọt"}'::jsonb, NULL, 'signature', 'gourmet', '{"brisket","smoked","texas","bbq","gourmet"}', 'brioche', true, 'beef', 150, 1, 'medium', '{"smoked_gouda"}', '{"smoked_brisket","coleslaw","pickles"}', '{"bbq_sauce"}', false, 1, '{"country":"USA","country_code":"US","region":"Texas"}'::jsonb, NULL, '{"portion_size":"large","is_shareable":false,"recommended_pairing":["bourbon","craft_beer","iced_tea"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs"],"calories_estimate":880,"protein_g":55,"carbs_g":48,"fat_g":52,"fiber_g":3}'::jsonb, NULL, '{}', 86, '{}', NULL, '{"cost_level":"high","suggested_price_usd":20}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-short-rib-burger', 'short-rib-burger', '{"en":"Braised Short Rib Burger","it":"Burger con Short Rib Brasato","vi":"Burger Sườn Bò Hầm"}'::jsonb, '{"en":"Ground short rib patty with red wine reduction, gruyère, and crispy shallots","it":"Hamburger di short rib macinato con riduzione di vino rosso, gruyère e scalogni croccanti","vi":"Thịt sườn bò xay với sốt vang đỏ, gruyère và hẹ tây giòn"}'::jsonb, NULL, 'signature', 'gourmet', '{"short_rib","braised","wine","gourmet","premium"}', 'brioche', true, 'blend', 200, 1, 'medium', '{"gruyere"}', '{"crispy_shallots","arugula"}', '{"red_wine_reduction"}', false, 0, '{"country":"USA","country_code":"US"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["red_wine","craft_beer"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs","sulfites"],"calories_estimate":750,"protein_g":42,"carbs_g":40,"fat_g":46,"fiber_g":2}'::jsonb, NULL, '{}', 80, '{}', NULL, '{"cost_level":"high","suggested_price_usd":19}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-kimchi-burger', 'korean-kimchi-burger', '{"en":"Korean Kimchi Burger","it":"Burger Coreano al Kimchi","vi":"Burger Kim Chi Hàn Quốc"}'::jsonb, '{"en":"Korean-inspired burger with kimchi, gochujang mayo, and sesame on a steamed bun","it":"Burger ispirazione coreana con kimchi, mayo al gochujang e sesamo su panino al vapore","vi":"Burger cảm hứng Hàn Quốc với kim chi, mayo gochujang và mè trên bánh hấp"}'::jsonb, NULL, 'modern', 'international', '{"korean","kimchi","gochujang","fusion","spicy"}', 'brioche', false, 'beef', 170, 1, 'medium', '{}', '{"kimchi","pickled_cucumber","sesame_seeds","scallions"}', '{"gochujang_mayo","sesame_oil"}', true, 3, '{"country":"Korea / USA","country_code":"KR"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["soju","korean_beer","iced_tea"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":false,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","sesame","soy"],"calories_estimate":580,"protein_g":32,"carbs_g":42,"fat_g":30,"fiber_g":4}'::jsonb, NULL, '{}', 84, '{}', NULL, '{"cost_level":"high","suggested_price_usd":17}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-teriyaki-burger', 'teriyaki-burger', '{"en":"Teriyaki Burger","it":"Teriyaki Burger","vi":"Burger Teriyaki"}'::jsonb, '{"en":"Japanese-style burger with teriyaki glaze, grilled pineapple, and wasabi mayo","it":"Burger stile giapponese con glassa teriyaki, ananas grigliato e mayo al wasabi","vi":"Burger kiểu Nhật với sốt teriyaki, dứa nướng và mayo wasabi"}'::jsonb, NULL, 'classic', 'international', '{"teriyaki","japanese","pineapple","fusion","sweet"}', 'brioche', true, 'beef', 170, 1, 'medium', '{}', '{"grilled_pineapple","lettuce","pickled_ginger"}', '{"teriyaki_sauce","wasabi_mayo"}', false, 1, '{"country":"Japan / USA","country_code":"JP"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["sake","japanese_beer","green_tea"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","soy","eggs"],"calories_estimate":620,"protein_g":34,"carbs_g":52,"fat_g":28,"fiber_g":3}'::jsonb, NULL, '{}', 82, '{}', NULL, '{"cost_level":"medium","suggested_price_usd":15}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-lamb-burger', 'mediterranean-lamb-burger', '{"en":"Mediterranean Lamb Burger","it":"Burger di Agnello Mediterraneo","vi":"Burger Cừu Địa Trung Hải"}'::jsonb, '{"en":"Seasoned lamb patty with feta, tzatziki, cucumber, and red onion","it":"Hamburger di agnello speziato con feta, tzatziki, cetriolo e cipolla rossa","vi":"Thịt cừu gia vị với feta, tzatziki, dưa chuột và hành đỏ"}'::jsonb, NULL, 'classic', 'international', '{"lamb","mediterranean","greek","feta","tzatziki"}', 'brioche', true, 'lamb', 180, 1, 'medium', '{"feta"}', '{"cucumber","red_onion","tomato","arugula"}', '{"tzatziki"}', false, 0, '{"country":"Greece","country_code":"GR"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["red_wine","ouzo","retsina"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs"],"calories_estimate":650,"protein_g":38,"carbs_g":38,"fat_g":38,"fiber_g":3}'::jsonb, NULL, '{}', 80, '{}', NULL, '{"cost_level":"high","suggested_price_usd":18}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-aussie-burger', 'aussie-burger', '{"en":"Aussie Burger","it":"Aussie Burger","vi":"Burger Úc"}'::jsonb, '{"en":"Australian-style with beetroot, fried egg, pineapple, bacon, and BBQ sauce","it":"Stile australiano con barbabietola, uovo fritto, ananas, bacon e salsa BBQ","vi":"Kiểu Úc với củ dền, trứng chiên, dứa, bacon và sốt BBQ"}'::jsonb, NULL, 'traditional', 'international', '{"aussie","australian","beetroot","egg","pineapple"}', 'sesame', true, 'beef', 170, 1, 'medium', '{"cheddar"}', '{"beetroot","fried_egg","pineapple","bacon","lettuce","tomato","onion"}', '{"bbq_sauce","mayonnaise"}', false, 0, '{"country":"Australia","country_code":"AU"}'::jsonb, NULL, '{"portion_size":"large","is_shareable":false,"recommended_pairing":["beer","lemonade"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs","sesame"],"calories_estimate":820,"protein_g":45,"carbs_g":52,"fat_g":48,"fiber_g":4}'::jsonb, NULL, '{}', 76, '{}', NULL, '{"cost_level":"high","suggested_price_usd":17}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-pimento-cheese-burger', 'pimento-cheese-burger', '{"en":"Pimento Cheese Burger","it":"Burger al Pimento Cheese","vi":"Burger Phô Mai Pimento"}'::jsonb, '{"en":"Southern classic with house-made pimento cheese, bacon, and fried green tomato","it":"Classico del Sud con pimento cheese fatto in casa, bacon e pomodoro verde fritto","vi":"Cổ điển miền Nam với phô mai pimento tự làm, bacon và cà chua xanh chiên"}'::jsonb, NULL, 'traditional', 'american_regional', '{"southern","pimento","bacon","regional","traditional"}', 'brioche', true, 'beef', 170, 1, 'medium', '{"pimento_cheese"}', '{"bacon","fried_green_tomato","lettuce"}', '{}', false, 1, '{"country":"USA","country_code":"US","region":"South"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["sweet_tea","bourbon","beer"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs"],"calories_estimate":720,"protein_g":38,"carbs_g":42,"fat_g":46,"fiber_g":3}'::jsonb, NULL, '{}', 74, '{}', NULL, '{"cost_level":"high","suggested_price_usd":16}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-elk-burger', 'elk-burger', '{"en":"Wild Elk Burger","it":"Burger di Alce Selvatico","vi":"Burger Nai Sừng Tấm Hoang Dã"}'::jsonb, '{"en":"Lean elk patty with huckleberry compote, brie, and arugula","it":"Hamburger magro di alce con composta di mirtillo, brie e rucola","vi":"Thịt nai sừng tấm nạc với mứt việt quất, brie và arugula"}'::jsonb, NULL, 'signature', 'gourmet', '{"elk","game","wild","lean","gourmet"}', 'brioche', true, 'other', 180, 1, 'medium', '{"brie"}', '{"arugula","caramelized_onions"}', '{"huckleberry_compote"}', false, 0, '{"country":"USA","country_code":"US","region":"Pacific Northwest"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["pinot_noir","craft_beer"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs"],"calories_estimate":520,"protein_g":38,"carbs_g":36,"fat_g":24,"fiber_g":2}'::jsonb, NULL, '{}', 68, '{}', NULL, '{"cost_level":"premium","suggested_price_usd":24}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-breakfast-burger', 'breakfast-burger', '{"en":"Breakfast Burger","it":"Breakfast Burger","vi":"Burger Bữa Sáng"}'::jsonb, '{"en":"Beef patty with fried egg, bacon, hash brown, American cheese, and maple syrup drizzle","it":"Hamburger di manzo con uovo fritto, bacon, hash brown, formaggio americano e filo di sciroppo d''acero","vi":"Thịt bò với trứng chiên, bacon, khoai tây chiên, phô mai Mỹ và mật phong"}'::jsonb, NULL, 'modern', 'american_classic', '{"breakfast","egg","bacon","brunch","hearty"}', 'brioche', true, 'beef', 150, 1, 'medium', '{"american"}', '{"fried_egg","bacon","hash_brown"}', '{"maple_syrup","ketchup"}', false, 0, '{"country":"USA","country_code":"US"}'::jsonb, NULL, '{"portion_size":"large","is_shareable":false,"recommended_pairing":["coffee","orange_juice","bloody_mary"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs"],"calories_estimate":920,"protein_g":48,"carbs_g":58,"fat_g":56,"fiber_g":3}'::jsonb, NULL, '{}', 84, '{}', NULL, '{"cost_level":"medium","suggested_price_usd":15}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO burgers (id, slug, name, description, tagline, status, style, tags, bun_type, bun_is_toasted, patty_type, patty_weight_g, patty_count, patty_recommended_cook, cheeses, toppings, sauces, is_spicy, spice_level, origin, history, serving, dietary, customization, variations, popularity, related_burgers, media, pricing)
VALUES ('burger-birria-burger', 'birria-burger', '{"en":"Birria Burger","it":"Burger alla Birria","vi":"Burger Birria"}'::jsonb, '{"en":"Mexican-inspired with birria-braised beef, oaxaca cheese, and consommé dipping sauce","it":"Ispirazione messicana con manzo brasato alla birria, formaggio oaxaca e consommé per intingere","vi":"Cảm hứng Mexico với thịt bò hầm birria, phô mai oaxaca và nước dùng chấm"}'::jsonb, NULL, 'modern', 'international', '{"birria","mexican","trending","consomme","fusion"}', 'brioche', true, 'beef', 170, 1, 'medium', '{"oaxaca"}', '{"cilantro","onion"}', '{"birria_consomme","salsa_verde"}', true, 2, '{"country":"Mexico / USA","country_code":"MX","region":"Jalisco"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["mexican_beer","margarita","horchata"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":680,"protein_g":42,"carbs_g":42,"fat_g":38,"fiber_g":2}'::jsonb, NULL, '{}', 90, '{}', NULL, '{"cost_level":"high","suggested_price_usd":18}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();