-- ============================================
-- JAPANESE DATABASE - Complete Data Import
-- 73 Japanese dishes (non-sushi)
-- ============================================

-- RAMEN (8 dishes)
INSERT INTO japanese (id, slug, name, description, japanese_name, japanese_script, category, status, region, protein_type, cooking_method, is_izakaya_style, is_street_food, is_comfort_food, served_hot, broth_based, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('JPN_SHOYU_RAMEN', 'shoyu-ramen', 'Shoyu Ramen', 'Classic soy sauce-based ramen with clear brown broth, chashu pork, bamboo shoots, nori and soft-boiled egg', 'Shoyu Ramen', '醤油ラーメン', 'ramen', 'signature', 'tokyo', 'pork', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 480, 28, 52, 18, 0, ARRAY['ramen', 'soy-sauce', 'tokyo', 'classic', 'noodles'], 95),
('JPN_TONKOTSU_RAMEN', 'tonkotsu-ramen', 'Tonkotsu Ramen', 'Rich and creamy pork bone broth ramen from Kyushu, milky white soup with thin noodles and chashu', 'Tonkotsu Ramen', '豚骨ラーメン', 'ramen', 'signature', 'kyushu', 'pork', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'eggs', 'sesame'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 620, 32, 48, 34, 0, ARRAY['ramen', 'pork-bone', 'kyushu', 'creamy', 'rich'], 98),
('JPN_MISO_RAMEN', 'miso-ramen', 'Miso Ramen', 'Hearty miso-based ramen from Hokkaido with rich fermented soybean broth, butter and corn', 'Miso Ramen', '味噌ラーメン', 'ramen', 'signature', 'hokkaido', 'pork', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'dairy'], FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 580, 30, 55, 28, 1, ARRAY['ramen', 'miso', 'hokkaido', 'hearty', 'butter'], 92),
('JPN_SHIO_RAMEN', 'shio-ramen', 'Shio Ramen', 'Light and delicate salt-based ramen with clear golden broth, showcasing pure umami flavors', 'Shio Ramen', '塩ラーメン', 'ramen', 'classic', 'hokkaido', 'pork', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 420, 26, 48, 14, 0, ARRAY['ramen', 'salt', 'light', 'clear-broth', 'delicate'], 78),
('JPN_TANTANMEN', 'tantanmen', 'Tantanmen', 'Spicy sesame-based ramen with ground pork, chili oil and bok choy, Japanese take on Sichuan dandan noodles', 'Tantanmen', '担々麺', 'ramen', 'popular', 'national', 'pork', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'sesame'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 550, 28, 50, 28, 3, ARRAY['ramen', 'spicy', 'sesame', 'sichuan-inspired'], 82),
('JPN_TSUKEMEN', 'tsukemen', 'Tsukemen', 'Dipping ramen with thick noodles served separately from concentrated rich broth', 'Tsukemen', 'つけ麺', 'ramen', 'popular', 'tokyo', 'pork', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'eggs', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 520, 30, 55, 20, 0, ARRAY['ramen', 'dipping', 'thick-noodles', 'tokyo'], 85),
('JPN_HAKATA_RAMEN', 'hakata-ramen', 'Hakata Ramen', 'Fukuoka specialty with super thin noodles in rich tonkotsu broth, known for kaedama (noodle refills)', 'Hakata Ramen', '博多ラーメン', 'ramen', 'regional', 'kyushu', 'pork', 'boiled', FALSE, TRUE, TRUE, TRUE, TRUE, ARRAY['gluten', 'sesame'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 580, 30, 45, 32, 0, ARRAY['ramen', 'hakata', 'fukuoka', 'thin-noodles', 'kaedama'], 88),
('JPN_VEGETABLE_RAMEN', 'yasai-ramen', 'Yasai Ramen', 'Vegetable ramen with kombu and shiitake-based broth loaded with seasonal vegetables', 'Yasai Ramen', '野菜ラーメン', 'ramen', 'active', 'national', 'vegetarian', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'sesame'], FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 380, 14, 58, 10, 0, ARRAY['ramen', 'vegetarian', 'vegan', 'vegetables', 'healthy'], 65);

-- UDON & SOBA (12 dishes)
INSERT INTO japanese (id, slug, name, description, japanese_name, japanese_script, category, status, region, protein_type, cooking_method, is_izakaya_style, is_street_food, is_comfort_food, served_hot, broth_based, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('JPN_KITSUNE_UDON', 'kitsune-udon', 'Kitsune Udon', 'Udon noodles in dashi broth topped with sweet fried tofu pouches, a beloved Osaka classic', 'Kitsune Udon', 'きつねうどん', 'udon_soba', 'signature', 'osaka', 'tofu', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 380, 14, 62, 8, 0, ARRAY['udon', 'osaka', 'tofu', 'comfort-food'], 88),
('JPN_TANUKI_UDON', 'tanuki-udon', 'Tanuki Udon', 'Udon noodles topped with crunchy tempura batter bits (tenkasu) in savory dashi broth', 'Tanuki Udon', 'たぬきうどん', 'udon_soba', 'classic', 'tokyo', 'none', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 420, 12, 68, 12, 0, ARRAY['udon', 'tokyo', 'tenkasu', 'crispy'], 75),
('JPN_TEMPURA_UDON', 'tempura-udon', 'Tempura Udon', 'Hot udon in dashi broth crowned with crispy shrimp tempura, a satisfying combination', 'Tempura Udon', '天ぷらうどん', 'udon_soba', 'popular', 'national', 'seafood', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'fish', 'shellfish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 520, 22, 65, 18, 0, ARRAY['udon', 'tempura', 'shrimp', 'crispy'], 85),
('JPN_NABEYAKI_UDON', 'nabeyaki-udon', 'Nabeyaki Udon', 'Hot pot udon served in an earthenware pot with tempura, egg, chicken and vegetables', 'Nabeyaki Udon', '鍋焼きうどん', 'udon_soba', 'traditional', 'national', 'mixed', 'hot_pot', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'fish', 'shellfish', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 580, 32, 62, 22, 0, ARRAY['udon', 'hot-pot', 'winter', 'hearty'], 78),
('JPN_CURRY_UDON', 'curry-udon', 'Curry Udon', 'Thick udon noodles swimming in Japanese curry-flavored broth, rich and warming', 'Kare Udon', 'カレーうどん', 'udon_soba', 'popular', 'national', 'pork', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 620, 24, 72, 26, 2, ARRAY['udon', 'curry', 'fusion', 'rich'], 82),
('JPN_SANUKI_UDON', 'sanuki-udon', 'Sanuki Udon', 'Famous Kagawa Prefecture udon with firm, chewy noodles, served simply to highlight texture', 'Sanuki Udon', '讃岐うどん', 'udon_soba', 'regional', 'national', 'none', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 350, 10, 65, 4, 0, ARRAY['udon', 'sanuki', 'kagawa', 'chewy', 'simple'], 80),
('JPN_ZARU_SOBA', 'zaru-soba', 'Zaru Soba', 'Chilled buckwheat noodles served on a bamboo tray with dipping sauce, wasabi and green onion', 'Zaru Soba', 'ざるそば', 'udon_soba', 'signature', 'national', 'none', 'boiled', FALSE, FALSE, TRUE, FALSE, FALSE, ARRAY['gluten', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 320, 12, 58, 2, 1, ARRAY['soba', 'cold', 'summer', 'refreshing', 'buckwheat'], 90),
('JPN_KAKE_SOBA', 'kake-soba', 'Kake Soba', 'Simple hot soba noodles in clear dashi broth, garnished with green onion and shichimi', 'Kake Soba', 'かけそば', 'udon_soba', 'classic', 'national', 'none', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 300, 10, 55, 2, 0, ARRAY['soba', 'hot', 'simple', 'traditional'], 72),
('JPN_TEMPURA_SOBA', 'tempura-soba', 'Tempura Soba', 'Buckwheat noodles in hot broth topped with crispy shrimp or vegetable tempura', 'Tempura Soba', '天ぷらそば', 'udon_soba', 'popular', 'national', 'seafood', 'boiled', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['gluten', 'soy', 'fish', 'shellfish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 480, 20, 60, 16, 0, ARRAY['soba', 'tempura', 'crispy', 'classic'], 82),
('JPN_TORORO_SOBA', 'tororo-soba', 'Tororo Soba', 'Cold soba topped with grated yamaimo (mountain yam), creating a slimy but delicious texture', 'Tororo Soba', 'とろろそば', 'udon_soba', 'traditional', 'national', 'vegetarian', 'boiled', FALSE, FALSE, TRUE, FALSE, FALSE, ARRAY['gluten', 'soy', 'fish', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 380, 14, 62, 8, 0, ARRAY['soba', 'cold', 'yam', 'unique-texture'], 68),
('JPN_YAKISOBA', 'yakisoba', 'Yakisoba', 'Stir-fried noodles with pork, cabbage and sweet-savory sauce, topped with pickled ginger and aonori', 'Yakisoba', '焼きそば', 'udon_soba', 'signature', 'national', 'pork', 'pan_fried', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['gluten', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 520, 22, 58, 22, 0, ARRAY['noodles', 'stir-fried', 'festival', 'street-food'], 92),
('JPN_SOMEN', 'somen', 'Somen', 'Very thin wheat noodles served ice-cold in summer, dipped in tsuyu with ginger and green onion', 'Somen', 'そうめん', 'udon_soba', 'seasonal', 'national', 'none', 'boiled', FALSE, FALSE, TRUE, FALSE, FALSE, ARRAY['gluten', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 280, 8, 55, 1, 0, ARRAY['noodles', 'cold', 'summer', 'refreshing', 'thin'], 75);

-- DONBURI (8 dishes)
INSERT INTO japanese (id, slug, name, description, japanese_name, japanese_script, category, status, region, protein_type, cooking_method, is_izakaya_style, is_street_food, is_comfort_food, served_hot, broth_based, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('JPN_GYUDON', 'gyudon', 'Gyudon', 'Thinly sliced beef and onions simmered in sweet soy sauce served over rice, Japanese fast food staple', 'Gyudon', '牛丼', 'donburi', 'signature', 'national', 'beef', 'simmered', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['soy', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 650, 28, 78, 24, 0, ARRAY['donburi', 'beef', 'fast-food', 'comfort'], 95),
('JPN_KATSUDON', 'katsudon', 'Katsudon', 'Crispy breaded pork cutlet simmered with egg and onion over rice, ultimate comfort food', 'Katsudon', 'カツ丼', 'donburi', 'signature', 'national', 'pork', 'deep_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'soy', 'eggs', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 780, 35, 82, 32, 0, ARRAY['donburi', 'tonkatsu', 'egg', 'hearty'], 92),
('JPN_OYAKODON', 'oyakodon', 'Oyakodon', 'Chicken and egg rice bowl, name means "parent and child" referring to chicken and egg', 'Oyakodon', '親子丼', 'donburi', 'signature', 'national', 'chicken', 'simmered', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['soy', 'eggs', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 580, 32, 72, 18, 0, ARRAY['donburi', 'chicken', 'egg', 'classic'], 90),
('JPN_TENDON', 'tendon', 'Tendon', 'Assorted tempura served over rice with sweet tentsuyu sauce drizzled on top', 'Tendon', '天丼', 'donburi', 'popular', 'tokyo', 'seafood', 'deep_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'soy', 'fish', 'shellfish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 680, 24, 85, 26, 0, ARRAY['donburi', 'tempura', 'crispy', 'tokyo'], 85),
('JPN_UNADON', 'unagi-donburi', 'Unadon', 'Grilled freshwater eel glazed with sweet kabayaki sauce over rice, summer delicacy', 'Unadon', 'うな丼', 'donburi', 'premium', 'national', 'seafood', 'grilled', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['soy', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 620, 30, 75, 22, 0, ARRAY['donburi', 'eel', 'premium', 'summer'], 82),
('JPN_KAISENDON', 'kaisen-donburi', 'Kaisendon', 'Fresh assorted sashimi served over sushi rice, a seafood lover dream bowl', 'Kaisendon', '海鮮丼', 'donburi', 'premium', 'hokkaido', 'seafood', 'raw', FALSE, FALSE, FALSE, FALSE, FALSE, ARRAY['soy', 'fish', 'shellfish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 480, 35, 55, 12, 1, ARRAY['donburi', 'sashimi', 'seafood', 'premium', 'hokkaido'], 88),
('JPN_SOBORO_DON', 'soboro-don', 'Soboro Don', 'Three-color rice bowl with seasoned ground chicken, scrambled egg and green vegetables', 'Soboro Don', 'そぼろ丼', 'donburi', 'classic', 'national', 'chicken', 'pan_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['soy', 'eggs'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 520, 28, 68, 14, 0, ARRAY['donburi', 'bento-style', 'colorful', 'home-cooking'], 72),
('JPN_BUTADON', 'butadon', 'Butadon', 'Grilled pork slices with sweet-savory glaze over rice, Hokkaido specialty', 'Butadon', '豚丼', 'donburi', 'regional', 'hokkaido', 'pork', 'grilled', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 680, 32, 75, 28, 0, ARRAY['donburi', 'pork', 'grilled', 'hokkaido'], 78);

-- TEMPURA & FRIED (9 dishes)
INSERT INTO japanese (id, slug, name, description, japanese_name, japanese_script, category, status, region, protein_type, cooking_method, is_izakaya_style, is_street_food, is_comfort_food, served_hot, broth_based, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('JPN_EBI_TEMPURA', 'ebi-tempura', 'Ebi Tempura', 'Classic shrimp tempura with light, crispy batter, served with tentsuyu dipping sauce', 'Ebi Tempura', '海老天ぷら', 'tempura', 'signature', 'national', 'seafood', 'deep_fried', TRUE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'shellfish', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 320, 20, 28, 16, 0, ARRAY['tempura', 'shrimp', 'crispy', 'classic'], 95),
('JPN_YASAI_TEMPURA', 'yasai-tempura', 'Yasai Tempura', 'Assorted vegetable tempura including sweet potato, eggplant, shiso and kabocha', 'Yasai Tempura', '野菜天ぷら', 'tempura', 'popular', 'national', 'vegetarian', 'deep_fried', TRUE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, 380, 6, 48, 18, 0, ARRAY['tempura', 'vegetables', 'vegetarian', 'crispy'], 85),
('JPN_KAKIAGE', 'kakiage', 'Kakiage', 'Mixed vegetable and shrimp tempura fritter, crunchy disc of deliciousness', 'Kakiage', 'かき揚げ', 'tempura', 'classic', 'national', 'seafood', 'deep_fried', TRUE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'shellfish', 'soy', 'fish'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 280, 12, 32, 14, 0, ARRAY['tempura', 'fritter', 'mixed', 'udon-topping'], 78),
('JPN_TONKATSU', 'tonkatsu', 'Tonkatsu', 'Golden breaded deep-fried pork cutlet served with shredded cabbage and tonkatsu sauce', 'Tonkatsu', 'とんかつ', 'tonkatsu', 'signature', 'national', 'pork', 'deep_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 580, 32, 35, 38, 0, ARRAY['tonkatsu', 'pork', 'crispy', 'panko'], 95),
('JPN_HIRE_KATSU', 'hire-katsu', 'Hire Katsu', 'Tender pork tenderloin cutlet, leaner alternative to regular tonkatsu', 'Hire Katsu', 'ヒレカツ', 'tonkatsu', 'popular', 'national', 'pork', 'deep_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 480, 35, 32, 24, 0, ARRAY['tonkatsu', 'pork', 'lean', 'tender'], 82),
('JPN_CHICKEN_KATSU', 'chicken-katsu', 'Chicken Katsu', 'Crispy breaded chicken cutlet, lighter alternative to tonkatsu', 'Chikin Katsu', 'チキンカツ', 'tonkatsu', 'popular', 'national', 'chicken', 'deep_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 420, 38, 30, 18, 0, ARRAY['katsu', 'chicken', 'crispy', 'lighter'], 85),
('JPN_KARAAGE', 'karaage', 'Karaage', 'Japanese fried chicken marinated in soy, ginger and garlic, double-fried for extra crunch', 'Karaage', '唐揚げ', 'tempura', 'signature', 'national', 'chicken', 'deep_fried', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 380, 28, 18, 24, 0, ARRAY['fried-chicken', 'izakaya', 'crispy', 'popular'], 98),
('JPN_KOROKKE', 'korokke', 'Korokke', 'Japanese croquettes filled with mashed potato and meat or vegetables, panko-breaded', 'Korokke', 'コロッケ', 'tempura', 'classic', 'national', 'beef', 'deep_fried', FALSE, TRUE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 280, 10, 32, 14, 0, ARRAY['croquette', 'potato', 'street-food', 'yoshoku'], 75),
('JPN_MENCHI_KATSU', 'menchi-katsu', 'Menchi Katsu', 'Breaded and fried ground meat patty, juicy inside with crispy panko coating', 'Menchi Katsu', 'メンチカツ', 'tonkatsu', 'classic', 'national', 'mixed', 'deep_fried', FALSE, TRUE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 350, 22, 24, 20, 0, ARRAY['katsu', 'meat-patty', 'juicy', 'street-food'], 72);

-- YAKITORI & GRILLED (10 dishes)
INSERT INTO japanese (id, slug, name, description, japanese_name, japanese_script, category, status, region, protein_type, cooking_method, is_izakaya_style, is_street_food, is_comfort_food, served_hot, broth_based, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('JPN_NEGIMA', 'negima-yakitori', 'Negima', 'Classic yakitori of chicken thigh alternating with green onion, the most popular skewer', 'Negima', 'ねぎま', 'yakitori', 'signature', 'national', 'chicken', 'grilled', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 180, 18, 4, 10, 0, ARRAY['yakitori', 'chicken', 'skewer', 'classic'], 95),
('JPN_TSUKUNE', 'tsukune', 'Tsukune', 'Savory chicken meatball skewers glazed with tare sauce, often served with raw egg yolk', 'Tsukune', 'つくね', 'yakitori', 'signature', 'national', 'chicken', 'grilled', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['soy', 'eggs'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 200, 20, 6, 12, 0, ARRAY['yakitori', 'meatball', 'tare', 'egg-yolk'], 92),
('JPN_MOMO', 'momo-yakitori', 'Momo', 'Juicy chicken thigh yakitori, grilled simply with salt or tare sauce', 'Momo', 'もも', 'yakitori', 'classic', 'national', 'chicken', 'grilled', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 160, 16, 2, 10, 0, ARRAY['yakitori', 'thigh', 'simple', 'juicy'], 88),
('JPN_KAWA', 'kawa-yakitori', 'Kawa', 'Crispy chicken skin skewers, grilled until crackling and delicious', 'Kawa', '皮', 'yakitori', 'popular', 'national', 'chicken', 'grilled', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 220, 8, 0, 20, 0, ARRAY['yakitori', 'skin', 'crispy', 'rich'], 78),
('JPN_TEBASAKI', 'tebasaki', 'Tebasaki', 'Grilled or fried chicken wings Nagoya-style, crispy and coated in sweet-spicy glaze', 'Tebasaki', '手羽先', 'yakitori', 'regional', 'nagoya', 'chicken', 'deep_fried', TRUE, FALSE, TRUE, TRUE, FALSE, ARRAY['soy', 'sesame'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 320, 22, 8, 24, 1, ARRAY['wings', 'nagoya', 'crispy', 'glazed'], 85),
('JPN_HATSU', 'hatsu-yakitori', 'Hatsu', 'Grilled chicken hearts, tender with a slightly chewy texture, yakitori specialty', 'Hatsu', 'ハツ', 'yakitori', 'traditional', 'national', 'chicken', 'grilled', TRUE, FALSE, FALSE, TRUE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 120, 18, 1, 5, 0, ARRAY['yakitori', 'offal', 'hearts', 'specialty'], 65),
('JPN_REBA', 'reba-yakitori', 'Reba', 'Grilled chicken liver skewers, rich and creamy when cooked medium', 'Reba', 'レバー', 'yakitori', 'traditional', 'national', 'chicken', 'grilled', TRUE, FALSE, FALSE, TRUE, FALSE, ARRAY['sesame'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 140, 16, 2, 8, 0, ARRAY['yakitori', 'liver', 'offal', 'rich'], 60),
('JPN_BUTABARA', 'butabara-yakitori', 'Butabara', 'Grilled pork belly skewers, fatty and flavorful with caramelized edges', 'Butabara', '豚バラ', 'yakitori', 'popular', 'national', 'pork', 'grilled', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 280, 14, 2, 26, 0, ARRAY['yakitori', 'pork', 'belly', 'fatty'], 82),
('JPN_SHIITAKE_YAKI', 'shiitake-yakitori', 'Shiitake Yaki', 'Grilled shiitake mushroom caps, brushed with soy and butter', 'Shiitake Yaki', '椎茸焼き', 'yakitori', 'active', 'national', 'vegetarian', 'grilled', TRUE, FALSE, TRUE, TRUE, FALSE, ARRAY['soy', 'dairy'], TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, 80, 4, 8, 4, 0, ARRAY['yakitori', 'mushroom', 'vegetarian', 'umami'], 70),
('JPN_ASPARA_BACON', 'aspara-bacon', 'Aspara Bacon', 'Asparagus spears wrapped in bacon and grilled, popular izakaya item', 'Aspara Bacon', 'アスパラベーコン', 'yakitori', 'popular', 'national', 'pork', 'grilled', TRUE, FALSE, TRUE, TRUE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 150, 8, 4, 12, 0, ARRAY['yakitori', 'bacon', 'asparagus', 'izakaya'], 78);

-- IZAKAYA SMALL PLATES (10 dishes)
INSERT INTO japanese (id, slug, name, description, japanese_name, japanese_script, category, status, region, protein_type, cooking_method, is_izakaya_style, is_street_food, is_comfort_food, served_hot, broth_based, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('JPN_EDAMAME', 'edamame', 'Edamame', 'Steamed young soybeans in pods, lightly salted, the quintessential izakaya starter', 'Edamame', '枝豆', 'izakaya', 'signature', 'national', 'vegetarian', 'steamed', TRUE, FALSE, TRUE, TRUE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 120, 11, 9, 5, 0, ARRAY['edamame', 'starter', 'healthy', 'beer-snack'], 95),
('JPN_AGEDASHI_TOFU', 'agedashi-tofu', 'Agedashi Tofu', 'Lightly fried tofu in warm dashi broth with grated daikon and ginger', 'Agedashi Tofu', '揚げ出し豆腐', 'izakaya', 'signature', 'national', 'tofu', 'deep_fried', TRUE, FALSE, TRUE, TRUE, TRUE, ARRAY['soy', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 180, 12, 10, 10, 0, ARRAY['tofu', 'fried', 'dashi', 'classic'], 88),
('JPN_GYOZA', 'gyoza', 'Gyoza', 'Pan-fried dumplings with pork and vegetable filling, crispy bottom and juicy inside', 'Gyoza', '餃子', 'izakaya', 'signature', 'national', 'pork', 'pan_fried', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['gluten', 'soy', 'sesame'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 280, 14, 28, 14, 1, ARRAY['gyoza', 'dumplings', 'pan-fried', 'popular'], 95),
('JPN_TAKOYAKI', 'takoyaki', 'Takoyaki', 'Crispy octopus balls from Osaka with takoyaki sauce, mayo, aonori and katsuobushi', 'Takoyaki', 'たこ焼き', 'izakaya', 'signature', 'osaka', 'seafood', 'pan_fried', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs', 'fish', 'shellfish'], FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, 350, 16, 38, 16, 0, ARRAY['takoyaki', 'osaka', 'octopus', 'street-food'], 92),
('JPN_OKONOMIYAKI', 'okonomiyaki', 'Okonomiyaki', 'Savory Japanese pancake with cabbage, pork and toppings, griddled Osaka-style', 'Okonomiyaki', 'お好み焼き', 'izakaya', 'signature', 'osaka', 'pork', 'pan_fried', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs', 'fish'], FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 580, 22, 52, 32, 0, ARRAY['okonomiyaki', 'pancake', 'osaka', 'griddled'], 90),
('JPN_HIROSHIMA_OKONOMIYAKI', 'hiroshima-okonomiyaki', 'Hiroshima Okonomiyaki', 'Layered style okonomiyaki with noodles, egg and cabbage stacked rather than mixed', 'Hiroshima-fu Okonomiyaki', '広島風お好み焼き', 'izakaya', 'regional', 'hiroshima', 'pork', 'pan_fried', TRUE, TRUE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs', 'fish'], FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 680, 26, 68, 34, 0, ARRAY['okonomiyaki', 'hiroshima', 'layered', 'noodles'], 82),
('JPN_TAMAGOYAKI', 'tamagoyaki', 'Tamagoyaki', 'Sweet rolled Japanese omelette, layered and slightly sweet, breakfast or izakaya staple', 'Tamagoyaki', '卵焼き', 'izakaya', 'classic', 'national', 'egg', 'pan_fried', TRUE, FALSE, TRUE, FALSE, FALSE, ARRAY['eggs', 'soy', 'fish'], TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, 150, 10, 8, 10, 0, ARRAY['egg', 'omelette', 'sweet', 'layered'], 85),
('JPN_NATTO', 'natto', 'Natto', 'Fermented soybeans with distinctive sticky texture and pungent flavor, acquired taste', 'Natto', '納豆', 'izakaya', 'traditional', 'national', 'vegetarian', 'raw', TRUE, FALSE, TRUE, FALSE, FALSE, ARRAY['soy'], TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 110, 9, 6, 5, 0, ARRAY['natto', 'fermented', 'traditional', 'healthy'], 65),
('JPN_HIYAYAKKO', 'hiyayakko', 'Hiyayakko', 'Chilled silken tofu with ginger, green onion and soy sauce, refreshing summer dish', 'Hiyayakko', '冷奴', 'izakaya', 'classic', 'national', 'tofu', 'raw', TRUE, FALSE, TRUE, FALSE, FALSE, ARRAY['soy', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 80, 8, 4, 4, 0, ARRAY['tofu', 'cold', 'summer', 'simple'], 72),
('JPN_MONJAYAKI', 'monjayaki', 'Monjayaki', 'Tokyo-style runny savory pancake, eaten directly from the griddle with small spatulas', 'Monjayaki', 'もんじゃ焼き', 'izakaya', 'regional', 'tokyo', 'seafood', 'pan_fried', TRUE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'shellfish', 'dairy'], FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, 420, 18, 45, 20, 0, ARRAY['monjayaki', 'tokyo', 'runny', 'griddle'], 68);

-- NABEMONO - HOT POTS (8 dishes)
INSERT INTO japanese (id, slug, name, description, japanese_name, japanese_script, category, status, region, protein_type, cooking_method, is_izakaya_style, is_street_food, is_comfort_food, served_hot, broth_based, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('JPN_SUKIYAKI', 'sukiyaki', 'Sukiyaki', 'Thinly sliced beef simmered in sweet soy broth with tofu, vegetables, dipped in raw egg', 'Sukiyaki', 'すき焼き', 'nabemono', 'signature', 'national', 'beef', 'hot_pot', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['soy', 'eggs'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 580, 35, 25, 38, 0, ARRAY['hot-pot', 'beef', 'premium', 'winter'], 92),
('JPN_SHABU_SHABU', 'shabu-shabu', 'Shabu Shabu', 'Thinly sliced meat swished in kombu broth, served with ponzu and sesame dipping sauces', 'Shabu Shabu', 'しゃぶしゃぶ', 'nabemono', 'signature', 'national', 'beef', 'hot_pot', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['soy', 'sesame', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 480, 38, 15, 30, 0, ARRAY['hot-pot', 'beef', 'healthy', 'light'], 90),
('JPN_CHANKO_NABE', 'chanko-nabe', 'Chanko Nabe', 'Hearty sumo wrestler hot pot with chicken, tofu, vegetables and various proteins', 'Chanko Nabe', 'ちゃんこ鍋', 'nabemono', 'traditional', 'tokyo', 'mixed', 'hot_pot', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['soy', 'fish', 'gluten'], FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 520, 42, 35, 22, 0, ARRAY['hot-pot', 'sumo', 'hearty', 'protein'], 75),
('JPN_YOSENABE', 'yosenabe', 'Yosenabe', 'Gathering pot with assorted seafood, chicken, tofu and vegetables in light dashi broth', 'Yosenabe', '寄せ鍋', 'nabemono', 'classic', 'national', 'mixed', 'hot_pot', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['soy', 'fish', 'shellfish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 380, 35, 18, 18, 0, ARRAY['hot-pot', 'mixed', 'family-style', 'winter'], 78),
('JPN_ODEN', 'oden', 'Oden', 'Assorted items like daikon, egg, fish cakes simmered in light soy-dashi broth, winter comfort', 'Oden', 'おでん', 'nabemono', 'signature', 'national', 'mixed', 'simmered', TRUE, TRUE, TRUE, TRUE, TRUE, ARRAY['soy', 'eggs', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 280, 18, 22, 12, 0, ARRAY['oden', 'winter', 'comfort', 'convenience-store'], 85),
('JPN_MOTSU_NABE', 'motsu-nabe', 'Motsu Nabe', 'Fukuoka specialty hot pot with beef or pork offal, cabbage, chives and garlic in miso broth', 'Motsu Nabe', 'もつ鍋', 'nabemono', 'regional', 'kyushu', 'beef', 'hot_pot', TRUE, FALSE, TRUE, TRUE, TRUE, ARRAY['soy', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 380, 28, 18, 22, 1, ARRAY['hot-pot', 'offal', 'fukuoka', 'garlic'], 72),
('JPN_KIMCHI_NABE', 'kimchi-nabe', 'Kimchi Nabe', 'Korean-influenced hot pot with kimchi, pork, tofu and vegetables in spicy broth', 'Kimchi Nabe', 'キムチ鍋', 'nabemono', 'popular', 'national', 'pork', 'hot_pot', TRUE, FALSE, TRUE, TRUE, TRUE, ARRAY['soy', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 420, 26, 22, 28, 3, ARRAY['hot-pot', 'spicy', 'korean-influenced', 'kimchi'], 80),
('JPN_MIZUTAKI', 'mizutaki', 'Mizutaki', 'Light chicken hot pot from Fukuoka cooked in simple water/kombu broth with ponzu', 'Mizutaki', '水炊き', 'nabemono', 'regional', 'kyushu', 'chicken', 'hot_pot', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['soy', 'fish'], TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 320, 32, 12, 16, 0, ARRAY['hot-pot', 'chicken', 'light', 'fukuoka'], 70);

-- YOSHOKU - WESTERN-INFLUENCED (8 dishes)
INSERT INTO japanese (id, slug, name, description, japanese_name, japanese_script, category, status, region, protein_type, cooking_method, is_izakaya_style, is_street_food, is_comfort_food, served_hot, broth_based, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('JPN_CURRY_RICE', 'japanese-curry-rice', 'Japanese Curry Rice', 'Rich and mild Japanese curry served over rice, often with tonkatsu or vegetables', 'Kare Raisu', 'カレーライス', 'yoshoku', 'signature', 'national', 'beef', 'simmered', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 680, 28, 85, 26, 2, ARRAY['curry', 'comfort-food', 'national-dish', 'popular'], 98),
('JPN_KATSU_CURRY', 'katsu-curry', 'Katsu Curry', 'Japanese curry rice topped with crispy tonkatsu cutlet, the ultimate comfort combination', 'Katsu Kare', 'カツカレー', 'yoshoku', 'signature', 'national', 'pork', 'deep_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 920, 38, 90, 44, 2, ARRAY['curry', 'tonkatsu', 'hearty', 'indulgent'], 95),
('JPN_OMURICE', 'omurice', 'Omurice', 'Ketchup fried rice wrapped in a fluffy omelette, often topped with demi-glace sauce', 'Omurice', 'オムライス', 'yoshoku', 'signature', 'national', 'chicken', 'pan_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['eggs', 'dairy'], TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, 580, 26, 62, 26, 0, ARRAY['omelette', 'rice', 'retro', 'kissaten'], 88),
('JPN_HAMBURG_STEAK', 'hamburg-steak', 'Hamburg Steak', 'Japanese-style hamburger patty served with demi-glace sauce, often with egg on top', 'Hambagu', 'ハンバーグ', 'yoshoku', 'popular', 'national', 'mixed', 'pan_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs', 'dairy'], FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 520, 32, 18, 36, 0, ARRAY['hamburg', 'western', 'family-restaurant', 'sauce'], 85),
('JPN_HAYASHI_RICE', 'hayashi-rice', 'Hayashi Rice', 'Beef and mushrooms in rich demi-glace tomato sauce served over rice', 'Hayashi Raisu', 'ハヤシライス', 'yoshoku', 'classic', 'national', 'beef', 'simmered', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten'], FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 620, 28, 75, 24, 0, ARRAY['rice', 'beef', 'demi-glace', 'western'], 72),
('JPN_NAPORITAN', 'naporitan', 'Naporitan', 'Retro Japanese spaghetti with ketchup-based sauce, ham, peppers and onions', 'Naporitan', 'ナポリタン', 'yoshoku', 'classic', 'national', 'pork', 'pan_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'dairy'], FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 520, 18, 68, 20, 0, ARRAY['pasta', 'retro', 'ketchup', 'kissaten'], 75),
('JPN_EBIFLY', 'ebi-fry', 'Ebi Fry', 'Large breaded and fried shrimp, yoshoku classic served with tartar sauce', 'Ebi Furai', 'エビフライ', 'yoshoku', 'classic', 'national', 'seafood', 'deep_fried', FALSE, FALSE, TRUE, TRUE, FALSE, ARRAY['gluten', 'eggs', 'shellfish'], FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, 380, 22, 28, 22, 0, ARRAY['fried-shrimp', 'yoshoku', 'tartar-sauce', 'crispy'], 82),
('JPN_NIKUJAGA', 'nikujaga', 'Nikujaga', 'Home-style meat and potato stew simmered in sweet soy broth, quintessential comfort food', 'Nikujaga', '肉じゃが', 'comfort_food', 'signature', 'national', 'beef', 'simmered', FALSE, FALSE, TRUE, TRUE, TRUE, ARRAY['soy'], TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 380, 22, 42, 14, 0, ARRAY['stew', 'home-cooking', 'comfort', 'potato'], 85);

-- Verify counts
SELECT category, COUNT(*) as count FROM japanese GROUP BY category ORDER BY count DESC;
SELECT 'Total Japanese dishes:' as label, COUNT(*) as total FROM japanese;
