-- GUDBRO Appetizers Batch 03
-- Records: 21 to 30 of 51
-- Generated: 2025-12-15T22:32:17.672Z

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'gambas-al-ajillo',
  'gambas-al-ajillo',
  '{"en":"Gambas al Ajillo","it":"Gamberi all''Aglio","vi":"Tôm xào tỏi Tây Ban Nha"}'::jsonb,
  '{"en":"Sizzling shrimp cooked in olive oil with garlic and chili","it":"Gamberi sfrigolanti cotti in olio d''oliva con aglio e peperoncino","vi":"Tôm nóng hổi nấu trong dầu ô liu với tỏi và ớt"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'mare',
  'hot',
  '{"shrimp","garlic","olive oil","chili","parsley"}',
  NULL,
  false,
  false,
  false,
  2,
  '{"country":"Spain","country_code":"ES","region":"Andalusia"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":8,"is_shareable":true,"recommended_pairing":["white wine","cava","crusty bread"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["shellfish"],"calories_estimate":280,"protein_g":22,"carbs_g":3,"fat_g":20,"fiber_g":0}'::jsonb,
  '{"prep_time_min":10,"cook_time_min":8,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"spanish","tapas","seafood","garlic","quick"}',
  92,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'tortilla-espanola',
  'tortilla-espanola',
  '{"en":"Spanish Tortilla","it":"Tortilla Spagnola","vi":"Trứng chiên Tây Ban Nha"}'::jsonb,
  '{"en":"Traditional Spanish omelette with potatoes and onions","it":"Tradizionale frittata spagnola con patate e cipolle","vi":"Trứng chiên truyền thống Tây Ban Nha với khoai tây và hành tây"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'tapas',
  'room_temp',
  '{"eggs","potatoes","onion","olive oil"}',
  NULL,
  true,
  false,
  false,
  0,
  '{"country":"Spain","country_code":"ES"}'::jsonb,
  '{"story":{"en":"Dating back to the 19th century, tortilla espanola is Spain''s most iconic dish","it":"Risalente al XIX secolo, la tortilla espanola e il piatto piu iconico della Spagna","vi":"Có từ thế kỷ 19, tortilla espanola là món ăn mang tính biểu tượng nhất của Tây Ban Nha"}}'::jsonb,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["red wine","beer","sangria"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["egg"],"calories_estimate":250,"protein_g":12,"carbs_g":22,"fat_g":14,"fiber_g":2}'::jsonb,
  '{"prep_time_min":20,"cook_time_min":25,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"spanish","tapas","eggs","potatoes","classic","vegetarian"}',
  90,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'croquetas-jamon',
  'croquetas-jamon',
  '{"en":"Ham Croquettes","it":"Crocchette di Prosciutto","vi":"Bánh khoai tây chiên nhân giăm bông"}'::jsonb,
  '{"en":"Creamy bechamel croquettes filled with Iberian ham","it":"Cremose crocchette di besciamella ripiene di prosciutto iberico","vi":"Bánh khoai tây chiên nhân kem bechamel với giăm bông Iberia"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'fritti',
  'hot',
  '{"bechamel","iberian ham","flour","butter","breadcrumbs"}',
  NULL,
  true,
  false,
  false,
  0,
  '{"country":"Spain","country_code":"ES"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":4,"is_shareable":true,"recommended_pairing":["cava","white wine","beer"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","egg"],"calories_estimate":320,"protein_g":14,"carbs_g":28,"fat_g":18,"fiber_g":1}'::jsonb,
  '{"prep_time_min":45,"cook_time_min":15,"difficulty":"hard"}'::jsonb,
  NULL,
  '{"spanish","tapas","fried","ham","creamy"}',
  88,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'pimientos-padron',
  'pimientos-padron',
  '{"en":"Padron Peppers","it":"Peperoni di Padron","vi":"Ớt Padron"}'::jsonb,
  '{"en":"Blistered green peppers from Galicia with sea salt - some are hot, some are not!","it":"Peperoni verdi scottati dalla Galizia con sale marino - alcuni sono piccanti, altri no!","vi":"Ớt xanh nướng từ Galicia với muối biển - một số cay, một số không!"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'verdure',
  'hot',
  '{"padron peppers","olive oil","sea salt"}',
  NULL,
  true,
  false,
  false,
  1,
  '{"country":"Spain","country_code":"ES","region":"Galicia","city":"Padron"}'::jsonb,
  NULL,
  '{"portion_size":"small","is_shareable":true,"recommended_pairing":["beer","white wine","albarino"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":[],"calories_estimate":80,"protein_g":2,"carbs_g":6,"fat_g":6,"fiber_g":2}'::jsonb,
  '{"prep_time_min":5,"cook_time_min":5,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"spanish","tapas","vegan","peppers","quick","galician"}',
  85,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'jamon-iberico',
  'jamon-iberico',
  '{"en":"Iberian Ham","it":"Prosciutto Iberico","vi":"Giăm bông Iberia"}'::jsonb,
  '{"en":"Hand-carved slices of premium acorn-fed Iberian ham","it":"Fette tagliate a mano di pregiato prosciutto iberico di ghianda","vi":"Lát giăm bông Iberia cao cấp từ heo ăn sồi, thái bằng tay"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'affettati',
  'room_temp',
  '{"iberian ham"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Spain","country_code":"ES","region":"Extremadura"}'::jsonb,
  '{"story":{"en":"Considered the finest ham in the world, from pigs fed on acorns in the dehesa","it":"Considerato il miglior prosciutto al mondo, da maiali nutriti con ghiande nella dehesa","vi":"Được coi là giăm bông ngon nhất thế giới, từ heo ăn sồi trong rừng sồi dehesa"}}'::jsonb,
  '{"portion_size":"small","is_shareable":true,"recommended_pairing":["fino sherry","cava","red wine"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":[],"calories_estimate":200,"protein_g":28,"carbs_g":0,"fat_g":10,"fiber_g":0}'::jsonb,
  '{"prep_time_min":10,"cook_time_min":0,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"spanish","ham","premium","cured","iberico"}',
  88,
  NULL,
  NULL,
  '{"cost_level":"premium","suggested_price_usd":28}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'pulpo-gallego',
  'pulpo-gallego',
  '{"en":"Galician Octopus","it":"Polpo alla Galiziana","vi":"Bạch tuộc kiểu Galicia"}'::jsonb,
  '{"en":"Tender octopus with paprika, olive oil and sea salt on potato slices","it":"Polpo tenero con paprika, olio d''oliva e sale marino su fette di patata","vi":"Bạch tuộc mềm với ớt paprika, dầu ô liu và muối biển trên lát khoai tây"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'mare',
  'warm',
  '{"octopus","potatoes","paprika","olive oil","sea salt"}',
  NULL,
  false,
  false,
  false,
  1,
  '{"country":"Spain","country_code":"ES","region":"Galicia"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["albarino","white wine","beer"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["mollusks"],"calories_estimate":220,"protein_g":26,"carbs_g":15,"fat_g":8,"fiber_g":1}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":60,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"spanish","tapas","seafood","octopus","galician"}',
  82,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'manchego-membrillo',
  'manchego-membrillo',
  '{"en":"Manchego with Quince","it":"Manchego con Cotognata","vi":"Phô mai Manchego với mứt mộc qua"}'::jsonb,
  '{"en":"Aged Manchego cheese served with sweet quince paste","it":"Manchego stagionato servito con dolce cotognata","vi":"Phô mai Manchego ủ lâu năm với mứt mộc qua ngọt"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'formaggi',
  'room_temp',
  '{"manchego cheese","quince paste"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Spain","country_code":"ES","region":"La Mancha"}'::jsonb,
  NULL,
  '{"portion_size":"small","is_shareable":true,"recommended_pairing":["red wine","sherry","tempranillo"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["milk"],"calories_estimate":280,"protein_g":18,"carbs_g":20,"fat_g":16,"fiber_g":1}'::jsonb,
  '{"prep_time_min":5,"cook_time_min":0,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"spanish","cheese","manchego","quince","simple"}',
  80,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'boquerones-vinagre',
  'boquerones-vinagre',
  '{"en":"Marinated Anchovies","it":"Acciughe Marinate","vi":"Ca com ngam giam"}'::jsonb,
  '{"en":"Fresh white anchovies marinated in vinegar with garlic and parsley","it":"Acciughe bianche fresche marinate in aceto con aglio e prezzemolo","vi":"Ca com trang tuoi ngam trong giam voi toi va rau mui"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'mare',
  'cold',
  '{"anchovies","vinegar","garlic","parsley","olive oil"}',
  NULL,
  false,
  false,
  true,
  0,
  '{"country":"Spain","country_code":"ES","region":"Andalusia"}'::jsonb,
  NULL,
  '{"portion_size":"small","is_shareable":true,"recommended_pairing":["manzanilla sherry","white wine","beer"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["fish"],"calories_estimate":120,"protein_g":16,"carbs_g":1,"fat_g":6,"fiber_g":0}'::jsonb,
  '{"prep_time_min":20,"cook_time_min":0,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"spanish","tapas","seafood","marinated","raw"}',
  75,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'chorizo-sidra',
  'chorizo-sidra',
  '{"en":"Chorizo in Cider","it":"Chorizo al Sidro","vi":"Xuc xich Chorizo trong ruou tao"}'::jsonb,
  '{"en":"Spicy chorizo sausage cooked in Asturian apple cider","it":"Salsiccia chorizo piccante cotta nel sidro di mele asturiano","vi":"Xuc xich chorizo cay nau trong ruou tao Asturias"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'tapas',
  'hot',
  '{"chorizo","apple cider"}',
  NULL,
  false,
  false,
  false,
  2,
  '{"country":"Spain","country_code":"ES","region":"Asturias"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":6,"is_shareable":true,"recommended_pairing":["cider","red wine","beer"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":[],"calories_estimate":340,"protein_g":18,"carbs_g":4,"fat_g":28,"fiber_g":0}'::jsonb,
  '{"prep_time_min":5,"cook_time_min":15,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"spanish","tapas","chorizo","cider","asturian"}',
  78,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'albondigas-salsa',
  'albondigas-salsa',
  '{"en":"Meatballs in Tomato Sauce","it":"Polpette in Salsa di Pomodoro","vi":"Thit vien sot ca chua"}'::jsonb,
  '{"en":"Tender pork and beef meatballs in rich tomato and wine sauce","it":"Tenere polpette di maiale e manzo in ricca salsa di pomodoro e vino","vi":"Thit vien heo va bo mem trong sot ca chua va ruou vang dam da"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'tapas',
  'hot',
  '{"pork","beef","tomato sauce","wine","onion","garlic"}',
  'tomato wine sauce',
  true,
  false,
  false,
  1,
  '{"country":"Spain","country_code":"ES"}'::jsonb,
  NULL,
  '{"portion_size":"medium","pieces_per_serving":5,"is_shareable":true,"recommended_pairing":["red wine","rioja","bread"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten"],"calories_estimate":380,"protein_g":24,"carbs_g":18,"fat_g":24,"fiber_g":2}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":40,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"spanish","tapas","meatballs","tomato","hearty"}',
  82,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();