-- GUDBRO Appetizers Batch 02
-- Records: 11 to 20 of 51
-- Generated: 2025-12-15T22:32:17.672Z

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-burrata-pomodorini',
  'burrata-pomodorini',
  '{"en":"Burrata with Cherry Tomatoes","it":"Burrata con Pomodorini","vi":"Burrata với Cà Chua Bi"}'::jsonb,
  '{"en":"Creamy Pugliese burrata with sweet cherry tomatoes, basil, and aged balsamic","it":"Burrata pugliese cremosa con pomodorini dolci, basilico e balsamico invecchiato","vi":"Burrata Puglia kem với cà chua bi ngọt, húng quế và giấm balsamic lâu năm"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'formaggi',
  'room_temp',
  '{"burrata","cherry_tomatoes","basil","balsamic","olive_oil"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Puglia"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["prosecco","white_wine"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":["milk"],"calories_estimate":280,"protein_g":14,"carbs_g":8,"fat_g":22,"fiber_g":2}'::jsonb,
  '{"prep_time_min":5,"cook_time_min":0,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"burrata","puglia","fresh","summer","vegetarian"}',
  92,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-caprese',
  'caprese-classica',
  '{"en":"Caprese Salad","it":"Caprese Classica","vi":"Salad Caprese"}'::jsonb,
  '{"en":"Fresh buffalo mozzarella, ripe tomatoes, and basil with extra virgin olive oil","it":"Mozzarella di bufala fresca, pomodori maturi e basilico con olio extravergine","vi":"Mozzarella trâu tươi, cà chua chín và húng quế với dầu olive nguyên chất"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'formaggi',
  'room_temp',
  '{"buffalo_mozzarella","tomatoes","basil","olive_oil"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Campania","city":"Capri"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["white_wine","prosecco"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":["milk"],"calories_estimate":250,"protein_g":14,"carbs_g":6,"fat_g":20,"fiber_g":2}'::jsonb,
  '{"prep_time_min":5,"cook_time_min":0,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"caprese","mozzarella","tomato","summer","fresh","vegetarian"}',
  96,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-caponata',
  'caponata-siciliana',
  '{"en":"Sicilian Caponata","it":"Caponata Siciliana","vi":"Caponata Sicily"}'::jsonb,
  '{"en":"Sweet and sour eggplant stew with celery, capers, olives, and pine nuts","it":"Stufato agrodolce di melanzane con sedano, capperi, olive e pinoli","vi":"Cà tím hầm chua ngọt với cần tây, nụ bạch hoa, oliu và hạt thông"}'::jsonb,
  NULL,
  'italian',
  'traditional',
  'verdure',
  'room_temp',
  '{"eggplant","celery","capers","olives","pine_nuts","tomato"}',
  NULL,
  true,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Sicily"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["white_wine","rosé"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":false,"is_high_protein":false,"allergens":["tree_nuts"],"calories_estimate":180,"protein_g":3,"carbs_g":18,"fat_g":12,"fiber_g":5}'::jsonb,
  '{"prep_time_min":20,"cook_time_min":30,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"caponata","sicily","eggplant","vegan","sweet_sour"}',
  82,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-peperonata',
  'peperonata',
  '{"en":"Peperonata","it":"Peperonata","vi":"Peperonata"}'::jsonb,
  '{"en":"Slow-cooked sweet peppers with tomatoes, onions, and olive oil","it":"Peperoni dolci cotti lentamente con pomodori, cipolle e olio d''oliva","vi":"Ớt chuông ngọt nấu chậm với cà chua, hành và dầu olive"}'::jsonb,
  NULL,
  'italian',
  'traditional',
  'verdure',
  'room_temp',
  '{"bell_peppers","tomatoes","onions","olive_oil","garlic"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["white_wine","rosé"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":[],"calories_estimate":120,"protein_g":2,"carbs_g":14,"fat_g":7,"fiber_g":3}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":40,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"peperonata","peppers","vegan","summer","contorno"}',
  76,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-melanzane-parmigiana',
  'melanzane-parmigiana',
  '{"en":"Eggplant Parmigiana","it":"Melanzane alla Parmigiana","vi":"Cà Tím Parmigiana"}'::jsonb,
  '{"en":"Layers of fried eggplant with tomato sauce, mozzarella, and parmesan","it":"Strati di melanzane fritte con sugo di pomodoro, mozzarella e parmigiano","vi":"Các lớp cà tím chiên với sốt cà chua, mozzarella và parmesan"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'verdure',
  'warm',
  '{"eggplant","tomato_sauce","mozzarella","parmesan","basil"}',
  NULL,
  true,
  true,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Campania / Sicily"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["red_wine","white_wine"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs"],"calories_estimate":320,"protein_g":14,"carbs_g":22,"fat_g":22,"fiber_g":4}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":45,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"parmigiana","eggplant","baked","comfort_food","vegetarian"}',
  90,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-insalata-mare',
  'insalata-di-mare',
  '{"en":"Seafood Salad","it":"Insalata di Mare","vi":"Salad Hải Sản"}'::jsonb,
  '{"en":"Chilled mixed seafood salad with octopus, shrimp, calamari, and lemon dressing","it":"Insalata fredda di frutti di mare misti con polpo, gamberi, calamari e condimento al limone","vi":"Salad hải sản hỗn hợp lạnh với bạch tuộc, tôm, mực và sốt chanh"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'mare',
  'cold',
  '{"octopus","shrimp","calamari","celery","lemon","olive_oil"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["white_wine","prosecco"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["shellfish","mollusks"],"calories_estimate":220,"protein_g":28,"carbs_g":4,"fat_g":12,"fiber_g":1}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":20,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"seafood","salad","summer","cold","healthy"}',
  86,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-cozze-marinara',
  'cozze-alla-marinara',
  '{"en":"Mussels Marinara","it":"Cozze alla Marinara","vi":"Vẹm Sốt Marinara"}'::jsonb,
  '{"en":"Fresh mussels steamed in white wine, garlic, tomato, and parsley","it":"Cozze fresche cotte al vapore in vino bianco, aglio, pomodoro e prezzemolo","vi":"Vẹm tươi hấp rượu vang trắng, tỏi, cà chua và mùi tây"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'mare',
  'hot',
  '{"mussels","white_wine","garlic","tomato","parsley"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["white_wine","prosecco"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["shellfish","sulfites"],"calories_estimate":180,"protein_g":20,"carbs_g":8,"fat_g":6,"fiber_g":1}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":10,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"mussels","seafood","marinara","wine","coastal"}',
  84,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-gamberi-aglio',
  'gamberi-aglio-olio',
  '{"en":"Garlic Shrimp","it":"Gamberi Aglio e Olio","vi":"Tôm Tỏi"}'::jsonb,
  '{"en":"Sautéed shrimp in garlic, olive oil, white wine, and chili flakes","it":"Gamberi saltati in aglio, olio d''oliva, vino bianco e peperoncino","vi":"Tôm xào tỏi, dầu olive, rượu vang trắng và ớt bột"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'mare',
  'hot',
  '{"shrimp","garlic","olive_oil","white_wine","chili"}',
  NULL,
  false,
  false,
  false,
  2,
  '{"country":"Italy","country_code":"IT"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["white_wine","prosecco"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["shellfish","sulfites"],"calories_estimate":200,"protein_g":22,"carbs_g":4,"fat_g":12,"fiber_g":0}'::jsonb,
  '{"prep_time_min":10,"cook_time_min":8,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"shrimp","garlic","seafood","quick","spicy"}',
  88,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-vitello-tonnato',
  'vitello-tonnato',
  '{"en":"Vitello Tonnato","it":"Vitello Tonnato","vi":"Vitello Tonnato"}'::jsonb,
  '{"en":"Thin slices of cold veal with creamy tuna-caper sauce - Piedmontese classic","it":"Fettine sottili di vitello freddo con salsa cremosa al tonno e capperi - classico piemontese","vi":"Lát thịt bê lạnh mỏng với sốt cá ngừ-nụ bạch hoa kem - cổ điển Piedmont"}'::jsonb,
  NULL,
  'italian',
  'traditional',
  'carpaccio',
  'cold',
  '{"veal","tuna","capers","anchovies","mayonnaise"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Piedmont"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["white_wine","prosecco"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["fish","eggs"],"calories_estimate":280,"protein_g":30,"carbs_g":2,"fat_g":18,"fiber_g":0}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":60,"difficulty":"hard"}'::jsonb,
  NULL,
  '{"vitello_tonnato","piedmont","cold","veal","elegant"}',
  80,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'patatas-bravas',
  'patatas-bravas',
  '{"en":"Patatas Bravas","it":"Patatas Bravas","vi":"Khoai tây Bravas"}'::jsonb,
  '{"en":"Crispy fried potatoes with spicy bravas sauce and garlic aioli","it":"Patate fritte croccanti con salsa bravas piccante e aioli all''aglio","vi":"Khoai tây chiên giòn với sốt bravas cay và sốt tỏi aioli"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'tapas',
  'hot',
  '{"potatoes","tomato sauce","paprika","garlic","olive oil"}',
  'bravas sauce + aioli',
  true,
  false,
  false,
  2,
  '{"country":"Spain","country_code":"ES","region":"Madrid"}'::jsonb,
  '{"story":{"en":"Invented in Madrid in the 1960s, patatas bravas became the quintessential Spanish tapa","it":"Inventate a Madrid negli anni ''60, sono diventate la tapa spagnola per eccellenza","vi":"Được phát minh ở Madrid vào những năm 1960, patatas bravas trở thành món tapas tiêu biểu của Tây Ban Nha"}}'::jsonb,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["beer","sangria","vermouth"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["egg"],"calories_estimate":320,"protein_g":4,"carbs_g":42,"fat_g":16,"fiber_g":4}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":20,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"spanish","tapas","fried","potatoes","classic","shareable"}',
  95,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();