-- GUDBRO Appetizers Batch 01
-- Records: 1 to 10 of 51
-- Generated: 2025-12-15T22:32:17.671Z

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-bruschetta-pomodoro',
  'bruschetta-pomodoro',
  '{"en":"Classic Tomato Bruschetta","it":"Bruschetta al Pomodoro","vi":"Bruschetta Cà Chua Cổ Điển"}'::jsonb,
  '{"en":"Grilled bread rubbed with garlic, topped with fresh tomatoes, basil, and extra virgin olive oil","it":"Pane grigliato strofinato con aglio, condito con pomodori freschi, basilico e olio extravergine","vi":"Bánh mì nướng chà tỏi, phủ cà chua tươi, húng quế và dầu olive nguyên chất"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'bruschetta',
  'room_temp',
  '{"bread","tomatoes","garlic","basil","olive_oil"}',
  NULL,
  false,
  true,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Lazio"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":2,"is_shareable":true,"recommended_pairing":["prosecco","white_wine"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten"],"calories_estimate":120,"protein_g":3,"carbs_g":18,"fat_g":5,"fiber_g":2}'::jsonb,
  '{"prep_time_min":10,"cook_time_min":5,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"bruschetta","vegetarian","vegan","classic","tomato","summer"}',
  95,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-bruschetta-nduja',
  'bruschetta-nduja',
  '{"en":"Nduja Bruschetta","it":"Bruschetta alla Nduja","vi":"Bruschetta Nduja"}'::jsonb,
  '{"en":"Grilled bread with spicy Calabrian nduja spread, stracciatella, and honey drizzle","it":"Pane grigliato con nduja calabrese piccante, stracciatella e filo di miele","vi":"Bánh mì nướng với nduja Calabria cay, stracciatella và mật ong"}'::jsonb,
  NULL,
  'italian',
  'modern',
  'bruschetta',
  'warm',
  '{"bread","nduja","stracciatella","honey"}',
  NULL,
  false,
  true,
  false,
  3,
  '{"country":"Italy","country_code":"IT","region":"Calabria"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":2,"is_shareable":true,"recommended_pairing":["red_wine","beer"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":220,"protein_g":10,"carbs_g":16,"fat_g":14,"fiber_g":1}'::jsonb,
  '{"prep_time_min":5,"cook_time_min":5,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"bruschetta","nduja","spicy","calabria","stracciatella"}',
  85,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-crostini-fegatini',
  'crostini-fegatini',
  '{"en":"Tuscan Chicken Liver Crostini","it":"Crostini ai Fegatini Toscani","vi":"Crostini Gan Gà Tuscan"}'::jsonb,
  '{"en":"Traditional Tuscan appetizer with creamy chicken liver pâté on toasted bread","it":"Antipasto toscano tradizionale con paté cremoso di fegatini su pane tostato","vi":"Khai vị Tuscan truyền thống với pâté gan gà kem trên bánh mì nướng"}'::jsonb,
  NULL,
  'italian',
  'traditional',
  'crostini',
  'room_temp',
  '{"bread","chicken_liver","onion","capers","anchovies"}',
  NULL,
  false,
  true,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Tuscany"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":3,"is_shareable":true,"recommended_pairing":["chianti","vin_santo"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","fish"],"calories_estimate":180,"protein_g":12,"carbs_g":14,"fat_g":9,"fiber_g":1}'::jsonb,
  '{"prep_time_min":20,"cook_time_min":15,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"crostini","tuscan","liver","traditional","pate"}',
  78,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-arancini',
  'arancini-siciliani',
  '{"en":"Sicilian Arancini","it":"Arancini Siciliani","vi":"Arancini Sicily"}'::jsonb,
  '{"en":"Crispy fried rice balls stuffed with ragù, mozzarella, and peas - Sicilian street food classic","it":"Palle di riso fritte croccanti ripiene di ragù, mozzarella e piselli - classico street food siciliano","vi":"Cơm viên chiên giòn nhân ragù, mozzarella và đậu Hà Lan - món đường phố Sicily cổ điển"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'fritti',
  'hot',
  '{"rice","ragu","mozzarella","peas","breadcrumbs"}',
  NULL,
  true,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Sicily"}'::jsonb,
  NULL,
  '{"portion_size":"medium","pieces_per_serving":2,"is_shareable":true,"recommended_pairing":["white_wine","beer"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs"],"calories_estimate":320,"protein_g":14,"carbs_g":38,"fat_g":14,"fiber_g":2}'::jsonb,
  '{"prep_time_min":45,"cook_time_min":15,"difficulty":"hard"}'::jsonb,
  NULL,
  '{"arancini","sicily","fried","rice","street_food"}',
  92,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-supplì',
  'suppli-romani',
  '{"en":"Roman Supplì","it":"Supplì Romani","vi":"Supplì La Mã"}'::jsonb,
  '{"en":"Roman fried rice croquettes with tomato sauce and stretchy mozzarella center","it":"Crocchette di riso fritte romane con sugo e cuore filante di mozzarella","vi":"Cơm viên chiên La Mã với sốt cà chua và nhân mozzarella kéo sợi"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'fritti',
  'hot',
  '{"rice","tomato_sauce","mozzarella","breadcrumbs"}',
  NULL,
  true,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Lazio","city":"Rome"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":2,"is_shareable":true,"recommended_pairing":["white_wine","beer"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk","eggs"],"calories_estimate":280,"protein_g":10,"carbs_g":34,"fat_g":12,"fiber_g":2}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":10,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"suppli","rome","fried","rice","mozzarella","street_food"}',
  88,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-fiori-zucca',
  'fiori-zucca-fritti',
  '{"en":"Fried Zucchini Flowers","it":"Fiori di Zucca Fritti","vi":"Hoa Bí Chiên"}'::jsonb,
  '{"en":"Delicate zucchini blossoms stuffed with mozzarella and anchovy, lightly battered and fried","it":"Delicati fiori di zucca ripieni di mozzarella e acciuga, in pastella leggera e fritti","vi":"Hoa bí mềm mại nhân mozzarella và cá cơm, tẩm bột nhẹ và chiên"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'fritti',
  'hot',
  '{"zucchini_flowers","mozzarella","anchovy","batter"}',
  NULL,
  true,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Lazio"}'::jsonb,
  NULL,
  '{"portion_size":"medium","pieces_per_serving":3,"is_shareable":true,"recommended_pairing":["prosecco","white_wine"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk","fish","eggs"],"calories_estimate":240,"protein_g":10,"carbs_g":20,"fat_g":14,"fiber_g":1}'::jsonb,
  '{"prep_time_min":20,"cook_time_min":10,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"fiori_zucca","fried","seasonal","summer","roman"}',
  85,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-mozzarella-carrozza',
  'mozzarella-in-carrozza',
  '{"en":"Mozzarella in Carrozza","it":"Mozzarella in Carrozza","vi":"Mozzarella Chiên Giòn"}'::jsonb,
  '{"en":"Fried mozzarella sandwich - crispy on the outside, melty cheese inside","it":"Sandwich di mozzarella fritta - croccante fuori, formaggio filante dentro","vi":"Bánh mì mozzarella chiên - giòn bên ngoài, phô mai tan chảy bên trong"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'fritti',
  'hot',
  '{"bread","mozzarella","eggs","flour"}',
  NULL,
  true,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT","region":"Campania"}'::jsonb,
  NULL,
  '{"portion_size":"medium","pieces_per_serving":1,"is_shareable":false,"recommended_pairing":["beer","white_wine"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","eggs"],"calories_estimate":350,"protein_g":18,"carbs_g":28,"fat_g":20,"fiber_g":1}'::jsonb,
  '{"prep_time_min":10,"cook_time_min":8,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"mozzarella","fried","naples","comfort_food","cheese"}',
  86,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-carpaccio-manzo',
  'carpaccio-manzo',
  '{"en":"Beef Carpaccio","it":"Carpaccio di Manzo","vi":"Thịt Bò Sống Carpaccio"}'::jsonb,
  '{"en":"Paper-thin slices of raw beef tenderloin with arugula, parmesan shavings, and lemon dressing","it":"Fettine sottilissime di filetto di manzo crudo con rucola, scaglie di parmigiano e condimento al limone","vi":"Lát thịt bò thăn sống mỏng như giấy với arugula, parmesan bào và sốt chanh"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'carpaccio',
  'cold',
  '{"beef_tenderloin","arugula","parmesan","lemon","olive_oil"}',
  NULL,
  false,
  false,
  true,
  0,
  '{"country":"Italy","country_code":"IT","region":"Veneto","city":"Venice"}'::jsonb,
  '{"story":{"en":"Created in 1950 at Harry''s Bar in Venice by Giuseppe Cipriani for a countess who couldn''t eat cooked meat","it":"Creato nel 1950 all''Harry''s Bar di Venezia da Giuseppe Cipriani per una contessa che non poteva mangiare carne cotta","vi":"Được tạo ra năm 1950 tại Harry''s Bar Venice bởi Giuseppe Cipriani cho một nữ bá tước không thể ăn thịt nấu chín"},"year_created":1950,"creator":"Giuseppe Cipriani"}'::jsonb,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["red_wine","prosecco"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["milk"],"calories_estimate":220,"protein_g":24,"carbs_g":2,"fat_g":14,"fiber_g":1}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":0,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"carpaccio","raw","beef","venice","elegant","gluten_free"}',
  88,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-tartare-tonno',
  'tartare-tonno',
  '{"en":"Tuna Tartare","it":"Tartare di Tonno","vi":"Tartare Cá Ngừ"}'::jsonb,
  '{"en":"Fresh raw tuna diced and seasoned with soy, sesame, and avocado","it":"Tonno fresco crudo tagliato a cubetti e condito con soia, sesamo e avocado","vi":"Cá ngừ tươi sống cắt hạt lựu, ướp với nước tương, mè và bơ"}'::jsonb,
  NULL,
  'italian',
  'modern',
  'tartare',
  'cold',
  '{"tuna","soy_sauce","sesame","avocado","lime"}',
  NULL,
  false,
  false,
  true,
  1,
  '{"country":"Italy","country_code":"IT"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["champagne","white_wine","sake"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":false,"is_halal":true,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["fish","soy","sesame"],"calories_estimate":200,"protein_g":26,"carbs_g":6,"fat_g":10,"fiber_g":2}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":0,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"tartare","tuna","raw","seafood","japanese_fusion"}',
  84,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'appetizer-tagliere-salumi',
  'tagliere-salumi-formaggi',
  '{"en":"Italian Charcuterie Board","it":"Tagliere di Salumi e Formaggi","vi":"Đĩa Thịt Nguội và Phô Mai Ý"}'::jsonb,
  '{"en":"Selection of premium Italian cured meats and aged cheeses with honey, nuts, and mostarda","it":"Selezione di salumi e formaggi stagionati italiani con miele, noci e mostarda","vi":"Tuyển chọn thịt nguội và phô mai lâu năm Ý với mật ong, hạt và mostarda"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'affettati',
  'room_temp',
  '{"prosciutto","salame","mortadella","parmigiano","pecorino","gorgonzola"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Italy","country_code":"IT"}'::jsonb,
  NULL,
  '{"portion_size":"sharing","is_shareable":true,"recommended_pairing":["red_wine","prosecco","lambrusco"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":false,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["milk","tree_nuts"],"calories_estimate":450,"protein_g":28,"carbs_g":8,"fat_g":36,"fiber_g":1}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":0,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"tagliere","salumi","formaggi","sharing","aperitivo"}',
  94,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();