-- GUDBRO Appetizers Batch 04
-- Records: 31 to 40 of 51
-- Generated: 2025-12-15T22:32:17.672Z

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'escalivada',
  'escalivada',
  '{"en":"Escalivada","it":"Escalivada","vi":"Rau nuong Catalan"}'::jsonb,
  '{"en":"Catalan roasted vegetables - eggplant, peppers, onions with olive oil","it":"Verdure arrosto catalane - melanzane, peperoni, cipolle con olio d''oliva","vi":"Rau nuong Catalan - ca tim, ot, hanh tay voi dau o liu"}'::jsonb,
  NULL,
  'spanish',
  'traditional',
  'verdure',
  'room_temp',
  '{"eggplant","red pepper","onion","olive oil","garlic"}',
  NULL,
  false,
  true,
  false,
  0,
  '{"country":"Spain","country_code":"ES","region":"Catalonia"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["white wine","cava","crusty bread"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":[],"calories_estimate":120,"protein_g":2,"carbs_g":12,"fat_g":8,"fiber_g":4}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":45,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"spanish","catalan","vegan","roasted","vegetables"}',
  72,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'pan-tumaca',
  'pan-tumaca',
  '{"en":"Pan con Tomate","it":"Pane con Pomodoro","vi":"Banh mi ca chua"}'::jsonb,
  '{"en":"Toasted bread rubbed with ripe tomato, garlic and olive oil","it":"Pane tostato strofinato con pomodoro maturo, aglio e olio d''oliva","vi":"Banh mi nuong xoa voi ca chua chin, toi va dau o liu"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'bruschetta',
  'room_temp',
  '{"bread","tomato","garlic","olive oil","salt"}',
  NULL,
  false,
  true,
  false,
  0,
  '{"country":"Spain","country_code":"ES","region":"Catalonia"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":2,"is_shareable":true,"recommended_pairing":["cava","wine","iberian ham"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten"],"calories_estimate":180,"protein_g":4,"carbs_g":28,"fat_g":7,"fiber_g":2}'::jsonb,
  '{"prep_time_min":5,"cook_time_min":5,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"spanish","catalan","bread","tomato","simple","vegan"}',
  85,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'empanadas-gallega',
  'empanadas-gallega',
  '{"en":"Galician Empanada","it":"Empanada Galiziana","vi":"Banh xep Galicia"}'::jsonb,
  '{"en":"Large savory pie with tuna, peppers and onions in crispy pastry","it":"Grande torta salata con tonno, peperoni e cipolle in pasta croccante","vi":"Banh nuong lon voi ca ngu, ot chuong va hanh tay trong vo gion"}'::jsonb,
  NULL,
  'spanish',
  'traditional',
  'tapas',
  'warm',
  '{"tuna","peppers","onion","tomato","pastry"}',
  NULL,
  false,
  true,
  false,
  0,
  '{"country":"Spain","country_code":"ES","region":"Galicia"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["albarino","white wine","beer"]}'::jsonb,
  '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","fish","egg"],"calories_estimate":320,"protein_g":18,"carbs_g":32,"fat_g":14,"fiber_g":2}'::jsonb,
  '{"prep_time_min":45,"cook_time_min":35,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"spanish","galician","tuna","pastry","baked"}',
  70,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'gazpacho-andaluz',
  'gazpacho-andaluz',
  '{"en":"Andalusian Gazpacho","it":"Gazpacho Andaluso","vi":"Sup lanh Gazpacho"}'::jsonb,
  '{"en":"Chilled tomato soup with cucumber, peppers, garlic and olive oil","it":"Zuppa fredda di pomodoro con cetriolo, peperoni, aglio e olio d''oliva","vi":"Sup ca chua lanh voi dua chuot, ot chuong, toi va dau o liu"}'::jsonb,
  NULL,
  'spanish',
  'classic',
  'dips',
  'cold',
  '{"tomato","cucumber","pepper","garlic","olive oil","bread","vinegar"}',
  NULL,
  false,
  false,
  true,
  0,
  '{"country":"Spain","country_code":"ES","region":"Andalusia"}'::jsonb,
  NULL,
  '{"portion_size":"small","is_shareable":false,"recommended_pairing":["white wine","fino sherry"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten"],"calories_estimate":90,"protein_g":2,"carbs_g":12,"fat_g":4,"fiber_g":2}'::jsonb,
  '{"prep_time_min":20,"cook_time_min":0,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"spanish","andalusian","cold","soup","summer","vegan"}',
  78,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'tzatziki',
  'tzatziki',
  '{"en":"Tzatziki","it":"Tzatziki","vi":"Sot sua chua Hy Lap"}'::jsonb,
  '{"en":"Creamy Greek yogurt dip with cucumber, garlic and dill","it":"Cremosa salsa greca allo yogurt con cetriolo, aglio e aneto","vi":"Sot sua chua Hy Lap kem voi dua chuot, toi va thi la"}'::jsonb,
  NULL,
  'greek',
  'classic',
  'dips',
  'cold',
  '{"greek yogurt","cucumber","garlic","dill","olive oil"}',
  NULL,
  false,
  false,
  true,
  0,
  '{"country":"Greece","country_code":"GR"}'::jsonb,
  NULL,
  '{"portion_size":"small","is_shareable":true,"recommended_pairing":["pita bread","grilled meats","ouzo"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["milk"],"calories_estimate":90,"protein_g":5,"carbs_g":4,"fat_g":6,"fiber_g":0}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":0,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"greek","mezze","dip","yogurt","refreshing"}',
  92,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'hummus',
  'hummus',
  '{"en":"Hummus","it":"Hummus","vi":"Sot dau ga"}'::jsonb,
  '{"en":"Silky chickpea dip with tahini, lemon, garlic and olive oil","it":"Cremosa crema di ceci con tahina, limone, aglio e olio d''oliva","vi":"Sot dau ga min voi tahini, chanh, toi va dau o liu"}'::jsonb,
  NULL,
  'middle_eastern',
  'classic',
  'dips',
  'room_temp',
  '{"chickpeas","tahini","lemon","garlic","olive oil"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Lebanon","country_code":"LB"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["pita","falafel","vegetables"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["sesame"],"calories_estimate":180,"protein_g":8,"carbs_g":20,"fat_g":9,"fiber_g":5}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":0,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"middle-eastern","mezze","dip","vegan","chickpeas"}',
  95,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'falafel',
  'falafel',
  '{"en":"Falafel","it":"Falafel","vi":"Banh dau ga chien"}'::jsonb,
  '{"en":"Crispy fried chickpea fritters with herbs and spices","it":"Frittelle di ceci croccanti con erbe e spezie","vi":"Banh dau ga chien gion voi thao moc va gia vi"}'::jsonb,
  NULL,
  'middle_eastern',
  'classic',
  'fritti',
  'hot',
  '{"chickpeas","parsley","cilantro","cumin","garlic"}',
  'tahini sauce',
  true,
  false,
  false,
  1,
  '{"country":"Egypt","country_code":"EG"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":5,"is_shareable":true,"recommended_pairing":["hummus","tahini","pita"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":[],"calories_estimate":280,"protein_g":12,"carbs_g":32,"fat_g":14,"fiber_g":6}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":15,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"middle-eastern","falafel","vegan","fried","chickpeas"}',
  90,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'baba-ganoush',
  'baba-ganoush',
  '{"en":"Baba Ganoush","it":"Baba Ganoush","vi":"Sot ca tim nuong"}'::jsonb,
  '{"en":"Smoky roasted eggplant dip with tahini and lemon","it":"Crema affumicata di melanzane arrosto con tahina e limone","vi":"Sot ca tim nuong khoi voi tahini va chanh"}'::jsonb,
  NULL,
  'middle_eastern',
  'classic',
  'dips',
  'room_temp',
  '{"eggplant","tahini","lemon","garlic","olive oil"}',
  NULL,
  false,
  true,
  false,
  0,
  '{"country":"Lebanon","country_code":"LB"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["pita","vegetables","grilled meats"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":["sesame"],"calories_estimate":120,"protein_g":3,"carbs_g":10,"fat_g":8,"fiber_g":4}'::jsonb,
  '{"prep_time_min":10,"cook_time_min":40,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"middle-eastern","mezze","dip","eggplant","vegan"}',
  85,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'dolmades',
  'dolmades',
  '{"en":"Dolmades","it":"Dolmades","vi":"La nho cuon"}'::jsonb,
  '{"en":"Grape leaves stuffed with herbed rice, pine nuts and currants","it":"Foglie di vite ripiene di riso alle erbe, pinoli e uvetta","vi":"La nho cuon com thom, hat thong va nho kho"}'::jsonb,
  NULL,
  'greek',
  'classic',
  'rolls',
  'cold',
  '{"grape leaves","rice","dill","mint","pine nuts","lemon"}',
  NULL,
  false,
  false,
  false,
  0,
  '{"country":"Greece","country_code":"GR"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":6,"is_shareable":true,"recommended_pairing":["tzatziki","white wine","ouzo"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["tree nuts"],"calories_estimate":160,"protein_g":3,"carbs_g":24,"fat_g":6,"fiber_g":2}'::jsonb,
  '{"prep_time_min":45,"cook_time_min":40,"difficulty":"hard"}'::jsonb,
  NULL,
  '{"greek","mezze","stuffed","vegetarian","cold"}',
  78,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO appetizers (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, sauce_or_dip, is_fried, is_baked, is_raw, spice_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_appetizers, media, pricing
) VALUES (
  'spanakopita',
  'spanakopita',
  '{"en":"Spanakopita","it":"Spanakopita","vi":"Banh cai bo xoi Hy Lap"}'::jsonb,
  '{"en":"Crispy phyllo pastry filled with spinach and feta cheese","it":"Pasta fillo croccante ripiena di spinaci e feta","vi":"Banh phyllo gion nhan cai bo xoi va pho mai feta"}'::jsonb,
  NULL,
  'greek',
  'classic',
  'bites',
  'warm',
  '{"phyllo dough","spinach","feta","dill","onion"}',
  NULL,
  false,
  true,
  false,
  0,
  '{"country":"Greece","country_code":"GR"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":3,"is_shareable":true,"recommended_pairing":["white wine","retsina","tzatziki"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":220,"protein_g":10,"carbs_g":18,"fat_g":14,"fiber_g":2}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":35,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"greek","mezze","phyllo","spinach","feta"}',
  82,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  sauce_or_dip = EXCLUDED.sauce_or_dip,
  is_fried = EXCLUDED.is_fried,
  is_baked = EXCLUDED.is_baked,
  is_raw = EXCLUDED.is_raw,
  spice_level = EXCLUDED.spice_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_appetizers = EXCLUDED.related_appetizers,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();