-- pho.ts: 13 items
-- bun.ts: 10 items
-- banh.ts: 13 items
-- cuon.ts: 11 items
-- com.ts: 10 items
-- other.ts: 15 items
-- =============================================================================
-- VIETNAMESE DATABASE - DATA IMPORT
-- 80 authentic Vietnamese dishes
-- DATABASE-STANDARDS v1.1 compliant
-- =============================================================================

INSERT INTO vietnamese (id, slug, name, description, vietnamese_name, category, status,
    region, origin_city, cuisine_influences, is_fusion, protein_type, cooking_method,
    broth_type, meal_types, is_street_food, is_vegetarian_adaptable, ingredient_ids,
    allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian,
    is_halal, is_pescatarian, calories_per_serving, protein_g, carbs_g, fat_g,
    spice_level, tags, popularity)
VALUES
  ('VIETNAMESE_PHO_BO_TAI', 'pho-bo-tai', 'Rare Beef Pho', 'Classic Vietnamese beef pho with thinly sliced rare beef cooked by the hot broth. The foundation of all pho.', 'Phở Bò Tái', 'pho', 'classic', 'national', 'Hanoi', ARRAY['chinese', 'french_colonial'], false, 'beef', 'simmered', 'beef_bone', ARRAY['breakfast', 'lunch', 'dinner', 'any_time'], true, false, ARRAY['ING_RICE_NOODLES', 'ING_BEEF_SIRLOIN', 'ING_BEEF_BONES', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_GINGER', 'ING_ONION', 'ING_FISH_SAUCE', 'ING_BEAN_SPROUTS', 'ING_THAI_BASIL', 'ING_LIME', 'ING_SCALLION', 'ING_CILANTRO'], ARRAY['fish'], true, true, true, false, false, true, false, 450, 32, 52, 12, 0, ARRAY['national_dish', 'iconic', 'breakfast', 'comfort_food'], 98),
  ('VIETNAMESE_PHO_BO_CHIN', 'pho-bo-chin', 'Well-Done Brisket Pho', 'Pho with tender, slow-cooked beef brisket slices. Melt-in-your-mouth texture from hours of simmering.', 'Phở Bò Chín', 'pho', 'classic', 'national', NULL, ARRAY['chinese'], false, 'beef', 'simmered', 'beef_bone', ARRAY['breakfast', 'lunch', 'dinner'], true, false, ARRAY['ING_RICE_NOODLES', 'ING_BEEF_BRISKET', 'ING_BEEF_BONES', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_GINGER', 'ING_ONION', 'ING_FISH_SAUCE', 'ING_BEAN_SPROUTS', 'ING_THAI_BASIL', 'ING_LIME'], ARRAY['fish'], true, true, true, false, false, true, false, 480, 35, 52, 14, 0, ARRAY['classic', 'tender', 'slow_cooked'], 90),
  ('VIETNAMESE_PHO_BO_DAC_BIET', 'pho-bo-dac-biet', 'Special Combination Beef Pho', 'The ultimate pho experience with rare beef, brisket, flank, tendon, and tripe. A complete beef showcase.', 'Phở Bò Đặc Biệt', 'pho', 'signature', 'national', NULL, ARRAY['chinese'], false, 'beef', 'simmered', 'beef_bone', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_RICE_NOODLES', 'ING_BEEF_SIRLOIN', 'ING_BEEF_BRISKET', 'ING_BEEF_FLANK', 'ING_BEEF_TENDON', 'ING_BEEF_TRIPE', 'ING_BEEF_BONES', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_CARDAMOM', 'ING_GINGER', 'ING_FISH_SAUCE', 'ING_THAI_BASIL'], ARRAY['fish'], true, true, true, false, false, true, false, 580, 45, 52, 20, 0, ARRAY['premium', 'combination', 'special'], 95),
  ('VIETNAMESE_PHO_BO_VIEN', 'pho-bo-vien', 'Beef Meatball Pho', 'Pho with bouncy, homemade beef meatballs. A family-friendly option loved by children.', 'Phở Bò Viên', 'pho', 'popular', 'national', NULL, ARRAY['chinese'], false, 'beef', 'simmered', 'beef_bone', ARRAY['breakfast', 'lunch', 'dinner'], true, false, ARRAY['ING_RICE_NOODLES', 'ING_BEEF_MEATBALLS', 'ING_BEEF_BONES', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_GINGER', 'ING_FISH_SAUCE', 'ING_BEAN_SPROUTS', 'ING_THAI_BASIL'], ARRAY['fish'], true, true, true, false, false, true, false, 460, 30, 52, 14, 0, ARRAY['family_friendly', 'meatballs', 'comfort'], 85),
  ('VIETNAMESE_PHO_BO_GAN', 'pho-bo-gan', 'Beef Tendon Pho', 'Pho featuring gelatinous beef tendon, prized for its collagen and melt-in-mouth texture.', 'Phở Bò Gân', 'pho', 'active', 'national', NULL, ARRAY['chinese'], false, 'beef', 'simmered', 'beef_bone', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_RICE_NOODLES', 'ING_BEEF_TENDON', 'ING_BEEF_BONES', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_GINGER', 'ING_FISH_SAUCE', 'ING_BEAN_SPROUTS', 'ING_THAI_BASIL'], ARRAY['fish'], true, true, true, false, false, true, false, 420, 28, 48, 12, 0, ARRAY['collagen', 'tender', 'traditional'], 75),
  ('VIETNAMESE_PHO_GA', 'pho-ga', 'Chicken Pho', 'Lighter pho with poached chicken in clear, aromatic broth. Gentle, comforting, and perfect for recovery.', 'Phở Gà', 'pho', 'classic', 'national', NULL, ARRAY['chinese'], false, 'chicken', 'simmered', 'chicken', ARRAY['breakfast', 'lunch', 'dinner'], true, false, ARRAY['ING_RICE_NOODLES', 'ING_CHICKEN_BREAST', 'ING_CHICKEN_THIGH', 'ING_CHICKEN_BONES', 'ING_GINGER', 'ING_ONION', 'ING_FISH_SAUCE', 'ING_BEAN_SPROUTS', 'ING_CILANTRO', 'ING_LIME', 'ING_SCALLION'], ARRAY['fish'], true, true, true, false, false, true, false, 380, 28, 48, 8, 0, ARRAY['light', 'healthy', 'recovery', 'comfort'], 88),
  ('VIETNAMESE_PHO_BAC', 'pho-bac', 'Northern Style Pho', 'Hanoi-style pho with clear, pure broth and minimal garnishes. The original, purist approach.', 'Phở Bắc', 'pho', 'classic', 'northern', 'Hanoi', ARRAY['indigenous'], false, 'beef', 'simmered', 'beef_bone', ARRAY['breakfast', 'lunch'], true, false, ARRAY['ING_RICE_NOODLES_WIDE', 'ING_BEEF_SIRLOIN', 'ING_BEEF_BRISKET', 'ING_BEEF_BONES', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_CARDAMOM', 'ING_GINGER', 'ING_FISH_SAUCE', 'ING_SCALLION', 'ING_LIME'], ARRAY['fish'], true, true, true, false, false, true, false, 420, 30, 48, 12, 0, ARRAY['traditional', 'purist', 'hanoi', 'original'], 85),
  ('VIETNAMESE_PHO_NAM', 'pho-nam', 'Southern Style Pho', 'Saigon-style pho with sweeter broth, abundant fresh herbs, hoisin, and sriracha on the table.', 'Phở Nam', 'pho', 'classic', 'southern', 'Ho Chi Minh City', ARRAY['indigenous'], false, 'beef', 'simmered', 'beef_bone', ARRAY['breakfast', 'lunch', 'dinner'], true, false, ARRAY['ING_RICE_NOODLES', 'ING_BEEF_SIRLOIN', 'ING_BEEF_BRISKET', 'ING_BEEF_TENDON', 'ING_BEEF_BONES', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_ROCK_SUGAR', 'ING_GINGER', 'ING_FISH_SAUCE', 'ING_BEAN_SPROUTS', 'ING_THAI_BASIL', 'ING_CULANTRO', 'ING_HOISIN_SAUCE', 'ING_SRIRACHA'], ARRAY['fish', 'soy'], false, true, true, false, false, true, false, 500, 34, 58, 14, 1, ARRAY['saigon', 'herbs', 'sweet', 'abundant'], 90),
  ('VIETNAMESE_PHO_HUE', 'pho-hue', 'Hue Style Pho', 'Central Vietnam pho with spicier, richer broth, lemongrass, and royal heritage influences.', 'Phở Huế', 'pho', 'regional', 'central', 'Hue', ARRAY['indigenous', 'cham'], false, 'mixed', 'simmered', 'mixed', ARRAY['breakfast', 'lunch', 'dinner'], true, false, ARRAY['ING_RICE_NOODLES', 'ING_BEEF_SIRLOIN', 'ING_PORK_MEATBALLS', 'ING_BEEF_BONES', 'ING_PORK_BONES', 'ING_LEMONGRASS', 'ING_SHRIMP_PASTE', 'ING_CHILI_OIL', 'ING_FISH_SAUCE', 'ING_BANANA_BLOSSOM', 'ING_MINT'], ARRAY['fish', 'shellfish'], true, true, true, false, false, false, false, 520, 36, 52, 18, 3, ARRAY['spicy', 'royal', 'hue', 'lemongrass'], 80),
  ('VIETNAMESE_PHO_HAI_SAN', 'pho-hai-san', 'Seafood Pho', 'Coastal-style pho with shrimp, squid, and fish in fragrant seafood broth.', 'Phở Hải Sản', 'pho', 'active', 'coastal', NULL, ARRAY['indigenous'], false, 'mixed_seafood', 'simmered', 'seafood', ARRAY['lunch', 'dinner'], false, false, ARRAY['ING_RICE_NOODLES', 'ING_SHRIMP', 'ING_SQUID', 'ING_FISH_FILLET', 'ING_FISH_BONES', 'ING_GINGER', 'ING_LEMONGRASS', 'ING_FISH_SAUCE', 'ING_BEAN_SPROUTS', 'ING_THAI_BASIL', 'ING_LIME'], ARRAY['fish', 'shellfish'], true, true, true, false, false, true, true, 360, 32, 42, 6, 0, ARRAY['seafood', 'coastal', 'light'], 70),
  ('VIETNAMESE_PHO_VIT', 'pho-vit', 'Duck Pho', 'Rich pho with tender duck meat in aromatic duck broth. A specialty in some regions.', 'Phở Vịt', 'pho', 'regional', 'northern', NULL, ARRAY['chinese'], false, 'duck', 'simmered', 'chicken', ARRAY['lunch', 'dinner'], false, false, ARRAY['ING_RICE_NOODLES', 'ING_DUCK', 'ING_DUCK_BONES', 'ING_STAR_ANISE', 'ING_GINGER', 'ING_FISH_SAUCE', 'ING_BEAN_SPROUTS', 'ING_THAI_BASIL'], ARRAY['fish'], true, true, true, false, false, true, false, 520, 30, 48, 22, 0, ARRAY['duck', 'rich', 'specialty'], 65),
  ('VIETNAMESE_PHO_CHAY', 'pho-chay', 'Vegetarian Pho', 'Buddhist-style vegetarian pho with tofu, mushrooms, and rich vegetable broth. Popular on lunar holidays.', 'Phở Chay', 'pho', 'active', 'national', NULL, ARRAY['chinese', 'indigenous'], false, 'tofu', 'simmered', 'vegetable', ARRAY['breakfast', 'lunch', 'dinner'], true, true, ARRAY['ING_RICE_NOODLES', 'ING_TOFU', 'ING_SHIITAKE_MUSHROOM', 'ING_WOOD_EAR_MUSHROOM', 'ING_DAIKON', 'ING_CARROT', 'ING_SOY_SAUCE', 'ING_STAR_ANISE', 'ING_BEAN_SPROUTS', 'ING_THAI_BASIL'], ARRAY['soy'], false, true, true, true, true, true, true, 320, 18, 50, 6, 0, ARRAY['vegetarian', 'vegan', 'buddhist', 'healthy'], 75),
  ('VIETNAMESE_PHO_SOT_VANG', 'pho-sot-vang', 'Red Wine Beef Pho', 'French-Vietnamese fusion pho with beef stewed in red wine sauce. Colonial heritage meets pho.', 'Phở Sốt Vang', 'pho', 'signature', 'northern', 'Hanoi', ARRAY['french_colonial'], true, 'beef', 'braised', 'beef_bone', ARRAY['lunch', 'dinner'], false, false, ARRAY['ING_RICE_NOODLES', 'ING_BEEF_CHUCK', 'ING_RED_WINE', 'ING_TOMATO', 'ING_CARROT', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_BAY_LEAF', 'ING_LEMONGRASS', 'ING_GINGER'], ARRAY['sulphites'], true, true, true, false, false, false, false, 550, 38, 52, 18, 0, ARRAY['fusion', 'french', 'wine', 'premium'], 72),
  ('VIETNAMESE_BUN_BO_HUE', 'bun-bo-hue', 'Bun Bo Hue', 'Spicy beef noodle soup from Hue with lemongrass, shrimp paste, and tender beef shank. Features thick round noodles and a bold, aromatic broth.', 'Bún Bò Huế', 'bun', 'signature', 'central', 'Hue', ARRAY['indigenous', 'cham'], false, 'beef', 'simmered', 'beef_bone', ARRAY['breakfast', 'lunch', 'dinner'], true, false, ARRAY['ING_RICE_VERMICELLI', 'ING_BEEF_SHANK', 'ING_PORK_KNUCKLE', 'ING_LEMONGRASS', 'ING_SHRIMP_PASTE', 'ING_CHILI_OIL', 'ING_BANANA_BLOSSOM', 'ING_MINT', 'ING_BEAN_SPROUTS', 'ING_LIME', 'ING_FISH_SAUCE', 'ING_ANNATTO_SEEDS'], ARRAY['fish', 'shellfish'], true, true, true, false, false, false, false, 520, 35, 55, 18, 4, ARRAY['spicy', 'soup', 'hue', 'beef', 'signature', 'lemongrass'], 92),
  ('VIETNAMESE_BUN_CHA', 'bun-cha', 'Bun Cha', 'Hanoi\', 'Bún Chả', 'bun', 'signature', 'northern', 'Hanoi', ARRAY['indigenous'], false, 'pork', 'grilled', 'none', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_RICE_VERMICELLI', 'ING_PORK_BELLY', 'ING_GROUND_PORK', 'ING_FISH_SAUCE', 'ING_SUGAR', 'ING_GARLIC', 'ING_SHALLOTS', 'ING_LETTUCE', 'ING_MINT', 'ING_PERILLA', 'ING_PICKLED_PAPAYA', 'ING_LIME'], ARRAY['fish'], true, true, true, false, false, false, false, 580, 32, 48, 28, 1, ARRAY['grilled', 'pork', 'hanoi', 'signature', 'obama', 'street_food'], 95),
  ('VIETNAMESE_BUN_RIEU', 'bun-rieu', 'Bun Rieu', 'Tomato-based crab noodle soup with freshwater crab paste, fried tofu, and blood cake. A Northern specialty with a distinctive tangy flavor.', 'Bún Riêu', 'bun', 'classic', 'northern', 'Hanoi', ARRAY['chinese', 'indigenous'], false, 'crab', 'simmered', 'mixed', ARRAY['breakfast', 'lunch'], true, false, ARRAY['ING_RICE_VERMICELLI', 'ING_CRAB_PASTE', 'ING_TOMATOES', 'ING_TOFU_FRIED', 'ING_SHRIMP_PASTE', 'ING_ANNATTO_SEEDS', 'ING_WATER_SPINACH', 'ING_BANANA_BLOSSOM', 'ING_BEAN_SPROUTS', 'ING_MINT', 'ING_PERILLA', 'ING_FISH_SAUCE'], ARRAY['shellfish', 'fish', 'soy'], true, true, true, false, false, false, false, 420, 25, 52, 14, 2, ARRAY['soup', 'crab', 'tomato', 'northern', 'tangy'], 78),
  ('VIETNAMESE_BUN_THIT_NUONG', 'bun-thit-nuong', 'Bun Thit Nuong', 'Grilled pork over cold vermicelli noodles with fresh herbs, pickled vegetables, and nuoc cham dipping sauce. A refreshing dry noodle dish.', 'Bún Thịt Nướng', 'bun', 'popular', 'southern', 'Saigon', ARRAY['indigenous'], false, 'pork', 'grilled', 'none', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_RICE_VERMICELLI', 'ING_PORK_LOIN', 'ING_FISH_SAUCE', 'ING_LEMONGRASS', 'ING_GARLIC', 'ING_SUGAR', 'ING_LETTUCE', 'ING_CUCUMBER', 'ING_BEAN_SPROUTS', 'ING_MINT', 'ING_PICKLED_CARROTS', 'ING_PEANUTS'], ARRAY['fish', 'peanuts'], true, true, false, false, false, false, false, 520, 30, 55, 20, 1, ARRAY['grilled', 'pork', 'cold_noodles', 'refreshing', 'herbs'], 88),
  ('VIETNAMESE_BUN_MAM', 'bun-mam', 'Bun Mam', 'Fermented fish noodle soup from the Mekong Delta. Features pungent mam (fermented fish) broth with roast pork, shrimp, squid, and eggplant.', 'Bún Mắm', 'bun', 'regional', 'mekong_delta', 'Can Tho', ARRAY['khmer', 'indigenous'], false, 'mixed_seafood', 'simmered', 'seafood', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_RICE_VERMICELLI', 'ING_FERMENTED_FISH', 'ING_PORK_BELLY', 'ING_SHRIMP', 'ING_SQUID', 'ING_EGGPLANT', 'ING_WATER_SPINACH', 'ING_BANANA_BLOSSOM', 'ING_BEAN_SPROUTS', 'ING_GARLIC', 'ING_LEMONGRASS', 'ING_CHILI'], ARRAY['fish', 'shellfish'], true, true, true, false, false, false, false, 550, 38, 48, 22, 2, ARRAY['soup', 'fermented_fish', 'mekong', 'pungent', 'seafood'], 65),
  ('VIETNAMESE_BUN_BO_NAM_BO', 'bun-bo-nam-bo', 'Bun Bo Nam Bo', 'Southern-style beef and noodle salad. Stir-fried beef over cold vermicelli with fresh herbs, peanuts, and nuoc cham. Also known as ', 'Bún Bò Nam Bộ', 'bun', 'popular', 'southern', 'Saigon', ARRAY['indigenous'], false, 'beef', 'stir_fried', 'none', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_RICE_VERMICELLI', 'ING_BEEF_SIRLOIN', 'ING_FISH_SAUCE', 'ING_GARLIC', 'ING_LEMONGRASS', 'ING_ONION', 'ING_LETTUCE', 'ING_CUCUMBER', 'ING_BEAN_SPROUTS', 'ING_MINT', 'ING_PEANUTS', 'ING_FRIED_SHALLOTS'], ARRAY['fish', 'peanuts'], true, true, false, false, false, false, false, 540, 32, 50, 22, 1, ARRAY['stir_fried', 'beef', 'cold_noodles', 'salad', 'peanuts'], 82),
  ('VIETNAMESE_BUN_OC', 'bun-oc', 'Bun Oc', 'Snail noodle soup, a Hanoi street food specialty. Features river snails in a tangy tomato-based broth with fried tofu and herbs.', 'Bún Ốc', 'bun', 'street_food', 'northern', 'Hanoi', ARRAY['indigenous'], false, 'mixed_seafood', 'simmered', 'mixed', ARRAY['snack', 'lunch'], true, false, ARRAY['ING_RICE_VERMICELLI', 'ING_RIVER_SNAILS', 'ING_TOMATOES', 'ING_TOFU_FRIED', 'ING_PERILLA', 'ING_SHRIMP_PASTE', 'ING_GARLIC', 'ING_CHILI', 'ING_GREEN_ONION', 'ING_LIME', 'ING_FISH_SAUCE', 'ING_VINEGAR'], ARRAY['shellfish', 'fish', 'soy'], true, true, true, false, false, false, true, 380, 22, 48, 12, 2, ARRAY['soup', 'snails', 'hanoi', 'street_food', 'tangy'], 70),
  ('VIETNAMESE_BUN_THANG', 'bun-thang', 'Bun Thang', 'Elegant Hanoi chicken noodle soup with delicate toppings: shredded chicken, pork, egg ribbons, and Vietnamese ham. A refined, labor-intensive dish.', 'Bún Thang', 'bun', 'classic', 'northern', 'Hanoi', ARRAY['chinese', 'indigenous'], false, 'chicken', 'simmered', 'chicken', ARRAY['breakfast', 'lunch'], false, false, ARRAY['ING_RICE_VERMICELLI', 'ING_CHICKEN_BREAST', 'ING_CHA_LUA', 'ING_PORK_FLOSS', 'ING_EGG', 'ING_DRIED_SHRIMP', 'ING_SHRIMP_PASTE', 'ING_GREEN_ONION', 'ING_CORIANDER', 'ING_GINGER', 'ING_FISH_SAUCE', 'ING_LIME'], ARRAY['fish', 'shellfish', 'eggs'], true, true, true, false, false, false, false, 420, 35, 45, 12, 0, ARRAY['soup', 'chicken', 'hanoi', 'refined', 'elegant'], 72),
  ('VIETNAMESE_BUN_CA', 'bun-ca', 'Bun Ca', 'Fish noodle soup with fried fish fillets, dill, tomatoes, and turmeric. A Hanoi favorite often made with catfish or snakehead fish.', 'Bún Cá', 'bun', 'popular', 'northern', 'Hanoi', ARRAY['indigenous'], false, 'fish', 'deep_fried', 'seafood', ARRAY['breakfast', 'lunch'], true, false, ARRAY['ING_RICE_VERMICELLI', 'ING_CATFISH', 'ING_DILL', 'ING_TOMATOES', 'ING_TURMERIC', 'ING_SHRIMP_PASTE', 'ING_GREEN_ONION', 'ING_GARLIC', 'ING_FISH_SAUCE', 'ING_LIME', 'ING_CHILI', 'ING_VEGETABLE_OIL'], ARRAY['fish'], true, true, true, false, false, true, true, 450, 28, 48, 16, 1, ARRAY['soup', 'fish', 'dill', 'turmeric', 'hanoi'], 75),
  ('VIETNAMESE_BUN_CHAY', 'bun-chay', 'Bun Chay', 'Vegetarian vermicelli bowl with grilled tofu, mushrooms, and fresh vegetables. Served with vegetarian nuoc cham sauce.', 'Bún Chay', 'bun', 'active', 'national', NULL, ARRAY['chinese', 'indigenous'], false, 'tofu', 'grilled', 'none', ARRAY['lunch', 'dinner'], true, true, ARRAY['ING_RICE_VERMICELLI', 'ING_TOFU', 'ING_SHIITAKE_MUSHROOMS', 'ING_LETTUCE', 'ING_CUCUMBER', 'ING_BEAN_SPROUTS', 'ING_MINT', 'ING_PERILLA', 'ING_PICKLED_CARROTS', 'ING_SOY_SAUCE', 'ING_SUGAR', 'ING_PEANUTS'], ARRAY['soy', 'peanuts'], true, true, false, true, true, true, true, 380, 18, 52, 12, 1, ARRAY['vegetarian', 'vegan', 'tofu', 'mushrooms', 'healthy'], 68),
  ('VIETNAMESE_BANH_MI_THIT', 'banh-mi-thit', 'Banh Mi Thit', 'The classic Vietnamese baguette sandwich with assorted cold cuts, pâté, pickled vegetables, cilantro, and chili. A perfect fusion of French and Vietnamese cuisines.', 'Bánh Mì Thịt', 'banh', 'signature', 'national', NULL, ARRAY['french_colonial', 'indigenous'], true, 'pork', 'baked', 'none', ARRAY['breakfast', 'lunch', 'snack'], true, true, ARRAY['ING_BAGUETTE', 'ING_CHA_LUA', 'ING_PATE', 'ING_PORK_BELLY', 'ING_PICKLED_CARROTS', 'ING_PICKLED_DAIKON', 'ING_CUCUMBER', 'ING_CILANTRO', 'ING_JALAPENO', 'ING_MAYONNAISE', 'ING_SOY_SAUCE', 'ING_MAGGI'], ARRAY['gluten', 'eggs', 'soy'], false, true, true, false, false, false, false, 450, 22, 48, 18, 2, ARRAY['sandwich', 'french_fusion', 'street_food', 'iconic', 'portable'], 98),
  ('VIETNAMESE_BANH_MI_THIT_NUONG', 'banh-mi-thit-nuong', 'Banh Mi Thit Nuong', 'Grilled pork banh mi with lemongrass-marinated meat, pickled vegetables, and fresh herbs. A popular variation with chargrilled flavor.', 'Bánh Mì Thịt Nướng', 'banh', 'popular', 'national', NULL, ARRAY['french_colonial', 'indigenous'], true, 'pork', 'grilled', 'none', ARRAY['breakfast', 'lunch', 'snack'], true, false, ARRAY['ING_BAGUETTE', 'ING_PORK_LOIN', 'ING_LEMONGRASS', 'ING_GARLIC', 'ING_FISH_SAUCE', 'ING_PICKLED_CARROTS', 'ING_PICKLED_DAIKON', 'ING_CUCUMBER', 'ING_CILANTRO', 'ING_JALAPENO', 'ING_MAYONNAISE', 'ING_SOY_SAUCE'], ARRAY['gluten', 'eggs', 'fish'], false, true, true, false, false, false, false, 480, 28, 45, 20, 2, ARRAY['sandwich', 'grilled', 'pork', 'lemongrass', 'street_food'], 90),
  ('VIETNAMESE_BANH_MI_GA', 'banh-mi-ga', 'Banh Mi Ga', 'Chicken banh mi with shredded or grilled chicken, pâté, pickled vegetables, and herbs. A lighter alternative to pork versions.', 'Bánh Mì Gà', 'banh', 'popular', 'national', NULL, ARRAY['french_colonial', 'indigenous'], true, 'chicken', 'grilled', 'none', ARRAY['breakfast', 'lunch', 'snack'], true, false, ARRAY['ING_BAGUETTE', 'ING_CHICKEN_BREAST', 'ING_PATE', 'ING_PICKLED_CARROTS', 'ING_PICKLED_DAIKON', 'ING_CUCUMBER', 'ING_CILANTRO', 'ING_JALAPENO', 'ING_MAYONNAISE', 'ING_SOY_SAUCE', 'ING_GARLIC', 'ING_FISH_SAUCE'], ARRAY['gluten', 'eggs', 'fish'], false, true, true, false, false, true, false, 420, 30, 45, 14, 2, ARRAY['sandwich', 'chicken', 'lighter', 'halal_option'], 82),
  ('VIETNAMESE_BANH_MI_CHAY', 'banh-mi-chay', 'Banh Mi Chay', 'Vegetarian banh mi with tofu, mushrooms, pickled vegetables, and herbs. Buddhist temple-inspired filling with full flavor.', 'Bánh Mì Chay', 'banh', 'active', 'national', NULL, ARRAY['french_colonial', 'chinese', 'indigenous'], true, 'tofu', 'grilled', 'none', ARRAY['breakfast', 'lunch', 'snack'], true, true, ARRAY['ING_BAGUETTE', 'ING_TOFU', 'ING_SHIITAKE_MUSHROOMS', 'ING_PICKLED_CARROTS', 'ING_PICKLED_DAIKON', 'ING_CUCUMBER', 'ING_CILANTRO', 'ING_SOY_SAUCE', 'ING_MAGGI', 'ING_VEGETARIAN_PATE', 'ING_JALAPENO', 'ING_LETTUCE'], ARRAY['gluten', 'soy'], false, true, true, true, true, true, true, 350, 15, 48, 10, 2, ARRAY['sandwich', 'vegetarian', 'vegan', 'tofu', 'buddhist'], 72),
  ('VIETNAMESE_BANH_XEO', 'banh-xeo', 'Banh Xeo', 'Crispy Vietnamese sizzling crepe filled with pork, shrimp, and bean sprouts. Named for the ', 'Bánh Xèo', 'banh', 'signature', 'southern', 'Saigon', ARRAY['khmer', 'indigenous'], false, 'mixed', 'deep_fried', 'none', ARRAY['lunch', 'dinner', 'snack'], true, true, ARRAY['ING_RICE_FLOUR', 'ING_TURMERIC', 'ING_COCONUT_MILK', 'ING_PORK_BELLY', 'ING_SHRIMP', 'ING_BEAN_SPROUTS', 'ING_MUNG_BEANS', 'ING_GREEN_ONION', 'ING_LETTUCE', 'ING_MINT', 'ING_PERILLA', 'ING_FISH_SAUCE'], ARRAY['shellfish', 'fish'], true, true, true, false, false, false, false, 520, 22, 45, 28, 1, ARRAY['crepe', 'crispy', 'sizzling', 'shrimp', 'pork', 'turmeric'], 92),
  ('VIETNAMESE_BANH_KHOT', 'banh-khot', 'Banh Khot', 'Mini sizzling rice cakes from Vung Tau, topped with shrimp and crispy edges. Served with lettuce wraps and nuoc cham.', 'Bánh Khọt', 'banh', 'regional', 'southern', 'Vung Tau', ARRAY['indigenous'], false, 'shrimp', 'deep_fried', 'none', ARRAY['snack', 'lunch'], true, false, ARRAY['ING_RICE_FLOUR', 'ING_TURMERIC', 'ING_COCONUT_MILK', 'ING_SHRIMP', 'ING_GREEN_ONION', 'ING_MUNG_BEANS', 'ING_LETTUCE', 'ING_MINT', 'ING_FISH_SAUCE', 'ING_LIME', 'ING_CHILI', 'ING_VEGETABLE_OIL'], ARRAY['shellfish', 'fish'], true, true, true, false, false, false, true, 380, 18, 35, 18, 1, ARRAY['mini_cakes', 'crispy', 'vung_tau', 'shrimp', 'appetizer'], 78),
  ('VIETNAMESE_BANH_CUON', 'banh-cuon', 'Banh Cuon', 'Delicate steamed rice rolls filled with seasoned ground pork and wood ear mushrooms. Served with cha lua, fried shallots, and nuoc cham.', 'Bánh Cuốn', 'banh', 'classic', 'northern', 'Hanoi', ARRAY['chinese', 'indigenous'], false, 'pork', 'steamed', 'none', ARRAY['breakfast', 'snack'], true, true, ARRAY['ING_RICE_FLOUR', 'ING_TAPIOCA_STARCH', 'ING_GROUND_PORK', 'ING_WOOD_EAR_MUSHROOMS', 'ING_SHALLOTS', 'ING_FISH_SAUCE', 'ING_CHA_LUA', 'ING_FRIED_SHALLOTS', 'ING_CUCUMBER', 'ING_BEAN_SPROUTS', 'ING_MINT', 'ING_LIME'], ARRAY['fish'], true, true, true, false, false, false, false, 320, 18, 38, 10, 0, ARRAY['steamed', 'rice_rolls', 'hanoi', 'breakfast', 'delicate'], 85),
  ('VIETNAMESE_BANH_CUON_THANH_TRI', 'banh-cuon-thanh-tri', 'Banh Cuon Thanh Tri', 'The famous ultra-thin rice rolls from Thanh Tri village near Hanoi. Paper-thin and served without filling, just with dipping sauce.', 'Bánh Cuốn Thanh Trì', 'banh', 'regional', 'northern', 'Thanh Tri', ARRAY['indigenous'], false, 'none', 'steamed', 'none', ARRAY['breakfast', 'snack'], true, true, ARRAY['ING_RICE_FLOUR', 'ING_TAPIOCA_STARCH', 'ING_FISH_SAUCE', 'ING_CHA_LUA', 'ING_FRIED_SHALLOTS', 'ING_CHILI', 'ING_LIME', 'ING_GARLIC', 'ING_SUGAR'], ARRAY['fish'], true, true, true, false, false, false, false, 250, 12, 35, 6, 1, ARRAY['steamed', 'thin', 'thanh_tri', 'artisanal', 'traditional'], 72),
  ('VIETNAMESE_BANH_BAO', 'banh-bao', 'Banh Bao', 'Vietnamese steamed buns filled with pork, Chinese sausage, quail eggs, and mushrooms. A Chinese-influenced snack popular throughout Vietnam.', 'Bánh Bao', 'banh', 'popular', 'national', NULL, ARRAY['chinese'], false, 'pork', 'steamed', 'none', ARRAY['breakfast', 'snack'], true, true, ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_GROUND_PORK', 'ING_LAP_XUONG', 'ING_QUAIL_EGGS', 'ING_WOOD_EAR_MUSHROOMS', 'ING_GLASS_NOODLES', 'ING_ONION', 'ING_SOY_SAUCE', 'ING_SUGAR', 'ING_FISH_SAUCE', 'ING_PEPPER'], ARRAY['gluten', 'eggs', 'fish'], false, true, true, false, false, false, false, 380, 18, 42, 14, 0, ARRAY['steamed_buns', 'chinese_influence', 'portable', 'breakfast'], 80),
  ('VIETNAMESE_BANH_GIO', 'banh-gio', 'Banh Gio', 'Pyramid-shaped rice dumplings wrapped in banana leaves, filled with pork, wood ear mushrooms, and shallots. A traditional Northern snack.', 'Bánh Giò', 'banh', 'classic', 'northern', NULL, ARRAY['chinese', 'indigenous'], false, 'pork', 'steamed', 'none', ARRAY['breakfast', 'snack'], true, false, ARRAY['ING_RICE_FLOUR', 'ING_TAPIOCA_STARCH', 'ING_GROUND_PORK', 'ING_WOOD_EAR_MUSHROOMS', 'ING_SHALLOTS', 'ING_FISH_SAUCE', 'ING_PEPPER', 'ING_BANANA_LEAVES', 'ING_SOY_SAUCE'], ARRAY['fish'], true, true, true, false, false, false, false, 280, 12, 35, 10, 0, ARRAY['dumplings', 'banana_leaves', 'pyramid', 'northern', 'traditional'], 70),
  ('VIETNAMESE_BANH_IT_TRAN', 'banh-it-tran', 'Banh It Tran', 'Central Vietnamese glutinous rice dumplings with shrimp and pork filling, wrapped in banana leaves. A Hue specialty.', 'Bánh Ít Trần', 'banh', 'regional', 'central', 'Hue', ARRAY['cham', 'indigenous'], false, 'mixed', 'steamed', 'none', ARRAY['snack', 'breakfast'], true, false, ARRAY['ING_GLUTINOUS_RICE_FLOUR', 'ING_SHRIMP', 'ING_GROUND_PORK', 'ING_SHALLOTS', 'ING_FISH_SAUCE', 'ING_PEPPER', 'ING_BANANA_LEAVES', 'ING_FRIED_SHALLOTS', 'ING_NUOC_CHAM'], ARRAY['shellfish', 'fish'], true, true, true, false, false, false, false, 260, 14, 32, 8, 0, ARRAY['dumplings', 'hue', 'glutinous_rice', 'shrimp', 'central'], 65),
  ('VIETNAMESE_BANH_BOT_LOC', 'banh-bot-loc', 'Banh Bot Loc', 'Translucent tapioca dumplings from Hue filled with shrimp and pork belly. The clear wrapper shows the pink shrimp inside.', 'Bánh Bột Lọc', 'banh', 'regional', 'central', 'Hue', ARRAY['indigenous'], false, 'mixed', 'steamed', 'none', ARRAY['snack', 'appetizer'], true, false, ARRAY['ING_TAPIOCA_STARCH', 'ING_SHRIMP', 'ING_PORK_BELLY', 'ING_SHALLOTS', 'ING_FISH_SAUCE', 'ING_PEPPER', 'ING_BANANA_LEAVES', 'ING_NUOC_CHAM', 'ING_CHILI'], ARRAY['shellfish', 'fish'], true, true, true, false, false, false, false, 220, 12, 28, 8, 1, ARRAY['dumplings', 'translucent', 'hue', 'shrimp', 'tapioca'], 75),
  ('VIETNAMESE_BANH_TRANG_NUONG', 'banh-trang-nuong', 'Banh Trang Nuong', 'Vietnamese pizza - grilled rice paper topped with egg, green onions, dried shrimp, and chili sauce. A popular Da Lat night market snack.', 'Bánh Tráng Nướng', 'banh', 'street_food', 'highlands', 'Da Lat', ARRAY['indigenous', 'fusion'], true, 'egg', 'grilled', 'none', ARRAY['snack', 'street_food'], true, true, ARRAY['ING_RICE_PAPER', 'ING_EGG', 'ING_GREEN_ONION', 'ING_DRIED_SHRIMP', 'ING_PORK_FLOSS', 'ING_CHILI_SAUCE', 'ING_MAYONNAISE', 'ING_CHEESE', 'ING_BUTTER'], ARRAY['eggs', 'shellfish', 'dairy'], true, false, true, false, false, false, false, 280, 12, 25, 14, 2, ARRAY['grilled', 'rice_paper', 'pizza', 'da_lat', 'night_market'], 82),
  ('VIETNAMESE_GOI_CUON', 'goi-cuon', 'Goi Cuon', 'Fresh Vietnamese spring rolls with rice paper, shrimp, pork, rice vermicelli, and fresh herbs. Served with peanut hoisin dipping sauce.', 'Gỏi Cuốn', 'goi_cuon', 'signature', 'southern', 'Saigon', ARRAY['chinese', 'indigenous'], false, 'mixed', 'raw', 'none', ARRAY['appetizer', 'snack', 'lunch'], true, true, ARRAY['ING_RICE_PAPER', 'ING_SHRIMP', 'ING_PORK_BELLY', 'ING_RICE_VERMICELLI', 'ING_LETTUCE', 'ING_MINT', 'ING_PERILLA', 'ING_CHIVES', 'ING_HOISIN_SAUCE', 'ING_PEANUTS', 'ING_GARLIC', 'ING_CHILI'], ARRAY['shellfish', 'peanuts', 'soy'], true, true, false, false, false, false, false, 180, 12, 22, 4, 0, ARRAY['fresh_rolls', 'healthy', 'light', 'herbs', 'appetizer', 'iconic'], 95),
  ('VIETNAMESE_GOI_CUON_TOM_THIT', 'goi-cuon-tom-thit', 'Goi Cuon Tom Thit', 'Classic shrimp and pork spring rolls - the most traditional combination. Pink shrimp visible through the translucent rice paper.', 'Gỏi Cuốn Tôm Thịt', 'goi_cuon', 'classic', 'southern', NULL, ARRAY['indigenous'], false, 'mixed', 'raw', 'none', ARRAY['appetizer', 'snack'], true, false, ARRAY['ING_RICE_PAPER', 'ING_SHRIMP', 'ING_PORK_LOIN', 'ING_RICE_VERMICELLI', 'ING_LETTUCE', 'ING_MINT', 'ING_BEAN_SPROUTS', 'ING_CHIVES', 'ING_HOISIN_SAUCE', 'ING_PEANUTS', 'ING_LIME'], ARRAY['shellfish', 'peanuts', 'soy'], true, true, false, false, false, false, false, 190, 14, 20, 5, 0, ARRAY['fresh_rolls', 'shrimp', 'pork', 'classic', 'traditional'], 92),
  ('VIETNAMESE_GOI_CUON_CHAY', 'goi-cuon-chay', 'Goi Cuon Chay', 'Vegetarian spring rolls with tofu, mushrooms, carrots, and fresh herbs. A Buddhist-friendly version with full flavor.', 'Gỏi Cuốn Chay', 'goi_cuon', 'active', 'national', NULL, ARRAY['chinese', 'indigenous'], false, 'tofu', 'raw', 'none', ARRAY['appetizer', 'snack', 'lunch'], true, true, ARRAY['ING_RICE_PAPER', 'ING_TOFU', 'ING_SHIITAKE_MUSHROOMS', 'ING_RICE_VERMICELLI', 'ING_LETTUCE', 'ING_MINT', 'ING_CARROTS', 'ING_CUCUMBER', 'ING_SOY_SAUCE', 'ING_HOISIN_SAUCE', 'ING_PEANUTS', 'ING_SESAME_SEEDS'], ARRAY['soy', 'peanuts', 'sesame'], true, true, false, true, true, true, true, 150, 8, 22, 4, 0, ARRAY['fresh_rolls', 'vegetarian', 'vegan', 'tofu', 'healthy'], 75),
  ('VIETNAMESE_GOI_CUON_BO', 'goi-cuon-bo', 'Goi Cuon Bo', 'Fresh spring rolls with grilled beef, lemongrass marinade, and fresh herbs. A protein-rich variation popular in modern Vietnamese restaurants.', 'Gỏi Cuốn Bò', 'goi_cuon', 'popular', 'national', NULL, ARRAY['indigenous', 'fusion'], false, 'beef', 'grilled', 'none', ARRAY['appetizer', 'lunch'], true, false, ARRAY['ING_RICE_PAPER', 'ING_BEEF_SIRLOIN', 'ING_LEMONGRASS', 'ING_RICE_VERMICELLI', 'ING_LETTUCE', 'ING_MINT', 'ING_PERILLA', 'ING_PICKLED_CARROTS', 'ING_HOISIN_SAUCE', 'ING_PEANUTS', 'ING_GARLIC', 'ING_FISH_SAUCE'], ARRAY['peanuts', 'soy', 'fish'], true, true, false, false, false, false, false, 220, 18, 20, 8, 1, ARRAY['fresh_rolls', 'beef', 'grilled', 'lemongrass', 'protein'], 80),
  ('VIETNAMESE_CHA_GIO', 'cha-gio', 'Cha Gio', 'Crispy fried spring rolls filled with ground pork, crab, wood ear mushrooms, and glass noodles. The Southern Vietnamese version of egg rolls.', 'Chả Giò', 'goi_cuon', 'signature', 'southern', 'Saigon', ARRAY['chinese', 'indigenous'], false, 'mixed', 'deep_fried', 'none', ARRAY['appetizer', 'snack', 'banquet'], true, true, ARRAY['ING_RICE_PAPER', 'ING_GROUND_PORK', 'ING_CRAB_MEAT', 'ING_WOOD_EAR_MUSHROOMS', 'ING_GLASS_NOODLES', 'ING_CARROTS', 'ING_TARO', 'ING_SHALLOTS', 'ING_FISH_SAUCE', 'ING_PEPPER', 'ING_VEGETABLE_OIL', 'ING_NUOC_CHAM'], ARRAY['shellfish', 'fish'], true, true, true, false, false, false, false, 320, 14, 28, 18, 0, ARRAY['fried_rolls', 'crispy', 'appetizer', 'party_food', 'crab'], 90),
  ('VIETNAMESE_NEM_RAN', 'nem-ran', 'Nem Ran', 'Northern Vietnamese fried spring rolls, typically smaller and with a wheat-based wrapper. Hanoi\', 'Nem Rán', 'goi_cuon', 'classic', 'northern', 'Hanoi', ARRAY['chinese', 'indigenous'], false, 'pork', 'deep_fried', 'none', ARRAY['appetizer', 'snack', 'banquet'], true, true, ARRAY['ING_WHEAT_WRAPPER', 'ING_GROUND_PORK', 'ING_WOOD_EAR_MUSHROOMS', 'ING_GLASS_NOODLES', 'ING_KOHLRABI', 'ING_CARROTS', 'ING_SHALLOTS', 'ING_EGG', 'ING_FISH_SAUCE', 'ING_PEPPER', 'ING_VEGETABLE_OIL', 'ING_NUOC_CHAM'], ARRAY['gluten', 'eggs', 'fish'], false, true, true, false, false, false, false, 300, 12, 30, 16, 0, ARRAY['fried_rolls', 'hanoi', 'northern', 'crispy', 'traditional'], 85),
  ('VIETNAMESE_CHA_GIO_CHAY', 'cha-gio-chay', 'Cha Gio Chay', 'Vegetarian fried spring rolls with tofu, mushrooms, taro, and glass noodles. Buddhist temple-style filling.', 'Chả Giò Chay', 'goi_cuon', 'active', 'national', NULL, ARRAY['chinese', 'indigenous'], false, 'tofu', 'deep_fried', 'none', ARRAY['appetizer', 'snack'], true, true, ARRAY['ING_RICE_PAPER', 'ING_TOFU', 'ING_SHIITAKE_MUSHROOMS', 'ING_WOOD_EAR_MUSHROOMS', 'ING_GLASS_NOODLES', 'ING_TARO', 'ING_CARROTS', 'ING_JICAMA', 'ING_SOY_SAUCE', 'ING_PEPPER', 'ING_VEGETABLE_OIL', 'ING_VEGETARIAN_NUOC_CHAM'], ARRAY['soy'], true, true, true, true, true, true, true, 280, 8, 32, 14, 0, ARRAY['fried_rolls', 'vegetarian', 'vegan', 'tofu', 'crispy'], 70),
  ('VIETNAMESE_CHA_GIO_TOM_CUA', 'cha-gio-tom-cua', 'Cha Gio Tom Cua', 'Premium fried spring rolls with shrimp and crab meat. A luxurious version served at special occasions.', 'Chả Giò Tôm Cua', 'goi_cuon', 'premium', 'southern', NULL, ARRAY['chinese', 'indigenous'], false, 'mixed_seafood', 'deep_fried', 'none', ARRAY['appetizer', 'banquet'], false, false, ARRAY['ING_RICE_PAPER', 'ING_SHRIMP', 'ING_CRAB_MEAT', 'ING_GROUND_PORK', 'ING_GLASS_NOODLES', 'ING_TARO', 'ING_CARROTS', 'ING_SHALLOTS', 'ING_FISH_SAUCE', 'ING_EGG', 'ING_VEGETABLE_OIL', 'ING_NUOC_CHAM'], ARRAY['shellfish', 'fish', 'eggs'], true, true, true, false, false, false, false, 350, 18, 26, 20, 0, ARRAY['fried_rolls', 'premium', 'seafood', 'crab', 'shrimp', 'banquet'], 82),
  ('VIETNAMESE_BI_CUON', 'bi-cuon', 'Bi Cuon', 'Fresh rolls filled with shredded pork skin, roasted rice powder, and herbs. A unique texture combination in rice paper.', 'Bì Cuốn', 'goi_cuon', 'classic', 'southern', NULL, ARRAY['indigenous'], false, 'pork', 'raw', 'none', ARRAY['appetizer', 'snack'], true, false, ARRAY['ING_RICE_PAPER', 'ING_PORK_SKIN', 'ING_ROASTED_RICE_POWDER', 'ING_RICE_VERMICELLI', 'ING_LETTUCE', 'ING_MINT', 'ING_PERILLA', 'ING_FISH_SAUCE', 'ING_GARLIC', 'ING_SUGAR', 'ING_LIME', 'ING_CHILI'], ARRAY['fish'], true, true, true, false, false, false, false, 200, 15, 18, 8, 1, ARRAY['fresh_rolls', 'pork_skin', 'roasted_rice', 'chewy', 'traditional'], 68),
  ('VIETNAMESE_BO_BIA', 'bo-bia', 'Bo Bia', 'Sweet and savory rolls with Chinese sausage, dried shrimp, jicama, and egg. A Teochew-influenced street snack.', 'Bò Bía', 'goi_cuon', 'street_food', 'southern', 'Saigon', ARRAY['chinese'], false, 'mixed', 'raw', 'none', ARRAY['snack', 'street_food'], true, false, ARRAY['ING_RICE_PAPER', 'ING_LAP_XUONG', 'ING_DRIED_SHRIMP', 'ING_JICAMA', 'ING_EGG_OMELET', 'ING_LETTUCE', 'ING_MINT', 'ING_HOISIN_SAUCE', 'ING_PEANUT_BUTTER', 'ING_CHILI_SAUCE', 'ING_GARLIC', 'ING_SOY_SAUCE'], ARRAY['shellfish', 'eggs', 'peanuts', 'soy'], true, true, false, false, false, false, false, 250, 10, 28, 12, 1, ARRAY['fresh_rolls', 'chinese_influence', 'sweet_savory', 'street_food'], 72),
  ('VIETNAMESE_CUON_DIEP', 'cuon-diep', 'Cuon Diep', 'Grilled beef wrapped in betel leaves (la lot), then wrapped again in rice paper with herbs. Double-wrapped deliciousness.', 'Cuốn Diệp', 'goi_cuon', 'popular', 'southern', NULL, ARRAY['indigenous'], false, 'beef', 'grilled', 'none', ARRAY['appetizer', 'dinner'], true, false, ARRAY['ING_RICE_PAPER', 'ING_GROUND_BEEF', 'ING_BETEL_LEAVES', 'ING_RICE_VERMICELLI', 'ING_LETTUCE', 'ING_MINT', 'ING_PERILLA', 'ING_LEMONGRASS', 'ING_FISH_SAUCE', 'ING_GARLIC', 'ING_NUOC_CHAM', 'ING_PEANUTS'], ARRAY['fish', 'peanuts'], true, true, false, false, false, false, false, 240, 16, 20, 12, 1, ARRAY['fresh_rolls', 'beef', 'betel_leaf', 'grilled', 'aromatic'], 78),
  ('VIETNAMESE_COM_TAM_SUON_BI_CHA', 'com-tam-suon-bi-cha', 'Com Tam Suon Bi Cha', 'The quintessential Saigon breakfast: broken rice with grilled pork chop, shredded pork skin, and steamed egg meatloaf. A complete meal.', 'Cơm Tấm Sườn Bì Chả', 'com', 'signature', 'southern', 'Saigon', ARRAY['indigenous'], false, 'pork', 'grilled', 'none', ARRAY['breakfast', 'lunch', 'dinner'], true, false, ARRAY['ING_BROKEN_RICE', 'ING_PORK_CHOP', 'ING_PORK_SKIN', 'ING_PORK_EGG_MEATLOAF', 'ING_FISH_SAUCE', 'ING_SUGAR', 'ING_GARLIC', 'ING_SHALLOTS', 'ING_CUCUMBER', 'ING_TOMATOES', 'ING_PICKLED_CARROTS', 'ING_GREEN_ONION'], ARRAY['fish', 'eggs'], true, true, true, false, false, false, false, 680, 38, 72, 26, 1, ARRAY['broken_rice', 'saigon', 'breakfast', 'signature', 'pork_chop'], 95),
  ('VIETNAMESE_COM_TAM_SUON_NUONG', 'com-tam-suon-nuong', 'Com Tam Suon Nuong', 'Broken rice with grilled marinated pork chop. The classic, simple version of com tam with just the essential grilled meat.', 'Cơm Tấm Sườn Nướng', 'com', 'popular', 'southern', 'Saigon', ARRAY['indigenous'], false, 'pork', 'grilled', 'none', ARRAY['breakfast', 'lunch', 'dinner'], true, false, ARRAY['ING_BROKEN_RICE', 'ING_PORK_CHOP', 'ING_FISH_SAUCE', 'ING_LEMONGRASS', 'ING_GARLIC', 'ING_SUGAR', 'ING_SHALLOTS', 'ING_CUCUMBER', 'ING_TOMATOES', 'ING_PICKLED_CARROTS', 'ING_GREEN_ONION', 'ING_VEGETABLE_OIL'], ARRAY['fish'], true, true, true, false, false, false, false, 580, 32, 68, 20, 1, ARRAY['broken_rice', 'grilled', 'pork_chop', 'simple', 'classic'], 90),
  ('VIETNAMESE_COM_TAM_GA_NUONG', 'com-tam-ga-nuong', 'Com Tam Ga Nuong', 'Broken rice with grilled lemongrass chicken. A lighter alternative to pork, popular among health-conscious diners.', 'Cơm Tấm Gà Nướng', 'com', 'popular', 'southern', NULL, ARRAY['indigenous'], false, 'chicken', 'grilled', 'none', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_BROKEN_RICE', 'ING_CHICKEN_THIGH', 'ING_LEMONGRASS', 'ING_FISH_SAUCE', 'ING_GARLIC', 'ING_SUGAR', 'ING_SHALLOTS', 'ING_CUCUMBER', 'ING_TOMATOES', 'ING_PICKLED_CARROTS', 'ING_GREEN_ONION', 'ING_VEGETABLE_OIL'], ARRAY['fish'], true, true, true, false, false, true, false, 520, 35, 65, 14, 1, ARRAY['broken_rice', 'chicken', 'grilled', 'lighter', 'halal'], 82),
  ('VIETNAMESE_COM_CHIEN_DUONG_CHAU', 'com-chien-duong-chau', 'Com Chien Duong Chau', 'Vietnamese Yangzhou-style fried rice with shrimp, Chinese sausage, eggs, and vegetables. A Chinese-influenced favorite.', 'Cơm Chiên Dương Châu', 'com', 'popular', 'national', NULL, ARRAY['chinese'], false, 'mixed', 'stir_fried', 'none', ARRAY['lunch', 'dinner'], true, true, ARRAY['ING_JASMINE_RICE', 'ING_SHRIMP', 'ING_LAP_XUONG', 'ING_EGG', 'ING_PEAS', 'ING_CARROTS', 'ING_GREEN_ONION', 'ING_SOY_SAUCE', 'ING_FISH_SAUCE', 'ING_GARLIC', 'ING_SESAME_OIL', 'ING_PEPPER'], ARRAY['shellfish', 'eggs', 'soy', 'fish', 'sesame'], true, true, true, false, false, false, false, 520, 22, 65, 18, 0, ARRAY['fried_rice', 'chinese_style', 'shrimp', 'sausage', 'classic'], 85),
  ('VIETNAMESE_COM_CHIEN_CA_MAN', 'com-chien-ca-man', 'Com Chien Ca Man', 'Salted fish fried rice, a bold and savory Southern Vietnamese specialty. The umami-packed comfort food.', 'Cơm Chiên Cá Mặn', 'com', 'regional', 'southern', NULL, ARRAY['chinese', 'indigenous'], false, 'fish', 'stir_fried', 'none', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_JASMINE_RICE', 'ING_SALTED_FISH', 'ING_EGG', 'ING_GREEN_ONION', 'ING_GARLIC', 'ING_SOY_SAUCE', 'ING_VEGETABLE_OIL', 'ING_PEPPER', 'ING_CHILI', 'ING_CUCUMBER', 'ING_LETTUCE', 'ING_LIME'], ARRAY['fish', 'eggs', 'soy'], true, true, true, false, false, true, true, 480, 20, 62, 16, 1, ARRAY['fried_rice', 'salted_fish', 'umami', 'southern', 'bold'], 72),
  ('VIETNAMESE_COM_TAY_CAM', 'com-tay-cam', 'Com Tay Cam', 'Vietnamese claypot rice with caramelized pork, Chinese sausage, and a crispy rice crust at the bottom. Hanoi-style comfort food.', 'Cơm Tay Cầm', 'com', 'classic', 'northern', 'Hanoi', ARRAY['chinese', 'indigenous'], false, 'pork', 'braised', 'none', ARRAY['lunch', 'dinner'], false, false, ARRAY['ING_JASMINE_RICE', 'ING_PORK_BELLY', 'ING_LAP_XUONG', 'ING_SOY_SAUCE', 'ING_CARAMEL_SAUCE', 'ING_SHALLOTS', 'ING_GARLIC', 'ING_GINGER', 'ING_PEPPER', 'ING_GREEN_ONION', 'ING_FISH_SAUCE', 'ING_VEGETABLE_OIL'], ARRAY['soy', 'fish'], true, true, true, false, false, false, false, 620, 28, 70, 24, 0, ARRAY['claypot', 'caramelized', 'crispy_rice', 'comfort_food', 'hanoi'], 78),
  ('VIETNAMESE_COM_NIEU_SINGAPORE', 'com-nieu-singapore', 'Com Nieu Singapore', 'Claypot rice Singapore-style served in Vietnam, with the rice dramatically thrown into the air at the table. An entertaining dining experience.', 'Cơm Niêu Singapore', 'com', 'popular', 'national', NULL, ARRAY['chinese', 'fusion'], true, 'mixed', 'braised', 'none', ARRAY['dinner'], false, false, ARRAY['ING_JASMINE_RICE', 'ING_CHICKEN', 'ING_LAP_XUONG', 'ING_SHIITAKE_MUSHROOMS', 'ING_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_GARLIC', 'ING_GINGER', 'ING_SESAME_OIL', 'ING_GREEN_ONION', 'ING_PEPPER', 'ING_VEGETABLE_OIL'], ARRAY['soy', 'sesame', 'shellfish'], true, true, true, false, false, false, false, 580, 30, 68, 20, 0, ARRAY['claypot', 'singapore_style', 'showmanship', 'entertaining', 'restaurant'], 75),
  ('VIETNAMESE_XOI_XEO', 'xoi-xeo', 'Xoi Xeo', 'Yellow sticky rice with mung beans and fried shallots, topped with shredded chicken. A Hanoi morning staple.', 'Xôi Xéo', 'com', 'classic', 'northern', 'Hanoi', ARRAY['indigenous'], false, 'chicken', 'steamed', 'none', ARRAY['breakfast', 'snack'], true, true, ARRAY['ING_GLUTINOUS_RICE', 'ING_MUNG_BEANS', 'ING_TURMERIC', 'ING_CHICKEN', 'ING_FRIED_SHALLOTS', 'ING_COCONUT_MILK', 'ING_PATE', 'ING_SOY_SAUCE', 'ING_SUGAR', 'ING_SALT', 'ING_VEGETABLE_OIL', 'ING_PEPPER'], ARRAY['soy'], true, true, true, false, false, true, false, 450, 20, 58, 16, 0, ARRAY['sticky_rice', 'mung_beans', 'breakfast', 'hanoi', 'yellow'], 82),
  ('VIETNAMESE_XOI_GA', 'xoi-ga', 'Xoi Ga', 'Sticky rice with shredded chicken, fried shallots, and pate. Simple, satisfying, and portable breakfast food.', 'Xôi Gà', 'com', 'popular', 'national', NULL, ARRAY['indigenous'], false, 'chicken', 'steamed', 'none', ARRAY['breakfast', 'snack'], true, false, ARRAY['ING_GLUTINOUS_RICE', 'ING_CHICKEN_BREAST', 'ING_FRIED_SHALLOTS', 'ING_PATE', 'ING_SOY_SAUCE', 'ING_FISH_SAUCE', 'ING_SALT', 'ING_PEPPER', 'ING_VEGETABLE_OIL'], ARRAY['soy', 'fish'], true, true, true, false, false, false, false, 420, 25, 52, 14, 0, ARRAY['sticky_rice', 'chicken', 'breakfast', 'portable', 'simple'], 80),
  ('VIETNAMESE_COM_GA_HOI_AN', 'com-ga-hoi-an', 'Com Ga Hoi An', 'Hoi An chicken rice with turmeric-infused rice, shredded poached chicken, and fresh herbs. Central Vietnam\', 'Cơm Gà Hội An', 'com', 'signature', 'central', 'Hoi An', ARRAY['chinese', 'indigenous'], false, 'chicken', 'boiled', 'chicken', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_JASMINE_RICE', 'ING_CHICKEN', 'ING_TURMERIC', 'ING_GINGER', 'ING_GARLIC', 'ING_FISH_SAUCE', 'ING_MINT', 'ING_VIETNAMESE_CORIANDER', 'ING_ONION', 'ING_GREEN_ONION', 'ING_CHILI', 'ING_LIME'], ARRAY['fish'], true, true, true, false, false, true, false, 520, 35, 58, 14, 1, ARRAY['chicken_rice', 'hoi_an', 'turmeric', 'central_vietnam', 'signature'], 88),
  ('VIETNAMESE_MI_QUANG', 'mi-quang', 'Mi Quang', 'Central Vietnam\', 'Mì Quảng', 'mi', 'signature', 'central', 'Quang Nam', ARRAY['indigenous', 'cham'], false, 'mixed', 'simmered', 'mixed', ARRAY['breakfast', 'lunch'], true, false, ARRAY['ING_RICE_NOODLES_WIDE', 'ING_SHRIMP', 'ING_PORK_LOIN', 'ING_QUAIL_EGGS', 'ING_TURMERIC', 'ING_PEANUTS', 'ING_RICE_CRACKERS', 'ING_BANANA_BLOSSOM', 'ING_MINT', 'ING_BASIL', 'ING_FISH_SAUCE', 'ING_CHILI'], ARRAY['shellfish', 'fish', 'peanuts', 'eggs'], true, true, false, false, false, false, false, 520, 30, 55, 18, 2, ARRAY['noodles', 'central_vietnam', 'turmeric', 'signature', 'quang_nam'], 90),
  ('VIETNAMESE_MI_XAO', 'mi-xao', 'Mi Xao', 'Vietnamese stir-fried egg noodles with seafood or meat and vegetables. Crispy on the outside, soft inside.', 'Mì Xào', 'mi', 'popular', 'national', NULL, ARRAY['chinese'], false, 'mixed_seafood', 'stir_fried', 'none', ARRAY['lunch', 'dinner'], true, true, ARRAY['ING_EGG_NOODLES', 'ING_SHRIMP', 'ING_SQUID', 'ING_BOK_CHOY', 'ING_CARROTS', 'ING_BABY_CORN', 'ING_OYSTER_SAUCE', 'ING_SOY_SAUCE', 'ING_GARLIC', 'ING_VEGETABLE_OIL', 'ING_SESAME_OIL', 'ING_PEPPER'], ARRAY['shellfish', 'gluten', 'soy', 'eggs', 'sesame'], false, true, true, false, false, false, false, 480, 25, 52, 18, 1, ARRAY['stir_fried', 'noodles', 'crispy', 'chinese_influence', 'seafood'], 78),
  ('VIETNAMESE_LAU_THAI', 'lau-thai', 'Lau Thai', 'Vietnamese-Thai fusion hot pot with spicy tom yum-inspired broth, seafood, and vegetables. Popular for group dining.', 'Lẩu Thái', 'lau', 'popular', 'national', NULL, ARRAY['thai', 'fusion'], true, 'mixed_seafood', 'hot_pot', 'seafood', ARRAY['dinner'], false, true, ARRAY['ING_SHRIMP', 'ING_SQUID', 'ING_FISH_BALLS', 'ING_TOFU', 'ING_MUSHROOMS', 'ING_MORNING_GLORY', 'ING_LEMONGRASS', 'ING_GALANGAL', 'ING_KAFFIR_LIME_LEAVES', 'ING_CHILI', 'ING_LIME', 'ING_FISH_SAUCE'], ARRAY['shellfish', 'fish', 'soy'], true, true, true, false, false, false, false, 380, 35, 25, 15, 4, ARRAY['hot_pot', 'spicy', 'thai_fusion', 'group_dining', 'seafood'], 85),
  ('VIETNAMESE_LAU_DE', 'lau-de', 'Lau De', 'Goat hot pot, a Northern Vietnamese specialty. Aromatic herbal broth with tender goat meat and vegetables.', 'Lẩu Dê', 'lau', 'regional', 'northern', NULL, ARRAY['chinese', 'indigenous'], false, 'mixed', 'hot_pot', 'mixed', ARRAY['dinner'], false, false, ARRAY['ING_GOAT_MEAT', 'ING_GOAT_BONES', 'ING_GINGER', 'ING_LEMONGRASS', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_FENNEL_SEEDS', 'ING_RICE_WINE', 'ING_TOFU', 'ING_MUSHROOMS', 'ING_MORNING_GLORY', 'ING_FERMENTED_TOFU'], ARRAY['soy'], true, true, true, false, false, true, false, 450, 40, 18, 25, 2, ARRAY['hot_pot', 'goat', 'herbal', 'northern', 'warming'], 70),
  ('VIETNAMESE_GOI_GA', 'goi-ga', 'Goi Ga', 'Vietnamese chicken salad with shredded cabbage, carrots, herbs, and fried shallots. Dressed with lime, fish sauce, and chili.', 'Gỏi Gà', 'goi', 'popular', 'national', NULL, ARRAY['indigenous'], false, 'chicken', 'boiled', 'none', ARRAY['appetizer', 'lunch'], true, false, ARRAY['ING_CHICKEN_BREAST', 'ING_CABBAGE', 'ING_CARROTS', 'ING_ONION', 'ING_VIETNAMESE_CORIANDER', 'ING_MINT', 'ING_FRIED_SHALLOTS', 'ING_PEANUTS', 'ING_FISH_SAUCE', 'ING_LIME', 'ING_SUGAR', 'ING_CHILI'], ARRAY['fish', 'peanuts'], true, true, false, false, false, true, false, 280, 25, 18, 12, 2, ARRAY['salad', 'chicken', 'refreshing', 'herbs', 'crunchy'], 82),
  ('VIETNAMESE_GOI_XOAI', 'goi-xoai', 'Goi Xoai', 'Green mango salad with dried shrimp, peanuts, and herbs. Sweet, sour, salty, and crunchy in every bite.', 'Gỏi Xoài', 'goi', 'popular', 'southern', NULL, ARRAY['thai', 'indigenous'], false, 'shrimp', 'raw', 'none', ARRAY['appetizer', 'snack'], true, true, ARRAY['ING_GREEN_MANGO', 'ING_DRIED_SHRIMP', 'ING_PEANUTS', 'ING_VIETNAMESE_CORIANDER', 'ING_MINT', 'ING_THAI_BASIL', 'ING_FISH_SAUCE', 'ING_LIME', 'ING_SUGAR', 'ING_CHILI', 'ING_GARLIC', 'ING_FRIED_SHALLOTS'], ARRAY['shellfish', 'fish', 'peanuts'], true, true, false, false, false, false, true, 220, 10, 28, 8, 3, ARRAY['salad', 'mango', 'refreshing', 'spicy', 'crunchy'], 78),
  ('VIETNAMESE_BO_LA_LOT', 'bo-la-lot', 'Bo La Lot', 'Grilled beef wrapped in betel leaves. Aromatic, charred, and bursting with lemongrass flavor. A beloved appetizer.', 'Bò Lá Lốt', 'nuong', 'signature', 'southern', NULL, ARRAY['indigenous'], false, 'beef', 'grilled', 'none', ARRAY['appetizer', 'dinner'], true, false, ARRAY['ING_GROUND_BEEF', 'ING_BETEL_LEAVES', 'ING_LEMONGRASS', 'ING_GARLIC', 'ING_SHALLOTS', 'ING_FISH_SAUCE', 'ING_SUGAR', 'ING_PEPPER', 'ING_FIVE_SPICE', 'ING_VEGETABLE_OIL', 'ING_PEANUTS', 'ING_NUOC_CHAM'], ARRAY['fish', 'peanuts'], true, true, false, false, false, false, false, 320, 22, 12, 20, 1, ARRAY['grilled', 'beef', 'betel_leaves', 'aromatic', 'appetizer'], 88),
  ('VIETNAMESE_THIT_NUONG', 'thit-nuong', 'Thit Nuong', 'Vietnamese grilled pork, marinated in lemongrass, fish sauce, and honey. The foundation of many noodle and rice dishes.', 'Thịt Nướng', 'nuong', 'classic', 'national', NULL, ARRAY['indigenous'], false, 'pork', 'grilled', 'none', ARRAY['lunch', 'dinner'], true, false, ARRAY['ING_PORK_SHOULDER', 'ING_LEMONGRASS', 'ING_FISH_SAUCE', 'ING_HONEY', 'ING_GARLIC', 'ING_SHALLOTS', 'ING_SUGAR', 'ING_PEPPER', 'ING_VEGETABLE_OIL', 'ING_SESAME_SEEDS', 'ING_GREEN_ONION', 'ING_NUOC_CHAM'], ARRAY['fish', 'sesame'], true, true, true, false, false, false, false, 380, 28, 15, 24, 0, ARRAY['grilled', 'pork', 'lemongrass', 'classic', 'marinade'], 85),
  ('VIETNAMESE_THIT_KHO_TRUNG', 'thit-kho-trung', 'Thit Kho Trung', 'Caramelized pork belly braised with eggs in coconut water. The ultimate Vietnamese comfort food, especially for Tet.', 'Thịt Kho Trứng', 'kho', 'signature', 'southern', NULL, ARRAY['chinese', 'indigenous'], false, 'pork', 'braised', 'none', ARRAY['lunch', 'dinner'], false, false, ARRAY['ING_PORK_BELLY', 'ING_EGGS', 'ING_COCONUT_WATER', 'ING_CARAMEL_SAUCE', 'ING_FISH_SAUCE', 'ING_GARLIC', 'ING_SHALLOTS', 'ING_PEPPER', 'ING_SUGAR', 'ING_JASMINE_RICE', 'ING_GREEN_ONION', 'ING_PICKLED_MUSTARD'], ARRAY['fish', 'eggs'], true, true, true, false, false, false, false, 580, 32, 25, 38, 0, ARRAY['braised', 'caramelized', 'pork_belly', 'eggs', 'tet', 'comfort_food'], 92),
  ('VIETNAMESE_CA_KHO_TO', 'ca-kho-to', 'Ca Kho To', 'Caramelized fish in clay pot, braised until the sauce is thick and the fish melts in your mouth. A Southern classic.', 'Cá Kho Tộ', 'kho', 'classic', 'southern', NULL, ARRAY['indigenous'], false, 'fish', 'braised', 'none', ARRAY['lunch', 'dinner'], false, false, ARRAY['ING_CATFISH', 'ING_CARAMEL_SAUCE', 'ING_FISH_SAUCE', 'ING_COCONUT_WATER', 'ING_GARLIC', 'ING_SHALLOTS', 'ING_GINGER', 'ING_PEPPER', 'ING_CHILI', 'ING_GREEN_ONION', 'ING_JASMINE_RICE', 'ING_VEGETABLE_OIL'], ARRAY['fish'], true, true, true, false, false, true, true, 420, 35, 20, 22, 1, ARRAY['braised', 'caramelized', 'fish', 'claypot', 'southern', 'umami'], 85),
  ('VIETNAMESE_CHE_BA_MAU', 'che-ba-mau', 'Che Ba Mau', 'Three-color dessert with mung beans, red beans, and pandan jelly, topped with coconut milk and crushed ice. Vietnam\', 'Chè Ba Màu', 'che', 'signature', 'southern', NULL, ARRAY['chinese', 'indigenous'], false, 'none', 'boiled', 'none', ARRAY['snack', 'any_time'], true, true, ARRAY['ING_MUNG_BEANS', 'ING_RED_BEANS', 'ING_PANDAN_JELLY', 'ING_COCONUT_MILK', 'ING_SUGAR', 'ING_ICE', 'ING_TAPIOCA_PEARLS', 'ING_PALM_SUGAR', 'ING_SALT'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 320, 8, 58, 8, 0, ARRAY['dessert', 'sweet', 'colorful', 'coconut', 'refreshing', 'iced'], 90),
  ('VIETNAMESE_CHE_CHUOI', 'che-chuoi', 'Che Chuoi', 'Banana in coconut milk, served warm with tapioca pearls. A simple, comforting Southern Vietnamese dessert.', 'Chè Chuối', 'che', 'classic', 'southern', NULL, ARRAY['indigenous'], false, 'none', 'simmered', 'none', ARRAY['snack', 'any_time'], true, true, ARRAY['ING_BANANAS', 'ING_COCONUT_MILK', 'ING_TAPIOCA_PEARLS', 'ING_SUGAR', 'ING_PANDAN_LEAVES', 'ING_SALT', 'ING_SESAME_SEEDS', 'ING_PEANUTS'], ARRAY['peanuts', 'sesame'], true, true, false, true, true, true, true, 280, 4, 48, 10, 0, ARRAY['dessert', 'banana', 'coconut', 'warm', 'comforting', 'simple'], 78),
  ('VIETNAMESE_CA_PHE_SUA_DA', 'ca-phe-sua-da', 'Ca Phe Sua Da', 'Vietnamese iced coffee with sweetened condensed milk. Strong, sweet, and intensely caffeinated - Vietnam\', 'Cà Phê Sữa Đá', 'do_uong', 'signature', 'national', NULL, ARRAY['french_colonial', 'indigenous'], true, 'none', 'raw', 'none', ARRAY['breakfast', 'any_time'], true, true, ARRAY['ING_VIETNAMESE_COFFEE', 'ING_CONDENSED_MILK', 'ING_ICE', 'ING_WATER'], ARRAY['dairy'], true, false, true, false, true, true, true, 150, 3, 25, 4, 0, ARRAY['coffee', 'iced', 'sweet', 'iconic', 'french_influence', 'caffeine'], 98),
  ('VIETNAMESE_SINH_TO_BO', 'sinh-to-bo', 'Sinh To Bo', 'Avocado smoothie blended with condensed milk and ice. Creamy, sweet, and refreshing - a Vietnamese dessert drink.', 'Sinh Tố Bơ', 'do_uong', 'popular', 'national', NULL, ARRAY['american', 'indigenous'], true, 'none', 'raw', 'none', ARRAY['snack', 'any_time'], true, true, ARRAY['ING_AVOCADO', 'ING_CONDENSED_MILK', 'ING_ICE', 'ING_MILK', 'ING_SUGAR'], ARRAY['dairy'], true, false, true, false, true, true, true, 380, 5, 42, 22, 0, ARRAY['smoothie', 'avocado', 'sweet', 'creamy', 'refreshing'], 82),
  ('VIETNAMESE_NUOC_MIA', 'nuoc-mia', 'Nuoc Mia', 'Fresh sugarcane juice, often mixed with kumquat. Extremely refreshing, especially in Vietnam\', 'Nước Mía', 'do_uong', 'street_food', 'national', NULL, ARRAY['indigenous'], false, 'none', 'raw', 'none', ARRAY['snack', 'any_time'], true, true, ARRAY['ING_SUGARCANE', 'ING_KUMQUAT', 'ING_ICE'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 180, 0, 45, 0, 0, ARRAY['juice', 'sugarcane', 'refreshing', 'street_food', 'natural'], 85);

-- Total: 72 Vietnamese dishes imported

-- Statistics by category:
--   banh: 13
--   bun: 10
--   che: 2
--   com: 10
--   do_uong: 3
--   goi: 2
--   goi_cuon: 11
--   kho: 2
--   lau: 2
--   mi: 2
--   nuong: 2
--   pho: 13
