-- Filipino Cuisine - Data
-- GUDBRO Database Standards v1.7
-- Generated: 2025-12-25
--
-- Total dishes: 59

-- =====================================================
-- INSERT DISHES
-- =====================================================

INSERT INTO filipino (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, dietary, allergens, tags, popularity)
VALUES
('FIL_HALO_HALO', 'halo-halo', 'Halo-Halo', 'Halo-Halo', 'The ultimate Filipino shaved ice dessert with sweet beans, jellies, fruits, leche flan, ube ice cream, and evaporated milk', 'desserts', 'nationwide', 'iconic', 'none', 'chilled', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy,eggs}', '{shaved_ice,summer,colorful,refreshing}', 98),
('FIL_ADOBO_CHICKEN', 'chicken-adobo', 'Chicken Adobo', 'Adobong Manok', 'The national dish of the Philippines featuring chicken braised in vinegar, soy sauce, garlic, bay leaves, and black peppercorns until tender and flavorful', 'meat', 'nationwide', 'iconic', 'chicken', 'braised', 60, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{soy}', '{national_dish,comfort_food,braised,vinegar}', 98),
('FIL_ADOBO_PORK', 'pork-adobo', 'Pork Adobo', 'Adobong Baboy', 'Classic Filipino pork stew braised in soy sauce and vinegar with garlic and spices, often considered the quintessential Filipino comfort food', 'meat', 'nationwide', 'iconic', 'pork', 'braised', 75, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{soy}', '{national_dish,comfort_food,braised,pork}', 96),
('FIL_TAPSILOG', 'tapsilog', 'Tapsilog', 'Tapsilog', 'Classic Filipino breakfast of cured beef tapa, garlic fried rice, and sunny-side-up egg', 'breakfast', 'nationwide', 'iconic', 'beef', 'pan_fried', 25, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{soy,eggs}', '{silog,breakfast,tapa,cured_meat}', 95),
('FIL_LECHE_FLAN', 'leche-flan', 'Leche Flan', 'Leche Flan', 'Rich Filipino caramel custard made with egg yolks and condensed milk, denser than Spanish flan', 'desserts', 'nationwide', 'iconic', 'none', 'steamed', 60, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy,eggs}', '{caramel,custard,spanish_influenced,festive}', 95),
('FIL_LECHON', 'lechon', 'Lechon', 'Lechon Baboy', 'Whole roasted pig with incredibly crispy skin and succulent meat, the centerpiece of Filipino celebrations and considered the best roast pig in the world', 'meat', 'cebu', 'iconic', 'pork', 'roasted', 480, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{}', '{celebration,roasted,crispy_skin,cebu,festive}', 95),
('FIL_LUMPIA', 'lumpia-shanghai', 'Lumpia Shanghai', 'Lumpia Shanghai', 'Crispy fried spring rolls filled with ground pork, carrots, and onions, a party essential', 'snacks', 'nationwide', 'iconic', 'pork', 'deep_fried', 60, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{gluten}', '{party_food,spring_rolls,crispy,finger_food}', 95),
('FIL_SINIGANG_BABOY', 'sinigang-na-baboy', 'Sinigang na Baboy', 'Sinigang na Baboy', 'Iconic sour pork soup with tamarind-based broth, tomatoes, and assorted vegetables, considered the quintessential Filipino comfort soup', 'soup', 'nationwide', 'iconic', 'pork', 'boiled', 60, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{}', '{sour,tamarind,comfort_food,national_favorite}', 95),
('FIL_SISIG', 'sisig', 'Sisig', 'Sisig', 'Sizzling chopped pig face and ears seasoned with calamansi, chili peppers, and onions, served on a hot plate, originating from Pampanga', 'meat', 'pampanga', 'iconic', 'pork', 'grilled', 90, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{eggs}', '{sizzling,pampanga,bar_food,crispy,spicy}', 94),
('FIL_LONGSILOG', 'longsilog', 'Longsilog', 'Longsilog', 'Filipino breakfast combo of sweet pork longganisa sausage with garlic rice and fried egg', 'breakfast', 'nationwide', 'iconic', 'pork', 'pan_fried', 20, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{eggs}', '{silog,breakfast,longganisa,sweet}', 92),
('FIL_UBE_HALAYA', 'ube-halaya', 'Ube Halaya', 'Ube Halaya', 'Purple yam jam made by cooking mashed ube with coconut milk and condensed milk until thick', 'desserts', 'nationwide', 'iconic', 'none', 'simmered', 90, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy}', '{ube,purple,jam,versatile}', 92),
('FIL_PANCIT_CANTON', 'pancit-canton', 'Pancit Canton', 'Pancit Canton', 'Stir-fried egg noodles with meat, shrimp, and vegetables in soy sauce, a staple at Filipino celebrations', 'noodles', 'nationwide', 'iconic', 'mixed', 'stir_fried', 30, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{gluten,shellfish,soy}', '{celebration,birthday,long_life,stir_fried}', 92),
('FIL_SINANGAG', 'sinangag', 'Sinangag', 'Sinangag', 'Filipino garlic fried rice, the essential base for silog breakfast meals, made with day-old rice', 'rice', 'nationwide', 'iconic', 'none', 'stir_fried', 10, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{}', '{breakfast,garlic,fried_rice,silog}', 92),
('FIL_TOCILOG', 'tocilog', 'Tocilog', 'Tocilog', 'Sweet cured pork tocino with garlic rice and fried egg, a beloved morning meal', 'breakfast', 'nationwide', 'iconic', 'pork', 'pan_fried', 25, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{eggs}', '{silog,breakfast,tocino,sweet}', 90),
('FIL_BIBINGKA', 'bibingka', 'Bibingka', 'Bibingka', 'Soft rice cake baked in clay pots lined with banana leaves, topped with salted egg and cheese, traditional Christmas treat', 'desserts', 'nationwide', 'iconic', 'none', 'baked', 45, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy,eggs}', '{christmas,rice_cake,banana_leaf,traditional}', 90),
('FIL_KARE_KARE', 'kare-kare', 'Kare-Kare', 'Kare-Kare', 'Rich oxtail stew in a savory peanut sauce with vegetables like eggplant, string beans, and banana blossom, traditionally served with fermented shrimp paste', 'meat', 'nationwide', 'iconic', 'beef', 'braised', 180, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": false, "is_halal": true, "is_kosher": false}'::jsonb, '{peanuts,shellfish}', '{festive,peanut_sauce,oxtail,special_occasion}', 90),
('FIL_PANCIT_BIHON', 'pancit-bihon', 'Pancit Bihon', 'Pancit Bihon', 'Stir-fried rice vermicelli with chicken, pork, and vegetables, the most common pancit variety', 'noodles', 'nationwide', 'iconic', 'mixed', 'stir_fried', 30, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{soy}', '{celebration,birthday,rice_noodles,everyday}', 90),
('FIL_TURON', 'turon', 'Turon', 'Turon', 'Fried banana spring rolls with jackfruit, coated in caramelized brown sugar', 'snacks', 'nationwide', 'iconic', 'none', 'deep_fried', 20, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{gluten}', '{sweet,banana,caramelized,merienda}', 90),
('FIL_BULALO', 'bulalo', 'Bulalo', 'Bulalo', 'Rich beef bone marrow soup from Batangas, with tender beef shanks, corn on the cob, and vegetables simmered for hours', 'soup', 'nationwide', 'iconic', 'beef', 'simmered', 240, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{bone_marrow,batangas,hearty,slow_cooked}', 90),
('FIL_CRISPY_PATA', 'crispy-pata', 'Crispy Pata', 'Crispy Pata', 'Deep-fried pig trotters with incredibly crispy skin and tender meat inside, served with a soy-vinegar dipping sauce', 'meat', 'nationwide', 'iconic', 'pork', 'deep_fried', 180, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{soy}', '{crispy,deep_fried,celebration,pulutan}', 88),
('FIL_PANCIT_PALABOK', 'pancit-palabok', 'Pancit Palabok', 'Pancit Palabok', 'Rice noodles topped with rich orange shrimp sauce, crushed chicharron, shrimp, and hard-boiled eggs', 'noodles', 'nationwide', 'iconic', 'shrimp', 'boiled', 45, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{shellfish,eggs}', '{shrimp_sauce,celebration,colorful,festive}', 88),
('FIL_ARROZ_CALDO', 'arroz-caldo', 'Arroz Caldo', 'Arroz Caldo', 'Filipino chicken rice porridge with ginger, garlic, and safflower, topped with fried garlic, scallions, and hard-boiled egg', 'rice', 'nationwide', 'iconic', 'chicken', 'simmered', 45, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{eggs}', '{porridge,comfort_food,rainy_day,healing}', 88),
('FIL_SINIGANG_HIPON', 'sinigang-na-hipon', 'Sinigang na Hipon', 'Sinigang na Hipon', 'Sour shrimp soup with tamarind broth, tomatoes, and vegetables like kangkong, radish, and string beans', 'seafood', 'nationwide', 'iconic', 'shrimp', 'boiled', 40, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish}', '{sour,tamarind,comfort_food,soup}', 88),
('FIL_FISHBALL', 'fishball', 'Fishball', 'Fishball', 'Deep-fried fish balls served on a stick with sweet, spicy, or vinegar sauce, iconic street food', 'snacks', 'nationwide', 'iconic', 'fish', 'deep_fried', 15, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish,gluten}', '{street_food,fish,skewer,after_school}', 88),
('FIL_TINOLA', 'tinola', 'Tinola', 'Tinolang Manok', 'Light and healthy chicken soup with ginger, green papaya, and chili leaves in a clear savory broth', 'soup', 'nationwide', 'iconic', 'chicken', 'boiled', 45, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{ginger,healthy,light,comfort_food}', 88),
('FIL_PUTO', 'puto', 'Puto', 'Puto', 'Steamed rice cakes that are soft, fluffy, and slightly sweet, often topped with cheese', 'desserts', 'nationwide', 'classic', 'none', 'steamed', 40, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy}', '{rice_cake,steamed,merienda,soft}', 85),
('FIL_KALDERETA', 'kaldereta', 'Kaldereta', 'Kaldereta', 'Hearty meat stew with tomato sauce, liver spread, potatoes, carrots, and bell peppers, influenced by Spanish cuisine', 'meat', 'nationwide', 'classic', 'beef', 'braised', 120, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy}', '{stew,spanish_influenced,hearty,tomato_based}', 85),
('FIL_INIHAW_NA_BANGUS', 'inihaw-na-bangus', 'Inihaw na Bangus', 'Inihaw na Bangus', 'Grilled milkfish stuffed with tomatoes, onions, and garlic, wrapped in banana leaves and charcoal-grilled', 'seafood', 'nationwide', 'iconic', 'fish', 'grilled', 45, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish}', '{grilled,milkfish,stuffed,banana_leaf}', 85),
('FIL_KWEK_KWEK', 'kwek-kwek', 'Kwek-Kwek', 'Kwek-Kwek', 'Deep-fried quail eggs coated in orange batter, a popular street food served with spiced vinegar', 'snacks', 'nationwide', 'classic', 'egg', 'deep_fried', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{eggs,gluten}', '{street_food,quail_eggs,battered,orange}', 85),
('FIL_BATCHOY', 'la-paz-batchoy', 'La Paz Batchoy', 'Batchoy', 'Iloilo noodle soup with pork organs, crushed chicharron, and fresh egg noodles in a rich broth', 'soup', 'visayas', 'iconic', 'pork', 'boiled', 45, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{gluten,eggs}', '{iloilo,noodle_soup,pork_offal,chicharron}', 85),
('FIL_PINAKBET', 'pinakbet', 'Pinakbet', 'Pinakbet', 'Ilocano mixed vegetable stew with bitter melon, eggplant, okra, and squash, flavored with fermented shrimp paste', 'vegetables', 'ilocos', 'iconic', 'vegetable', 'sauteed', 35, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish}', '{ilocano,mixed_vegetables,shrimp_paste,healthy}', 85),
('FIL_BANGSILOG', 'bangsilog', 'Bangsilog', 'Bangsilog', 'Fried milkfish (bangus) with garlic rice and egg, a protein-rich Filipino breakfast', 'breakfast', 'nationwide', 'classic', 'fish', 'pan_fried', 25, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish,eggs}', '{silog,breakfast,bangus,milkfish}', 82),
('FIL_BUKO_PANDAN', 'buko-pandan', 'Buko Pandan', 'Buko Pandan', 'Refreshing dessert salad with young coconut, pandan-flavored gelatin, and cream', 'desserts', 'nationwide', 'classic', 'none', 'chilled', 30, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy}', '{coconut,pandan,refreshing,party}', 82),
('FIL_PANCIT_GUISADO', 'pancit-guisado', 'Pancit Guisado', 'Pancit Guisado', 'Home-style sauteed noodles combining bihon and canton noodles with meat and vegetables', 'noodles', 'nationwide', 'classic', 'mixed', 'stir_fried', 30, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{gluten,soy}', '{home_style,mixed_noodles,everyday}', 82),
('FIL_CHAMPORADO', 'champorado', 'Champorado', 'Champorado', 'Sweet chocolate rice porridge made with glutinous rice and cocoa, often served with dried salted fish', 'rice', 'nationwide', 'classic', 'none', 'simmered', 30, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy}', '{chocolate,breakfast,sweet,porridge}', 82),
('FIL_KINILAW', 'kinilaw', 'Kinilaw', 'Kinilaw na Tanigue', 'Filipino ceviche with fresh raw fish cured in vinegar and calamansi, mixed with ginger, onions, and chilies', 'seafood', 'visayas', 'iconic', 'fish', 'raw', 20, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish}', '{raw,ceviche,fresh,appetizer}', 82),
('FIL_LUMPIA_FRESH', 'lumpiang-sariwa', 'Lumpiang Sariwa', 'Lumpiang Sariwa', 'Fresh spring rolls with vegetables, heart of palm, and sweet peanut sauce in a soft crepe wrapper', 'snacks', 'nationwide', 'classic', 'vegetable', 'raw', 45, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": false, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,peanuts,eggs}', '{fresh,vegetables,peanut_sauce,healthy}', 82),
('FIL_NILAGA', 'nilaga', 'Nilaga', 'Nilagang Baka', 'Simple boiled beef soup with potatoes, cabbage, and corn, a nourishing everyday Filipino soup', 'soup', 'nationwide', 'classic', 'beef', 'boiled', 90, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{simple,everyday,nourishing,clear_broth}', 82),
('FIL_LAING', 'laing', 'Laing', 'Laing', 'Bicolano dish of dried taro leaves cooked in coconut milk with chilies and shrimp paste, rich and spicy', 'vegetables', 'bicol', 'iconic', 'vegetable', 'simmered', 60, 4, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish}', '{bicol,spicy,coconut,taro_leaves}', 82),
('FIL_MAJA_BLANCA', 'maja-blanca', 'Maja Blanca', 'Maja Blanca', 'Coconut pudding with sweet corn kernels, a creamy and subtly sweet Filipino dessert', 'desserts', 'nationwide', 'classic', 'none', 'simmered', 45, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy}', '{coconut,pudding,corn,party}', 80),
('FIL_TOKWA_BABOY', 'tokwat-baboy', 'Tokwa at Baboy', 'Tokwa\', 'Fried tofu and boiled pork ears served with a tangy soy-vinegar dipping sauce, a popular pulutan', 'snacks', 'nationwide', 'classic', 'pork', 'deep_fried', 45, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{soy}', '{pulutan,bar_snack,tofu,vinegar}', 80),
('FIL_TORTANG_TALONG', 'tortang-talong', 'Tortang Talong', 'Tortang Talong', 'Grilled eggplant omelette, a simple yet delicious vegetable dish often served with ground pork', 'vegetables', 'nationwide', 'classic', 'egg', 'pan_fried', 25, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{eggs}', '{eggplant,omelette,simple,everyday}', 80),
('FIL_CORNSILOG', 'cornsilog', 'Cornsilog', 'Cornsilog', 'Corned beef hash with garlic rice and fried egg, a quick and satisfying breakfast', 'breakfast', 'nationwide', 'classic', 'beef', 'pan_fried', 15, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{eggs}', '{silog,breakfast,corned_beef,quick}', 78),
('FIL_SAPIN_SAPIN', 'sapin-sapin', 'Sapin-Sapin', 'Sapin-Sapin', 'Colorful layered glutinous rice cake with three distinct flavors: ube, coconut, and jackfruit', 'desserts', 'nationwide', 'traditional', 'none', 'steamed', 90, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy}', '{layered,colorful,glutinous,festive}', 78),
('FIL_MECHADO', 'mechado', 'Mechado', 'Mechado', 'Braised beef in tomato sauce with soy sauce and calamansi, similar to a pot roast, a Spanish-influenced Filipino classic', 'meat', 'nationwide', 'classic', 'beef', 'braised', 90, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{soy}', '{braised,tomato,spanish_influenced,comfort_food}', 78),
('FIL_SOTANGHON_GUISADO', 'sotanghon-guisado', 'Sotanghon Guisado', 'Sotanghon Guisado', 'Stir-fried glass noodles with chicken and vegetables, lighter than other pancit varieties', 'noodles', 'nationwide', 'classic', 'chicken', 'stir_fried', 25, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{soy}', '{glass_noodles,light,chinese_influenced}', 78),
('FIL_JAVA_RICE', 'java-rice', 'Java Rice', 'Java Rice', 'Filipino-style fried rice tinted yellow with annatto and flavored with garlic, popular in fast-food chains', 'rice', 'nationwide', 'modern', 'none', 'stir_fried', 15, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{}', '{yellow_rice,annatto,fast_food,modern}', 78),
('FIL_GINATAANG_HIPON', 'ginataang-hipon', 'Ginataang Hipon', 'Ginataang Hipon', 'Shrimp cooked in rich coconut milk with squash, string beans, and chilies', 'seafood', 'bicol', 'classic', 'shrimp', 'simmered', 35, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish}', '{coconut,bicol,creamy,spicy}', 78),
('FIL_ISAW', 'isaw', 'Isaw', 'Isaw', 'Grilled chicken or pork intestines on a stick, a beloved Filipino street food staple', 'snacks', 'nationwide', 'classic', 'pork', 'grilled', 30, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{}', '{street_food,offal,grilled,skewer}', 78),
('FIL_MOLO_SOUP', 'pancit-molo', 'Pancit Molo', 'Pancit Molo', 'Filipino wonton soup from Iloilo with pork and shrimp dumplings in a flavorful chicken broth', 'soup', 'visayas', 'regional', 'pork', 'boiled', 60, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{gluten,shellfish}', '{iloilo,dumplings,chinese_influenced,festive}', 78),
('FIL_GINISANG_MONGGO', 'ginisang-monggo', 'Ginisang Monggo', 'Ginisang Monggo', 'Sauteed mung bean stew with pork, shrimp, and bitter melon leaves, a nutritious everyday dish', 'vegetables', 'nationwide', 'classic', 'pork', 'sauteed', 45, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{shellfish}', '{mung_beans,friday_dish,nutritious,everyday}', 78),
('FIL_DANGGIT', 'danggit-silog', 'Danggit Silog', 'Danggit Silog', 'Crispy dried rabbitfish with garlic rice and egg, a Cebuano breakfast specialty', 'breakfast', 'cebu', 'regional', 'fish', 'deep_fried', 15, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish,eggs}', '{silog,breakfast,cebu,dried_fish}', 75),
('FIL_BINAGOONGAN', 'binagoongan', 'Binagoongan', 'Binagoongang Baboy', 'Pork belly cooked with fermented shrimp paste (bagoong), tomatoes, and chilies, creating a savory and slightly funky dish', 'meat', 'nationwide', 'classic', 'pork', 'sauteed', 45, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{shellfish}', '{fermented,shrimp_paste,savory,pork_belly}', 75),
('FIL_PANCIT_LUCBAN', 'pancit-habhab', 'Pancit Habhab', 'Pancit Habhab', 'Lucban specialty of stir-fried noodles served on banana leaf, eaten without utensils by slurping', 'noodles', 'nationwide', 'regional', 'pork', 'stir_fried', 25, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{gluten,soy}', '{lucban,street_food,banana_leaf,unique}', 75),
('FIL_BRINGHE', 'bringhe', 'Bringhe', 'Bringhe', 'Filipino paella-style sticky rice with chicken, coconut milk, and turmeric, wrapped in banana leaves', 'rice', 'pampanga', 'traditional', 'chicken', 'steamed', 90, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{pampanga,festive,coconut,turmeric}', 75),
('FIL_PAKSIW_NA_ISDA', 'paksiw-na-isda', 'Paksiw na Isda', 'Paksiw na Isda', 'Fish stewed in vinegar with ginger, garlic, and bitter melon, a simple yet flavorful everyday dish', 'seafood', 'nationwide', 'classic', 'fish', 'braised', 30, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish}', '{vinegar,everyday,simple,sour}', 75),
('FIL_ENSALADANG_TALONG', 'ensaladang-talong', 'Ensaladang Talong', 'Ensaladang Talong', 'Grilled eggplant salad with tomatoes, onions, and a tangy vinegar dressing', 'vegetables', 'nationwide', 'classic', 'vegetable', 'grilled', 20, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{}', '{salad,grilled,healthy,side_dish}', 75),
('FIL_HUMBA', 'humba', 'Humba', 'Humba', 'Visayan braised pork belly with fermented black beans, banana blossoms, and brown sugar, sweeter than regular adobo', 'meat', 'visayas', 'regional', 'pork', 'braised', 90, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{soy}', '{visayan,sweet,braised,pork_belly}', 72),
('FIL_ADOBONG_PUSIT', 'adobong-pusit', 'Adobong Pusit', 'Adobong Pusit', 'Squid cooked adobo-style in its own ink with vinegar and soy sauce, creating a rich dark sauce', 'seafood', 'nationwide', 'classic', 'squid', 'braised', 35, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish,soy}', '{squid_ink,adobo,rich,savory}', 72);

-- =====================================================
-- VERIFICATION
-- =====================================================
SELECT 'Filipino dishes' AS status, COUNT(*) AS count FROM filipino;