-- ============================================
-- THAI DATA IMPORT
-- ============================================
-- Total: 69 Thai dishes
-- curries.ts: 8
-- stir-fries.ts: 9
-- soups.ts: 6
-- salads.ts: 7
-- noodles.ts: 6
-- rice-dishes.ts: 7
-- appetizers.ts: 7
-- grilled.ts: 6
-- seafood.ts: 7
-- desserts.ts: 6
-- ============================================

BEGIN;

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GREEN_CURRY_CHICKEN',
  'green-curry-chicken',
  'Green Curry with Chicken',
  'Aromatic Thai green curry with tender chicken, Thai eggplant, and bamboo shoots in rich coconut milk. The spiciest of Thai curries.',
  'Kaeng Khiao Wan Gai',
  'แกงเขียวหวานไก่',
  'curries',
  'signature',
  'central',
  'chicken',
  'simmered',
  'green',
  false,
  true,
  ARRAY['ING_CHICKEN_THIGH', 'ING_COCONUT_MILK', 'ING_GREEN_CURRY_PASTE', 'ING_THAI_EGGPLANT', 'ING_BAMBOO_SHOOTS', 'ING_THAI_BASIL', 'ING_KAFFIR_LIME_LEAVES', 'ING_PALM_SUGAR', 'ING_FISH_SAUCE', 'ING_GREEN_CHILI', 'ING_COCONUT_CREAM'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  420,
  28,
  12,
  30,
  4,
  ARRAY['iconic', 'spicy', 'coconut', 'bangkok-style'],
  95
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_RED_CURRY_DUCK',
  'red-curry-duck',
  'Red Curry with Duck',
  'Rich red curry with tender roasted duck, pineapple, cherry tomatoes, and Thai basil. A balance of sweet, savory, and spicy.',
  'Kaeng Phet Ped Yang',
  'แกงเผ็ดเป็ดย่าง',
  'curries',
  'signature',
  'central',
  'duck',
  'simmered',
  'red',
  false,
  true,
  ARRAY['ING_DUCK_BREAST', 'ING_COCONUT_MILK', 'ING_RED_CURRY_PASTE', 'ING_PINEAPPLE', 'ING_CHERRY_TOMATO', 'ING_THAI_BASIL', 'ING_KAFFIR_LIME_LEAVES', 'ING_PALM_SUGAR', 'ING_FISH_SAUCE', 'ING_COCONUT_CREAM'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  480,
  32,
  18,
  32,
  3,
  ARRAY['roasted-duck', 'tropical', 'sweet-savory'],
  88
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_MASSAMAN_CURRY',
  'massaman-curry-beef',
  'Massaman Curry with Beef',
  'Mild, rich curry with tender beef, potatoes, and peanuts in a fragrant coconut sauce. Indian and Malay influenced.',
  'Kaeng Massaman Neua',
  'แกงมัสมั่นเนื้อ',
  'curries',
  'popular',
  'southern',
  'beef',
  'simmered',
  'massaman',
  false,
  true,
  ARRAY['ING_BEEF_CHUCK', 'ING_COCONUT_MILK', 'ING_MASSAMAN_CURRY_PASTE', 'ING_POTATO', 'ING_ONION', 'ING_PEANUTS', 'ING_TAMARIND', 'ING_PALM_SUGAR', 'ING_FISH_SAUCE', 'ING_CINNAMON', 'ING_CARDAMOM', 'ING_BAY_LEAF'],
  ARRAY['fish', 'peanuts'],
  true,
  true,
  false,
  false,
  false,
  true,
  false,
  520,
  35,
  28,
  32,
  2,
  ARRAY['mild', 'peanuts', 'indian-influence', 'comfort-food'],
  92
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PANANG_CURRY',
  'panang-curry-pork',
  'Panang Curry with Pork',
  'Thick, creamy curry with sliced pork in a rich, nutty sauce. Less soupy than other Thai curries, with complex peanut notes.',
  'Panang Moo',
  'พะแนงหมู',
  'curries',
  'popular',
  'central',
  'pork',
  'simmered',
  'panang',
  false,
  true,
  ARRAY['ING_PORK_LOIN', 'ING_COCONUT_MILK', 'ING_PANANG_CURRY_PASTE', 'ING_PEANUTS', 'ING_KAFFIR_LIME_LEAVES', 'ING_THAI_BASIL', 'ING_PALM_SUGAR', 'ING_FISH_SAUCE', 'ING_COCONUT_CREAM', 'ING_RED_CHILI'],
  ARRAY['fish', 'peanuts'],
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  450,
  30,
  14,
  32,
  3,
  ARRAY['thick', 'creamy', 'peanut', 'rich'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_YELLOW_CURRY',
  'yellow-curry-chicken',
  'Yellow Curry with Chicken',
  'Mild, turmeric-based curry with chicken and potatoes. The mildest Thai curry, perfect for those new to Thai cuisine.',
  'Kaeng Kari Gai',
  'แกงกะหรี่ไก่',
  'curries',
  'popular',
  'central',
  'chicken',
  'simmered',
  'yellow',
  false,
  true,
  ARRAY['ING_CHICKEN_THIGH', 'ING_COCONUT_MILK', 'ING_YELLOW_CURRY_PASTE', 'ING_POTATO', 'ING_ONION', 'ING_TURMERIC', 'ING_PALM_SUGAR', 'ING_FISH_SAUCE', 'ING_COCONUT_CREAM', 'ING_CURRY_POWDER'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  400,
  26,
  22,
  24,
  1,
  ARRAY['mild', 'beginner-friendly', 'comfort-food'],
  82
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_JUNGLE_CURRY',
  'jungle-curry-pork',
  'Jungle Curry with Pork',
  'Fiery Northern Thai curry without coconut milk. Packed with herbs, vegetables, and intense heat. Traditional forest-style cooking.',
  'Kaeng Pa',
  'แกงป่า',
  'curries',
  'classic',
  'northern',
  'pork',
  'simmered',
  'jungle',
  false,
  false,
  ARRAY['ING_PORK_BELLY', 'ING_GREEN_CURRY_PASTE', 'ING_GREEN_PEPPERCORNS', 'ING_BAMBOO_SHOOTS', 'ING_THAI_EGGPLANT', 'ING_WILD_GINGER', 'ING_HOLY_BASIL', 'ING_FISH_SAUCE', 'ING_KRACHAI', 'ING_LONG_BEANS', 'ING_BIRD_EYE_CHILI'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  320,
  28,
  8,
  20,
  5,
  ARRAY['no-coconut', 'very-spicy', 'northern', 'rustic'],
  72
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KHAO_SOI',
  'khao-soi',
  'Khao Soi',
  'Northern Thai coconut curry noodle soup with egg noodles, topped with crispy noodles. Burmese-influenced comfort food from Chiang Mai.',
  'Khao Soi',
  'ข้าวซอย',
  'curries',
  'signature',
  'northern',
  'chicken',
  'simmered',
  'red',
  true,
  true,
  ARRAY['ING_CHICKEN_LEG', 'ING_COCONUT_MILK', 'ING_KHAO_SOI_PASTE', 'ING_EGG_NOODLES', 'ING_SHALLOTS', 'ING_PICKLED_MUSTARD_GREENS', 'ING_LIME', 'ING_CILANTRO', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_CRISPY_NOODLES'],
  ARRAY['fish', 'gluten', 'eggs'],
  false,
  true,
  true,
  false,
  false,
  true,
  false,
  580,
  32,
  48,
  28,
  2,
  ARRAY['chiang-mai', 'noodle-soup', 'burmese-influence', 'comfort-food'],
  90
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GREEN_CURRY_SHRIMP',
  'green-curry-shrimp',
  'Green Curry with Shrimp',
  'Classic green curry with succulent prawns, Thai eggplant, and fresh basil in creamy coconut milk.',
  'Kaeng Khiao Wan Goong',
  'แกงเขียวหวานกุ้ง',
  'curries',
  'popular',
  'central',
  'shrimp',
  'simmered',
  'green',
  false,
  true,
  ARRAY['ING_SHRIMP', 'ING_COCONUT_MILK', 'ING_GREEN_CURRY_PASTE', 'ING_THAI_EGGPLANT', 'ING_BAMBOO_SHOOTS', 'ING_THAI_BASIL', 'ING_KAFFIR_LIME_LEAVES', 'ING_PALM_SUGAR', 'ING_FISH_SAUCE', 'ING_GREEN_CHILI', 'ING_COCONUT_CREAM'],
  ARRAY['fish', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  380,
  26,
  12,
  26,
  4,
  ARRAY['seafood', 'spicy', 'coconut'],
  86
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PAD_THAI',
  'pad-thai',
  'Pad Thai',
  'Thailand\''s most famous stir-fried noodle dish with rice noodles, eggs, tofu, tamarind sauce, and crushed peanuts. Iconic street food.',
  'Pad Thai',
  'ผัดไทย',
  'stir_fries',
  'signature',
  'central',
  'shrimp',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_RICE_NOODLES', 'ING_SHRIMP', 'ING_EGGS', 'ING_TOFU', 'ING_TAMARIND', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_PEANUTS', 'ING_BEAN_SPROUTS', 'ING_GARLIC_CHIVES', 'ING_DRIED_SHRIMP', 'ING_LIME', 'ING_GARLIC'],
  ARRAY['eggs', 'shellfish', 'fish', 'peanuts', 'soy'],
  true,
  true,
  false,
  false,
  false,
  true,
  true,
  450,
  22,
  52,
  18,
  1,
  ARRAY['iconic', 'street-food', 'noodles', 'globally-famous'],
  98
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PAD_SEE_EW',
  'pad-see-ew',
  'Pad See Ew',
  'Wide rice noodles stir-fried with Chinese broccoli, egg, and sweet soy sauce. Smoky wok flavor from high heat cooking.',
  'Pad Si Ew',
  'ผัดซีอิ๊ว',
  'stir_fries',
  'popular',
  'central',
  'chicken',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_WIDE_RICE_NOODLES', 'ING_CHICKEN_BREAST', 'ING_CHINESE_BROCCOLI', 'ING_EGGS', 'ING_DARK_SOY_SAUCE', 'ING_LIGHT_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_GARLIC', 'ING_WHITE_PEPPER', 'ING_VEGETABLE_OIL'],
  ARRAY['eggs', 'soy', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  480,
  26,
  56,
  16,
  0,
  ARRAY['smoky', 'wok-hei', 'comfort-food', 'chinese-influenced'],
  88
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PAD_KRA_PAO',
  'pad-kra-pao',
  'Pad Kra Pao',
  'Stir-fried minced meat with holy basil, chilies, and garlic. Thailand\''s most popular everyday dish, often served with fried egg.',
  'Pad Kra Pao',
  'ผัดกะเพรา',
  'stir_fries',
  'signature',
  'central',
  'pork',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_PORK_GROUND', 'ING_HOLY_BASIL', 'ING_BIRD_EYE_CHILI', 'ING_GARLIC', 'ING_OYSTER_SAUCE', 'ING_FISH_SAUCE', 'ING_DARK_SOY_SAUCE', 'ING_PALM_SUGAR', 'ING_VEGETABLE_OIL', 'ING_LONG_BEANS', 'ING_EGGS'],
  ARRAY['fish', 'soy', 'shellfish', 'eggs'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  420,
  28,
  18,
  28,
  4,
  ARRAY['everyday-thai', 'holy-basil', 'spicy', 'quick'],
  94
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PAD_PRIK_KING',
  'pad-prik-king',
  'Pad Prik King',
  'Dry red curry stir-fry with green beans and kaffir lime leaves. No coconut milk, intensely flavored with curry paste.',
  'Pad Prik King',
  'ผัดพริกขิง',
  'stir_fries',
  'classic',
  'central',
  'pork',
  'stir_fried',
  'none',
  false,
  false,
  ARRAY['ING_PORK_LOIN', 'ING_RED_CURRY_PASTE', 'ING_LONG_BEANS', 'ING_KAFFIR_LIME_LEAVES', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_VEGETABLE_OIL', 'ING_GARLIC'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  350,
  26,
  12,
  22,
  3,
  ARRAY['dry-curry', 'green-beans', 'no-coconut'],
  78
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PAD_PAK',
  'pad-pak-ruam',
  'Pad Pak Ruam',
  'Stir-fried mixed vegetables in oyster sauce. A simple, healthy dish showcasing fresh seasonal vegetables.',
  'Pad Pak Ruam',
  'ผัดผักรวม',
  'stir_fries',
  'classic',
  'central',
  'vegetables',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_CHINESE_BROCCOLI', 'ING_BOK_CHOY', 'ING_BABY_CORN', 'ING_MUSHROOMS', 'ING_CARROTS', 'ING_OYSTER_SAUCE', 'ING_GARLIC', 'ING_LIGHT_SOY_SAUCE', 'ING_VEGETABLE_OIL'],
  ARRAY['soy', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  180,
  6,
  18,
  10,
  0,
  ARRAY['vegetable', 'healthy', 'simple'],
  72
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PAD_CASHEW',
  'pad-med-mamuang',
  'Pad Med Mamuang',
  'Stir-fried chicken with roasted cashews, dried chilies, and onions. Sweet and savory with satisfying crunch.',
  'Gai Pad Med Mamuang',
  'ไก่ผัดเม็ดมะม่วงหิมพานต์',
  'stir_fries',
  'popular',
  'central',
  'chicken',
  'stir_fried',
  'none',
  false,
  false,
  ARRAY['ING_CHICKEN_BREAST', 'ING_CASHEWS', 'ING_DRIED_CHILIES', 'ING_ONION', 'ING_BELL_PEPPER', 'ING_OYSTER_SAUCE', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_LIGHT_SOY_SAUCE', 'ING_GARLIC', 'ING_SPRING_ONION'],
  ARRAY['tree_nuts', 'soy', 'fish', 'shellfish'],
  true,
  true,
  false,
  false,
  false,
  true,
  false,
  420,
  28,
  22,
  26,
  2,
  ARRAY['cashew-nut', 'sweet-savory', 'crunchy'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PAD_GINGER',
  'pad-khing',
  'Pad Khing',
  'Stir-fried meat with fresh ginger, wood ear mushrooms, and vegetables. Aromatic and warming with intense ginger flavor.',
  'Pad Khing',
  'ผัดขิง',
  'stir_fries',
  'classic',
  'central',
  'chicken',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_CHICKEN_BREAST', 'ING_GINGER', 'ING_WOOD_EAR_MUSHROOMS', 'ING_ONION', 'ING_BELL_PEPPER', 'ING_OYSTER_SAUCE', 'ING_LIGHT_SOY_SAUCE', 'ING_GARLIC', 'ING_SPRING_ONION', 'ING_VEGETABLE_OIL'],
  ARRAY['soy', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  320,
  26,
  14,
  18,
  1,
  ARRAY['ginger', 'warming', 'aromatic'],
  74
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PAD_THAI_GOONG_SOD',
  'pad-thai-goong-sod',
  'Pad Thai with Fresh Prawns',
  'Premium version of Pad Thai with large fresh river prawns. A step up from the classic with succulent whole prawns.',
  'Pad Thai Goong Sod',
  'ผัดไทยกุ้งสด',
  'stir_fries',
  'premium',
  'central',
  'shrimp',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_RICE_NOODLES', 'ING_RIVER_PRAWNS', 'ING_EGGS', 'ING_TOFU', 'ING_TAMARIND', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_PEANUTS', 'ING_BEAN_SPROUTS', 'ING_GARLIC_CHIVES', 'ING_DRIED_SHRIMP', 'ING_LIME', 'ING_GARLIC'],
  ARRAY['eggs', 'shellfish', 'fish', 'peanuts', 'soy'],
  true,
  true,
  false,
  false,
  false,
  true,
  true,
  520,
  32,
  52,
  20,
  1,
  ARRAY['premium', 'river-prawns', 'noodles'],
  82
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PAD_WOON_SEN',
  'pad-woon-sen',
  'Pad Woon Sen',
  'Stir-fried glass noodles with vegetables, eggs, and meat. Light and silky texture with savory seasoning.',
  'Pad Woon Sen',
  'ผัดวุ้นเส้น',
  'stir_fries',
  'classic',
  'central',
  'mixed',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_GLASS_NOODLES', 'ING_CHICKEN_BREAST', 'ING_SHRIMP', 'ING_EGGS', 'ING_CABBAGE', 'ING_CARROTS', 'ING_CELERY', 'ING_TOMATO', 'ING_OYSTER_SAUCE', 'ING_LIGHT_SOY_SAUCE', 'ING_GARLIC', 'ING_WHITE_PEPPER'],
  ARRAY['eggs', 'shellfish', 'soy'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  380,
  22,
  42,
  14,
  0,
  ARRAY['glass-noodles', 'light', 'silky'],
  76
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_TOM_YUM_GOONG',
  'tom-yum-goong',
  'Tom Yum Goong',
  'Thailand\''s most famous soup with prawns in hot and sour broth. Aromatic with lemongrass, galangal, kaffir lime, and chilies.',
  'Tom Yum Goong',
  'ต้มยำกุ้ง',
  'soups',
  'signature',
  'central',
  'shrimp',
  'boiled',
  'none',
  false,
  false,
  ARRAY['ING_SHRIMP', 'ING_LEMONGRASS', 'ING_GALANGAL', 'ING_KAFFIR_LIME_LEAVES', 'ING_BIRD_EYE_CHILI', 'ING_STRAW_MUSHROOMS', 'ING_LIME_JUICE', 'ING_FISH_SAUCE', 'ING_ROASTED_CHILI_PASTE', 'ING_CILANTRO', 'ING_SHALLOTS'],
  ARRAY['shellfish', 'fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  180,
  22,
  8,
  6,
  4,
  ARRAY['iconic', 'hot-sour', 'aromatic', 'globally-famous'],
  96
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_TOM_KHA_GAI',
  'tom-kha-gai',
  'Tom Kha Gai',
  'Creamy coconut soup with chicken, galangal, and lemongrass. The gentler, richer cousin of Tom Yum with sublime coconut flavor.',
  'Tom Kha Gai',
  'ต้มข่าไก่',
  'soups',
  'signature',
  'central',
  'chicken',
  'boiled',
  'none',
  false,
  true,
  ARRAY['ING_CHICKEN_BREAST', 'ING_COCONUT_MILK', 'ING_GALANGAL', 'ING_LEMONGRASS', 'ING_KAFFIR_LIME_LEAVES', 'ING_STRAW_MUSHROOMS', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_BIRD_EYE_CHILI', 'ING_PALM_SUGAR', 'ING_CILANTRO'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  320,
  24,
  10,
  22,
  2,
  ARRAY['creamy', 'coconut', 'aromatic', 'comfort-food'],
  92
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_TOM_YUM_NAM_KHON',
  'tom-yum-nam-khon',
  'Tom Yum Nam Khon',
  'Creamy version of Tom Yum with evaporated milk. Rich, spicy, and tangy with a beautiful orange-red color.',
  'Tom Yum Nam Khon',
  'ต้มยำน้ำข้น',
  'soups',
  'popular',
  'central',
  'shrimp',
  'boiled',
  'none',
  false,
  false,
  ARRAY['ING_SHRIMP', 'ING_EVAPORATED_MILK', 'ING_LEMONGRASS', 'ING_GALANGAL', 'ING_KAFFIR_LIME_LEAVES', 'ING_ROASTED_CHILI_PASTE', 'ING_STRAW_MUSHROOMS', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_BIRD_EYE_CHILI', 'ING_CILANTRO'],
  ARRAY['shellfish', 'fish', 'milk'],
  true,
  false,
  true,
  false,
  false,
  true,
  true,
  250,
  22,
  12,
  12,
  4,
  ARRAY['creamy', 'hot-sour', 'rich'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GAENG_JUED',
  'gaeng-jued',
  'Gaeng Jued',
  'Clear Thai soup with tofu, vegetables, and glass noodles. Mild and comforting, perfect for balancing spicy dishes.',
  'Gaeng Jued',
  'แกงจืด',
  'soups',
  'classic',
  'central',
  'tofu',
  'boiled',
  'none',
  false,
  false,
  ARRAY['ING_TOFU', 'ING_GLASS_NOODLES', 'ING_NAPA_CABBAGE', 'ING_PORK_GROUND', 'ING_GARLIC', 'ING_CILANTRO', 'ING_WHITE_PEPPER', 'ING_LIGHT_SOY_SAUCE', 'ING_CHICKEN_STOCK'],
  ARRAY['soy'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  150,
  12,
  14,
  6,
  0,
  ARRAY['mild', 'clear-soup', 'comfort-food'],
  70
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_TOM_SAP',
  'tom-sap',
  'Tom Sap',
  'Northeastern Thai sour soup with pork ribs and vegetables. Similar to Tom Yum but with Isan flavors and herbs.',
  'Tom Sap',
  'ต้มแซ่บ',
  'soups',
  'classic',
  'northeastern',
  'pork',
  'boiled',
  'none',
  true,
  false,
  ARRAY['ING_PORK_RIBS', 'ING_LEMONGRASS', 'ING_GALANGAL', 'ING_KAFFIR_LIME_LEAVES', 'ING_SAWTOOTH_CORIANDER', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_ROASTED_RICE_POWDER', 'ING_DRIED_CHILI', 'ING_SHALLOTS', 'ING_SPRING_ONION'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  220,
  18,
  8,
  14,
  4,
  ARRAY['isan', 'sour', 'pork-ribs'],
  75
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PO_TAEK',
  'po-taek',
  'Po Taek',
  'Spicy Thai seafood soup with mixed shellfish and fish. A fisherman\''s soup with bold, briny flavors.',
  'Po Taek',
  'โป๊ะแตก',
  'soups',
  'classic',
  'central',
  'mixed_seafood',
  'boiled',
  'none',
  false,
  false,
  ARRAY['ING_SHRIMP', 'ING_MUSSELS', 'ING_SQUID', 'ING_FISH_WHITE', 'ING_CRAB', 'ING_LEMONGRASS', 'ING_GALANGAL', 'ING_KAFFIR_LIME_LEAVES', 'ING_THAI_BASIL', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_BIRD_EYE_CHILI'],
  ARRAY['shellfish', 'fish', 'mollusks'],
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  200,
  28,
  6,
  6,
  4,
  ARRAY['seafood', 'fisherman-style', 'spicy'],
  78
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_SOM_TAM',
  'som-tam',
  'Som Tam',
  'Iconic green papaya salad from Northeastern Thailand. Pounded in mortar with chilies, lime, fish sauce, and peanuts. Addictively spicy-sour.',
  'Som Tam',
  'ส้มตำ',
  'salads',
  'signature',
  'northeastern',
  'vegetables',
  'raw',
  'none',
  true,
  false,
  ARRAY['ING_GREEN_PAPAYA', 'ING_TOMATO', 'ING_LONG_BEANS', 'ING_BIRD_EYE_CHILI', 'ING_GARLIC', 'ING_PEANUTS', 'ING_DRIED_SHRIMP', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_PALM_SUGAR'],
  ARRAY['fish', 'shellfish', 'peanuts'],
  true,
  true,
  false,
  false,
  false,
  true,
  true,
  180,
  8,
  22,
  8,
  4,
  ARRAY['iconic', 'isan', 'street-food', 'spicy-sour'],
  95
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_YUM_WOON_SEN',
  'yum-woon-sen',
  'Yum Woon Sen',
  'Glass noodle salad with minced pork, shrimp, and vegetables. Tangy, spicy dressing with fresh herbs.',
  'Yum Woon Sen',
  'ยำวุ้นเส้น',
  'salads',
  'popular',
  'central',
  'mixed',
  'raw',
  'none',
  true,
  false,
  ARRAY['ING_GLASS_NOODLES', 'ING_PORK_GROUND', 'ING_SHRIMP', 'ING_CELERY', 'ING_ONION', 'ING_TOMATO', 'ING_CILANTRO', 'ING_BIRD_EYE_CHILI', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_PALM_SUGAR', 'ING_ROASTED_CHILI_POWDER'],
  ARRAY['shellfish', 'fish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  280,
  18,
  32,
  10,
  3,
  ARRAY['glass-noodles', 'tangy', 'mixed-protein'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_LARB_MOO',
  'larb-moo',
  'Larb Moo',
  'Northeastern Thai minced pork salad with roasted rice powder, fresh herbs, and fiery dressing. The quintessential Isan dish.',
  'Larb Moo',
  'ลาบหมู',
  'salads',
  'signature',
  'northeastern',
  'pork',
  'raw',
  'none',
  true,
  false,
  ARRAY['ING_PORK_GROUND', 'ING_ROASTED_RICE_POWDER', 'ING_SHALLOTS', 'ING_MINT', 'ING_CILANTRO', 'ING_SAWTOOTH_CORIANDER', 'ING_SPRING_ONION', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_DRIED_CHILI', 'ING_ROASTED_CHILI_POWDER'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  250,
  24,
  8,
  14,
  4,
  ARRAY['isan', 'minced-meat', 'roasted-rice', 'herby'],
  90
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_LARB_GAI',
  'larb-gai',
  'Larb Gai',
  'Minced chicken salad with roasted rice powder and fresh herbs. Lighter than pork version but equally flavorful.',
  'Larb Gai',
  'ลาบไก่',
  'salads',
  'popular',
  'northeastern',
  'chicken',
  'raw',
  'none',
  true,
  false,
  ARRAY['ING_CHICKEN_GROUND', 'ING_ROASTED_RICE_POWDER', 'ING_SHALLOTS', 'ING_MINT', 'ING_CILANTRO', 'ING_SAWTOOTH_CORIANDER', 'ING_SPRING_ONION', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_DRIED_CHILI', 'ING_ROASTED_CHILI_POWDER'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  220,
  26,
  8,
  10,
  4,
  ARRAY['isan', 'chicken', 'light', 'herby'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_YUM_NEUA',
  'yum-neua',
  'Yum Neua',
  'Thai beef salad with grilled beef, fresh vegetables, and spicy lime dressing. Smoky, tangy, and refreshing.',
  'Yum Neua',
  'ยำเนื้อ',
  'salads',
  'popular',
  'central',
  'beef',
  'grilled',
  'none',
  false,
  false,
  ARRAY['ING_BEEF_SIRLOIN', 'ING_TOMATO', 'ING_ONION', 'ING_CUCUMBER', 'ING_CELERY', 'ING_CILANTRO', 'ING_MINT', 'ING_BIRD_EYE_CHILI', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_ROASTED_CHILI_POWDER'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  280,
  30,
  10,
  14,
  3,
  ARRAY['grilled-beef', 'tangy', 'refreshing'],
  82
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_YUM_PLA_DOOK_FOO',
  'yum-pla-dook-foo',
  'Yum Pla Dook Foo',
  'Crispy catfish salad with green mango. Deep-fried fluffed catfish served with spicy mango salad. Unique texture.',
  'Yum Pla Dook Foo',
  'ยำปลาดุกฟู',
  'salads',
  'signature',
  'central',
  'fish',
  'deep_fried',
  'none',
  false,
  false,
  ARRAY['ING_CATFISH', 'ING_GREEN_MANGO', 'ING_CASHEWS', 'ING_SHALLOTS', 'ING_BIRD_EYE_CHILI', 'ING_CILANTRO', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_PALM_SUGAR', 'ING_DRIED_SHRIMP'],
  ARRAY['fish', 'shellfish', 'tree_nuts'],
  true,
  true,
  false,
  false,
  false,
  true,
  true,
  380,
  24,
  22,
  24,
  3,
  ARRAY['crispy', 'catfish', 'mango', 'unique'],
  80
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_NAM_TOK',
  'nam-tok-moo',
  'Nam Tok Moo',
  'Waterfall pork salad with grilled pork, roasted rice powder, and fresh herbs. Named for the meat juices that drip like waterfalls.',
  'Nam Tok Moo',
  'น้ำตกหมู',
  'salads',
  'classic',
  'northeastern',
  'pork',
  'grilled',
  'none',
  true,
  false,
  ARRAY['ING_PORK_NECK', 'ING_ROASTED_RICE_POWDER', 'ING_SHALLOTS', 'ING_MINT', 'ING_CILANTRO', 'ING_SAWTOOTH_CORIANDER', 'ING_SPRING_ONION', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_DRIED_CHILI', 'ING_ROASTED_CHILI_POWDER'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  320,
  28,
  8,
  20,
  4,
  ARRAY['isan', 'grilled', 'herby', 'smoky'],
  84
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GUAY_TEOW_REUA',
  'boat-noodles',
  'Boat Noodles',
  'Thai boat noodles with rich, dark broth traditionally thickened with pig or beef blood. Intense, complex flavor served in small portions.',
  'Guay Teow Reua',
  'ก๋วยเตี๋ยวเรือ',
  'noodles',
  'signature',
  'central',
  'beef',
  'boiled',
  'none',
  true,
  false,
  ARRAY['ING_RICE_NOODLES', 'ING_BEEF_SLICES', 'ING_BEEF_MEATBALLS', 'ING_BEEF_LIVER', 'ING_MORNING_GLORY', 'ING_BEAN_SPROUTS', 'ING_CINNAMON', 'ING_STAR_ANISE', 'ING_DARK_SOY_SAUCE', 'ING_FISH_SAUCE', 'ING_FRIED_GARLIC'],
  ARRAY['fish', 'soy'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  350,
  22,
  38,
  12,
  2,
  ARRAY['boat-noodles', 'rich-broth', 'street-food', 'intense'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GUAY_TEOW_TOM_YUM',
  'tom-yum-noodles',
  'Tom Yum Noodle Soup',
  'Noodle soup with Tom Yum broth, featuring the classic hot and sour flavors with rice noodles and your choice of protein.',
  'Guay Teow Tom Yum',
  'ก๋วยเตี๋ยวต้มยำ',
  'noodles',
  'popular',
  'central',
  'pork',
  'boiled',
  'none',
  true,
  false,
  ARRAY['ING_RICE_NOODLES', 'ING_PORK_SLICES', 'ING_PORK_MEATBALLS', 'ING_BEAN_SPROUTS', 'ING_MORNING_GLORY', 'ING_ROASTED_CHILI_PASTE', 'ING_FISH_SAUCE', 'ING_LIME_JUICE', 'ING_PALM_SUGAR', 'ING_PEANUTS', 'ING_FRIED_GARLIC'],
  ARRAY['fish', 'peanuts'],
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  380,
  20,
  42,
  14,
  3,
  ARRAY['tom-yum', 'noodle-soup', 'hot-sour'],
  82
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KUAY_CHAP',
  'kuay-chap',
  'Kuay Chap',
  'Rolled rice noodle soup with pork offal in five-spice broth. Chinese-Thai comfort food with soft boiled eggs and tofu.',
  'Kuay Chap',
  'ก๋วยจั๊บ',
  'noodles',
  'classic',
  'central',
  'pork',
  'boiled',
  'none',
  true,
  false,
  ARRAY['ING_ROLLED_RICE_NOODLES', 'ING_PORK_BELLY', 'ING_PORK_INTESTINES', 'ING_PORK_LIVER', 'ING_EGGS', 'ING_TOFU', 'ING_FIVE_SPICE', 'ING_DARK_SOY_SAUCE', 'ING_CILANTRO', 'ING_WHITE_PEPPER', 'ING_FRIED_GARLIC'],
  ARRAY['soy', 'eggs'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  450,
  28,
  32,
  24,
  1,
  ARRAY['five-spice', 'offal', 'chinese-thai', 'comfort-food'],
  75
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_RAD_NA',
  'rad-na',
  'Rad Na',
  'Wide rice noodles smothered in thick gravy with Chinese broccoli and your choice of meat. Comforting and satisfying.',
  'Rad Na',
  'ราดหน้า',
  'noodles',
  'popular',
  'central',
  'pork',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_WIDE_RICE_NOODLES', 'ING_PORK_LOIN', 'ING_CHINESE_BROCCOLI', 'ING_EGGS', 'ING_DARK_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_TAPIOCA_STARCH', 'ING_GARLIC', 'ING_WHITE_PEPPER', 'ING_VEGETABLE_OIL', 'ING_CHICKEN_STOCK'],
  ARRAY['soy', 'eggs', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  520,
  24,
  58,
  20,
  0,
  ARRAY['gravy', 'comfort-food', 'chinese-thai'],
  80
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GUAY_TEOW_HAENG',
  'dry-noodles',
  'Guay Teow Haeng',
  'Dry-style Thai noodles without broth, served with minced meat, seasonings, and condiments on the side.',
  'Guay Teow Haeng',
  'ก๋วยเตี๋ยวแห้ง',
  'noodles',
  'classic',
  'central',
  'pork',
  'boiled',
  'none',
  true,
  false,
  ARRAY['ING_RICE_NOODLES', 'ING_PORK_SLICES', 'ING_PORK_MEATBALLS', 'ING_BEAN_SPROUTS', 'ING_MORNING_GLORY', 'ING_LIGHT_SOY_SAUCE', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_WHITE_PEPPER', 'ING_FRIED_GARLIC', 'ING_CILANTRO'],
  ARRAY['fish', 'soy'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  340,
  18,
  40,
  12,
  1,
  ARRAY['dry-style', 'simple', 'street-food'],
  74
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_BA_MEE_HAENG',
  'egg-noodles-dry',
  'Ba Mee Haeng',
  'Dry egg noodles with roasted pork, wonton, and vegetables. Chinese-influenced dish popular in Bangkok.',
  'Ba Mee Haeng',
  'บะหมี่แห้ง',
  'noodles',
  'popular',
  'central',
  'pork',
  'boiled',
  'none',
  true,
  false,
  ARRAY['ING_EGG_NOODLES', 'ING_CHAR_SIU', 'ING_WONTONS', 'ING_CHINESE_BROCCOLI', 'ING_BEAN_SPROUTS', 'ING_LIGHT_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_FISH_SAUCE', 'ING_WHITE_PEPPER', 'ING_FRIED_GARLIC', 'ING_SPRING_ONION'],
  ARRAY['gluten', 'eggs', 'soy', 'fish', 'shellfish'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  420,
  22,
  48,
  16,
  0,
  ARRAY['egg-noodles', 'char-siu', 'chinese-thai'],
  78
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KHAO_PAD',
  'khao-pad',
  'Khao Pad',
  'Classic Thai fried rice with egg, vegetables, and your choice of meat. Simple, satisfying, and endlessly customizable.',
  'Khao Pad',
  'ข้าวผัด',
  'rice_dishes',
  'popular',
  'central',
  'chicken',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_JASMINE_RICE', 'ING_CHICKEN_BREAST', 'ING_EGGS', 'ING_ONION', 'ING_TOMATO', 'ING_CUCUMBER', 'ING_SPRING_ONION', 'ING_GARLIC', 'ING_FISH_SAUCE', 'ING_LIGHT_SOY_SAUCE', 'ING_WHITE_PEPPER', 'ING_LIME'],
  ARRAY['eggs', 'fish', 'soy'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  450,
  22,
  58,
  14,
  0,
  ARRAY['fried-rice', 'simple', 'everyday'],
  88
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KHAO_MAN_GAI',
  'khao-man-gai',
  'Khao Man Gai',
  'Thai-style Hainanese chicken rice with poached chicken and aromatic rice cooked in chicken stock. Served with special soybean sauce.',
  'Khao Man Gai',
  'ข้าวมันไก่',
  'rice_dishes',
  'signature',
  'central',
  'chicken',
  'boiled',
  'none',
  true,
  false,
  ARRAY['ING_CHICKEN_WHOLE', 'ING_JASMINE_RICE', 'ING_GARLIC', 'ING_GINGER', 'ING_CHICKEN_FAT', 'ING_CUCUMBER', 'ING_CILANTRO', 'ING_SOYBEAN_PASTE', 'ING_GINGER_SAUCE', 'ING_CHICKEN_STOCK', 'ING_SPRING_ONION'],
  ARRAY['soy'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  520,
  32,
  54,
  18,
  0,
  ARRAY['hainanese', 'comfort-food', 'chicken-rice'],
  90
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KHAO_MOO_DAENG',
  'khao-moo-daeng',
  'Khao Moo Daeng',
  'Red BBQ pork over rice with sweet gravy. Chinese-Thai classic with char siu pork, hard-boiled egg, and Chinese sausage.',
  'Khao Moo Daeng',
  'ข้าวหมูแดง',
  'rice_dishes',
  'popular',
  'central',
  'pork',
  'roasted',
  'none',
  true,
  false,
  ARRAY['ING_JASMINE_RICE', 'ING_CHAR_SIU', 'ING_CRISPY_PORK', 'ING_CHINESE_SAUSAGE', 'ING_EGGS', 'ING_CUCUMBER', 'ING_RED_SAUCE', 'ING_FIVE_SPICE', 'ING_SOY_SAUCE', 'ING_MORNING_GLORY'],
  ARRAY['eggs', 'soy'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  580,
  28,
  62,
  24,
  0,
  ARRAY['bbq-pork', 'chinese-thai', 'sweet-savory'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KHAO_KA_MOO',
  'khao-ka-moo',
  'Khao Ka Moo',
  'Stewed pork leg over rice with pickled mustard greens. Melt-in-mouth tender pork braised in five-spice and soy.',
  'Khao Kha Moo',
  'ข้าวขาหมู',
  'rice_dishes',
  'signature',
  'central',
  'pork',
  'simmered',
  'none',
  true,
  false,
  ARRAY['ING_JASMINE_RICE', 'ING_PORK_LEG', 'ING_FIVE_SPICE', 'ING_DARK_SOY_SAUCE', 'ING_GARLIC', 'ING_CILANTRO', 'ING_PICKLED_MUSTARD_GREENS', 'ING_EGGS', 'ING_CHILI_VINEGAR', 'ING_PALM_SUGAR'],
  ARRAY['soy', 'eggs'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  620,
  38,
  58,
  28,
  1,
  ARRAY['braised-pork', 'comfort-food', 'street-food'],
  88
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KHAO_PAD_KRAPAO',
  'khao-pad-krapao',
  'Khao Pad Kra Pao',
  'Holy basil stir-fry served over rice with fried egg on top. Thailand\''s most beloved lunch dish.',
  'Khao Pad Kra Pao',
  'ข้าวผัดกะเพรา',
  'rice_dishes',
  'signature',
  'central',
  'pork',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_JASMINE_RICE', 'ING_PORK_GROUND', 'ING_HOLY_BASIL', 'ING_BIRD_EYE_CHILI', 'ING_GARLIC', 'ING_EGGS', 'ING_OYSTER_SAUCE', 'ING_FISH_SAUCE', 'ING_DARK_SOY_SAUCE', 'ING_PALM_SUGAR', 'ING_VEGETABLE_OIL'],
  ARRAY['eggs', 'fish', 'soy', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  580,
  28,
  62,
  24,
  4,
  ARRAY['holy-basil', 'fried-egg', 'lunch-favorite'],
  95
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KHAO_NA_PED',
  'khao-na-ped',
  'Khao Na Ped',
  'Roasted duck over rice with sweet gravy. Chinese-influenced dish with tender five-spice duck and Chinese broccoli.',
  'Khao Na Ped',
  'ข้าวหน้าเป็ด',
  'rice_dishes',
  'classic',
  'central',
  'duck',
  'roasted',
  'none',
  true,
  false,
  ARRAY['ING_JASMINE_RICE', 'ING_DUCK_WHOLE', 'ING_FIVE_SPICE', 'ING_DARK_SOY_SAUCE', 'ING_CHINESE_BROCCOLI', 'ING_RED_SAUCE', 'ING_CILANTRO', 'ING_STAR_ANISE', 'ING_CINNAMON', 'ING_GARLIC'],
  ARRAY['soy'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  560,
  30,
  56,
  24,
  0,
  ARRAY['roasted-duck', 'chinese-thai', 'five-spice'],
  82
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KHAO_NIAO',
  'sticky-rice',
  'Khao Niao',
  'Thai sticky rice, the staple carbohydrate of Northeastern Thailand. Essential accompaniment to Isan dishes like larb and som tam.',
  'Khao Niao',
  'ข้าวเหนียว',
  'rice_dishes',
  'classic',
  'northeastern',
  'vegetables',
  'steamed',
  'none',
  true,
  false,
  ARRAY['ING_STICKY_RICE'],
  '{}'::TEXT[],
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  200,
  4,
  44,
  0,
  0,
  ARRAY['staple', 'isan', 'side-dish'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_SATAY',
  'satay',
  'Satay',
  'Grilled marinated meat skewers with creamy peanut sauce and cucumber relish. Thai-style satay with aromatic spices.',
  'Satay',
  'สะเต๊ะ',
  'appetizers',
  'signature',
  'central',
  'chicken',
  'grilled',
  'none',
  true,
  true,
  ARRAY['ING_CHICKEN_THIGH', 'ING_COCONUT_MILK', 'ING_TURMERIC', 'ING_LEMONGRASS', 'ING_CORIANDER', 'ING_CUMIN', 'ING_PEANUTS', 'ING_COCONUT_CREAM', 'ING_RED_CURRY_PASTE', 'ING_PALM_SUGAR', 'ING_TAMARIND', 'ING_CUCUMBER'],
  ARRAY['peanuts'],
  true,
  true,
  false,
  false,
  false,
  true,
  false,
  320,
  24,
  16,
  20,
  1,
  ARRAY['skewers', 'peanut-sauce', 'grilled', 'party-food'],
  92
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_SPRING_ROLLS',
  'poh-pia-tod',
  'Poh Pia Tod',
  'Crispy Thai spring rolls filled with glass noodles, vegetables, and minced pork. Golden and crunchy appetizer.',
  'Poh Pia Tod',
  'ปอเปี๊ยะทอด',
  'appetizers',
  'popular',
  'central',
  'pork',
  'deep_fried',
  'none',
  true,
  false,
  ARRAY['ING_SPRING_ROLL_WRAPPERS', 'ING_GLASS_NOODLES', 'ING_PORK_GROUND', 'ING_CABBAGE', 'ING_CARROTS', 'ING_WOOD_EAR_MUSHROOMS', 'ING_GARLIC', 'ING_SOY_SAUCE', 'ING_WHITE_PEPPER', 'ING_VEGETABLE_OIL'],
  ARRAY['gluten', 'soy'],
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  280,
  12,
  28,
  14,
  0,
  ARRAY['crispy', 'fried', 'appetizer'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_FRESH_ROLLS',
  'poh-pia-sod',
  'Poh Pia Sod',
  'Fresh Thai spring rolls wrapped in soft rice paper with vegetables, herbs, and cooked shrimp. Light and healthy.',
  'Poh Pia Sod',
  'ปอเปี๊ยะสด',
  'appetizers',
  'popular',
  'central',
  'shrimp',
  'raw',
  'none',
  true,
  false,
  ARRAY['ING_RICE_PAPER', 'ING_SHRIMP', 'ING_LETTUCE', 'ING_VERMICELLI', 'ING_CARROTS', 'ING_CUCUMBER', 'ING_MINT', 'ING_THAI_BASIL', 'ING_PEANUT_SAUCE', 'ING_HOISIN_SAUCE'],
  ARRAY['shellfish', 'peanuts', 'soy'],
  true,
  true,
  false,
  false,
  false,
  true,
  true,
  180,
  12,
  22,
  6,
  0,
  ARRAY['fresh', 'healthy', 'light'],
  80
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_TOD_MUN_PLA',
  'tod-mun-pla',
  'Tod Mun Pla',
  'Thai fish cakes with red curry paste, kaffir lime leaves, and long beans. Aromatic and bouncy texture, served with cucumber relish.',
  'Tod Mun Pla',
  'ทอดมันปลา',
  'appetizers',
  'signature',
  'central',
  'fish',
  'deep_fried',
  'none',
  true,
  false,
  ARRAY['ING_FISH_PASTE', 'ING_RED_CURRY_PASTE', 'ING_KAFFIR_LIME_LEAVES', 'ING_LONG_BEANS', 'ING_EGGS', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_CUCUMBER_RELISH', 'ING_PEANUTS', 'ING_VEGETABLE_OIL'],
  ARRAY['fish', 'eggs', 'peanuts'],
  true,
  true,
  false,
  false,
  false,
  true,
  true,
  260,
  18,
  14,
  16,
  2,
  ARRAY['fish-cakes', 'aromatic', 'street-food'],
  88
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_MIENG_KUM',
  'mieng-kum',
  'Mieng Kum',
  'Betel leaf wraps with coconut, ginger, lime, peanuts, and sweet sauce. One-bite appetizer with explosion of flavors.',
  'Miang Kham',
  'เมี่ยงคำ',
  'appetizers',
  'classic',
  'central',
  'vegetables',
  'raw',
  'none',
  true,
  false,
  ARRAY['ING_BETEL_LEAVES', 'ING_TOASTED_COCONUT', 'ING_GINGER', 'ING_LIME', 'ING_PEANUTS', 'ING_DRIED_SHRIMP', 'ING_SHALLOTS', 'ING_BIRD_EYE_CHILI', 'ING_PALM_SUGAR', 'ING_FISH_SAUCE'],
  ARRAY['peanuts', 'shellfish', 'fish'],
  true,
  true,
  false,
  false,
  false,
  true,
  true,
  150,
  6,
  18,
  8,
  2,
  ARRAY['one-bite', 'royal', 'complex-flavors'],
  75
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GOONG_SARONG',
  'goong-sarong',
  'Goong Sarong',
  'Prawns wrapped in crispy noodle threads then deep-fried. Elegant appetizer with crunchy exterior and juicy prawn inside.',
  'Goong Sarong',
  'กุ้งสะโรง',
  'appetizers',
  'classic',
  'central',
  'shrimp',
  'deep_fried',
  'none',
  false,
  false,
  ARRAY['ING_SHRIMP', 'ING_RICE_VERMICELLI', 'ING_EGGS', 'ING_GARLIC', 'ING_WHITE_PEPPER', 'ING_SESAME_OIL', 'ING_SOY_SAUCE', 'ING_VEGETABLE_OIL', 'ING_SWEET_CHILI_SAUCE'],
  ARRAY['shellfish', 'eggs', 'soy', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  220,
  16,
  18,
  10,
  0,
  ARRAY['crispy', 'elegant', 'prawns'],
  78
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GAI_HO_BAI_TOEY',
  'gai-ho-bai-toey',
  'Gai Ho Bai Toey',
  'Chicken wrapped in pandan leaves and deep-fried. Aromatic chicken parcels with sweet, fragrant pandan flavor.',
  'Gai Ho Bai Toey',
  'ไก่ห่อใบเตย',
  'appetizers',
  'popular',
  'central',
  'chicken',
  'deep_fried',
  'none',
  true,
  false,
  ARRAY['ING_CHICKEN_THIGH', 'ING_PANDAN_LEAVES', 'ING_OYSTER_SAUCE', 'ING_SOY_SAUCE', 'ING_SESAME_OIL', 'ING_GARLIC', 'ING_WHITE_PEPPER', 'ING_PALM_SUGAR', 'ING_VEGETABLE_OIL', 'ING_SWEET_CHILI_SAUCE'],
  ARRAY['soy', 'shellfish', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  280,
  22,
  12,
  16,
  0,
  ARRAY['pandan', 'aromatic', 'street-food'],
  82
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GAI_YANG',
  'gai-yang',
  'Gai Yang',
  'Northeastern Thai grilled chicken marinated in garlic, coriander root, and white pepper. Charcoal-grilled to perfection, served with sticky rice.',
  'Gai Yang',
  'ไก่ย่าง',
  'grilled',
  'signature',
  'northeastern',
  'chicken',
  'grilled',
  'none',
  true,
  false,
  ARRAY['ING_CHICKEN_WHOLE', 'ING_GARLIC', 'ING_CORIANDER_ROOT', 'ING_WHITE_PEPPER', 'ING_SOY_SAUCE', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_OYSTER_SAUCE', 'ING_STICKY_RICE', 'ING_JAEW_SAUCE'],
  ARRAY['soy', 'fish', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  380,
  35,
  8,
  22,
  1,
  ARRAY['isan', 'charcoal-grilled', 'street-food'],
  92
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_MOO_PING',
  'moo-ping',
  'Moo Ping',
  'Grilled pork skewers marinated in coconut milk, garlic, and coriander root. Sweet and savory street food breakfast classic.',
  'Moo Ping',
  'หมูปิ้ง',
  'grilled',
  'signature',
  'central',
  'pork',
  'grilled',
  'none',
  true,
  true,
  ARRAY['ING_PORK_SHOULDER', 'ING_COCONUT_MILK', 'ING_GARLIC', 'ING_CORIANDER_ROOT', 'ING_WHITE_PEPPER', 'ING_SOY_SAUCE', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_OYSTER_SAUCE', 'ING_STICKY_RICE'],
  ARRAY['soy', 'fish', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  320,
  26,
  12,
  20,
  0,
  ARRAY['skewers', 'breakfast', 'street-food'],
  90
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KOR_MOO_YANG',
  'kor-moo-yang',
  'Kor Moo Yang',
  'Grilled pork neck, marbled with fat for incredible flavor. Thai BBQ favorite served with spicy dipping sauce.',
  'Kor Moo Yang',
  'คอหมูย่าง',
  'grilled',
  'popular',
  'northeastern',
  'pork',
  'grilled',
  'none',
  true,
  false,
  ARRAY['ING_PORK_NECK', 'ING_GARLIC', 'ING_CORIANDER_ROOT', 'ING_WHITE_PEPPER', 'ING_SOY_SAUCE', 'ING_FISH_SAUCE', 'ING_OYSTER_SAUCE', 'ING_JAEW_SAUCE', 'ING_STICKY_RICE', 'ING_CABBAGE'],
  ARRAY['soy', 'fish', 'shellfish'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  420,
  32,
  6,
  30,
  0,
  ARRAY['pork-neck', 'marbled', 'bbq'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PLA_PAO',
  'pla-pao',
  'Pla Pao',
  'Salt-crusted grilled fish, traditionally over charcoal. Whole fish stuffed with lemongrass, served with spicy seafood sauce.',
  'Pla Pao',
  'ปลาเผา',
  'grilled',
  'classic',
  'central',
  'fish',
  'grilled',
  'none',
  true,
  false,
  ARRAY['ING_WHOLE_FISH', 'ING_SALT', 'ING_LEMONGRASS', 'ING_KAFFIR_LIME_LEAVES', 'ING_GALANGAL', 'ING_SEAFOOD_SAUCE', 'ING_LIME_JUICE', 'ING_GARLIC', 'ING_BIRD_EYE_CHILI', 'ING_CILANTRO'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  280,
  38,
  4,
  12,
  3,
  ARRAY['whole-fish', 'salt-crusted', 'charcoal'],
  82
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GOONG_YANG',
  'goong-yang',
  'Goong Yang',
  'Grilled river prawns, typically large freshwater prawns. Simply seasoned and grilled to highlight their sweet, oceanic flavor.',
  'Goong Yang',
  'กุ้งย่าง',
  'grilled',
  'premium',
  'central',
  'shrimp',
  'grilled',
  'none',
  false,
  false,
  ARRAY['ING_RIVER_PRAWNS', 'ING_SALT', 'ING_SEAFOOD_SAUCE', 'ING_LIME_JUICE', 'ING_GARLIC', 'ING_BIRD_EYE_CHILI', 'ING_FISH_SAUCE', 'ING_CILANTRO'],
  ARRAY['shellfish', 'fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  180,
  32,
  2,
  4,
  2,
  ARRAY['river-prawns', 'premium', 'simple'],
  80
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_SEE_KRONG_MOO_YANG',
  'see-krong-moo-yang',
  'See Krong Moo Yang',
  'Thai-style grilled pork ribs marinated in honey, garlic, and spices. Sweet, sticky, and fall-off-the-bone tender.',
  'See Krong Moo Yang',
  'ซี่โครงหมูย่าง',
  'grilled',
  'popular',
  'central',
  'pork',
  'grilled',
  'none',
  false,
  false,
  ARRAY['ING_PORK_RIBS', 'ING_HONEY', 'ING_GARLIC', 'ING_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_FIVE_SPICE', 'ING_WHITE_PEPPER', 'ING_SESAME_OIL', 'ING_CILANTRO', 'ING_STICKY_RICE'],
  ARRAY['soy', 'shellfish', 'sesame'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  480,
  28,
  18,
  34,
  0,
  ARRAY['ribs', 'honey-glazed', 'tender'],
  78
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PLA_RAD_PRIK',
  'pla-rad-prik',
  'Pla Rad Prik',
  'Deep-fried whole fish topped with spicy chili sauce. Crispy fish smothered in sweet, sour, and spicy tamarind-chili sauce.',
  'Pla Rad Prik',
  'ปลาราดพริก',
  'seafood',
  'signature',
  'central',
  'fish',
  'deep_fried',
  'none',
  false,
  false,
  ARRAY['ING_WHOLE_FISH', 'ING_RED_CHILI', 'ING_GARLIC', 'ING_TAMARIND', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_SHALLOTS', 'ING_VEGETABLE_OIL', 'ING_CILANTRO', 'ING_RICE_FLOUR'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  380,
  32,
  22,
  18,
  4,
  ARRAY['crispy-fish', 'chili-sauce', 'iconic'],
  88
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PLA_NEUNG_MANAO',
  'pla-neung-manao',
  'Pla Neung Manao',
  'Steamed fish with lime, garlic, and chili. Delicate steamed fish in intensely flavorful lime-chili-garlic broth.',
  'Pla Neung Manao',
  'ปลานึ่งมะนาว',
  'seafood',
  'signature',
  'central',
  'fish',
  'steamed',
  'none',
  false,
  false,
  ARRAY['ING_WHOLE_FISH', 'ING_LIME_JUICE', 'ING_GARLIC', 'ING_BIRD_EYE_CHILI', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_CILANTRO', 'ING_CELERY', 'ING_CHICKEN_STOCK'],
  ARRAY['fish'],
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  220,
  36,
  8,
  6,
  4,
  ARRAY['steamed', 'lime', 'healthy', 'light'],
  85
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_GOONG_OB_WOON_SEN',
  'goong-ob-woon-sen',
  'Goong Ob Woon Sen',
  'Baked prawns with glass noodles in clay pot. Prawns, bacon, and glass noodles steamed together with aromatic seasonings.',
  'Goong Ob Woon Sen',
  'กุ้งอบวุ้นเส้น',
  'seafood',
  'signature',
  'central',
  'shrimp',
  'steamed',
  'none',
  false,
  false,
  ARRAY['ING_SHRIMP', 'ING_GLASS_NOODLES', 'ING_BACON', 'ING_GINGER', 'ING_GARLIC', 'ING_CORIANDER_ROOT', 'ING_SOY_SAUCE', 'ING_OYSTER_SAUCE', 'ING_SESAME_OIL', 'ING_WHITE_PEPPER', 'ING_CELERY'],
  ARRAY['shellfish', 'soy'],
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  350,
  28,
  32,
  14,
  0,
  ARRAY['clay-pot', 'glass-noodles', 'aromatic'],
  86
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_HOY_LAI_PAD_NAM_PRIK_PAO',
  'hoy-lai-pad-nam-prik-pao',
  'Hoy Lai Pad Nam Prik Pao',
  'Stir-fried clams with roasted chili paste. Briny clams wok-fried with aromatic Thai chili jam and fresh basil.',
  'Hoy Lai Pad Nam Prik Pao',
  'หอยลายผัดน้ำพริกเผา',
  'seafood',
  'popular',
  'central',
  'mixed_seafood',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_CLAMS', 'ING_ROASTED_CHILI_PASTE', 'ING_THAI_BASIL', 'ING_GARLIC', 'ING_BIRD_EYE_CHILI', 'ING_FISH_SAUCE', 'ING_PALM_SUGAR', 'ING_VEGETABLE_OIL'],
  ARRAY['shellfish', 'fish'],
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  220,
  22,
  12,
  10,
  3,
  ARRAY['clams', 'chili-paste', 'wok-fried'],
  80
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_PLA_MEUK_PAD_KHAI_KEM',
  'pla-meuk-pad-khai-kem',
  'Pla Meuk Pad Khai Kem',
  'Stir-fried squid with salted egg yolk. Tender squid coated in rich, creamy salted egg sauce with curry leaves.',
  'Pla Meuk Pad Khai Kem',
  'ปลาหมึกผัดไข่เค็ม',
  'seafood',
  'popular',
  'central',
  'squid',
  'stir_fried',
  'none',
  false,
  false,
  ARRAY['ING_SQUID', 'ING_SALTED_EGG_YOLK', 'ING_CURRY_LEAVES', 'ING_BIRD_EYE_CHILI', 'ING_GARLIC', 'ING_BUTTER', 'ING_EVAPORATED_MILK', 'ING_PALM_SUGAR', 'ING_FISH_SAUCE'],
  ARRAY['mollusks', 'eggs', 'milk', 'fish'],
  true,
  false,
  true,
  false,
  false,
  true,
  true,
  320,
  24,
  14,
  20,
  2,
  ARRAY['salted-egg', 'creamy', 'modern-thai'],
  82
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_POO_PAD_PONG_KARI',
  'poo-pad-pong-kari',
  'Poo Pad Pong Kari',
  'Stir-fried crab in yellow curry sauce. Whole crab in creamy, mild curry sauce with egg, a Thai-Chinese fusion classic.',
  'Poo Pad Pong Kari',
  'ปูผัดผงกะหรี่',
  'seafood',
  'signature',
  'central',
  'crab',
  'stir_fried',
  'yellow',
  false,
  false,
  ARRAY['ING_CRAB', 'ING_CURRY_POWDER', 'ING_EGGS', 'ING_EVAPORATED_MILK', 'ING_CELERY', 'ING_ONION', 'ING_SPRING_ONION', 'ING_OYSTER_SAUCE', 'ING_SOY_SAUCE', 'ING_GARLIC', 'ING_BIRD_EYE_CHILI'],
  ARRAY['shellfish', 'eggs', 'milk', 'soy'],
  true,
  false,
  true,
  false,
  false,
  false,
  true,
  380,
  28,
  16,
  24,
  1,
  ARRAY['crab', 'curry', 'thai-chinese', 'premium'],
  90
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_HOY_THOD',
  'hoy-thod',
  'Hoy Thod',
  'Crispy mussel pancake with egg and batter. Street food favorite with crunchy edges and soft eggy center.',
  'Hoy Thod',
  'หอยทอด',
  'seafood',
  'classic',
  'central',
  'mixed_seafood',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_MUSSELS', 'ING_EGGS', 'ING_TAPIOCA_STARCH', 'ING_RICE_FLOUR', 'ING_BEAN_SPROUTS', 'ING_SPRING_ONION', 'ING_VEGETABLE_OIL', 'ING_SOY_SAUCE', 'ING_SRIRACHA'],
  ARRAY['mollusks', 'eggs', 'soy'],
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  420,
  18,
  38,
  22,
  1,
  ARRAY['pancake', 'crispy', 'street-food'],
  84
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_MANGO_STICKY_RICE',
  'khao-niao-mamuang',
  'Mango Sticky Rice',
  'Thailand\''s most beloved dessert with ripe mango, sweet coconut sticky rice, and coconut cream. Simple perfection.',
  'Khao Niao Mamuang',
  'ข้าวเหนียวมะม่วง',
  'desserts',
  'signature',
  'central',
  'vegetables',
  'steamed',
  'none',
  true,
  true,
  ARRAY['ING_STICKY_RICE', 'ING_MANGO', 'ING_COCONUT_MILK', 'ING_COCONUT_CREAM', 'ING_PALM_SUGAR', 'ING_SALT', 'ING_MUNG_BEANS'],
  '{}'::TEXT[],
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  380,
  5,
  68,
  12,
  0,
  ARRAY['iconic', 'mango', 'coconut', 'must-try'],
  98
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_ROTI_BANANA',
  'roti-kluay',
  'Roti with Banana',
  'Thai-style Indian flatbread filled with banana, drizzled with condensed milk and chocolate. Street food dessert favorite.',
  'Roti Kluay',
  'โรตีกล้วย',
  'desserts',
  'popular',
  'southern',
  'vegetables',
  'stir_fried',
  'none',
  true,
  false,
  ARRAY['ING_ROTI_DOUGH', 'ING_BANANA', 'ING_EGGS', 'ING_CONDENSED_MILK', 'ING_BUTTER', 'ING_CHOCOLATE_SAUCE', 'ING_SUGAR'],
  ARRAY['gluten', 'eggs', 'milk'],
  false,
  false,
  true,
  false,
  true,
  true,
  true,
  420,
  8,
  58,
  18,
  0,
  ARRAY['roti', 'street-food', 'indian-influenced'],
  88
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_TUB_TIM_KROB',
  'tub-tim-krob',
  'Tub Tim Krob',
  'Red ruby water chestnuts in coconut milk. Crisp water chestnut cubes coated in red tapioca, served in sweet coconut milk over ice.',
  'Tub Tim Krob',
  'ทับทิมกรอบ',
  'desserts',
  'popular',
  'central',
  'vegetables',
  'boiled',
  'none',
  true,
  true,
  ARRAY['ING_WATER_CHESTNUTS', 'ING_TAPIOCA_STARCH', 'ING_COCONUT_MILK', 'ING_PALM_SUGAR', 'ING_FOOD_COLORING', 'ING_JASMINE', 'ING_ICE'],
  '{}'::TEXT[],
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  280,
  2,
  52,
  8,
  0,
  ARRAY['refreshing', 'coconut', 'red-rubies'],
  82
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_KHANOM_KROK',
  'khanom-krok',
  'Khanom Krok',
  'Coconut rice pancakes cooked in a special pan. Crispy edges with creamy coconut custard center, topped with corn or taro.',
  'Khanom Krok',
  'ขนมครก',
  'desserts',
  'classic',
  'central',
  'vegetables',
  'stir_fried',
  'none',
  true,
  true,
  ARRAY['ING_RICE_FLOUR', 'ING_COCONUT_MILK', 'ING_COCONUT_CREAM', 'ING_PALM_SUGAR', 'ING_SALT', 'ING_CORN', 'ING_SPRING_ONION'],
  '{}'::TEXT[],
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  180,
  3,
  28,
  8,
  0,
  ARRAY['pancakes', 'coconut', 'breakfast-dessert'],
  80
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_THAI_TEA_PANNA_COTTA',
  'thai-tea-dessert',
  'Thai Tea Custard',
  'Silky Thai tea-flavored custard dessert. Rich orange-colored Thai tea transformed into a creamy, jiggly sweet treat.',
  'Khanom Cha Thai',
  'ขนมชาไทย',
  'desserts',
  'popular',
  'central',
  'vegetables',
  'steamed',
  'none',
  false,
  true,
  ARRAY['ING_THAI_TEA', 'ING_COCONUT_MILK', 'ING_CONDENSED_MILK', 'ING_EGGS', 'ING_PALM_SUGAR', 'ING_GELATIN'],
  ARRAY['eggs', 'milk'],
  true,
  false,
  true,
  false,
  true,
  true,
  true,
  220,
  5,
  32,
  10,
  0,
  ARRAY['thai-tea', 'custard', 'modern'],
  75
);

INSERT INTO thai (
  id, slug, name, description, thai_name, thai_script,
  category, status, region, protein_type, cooking_method, curry_type,
  is_street_food, has_coconut_milk,
  ingredient_ids, allergens,
  is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian,
  calories_per_serving, protein_g, carbs_g, fat_g,
  spice_level, tags, popularity
) VALUES (
  'THAI_BINGSU_THAI',
  'nam-kang-sai',
  'Nam Kang Sai',
  'Thai shaved ice with various toppings including coconut jelly, jackfruit, palm seeds, and red beans in sweet syrup.',
  'Nam Kang Sai',
  'น้ำแข็งใส',
  'desserts',
  'classic',
  'central',
  'vegetables',
  'raw',
  'none',
  true,
  false,
  ARRAY['ING_ICE', 'ING_COCONUT_JELLY', 'ING_JACKFRUIT', 'ING_PALM_SEEDS', 'ING_RED_BEANS', 'ING_GRASS_JELLY', 'ING_SIMPLE_SYRUP', 'ING_CONDENSED_MILK'],
  ARRAY['milk'],
  true,
  false,
  true,
  false,
  true,
  true,
  true,
  260,
  4,
  52,
  6,
  0,
  ARRAY['shaved-ice', 'refreshing', 'toppings'],
  78
);

COMMIT;

-- Verify
SELECT category, COUNT(*) as count FROM thai GROUP BY category ORDER BY count DESC;
SELECT COUNT(*) as total_thai_dishes FROM thai;
