/**
 * Mock Data for Menu Management
 *
 * Used for offline development and testing.
 * This data mirrors the SQL seed data in 001-menu-management.sql
 */

import type {
  Merchant,
  MerchantUser,
  MenuCategory,
  MenuItem,
  MenuItemIngredient,
} from '../types';

// ============================================================================
// DEMO MERCHANT
// ============================================================================

export const demoMerchant: Merchant = {
  id: 'demo-cafe-uuid-001',
  slug: 'demo-cafe',
  name: 'Demo Café',
  description: 'A demo coffee shop for testing the GUDBRO platform',
  email: 'demo@gudbro.com',
  phone: '+84 236 1234567',
  website: 'https://demo-cafe.gudbro.com',
  address: '42 Nguyen Van Linh, Hai Chau',
  city: 'Da Nang',
  country: 'VN',
  timezone: 'Asia/Ho_Chi_Minh',
  logoUrl: '/images/merchants/demo-cafe-logo.png',
  coverImageUrl: '/images/merchants/demo-cafe-cover.jpg',
  primaryColor: '#2d5016',
  secondaryColor: '#f5f5dc',
  currency: 'VND',
  defaultLanguage: 'en',
  supportedLanguages: ['en', 'vi', 'ko'],
  tier: 'full_suite',
  tierExpiresAt: '2025-12-31T23:59:59Z',
  wifiEnabled: true,
  wifiSsid: 'Demo_Guest_WiFi',
  wifiPassword: 'demo2024!',
  wifiSecurity: 'WPA2',
  isActive: true,
  isVerified: true,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-11-29T10:00:00Z',
};

// ============================================================================
// DEMO MERCHANT USERS
// ============================================================================

export const demoMerchantUsers: MerchantUser[] = [
  {
    id: 'user-uuid-001',
    merchantId: 'demo-cafe-uuid-001',
    authProvider: 'email',
    authProviderId: 'demo-owner@gudbro.com',
    email: 'demo-owner@gudbro.com',
    name: 'Demo Owner',
    role: 'owner',
    permissions: {
      canViewMenu: true,
      canEditMenu: true,
      canDeleteMenuItems: true,
      canManageCategories: true,
      canViewOrders: true,
      canManageOrders: true,
      canViewAnalytics: true,
      canEditSettings: true,
      canManageBilling: true,
      canManageTeam: true,
      canManageTranslations: true,
      canManageQRCodes: true,
    },
    isActive: true,
    lastLoginAt: '2024-11-29T08:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T08:00:00Z',
  },
  {
    id: 'user-uuid-002',
    merchantId: 'demo-cafe-uuid-001',
    authProvider: 'email',
    authProviderId: 'demo-staff@gudbro.com',
    email: 'demo-staff@gudbro.com',
    name: 'Demo Staff',
    role: 'staff',
    permissions: {
      canViewMenu: true,
      canEditMenu: false,
      canDeleteMenuItems: false,
      canManageCategories: false,
      canViewOrders: true,
      canManageOrders: true,
      canViewAnalytics: false,
      canEditSettings: false,
      canManageBilling: false,
      canManageTeam: false,
      canManageTranslations: false,
      canManageQRCodes: false,
    },
    isActive: true,
    lastLoginAt: '2024-11-28T14:00:00Z',
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-11-28T14:00:00Z',
  },
];

// ============================================================================
// DEMO CATEGORIES
// ============================================================================

export const demoCategories: MenuCategory[] = [
  {
    id: 'cat-uuid-001',
    merchantId: 'demo-cafe-uuid-001',
    slug: 'hot-coffee',
    name: { en: 'Hot Coffee', it: 'Caffè Caldo', vi: 'Cà phê nóng' },
    description: {
      en: 'Freshly brewed hot coffee drinks',
      it: 'Caffè caldo appena preparato',
      vi: 'Cà phê nóng pha mới',
    },
    icon: '☕',
    color: '#4a2c2a',
    displayOrder: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },
  {
    id: 'cat-uuid-002',
    merchantId: 'demo-cafe-uuid-001',
    slug: 'iced-coffee',
    name: { en: 'Iced Coffee', it: 'Caffè Freddo', vi: 'Cà phê đá' },
    description: {
      en: 'Refreshing iced coffee drinks',
      it: 'Caffè freddo rinfrescante',
      vi: 'Cà phê đá mát lạnh',
    },
    icon: '🧊',
    color: '#87ceeb',
    displayOrder: 2,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },
  {
    id: 'cat-uuid-003',
    merchantId: 'demo-cafe-uuid-001',
    slug: 'food',
    name: { en: 'Food', it: 'Cibo', vi: 'Đồ ăn' },
    description: {
      en: 'Light bites and sandwiches',
      it: 'Spuntini e panini',
      vi: 'Đồ ăn nhẹ và bánh mì',
    },
    icon: '🍽️',
    color: '#ffa500',
    displayOrder: 3,
    isActive: true,
    visibleFrom: '07:00:00',
    visibleTo: '20:00:00',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },
  {
    id: 'cat-uuid-004',
    merchantId: 'demo-cafe-uuid-001',
    slug: 'desserts',
    name: { en: 'Desserts', it: 'Dolci', vi: 'Tráng miệng' },
    description: {
      en: 'Sweet treats and pastries',
      it: 'Dolci e pasticcini',
      vi: 'Bánh ngọt và đồ tráng miệng',
    },
    icon: '🍰',
    color: '#ffb6c1',
    displayOrder: 4,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },
  {
    id: 'cat-uuid-005',
    merchantId: 'demo-cafe-uuid-001',
    slug: 'smoothies',
    name: { en: 'Smoothies & Wellness', it: 'Frullati & Benessere', vi: 'Sinh tố & Sức khỏe' },
    description: {
      en: 'Healthy smoothies and wellness drinks',
      it: 'Frullati salutari e bevande benessere',
      vi: 'Sinh tố và đồ uống sức khỏe',
    },
    icon: '🥤',
    color: '#90ee90',
    displayOrder: 5,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },
];

// ============================================================================
// DEMO MENU ITEMS
// ============================================================================

export const demoMenuItems: MenuItem[] = [
  // ===== HOT COFFEE =====
  {
    id: 'item-uuid-001',
    merchantId: 'demo-cafe-uuid-001',
    categoryId: 'cat-uuid-001',
    slug: 'espresso',
    name: { en: 'Espresso', it: 'Espresso', vi: 'Espresso' },
    description: {
      en: 'Rich and bold single shot of espresso',
      it: 'Espresso singolo ricco e intenso',
      vi: 'Một shot espresso đậm đà',
    },
    shortDescription: { en: 'Single shot', it: 'Shot singolo', vi: 'Một shot' },
    price: 35000,
    currency: 'VND',
    imageUrl: '/images/menu/espresso.jpg',
    allergens: {},
    intolerances: { caffeine: true },
    dietaryFlags: { vegan: true, vegetarian: true, gluten_free: true, dairy_free: true },
    spiceLevel: 0,
    safetyDataSource: 'manual',
    customizations: [
      {
        id: 'shot-type',
        type: 'radio',
        name: { en: 'Shot Type', it: 'Tipo Shot', vi: 'Loại Shot' },
        required: true,
        options: [
          { id: 'single', name: { en: 'Single', it: 'Singolo', vi: 'Đơn' }, price_modifier: 0, is_default: true },
          { id: 'double', name: { en: 'Double', it: 'Doppio', vi: 'Đôi' }, price_modifier: 15000, is_default: false },
        ],
        display_order: 1,
      },
    ],
    trackInventory: false,
    lowStockThreshold: 10,
    isAvailable: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    displayOrder: 1,
    tags: ['coffee', 'classic', 'quick'],
    totalOrders: 1250,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },
  {
    id: 'item-uuid-002',
    merchantId: 'demo-cafe-uuid-001',
    categoryId: 'cat-uuid-001',
    slug: 'cappuccino',
    name: { en: 'Cappuccino', it: 'Cappuccino', vi: 'Cappuccino' },
    description: {
      en: 'Espresso with steamed milk and foam',
      it: 'Espresso con latte caldo e schiuma',
      vi: 'Espresso với sữa nóng và bọt sữa',
    },
    price: 55000,
    currency: 'VND',
    imageUrl: '/images/menu/cappuccino.jpg',
    allergens: { milk: true },
    intolerances: { caffeine: true, lactose: true },
    dietaryFlags: { vegetarian: true, gluten_free: true },
    spiceLevel: 0,
    safetyDataSource: 'manual',
    customizations: [
      {
        id: 'size',
        type: 'radio',
        name: { en: 'Size', it: 'Dimensione', vi: 'Kích cỡ' },
        required: true,
        options: [
          { id: 'small', name: { en: 'Small (8oz)', it: 'Piccolo', vi: 'Nhỏ' }, price_modifier: 0, is_default: true },
          { id: 'medium', name: { en: 'Medium (12oz)', it: 'Medio', vi: 'Vừa' }, price_modifier: 10000, is_default: false },
          { id: 'large', name: { en: 'Large (16oz)', it: 'Grande', vi: 'Lớn' }, price_modifier: 20000, is_default: false },
        ],
        display_order: 1,
      },
      {
        id: 'milk-type',
        type: 'radio',
        name: { en: 'Milk Type', it: 'Tipo di Latte', vi: 'Loại Sữa' },
        required: true,
        options: [
          { id: 'regular', name: { en: 'Regular Milk', it: 'Latte Normale', vi: 'Sữa thường' }, price_modifier: 0, is_default: true },
          { id: 'oat', name: { en: 'Oat Milk', it: 'Latte di Avena', vi: 'Sữa yến mạch' }, price_modifier: 15000, is_default: false },
          { id: 'almond', name: { en: 'Almond Milk', it: 'Latte di Mandorla', vi: 'Sữa hạnh nhân' }, price_modifier: 15000, is_default: false },
          { id: 'soy', name: { en: 'Soy Milk', it: 'Latte di Soia', vi: 'Sữa đậu nành' }, price_modifier: 10000, is_default: false },
        ],
        display_order: 2,
      },
    ],
    trackInventory: false,
    lowStockThreshold: 10,
    isAvailable: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    displayOrder: 2,
    tags: ['coffee', 'classic', 'milk-based'],
    totalOrders: 3420,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },
  {
    id: 'item-uuid-003',
    merchantId: 'demo-cafe-uuid-001',
    categoryId: 'cat-uuid-001',
    slug: 'latte',
    name: { en: 'Caffè Latte', it: 'Caffè Latte', vi: 'Cà phê Latte' },
    description: {
      en: 'Espresso with extra steamed milk',
      it: 'Espresso con molto latte caldo',
      vi: 'Espresso với nhiều sữa nóng',
    },
    price: 55000,
    currency: 'VND',
    imageUrl: '/images/menu/latte.jpg',
    allergens: { milk: true },
    intolerances: { caffeine: true, lactose: true },
    dietaryFlags: { vegetarian: true, gluten_free: true },
    spiceLevel: 0,
    safetyDataSource: 'manual',
    customizations: [
      {
        id: 'size',
        type: 'radio',
        name: { en: 'Size', it: 'Dimensione', vi: 'Kích cỡ' },
        required: true,
        options: [
          { id: 'small', name: { en: 'Small', it: 'Piccolo', vi: 'Nhỏ' }, price_modifier: 0, is_default: true },
          { id: 'medium', name: { en: 'Medium', it: 'Medio', vi: 'Vừa' }, price_modifier: 10000, is_default: false },
          { id: 'large', name: { en: 'Large', it: 'Grande', vi: 'Lớn' }, price_modifier: 20000, is_default: false },
        ],
        display_order: 1,
      },
      {
        id: 'milk-type',
        type: 'radio',
        name: { en: 'Milk Type', it: 'Tipo di Latte', vi: 'Loại Sữa' },
        required: true,
        options: [
          { id: 'regular', name: { en: 'Regular Milk', it: 'Latte Normale', vi: 'Sữa thường' }, price_modifier: 0, is_default: true },
          { id: 'oat', name: { en: 'Oat Milk', it: 'Latte di Avena', vi: 'Sữa yến mạch' }, price_modifier: 15000, is_default: false },
          { id: 'almond', name: { en: 'Almond Milk', it: 'Latte di Mandorla', vi: 'Sữa hạnh nhân' }, price_modifier: 15000, is_default: false },
          { id: 'coconut', name: { en: 'Coconut Milk', it: 'Latte di Cocco', vi: 'Sữa dừa' }, price_modifier: 15000, is_default: false },
        ],
        display_order: 2,
      },
      {
        id: 'flavor',
        type: 'checkbox',
        name: { en: 'Add Flavor', it: 'Aggiungi Aroma', vi: 'Thêm Hương Vị' },
        required: false,
        max_selections: 2,
        options: [
          { id: 'vanilla', name: { en: 'Vanilla', it: 'Vaniglia', vi: 'Vani' }, price_modifier: 10000, is_default: false },
          { id: 'caramel', name: { en: 'Caramel', it: 'Caramello', vi: 'Caramel' }, price_modifier: 10000, is_default: false },
          { id: 'hazelnut', name: { en: 'Hazelnut', it: 'Nocciola', vi: 'Hạt dẻ' }, price_modifier: 10000, is_default: false },
        ],
        display_order: 3,
      },
    ],
    trackInventory: false,
    lowStockThreshold: 10,
    isAvailable: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    displayOrder: 3,
    tags: ['coffee', 'milk-based'],
    totalOrders: 2890,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },

  // ===== ICED COFFEE =====
  {
    id: 'item-uuid-004',
    merchantId: 'demo-cafe-uuid-001',
    categoryId: 'cat-uuid-002',
    slug: 'vietnamese-iced-coffee',
    name: {
      en: 'Vietnamese Iced Coffee',
      it: 'Caffè Vietnamita Ghiacciato',
      vi: 'Cà phê sữa đá',
    },
    description: {
      en: 'Traditional Vietnamese coffee with condensed milk over ice',
      it: 'Caffè vietnamita tradizionale con latte condensato su ghiaccio',
      vi: 'Cà phê Việt Nam truyền thống với sữa đặc và đá',
    },
    price: 45000,
    currency: 'VND',
    imageUrl: '/images/menu/vietnamese-iced-coffee.jpg',
    allergens: { milk: true },
    intolerances: { caffeine: true, lactose: true },
    dietaryFlags: { vegetarian: true, gluten_free: true },
    spiceLevel: 0,
    safetyDataSource: 'manual',
    customizations: [
      {
        id: 'sweetness',
        type: 'radio',
        name: { en: 'Sweetness', it: 'Dolcezza', vi: 'Độ ngọt' },
        required: true,
        options: [
          { id: 'normal', name: { en: 'Normal', it: 'Normale', vi: 'Bình thường' }, price_modifier: 0, is_default: true },
          { id: 'less', name: { en: 'Less Sweet', it: 'Meno Dolce', vi: 'Ít ngọt' }, price_modifier: 0, is_default: false },
          { id: 'extra', name: { en: 'Extra Sweet', it: 'Extra Dolce', vi: 'Ngọt hơn' }, price_modifier: 0, is_default: false },
        ],
        display_order: 1,
      },
    ],
    trackInventory: false,
    lowStockThreshold: 10,
    isAvailable: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    displayOrder: 1,
    tags: ['coffee', 'vietnamese', 'signature', 'iced'],
    totalOrders: 5230,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },
  {
    id: 'item-uuid-005',
    merchantId: 'demo-cafe-uuid-001',
    categoryId: 'cat-uuid-002',
    slug: 'coconut-cold-brew',
    name: {
      en: 'Coconut Cold Brew',
      it: 'Cold Brew al Cocco',
      vi: 'Cold Brew Dừa',
    },
    description: {
      en: 'Smooth cold brew coffee with creamy coconut milk',
      it: 'Cold brew delicato con latte di cocco cremoso',
      vi: 'Cold brew mịn màng với sữa dừa béo ngậy',
    },
    price: 65000,
    currency: 'VND',
    imageUrl: '/images/menu/coconut-cold-brew.jpg',
    allergens: {},
    intolerances: { caffeine: true },
    dietaryFlags: { vegan: true, vegetarian: true, gluten_free: true, dairy_free: true },
    spiceLevel: 0,
    safetyDataSource: 'manual',
    customizations: [],
    trackInventory: false,
    lowStockThreshold: 10,
    isAvailable: true,
    isActive: true,
    isFeatured: false,
    isNew: true,
    newUntil: '2025-01-31',
    displayOrder: 2,
    tags: ['coffee', 'vegan', 'iced', 'new'],
    totalOrders: 890,
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },

  // ===== SMOOTHIES =====
  {
    id: 'item-uuid-006',
    merchantId: 'demo-cafe-uuid-001',
    categoryId: 'cat-uuid-005',
    slug: 'green-power-smoothie',
    name: {
      en: 'Green Power Smoothie',
      it: 'Frullato Green Power',
      vi: 'Sinh tố Năng lượng Xanh',
    },
    description: {
      en: 'Spinach, banana, mango, and chia seeds blended with coconut water',
      it: 'Spinaci, banana, mango e semi di chia con acqua di cocco',
      vi: 'Rau bina, chuối, xoài và hạt chia xay với nước dừa',
    },
    price: 75000,
    currency: 'VND',
    imageUrl: '/images/menu/green-smoothie.jpg',
    allergens: { banana: true, mango: true },
    intolerances: {},
    dietaryFlags: { vegan: true, vegetarian: true, gluten_free: true, dairy_free: true },
    spiceLevel: 0,
    safetyDataSource: 'manual',
    customizations: [
      {
        id: 'boost',
        type: 'checkbox',
        name: { en: 'Add Boost', it: 'Aggiungi Boost', vi: 'Thêm Boost' },
        required: false,
        max_selections: 3,
        options: [
          { id: 'protein', name: { en: 'Protein (+20g)', it: 'Proteine (+20g)', vi: 'Protein (+20g)' }, price_modifier: 20000, is_default: false },
          { id: 'spirulina', name: { en: 'Spirulina', it: 'Spirulina', vi: 'Tảo xoắn' }, price_modifier: 15000, is_default: false },
          { id: 'collagen', name: { en: 'Collagen', it: 'Collagene', vi: 'Collagen' }, price_modifier: 25000, is_default: false },
        ],
        display_order: 1,
      },
    ],
    trackInventory: false,
    lowStockThreshold: 10,
    isAvailable: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    displayOrder: 1,
    tags: ['smoothie', 'vegan', 'healthy', 'wellness'],
    totalOrders: 1560,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },

  // ===== FOOD =====
  {
    id: 'item-uuid-007',
    merchantId: 'demo-cafe-uuid-001',
    categoryId: 'cat-uuid-003',
    slug: 'avocado-toast',
    name: {
      en: 'Avocado Toast',
      it: 'Toast con Avocado',
      vi: 'Bánh mì Bơ',
    },
    description: {
      en: 'Sourdough toast with smashed avocado, cherry tomatoes, and poached egg',
      it: 'Toast con lievito madre, avocado schiacciato, pomodorini e uovo in camicia',
      vi: 'Bánh mì nướng với bơ nghiền, cà chua bi và trứng chần',
    },
    price: 95000,
    currency: 'VND',
    imageUrl: '/images/menu/avocado-toast.jpg',
    allergens: { gluten: true, eggs: true, tomato: true },
    intolerances: {},
    dietaryFlags: { vegetarian: true },
    spiceLevel: 0,
    safetyDataSource: 'manual',
    customizations: [
      {
        id: 'extras',
        type: 'checkbox',
        name: { en: 'Add Extras', it: 'Aggiungi Extra', vi: 'Thêm Topping' },
        required: false,
        max_selections: 3,
        options: [
          { id: 'bacon', name: { en: 'Bacon', it: 'Pancetta', vi: 'Thịt xông khói' }, price_modifier: 30000, is_default: false },
          { id: 'smoked-salmon', name: { en: 'Smoked Salmon', it: 'Salmone Affumicato', vi: 'Cá hồi xông khói' }, price_modifier: 45000, is_default: false },
          { id: 'feta', name: { en: 'Feta Cheese', it: 'Formaggio Feta', vi: 'Phô mai Feta' }, price_modifier: 20000, is_default: false },
        ],
        display_order: 1,
      },
    ],
    trackInventory: false,
    lowStockThreshold: 10,
    isAvailable: true,
    isActive: true,
    isFeatured: true,
    isNew: false,
    availableFrom: '07:00:00',
    availableTo: '14:00:00',
    displayOrder: 1,
    tags: ['breakfast', 'brunch', 'healthy'],
    totalOrders: 2340,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },

  // ===== DESSERTS =====
  {
    id: 'item-uuid-008',
    merchantId: 'demo-cafe-uuid-001',
    categoryId: 'cat-uuid-004',
    slug: 'tiramisu',
    name: { en: 'Tiramisu', it: 'Tiramisù', vi: 'Tiramisu' },
    description: {
      en: 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream',
      it: 'Classico dolce italiano con savoiardi al caffè e crema al mascarpone',
      vi: 'Bánh tráng miệng Ý cổ điển với bánh quy ngâm espresso và kem mascarpone',
    },
    price: 85000,
    currency: 'VND',
    imageUrl: '/images/menu/tiramisu.jpg',
    allergens: { gluten: true, eggs: true, milk: true },
    intolerances: { caffeine: true, lactose: true, alcohol: true },
    dietaryFlags: { vegetarian: true },
    spiceLevel: 0,
    safetyDataSource: 'manual',
    customizations: [],
    trackInventory: true,
    inventoryCount: 15,
    lowStockThreshold: 5,
    isAvailable: true,
    isActive: true,
    isFeatured: false,
    isNew: false,
    displayOrder: 1,
    tags: ['dessert', 'italian', 'classic'],
    totalOrders: 1890,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },

  // ===== SPICY ITEM EXAMPLE =====
  {
    id: 'item-uuid-009',
    merchantId: 'demo-cafe-uuid-001',
    categoryId: 'cat-uuid-003',
    slug: 'spicy-kimchi-toast',
    name: {
      en: 'Spicy Kimchi Toast',
      it: 'Toast al Kimchi Piccante',
      vi: 'Bánh mì Kim chi Cay',
    },
    description: {
      en: 'Crispy toast topped with homemade kimchi, fried egg, and gochujang mayo',
      it: 'Toast croccante con kimchi fatto in casa, uovo fritto e maionese gochujang',
      vi: 'Bánh mì giòn với kimchi tự làm, trứng chiên và sốt gochujang',
    },
    price: 85000,
    currency: 'VND',
    imageUrl: '/images/menu/kimchi-toast.jpg',
    allergens: { gluten: true, eggs: true, soybeans: true, sesame: true, chili_pepper: true },
    intolerances: { fodmap: true, histamine: true },
    dietaryFlags: { vegetarian: true },
    spiceLevel: 3,
    safetyDataSource: 'manual',
    customizations: [
      {
        id: 'spice-level',
        type: 'radio',
        name: { en: 'Spice Level', it: 'Livello Piccantezza', vi: 'Độ cay' },
        required: true,
        options: [
          { id: 'mild', name: { en: 'Mild 🌶️', it: 'Leggero 🌶️', vi: 'Ít cay 🌶️' }, price_modifier: 0, is_default: false },
          { id: 'medium', name: { en: 'Medium 🌶️🌶️', it: 'Medio 🌶️🌶️', vi: 'Cay vừa 🌶️🌶️' }, price_modifier: 0, is_default: true },
          { id: 'hot', name: { en: 'Hot 🌶️🌶️🌶️', it: 'Piccante 🌶️🌶️🌶️', vi: 'Cay 🌶️🌶️🌶️' }, price_modifier: 0, is_default: false },
          { id: 'extra-hot', name: { en: 'Extra Hot 🔥', it: 'Extra Piccante 🔥', vi: 'Siêu cay 🔥' }, price_modifier: 0, is_default: false },
        ],
        display_order: 1,
      },
    ],
    trackInventory: false,
    lowStockThreshold: 10,
    isAvailable: true,
    isActive: true,
    isFeatured: false,
    isNew: true,
    newUntil: '2025-02-28',
    availableFrom: '11:00:00',
    availableTo: '20:00:00',
    displayOrder: 2,
    tags: ['korean', 'spicy', 'brunch', 'new'],
    totalOrders: 450,
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-11-29T10:00:00Z',
  },
];

// ============================================================================
// DEMO MENU ITEM INGREDIENTS (for auto-computation demo)
// ============================================================================

export const demoMenuItemIngredients: MenuItemIngredient[] = [
  // Cappuccino ingredients
  {
    id: 'ing-uuid-001',
    menuItemId: 'item-uuid-002',
    masterIngredientId: 'ING_COFFEE_ESPRESSO',
    quantity: 30,
    unit: 'ml',
    allergens: {},
    intolerances: { caffeine: true },
    dietaryFlags: { vegan: true, vegetarian: true, gluten_free: true, dairy_free: true },
    isOptional: false,
    displayOrder: 1,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ing-uuid-002',
    menuItemId: 'item-uuid-002',
    masterIngredientId: 'ING_MILK_WHOLE',
    quantity: 150,
    unit: 'ml',
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietaryFlags: { vegetarian: true, gluten_free: true },
    isOptional: false,
    displayOrder: 2,
    createdAt: '2024-01-01T00:00:00Z',
  },
  // Avocado toast ingredients
  {
    id: 'ing-uuid-003',
    menuItemId: 'item-uuid-007',
    masterIngredientId: 'ING_BREAD_SOURDOUGH',
    quantity: 80,
    unit: 'g',
    allergens: { gluten: true },
    intolerances: {},
    dietaryFlags: { vegetarian: true, dairy_free: true },
    isOptional: false,
    displayOrder: 1,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ing-uuid-004',
    menuItemId: 'item-uuid-007',
    masterIngredientId: 'ING_AVOCADO',
    quantity: 100,
    unit: 'g',
    allergens: {},
    intolerances: {},
    dietaryFlags: { vegan: true, vegetarian: true, gluten_free: true, dairy_free: true, halal: true, kosher: true },
    isOptional: false,
    displayOrder: 2,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ing-uuid-005',
    menuItemId: 'item-uuid-007',
    masterIngredientId: 'ING_EGG_CHICKEN',
    quantity: 1,
    unit: 'piece',
    allergens: { eggs: true },
    intolerances: {},
    dietaryFlags: { vegetarian: true, gluten_free: true, dairy_free: true },
    isOptional: false,
    displayOrder: 3,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ing-uuid-006',
    menuItemId: 'item-uuid-007',
    masterIngredientId: 'ING_TOMATO_CHERRY',
    quantity: 50,
    unit: 'g',
    allergens: { tomato: true },
    intolerances: { histamine: true },
    dietaryFlags: { vegan: true, vegetarian: true, gluten_free: true, dairy_free: true, halal: true, kosher: true },
    isOptional: false,
    displayOrder: 4,
    createdAt: '2024-01-01T00:00:00Z',
  },
];

// ============================================================================
// HELPER: Get all data as a bundle
// ============================================================================

export const mockDataBundle = {
  merchants: [demoMerchant],
  merchantUsers: demoMerchantUsers,
  categories: demoCategories,
  menuItems: demoMenuItems,
  menuItemIngredients: demoMenuItemIngredients,
};
