/**
 * GUDBRO Salad Ingredients Database
 *
 * Comprehensive ingredient list for salad preparation including:
 * - Greens & Bases
 * - Vegetables & Fruits
 * - Proteins
 * - Cheeses
 * - Nuts & Seeds
 * - Grains & Legumes
 * - Dressings & Condiments
 * - Herbs & Garnishes
 *
 * All ingredients have Sistema 5 Dimensioni data for allergen computation
 */

import type { IngredientMaster } from '../../types';

export const saladIngredients: IngredientMaster[] = [
  // ============================================================================
  // GREENS & BASES
  // ============================================================================
  {
    id: 'ING_ROMAINE_LETTUCE',
    slug: 'romaine-lettuce',
    name: {
      en: 'Romaine Lettuce',
      it: 'Lattuga Romana',
      es: 'Lechuga Romana',
    },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 3, fat_g: 0, fiber_g: 2, calories_kcal: 17 },
    version: 1,
  },
  {
    id: 'ING_MIXED_GREENS',
    slug: 'mixed-greens',
    name: {
      en: 'Mixed Greens',
      it: 'Misticanza',
      es: 'Mezcla de Verdes',
    },
    description: { en: 'Spring mix of baby lettuces and greens' },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 2, carbs_g: 4, fat_g: 0, fiber_g: 2, calories_kcal: 20 },
    version: 1,
  },
  {
    id: 'ING_ARUGULA',
    slug: 'arugula',
    name: {
      en: 'Arugula',
      it: 'Rucola',
      es: 'Rúcula',
    },
    description: { en: 'Peppery Italian salad green' },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 1 },
    nutrition: { protein_g: 3, carbs_g: 4, fat_g: 1, fiber_g: 2, calories_kcal: 25 },
    version: 1,
  },
  {
    id: 'ING_BABY_SPINACH',
    slug: 'baby-spinach',
    name: {
      en: 'Baby Spinach',
      it: 'Spinacino',
      es: 'Espinaca Baby',
    },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 4, fat_g: 0, fiber_g: 2, calories_kcal: 23 },
    version: 1,
  },
  {
    id: 'ING_KALE',
    slug: 'kale',
    name: {
      en: 'Kale',
      it: 'Cavolo Riccio',
      es: 'Col Rizada',
    },
    description: { en: 'Nutrient-dense superfood green' },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 4, carbs_g: 9, fat_g: 1, fiber_g: 4, calories_kcal: 49 },
    version: 1,
  },
  {
    id: 'ING_ICEBERG_LETTUCE',
    slug: 'iceberg-lettuce',
    name: {
      en: 'Iceberg Lettuce',
      it: 'Lattuga Iceberg',
      es: 'Lechuga Iceberg',
    },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 3, fat_g: 0, fiber_g: 1, calories_kcal: 14 },
    version: 1,
  },
  {
    id: 'ING_RADICCHIO',
    slug: 'radicchio',
    name: {
      en: 'Radicchio',
      it: 'Radicchio',
      es: 'Radicchio',
    },
    description: { en: 'Italian bitter red chicory' },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 5, fat_g: 0, fiber_g: 1, calories_kcal: 23 },
    version: 1,
  },
  {
    id: 'ING_CABBAGE_GREEN',
    slug: 'green-cabbage',
    name: {
      en: 'Green Cabbage',
      it: 'Cavolo Verde',
      es: 'Repollo Verde',
    },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 6, fat_g: 0, fiber_g: 3, calories_kcal: 25 },
    version: 1,
  },
  {
    id: 'ING_CABBAGE_RED',
    slug: 'red-cabbage',
    name: {
      en: 'Red Cabbage',
      it: 'Cavolo Rosso',
      es: 'Repollo Morado',
    },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 7, fat_g: 0, fiber_g: 2, calories_kcal: 31 },
    version: 1,
  },
  {
    id: 'ING_WATERCRESS',
    slug: 'watercress',
    name: {
      en: 'Watercress',
      it: 'Crescione',
      es: 'Berros',
    },
    description: { en: 'Peppery aquatic green' },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 1 },
    nutrition: { protein_g: 2, carbs_g: 1, fat_g: 0, fiber_g: 1, calories_kcal: 11 },
    version: 1,
  },
  {
    id: 'ING_ENDIVE',
    slug: 'endive',
    name: {
      en: 'Belgian Endive',
      it: 'Indivia Belga',
      es: 'Endivia',
    },
    category: { main: 'vegetables', sub: 'greens' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 3, calories_kcal: 17 },
    version: 1,
  },

  // ============================================================================
  // VEGETABLES
  // ============================================================================
  {
    id: 'ING_TOMATO_CHERRY',
    slug: 'cherry-tomatoes',
    name: {
      en: 'Cherry Tomatoes',
      it: 'Pomodorini',
      es: 'Tomates Cherry',
    },
    category: { main: 'vegetables', sub: 'tomatoes' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1, calories_kcal: 18 },
    version: 1,
  },
  {
    id: 'ING_TOMATO_VINE',
    slug: 'vine-tomatoes',
    name: {
      en: 'Vine Tomatoes',
      it: 'Pomodori a Grappolo',
      es: 'Tomates de Rama',
    },
    category: { main: 'vegetables', sub: 'tomatoes' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1, calories_kcal: 18 },
    version: 1,
  },
  {
    id: 'ING_CUCUMBER',
    slug: 'cucumber',
    name: {
      en: 'Cucumber',
      it: 'Cetriolo',
      es: 'Pepino',
    },
    category: { main: 'vegetables', sub: 'cucumber' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1, calories_kcal: 16 },
    version: 1,
  },
  {
    id: 'ING_CUCUMBER_PERSIAN',
    slug: 'persian-cucumber',
    name: {
      en: 'Persian Cucumber',
      it: 'Cetriolo Persiano',
      es: 'Pepino Persa',
    },
    description: { en: 'Small, thin-skinned, seedless cucumber' },
    category: { main: 'vegetables', sub: 'cucumber' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 3, fat_g: 0, fiber_g: 1, calories_kcal: 12 },
    version: 1,
  },
  {
    id: 'ING_RED_ONION',
    slug: 'red-onion',
    name: {
      en: 'Red Onion',
      it: 'Cipolla Rossa',
      es: 'Cebolla Morada',
    },
    category: { main: 'vegetables', sub: 'alliums' },
    allergens: {},
    intolerances: { fodmap: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 1 },
    nutrition: { protein_g: 1, carbs_g: 9, fat_g: 0, fiber_g: 2, calories_kcal: 40 },
    version: 1,
  },
  {
    id: 'ING_GREEN_ONION',
    slug: 'green-onion',
    name: {
      en: 'Green Onion',
      it: 'Cipollotto',
      es: 'Cebolleta',
    },
    category: { main: 'vegetables', sub: 'alliums' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 2, carbs_g: 7, fat_g: 0, fiber_g: 3, calories_kcal: 32 },
    version: 1,
  },
  {
    id: 'ING_BELL_PEPPER_RED',
    slug: 'red-bell-pepper',
    name: {
      en: 'Red Bell Pepper',
      it: 'Peperone Rosso',
      es: 'Pimiento Rojo',
    },
    category: { main: 'vegetables', sub: 'peppers' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 6, fat_g: 0, fiber_g: 2, calories_kcal: 31 },
    version: 1,
  },
  {
    id: 'ING_BELL_PEPPER_YELLOW',
    slug: 'yellow-bell-pepper',
    name: {
      en: 'Yellow Bell Pepper',
      it: 'Peperone Giallo',
      es: 'Pimiento Amarillo',
    },
    category: { main: 'vegetables', sub: 'peppers' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 6, fat_g: 0, fiber_g: 1, calories_kcal: 27 },
    version: 1,
  },
  {
    id: 'ING_CARROT',
    slug: 'carrot',
    name: {
      en: 'Carrot',
      it: 'Carota',
      es: 'Zanahoria',
    },
    category: { main: 'vegetables', sub: 'root' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 10, fat_g: 0, fiber_g: 3, calories_kcal: 41 },
    version: 1,
  },
  {
    id: 'ING_RADISH',
    slug: 'radish',
    name: {
      en: 'Radish',
      it: 'Ravanello',
      es: 'Rábano',
    },
    category: { main: 'vegetables', sub: 'root' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 1 },
    nutrition: { protein_g: 1, carbs_g: 3, fat_g: 0, fiber_g: 2, calories_kcal: 16 },
    version: 1,
  },
  {
    id: 'ING_CELERY',
    slug: 'celery',
    name: {
      en: 'Celery',
      it: 'Sedano',
      es: 'Apio',
    },
    category: { main: 'vegetables', sub: 'stalks' },
    allergens: { celery: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 3, fat_g: 0, fiber_g: 2, calories_kcal: 16 },
    version: 1,
  },
  {
    id: 'ING_AVOCADO',
    slug: 'avocado',
    name: {
      en: 'Avocado',
      it: 'Avocado',
      es: 'Aguacate',
    },
    category: { main: 'vegetables', sub: 'fruit_vegetables' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 2, carbs_g: 9, fat_g: 15, fiber_g: 7, calories_kcal: 160 },
    version: 1,
  },
  {
    id: 'ING_CORN',
    slug: 'corn-kernels',
    name: {
      en: 'Corn Kernels',
      it: 'Mais',
      es: 'Maíz',
    },
    category: { main: 'vegetables', sub: 'grains' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 19, fat_g: 1, fiber_g: 2, calories_kcal: 86 },
    version: 1,
  },
  {
    id: 'ING_BEETS',
    slug: 'beets',
    name: {
      en: 'Beets',
      it: 'Barbabietole',
      es: 'Remolacha',
    },
    category: { main: 'vegetables', sub: 'root' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 2, carbs_g: 10, fat_g: 0, fiber_g: 3, calories_kcal: 43 },
    version: 1,
  },
  {
    id: 'ING_GREEN_BEANS',
    slug: 'green-beans',
    name: {
      en: 'Green Beans',
      it: 'Fagiolini',
      es: 'Judías Verdes',
    },
    category: { main: 'vegetables', sub: 'beans' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 2, carbs_g: 7, fat_g: 0, fiber_g: 3, calories_kcal: 31 },
    version: 1,
  },
  {
    id: 'ING_ARTICHOKE_HEARTS',
    slug: 'artichoke-hearts',
    name: {
      en: 'Artichoke Hearts',
      it: 'Cuori di Carciofo',
      es: 'Corazones de Alcachofa',
    },
    category: { main: 'vegetables', sub: 'specialty' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 11, fat_g: 0, fiber_g: 5, calories_kcal: 47 },
    version: 1,
  },
  {
    id: 'ING_SUN_DRIED_TOMATOES',
    slug: 'sun-dried-tomatoes',
    name: {
      en: 'Sun-Dried Tomatoes',
      it: 'Pomodori Secchi',
      es: 'Tomates Secos',
    },
    category: { main: 'vegetables', sub: 'tomatoes' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 6, carbs_g: 44, fat_g: 3, fiber_g: 7, calories_kcal: 213 },
    version: 1,
  },
  {
    id: 'ING_EDAMAME',
    slug: 'edamame',
    name: {
      en: 'Edamame',
      it: 'Edamame',
      es: 'Edamame',
    },
    description: { en: 'Young soybeans in the pod' },
    category: { main: 'vegetables', sub: 'beans' },
    allergens: { soy: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 11, carbs_g: 10, fat_g: 5, fiber_g: 5, calories_kcal: 121 },
    version: 1,
  },
  {
    id: 'ING_BEAN_SPROUTS',
    slug: 'bean-sprouts',
    name: {
      en: 'Bean Sprouts',
      it: 'Germogli di Soia',
      es: 'Brotes de Soja',
    },
    category: { main: 'vegetables', sub: 'sprouts' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 6, fat_g: 0, fiber_g: 2, calories_kcal: 31 },
    version: 1,
  },
  {
    id: 'ING_GREEN_PAPAYA',
    slug: 'green-papaya',
    name: {
      en: 'Green Papaya',
      it: 'Papaya Verde',
      es: 'Papaya Verde',
    },
    description: { en: 'Unripe papaya used in Thai salads' },
    category: { main: 'vegetables', sub: 'fruit_vegetables' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 10, fat_g: 0, fiber_g: 2, calories_kcal: 43 },
    version: 1,
  },

  // ============================================================================
  // FRUITS
  // ============================================================================
  {
    id: 'ING_APPLE_GREEN',
    slug: 'green-apple',
    name: {
      en: 'Green Apple',
      it: 'Mela Verde',
      es: 'Manzana Verde',
    },
    category: { main: 'fruits', sub: 'pome' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 0, carbs_g: 14, fat_g: 0, fiber_g: 2, calories_kcal: 52 },
    version: 1,
  },
  {
    id: 'ING_GRAPES_RED',
    slug: 'red-grapes',
    name: {
      en: 'Red Grapes',
      it: 'Uva Rossa',
      es: 'Uvas Rojas',
    },
    category: { main: 'fruits', sub: 'berries' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 18, fat_g: 0, fiber_g: 1, calories_kcal: 69 },
    version: 1,
  },
  {
    id: 'ING_ORANGE_SEGMENTS',
    slug: 'orange-segments',
    name: {
      en: 'Orange Segments',
      it: 'Spicchi di Arancia',
      es: 'Gajos de Naranja',
    },
    category: { main: 'fruits', sub: 'citrus' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 12, fat_g: 0, fiber_g: 2, calories_kcal: 47 },
    version: 1,
  },
  {
    id: 'ING_MANGO',
    slug: 'mango',
    name: {
      en: 'Mango',
      it: 'Mango',
      es: 'Mango',
    },
    category: { main: 'fruits', sub: 'tropical' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 15, fat_g: 0, fiber_g: 2, calories_kcal: 60 },
    version: 1,
  },
  {
    id: 'ING_POMEGRANATE_SEEDS',
    slug: 'pomegranate-seeds',
    name: {
      en: 'Pomegranate Seeds',
      it: 'Semi di Melograno',
      es: 'Semillas de Granada',
    },
    category: { main: 'fruits', sub: 'berries' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 2, carbs_g: 19, fat_g: 1, fiber_g: 4, calories_kcal: 83 },
    version: 1,
  },
  {
    id: 'ING_CRANBERRIES_DRIED',
    slug: 'dried-cranberries',
    name: {
      en: 'Dried Cranberries',
      it: 'Mirtilli Rossi Essiccati',
      es: 'Arándanos Secos',
    },
    category: { main: 'fruits', sub: 'dried' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 0, carbs_g: 82, fat_g: 1, fiber_g: 6, calories_kcal: 308 },
    version: 1,
  },
  {
    id: 'ING_PINEAPPLE',
    slug: 'pineapple',
    name: {
      en: 'Pineapple',
      it: 'Ananas',
      es: 'Piña',
    },
    category: { main: 'fruits', sub: 'tropical' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 13, fat_g: 0, fiber_g: 1, calories_kcal: 50 },
    version: 1,
  },

  // ============================================================================
  // PROTEINS
  // ============================================================================
  {
    id: 'ING_CHICKEN_GRILLED',
    slug: 'grilled-chicken',
    name: {
      en: 'Grilled Chicken Breast',
      it: 'Petto di Pollo alla Griglia',
      es: 'Pechuga de Pollo a la Plancha',
    },
    category: { main: 'proteins', sub: 'poultry' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 31, carbs_g: 0, fat_g: 4, fiber_g: 0, calories_kcal: 165 },
    version: 1,
  },
  {
    id: 'ING_CHICKEN_CRISPY',
    slug: 'crispy-chicken',
    name: {
      en: 'Crispy Fried Chicken',
      it: 'Pollo Croccante',
      es: 'Pollo Crujiente',
    },
    category: { main: 'proteins', sub: 'poultry' },
    allergens: { gluten: true },
    intolerances: { gluten: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: false,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 26, carbs_g: 10, fat_g: 14, fiber_g: 0, calories_kcal: 260 },
    version: 1,
  },
  {
    id: 'ING_STEAK_SLICED',
    slug: 'sliced-steak',
    name: {
      en: 'Sliced Grilled Steak',
      it: 'Tagliata di Manzo',
      es: 'Bistec en Rodajas',
    },
    category: { main: 'proteins', sub: 'beef' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 26, carbs_g: 0, fat_g: 15, fiber_g: 0, calories_kcal: 250 },
    version: 1,
  },
  {
    id: 'ING_SALMON_GRILLED',
    slug: 'grilled-salmon',
    name: {
      en: 'Grilled Salmon',
      it: 'Salmone alla Griglia',
      es: 'Salmón a la Plancha',
    },
    category: { main: 'proteins', sub: 'fish' },
    allergens: { fish: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 25, carbs_g: 0, fat_g: 13, fiber_g: 0, calories_kcal: 208 },
    version: 1,
  },
  {
    id: 'ING_TUNA_SEARED',
    slug: 'seared-tuna',
    name: {
      en: 'Seared Ahi Tuna',
      it: 'Tonno Scottato',
      es: 'Atún Sellado',
    },
    category: { main: 'proteins', sub: 'fish' },
    allergens: { fish: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 29, carbs_g: 0, fat_g: 1, fiber_g: 0, calories_kcal: 130 },
    version: 1,
  },
  {
    id: 'ING_TUNA_RAW',
    slug: 'raw-tuna',
    name: {
      en: 'Raw Ahi Tuna',
      it: 'Tonno Crudo',
      es: 'Atún Crudo',
    },
    description: { en: 'Sashimi-grade tuna for poke bowls' },
    category: { main: 'proteins', sub: 'fish' },
    allergens: { fish: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 29, carbs_g: 0, fat_g: 1, fiber_g: 0, calories_kcal: 130 },
    version: 1,
  },
  {
    id: 'ING_SALMON_RAW',
    slug: 'raw-salmon',
    name: {
      en: 'Raw Salmon',
      it: 'Salmone Crudo',
      es: 'Salmón Crudo',
    },
    description: { en: 'Sashimi-grade salmon for poke bowls' },
    category: { main: 'proteins', sub: 'fish' },
    allergens: { fish: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 25, carbs_g: 0, fat_g: 13, fiber_g: 0, calories_kcal: 208 },
    version: 1,
  },
  {
    id: 'ING_SHRIMP',
    slug: 'shrimp',
    name: {
      en: 'Shrimp',
      it: 'Gamberetti',
      es: 'Camarones',
    },
    category: { main: 'proteins', sub: 'seafood' },
    allergens: { shellfish: true, crustaceans: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 24, carbs_g: 0, fat_g: 1, fiber_g: 0, calories_kcal: 99 },
    version: 1,
  },
  {
    id: 'ING_CALAMARI',
    slug: 'calamari',
    name: {
      en: 'Calamari',
      it: 'Calamari',
      es: 'Calamares',
    },
    category: { main: 'proteins', sub: 'seafood' },
    allergens: { mollusks: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 18, carbs_g: 3, fat_g: 1, fiber_g: 0, calories_kcal: 92 },
    version: 1,
  },
  {
    id: 'ING_CRAB_MEAT',
    slug: 'crab-meat',
    name: {
      en: 'Crab Meat',
      it: 'Polpa di Granchio',
      es: 'Carne de Cangrejo',
    },
    category: { main: 'proteins', sub: 'seafood' },
    allergens: { shellfish: true, crustaceans: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 20, carbs_g: 0, fat_g: 1, fiber_g: 0, calories_kcal: 97 },
    version: 1,
  },
  {
    id: 'ING_TOFU',
    slug: 'tofu',
    name: {
      en: 'Tofu',
      it: 'Tofu',
      es: 'Tofu',
    },
    category: { main: 'proteins', sub: 'plant_based' },
    allergens: { soy: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 8, carbs_g: 2, fat_g: 4, fiber_g: 1, calories_kcal: 76 },
    version: 1,
  },
  {
    id: 'ING_TEMPEH',
    slug: 'tempeh',
    name: {
      en: 'Tempeh',
      it: 'Tempeh',
      es: 'Tempeh',
    },
    description: { en: 'Fermented soybean protein' },
    category: { main: 'proteins', sub: 'plant_based' },
    allergens: { soy: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 19, carbs_g: 9, fat_g: 11, fiber_g: 0, calories_kcal: 193 },
    version: 1,
  },
  {
    id: 'ING_HARD_BOILED_EGG',
    slug: 'hard-boiled-egg',
    name: {
      en: 'Hard-Boiled Egg',
      it: 'Uovo Sodo',
      es: 'Huevo Duro',
    },
    category: { main: 'proteins', sub: 'eggs' },
    allergens: { eggs: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 6, carbs_g: 1, fat_g: 5, fiber_g: 0, calories_kcal: 78 },
    version: 1,
  },
  {
    id: 'ING_BACON',
    slug: 'bacon',
    name: {
      en: 'Bacon',
      it: 'Bacon',
      es: 'Tocino',
    },
    category: { main: 'proteins', sub: 'pork' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 37, carbs_g: 1, fat_g: 42, fiber_g: 0, calories_kcal: 541 },
    version: 1,
  },
  {
    id: 'ING_PROSCIUTTO',
    slug: 'prosciutto',
    name: {
      en: 'Prosciutto',
      it: 'Prosciutto Crudo',
      es: 'Jamón Serrano',
    },
    category: { main: 'proteins', sub: 'pork' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: false,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 26, carbs_g: 0, fat_g: 18, fiber_g: 0, calories_kcal: 270 },
    version: 1,
  },
  {
    id: 'ING_ANCHOVIES',
    slug: 'anchovies',
    name: {
      en: 'Anchovies',
      it: 'Acciughe',
      es: 'Anchoas',
    },
    category: { main: 'proteins', sub: 'fish' },
    allergens: { fish: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 29, carbs_g: 0, fat_g: 5, fiber_g: 0, calories_kcal: 131 },
    version: 1,
  },
  {
    id: 'ING_TUNA_CANNED',
    slug: 'canned-tuna',
    name: {
      en: 'Canned Tuna',
      it: 'Tonno in Scatola',
      es: 'Atún en Lata',
    },
    category: { main: 'proteins', sub: 'fish' },
    allergens: { fish: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 26, carbs_g: 0, fat_g: 1, fiber_g: 0, calories_kcal: 116 },
    version: 1,
  },

  // ============================================================================
  // CHEESES
  // ============================================================================
  {
    id: 'ING_FETA_CHEESE',
    slug: 'feta-cheese',
    name: {
      en: 'Feta Cheese',
      it: 'Feta',
      es: 'Queso Feta',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 14, carbs_g: 4, fat_g: 21, fiber_g: 0, calories_kcal: 264 },
    version: 1,
  },
  {
    id: 'ING_GOAT_CHEESE',
    slug: 'goat-cheese',
    name: {
      en: 'Goat Cheese',
      it: 'Formaggio di Capra',
      es: 'Queso de Cabra',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 22, carbs_g: 0, fat_g: 30, fiber_g: 0, calories_kcal: 364 },
    version: 1,
  },
  {
    id: 'ING_BLUE_CHEESE',
    slug: 'blue-cheese',
    name: {
      en: 'Blue Cheese',
      it: 'Gorgonzola',
      es: 'Queso Azul',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 21, carbs_g: 2, fat_g: 29, fiber_g: 0, calories_kcal: 353 },
    version: 1,
  },
  {
    id: 'ING_PARMESAN_SHAVED',
    slug: 'shaved-parmesan',
    name: {
      en: 'Shaved Parmesan',
      it: 'Scaglie di Parmigiano',
      es: 'Virutas de Parmesano',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 36, carbs_g: 4, fat_g: 26, fiber_g: 0, calories_kcal: 392 },
    version: 1,
  },
  {
    id: 'ING_MOZZARELLA_FRESH',
    slug: 'fresh-mozzarella',
    name: {
      en: 'Fresh Mozzarella',
      it: 'Mozzarella Fresca',
      es: 'Mozzarella Fresca',
    },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 22, carbs_g: 2, fat_g: 22, fiber_g: 0, calories_kcal: 280 },
    version: 1,
  },
  {
    id: 'ING_BURRATA',
    slug: 'burrata',
    name: {
      en: 'Burrata',
      it: 'Burrata',
      es: 'Burrata',
    },
    description: { en: 'Creamy Italian cheese with stracciatella center' },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 18, carbs_g: 1, fat_g: 25, fiber_g: 0, calories_kcal: 300 },
    version: 1,
  },
  {
    id: 'ING_HALLOUMI',
    slug: 'halloumi',
    name: {
      en: 'Halloumi',
      it: 'Halloumi',
      es: 'Halloumi',
    },
    description: { en: 'Grillable Cypriot cheese' },
    category: { main: 'dairy', sub: 'cheese' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 21, carbs_g: 3, fat_g: 25, fiber_g: 0, calories_kcal: 321 },
    version: 1,
  },

  // ============================================================================
  // NUTS & SEEDS
  // ============================================================================
  {
    id: 'ING_WALNUTS',
    slug: 'walnuts',
    name: {
      en: 'Walnuts',
      it: 'Noci',
      es: 'Nueces',
    },
    category: { main: 'nuts_seeds', sub: 'nuts' },
    allergens: { tree_nuts: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: false,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 15, carbs_g: 14, fat_g: 65, fiber_g: 7, calories_kcal: 654 },
    version: 1,
  },
  {
    id: 'ING_ALMONDS_SLICED',
    slug: 'sliced-almonds',
    name: {
      en: 'Sliced Almonds',
      it: 'Mandorle a Lamelle',
      es: 'Almendras en Láminas',
    },
    category: { main: 'nuts_seeds', sub: 'nuts' },
    allergens: { tree_nuts: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: false,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 21, carbs_g: 22, fat_g: 50, fiber_g: 12, calories_kcal: 579 },
    version: 1,
  },
  {
    id: 'ING_PINE_NUTS',
    slug: 'pine-nuts',
    name: {
      en: 'Pine Nuts',
      it: 'Pinoli',
      es: 'Piñones',
    },
    category: { main: 'nuts_seeds', sub: 'nuts' },
    allergens: { tree_nuts: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: false,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 14, carbs_g: 13, fat_g: 68, fiber_g: 4, calories_kcal: 673 },
    version: 1,
  },
  {
    id: 'ING_CASHEWS',
    slug: 'cashews',
    name: {
      en: 'Cashews',
      it: 'Anacardi',
      es: 'Anacardos',
    },
    category: { main: 'nuts_seeds', sub: 'nuts' },
    allergens: { tree_nuts: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: false,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 18, carbs_g: 30, fat_g: 44, fiber_g: 3, calories_kcal: 553 },
    version: 1,
  },
  {
    id: 'ING_PEANUTS',
    slug: 'peanuts',
    name: {
      en: 'Peanuts',
      it: 'Arachidi',
      es: 'Cacahuetes',
    },
    category: { main: 'nuts_seeds', sub: 'legumes' },
    allergens: { peanuts: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: false,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 26, carbs_g: 16, fat_g: 49, fiber_g: 9, calories_kcal: 567 },
    version: 1,
  },
  {
    id: 'ING_SUNFLOWER_SEEDS',
    slug: 'sunflower-seeds',
    name: {
      en: 'Sunflower Seeds',
      it: 'Semi di Girasole',
      es: 'Semillas de Girasol',
    },
    category: { main: 'nuts_seeds', sub: 'seeds' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 21, carbs_g: 20, fat_g: 51, fiber_g: 9, calories_kcal: 584 },
    version: 1,
  },
  {
    id: 'ING_PUMPKIN_SEEDS',
    slug: 'pumpkin-seeds',
    name: {
      en: 'Pumpkin Seeds',
      it: 'Semi di Zucca',
      es: 'Semillas de Calabaza',
    },
    category: { main: 'nuts_seeds', sub: 'seeds' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 30, carbs_g: 11, fat_g: 49, fiber_g: 6, calories_kcal: 559 },
    version: 1,
  },
  {
    id: 'ING_SESAME_SEEDS',
    slug: 'sesame-seeds',
    name: {
      en: 'Sesame Seeds',
      it: 'Semi di Sesamo',
      es: 'Semillas de Sésamo',
    },
    category: { main: 'nuts_seeds', sub: 'seeds' },
    allergens: { sesame: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 17, carbs_g: 23, fat_g: 50, fiber_g: 12, calories_kcal: 573 },
    version: 1,
  },
  {
    id: 'ING_CHIA_SEEDS',
    slug: 'chia-seeds',
    name: {
      en: 'Chia Seeds',
      it: 'Semi di Chia',
      es: 'Semillas de Chía',
    },
    category: { main: 'nuts_seeds', sub: 'seeds' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 17, carbs_g: 42, fat_g: 31, fiber_g: 34, calories_kcal: 486 },
    version: 1,
  },
  {
    id: 'ING_HEMP_SEEDS',
    slug: 'hemp-seeds',
    name: {
      en: 'Hemp Seeds',
      it: 'Semi di Canapa',
      es: 'Semillas de Cáñamo',
    },
    category: { main: 'nuts_seeds', sub: 'seeds' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 32, carbs_g: 9, fat_g: 49, fiber_g: 4, calories_kcal: 553 },
    version: 1,
  },

  // ============================================================================
  // GRAINS & LEGUMES
  // ============================================================================
  {
    id: 'ING_QUINOA',
    slug: 'quinoa',
    name: {
      en: 'Quinoa',
      it: 'Quinoa',
      es: 'Quinoa',
    },
    category: { main: 'grains', sub: 'pseudograins' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 14, carbs_g: 64, fat_g: 6, fiber_g: 7, calories_kcal: 368 },
    version: 1,
  },
  {
    id: 'ING_BULGUR',
    slug: 'bulgur',
    name: {
      en: 'Bulgur Wheat',
      it: 'Bulgur',
      es: 'Bulgur',
    },
    category: { main: 'grains', sub: 'wheat' },
    allergens: { gluten: true, wheat: true },
    intolerances: { gluten: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: false,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 12, carbs_g: 76, fat_g: 1, fiber_g: 18, calories_kcal: 342 },
    version: 1,
  },
  {
    id: 'ING_FARRO',
    slug: 'farro',
    name: {
      en: 'Farro',
      it: 'Farro',
      es: 'Farro',
    },
    category: { main: 'grains', sub: 'wheat' },
    allergens: { gluten: true, wheat: true },
    intolerances: { gluten: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: false,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 15, carbs_g: 72, fat_g: 3, fiber_g: 11, calories_kcal: 339 },
    version: 1,
  },
  {
    id: 'ING_BROWN_RICE',
    slug: 'brown-rice',
    name: {
      en: 'Brown Rice',
      it: 'Riso Integrale',
      es: 'Arroz Integral',
    },
    category: { main: 'grains', sub: 'rice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 8, carbs_g: 77, fat_g: 3, fiber_g: 4, calories_kcal: 370 },
    version: 1,
  },
  {
    id: 'ING_SUSHI_RICE',
    slug: 'sushi-rice',
    name: {
      en: 'Sushi Rice',
      it: 'Riso per Sushi',
      es: 'Arroz para Sushi',
    },
    category: { main: 'grains', sub: 'rice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 7, carbs_g: 78, fat_g: 1, fiber_g: 1, calories_kcal: 350 },
    version: 1,
  },
  {
    id: 'ING_CHICKPEAS',
    slug: 'chickpeas',
    name: {
      en: 'Chickpeas',
      it: 'Ceci',
      es: 'Garbanzos',
    },
    category: { main: 'legumes', sub: 'beans' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 19, carbs_g: 61, fat_g: 6, fiber_g: 17, calories_kcal: 364 },
    version: 1,
  },
  {
    id: 'ING_BLACK_BEANS',
    slug: 'black-beans',
    name: {
      en: 'Black Beans',
      it: 'Fagioli Neri',
      es: 'Frijoles Negros',
    },
    category: { main: 'legumes', sub: 'beans' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 21, carbs_g: 63, fat_g: 1, fiber_g: 16, calories_kcal: 341 },
    version: 1,
  },
  {
    id: 'ING_LENTILS',
    slug: 'lentils',
    name: {
      en: 'Lentils',
      it: 'Lenticchie',
      es: 'Lentejas',
    },
    category: { main: 'legumes', sub: 'lentils' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 25, carbs_g: 60, fat_g: 1, fiber_g: 31, calories_kcal: 352 },
    version: 1,
  },
  {
    id: 'ING_CANNELLINI_BEANS',
    slug: 'cannellini-beans',
    name: {
      en: 'Cannellini Beans',
      it: 'Fagioli Cannellini',
      es: 'Alubias Blancas',
    },
    category: { main: 'legumes', sub: 'beans' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 21, carbs_g: 60, fat_g: 1, fiber_g: 15, calories_kcal: 333 },
    version: 1,
  },

  // ============================================================================
  // BREAD & CROUTONS
  // ============================================================================
  {
    id: 'ING_CROUTONS',
    slug: 'croutons',
    name: {
      en: 'Croutons',
      it: 'Crostini',
      es: 'Croutones',
    },
    category: { main: 'bread', sub: 'croutons' },
    allergens: { gluten: true, wheat: true },
    intolerances: { gluten: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: false,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 10, carbs_g: 73, fat_g: 6, fiber_g: 3, calories_kcal: 407 },
    version: 1,
  },
  {
    id: 'ING_PITA_CHIPS',
    slug: 'pita-chips',
    name: {
      en: 'Pita Chips',
      it: 'Chips di Pita',
      es: 'Chips de Pita',
    },
    category: { main: 'bread', sub: 'chips' },
    allergens: { gluten: true, wheat: true },
    intolerances: { gluten: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: false,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 9, carbs_g: 68, fat_g: 10, fiber_g: 3, calories_kcal: 400 },
    version: 1,
  },
  {
    id: 'ING_CIABATTA_CUBES',
    slug: 'ciabatta-cubes',
    name: {
      en: 'Ciabatta Bread Cubes',
      it: 'Cubetti di Ciabatta',
      es: 'Cubos de Ciabatta',
    },
    description: { en: 'For Panzanella salad' },
    category: { main: 'bread', sub: 'cubes' },
    allergens: { gluten: true, wheat: true },
    intolerances: { gluten: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: false,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 9, carbs_g: 50, fat_g: 3, fiber_g: 2, calories_kcal: 271 },
    version: 1,
  },
  {
    id: 'ING_WONTON_STRIPS',
    slug: 'wonton-strips',
    name: {
      en: 'Crispy Wonton Strips',
      it: 'Strisce di Wonton Croccanti',
      es: 'Tiras de Wonton Crujientes',
    },
    category: { main: 'bread', sub: 'asian' },
    allergens: { gluten: true, wheat: true },
    intolerances: { gluten: true },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: false,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 8, carbs_g: 55, fat_g: 15, fiber_g: 2, calories_kcal: 380 },
    version: 1,
  },

  // ============================================================================
  // OLIVES & PICKLES
  // ============================================================================
  {
    id: 'ING_KALAMATA_OLIVES',
    slug: 'kalamata-olives',
    name: {
      en: 'Kalamata Olives',
      it: 'Olive Kalamata',
      es: 'Aceitunas Kalamata',
    },
    category: { main: 'condiments', sub: 'olives' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 4, fat_g: 15, fiber_g: 3, calories_kcal: 145 },
    version: 1,
  },
  {
    id: 'ING_BLACK_OLIVES',
    slug: 'black-olives',
    name: {
      en: 'Black Olives',
      it: 'Olive Nere',
      es: 'Aceitunas Negras',
    },
    category: { main: 'condiments', sub: 'olives' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 6, fat_g: 11, fiber_g: 3, calories_kcal: 115 },
    version: 1,
  },
  {
    id: 'ING_CAPERS',
    slug: 'capers',
    name: {
      en: 'Capers',
      it: 'Capperi',
      es: 'Alcaparras',
    },
    category: { main: 'condiments', sub: 'pickled' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 2, carbs_g: 5, fat_g: 1, fiber_g: 3, calories_kcal: 23 },
    version: 1,
  },
  {
    id: 'ING_PICKLED_ONIONS',
    slug: 'pickled-onions',
    name: {
      en: 'Pickled Onions',
      it: 'Cipolle Sottaceto',
      es: 'Cebollas Encurtidas',
    },
    category: { main: 'condiments', sub: 'pickled' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 1, carbs_g: 5, fat_g: 0, fiber_g: 1, calories_kcal: 24 },
    version: 1,
  },
  {
    id: 'ING_PICKLED_GINGER',
    slug: 'pickled-ginger',
    name: {
      en: 'Pickled Ginger',
      it: 'Zenzero Sottaceto',
      es: 'Jengibre Encurtido',
    },
    description: { en: 'For poke bowls and Asian salads' },
    category: { main: 'condiments', sub: 'pickled' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 1 },
    nutrition: { protein_g: 0, carbs_g: 4, fat_g: 0, fiber_g: 0, calories_kcal: 20 },
    version: 1,
  },

  // ============================================================================
  // HERBS & GARNISHES
  // ============================================================================
  {
    id: 'ING_FRESH_BASIL',
    slug: 'fresh-basil',
    name: {
      en: 'Fresh Basil',
      it: 'Basilico Fresco',
      es: 'Albahaca Fresca',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 3, fat_g: 1, fiber_g: 2, calories_kcal: 23 },
    version: 1,
  },
  {
    id: 'ING_FRESH_PARSLEY',
    slug: 'fresh-parsley',
    name: {
      en: 'Fresh Parsley',
      it: 'Prezzemolo Fresco',
      es: 'Perejil Fresco',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 6, fat_g: 1, fiber_g: 3, calories_kcal: 36 },
    version: 1,
  },
  {
    id: 'ING_FRESH_MINT',
    slug: 'fresh-mint',
    name: {
      en: 'Fresh Mint',
      it: 'Menta Fresca',
      es: 'Menta Fresca',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 4, carbs_g: 9, fat_g: 1, fiber_g: 8, calories_kcal: 44 },
    version: 1,
  },
  {
    id: 'ING_CILANTRO',
    slug: 'cilantro',
    name: {
      en: 'Cilantro',
      it: 'Coriandolo',
      es: 'Cilantro',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 2, carbs_g: 4, fat_g: 1, fiber_g: 3, calories_kcal: 23 },
    version: 1,
  },
  {
    id: 'ING_FRESH_DILL',
    slug: 'fresh-dill',
    name: {
      en: 'Fresh Dill',
      it: 'Aneto Fresco',
      es: 'Eneldo Fresco',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 4, carbs_g: 7, fat_g: 1, fiber_g: 2, calories_kcal: 43 },
    version: 1,
  },
  {
    id: 'ING_CHIVES',
    slug: 'chives',
    name: {
      en: 'Chives',
      it: 'Erba Cipollina',
      es: 'Cebollino',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 4, fat_g: 1, fiber_g: 3, calories_kcal: 30 },
    version: 1,
  },
  {
    id: 'ING_THAI_BASIL',
    slug: 'thai-basil',
    name: {
      en: 'Thai Basil',
      it: 'Basilico Thailandese',
      es: 'Albahaca Tailandesa',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 3, carbs_g: 3, fat_g: 1, fiber_g: 2, calories_kcal: 23 },
    version: 1,
  },
  {
    id: 'ING_OREGANO_DRIED',
    slug: 'dried-oregano',
    name: {
      en: 'Dried Oregano',
      it: 'Origano Secco',
      es: 'Orégano Seco',
    },
    category: { main: 'herbs', sub: 'dried' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 9, carbs_g: 69, fat_g: 4, fiber_g: 43, calories_kcal: 265 },
    version: 1,
  },
  {
    id: 'ING_SUMAC',
    slug: 'sumac',
    name: {
      en: 'Sumac',
      it: 'Sommacco',
      es: 'Zumaque',
    },
    description: { en: 'Tangy Middle Eastern spice' },
    category: { main: 'spices', sub: 'middle_eastern' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 5, carbs_g: 71, fat_g: 8, fiber_g: 0, calories_kcal: 268 },
    version: 1,
  },
  {
    id: 'ING_ZAATAR',
    slug: 'zaatar',
    name: {
      en: 'Za\'atar',
      it: 'Za\'atar',
      es: 'Za\'atar',
    },
    description: { en: 'Middle Eastern herb blend with thyme, sesame, sumac' },
    category: { main: 'spices', sub: 'blends' },
    allergens: { sesame: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 8, carbs_g: 50, fat_g: 20, fiber_g: 15, calories_kcal: 380 },
    version: 1,
  },
  {
    id: 'ING_FURIKAKE',
    slug: 'furikake',
    name: {
      en: 'Furikake',
      it: 'Furikake',
      es: 'Furikake',
    },
    description: { en: 'Japanese rice seasoning with seaweed and sesame' },
    category: { main: 'spices', sub: 'japanese' },
    allergens: { sesame: true, fish: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 15, carbs_g: 40, fat_g: 10, fiber_g: 5, calories_kcal: 300 },
    version: 1,
  },
  {
    id: 'ING_NORI_SEAWEED',
    slug: 'nori-seaweed',
    name: {
      en: 'Nori Seaweed',
      it: 'Alga Nori',
      es: 'Alga Nori',
    },
    category: { main: 'seaweed', sub: 'sheets' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: { protein_g: 6, carbs_g: 5, fat_g: 1, fiber_g: 1, calories_kcal: 35 },
    version: 1,
  },
];

export default saladIngredients;
