-- ============================================================================
-- GUDBRO Salads Database - Batch 02
-- Salads 6 to 10 of 52
-- ============================================================================
-- Salads in this batch:
--   - Chef's Salad (chefs-salad)
--   - Wedge Salad (wedge-salad)
--   - Spinach Salad (spinach-salad)
--   - Garden Salad (garden-salad)
--   - House Salad (house-salad)
-- ============================================================================

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'a751368e-5a32-44ee-9e27-b86924687b0b',
    'chefs-salad',
    'chefs-salad',
    '{"en":"Chef''s Salad","it":"Insalata dello Chef","es":"Ensalada del Chef"}'::jsonb,
    '{"en":"Classic deli-style salad with strips of ham, turkey, cheese, and hard-boiled eggs on crisp greens","it":"Classica insalata da deli con strisce di prosciutto, tacchino, formaggio e uova sode su verdure croccanti","es":"Ensalada clásica estilo deli con tiras de jamón, pavo, queso y huevos duros sobre verduras crujientes"}'::jsonb,
    NULL,
    'classic',
    'classic',
    '{"american","deli","protein-rich","hearty","classic"}',
    '{"country":"United States","country_code":"US","year_created":"1940s"}'::jsonb,
    '{"story":{"en":"Originated in American restaurants as a way to use leftover deli meats and cheeses in an elegant presentation","it":"Nata nei ristoranti americani come modo per utilizzare avanzi di salumi e formaggi in una presentazione elegante","es":"Se originó en restaurantes estadounidenses como una forma de usar sobras de carnes y quesos en una presentación elegante"}}'::jsonb,
    'iceberg',
    'none',
    '{"chicken_grilled","shrimp"}',
    'thousand-island',
    '{"ranch-dressing","blue-cheese-dressing","french-dressing"}',
    true,
    '[{"ingredient_id":"ING_HAM","quantity":{"amount":60,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_TURKEY","quantity":{"amount":60,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_SWISS_CHEESE","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_CHEDDAR","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_EGG","quantity":{"amount":2,"unit":"piece"}},{"ingredient_id":"ING_ICEBERG_LETTUCE","quantity":{"amount":120,"unit":"g"}},{"ingredient_id":"ING_TOMATO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":20,"unit":"g"}}]'::jsonb,
    '[{"ingredient_id":"ING_CROUTONS"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["regular","large"],"temperature":"cold","presentation":"composed"}'::jsonb,
    '{"profile":["savory","smoky","mild","satisfying","fresh"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["eggs","milk"],"calories_estimate":480,"protein_g":35,"fiber_g":3}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":true,"extra_dressing":true,"make_vegan":false,"make_gluten_free":true}'::jsonb,
    NULL,
    72,
    '{"lunch","deli","protein-seekers"}',
    '{"soups":["tomato-soup","chicken-noodle"],"breads":["rye-bread","sourdough"],"drinks":["iced-tea","soda","beer"]}'::jsonb,
    '{"cobb-salad","antipasto-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'a99bb80d-fb55-41ef-978e-adfc68aa1df8',
    'wedge-salad',
    'wedge-salad',
    '{"en":"Wedge Salad","it":"Insalata a Spicchio","es":"Ensalada Wedge"}'::jsonb,
    '{"en":"Quarter wedge of crisp iceberg lettuce topped with creamy blue cheese dressing, bacon bits, and tomatoes","it":"Quarto di lattuga iceberg croccante con salsa al formaggio blu cremosa, pezzetti di bacon e pomodori","es":"Cuarto de lechuga iceberg crujiente con aderezo cremoso de queso azul, trocitos de bacon y tomates"}'::jsonb,
    NULL,
    'classic',
    'classic',
    '{"american","steakhouse","creamy","bacon","retro"}',
    '{"country":"United States","country_code":"US","year_created":"1950s"}'::jsonb,
    '{"story":{"en":"A steakhouse staple since the 1950s, the wedge salad represents the bold, simple approach to American dining","it":"Un classico delle steakhouse dagli anni ''50, l''insalata a spicchio rappresenta l''approccio audace e semplice della cucina americana","es":"Un clásico de los restaurantes de carnes desde los años 50, la ensalada wedge representa el enfoque audaz y simple de la cocina estadounidense"}}'::jsonb,
    'iceberg',
    'none',
    '{"chicken_grilled","steak","shrimp"}',
    'blue-cheese-dressing',
    '{"ranch-dressing","thousand-island"}',
    false,
    '[{"ingredient_id":"ING_ICEBERG_LETTUCE","quantity":{"amount":200,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_BLUE_CHEESE","quantity":{"amount":60,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_BACON","quantity":{"amount":50,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CHERRY_TOMATO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_CHIVES","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_BLUE_CHEESE","is_signature":true},{"ingredient_id":"ING_BACON","is_signature":true},{"ingredient_id":"ING_CHIVES"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["side","regular"],"temperature":"cold","presentation":"composed"}'::jsonb,
    '{"profile":["creamy","smoky","tangy","crunchy","bold"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":["milk","eggs"],"calories_estimate":380,"protein_g":15,"fiber_g":3}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":false,"extra_dressing":true,"make_vegan":false,"make_gluten_free":true}'::jsonb,
    NULL,
    78,
    '{"dinner","steakhouse","appetizer"}',
    '{"proteins":["ribeye","filet-mignon"],"drinks":["red-wine","craft-beer","martini"]}'::jsonb,
    '{"cobb-salad","chefs-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '84eea0da-cd82-45e4-9cbe-0fc00585dae3',
    'spinach-salad',
    'spinach-salad',
    '{"en":"Spinach Salad","it":"Insalata di Spinaci","es":"Ensalada de Espinacas"}'::jsonb,
    '{"en":"Fresh baby spinach with warm bacon dressing, mushrooms, hard-boiled eggs, and red onion","it":"Spinaci baby freschi con condimento caldo al bacon, funghi, uova sode e cipolla rossa","es":"Espinacas baby frescas con aderezo caliente de bacon, champiñones, huevos duros y cebolla roja"}'::jsonb,
    NULL,
    'classic',
    'classic',
    '{"american","warm-dressing","nutritious","iron-rich","classic"}',
    '{"country":"United States","country_code":"US","year_created":"1960s"}'::jsonb,
    NULL,
    'spinach',
    'eggs',
    '{"chicken_grilled","salmon","steak"}',
    'warm-bacon-dressing',
    '{"balsamic-vinaigrette","honey-mustard"}',
    false,
    '[{"ingredient_id":"ING_BABY_SPINACH","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_BACON","quantity":{"amount":50,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_MUSHROOM","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_EGG","quantity":{"amount":2,"unit":"piece"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":30,"unit":"g"}}]'::jsonb,
    '[{"ingredient_id":"ING_BACON","is_signature":true},{"ingredient_id":"ING_SUNFLOWER_SEEDS"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["side","regular","large"],"temperature":"warm","presentation":"tossed"}'::jsonb,
    '{"profile":["savory","smoky","earthy","tangy","warm"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["eggs"],"calories_estimate":340,"protein_g":18,"fiber_g":4}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":false,"extra_dressing":true,"make_vegan":false,"make_gluten_free":true}'::jsonb,
    NULL,
    74,
    '{"lunch","dinner","health-conscious"}',
    '{"soups":["mushroom-soup"],"breads":["crusty-bread"],"drinks":["red-wine","craft-beer"]}'::jsonb,
    '{"kale-salad","arugula-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '5db1e537-e5fb-4f65-b2ce-e3ac61119765',
    'garden-salad',
    'garden-salad',
    '{"en":"Garden Salad","it":"Insalata dell''Orto","es":"Ensalada de la Huerta"}'::jsonb,
    '{"en":"Simple, fresh mix of seasonal vegetables on crisp mixed greens with choice of dressing","it":"Semplice mix fresco di verdure di stagione su verdure miste croccanti con condimento a scelta","es":"Mezcla simple y fresca de verduras de temporada sobre hojas verdes crujientes con aderezo a elección"}'::jsonb,
    NULL,
    'classic',
    'classic',
    '{"simple","fresh","versatile","side-salad","everyday"}',
    '{"country":"United States","country_code":"US"}'::jsonb,
    NULL,
    'mixed_greens',
    'none',
    '{"chicken_grilled","tofu","shrimp","salmon"}',
    'ranch-dressing',
    '{"italian-dressing","balsamic-vinaigrette","french-dressing","thousand-island"}',
    true,
    '[{"ingredient_id":"ING_MIXED_GREENS","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_TOMATO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_CARROT","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_RED_CABBAGE","quantity":{"amount":20,"unit":"g"}}]'::jsonb,
    '[{"ingredient_id":"ING_CROUTONS"},{"ingredient_id":"ING_SUNFLOWER_SEEDS"}]'::jsonb,
    '{"default_portion":"side","available_portions":["side","regular","large"],"temperature":"cold","presentation":"tossed"}'::jsonb,
    '{"profile":["fresh","crisp","light","clean","refreshing"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":[],"calories_estimate":80,"protein_g":3,"fiber_g":4}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":true,"extra_dressing":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    85,
    '{"everyday","side-dish","light-meal","health-conscious"}',
    '{"soups":["any"],"breads":["any"],"proteins":["any"],"drinks":["any"]}'::jsonb,
    '{"house-salad","mixed-greens"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '66c03719-6a41-4b35-a58b-39feb551d90a',
    'house-salad',
    'house-salad',
    '{"en":"House Salad","it":"Insalata della Casa","es":"Ensalada de la Casa"}'::jsonb,
    '{"en":"Our signature blend of fresh greens with house-made vinaigrette and seasonal toppings","it":"La nostra miscela di verdure fresche con vinaigrette fatta in casa e condimenti di stagione","es":"Nuestra mezcla de verduras frescas con vinagreta casera y toppings de temporada"}'::jsonb,
    NULL,
    'signature',
    'signature',
    '{"signature","fresh","seasonal","versatile","house-special"}',
    '{"country":"International","country_code":"XX"}'::jsonb,
    NULL,
    'mixed_greens',
    'none',
    '{"chicken_grilled","salmon","shrimp","tofu"}',
    'house-vinaigrette',
    '{"balsamic-vinaigrette","ranch-dressing","lemon-olive-oil"}',
    true,
    '[{"ingredient_id":"ING_MIXED_GREENS","quantity":{"amount":120,"unit":"g"}},{"ingredient_id":"ING_CHERRY_TOMATO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_SHAVED_PARMESAN","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":15,"unit":"g"}}]'::jsonb,
    '[{"ingredient_id":"ING_SHAVED_PARMESAN"},{"ingredient_id":"ING_PINE_NUTS"}]'::jsonb,
    '{"default_portion":"side","available_portions":["side","regular","large"],"temperature":"cold","presentation":"tossed"}'::jsonb,
    '{"profile":["fresh","bright","balanced","clean"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":["milk","tree_nuts"],"calories_estimate":150,"protein_g":5,"fiber_g":3}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":true,"extra_dressing":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    80,
    '{"everyday","starter","light-meal"}',
    NULL,
    '{"garden-salad","mixed-greens"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();