-- ============================================================================
-- GUDBRO Salads Database - Batch 08
-- Salads 36 to 40 of 52
-- ============================================================================
-- Salads in this batch:
--   - Ahi Tuna Poke Bowl (ahi-tuna-poke-bowl)
--   - Salmon Poke Bowl (salmon-poke-bowl)
--   - Mediterranean Bowl (mediterranean-bowl)
--   - Acai Bowl (acai-bowl)
--   - Kale Superfood Bowl (kale-superfood-bowl)
-- ============================================================================

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'a036f8ab-fcc3-4c01-a838-1f189efc8740',
    'ahi-tuna-poke-bowl',
    'ahi-tuna-poke-bowl',
    '{"en":"Ahi Tuna Poke Bowl","it":"Poke Bowl di Tonno Ahi","es":"Poke Bowl de Atún Ahi"}'::jsonb,
    '{"en":"Hawaiian-style bowl with marinated ahi tuna, sushi rice, edamame, seaweed, and spicy mayo","it":"Ciotola hawaiana con tonno ahi marinato, riso sushi, edamame, alghe e maionese piccante","es":"Bol hawaiano con atún ahi marinado, arroz sushi, edamame, algas y mayonesa picante"}'::jsonb,
    '{"en":"Aloha in a Bowl","it":"Aloha in una Ciotola","es":"Aloha en un Bol"}'::jsonb,
    'trending',
    'poke',
    '{"hawaiian","raw-fish","healthy","umami","instagram-worthy"}',
    '{"country":"United States","country_code":"US","region":"Hawaii"}'::jsonb,
    '{"story":{"en":"Poke (pronounced POH-keh) means \"to slice\" in Hawaiian. It was originally fishermen''s snack made from reef fish trimmings","it":"Poke (pronunciato POH-keh) significa \"tagliare\" in hawaiano. Era originariamente lo spuntino dei pescatori fatto con ritagli di pesce di barriera","es":"Poke (pronunciado POH-keh) significa \"cortar\" en hawaiano. Era originalmente el snack de los pescadores hecho con recortes de pescado de arrecife"}}'::jsonb,
    'rice',
    'tuna_raw',
    '{"salmon","shrimp","tofu"}',
    'poke-sauce',
    '{"spicy-mayo","ponzu-dressing"}',
    false,
    '[{"ingredient_id":"ING_AHI_TUNA","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_SUSHI_RICE","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_EDAMAME","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_WAKAME","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_AVOCADO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_PICKLED_GINGER","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_GREEN_ONION","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_SOY_SAUCE","quantity":{"amount":2,"unit":"tbsp"}},{"ingredient_id":"ING_SESAME_OIL","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_SESAME_SEEDS","is_signature":true},{"ingredient_id":"ING_FURIKAKE"},{"ingredient_id":"ING_MASAGO"},{"ingredient_id":"ING_CRISPY_ONION"}]'::jsonb,
    '{"default_portion":"bowl","available_portions":["regular","large","bowl"],"temperature":"cold","presentation":"bowl"}'::jsonb,
    '{"profile":["umami","fresh","savory","oceanic","rich"],"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["fish","soy","sesame"],"calories_estimate":520,"protein_g":38,"fiber_g":6}'::jsonb,
    '{"add_protein":false,"substitute_base":true,"extra_dressing":true,"make_vegan":false,"make_gluten_free":true}'::jsonb,
    NULL,
    94,
    '{"lunch","dinner","sushi-lovers","health-conscious"}',
    '{"drinks":["sake","japanese-beer","coconut-water","green-tea"]}'::jsonb,
    '{"salmon-poke-bowl","spicy-tuna-bowl"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '83edf7be-f329-4914-8eb9-e2d4a6bdf0d7',
    'salmon-poke-bowl',
    'salmon-poke-bowl',
    '{"en":"Salmon Poke Bowl","it":"Poke Bowl al Salmone","es":"Poke Bowl de Salmón"}'::jsonb,
    '{"en":"Fresh salmon cubes marinated in sesame soy over rice with mango, avocado, and wasabi mayo","it":"Cubetti di salmone fresco marinati in sesamo e soia su riso con mango, avocado e maionese al wasabi","es":"Cubos de salmón fresco marinados en sésamo y soja sobre arroz con mango, aguacate y mayonesa de wasabi"}'::jsonb,
    NULL,
    'trending',
    'poke',
    '{"hawaiian","raw-fish","healthy","omega-3","fresh"}',
    '{"country":"United States","country_code":"US","region":"Hawaii"}'::jsonb,
    NULL,
    'rice',
    'salmon',
    '{"tuna_raw","shrimp","tofu"}',
    'sesame-soy-dressing',
    '{"spicy-mayo","wasabi-mayo","ponzu-dressing"}',
    false,
    '[{"ingredient_id":"ING_SALMON","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_SUSHI_RICE","quantity":{"amount":150,"unit":"g"}},{"ingredient_id":"ING_MANGO","quantity":{"amount":60,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_AVOCADO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_EDAMAME","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_SESAME_OIL","quantity":{"amount":1,"unit":"tbsp"}},{"ingredient_id":"ING_SOY_SAUCE","quantity":{"amount":2,"unit":"tbsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_SESAME_SEEDS"},{"ingredient_id":"ING_NORI"},{"ingredient_id":"ING_MASAGO"}]'::jsonb,
    '{"default_portion":"bowl","available_portions":["regular","large","bowl"],"temperature":"cold","presentation":"bowl"}'::jsonb,
    '{"profile":["rich","sweet","umami","fresh","creamy"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["fish","soy","sesame"],"calories_estimate":540,"protein_g":35,"fiber_g":5}'::jsonb,
    '{"add_protein":false,"substitute_base":true,"extra_dressing":true,"make_vegan":false,"make_gluten_free":true}'::jsonb,
    NULL,
    92,
    '{"lunch","dinner","omega-3","health-conscious"}',
    '{"drinks":["sake","white-wine","sparkling-water"]}'::jsonb,
    '{"ahi-tuna-poke-bowl","spicy-salmon-bowl"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '76f96d4e-6172-422e-96a4-c5d0009bc979',
    'mediterranean-bowl',
    'mediterranean-bowl',
    '{"en":"Mediterranean Bowl","it":"Mediterranean Bowl","es":"Bowl Mediterráneo"}'::jsonb,
    '{"en":"Falafel, hummus, cucumber, tomatoes, olives, and feta over farro with tzatziki","it":"Falafel, hummus, cetriolo, pomodori, olive e feta su farro con tzatziki","es":"Falafel, hummus, pepino, tomates, aceitunas y feta sobre farro con tzatziki"}'::jsonb,
    NULL,
    'modern',
    'bowl',
    '{"mediterranean","healthy","protein-rich","vegetarian","grain-bowl"}',
    '{"country":"United States","country_code":"US"}'::jsonb,
    NULL,
    'grain',
    'none',
    '{"chicken_grilled","lamb","shrimp"}',
    'tzatziki',
    '{"tahini-dressing","lemon-olive-oil"}',
    true,
    '[{"ingredient_id":"ING_FARRO","quantity":{"amount":120,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_FALAFEL","quantity":{"amount":4,"unit":"piece"},"is_signature":true},{"ingredient_id":"ING_HUMMUS","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CHERRY_TOMATO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_KALAMATA_OLIVES","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_FETA","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_PARSLEY","quantity":{"amount":10,"unit":"g"}}]'::jsonb,
    '[{"ingredient_id":"ING_FETA"},{"ingredient_id":"ING_PINE_NUTS"},{"ingredient_id":"ING_FRESH_MINT"}]'::jsonb,
    '{"default_portion":"bowl","available_portions":["regular","large","bowl"],"temperature":"mixed","presentation":"bowl","suggested_bread":"warm pita"}'::jsonb,
    '{"profile":["herbaceous","tangy","savory","fresh","satisfying"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","sesame","tree_nuts"],"calories_estimate":580,"protein_g":22,"fiber_g":14}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":true,"extra_dressing":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    86,
    '{"lunch","dinner","vegetarian","mediterranean-diet"}',
    '{"breads":["pita","lavash"],"drinks":["mint-tea","white-wine","sparkling-water"]}'::jsonb,
    '{"falafel-salad","greek-salad","buddha-bowl"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '8e507d1d-c7d4-4041-9335-e11e04667782',
    'acai-bowl',
    'acai-bowl',
    '{"en":"Acai Bowl","it":"Acai Bowl","es":"Açaí Bowl"}'::jsonb,
    '{"en":"Thick Brazilian acai smoothie base topped with fresh fruits, granola, coconut, and honey","it":"Base di smoothie di acai brasiliano denso con frutta fresca, granola, cocco e miele","es":"Base de smoothie de açaí brasileño espeso con frutas frescas, granola, coco y miel"}'::jsonb,
    '{"en":"Superfood Breakfast from Brazil","it":"Colazione Superfood dal Brasile","es":"Desayuno Superalimento de Brasil"}'::jsonb,
    'trending',
    'superfood',
    '{"brazilian","superfood","breakfast","antioxidant","instagram-worthy"}',
    '{"country":"Brazil","country_code":"BR","region":"Amazon"}'::jsonb,
    '{"story":{"en":"Acai berries have been harvested in the Amazon for centuries but became a global superfood trend in the 2000s","it":"Le bacche di acai vengono raccolte in Amazzonia da secoli ma sono diventate un trend superfood globale negli anni 2000","es":"Las bayas de açaí se han cosechado en el Amazonas durante siglos pero se convirtieron en tendencia superfood global en los 2000"}}'::jsonb,
    'no_base',
    'none',
    '{}',
    'none',
    '{}',
    false,
    '[{"ingredient_id":"ING_ACAI_PUREE","quantity":{"amount":200,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_BANANA","quantity":{"amount":80,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_STRAWBERRY","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_BLUEBERRY","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_GRANOLA","quantity":{"amount":40,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_COCONUT_FLAKES","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_HONEY","quantity":{"amount":1,"unit":"tbsp"}},{"ingredient_id":"ING_CHIA_SEEDS","quantity":{"amount":1,"unit":"tsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_BANANA","is_signature":true},{"ingredient_id":"ING_GRANOLA","is_signature":true},{"ingredient_id":"ING_COCONUT_FLAKES"},{"ingredient_id":"ING_CHIA_SEEDS"},{"ingredient_id":"ING_ALMOND_BUTTER"}]'::jsonb,
    '{"default_portion":"bowl","available_portions":["regular","large","bowl"],"temperature":"cold","presentation":"bowl"}'::jsonb,
    '{"profile":["sweet","fruity","refreshing","creamy","tropical"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","tree_nuts"],"calories_estimate":420,"protein_g":8,"fiber_g":10}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    90,
    '{"breakfast","brunch","post-workout","summer"}',
    '{"drinks":["coconut-water","fresh-juice","coffee"]}'::jsonb,
    '{"smoothie-bowl","dragon-fruit-bowl"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '02d9926c-148f-4681-b4a9-f12ade234b87',
    'kale-superfood-bowl',
    'kale-superfood-bowl',
    '{"en":"Kale Superfood Bowl","it":"Superfood Bowl di Cavolo Riccio","es":"Bowl Superalimento de Kale"}'::jsonb,
    '{"en":"Massaged kale with quinoa, roasted beets, goat cheese, walnuts, and lemon tahini dressing","it":"Cavolo riccio massaggiato con quinoa, barbabietole arrostite, formaggio di capra, noci e condimento al tahini e limone","es":"Kale masajeado con quinoa, remolacha asada, queso de cabra, nueces y aderezo de tahini y limón"}'::jsonb,
    NULL,
    'modern',
    'superfood',
    '{"superfood","healthy","nutrient-dense","antioxidant","detox"}',
    '{"country":"United States","country_code":"US"}'::jsonb,
    NULL,
    'kale',
    'none',
    '{"chicken_grilled","salmon","tofu","eggs"}',
    'lemon-tahini',
    '{"apple-cider-vinaigrette","green-goddess"}',
    true,
    '[{"ingredient_id":"ING_KALE","quantity":{"amount":100,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_QUINOA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_ROASTED_BEETS","quantity":{"amount":80,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_GOAT_CHEESE","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_WALNUT","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_AVOCADO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_SUNFLOWER_SEEDS","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_DRIED_CRANBERRIES","quantity":{"amount":20,"unit":"g"}}]'::jsonb,
    '[{"ingredient_id":"ING_GOAT_CHEESE"},{"ingredient_id":"ING_WALNUT"},{"ingredient_id":"ING_HEMP_SEEDS"}]'::jsonb,
    '{"default_portion":"bowl","available_portions":["regular","large","bowl"],"temperature":"room_temp","presentation":"bowl"}'::jsonb,
    '{"profile":["earthy","tangy","nutty","sweet","complex"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["milk","tree_nuts"],"calories_estimate":480,"protein_g":18,"fiber_g":12}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":true,"extra_dressing":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    82,
    '{"lunch","health-conscious","detox","superfood-lovers"}',
    '{"drinks":["green-juice","kombucha","matcha"]}'::jsonb,
    '{"buddha-bowl","detox-salad","rainbow-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();