-- ============================================================================
-- GUDBRO Salads Database - Batch 05
-- Salads 21 to 25 of 52
-- ============================================================================
-- Salads in this batch:
--   - Israeli Salad (israeli-salad)
--   - Shirazi Salad (shirazi-salad)
--   - Turkish Shepherd Salad (coban-salad)
--   - Hummus Salad Bowl (hummus-salad-bowl)
--   - Falafel Salad (falafel-salad)
-- ============================================================================

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'c58b2aab-3bad-4fa7-87fe-89c6db5458be',
    'israeli-salad',
    'israeli-salad',
    '{"en":"Israeli Salad","it":"Insalata Israeliana","es":"Ensalada Israelí"}'::jsonb,
    '{"en":"Finely diced cucumber and tomato salad with fresh herbs, lemon juice, and olive oil","it":"Insalata di cetrioli e pomodori tagliati a dadini fini con erbe fresche, succo di limone e olio d''oliva","es":"Ensalada de pepino y tomate cortados en dados finos con hierbas frescas, jugo de limón y aceite de oliva"}'::jsonb,
    '{"en":"The Heart of Israeli Breakfast","it":"Il Cuore della Colazione Israeliana","es":"El Corazón del Desayuno Israelí"}'::jsonb,
    'traditional',
    'mediterranean',
    '{"israeli","simple","fresh","healthy","breakfast","vegan"}',
    '{"country":"Israel","country_code":"IL","year_created":"1950s"}'::jsonb,
    '{"story":{"en":"Also known as Arab Salad or Kibbutz Salad, this dish became a symbol of Israeli cuisine and is served at every meal","it":"Conosciuta anche come Insalata Araba o Insalata del Kibbutz, questo piatto è diventato un simbolo della cucina israeliana","es":"También conocida como Ensalada Árabe o Ensalada del Kibbutz, este plato se convirtió en símbolo de la cocina israelí"},"fun_fact":{"en":"The key is cutting all vegetables into tiny, uniform cubes - about 5mm dice","it":"Il segreto è tagliare tutte le verdure in cubetti piccoli e uniformi - circa 5mm","es":"La clave es cortar todas las verduras en cubos pequeños y uniformes - aproximadamente 5mm"}}'::jsonb,
    'no_base',
    'none',
    '{"feta","halloumi","chickpeas","eggs"}',
    'lemon-olive-oil',
    '{"tahini-dressing"}',
    false,
    '[{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_TOMATO","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_PARSLEY","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_OLIVE_OIL","quantity":{"amount":30,"unit":"ml"}}]'::jsonb,
    '[{"ingredient_id":"ING_PARSLEY"},{"ingredient_id":"ING_FRESH_MINT"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["side","regular"],"temperature":"cold","presentation":"tossed","suggested_bread":"pita"}'::jsonb,
    '{"profile":["fresh","citrusy","clean","crisp","light"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":[],"calories_estimate":100,"protein_g":2,"fiber_g":3}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":false,"extra_dressing":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    82,
    '{"breakfast","lunch","mezze","health-conscious"}',
    '{"breads":["pita","challah"],"proteins":["shakshuka","hummus","falafel"],"drinks":["turkish-coffee","fresh-juice"]}'::jsonb,
    '{"tabbouleh","greek-salad","shirazi-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'd86188c9-b2a5-4c2a-b410-42b1e44046a2',
    'shirazi-salad',
    'shirazi-salad',
    '{"en":"Shirazi Salad","it":"Insalata Shirazi","es":"Ensalada Shirazi"}'::jsonb,
    '{"en":"Persian cucumber and tomato salad from Shiraz with fresh herbs and lime juice","it":"Insalata persiana di cetrioli e pomodori da Shiraz con erbe fresche e succo di lime","es":"Ensalada persa de pepino y tomate de Shiraz con hierbas frescas y jugo de lima"}'::jsonb,
    NULL,
    'traditional',
    'mediterranean',
    '{"persian","iranian","fresh","simple","healthy","vegan"}',
    '{"country":"Iran","country_code":"IR","city":"Shiraz"}'::jsonb,
    NULL,
    'no_base',
    'none',
    '{"feta","chickpeas"}',
    'lime-olive-oil',
    '{"lemon-olive-oil"}',
    false,
    '[{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_TOMATO","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_FRESH_MINT","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":30,"unit":"ml"},"is_signature":true},{"ingredient_id":"ING_OLIVE_OIL","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_DRIED_MINT","quantity":{"amount":1,"unit":"tsp"}}]'::jsonb,
    NULL,
    '{"default_portion":"side","available_portions":["side","regular"],"temperature":"cold","presentation":"tossed"}'::jsonb,
    '{"profile":["fresh","tangy","herbaceous","light","crisp"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":[],"calories_estimate":90,"protein_g":2,"fiber_g":3}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    72,
    '{"lunch","dinner","mezze","persian-cuisine"}',
    '{"proteins":["kebab","grilled-chicken"],"drinks":["doogh","tea"]}'::jsonb,
    '{"israeli-salad","turkish-shepherd-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'a334e78e-1200-4e42-9389-ee967f07767b',
    'coban-salad',
    'coban-salad',
    '{"en":"Turkish Shepherd Salad","it":"Insalata del Pastore Turca","es":"Ensalada de Pastor Turca"}'::jsonb,
    '{"en":"Traditional Turkish chopped salad with tomatoes, cucumber, peppers, onion, and parsley","it":"Tradizionale insalata turca tritata con pomodori, cetrioli, peperoni, cipolla e prezzemolo","es":"Ensalada turca tradicional picada con tomates, pepino, pimientos, cebolla y perejil"}'::jsonb,
    '{"en":"The Pride of Turkish Tables","it":"L''Orgoglio delle Tavole Turche","es":"El Orgullo de las Mesas Turcas"}'::jsonb,
    'traditional',
    'mediterranean',
    '{"turkish","fresh","simple","everyday","healthy"}',
    '{"country":"Turkey","country_code":"TR"}'::jsonb,
    '{"story":{"en":"Named after the shepherds who would make this simple salad with fresh vegetables while tending their flocks","it":"Prende il nome dai pastori che preparavano questa semplice insalata con verdure fresche mentre curavano le greggi","es":"Nombrada en honor a los pastores que hacían esta simple ensalada con verduras frescas mientras cuidaban sus rebaños"}}'::jsonb,
    'no_base',
    'none',
    '{"feta","halloumi","chicken_grilled"}',
    'lemon-olive-oil',
    '{"pomegranate-dressing"}',
    false,
    '[{"ingredient_id":"ING_TOMATO","quantity":{"amount":120,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_GREEN_BELL_PEPPER","quantity":{"amount":60,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_PARSLEY","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":2,"unit":"tbsp"}},{"ingredient_id":"ING_SUMAC","quantity":{"amount":1,"unit":"tsp"}}]'::jsonb,
    NULL,
    '{"default_portion":"side","available_portions":["side","regular"],"temperature":"cold","presentation":"tossed"}'::jsonb,
    '{"profile":["fresh","tangy","crisp","herbaceous","light"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":[],"calories_estimate":100,"protein_g":2,"fiber_g":3}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    75,
    '{"everyday","mezze","dinner"}',
    '{"proteins":["kebab","kofte","grilled-fish"],"drinks":["ayran","turkish-tea","raki"]}'::jsonb,
    '{"israeli-salad","greek-salad","shirazi-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '7b5fffa3-9665-442d-b0fb-905d78b301bf',
    'hummus-salad-bowl',
    'hummus-salad-bowl',
    '{"en":"Hummus Salad Bowl","it":"Ciotola di Hummus con Insalata","es":"Bol de Hummus con Ensalada"}'::jsonb,
    '{"en":"Creamy hummus topped with fresh Mediterranean vegetables, chickpeas, and olive oil","it":"Hummus cremoso con verdure mediterranee fresche, ceci e olio d''oliva","es":"Hummus cremoso cubierto con verduras mediterráneas frescas, garbanzos y aceite de oliva"}'::jsonb,
    NULL,
    'modern',
    'mediterranean',
    '{"middle-eastern","protein-rich","healthy","bowl","vegan"}',
    '{"country":"Israel","country_code":"IL"}'::jsonb,
    NULL,
    'no_base',
    'chickpeas',
    '{"chicken_grilled","falafel","halloumi","eggs"}',
    'tahini-dressing',
    '{"lemon-olive-oil","zhug"}',
    false,
    '[{"ingredient_id":"ING_HUMMUS","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CHICKPEAS","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CHERRY_TOMATO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_PARSLEY","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_PAPRIKA","quantity":{"amount":1,"unit":"tsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_PINE_NUTS"},{"ingredient_id":"ING_PAPRIKA","is_signature":true}]'::jsonb,
    '{"default_portion":"bowl","available_portions":["regular","bowl"],"temperature":"cold","presentation":"bowl","suggested_bread":"warm pita"}'::jsonb,
    '{"profile":["creamy","nutty","fresh","satisfying","earthy"],"spice_level":1}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["sesame","tree_nuts"],"calories_estimate":380,"protein_g":14,"fiber_g":10}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    86,
    '{"lunch","healthy-eating","vegan","protein-seekers"}',
    '{"breads":["pita","lavash"],"drinks":["mint-tea","fresh-juice"]}'::jsonb,
    '{"falafel-salad","mediterranean-bowl"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'a4e38e71-b83c-45ba-916f-c715bb31cef3',
    'falafel-salad',
    'falafel-salad',
    '{"en":"Falafel Salad","it":"Insalata con Falafel","es":"Ensalada de Falafel"}'::jsonb,
    '{"en":"Crispy falafel over fresh greens with hummus, pickles, and creamy tahini dressing","it":"Falafel croccanti su verdure fresche con hummus, sottaceti e salsa tahini cremosa","es":"Falafel crujiente sobre verduras frescas con hummus, pepinillos y aderezo cremoso de tahini"}'::jsonb,
    NULL,
    'modern',
    'mediterranean',
    '{"middle-eastern","vegan","protein-rich","healthy","popular"}',
    '{"country":"Middle East","country_code":"XX"}'::jsonb,
    NULL,
    'mixed_greens',
    'none',
    '{"chicken_grilled","halloumi"}',
    'tahini-dressing',
    '{"garlic-sauce","lemon-olive-oil"}',
    true,
    '[{"ingredient_id":"ING_FALAFEL","quantity":{"amount":5,"unit":"piece"},"is_signature":true},{"ingredient_id":"ING_MIXED_GREENS","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_HUMMUS","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_TOMATO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_RED_CABBAGE","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_PICKLED_TURNIP","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":20,"unit":"g"}}]'::jsonb,
    '[{"ingredient_id":"ING_TAHINI"},{"ingredient_id":"ING_PARSLEY"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["regular","large","bowl"],"temperature":"mixed","presentation":"bowl","suggested_bread":"pita"}'::jsonb,
    '{"profile":["crispy","herbaceous","creamy","tangy","satisfying"],"spice_level":1}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","sesame"],"calories_estimate":450,"protein_g":18,"fiber_g":12}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    88,
    '{"lunch","vegan","healthy-eating","quick-meal"}',
    '{"breads":["pita"],"drinks":["mint-lemonade","ayran"]}'::jsonb,
    '{"hummus-salad-bowl","mediterranean-bowl"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();