-- ============================================================================
-- GUDBRO Salads Database - Batch 06
-- Salads 26 to 30 of 52
-- ============================================================================
-- Salads in this batch:
--   - Thai Beef Salad (thai-beef-salad)
--   - Larb Salad (larb-salad)
--   - Green Papaya Salad (som-tum)
--   - Vietnamese Noodle Salad (vietnamese-noodle-salad)
--   - Korean Spicy Cucumber Salad (korean-cucumber-salad)
-- ============================================================================

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '9d9bf76e-9667-48f1-93e6-d27ca0f77d17',
    'thai-beef-salad',
    'thai-beef-salad',
    '{"en":"Thai Beef Salad","it":"Insalata Thai di Manzo","es":"Ensalada Tailandesa de Res"}'::jsonb,
    '{"en":"Grilled beef slices with fresh herbs, lime, fish sauce, and Thai chilies on a bed of greens","it":"Fette di manzo grigliato con erbe fresche, lime, salsa di pesce e peperoncini thai su un letto di verdure","es":"Rebanadas de res a la parrilla con hierbas frescas, lima, salsa de pescado y chiles tailandeses sobre verduras"}'::jsonb,
    '{"en":"Bold Thai Flavors","it":"Sapori Thai Audaci","es":"Sabores Tailandeses Audaces"}'::jsonb,
    'classic',
    'asian',
    '{"thai","spicy","protein-rich","fresh","bold-flavors"}',
    '{"country":"Thailand","country_code":"TH"}'::jsonb,
    '{"story":{"en":"Known as Yum Nua in Thai, this salad exemplifies the Thai balance of hot, sour, salty, and sweet flavors","it":"Conosciuta come Yum Nua in thailandese, questa insalata esemplifica l''equilibrio thai tra sapori piccanti, acidi, salati e dolci","es":"Conocida como Yum Nua en tailandés, esta ensalada ejemplifica el equilibrio tailandés de sabores picantes, ácidos, salados y dulces"}}'::jsonb,
    'mixed_greens',
    'steak',
    '{"chicken_grilled","shrimp","tofu"}',
    'thai-lime-dressing',
    '{"nam-jim-dressing"}',
    false,
    '[{"ingredient_id":"ING_BEEF_SIRLOIN","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_MIXED_GREENS","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CHERRY_TOMATO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_FRESH_MINT","quantity":{"amount":15,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CILANTRO","quantity":{"amount":15,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_THAI_BASIL","quantity":{"amount":10,"unit":"g"}},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":3,"unit":"tbsp"}},{"ingredient_id":"ING_FISH_SAUCE","quantity":{"amount":2,"unit":"tbsp"}},{"ingredient_id":"ING_THAI_CHILI","quantity":{"amount":2,"unit":"piece"},"is_signature":true},{"ingredient_id":"ING_PALM_SUGAR","quantity":{"amount":1,"unit":"tsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_ROASTED_RICE_POWDER"},{"ingredient_id":"ING_CILANTRO","is_signature":true},{"ingredient_id":"ING_THAI_CHILI"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["regular","large"],"temperature":"mixed","presentation":"composed"}'::jsonb,
    '{"profile":["spicy","sour","savory","fresh","bold"],"spice_level":3}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["fish"],"calories_estimate":380,"protein_g":35,"fiber_g":4}'::jsonb,
    '{"add_protein":false,"substitute_base":true,"extra_dressing":true,"make_vegan":false,"make_gluten_free":true}'::jsonb,
    NULL,
    86,
    '{"lunch","dinner","spicy-lovers","protein-seekers"}',
    '{"drinks":["thai-iced-tea","singha-beer","coconut-water"]}'::jsonb,
    '{"larb-salad","vietnamese-beef-salad","korean-beef-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '1a468579-8821-41a0-908e-d2f2f26fdced',
    'larb-salad',
    'larb-salad',
    '{"en":"Larb Salad","it":"Insalata Larb","es":"Ensalada Larb"}'::jsonb,
    '{"en":"Isaan-style minced chicken salad with toasted rice powder, fresh herbs, and fiery chilies","it":"Insalata di pollo macinato in stile Isaan con polvere di riso tostato, erbe fresche e peperoncini piccanti","es":"Ensalada de pollo picado estilo Isaan con polvo de arroz tostado, hierbas frescas y chiles picantes"}'::jsonb,
    '{"en":"The Soul of Isaan Cuisine","it":"L''Anima della Cucina Isaan","es":"El Alma de la Cocina Isaan"}'::jsonb,
    'traditional',
    'asian',
    '{"thai","isaan","spicy","minced-meat","street-food"}',
    '{"country":"Thailand","country_code":"TH","region":"Isaan (Northeast)"}'::jsonb,
    '{"story":{"en":"Originating from the Isaan region of Northeast Thailand and Laos, larb is the national dish of Laos","it":"Originario della regione Isaan del nord-est della Thailandia e del Laos, il larb è il piatto nazionale del Laos","es":"Originario de la región Isaan del noreste de Tailandia y Laos, el larb es el plato nacional de Laos"},"fun_fact":{"en":"Toasted rice powder (khao khua) gives larb its distinctive nutty, crunchy texture","it":"La polvere di riso tostato (khao khua) dà al larb la sua distintiva consistenza nocciolata e croccante","es":"El polvo de arroz tostado (khao khua) le da al larb su distintiva textura crujiente y a nuez"}}'::jsonb,
    'no_base',
    'chicken_grilled',
    '{"steak","tofu"}',
    'larb-dressing',
    '{}',
    false,
    '[{"ingredient_id":"ING_CHICKEN_MINCED","quantity":{"amount":200,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_SHALLOT","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_GREEN_ONION","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_FRESH_MINT","quantity":{"amount":20,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CILANTRO","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_ROASTED_RICE_POWDER","quantity":{"amount":2,"unit":"tbsp"},"is_signature":true},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":3,"unit":"tbsp"}},{"ingredient_id":"ING_FISH_SAUCE","quantity":{"amount":2,"unit":"tbsp"}},{"ingredient_id":"ING_THAI_CHILI","quantity":{"amount":3,"unit":"piece"}}]'::jsonb,
    '[{"ingredient_id":"ING_FRESH_MINT","is_signature":true},{"ingredient_id":"ING_THAI_CHILI"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["regular","large"],"temperature":"warm","presentation":"composed","suggested_bread":"sticky rice"}'::jsonb,
    '{"profile":["spicy","sour","savory","herbaceous","crunchy"],"spice_level":4}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["fish"],"calories_estimate":320,"protein_g":32,"fiber_g":3}'::jsonb,
    '{"add_protein":false,"make_vegan":false,"make_gluten_free":true}'::jsonb,
    NULL,
    78,
    '{"dinner","spicy-lovers","thai-cuisine"}',
    '{"drinks":["singha-beer","thai-iced-tea","whiskey-soda"]}'::jsonb,
    '{"thai-beef-salad","nam-tok"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'afe96460-2a08-43a5-b8bd-bd74d555b2d4',
    'som-tum',
    'som-tum',
    '{"en":"Green Papaya Salad","it":"Insalata di Papaya Verde","es":"Ensalada de Papaya Verde"}'::jsonb,
    '{"en":"Shredded green papaya pounded with tomatoes, long beans, peanuts, and spicy lime dressing","it":"Papaya verde grattugiata pestata con pomodori, fagiolini lunghi, arachidi e condimento piccante al lime","es":"Papaya verde rallada machacada con tomates, judías largas, cacahuetes y aderezo picante de lima"}'::jsonb,
    '{"en":"Thailand''s Most Famous Street Food Salad","it":"L''Insalata Street Food Più Famosa della Thailandia","es":"La Ensalada de Comida Callejera Más Famosa de Tailandia"}'::jsonb,
    'classic',
    'asian',
    '{"thai","spicy","street-food","fresh","iconic"}',
    '{"country":"Thailand","country_code":"TH","region":"Isaan"}'::jsonb,
    '{"story":{"en":"Originally from Laos and Isaan, som tum has become one of Thailand''s most beloved dishes worldwide","it":"Originariamente dal Laos e dall''Isaan, il som tum è diventato uno dei piatti thailandesi più amati al mondo","es":"Originario de Laos e Isaan, el som tum se ha convertido en uno de los platos tailandeses más queridos del mundo"},"fun_fact":{"en":"The salad is traditionally made by pounding ingredients in a mortar and pestle (krok)","it":"L''insalata è tradizionalmente preparata pestando gli ingredienti in un mortaio (krok)","es":"La ensalada se hace tradicionalmente machacando los ingredientes en un mortero (krok)"}}'::jsonb,
    'no_base',
    'none',
    '{"shrimp","crab","eggs"}',
    'som-tum-dressing',
    '{}',
    false,
    '[{"ingredient_id":"ING_GREEN_PAPAYA","quantity":{"amount":200,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CHERRY_TOMATO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_LONG_BEANS","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_PEANUTS","quantity":{"amount":30,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_DRIED_SHRIMP","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_GARLIC","quantity":{"amount":3,"unit":"piece"}},{"ingredient_id":"ING_THAI_CHILI","quantity":{"amount":3,"unit":"piece"},"is_signature":true},{"ingredient_id":"ING_PALM_SUGAR","quantity":{"amount":2,"unit":"tbsp"}},{"ingredient_id":"ING_FISH_SAUCE","quantity":{"amount":2,"unit":"tbsp"}},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":3,"unit":"tbsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_PEANUTS","is_signature":true},{"ingredient_id":"ING_DRIED_SHRIMP"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["side","regular","large"],"temperature":"cold","presentation":"composed","suggested_bread":"sticky rice"}'::jsonb,
    '{"profile":["spicy","sour","sweet","salty","crunchy"],"spice_level":4}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":false,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":false,"is_high_protein":false,"allergens":["peanuts","fish","shellfish"],"calories_estimate":220,"protein_g":8,"fiber_g":5}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    90,
    '{"lunch","dinner","spicy-lovers","street-food"}',
    '{"proteins":["grilled-chicken","fried-fish"],"drinks":["thai-iced-tea","chang-beer","coconut-water"]}'::jsonb,
    '{"thai-beef-salad","vietnamese-green-mango-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'ccd26f7f-828d-4cdf-ba4b-d3123a23aa6a',
    'vietnamese-noodle-salad',
    'vietnamese-noodle-salad',
    '{"en":"Vietnamese Noodle Salad","it":"Insalata Vietnamita di Noodle","es":"Ensalada Vietnamita de Fideos"}'::jsonb,
    '{"en":"Rice vermicelli with fresh herbs, pickled vegetables, peanuts, and nuoc cham dressing","it":"Vermicelli di riso con erbe fresche, verdure sottaceto, arachidi e condimento nuoc cham","es":"Vermicelli de arroz con hierbas frescas, verduras encurtidas, cacahuetes y aderezo nuoc cham"}'::jsonb,
    '{"en":"Fresh Vietnamese Comfort","it":"Comfort Vietnamita Fresco","es":"Confort Vietnamita Fresco"}'::jsonb,
    'classic',
    'asian',
    '{"vietnamese","fresh","noodles","healthy","light"}',
    '{"country":"Vietnam","country_code":"VN"}'::jsonb,
    NULL,
    'noodle',
    'none',
    '{"chicken_grilled","shrimp","tofu","steak"}',
    'nuoc-cham',
    '{"peanut-sauce"}',
    true,
    '[{"ingredient_id":"ING_RICE_VERMICELLI","quantity":{"amount":100,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_ROMAINE_LETTUCE","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_CARROT","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_BEAN_SPROUTS","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_FRESH_MINT","quantity":{"amount":15,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CILANTRO","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_THAI_BASIL","quantity":{"amount":10,"unit":"g"}},{"ingredient_id":"ING_PEANUTS","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_PICKLED_DAIKON","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_PICKLED_CARROT","quantity":{"amount":30,"unit":"g"}}]'::jsonb,
    '[{"ingredient_id":"ING_PEANUTS"},{"ingredient_id":"ING_FRIED_SHALLOTS"},{"ingredient_id":"ING_FRESH_MINT","is_signature":true}]'::jsonb,
    '{"default_portion":"regular","available_portions":["regular","large","bowl"],"temperature":"room_temp","presentation":"bowl"}'::jsonb,
    '{"profile":["fresh","tangy","herbaceous","light","balanced"],"spice_level":1}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":false,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["peanuts","fish"],"calories_estimate":350,"protein_g":10,"fiber_g":5}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    84,
    '{"lunch","summer","health-conscious","light-meal"}',
    '{"drinks":["vietnamese-iced-coffee","coconut-water","bia-hoi"]}'::jsonb,
    '{"thai-noodle-salad","asian-sesame-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '24defb6a-4b10-4d9e-acdf-878a370544c1',
    'korean-cucumber-salad',
    'korean-cucumber-salad',
    '{"en":"Korean Spicy Cucumber Salad","it":"Insalata Coreana di Cetrioli Piccanti","es":"Ensalada Coreana de Pepino Picante"}'::jsonb,
    '{"en":"Crisp cucumber dressed in gochugaru (Korean chili flakes), sesame oil, and garlic","it":"Cetrioli croccanti conditi con gochugaru (fiocchi di peperoncino coreano), olio di sesamo e aglio","es":"Pepino crujiente aderezado con gochugaru (hojuelas de chile coreano), aceite de sésamo y ajo"}'::jsonb,
    NULL,
    'traditional',
    'asian',
    '{"korean","spicy","side-dish","banchan","quick"}',
    '{"country":"South Korea","country_code":"KR"}'::jsonb,
    NULL,
    'no_base',
    'none',
    '{}',
    'gochugaru-dressing',
    '{}',
    false,
    '[{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":250,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_GOCHUGARU","quantity":{"amount":1,"unit":"tbsp"},"is_signature":true},{"ingredient_id":"ING_SESAME_OIL","quantity":{"amount":1,"unit":"tbsp"},"is_signature":true},{"ingredient_id":"ING_GARLIC","quantity":{"amount":2,"unit":"piece"}},{"ingredient_id":"ING_SOY_SAUCE","quantity":{"amount":1,"unit":"tbsp"}},{"ingredient_id":"ING_RICE_VINEGAR","quantity":{"amount":1,"unit":"tbsp"}},{"ingredient_id":"ING_SESAME_SEEDS","quantity":{"amount":1,"unit":"tsp"}},{"ingredient_id":"ING_GREEN_ONION","quantity":{"amount":2,"unit":"tbsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_SESAME_SEEDS","is_signature":true}]'::jsonb,
    '{"default_portion":"side","available_portions":["side","regular"],"temperature":"cold","presentation":"tossed"}'::jsonb,
    '{"profile":["spicy","crunchy","garlicky","tangy","nutty"],"spice_level":3}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":["soy","sesame"],"calories_estimate":80,"protein_g":2,"fiber_g":2}'::jsonb,
    '{"add_protein":false,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    76,
    '{"side-dish","korean-bbq","banchan"}',
    '{"proteins":["korean-bbq","bulgogi","fried-chicken"],"drinks":["soju","makgeolli","barley-tea"]}'::jsonb,
    '{"korean-spinach-salad","korean-bean-sprout-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();