-- ============================================================================
-- GUDBRO Salads Database - Batch 03
-- Salads 11 to 15 of 52
-- ============================================================================
-- Salads in this batch:
--   - Caprese Salad (caprese-salad)
--   - Panzanella (panzanella)
--   - Tricolore Salad (tricolore-salad)
--   - Seafood Salad (insalata-di-mare)
--   - Arugula Salad (arugula-salad)
-- ============================================================================

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'e969e270-d9c0-40ec-9f7c-df29539b21a5',
    'caprese-salad',
    'caprese-salad',
    '{"en":"Caprese Salad","it":"Insalata Caprese","es":"Ensalada Caprese"}'::jsonb,
    '{"en":"Simple elegance of ripe tomatoes, fresh mozzarella, and basil drizzled with olive oil","it":"Semplice eleganza di pomodori maturi, mozzarella fresca e basilico con un filo d''olio","es":"Simple elegancia de tomates maduros, mozzarella fresca y albahaca con aceite de oliva"}'::jsonb,
    '{"en":"The Colors of Italy","it":"I Colori dell''Italia","es":"Los Colores de Italia"}'::jsonb,
    'classic',
    'italian',
    '{"italian","simple","fresh","no-lettuce","summer","tricolore"}',
    '{"country":"Italy","country_code":"IT","region":"Campania","city":"Capri","year_created":"1950s"}'::jsonb,
    '{"story":{"en":"Named after the island of Capri, this salad represents the colors of the Italian flag: red tomatoes, white mozzarella, green basil","it":"Prende il nome dall''isola di Capri, questa insalata rappresenta i colori della bandiera italiana: pomodori rossi, mozzarella bianca, basilico verde","es":"Nombrada en honor a la isla de Capri, esta ensalada representa los colores de la bandera italiana: tomates rojos, mozzarella blanca, albahaca verde"},"fun_fact":{"en":"The original caprese was meant to be a patriotic dish during the post-war period","it":"La caprese originale era pensata come piatto patriottico nel periodo post-bellico","es":"La caprese original estaba pensada como un plato patriótico en el período de posguerra"}}'::jsonb,
    'no_base',
    'mozzarella',
    '{"burrata","prosciutto"}',
    'olive-oil-basil',
    '{"balsamic-reduction","pesto-drizzle"}',
    false,
    '[{"ingredient_id":"ING_TOMATO","quantity":{"amount":200,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_MOZZARELLA","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_FRESH_BASIL","quantity":{"amount":10,"unit":"leaves"},"is_signature":true},{"ingredient_id":"ING_OLIVE_OIL","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_SEA_SALT","quantity":{"amount":1,"unit":"tsp"}},{"ingredient_id":"ING_BLACK_PEPPER","quantity":{"amount":1,"unit":"tsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_FRESH_BASIL","is_signature":true},{"ingredient_id":"ING_BALSAMIC_GLAZE"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["side","regular"],"temperature":"room_temp","presentation":"composed","suggested_bread":"ciabatta"}'::jsonb,
    '{"profile":["fresh","creamy","herbaceous","sweet","simple"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":["milk"],"calories_estimate":280,"protein_g":14,"fiber_g":2}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":false,"extra_dressing":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    '[{"name":"Caprese with Burrata","description":{"en":"Premium version with creamy burrata instead of mozzarella","it":"Versione premium con burrata cremosa invece della mozzarella","es":"Versión premium con burrata cremosa en lugar de mozzarella"},"changes":["Replace mozzarella with burrata"]},{"name":"Caprese Stack","description":{"en":"Stacked tower presentation for elegant plating","it":"Presentazione a torre impilata per un''elegante impiattamento","es":"Presentación en torre apilada para un emplatado elegante"},"changes":["Layered presentation"]}]'::jsonb,
    92,
    '{"summer","appetizer","light-meal","italian-dinner"}',
    '{"breads":["ciabatta","focaccia","bruschetta"],"drinks":["prosecco","white-wine","limoncello"]}'::jsonb,
    '{"tricolore-salad","burrata-salad","tomato-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    'a30a851a-fc4b-42f8-a573-d367a48990b7',
    'panzanella',
    'panzanella',
    '{"en":"Panzanella","it":"Panzanella","es":"Panzanella"}'::jsonb,
    '{"en":"Tuscan bread salad with chunks of crusty bread, ripe tomatoes, cucumber, onion, and basil in red wine vinaigrette","it":"Insalata di pane toscana con pezzi di pane croccante, pomodori maturi, cetriolo, cipolla e basilico in vinaigrette al vino rosso","es":"Ensalada toscana de pan con trozos de pan crujiente, tomates maduros, pepino, cebolla y albahaca en vinagreta de vino tinto"}'::jsonb,
    '{"en":"Tuscan Summer in a Bowl","it":"L''Estate Toscana in una Ciotola","es":"El Verano Toscano en un Bol"}'::jsonb,
    'traditional',
    'italian',
    '{"tuscan","bread-salad","summer","rustic","traditional"}',
    '{"country":"Italy","country_code":"IT","region":"Tuscany","year_created":"16th century"}'::jsonb,
    '{"story":{"en":"A frugal Tuscan dish created to use stale bread, soaked in water and mixed with summer vegetables","it":"Un piatto toscano frugale creato per utilizzare il pane raffermo, ammollato in acqua e mescolato con verdure estive","es":"Un plato toscano frugal creado para usar pan duro, remojado en agua y mezclado con verduras de verano"},"fun_fact":{"en":"The key to authentic panzanella is using unsalted Tuscan bread that has gone slightly stale","it":"Il segreto della panzanella autentica è usare pane toscano senza sale leggermente raffermo","es":"El secreto de la panzanella auténtica es usar pan toscano sin sal ligeramente duro"}}'::jsonb,
    'bread',
    'none',
    '{"chicken_grilled","tuna_seared","prosciutto"}',
    'red-wine-vinaigrette',
    '{"balsamic-vinaigrette","lemon-olive-oil"}',
    false,
    '[{"ingredient_id":"ING_CRUSTY_BREAD","quantity":{"amount":150,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_TOMATO","quantity":{"amount":200,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CUCUMBER","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_RED_ONION","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_FRESH_BASIL","quantity":{"amount":15,"unit":"leaves"},"is_signature":true},{"ingredient_id":"ING_OLIVE_OIL","quantity":{"amount":45,"unit":"ml"}},{"ingredient_id":"ING_RED_WINE_VINEGAR","quantity":{"amount":2,"unit":"tbsp"}},{"ingredient_id":"ING_CAPERS","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_FRESH_BASIL","is_signature":true},{"ingredient_id":"ING_CAPERS"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["side","regular","large"],"temperature":"room_temp","presentation":"tossed","suggested_bread":"none"}'::jsonb,
    '{"profile":["tangy","fresh","herbaceous","rustic","satisfying"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten"],"calories_estimate":320,"protein_g":8,"fiber_g":5}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":false,"extra_dressing":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    82,
    '{"summer","lunch","rustic-dining","italian-dinner"}',
    '{"drinks":["chianti","rosé","prosecco"]}'::jsonb,
    '{"fattoush","caprese-salad","greek-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '55831778-d51a-495d-9e33-b6a1737dafd6',
    'tricolore-salad',
    'tricolore-salad',
    '{"en":"Tricolore Salad","it":"Insalata Tricolore","es":"Ensalada Tricolore"}'::jsonb,
    '{"en":"Classic Italian salad of radicchio, arugula, and endive representing the Italian flag colors","it":"Classica insalata italiana di radicchio, rucola e indivia che rappresenta i colori della bandiera italiana","es":"Clásica ensalada italiana de radicchio, rúcula y endivia que representa los colores de la bandera italiana"}'::jsonb,
    NULL,
    'classic',
    'italian',
    '{"italian","bitter-greens","elegant","simple","patriotic"}',
    '{"country":"Italy","country_code":"IT","region":"Northern Italy"}'::jsonb,
    NULL,
    'arugula',
    'none',
    '{"prosciutto","shrimp","chicken_grilled"}',
    'balsamic-vinaigrette',
    '{"lemon-olive-oil","sherry-vinaigrette"}',
    true,
    '[{"ingredient_id":"ING_RADICCHIO","quantity":{"amount":60,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_ARUGULA","quantity":{"amount":60,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_ENDIVE","quantity":{"amount":60,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_PARMESAN","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_BALSAMIC_VINEGAR","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_PARMESAN"},{"ingredient_id":"ING_PINE_NUTS"}]'::jsonb,
    '{"default_portion":"side","available_portions":["side","regular"],"temperature":"cold","presentation":"composed"}'::jsonb,
    '{"profile":["bitter","peppery","sophisticated","crisp","earthy"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":["milk","tree_nuts"],"calories_estimate":180,"protein_g":6,"fiber_g":3}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":false,"extra_dressing":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    72,
    '{"dinner","elegant-dining","italian-dinner","appetizer"}',
    '{"drinks":["barolo","prosecco","aperol-spritz"]}'::jsonb,
    '{"caprese-salad","arugula-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '2882b024-258a-45c2-af03-baf39e090e6c',
    'insalata-di-mare',
    'insalata-di-mare',
    '{"en":"Seafood Salad","it":"Insalata di Mare","es":"Ensalada de Mariscos"}'::jsonb,
    '{"en":"Italian seafood salad with tender calamari, shrimp, mussels, and octopus in lemon-olive oil dressing","it":"Insalata di mare italiana con calamari teneri, gamberi, cozze e polpo in condimento al limone e olio","es":"Ensalada italiana de mariscos con calamares tiernos, gambas, mejillones y pulpo en aderezo de limón y aceite"}'::jsonb,
    '{"en":"Treasures from the Italian Sea","it":"Tesori del Mare Italiano","es":"Tesoros del Mar Italiano"}'::jsonb,
    'classic',
    'italian',
    '{"italian","seafood","elegant","coastal","protein-rich"}',
    '{"country":"Italy","country_code":"IT","region":"Coastal Italy"}'::jsonb,
    NULL,
    'no_base',
    'none',
    '{}',
    'lemon-olive-oil',
    '{"white-wine-vinaigrette"}',
    false,
    '[{"ingredient_id":"ING_CALAMARI","quantity":{"amount":100,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_SHRIMP","quantity":{"amount":80,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_MUSSELS","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_OCTOPUS","quantity":{"amount":60,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CELERY","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":3,"unit":"tbsp"}},{"ingredient_id":"ING_OLIVE_OIL","quantity":{"amount":45,"unit":"ml"}},{"ingredient_id":"ING_PARSLEY","quantity":{"amount":2,"unit":"tbsp"}},{"ingredient_id":"ING_GARLIC","quantity":{"amount":2,"unit":"piece"}}]'::jsonb,
    '[{"ingredient_id":"ING_PARSLEY","is_signature":true},{"ingredient_id":"ING_LEMON_ZEST"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["side","regular","large"],"temperature":"cold","presentation":"composed","suggested_bread":"crusty bread"}'::jsonb,
    '{"profile":["briny","citrusy","fresh","tender","sophisticated"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":true,"allergens":["shellfish","mollusks"],"calories_estimate":320,"protein_g":32,"fiber_g":1}'::jsonb,
    '{"add_protein":false,"substitute_base":false,"extra_dressing":true,"make_vegan":false,"make_gluten_free":true}'::jsonb,
    NULL,
    78,
    '{"dinner","special-occasion","seafood-lovers","summer"}',
    '{"breads":["crusty-bread","focaccia"],"drinks":["vermentino","prosecco","pinot-grigio"]}'::jsonb,
    '{"nicoise-salad","shrimp-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO salads (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, default_protein, protein_options,
    default_dressing, dressing_options, dressing_on_side,
    ingredients, toppings,
    serving, flavor, dietary, customization,
    variations, popularity, recommended_for,
    pairings, related_salads,
    media, source_url, source_note, version
) VALUES (
    '2b76fa6d-0035-426c-a222-b50b504553c6',
    'arugula-salad',
    'arugula-salad',
    '{"en":"Arugula Salad","it":"Insalata di Rucola","es":"Ensalada de Rúcula"}'::jsonb,
    '{"en":"Peppery arugula topped with shaved Parmesan, cherry tomatoes, and balsamic vinaigrette","it":"Rucola piccante con scaglie di Parmigiano, pomodorini e vinaigrette balsamica","es":"Rúcula picante con láminas de Parmesano, tomates cherry y vinagreta balsámica"}'::jsonb,
    NULL,
    'classic',
    'italian',
    '{"italian","peppery","simple","elegant","light"}',
    '{"country":"Italy","country_code":"IT"}'::jsonb,
    NULL,
    'arugula',
    'none',
    '{"prosciutto","chicken_grilled","shrimp","steak"}',
    'balsamic-vinaigrette',
    '{"lemon-olive-oil","sherry-vinaigrette"}',
    true,
    '[{"ingredient_id":"ING_ARUGULA","quantity":{"amount":120,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_PARMESAN","quantity":{"amount":30,"unit":"g"},"is_signature":true},{"ingredient_id":"ING_CHERRY_TOMATO","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_BALSAMIC_VINEGAR","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '[{"ingredient_id":"ING_PARMESAN","is_signature":true},{"ingredient_id":"ING_PINE_NUTS"},{"ingredient_id":"ING_BALSAMIC_GLAZE"}]'::jsonb,
    '{"default_portion":"regular","available_portions":["side","regular","large"],"temperature":"cold","presentation":"tossed"}'::jsonb,
    '{"profile":["peppery","nutty","tangy","fresh","bold"],"spice_level":1}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":true,"is_keto_friendly":true,"is_high_protein":false,"allergens":["milk","tree_nuts"],"calories_estimate":220,"protein_g":8,"fiber_g":2}'::jsonb,
    '{"add_protein":true,"protein_upcharge":true,"substitute_base":false,"extra_dressing":true,"make_vegan":true,"make_gluten_free":true}'::jsonb,
    NULL,
    85,
    '{"lunch","dinner","appetizer","italian-dinner"}',
    '{"breads":["focaccia","ciabatta"],"drinks":["prosecco","pinot-grigio","aperol-spritz"]}'::jsonb,
    '{"tricolore-salad","caprese-salad"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    default_protein = EXCLUDED.default_protein,
    protein_options = EXCLUDED.protein_options,
    default_dressing = EXCLUDED.default_dressing,
    dressing_options = EXCLUDED.dressing_options,
    dressing_on_side = EXCLUDED.dressing_on_side,
    ingredients = EXCLUDED.ingredients,
    toppings = EXCLUDED.toppings,
    serving = EXCLUDED.serving,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    customization = EXCLUDED.customization,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    pairings = EXCLUDED.pairings,
    related_salads = EXCLUDED.related_salads,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();