-- ============================================
-- INDIAN - Complete Import (65 items)
-- ============================================
-- Run this SECOND after 01-indian-missing-ingredients.sql
-- Creates the indian table and imports all dishes
-- ============================================
-- DATABASE-STANDARDS v1.1 COMPLIANT
-- - TEXT + CHECK constraints (no ENUM)
-- - JSONB for arrays
-- - All dietary fields
-- ============================================

-- Drop existing table if needed (uncomment if reimporting)
-- DROP TABLE IF EXISTS indian CASCADE;

-- Create the indian table
CREATE TABLE IF NOT EXISTS indian (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  hindi_name TEXT,

  -- Classification (TEXT + CHECK)
  category TEXT NOT NULL CHECK (category IN ('curries', 'biryani_rice', 'tandoori', 'breads', 'appetizers', 'dals', 'vegetarian', 'street_food')),
  region TEXT NOT NULL CHECK (region IN ('north', 'south', 'east', 'west', 'central', 'mughlai', 'coastal', 'punjabi', 'hyderabadi', 'kashmiri', 'indo_chinese', 'international')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'classic', 'popular', 'signature', 'seasonal', 'premium', 'traditional', 'trending', 'iconic')),

  -- Protein & Cooking
  protein_type TEXT CHECK (protein_type IN ('chicken', 'lamb', 'fish', 'shrimp', 'paneer', 'vegetables', 'lentils', 'chickpeas', 'eggs')),
  cooking_method TEXT CHECK (cooking_method IN ('tandoor', 'dum', 'tawa', 'kadhai', 'deep_fried', 'simmered', 'steamed', 'grilled', 'bhuna', 'raw')),
  is_street_food BOOLEAN NOT NULL DEFAULT false,
  curry_base TEXT CHECK (curry_base IN ('tomato', 'tomato_cream', 'cream', 'yogurt', 'spinach', 'coconut', 'tamarind')),

  -- Ingredients
  ingredient_ids JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Sistema 5 Dimensioni - Allergens
  allergens JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Sistema 5 Dimensioni - Dietary
  is_gluten_free BOOLEAN NOT NULL DEFAULT false,
  is_dairy_free BOOLEAN NOT NULL DEFAULT false,
  is_nut_free BOOLEAN NOT NULL DEFAULT true,
  is_vegan BOOLEAN NOT NULL DEFAULT false,
  is_vegetarian BOOLEAN NOT NULL DEFAULT false,
  is_halal BOOLEAN NOT NULL DEFAULT true,
  is_kosher BOOLEAN NOT NULL DEFAULT true,

  -- Sistema 5 Dimensioni - Nutrition
  calories_per_serving INTEGER,
  protein_g INTEGER,
  carbs_g INTEGER,
  fat_g INTEGER,

  -- Sistema 5 Dimensioni - Spice
  spice_level INTEGER NOT NULL DEFAULT 0 CHECK (spice_level >= 0 AND spice_level <= 5),

  -- Metadata
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  popularity INTEGER NOT NULL DEFAULT 50 CHECK (popularity >= 0 AND popularity <= 100),

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_indian_category ON indian(category);
CREATE INDEX IF NOT EXISTS idx_indian_region ON indian(region);
CREATE INDEX IF NOT EXISTS idx_indian_protein_type ON indian(protein_type);
CREATE INDEX IF NOT EXISTS idx_indian_cooking_method ON indian(cooking_method);
CREATE INDEX IF NOT EXISTS idx_indian_popularity ON indian(popularity DESC);
CREATE INDEX IF NOT EXISTS idx_indian_is_vegetarian ON indian(is_vegetarian);
CREATE INDEX IF NOT EXISTS idx_indian_is_street_food ON indian(is_street_food);

-- ============================================
-- CURRIES CATEGORY (12 items)
-- ============================================
INSERT INTO indian (id, slug, name, description, hindi_name, category, region, status, protein_type, cooking_method, is_street_food, curry_base, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('IND_BUTTER_CHICKEN', 'butter-chicken', 'Butter Chicken', 'Tender chicken pieces in a rich, creamy tomato and butter sauce with aromatic spices. The quintessential North Indian dish beloved worldwide.', 'Murgh Makhani', 'curries', 'punjabi', 'signature', 'chicken', 'simmered', false, 'tomato_cream', '["ING_CHICKEN_THIGH", "ING_TOMATO", "ING_BUTTER", "ING_CREAM", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_GARAM_MASALA", "ING_KASHMIRI_CHILI", "ING_CUMIN", "ING_CORIANDER", "ING_FENUGREEK_LEAVES", "ING_YOGURT"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 490, 32, 12, 35, 2, '["iconic", "creamy", "north-indian", "restaurant-favorite"]'::jsonb, 98),
('IND_CHICKEN_TIKKA_MASALA', 'chicken-tikka-masala', 'Chicken Tikka Masala', 'Roasted marinated chicken chunks in a creamy, spiced orange-hued tomato sauce. One of the most popular curry dishes globally.', 'Chicken Tikka Masala', 'curries', 'punjabi', 'popular', 'chicken', 'simmered', false, 'tomato_cream', '["ING_CHICKEN_BREAST", "ING_TOMATO", "ING_CREAM", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_YOGURT", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_PAPRIKA", "ING_TURMERIC"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 470, 35, 14, 30, 2, '["british-indian", "creamy", "globally-popular"]'::jsonb, 95),
('IND_LAMB_ROGAN_JOSH', 'lamb-rogan-josh', 'Lamb Rogan Josh', 'Aromatic Kashmiri lamb curry with a deep red color from Kashmiri chilies. Slow-cooked with yogurt and warming spices.', 'Gosht Rogan Josh', 'curries', 'kashmiri', 'classic', 'lamb', 'simmered', false, 'yogurt', '["ING_LAMB_LEG", "ING_YOGURT", "ING_KASHMIRI_CHILI", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_FENNEL_SEEDS", "ING_CARDAMOM", "ING_CINNAMON", "ING_CLOVES", "ING_BAY_LEAF", "ING_GHEE"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 420, 38, 8, 26, 3, '["kashmiri", "aromatic", "slow-cooked", "persian-origin"]'::jsonb, 88),
('IND_CHICKEN_KORMA', 'chicken-korma', 'Chicken Korma', 'Mild and creamy Mughlai curry with chicken braised in a rich sauce of yogurt, cream, and ground nuts. Subtly spiced and aromatic.', 'Murgh Korma', 'curries', 'mughlai', 'classic', 'chicken', 'simmered', false, 'cream', '["ING_CHICKEN_THIGH", "ING_YOGURT", "ING_CREAM", "ING_CASHEWS", "ING_ALMONDS", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_CARDAMOM", "ING_CINNAMON", "ING_CORIANDER", "ING_SAFFRON"]'::jsonb, '["milk", "tree_nuts"]'::jsonb, true, false, false, false, false, true, false, 520, 30, 15, 38, 1, '["mild", "creamy", "mughlai", "royal"]'::jsonb, 90),
('IND_LAMB_VINDALOO', 'lamb-vindaloo', 'Lamb Vindaloo', 'Fiery Goan curry with lamb marinated in vinegar and spices. Portuguese-influenced dish known for its intense heat and tangy flavor.', 'Gosht Vindaloo', 'curries', 'coastal', 'classic', 'lamb', 'simmered', false, 'tomato', '["ING_LAMB_SHOULDER", "ING_VINEGAR", "ING_TOMATO", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_RED_CHILI", "ING_CUMIN", "ING_MUSTARD_SEEDS", "ING_CINNAMON", "ING_CLOVES", "ING_TAMARIND"]'::jsonb, '[]'::jsonb, true, true, true, false, false, true, false, 380, 35, 10, 22, 5, '["goan", "spicy", "tangy", "portuguese-influence"]'::jsonb, 82),
('IND_CHICKEN_MADRAS', 'chicken-madras', 'Chicken Madras', 'Hot and tangy South Indian curry with chicken in a tomato-based sauce. Named after the city of Chennai (formerly Madras).', 'Chicken Madras', 'curries', 'south', 'popular', 'chicken', 'simmered', false, 'tomato', '["ING_CHICKEN_THIGH", "ING_TOMATO", "ING_COCONUT_MILK", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_RED_CHILI", "ING_CURRY_LEAVES", "ING_MUSTARD_SEEDS", "ING_TAMARIND", "ING_TURMERIC", "ING_CORIANDER"]'::jsonb, '[]'::jsonb, true, true, true, false, false, true, false, 350, 32, 12, 18, 4, '["south-indian", "spicy", "tangy"]'::jsonb, 78),
('IND_LAMB_SAAG', 'lamb-saag', 'Lamb Saag', 'Tender lamb pieces cooked with pureed spinach and aromatic spices. A hearty North Indian curry rich in iron and flavor.', 'Gosht Saag', 'curries', 'punjabi', 'classic', 'lamb', 'simmered', false, 'spinach', '["ING_LAMB_SHOULDER", "ING_SPINACH", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_TOMATO", "ING_CREAM", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_GREEN_CHILI", "ING_GHEE"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 400, 36, 10, 24, 2, '["spinach", "healthy", "iron-rich", "north-indian"]'::jsonb, 75),
('IND_CHICKEN_CHETTINAD', 'chicken-chettinad', 'Chicken Chettinad', 'Fiery South Indian curry from Tamil Nadu with freshly ground spices. Known for its bold flavors and aromatic spice blend.', 'Chettinad Chicken', 'curries', 'south', 'signature', 'chicken', 'simmered', false, 'tomato', '["ING_CHICKEN_THIGH", "ING_TOMATO", "ING_ONION", "ING_COCONUT", "ING_GARLIC", "ING_GINGER", "ING_BLACK_PEPPER", "ING_FENNEL_SEEDS", "ING_STAR_ANISE", "ING_CURRY_LEAVES", "ING_RED_CHILI", "ING_POPPY_SEEDS"]'::jsonb, '[]'::jsonb, true, true, true, false, false, true, false, 370, 34, 8, 22, 4, '["chettinad", "tamil-nadu", "spicy", "aromatic"]'::jsonb, 80),
('IND_LAMB_KEEMA', 'lamb-keema', 'Lamb Keema', 'Spiced minced lamb curry with peas, tomatoes, and aromatic spices. A versatile dish often served with bread or rice.', 'Keema Matar', 'curries', 'mughlai', 'traditional', 'lamb', 'simmered', false, 'tomato', '["ING_LAMB_GROUND", "ING_GREEN_PEAS", "ING_TOMATO", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_TURMERIC", "ING_GREEN_CHILI", "ING_CILANTRO"]'::jsonb, '[]'::jsonb, true, true, true, false, false, true, false, 340, 28, 12, 20, 3, '["minced", "everyday", "versatile"]'::jsonb, 72),
('IND_FISH_CURRY', 'fish-curry', 'Kerala Fish Curry', 'Tangy South Indian fish curry with coconut milk and kokum. A coastal specialty with complex sweet-sour flavors.', 'Meen Curry', 'curries', 'coastal', 'classic', 'fish', 'simmered', false, 'coconut', '["ING_FISH_WHITE", "ING_COCONUT_MILK", "ING_KOKUM", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_CURRY_LEAVES", "ING_MUSTARD_SEEDS", "ING_FENUGREEK_SEEDS", "ING_RED_CHILI", "ING_TURMERIC", "ING_TAMARIND"]'::jsonb, '["fish"]'::jsonb, true, true, true, false, false, true, false, 320, 30, 8, 18, 3, '["kerala", "coastal", "coconut", "tangy"]'::jsonb, 76),
('IND_PRAWN_MASALA', 'prawn-masala', 'Prawn Masala', 'Succulent prawns cooked in a spiced tomato and onion gravy. Popular coastal curry with bold flavors.', 'Jhinga Masala', 'curries', 'coastal', 'popular', 'shrimp', 'simmered', false, 'tomato', '["ING_SHRIMP", "ING_TOMATO", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_COCONUT_MILK", "ING_CURRY_LEAVES", "ING_GARAM_MASALA", "ING_TURMERIC", "ING_RED_CHILI", "ING_CILANTRO"]'::jsonb, '["shellfish"]'::jsonb, true, true, true, false, false, true, false, 280, 26, 10, 14, 3, '["seafood", "coastal", "goan"]'::jsonb, 74),
('IND_KADAI_CHICKEN', 'kadai-chicken', 'Kadai Chicken', 'Rustic chicken curry cooked in a kadai (wok) with bell peppers, tomatoes, and freshly ground spices.', 'Kadhai Murgh', 'curries', 'north', 'popular', 'chicken', 'kadhai', false, 'tomato', '["ING_CHICKEN_THIGH", "ING_BELL_PEPPER", "ING_TOMATO", "ING_ONION", "ING_GARLIC", "ING_GINGER", "ING_KASHMIRI_CHILI", "ING_CUMIN", "ING_CORIANDER", "ING_GARAM_MASALA", "ING_FENUGREEK_LEAVES", "ING_GHEE"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 380, 32, 12, 22, 3, '["kadai", "bell-peppers", "rustic"]'::jsonb, 85)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- BIRYANI & RICE CATEGORY (8 items)
-- ============================================
INSERT INTO indian (id, slug, name, description, hindi_name, category, region, status, protein_type, cooking_method, is_street_food, curry_base, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('IND_HYDERABADI_BIRYANI', 'hyderabadi-biryani', 'Hyderabadi Biryani', 'Iconic layered rice dish with marinated meat and basmati rice cooked in dum style. Aromatic with saffron, fried onions, and whole spices.', 'Hyderabadi Dum Biryani', 'biryani_rice', 'hyderabadi', 'signature', 'lamb', 'dum', false, 'yogurt', '["ING_LAMB_LEG", "ING_BASMATI_RICE", "ING_YOGURT", "ING_ONION", "ING_SAFFRON", "ING_GHEE", "ING_GINGER_GARLIC_PASTE", "ING_GREEN_CHILI", "ING_MINT", "ING_CILANTRO", "ING_GARAM_MASALA", "ING_BAY_LEAF", "ING_CARDAMOM", "ING_CINNAMON", "ING_CLOVES", "ING_ROSE_WATER"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 580, 28, 65, 22, 3, '["iconic", "dum-cooked", "nizam-cuisine", "layered"]'::jsonb, 98),
('IND_LUCKNOWI_BIRYANI', 'lucknowi-biryani', 'Lucknowi Biryani', 'Delicate Awadhi biryani with pre-cooked meat and rice layered together. More subtle and aromatic than Hyderabadi style.', 'Awadhi Biryani', 'biryani_rice', 'mughlai', 'classic', 'lamb', 'dum', false, 'yogurt', '["ING_LAMB_LEG", "ING_BASMATI_RICE", "ING_YOGURT", "ING_ONION", "ING_SAFFRON", "ING_GHEE", "ING_KEWRA_WATER", "ING_ROSE_WATER", "ING_CARDAMOM", "ING_MACE", "ING_NUTMEG", "ING_MINT", "ING_MILK"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 560, 26, 62, 20, 2, '["awadhi", "subtle", "aromatic", "nawabi"]'::jsonb, 88),
('IND_CHICKEN_BIRYANI', 'chicken-biryani', 'Chicken Biryani', 'Fragrant layered rice dish with spiced chicken and aromatic basmati. A beloved everyday biryani across India.', 'Murgh Biryani', 'biryani_rice', 'north', 'popular', 'chicken', 'dum', false, 'yogurt', '["ING_CHICKEN_THIGH", "ING_BASMATI_RICE", "ING_YOGURT", "ING_ONION", "ING_TOMATO", "ING_GINGER", "ING_GARLIC", "ING_GREEN_CHILI", "ING_SAFFRON", "ING_GHEE", "ING_GARAM_MASALA", "ING_MINT", "ING_CILANTRO"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 520, 30, 60, 18, 2, '["everyday", "popular", "family-style"]'::jsonb, 95),
('IND_KOLKATA_BIRYANI', 'kolkata-biryani', 'Kolkata Biryani', 'Unique Bengali-style biryani with potato and boiled egg. Lighter spices with subtle sweetness, influenced by Awadhi cuisine.', 'Kolkata Biryani', 'biryani_rice', 'east', 'classic', 'lamb', 'dum', false, 'yogurt', '["ING_LAMB_LEG", "ING_BASMATI_RICE", "ING_POTATO", "ING_EGG", "ING_YOGURT", "ING_ONION", "ING_SAFFRON", "ING_GHEE", "ING_KEWRA_WATER", "ING_CARDAMOM", "ING_NUTMEG", "ING_MACE"]'::jsonb, '["milk", "eggs"]'::jsonb, true, false, true, false, false, true, false, 590, 25, 70, 20, 1, '["bengali", "potato", "egg", "subtle"]'::jsonb, 82),
('IND_VEGETABLE_BIRYANI', 'vegetable-biryani', 'Vegetable Biryani', 'Aromatic layered rice with mixed vegetables and paneer. A vegetarian feast with the same royal flavors.', 'Sabz Biryani', 'biryani_rice', 'north', 'popular', 'vegetables', 'dum', false, 'yogurt', '["ING_BASMATI_RICE", "ING_PANEER", "ING_CARROT", "ING_GREEN_BEANS", "ING_GREEN_PEAS", "ING_POTATO", "ING_CAULIFLOWER", "ING_YOGURT", "ING_ONION", "ING_SAFFRON", "ING_GHEE", "ING_GARAM_MASALA", "ING_MINT"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 480, 14, 68, 16, 2, '["vegetarian", "mixed-vegetables", "festive"]'::jsonb, 85),
('IND_THALASSERY_BIRYANI', 'thalassery-biryani', 'Thalassery Biryani', 'Malabar-style biryani from Kerala using special Khyma rice. Distinctive short-grain texture with aromatic spices.', 'Malabar Biryani', 'biryani_rice', 'coastal', 'classic', 'chicken', 'dum', false, 'coconut', '["ING_CHICKEN_THIGH", "ING_JEERAKASALA_RICE", "ING_COCONUT_MILK", "ING_ONION", "ING_TOMATO", "ING_GINGER", "ING_GARLIC", "ING_FENNEL_SEEDS", "ING_CARDAMOM", "ING_CLOVES", "ING_GHEE", "ING_CASHEWS"]'::jsonb, '["milk", "tree_nuts"]'::jsonb, true, false, false, false, false, true, false, 540, 26, 58, 22, 2, '["malabar", "kerala", "khyma-rice"]'::jsonb, 75),
('IND_JEERA_RICE', 'jeera-rice', 'Jeera Rice', 'Fragrant basmati rice tempered with cumin seeds and ghee. Simple yet aromatic accompaniment to curries.', 'Jeera Chawal', 'biryani_rice', 'north', 'active', 'vegetables', 'simmered', false, NULL, '["ING_BASMATI_RICE", "ING_CUMIN", "ING_GHEE", "ING_BAY_LEAF", "ING_CLOVES", "ING_CARDAMOM", "ING_ONION"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 220, 4, 42, 6, 0, '["simple", "accompaniment", "everyday"]'::jsonb, 80),
('IND_PULAO', 'pulao', 'Vegetable Pulao', 'Mildly spiced one-pot rice dish with mixed vegetables. Lighter than biryani, cooked together rather than layered.', 'Sabzi Pulao', 'biryani_rice', 'north', 'traditional', 'vegetables', 'simmered', false, NULL, '["ING_BASMATI_RICE", "ING_CARROT", "ING_GREEN_PEAS", "ING_GREEN_BEANS", "ING_CAULIFLOWER", "ING_ONION", "ING_GHEE", "ING_CUMIN", "ING_BAY_LEAF", "ING_CARDAMOM", "ING_CINNAMON", "ING_CLOVES"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 280, 6, 48, 8, 1, '["one-pot", "mild", "everyday", "light"]'::jsonb, 75)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- TANDOORI CATEGORY (10 items)
-- ============================================
INSERT INTO indian (id, slug, name, description, hindi_name, category, region, status, protein_type, cooking_method, is_street_food, curry_base, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('IND_TANDOORI_CHICKEN', 'tandoori-chicken', 'Tandoori Chicken', 'Iconic marinated chicken roasted in a clay tandoor oven until charred and smoky. The fiery red color comes from Kashmiri chili.', 'Tandoori Murgh', 'tandoori', 'punjabi', 'signature', 'chicken', 'tandoor', false, 'yogurt', '["ING_CHICKEN_LEG", "ING_YOGURT", "ING_KASHMIRI_CHILI", "ING_GINGER", "ING_GARLIC", "ING_LEMON_JUICE", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_TURMERIC", "ING_MUSTARD_OIL"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 280, 35, 4, 14, 3, '["iconic", "smoky", "charred", "punjabi"]'::jsonb, 96),
('IND_CHICKEN_TIKKA', 'chicken-tikka', 'Chicken Tikka', 'Boneless chicken pieces marinated in spiced yogurt and roasted in tandoor. Tender, juicy, and bursting with flavor.', 'Murgh Tikka', 'tandoori', 'punjabi', 'popular', 'chicken', 'tandoor', false, 'yogurt', '["ING_CHICKEN_BREAST", "ING_YOGURT", "ING_KASHMIRI_CHILI", "ING_GINGER", "ING_GARLIC", "ING_LEMON_JUICE", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_AJWAIN", "ING_MUSTARD_OIL"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 240, 32, 3, 10, 2, '["boneless", "appetizer", "smoky"]'::jsonb, 94),
('IND_SEEKH_KEBAB', 'seekh-kebab', 'Seekh Kebab', 'Spiced minced meat molded onto skewers and grilled in tandoor. Aromatic with fresh herbs and char-grilled perfection.', 'Seekh Kabab', 'tandoori', 'mughlai', 'classic', 'lamb', 'tandoor', true, NULL, '["ING_LAMB_GROUND", "ING_ONION", "ING_GINGER", "ING_GARLIC", "ING_GREEN_CHILI", "ING_CILANTRO", "ING_MINT", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_EGG"]'::jsonb, '["eggs"]'::jsonb, true, true, true, false, false, true, false, 260, 22, 5, 16, 3, '["minced", "skewered", "street-food"]'::jsonb, 88),
('IND_MALAI_KEBAB', 'malai-kebab', 'Chicken Malai Kebab', 'Creamy, mild chicken kebabs marinated in cream, cheese, and cardamom. Melt-in-mouth texture with subtle flavors.', 'Murgh Malai Tikka', 'tandoori', 'mughlai', 'popular', 'chicken', 'tandoor', false, 'cream', '["ING_CHICKEN_BREAST", "ING_CREAM", "ING_CREAM_CHEESE", "ING_YOGURT", "ING_GINGER", "ING_GARLIC", "ING_GREEN_CARDAMOM", "ING_WHITE_PEPPER", "ING_MACE", "ING_NUTMEG", "ING_CASHEWS"]'::jsonb, '["milk", "tree_nuts"]'::jsonb, true, false, false, false, false, true, false, 320, 28, 4, 22, 1, '["creamy", "mild", "melt-in-mouth"]'::jsonb, 86),
('IND_FISH_TIKKA', 'fish-tikka', 'Fish Tikka', 'Firm white fish marinated with ajwain and spices, grilled in tandoor. Light and flavorful with a smoky finish.', 'Machli Tikka', 'tandoori', 'punjabi', 'classic', 'fish', 'tandoor', false, 'yogurt', '["ING_FISH_WHITE", "ING_YOGURT", "ING_AJWAIN", "ING_KASHMIRI_CHILI", "ING_GINGER", "ING_GARLIC", "ING_LEMON_JUICE", "ING_CUMIN", "ING_CORIANDER", "ING_TURMERIC", "ING_MUSTARD_OIL"]'::jsonb, '["milk", "fish"]'::jsonb, true, false, true, false, false, true, false, 200, 28, 3, 8, 2, '["seafood", "light", "ajwain"]'::jsonb, 78),
('IND_PANEER_TIKKA', 'paneer-tikka', 'Paneer Tikka', 'Marinated paneer cubes with bell peppers and onions, grilled to perfection. The vegetarian star of tandoori cuisine.', 'Paneer Tikka', 'tandoori', 'punjabi', 'popular', 'paneer', 'tandoor', false, 'yogurt', '["ING_PANEER", "ING_BELL_PEPPER", "ING_ONION", "ING_YOGURT", "ING_KASHMIRI_CHILI", "ING_GINGER", "ING_GARLIC", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_LEMON_JUICE", "ING_MUSTARD_OIL"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 280, 16, 8, 20, 2, '["vegetarian", "grilled-paneer", "appetizer"]'::jsonb, 92),
('IND_RESHMI_KEBAB', 'reshmi-kebab', 'Reshmi Kebab', 'Silky smooth chicken kebabs with a cream and cashew marinade. Named "reshmi" (silky) for their luxurious texture.', 'Reshmi Kabab', 'tandoori', 'mughlai', 'classic', 'chicken', 'tandoor', false, 'cream', '["ING_CHICKEN_BREAST", "ING_CREAM", "ING_CASHEWS", "ING_YOGURT", "ING_GINGER", "ING_GARLIC", "ING_GREEN_CARDAMOM", "ING_WHITE_PEPPER", "ING_MACE", "ING_SAFFRON"]'::jsonb, '["milk", "tree_nuts"]'::jsonb, true, false, false, false, false, true, false, 300, 26, 5, 20, 1, '["silky", "luxurious", "mild"]'::jsonb, 80),
('IND_LAMB_BOTI_KEBAB', 'lamb-boti-kebab', 'Lamb Boti Kebab', 'Succulent lamb cubes marinated in robust spices and grilled on skewers. Classic Mughlai preparation.', 'Gosht Boti Kabab', 'tandoori', 'mughlai', 'classic', 'lamb', 'tandoor', false, 'yogurt', '["ING_LAMB_LEG", "ING_YOGURT", "ING_GINGER", "ING_GARLIC", "ING_KASHMIRI_CHILI", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_RAW_PAPAYA", "ING_MUSTARD_OIL"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 280, 30, 4, 16, 3, '["lamb-cubes", "robust", "mughlai"]'::jsonb, 82),
('IND_TANDOORI_PRAWNS', 'tandoori-prawns', 'Tandoori Prawns', 'Large prawns marinated in tandoori spices and grilled until smoky and succulent. Coastal meets North Indian cuisine.', 'Tandoori Jhinga', 'tandoori', 'coastal', 'premium', 'shrimp', 'tandoor', false, 'yogurt', '["ING_SHRIMP_LARGE", "ING_YOGURT", "ING_KASHMIRI_CHILI", "ING_GINGER", "ING_GARLIC", "ING_LEMON_JUICE", "ING_GARAM_MASALA", "ING_AJWAIN", "ING_CUMIN", "ING_MUSTARD_OIL"]'::jsonb, '["milk", "shellfish"]'::jsonb, true, false, true, false, false, true, false, 220, 28, 3, 10, 2, '["seafood", "premium", "coastal"]'::jsonb, 76),
('IND_HARIYALI_TIKKA', 'hariyali-tikka', 'Hariyali Chicken Tikka', 'Green chicken tikka marinated in mint, cilantro, and green chili paste. Vibrant color with fresh herbal flavors.', 'Hariyali Murgh Tikka', 'tandoori', 'punjabi', 'popular', 'chicken', 'tandoor', false, 'yogurt', '["ING_CHICKEN_BREAST", "ING_YOGURT", "ING_MINT", "ING_CILANTRO", "ING_GREEN_CHILI", "ING_GINGER", "ING_GARLIC", "ING_SPINACH", "ING_LEMON_JUICE", "ING_CUMIN", "ING_CHAAT_MASALA"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, false, true, false, 230, 30, 4, 10, 3, '["green", "herbal", "fresh", "mint"]'::jsonb, 84)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- BREADS CATEGORY (8 items)
-- ============================================
INSERT INTO indian (id, slug, name, description, hindi_name, category, region, status, protein_type, cooking_method, is_street_food, curry_base, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('IND_GARLIC_NAAN', 'garlic-naan', 'Garlic Naan', 'Leavened flatbread topped with garlic and butter, baked in tandoor. The most popular naan variety worldwide.', 'Lahsun Naan', 'breads', 'punjabi', 'signature', 'vegetables', 'tandoor', false, NULL, '["ING_ALL_PURPOSE_FLOUR", "ING_YEAST", "ING_YOGURT", "ING_GARLIC", "ING_BUTTER", "ING_CILANTRO", "ING_MILK", "ING_SUGAR", "ING_SALT"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 260, 7, 42, 8, 0, '["garlic", "butter", "tandoor-baked"]'::jsonb, 96),
('IND_BUTTER_NAAN', 'butter-naan', 'Butter Naan', 'Classic leavened bread brushed with melted butter. Soft, pillowy, and perfect for scooping up curries.', 'Makhan Naan', 'breads', 'punjabi', 'classic', 'vegetables', 'tandoor', false, NULL, '["ING_ALL_PURPOSE_FLOUR", "ING_YEAST", "ING_YOGURT", "ING_BUTTER", "ING_MILK", "ING_SUGAR", "ING_SALT", "ING_BAKING_POWDER"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 280, 6, 40, 10, 0, '["buttery", "soft", "classic"]'::jsonb, 94),
('IND_ROTI', 'roti', 'Roti', 'Everyday unleavened whole wheat flatbread. Thin, soft, and the staple bread served daily in Indian households.', 'Chapati', 'breads', 'north', 'traditional', 'vegetables', 'tawa', false, NULL, '["ING_WHOLE_WHEAT_FLOUR", "ING_WATER", "ING_SALT", "ING_GHEE"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 120, 4, 24, 1, 0, '["everyday", "healthy", "whole-wheat"]'::jsonb, 90),
('IND_PARATHA', 'paratha', 'Plain Paratha', 'Layered flaky flatbread cooked with ghee on a griddle. Crispy exterior with soft, buttery layers inside.', 'Paratha', 'breads', 'punjabi', 'traditional', 'vegetables', 'tawa', false, NULL, '["ING_WHOLE_WHEAT_FLOUR", "ING_GHEE", "ING_WATER", "ING_SALT"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 200, 5, 28, 8, 0, '["layered", "flaky", "griddle-cooked"]'::jsonb, 88),
('IND_ALOO_PARATHA', 'aloo-paratha', 'Aloo Paratha', 'Stuffed paratha filled with spiced mashed potatoes. Iconic Punjabi breakfast served with yogurt and pickle.', 'Aloo Paratha', 'breads', 'punjabi', 'signature', 'vegetables', 'tawa', true, NULL, '["ING_WHOLE_WHEAT_FLOUR", "ING_POTATO", "ING_GREEN_CHILI", "ING_ONION", "ING_CILANTRO", "ING_CUMIN", "ING_CORIANDER", "ING_RED_CHILI", "ING_AMCHUR", "ING_GHEE", "ING_SALT"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 280, 6, 38, 12, 2, '["stuffed", "breakfast", "punjabi", "comfort-food"]'::jsonb, 92),
('IND_PURI', 'puri', 'Puri', 'Deep-fried puffed bread that balloons when fried. Light and crispy, traditionally served with chole or aloo.', 'Poori', 'breads', 'north', 'traditional', 'vegetables', 'deep_fried', true, NULL, '["ING_WHOLE_WHEAT_FLOUR", "ING_VEGETABLE_OIL", "ING_WATER", "ING_SALT"]'::jsonb, '["gluten"]'::jsonb, false, true, true, true, true, true, true, 150, 3, 20, 7, 0, '["puffed", "fried", "festive"]'::jsonb, 85),
('IND_BHATURA', 'bhatura', 'Bhatura', 'Leavened deep-fried bread, larger and fluffier than puri. The essential companion to chole in chole bhature.', 'Bhatura', 'breads', 'punjabi', 'popular', 'vegetables', 'deep_fried', true, NULL, '["ING_ALL_PURPOSE_FLOUR", "ING_YOGURT", "ING_BAKING_POWDER", "ING_SEMOLINA", "ING_VEGETABLE_OIL", "ING_SUGAR", "ING_SALT"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 320, 6, 42, 14, 0, '["fluffy", "fried", "chole-bhature"]'::jsonb, 88),
('IND_KULCHA', 'kulcha', 'Amritsari Kulcha', 'Leavened bread stuffed with spiced potatoes, crispy outside and soft inside. Famous Punjabi specialty from Amritsar.', 'Amritsari Kulcha', 'breads', 'punjabi', 'signature', 'vegetables', 'tandoor', true, NULL, '["ING_ALL_PURPOSE_FLOUR", "ING_POTATO", "ING_ONION", "ING_GREEN_CHILI", "ING_CILANTRO", "ING_POMEGRANATE_SEEDS", "ING_CUMIN", "ING_YOGURT", "ING_BAKING_POWDER", "ING_GHEE", "ING_SALT"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 300, 7, 40, 12, 2, '["stuffed", "amritsar", "crispy"]'::jsonb, 86)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- APPETIZERS CATEGORY (7 items)
-- ============================================
INSERT INTO indian (id, slug, name, description, hindi_name, category, region, status, protein_type, cooking_method, is_street_food, curry_base, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('IND_SAMOSA', 'samosa', 'Samosa', 'Iconic triangular pastry filled with spiced potatoes and peas. Crispy, golden, and probably the most famous Indian snack worldwide.', 'Samosa', 'appetizers', 'north', 'signature', 'vegetables', 'deep_fried', true, NULL, '["ING_ALL_PURPOSE_FLOUR", "ING_POTATO", "ING_GREEN_PEAS", "ING_ONION", "ING_GREEN_CHILI", "ING_GINGER", "ING_CUMIN", "ING_CORIANDER", "ING_GARAM_MASALA", "ING_AMCHUR", "ING_VEGETABLE_OIL", "ING_CILANTRO"]'::jsonb, '["gluten"]'::jsonb, false, true, true, true, true, true, true, 180, 4, 24, 8, 2, '["iconic", "triangular", "street-food", "crispy"]'::jsonb, 98),
('IND_ONION_PAKORA', 'onion-pakora', 'Onion Pakora', 'Crispy fritters made with sliced onions in spiced chickpea batter. Perfect monsoon snack served with mint chutney.', 'Pyaaz Pakora', 'appetizers', 'north', 'traditional', 'vegetables', 'deep_fried', true, NULL, '["ING_CHICKPEA_FLOUR", "ING_ONION", "ING_GREEN_CHILI", "ING_CILANTRO", "ING_CUMIN", "ING_RED_CHILI", "ING_AJWAIN", "ING_TURMERIC", "ING_VEGETABLE_OIL", "ING_SALT"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 150, 5, 18, 7, 2, '["crispy", "monsoon-snack", "chai-time"]'::jsonb, 88),
('IND_VEGETABLE_PAKORA', 'vegetable-pakora', 'Vegetable Pakora', 'Assorted vegetables dipped in spiced chickpea batter and deep-fried. Includes potato, cauliflower, spinach, and peppers.', 'Sabzi Pakora', 'appetizers', 'north', 'popular', 'vegetables', 'deep_fried', true, NULL, '["ING_CHICKPEA_FLOUR", "ING_POTATO", "ING_CAULIFLOWER", "ING_SPINACH", "ING_BELL_PEPPER", "ING_GREEN_CHILI", "ING_CUMIN", "ING_CORIANDER", "ING_TURMERIC", "ING_VEGETABLE_OIL", "ING_SALT"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 160, 5, 20, 7, 2, '["mixed-vegetables", "crispy", "tea-time"]'::jsonb, 85),
('IND_ALOO_TIKKI', 'aloo-tikki', 'Aloo Tikki', 'Spiced potato patties pan-fried until crispy. Popular street food often topped with chutneys and yogurt.', 'Aloo Tikki', 'appetizers', 'north', 'popular', 'vegetables', 'tawa', true, NULL, '["ING_POTATO", "ING_GREEN_PEAS", "ING_ONION", "ING_GREEN_CHILI", "ING_GINGER", "ING_CILANTRO", "ING_CUMIN", "ING_CORIANDER", "ING_GARAM_MASALA", "ING_CHAAT_MASALA", "ING_VEGETABLE_OIL"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 140, 3, 22, 5, 2, '["potato-patties", "crispy", "chaat-base"]'::jsonb, 90),
('IND_ONION_BHAJI', 'onion-bhaji', 'Onion Bhaji', 'British-Indian style onion fritters, slightly different from pakora. Rounder shape with more batter.', 'Onion Bhaji', 'appetizers', 'international', 'popular', 'vegetables', 'deep_fried', true, NULL, '["ING_CHICKPEA_FLOUR", "ING_ONION", "ING_CUMIN", "ING_CORIANDER", "ING_TURMERIC", "ING_RED_CHILI", "ING_BAKING_POWDER", "ING_VEGETABLE_OIL", "ING_SALT"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 160, 4, 18, 8, 2, '["british-indian", "round", "crispy"]'::jsonb, 82),
('IND_CHICKEN_PAKORA', 'chicken-pakora', 'Chicken Pakora', 'Tender chicken pieces coated in spiced chickpea batter and deep-fried. Popular non-vegetarian appetizer.', 'Murgh Pakora', 'appetizers', 'north', 'popular', 'chicken', 'deep_fried', true, NULL, '["ING_CHICKEN_BREAST", "ING_CHICKPEA_FLOUR", "ING_GINGER", "ING_GARLIC", "ING_CUMIN", "ING_CORIANDER", "ING_RED_CHILI", "ING_GARAM_MASALA", "ING_VEGETABLE_OIL", "ING_LEMON_JUICE"]'::jsonb, '[]'::jsonb, true, true, true, false, false, true, false, 200, 18, 12, 10, 2, '["chicken", "crispy", "non-veg"]'::jsonb, 84),
('IND_PANEER_PAKORA', 'paneer-pakora', 'Paneer Pakora', 'Cubes of paneer coated in spiced batter and deep-fried until golden. Soft inside, crispy outside.', 'Paneer Pakora', 'appetizers', 'north', 'popular', 'paneer', 'deep_fried', true, NULL, '["ING_PANEER", "ING_CHICKPEA_FLOUR", "ING_CUMIN", "ING_CORIANDER", "ING_RED_CHILI", "ING_AJWAIN", "ING_TURMERIC", "ING_VEGETABLE_OIL", "ING_CHAAT_MASALA"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 220, 12, 14, 14, 2, '["paneer", "crispy", "vegetarian"]'::jsonb, 86)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- DALS CATEGORY (6 items)
-- ============================================
INSERT INTO indian (id, slug, name, description, hindi_name, category, region, status, protein_type, cooking_method, is_street_food, curry_base, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('IND_DAL_MAKHANI', 'dal-makhani', 'Dal Makhani', 'Rich and creamy black lentils slow-cooked with butter and cream. The queen of dals from Punjab, simmered for hours.', 'Dal Makhani', 'dals', 'punjabi', 'signature', 'lentils', 'simmered', false, 'tomato_cream', '["ING_BLACK_LENTILS", "ING_KIDNEY_BEANS", "ING_BUTTER", "ING_CREAM", "ING_TOMATO", "ING_ONION", "ING_GINGER", "ING_GARLIC", "ING_GARAM_MASALA", "ING_KASHMIRI_CHILI", "ING_FENUGREEK_LEAVES"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 380, 14, 35, 20, 2, '["creamy", "slow-cooked", "restaurant-favorite", "punjabi"]'::jsonb, 95),
('IND_DAL_TADKA', 'dal-tadka', 'Dal Tadka', 'Yellow lentils tempered with cumin, garlic, and dried chilies in hot ghee. Everyday comfort food across India.', 'Dal Tadka', 'dals', 'north', 'traditional', 'lentils', 'simmered', false, 'tomato', '["ING_TOOR_DAL", "ING_GHEE", "ING_CUMIN", "ING_GARLIC", "ING_DRIED_RED_CHILI", "ING_ONION", "ING_TOMATO", "ING_TURMERIC", "ING_CILANTRO", "ING_ASAFOETIDA"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 220, 12, 30, 6, 2, '["everyday", "tempered", "comfort-food"]'::jsonb, 90),
('IND_CHANA_MASALA', 'chana-masala', 'Chana Masala', 'Spiced chickpea curry in a tangy tomato-onion gravy. Popular North Indian dish often paired with bhatura.', 'Chole', 'dals', 'punjabi', 'signature', 'chickpeas', 'simmered', true, 'tomato', '["ING_CHICKPEAS", "ING_TOMATO", "ING_ONION", "ING_GINGER", "ING_GARLIC", "ING_GREEN_CHILI", "ING_CHOLE_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_AMCHUR", "ING_POMEGRANATE_SEEDS", "ING_VEGETABLE_OIL"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 280, 14, 42, 6, 3, '["chickpeas", "tangy", "chole-bhature", "protein-rich"]'::jsonb, 94),
('IND_RAJMA', 'rajma', 'Rajma', 'Red kidney bean curry in a thick tomato-onion gravy. Punjabi comfort food traditionally served with rice.', 'Rajma Chawal', 'dals', 'punjabi', 'traditional', 'lentils', 'simmered', false, 'tomato', '["ING_KIDNEY_BEANS", "ING_TOMATO", "ING_ONION", "ING_GINGER", "ING_GARLIC", "ING_GREEN_CHILI", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_KASHMIRI_CHILI", "ING_GHEE", "ING_CILANTRO"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 260, 15, 38, 5, 2, '["kidney-beans", "comfort-food", "sunday-special"]'::jsonb, 88),
('IND_SAMBAR', 'sambar', 'Sambar', 'South Indian lentil stew with vegetables and tamarind. Essential accompaniment to dosa and idli.', 'Sambar', 'dals', 'south', 'signature', 'lentils', 'simmered', false, 'tamarind', '["ING_TOOR_DAL", "ING_TAMARIND", "ING_SAMBAR_POWDER", "ING_DRUMSTICK", "ING_CARROT", "ING_ONION", "ING_TOMATO", "ING_CURRY_LEAVES", "ING_MUSTARD_SEEDS", "ING_DRIED_RED_CHILI", "ING_ASAFOETIDA", "ING_COCONUT_OIL"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 180, 10, 28, 4, 3, '["south-indian", "tangy", "dosa-idli"]'::jsonb, 92),
('IND_DAL_FRY', 'dal-fry', 'Dal Fry', 'Mixed lentils cooked with onion and tomato, then tempered. Restaurant-style dal with richer flavor than home-style.', 'Dal Fry', 'dals', 'north', 'popular', 'lentils', 'simmered', false, 'tomato', '["ING_TOOR_DAL", "ING_MASOOR_DAL", "ING_ONION", "ING_TOMATO", "ING_GINGER", "ING_GARLIC", "ING_GREEN_CHILI", "ING_CUMIN", "ING_TURMERIC", "ING_GARAM_MASALA", "ING_GHEE", "ING_CILANTRO"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 200, 11, 28, 5, 2, '["restaurant-style", "mixed-lentils", "everyday"]'::jsonb, 85)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- VEGETARIAN CATEGORY (8 items)
-- ============================================
INSERT INTO indian (id, slug, name, description, hindi_name, category, region, status, protein_type, cooking_method, is_street_food, curry_base, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('IND_PALAK_PANEER', 'palak-paneer', 'Palak Paneer', 'Paneer cubes in a vibrant, creamy spinach sauce. One of the most popular vegetarian dishes in Indian cuisine.', 'Palak Paneer', 'vegetarian', 'punjabi', 'signature', 'paneer', 'simmered', false, 'spinach', '["ING_PANEER", "ING_SPINACH", "ING_ONION", "ING_TOMATO", "ING_GINGER", "ING_GARLIC", "ING_GREEN_CHILI", "ING_CREAM", "ING_CUMIN", "ING_GARAM_MASALA", "ING_GHEE"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 340, 18, 12, 26, 2, '["spinach", "creamy", "healthy", "iron-rich"]'::jsonb, 96),
('IND_MATAR_PANEER', 'matar-paneer', 'Matar Paneer', 'Paneer and green peas in a spiced tomato-based sauce. Classic North Indian curry loved by all ages.', 'Matar Paneer', 'vegetarian', 'north', 'classic', 'paneer', 'simmered', false, 'tomato', '["ING_PANEER", "ING_GREEN_PEAS", "ING_TOMATO", "ING_ONION", "ING_GINGER", "ING_GARLIC", "ING_CREAM", "ING_GARAM_MASALA", "ING_CUMIN", "ING_CORIANDER", "ING_KASHMIRI_CHILI", "ING_GHEE"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 320, 16, 18, 22, 2, '["peas", "comfort-food", "family-favorite"]'::jsonb, 90),
('IND_PANEER_BUTTER_MASALA', 'paneer-butter-masala', 'Paneer Butter Masala', 'Paneer in a rich, creamy tomato-butter sauce. The vegetarian equivalent of butter chicken.', 'Paneer Makhani', 'vegetarian', 'punjabi', 'signature', 'paneer', 'simmered', false, 'tomato_cream', '["ING_PANEER", "ING_TOMATO", "ING_BUTTER", "ING_CREAM", "ING_ONION", "ING_GINGER", "ING_GARLIC", "ING_GARAM_MASALA", "ING_KASHMIRI_CHILI", "ING_FENUGREEK_LEAVES", "ING_SUGAR"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 400, 16, 14, 32, 1, '["rich", "creamy", "restaurant-favorite"]'::jsonb, 94),
('IND_ALOO_GOBI', 'aloo-gobi', 'Aloo Gobi', 'Dry curry of potatoes and cauliflower with turmeric and spices. Simple, comforting, everyday vegetable dish.', 'Aloo Gobhi', 'vegetarian', 'north', 'traditional', 'vegetables', 'bhuna', false, NULL, '["ING_POTATO", "ING_CAULIFLOWER", "ING_ONION", "ING_TOMATO", "ING_GINGER", "ING_GARLIC", "ING_TURMERIC", "ING_CUMIN", "ING_CORIANDER", "ING_GARAM_MASALA", "ING_GREEN_CHILI", "ING_VEGETABLE_OIL"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 180, 4, 28, 6, 2, '["dry-curry", "everyday", "home-style"]'::jsonb, 85),
('IND_KADAI_PANEER', 'kadai-paneer', 'Kadai Paneer', 'Paneer with bell peppers in a spiced tomato gravy cooked in a kadai. Rustic, flavorful, and colorful.', 'Kadhai Paneer', 'vegetarian', 'north', 'popular', 'paneer', 'kadhai', false, 'tomato', '["ING_PANEER", "ING_BELL_PEPPER", "ING_TOMATO", "ING_ONION", "ING_GINGER", "ING_GARLIC", "ING_KASHMIRI_CHILI", "ING_CUMIN", "ING_CORIANDER", "ING_GARAM_MASALA", "ING_FENUGREEK_LEAVES", "ING_GHEE"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 340, 16, 14, 26, 3, '["bell-peppers", "rustic", "colorful"]'::jsonb, 88),
('IND_SHAHI_PANEER', 'shahi-paneer', 'Shahi Paneer', 'Royal paneer curry with cashew-cream sauce and aromatic spices. Rich Mughlai preparation fit for royalty.', 'Shahi Paneer', 'vegetarian', 'mughlai', 'premium', 'paneer', 'simmered', false, 'cream', '["ING_PANEER", "ING_CREAM", "ING_CASHEWS", "ING_ONION", "ING_TOMATO", "ING_GINGER", "ING_GARLIC", "ING_CARDAMOM", "ING_CINNAMON", "ING_SAFFRON", "ING_GARAM_MASALA", "ING_GHEE"]'::jsonb, '["milk", "tree_nuts"]'::jsonb, true, false, false, false, true, true, true, 420, 18, 16, 34, 1, '["royal", "rich", "festive", "mughlai"]'::jsonb, 86),
('IND_BAINGAN_BHARTA', 'baingan-bharta', 'Baingan Bharta', 'Smoky mashed eggplant cooked with onions, tomatoes, and spices. Rustic Punjabi dish with charred flavor.', 'Baingan Bharta', 'vegetarian', 'punjabi', 'traditional', 'vegetables', 'grilled', false, 'tomato', '["ING_EGGPLANT", "ING_ONION", "ING_TOMATO", "ING_GREEN_PEAS", "ING_GINGER", "ING_GARLIC", "ING_GREEN_CHILI", "ING_CUMIN", "ING_CORIANDER", "ING_GARAM_MASALA", "ING_MUSTARD_OIL", "ING_CILANTRO"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 160, 4, 18, 8, 2, '["smoky", "eggplant", "rustic"]'::jsonb, 78),
('IND_MALAI_KOFTA', 'malai-kofta', 'Malai Kofta', 'Deep-fried paneer and potato dumplings in a creamy tomato-cashew sauce. Indulgent vegetarian celebration dish.', 'Malai Kofta', 'vegetarian', 'mughlai', 'premium', 'paneer', 'deep_fried', false, 'cream', '["ING_PANEER", "ING_POTATO", "ING_CASHEWS", "ING_RAISINS", "ING_CREAM", "ING_TOMATO", "ING_ONION", "ING_GINGER", "ING_GARLIC", "ING_GARAM_MASALA", "ING_CARDAMOM", "ING_GHEE", "ING_VEGETABLE_OIL"]'::jsonb, '["milk", "tree_nuts"]'::jsonb, true, false, false, false, true, true, true, 450, 14, 28, 32, 1, '["kofta", "indulgent", "festive", "celebration"]'::jsonb, 84)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- STREET FOOD CATEGORY (6 items)
-- ============================================
INSERT INTO indian (id, slug, name, description, hindi_name, category, region, status, protein_type, cooking_method, is_street_food, curry_base, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('IND_PAV_BHAJI', 'pav-bhaji', 'Pav Bhaji', 'Spicy mashed vegetable curry served with buttered soft bread rolls. Iconic Mumbai street food loved across India.', 'Pav Bhaji', 'street_food', 'west', 'signature', 'vegetables', 'tawa', true, 'tomato', '["ING_POTATO", "ING_CAULIFLOWER", "ING_GREEN_PEAS", "ING_CARROT", "ING_BELL_PEPPER", "ING_TOMATO", "ING_ONION", "ING_PAV_BHAJI_MASALA", "ING_BUTTER", "ING_GINGER", "ING_GARLIC", "ING_PAV_BREAD", "ING_CILANTRO"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 420, 10, 52, 18, 3, '["mumbai", "buttery", "mashed-vegetables", "iconic"]'::jsonb, 95),
('IND_VADA_PAV', 'vada-pav', 'Vada Pav', 'Spicy potato fritter in a bread roll with chutneys. Mumbai''s beloved "Indian burger" - cheap, filling, and delicious.', 'Vada Pav', 'street_food', 'west', 'signature', 'vegetables', 'deep_fried', true, NULL, '["ING_POTATO", "ING_CHICKPEA_FLOUR", "ING_GREEN_CHILI", "ING_GINGER", "ING_GARLIC", "ING_CURRY_LEAVES", "ING_MUSTARD_SEEDS", "ING_TURMERIC", "ING_PAV_BREAD", "ING_GREEN_CHUTNEY", "ING_TAMARIND_CHUTNEY", "ING_VEGETABLE_OIL"]'::jsonb, '["gluten"]'::jsonb, false, true, true, true, true, true, true, 280, 6, 38, 12, 3, '["mumbai", "indian-burger", "working-class-food"]'::jsonb, 92),
('IND_PANI_PURI', 'pani-puri', 'Pani Puri', 'Crispy hollow puris filled with spiced water, potatoes, and chickpeas. The quintessential Indian chaat experience.', 'Golgappa', 'street_food', 'north', 'signature', 'vegetables', 'deep_fried', true, NULL, '["ING_SEMOLINA", "ING_POTATO", "ING_CHICKPEAS", "ING_ONION", "ING_MINT", "ING_CILANTRO", "ING_TAMARIND", "ING_CUMIN", "ING_BLACK_SALT", "ING_CHAAT_MASALA", "ING_GREEN_CHILI", "ING_VEGETABLE_OIL"]'::jsonb, '["gluten"]'::jsonb, false, true, true, true, true, true, true, 150, 4, 24, 4, 3, '["chaat", "tangy", "spicy-water", "addictive"]'::jsonb, 94),
('IND_BHEL_PURI', 'bhel-puri', 'Bhel Puri', 'Puffed rice mixed with chutneys, vegetables, and sev. Light, crunchy Mumbai beach snack with sweet-sour-spicy flavors.', 'Bhel Puri', 'street_food', 'west', 'popular', 'vegetables', 'raw', true, NULL, '["ING_PUFFED_RICE", "ING_SEV", "ING_POTATO", "ING_ONION", "ING_TOMATO", "ING_GREEN_CHUTNEY", "ING_TAMARIND_CHUTNEY", "ING_CHAAT_MASALA", "ING_CILANTRO", "ING_GREEN_CHILI"]'::jsonb, '["gluten"]'::jsonb, false, true, true, true, true, true, true, 180, 4, 32, 5, 2, '["beach-snack", "crunchy", "light", "refreshing"]'::jsonb, 88),
('IND_DOSA', 'dosa', 'Masala Dosa', 'Crispy fermented rice crepe filled with spiced potato masala. South Indian breakfast staple served with sambar and chutneys.', 'Masala Dosa', 'street_food', 'south', 'signature', 'vegetables', 'tawa', true, NULL, '["ING_RICE", "ING_URAD_DAL", "ING_POTATO", "ING_ONION", "ING_MUSTARD_SEEDS", "ING_CURRY_LEAVES", "ING_GREEN_CHILI", "ING_TURMERIC", "ING_GHEE", "ING_ASAFOETIDA"]'::jsonb, '["milk"]'::jsonb, true, false, true, false, true, true, true, 280, 6, 42, 10, 2, '["south-indian", "fermented", "crispy", "breakfast"]'::jsonb, 96),
('IND_IDLI', 'idli', 'Idli', 'Soft, fluffy steamed rice cakes. Healthy South Indian breakfast served with sambar and coconut chutney.', 'Idli', 'street_food', 'south', 'traditional', 'vegetables', 'steamed', true, NULL, '["ING_RICE", "ING_URAD_DAL", "ING_FENUGREEK_SEEDS", "ING_SALT"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 120, 4, 24, 0, 0, '["steamed", "healthy", "light", "breakfast"]'::jsonb, 90)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- Verify count
-- ============================================
SELECT
  'Total Indian dishes' as metric,
  COUNT(*) as count
FROM indian;

SELECT
  category,
  COUNT(*) as count
FROM indian
GROUP BY category
ORDER BY count DESC;
