-- Nigerian Cuisine - Insert Dishes
-- GUDBRO Database
-- Date: 2025-12-26
-- Total dishes: 49

INSERT INTO nigerian (id, slug, name, description, category, status, region, protein_type, cooking_method, prep_time_min, spice_level, is_vegetarian, is_vegan, is_gluten_free, is_dairy_free, allergens, tags, popularity) VALUES

-- SOUPS (10)
('NIG_EGUSI_SOUP', 'egusi-soup', 'Egusi Soup', 'Rich and hearty soup made with ground melon seeds, leafy vegetables, and assorted meats. One of Nigeria''s most beloved dishes.', 'soup', 'iconic', 'nationwide', 'mixed', 'simmered', 60, 2, false, false, true, true, ARRAY['fish'], ARRAY['melon-seeds', 'vegetables', 'traditional', 'hearty'], 98),
('NIG_OGBONO_SOUP', 'ogbono-soup', 'Ogbono Soup', 'Traditional Nigerian soup made from ground ogbono (wild mango) seeds with a distinctive slimy texture and rich umami flavor.', 'soup', 'iconic', 'southeast', 'mixed', 'simmered', 50, 2, false, false, true, true, ARRAY['fish'], ARRAY['ogbono', 'draw-soup', 'igbo', 'traditional'], 90),
('NIG_EFO_RIRO', 'efo-riro', 'Efo Riro', 'Yoruba-style vegetable soup made with spinach or pumpkin leaves, cooked in a rich tomato and pepper base with assorted proteins.', 'soup', 'iconic', 'southwest', 'mixed', 'simmered', 45, 3, false, false, true, true, ARRAY['fish'], ARRAY['yoruba', 'vegetables', 'spinach', 'traditional'], 92),
('NIG_AFANG_SOUP', 'afang-soup', 'Afang Soup', 'Rich vegetable soup from the Efik and Ibibio people, made with afang leaves and waterleaf, simmered with assorted meats and fish.', 'soup', 'classic', 'southeast', 'mixed', 'simmered', 55, 2, false, false, true, true, ARRAY['fish', 'shellfish'], ARRAY['efik', 'ibibio', 'vegetables', 'traditional'], 85),
('NIG_PEPPER_SOUP', 'nigerian-pepper-soup', 'Nigerian Pepper Soup', 'Spicy, aromatic broth made with native spices including uziza seeds, calabash nutmeg, and scotch bonnet peppers. Often prepared with goat, catfish, or chicken.', 'soup', 'iconic', 'nationwide', 'goat', 'boiled', 40, 4, false, false, true, true, ARRAY[]::TEXT[], ARRAY['spicy', 'warming', 'medicinal', 'traditional'], 95),
('NIG_OKRA_SOUP', 'okra-soup', 'Okra Soup', 'Traditional Nigerian soup made with fresh okra, palm oil, and assorted proteins. Known for its thick, mucilaginous texture.', 'soup', 'classic', 'nationwide', 'mixed', 'simmered', 40, 2, false, false, true, true, ARRAY['fish', 'shellfish'], ARRAY['okra', 'draw-soup', 'traditional', 'nutritious'], 85),
('NIG_GROUNDNUT_SOUP', 'groundnut-soup', 'Groundnut Soup', 'Creamy Nigerian soup made with ground peanuts, creating a rich and nutty base for meats and vegetables.', 'soup', 'classic', 'north', 'chicken', 'simmered', 50, 2, false, false, true, true, ARRAY['peanut'], ARRAY['peanut', 'creamy', 'northern', 'hearty'], 80),
('NIG_BANGA_SOUP', 'banga-soup', 'Banga Soup', 'Rich soup made from palm fruit extract, popular in the Niger Delta region. Served with starch or fufu.', 'soup', 'classic', 'south-south', 'mixed', 'simmered', 90, 3, false, false, true, true, ARRAY['fish'], ARRAY['palm-fruit', 'delta', 'urhobo', 'traditional'], 82),
('NIG_EDIKAIKONG', 'edikaikong', 'Edikaikong', 'Luxurious vegetable soup from Cross River State, made with a combination of fluted pumpkin leaves and waterleaf.', 'soup', 'classic', 'southeast', 'mixed', 'simmered', 60, 2, false, false, true, true, ARRAY['fish', 'shellfish'], ARRAY['efik', 'calabar', 'vegetables', 'premium'], 80),
('NIG_OHA_SOUP', 'oha-soup', 'Oha Soup', 'Traditional Igbo soup made with oha leaves and cocoyam paste, known for its unique flavor and thick consistency.', 'soup', 'traditional', 'southeast', 'mixed', 'simmered', 55, 2, false, false, true, true, ARRAY['fish'], ARRAY['igbo', 'oha-leaves', 'cocoyam', 'traditional'], 78),

-- SWALLOWS (7)
('NIG_POUNDED_YAM', 'pounded-yam', 'Pounded Yam', 'Smooth, stretchy dough made from boiled and pounded white yam. The king of Nigerian swallows, especially popular among the Yoruba.', 'swallow', 'iconic', 'southwest', NULL, 'boiled_pounded', 45, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['yoruba', 'yam', 'traditional', 'staple'], 95),
('NIG_EBA', 'eba', 'Eba (Garri)', 'Quick-to-prepare swallow made from cassava flour (garri) mixed with hot water. One of the most common Nigerian staples.', 'swallow', 'iconic', 'nationwide', NULL, 'mixed', 10, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['cassava', 'garri', 'quick', 'staple'], 92),
('NIG_AMALA', 'amala', 'Amala', 'Dark-colored swallow made from yam flour (elubo). A beloved Yoruba staple traditionally served with gbegiri and ewedu soups.', 'swallow', 'iconic', 'southwest', NULL, 'mixed', 15, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['yoruba', 'yam-flour', 'traditional', 'staple'], 88),
('NIG_FUFU', 'nigerian-fufu', 'Fufu', 'Fermented cassava swallow with a distinctive sour taste. Made by soaking cassava and then cooking it into a smooth dough.', 'swallow', 'classic', 'southeast', NULL, 'fermented', 20, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['cassava', 'fermented', 'igbo', 'staple'], 85),
('NIG_SEMOVITA', 'semovita', 'Semovita', 'Modern Nigerian swallow made from semolina wheat. Light in color and texture, popular in urban areas.', 'swallow', 'classic', 'nationwide', NULL, 'mixed', 10, 0, true, true, false, true, ARRAY['gluten'], ARRAY['semolina', 'modern', 'urban', 'staple'], 75),
('NIG_TUWO_SHINKAFA', 'tuwo-shinkafa', 'Tuwo Shinkafa', 'Northern Nigerian rice-based swallow with a smooth, sticky texture. Traditionally served with miyan kuka or other northern soups.', 'swallow', 'classic', 'north', NULL, 'boiled', 30, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['hausa', 'rice', 'northern', 'staple'], 78),
('NIG_STARCH', 'nigerian-starch', 'Starch', 'Cassava starch-based swallow popular in the Niger Delta region. Has a unique stretchy texture and is traditionally paired with banga soup.', 'swallow', 'regional', 'south-south', NULL, 'mixed', 15, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['delta', 'cassava-starch', 'urhobo', 'staple'], 70),

-- RICE DISHES (5)
('NIG_JOLLOF_RICE', 'jollof-rice', 'Jollof Rice', 'Nigeria''s most iconic dish - rice cooked in a rich tomato and pepper sauce with aromatic spices. The subject of West Africa''s famous jollof wars.', 'rice', 'iconic', 'nationwide', 'chicken', 'simmered', 60, 2, false, false, true, true, ARRAY[]::TEXT[], ARRAY['party', 'festive', 'tomato', 'iconic'], 100),
('NIG_FRIED_RICE', 'nigerian-fried-rice', 'Nigerian Fried Rice', 'Colorful rice dish with mixed vegetables, shrimp, and liver. A party staple often served alongside jollof rice.', 'rice', 'iconic', 'nationwide', 'mixed', 'fried', 45, 1, false, false, true, true, ARRAY['shellfish'], ARRAY['party', 'colorful', 'vegetables', 'festive'], 92),
('NIG_OFADA_RICE', 'ofada-rice', 'Ofada Rice with Ayamase', 'Locally grown unpolished Nigerian rice served with ayamase (designer stew) - a spicy green pepper sauce with assorted meats.', 'rice', 'classic', 'southwest', 'mixed', 'boiled', 50, 4, false, false, true, true, ARRAY[]::TEXT[], ARRAY['yoruba', 'local-rice', 'ayamase', 'spicy'], 85),
('NIG_COCONUT_RICE', 'coconut-rice', 'Coconut Rice', 'Fragrant rice cooked in coconut milk, giving it a rich, creamy flavor. A popular alternative to jollof at celebrations.', 'rice', 'classic', 'nationwide', NULL, 'simmered', 40, 1, true, true, true, true, ARRAY[]::TEXT[], ARRAY['coconut', 'creamy', 'festive', 'fragrant'], 78),
('NIG_NATIVE_JOLLOF', 'native-jollof', 'Native Jollof (Palm Oil Jollof)', 'Traditional version of jollof rice made with palm oil instead of vegetable oil, giving it an earthy, authentic flavor.', 'rice', 'traditional', 'southeast', 'mixed', 'simmered', 60, 2, false, false, true, true, ARRAY[]::TEXT[], ARRAY['palm-oil', 'traditional', 'village-style', 'authentic'], 72),

-- STREET FOOD (10)
('NIG_SUYA', 'suya', 'Suya', 'Nigeria''s famous grilled meat skewers, coated in yaji (suya spice) - a blend of ground peanuts, ginger, garlic, and cayenne pepper. Originally from the Hausa people.', 'street_food', 'iconic', 'north', 'beef', 'grilled', 30, 4, false, false, true, true, ARRAY['peanut'], ARRAY['hausa', 'grilled', 'spicy', 'street-food'], 98),
('NIG_AKARA', 'akara', 'Akara', 'Crispy deep-fried bean cakes made from black-eyed peas blended with peppers and onions. A beloved breakfast street food.', 'street_food', 'iconic', 'nationwide', NULL, 'deep_fried', 30, 2, true, true, true, true, ARRAY[]::TEXT[], ARRAY['breakfast', 'beans', 'fried', 'yoruba'], 92),
('NIG_MOIN_MOIN', 'moin-moin', 'Moin Moin', 'Steamed bean pudding made from pureed black-eyed peas with peppers, onions, and spices. Often enriched with eggs, fish, or crayfish.', 'street_food', 'iconic', 'southwest', NULL, 'steamed', 90, 2, false, false, true, true, ARRAY['egg', 'fish'], ARRAY['yoruba', 'beans', 'steamed', 'protein-rich'], 90),
('NIG_PUFF_PUFF', 'puff-puff', 'Puff Puff', 'Sweet, fluffy deep-fried dough balls - Nigeria''s beloved street snack. Similar to beignets or doughnuts.', 'snack', 'iconic', 'nationwide', NULL, 'deep_fried', 45, 0, true, false, false, true, ARRAY['gluten', 'egg'], ARRAY['sweet', 'fried', 'snack', 'street-food'], 95),
('NIG_CHIN_CHIN', 'chin-chin', 'Chin Chin', 'Crunchy, sweet fried pastry strips. A popular Nigerian snack especially during celebrations and holidays.', 'snack', 'classic', 'nationwide', NULL, 'deep_fried', 40, 0, true, false, false, false, ARRAY['gluten', 'egg', 'dairy'], ARRAY['sweet', 'crunchy', 'festive', 'snack'], 88),
('NIG_KILISHI', 'kilishi', 'Kilishi', 'Nigerian dried meat snack similar to jerky, heavily spiced with yaji seasoning. A traditional Hausa delicacy.', 'street_food', 'classic', 'north', 'beef', 'dried', 480, 4, false, false, true, true, ARRAY['peanut'], ARRAY['hausa', 'dried-meat', 'spicy', 'jerky'], 80),
('NIG_DODO', 'dodo', 'Dodo (Fried Plantain)', 'Sweet ripe plantains sliced and deep-fried until golden and caramelized. A ubiquitous Nigerian side dish and snack.', 'side', 'iconic', 'nationwide', NULL, 'deep_fried', 15, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['plantain', 'sweet', 'fried', 'side'], 95),
('NIG_BOLI', 'boli', 'Boli (Roasted Plantain)', 'Whole plantains roasted over charcoal until the skin is charred and the flesh is soft and sweet. Often served with groundnuts or fish.', 'street_food', 'classic', 'nationwide', NULL, 'roasted', 20, 0, true, true, true, true, ARRAY['peanut'], ARRAY['plantain', 'roasted', 'charcoal', 'street-food'], 85),
('NIG_GIZDODO', 'gizdodo', 'Gizdodo', 'Popular Nigerian appetizer combining peppered gizzards and fried plantains in a spicy tomato-pepper sauce.', 'appetizer', 'classic', 'nationwide', 'poultry', 'fried', 35, 3, false, false, true, true, ARRAY[]::TEXT[], ARRAY['gizzard', 'plantain', 'spicy', 'party-food'], 88),
('NIG_NKWOBI', 'nkwobi', 'Nkwobi', 'Spicy cow foot dish from the Igbo people, cooked in a thick palm oil and utazi leaf sauce. A popular bar snack.', 'appetizer', 'classic', 'southeast', 'beef', 'stewed', 120, 3, false, false, true, true, ARRAY[]::TEXT[], ARRAY['igbo', 'cow-foot', 'spicy', 'bar-snack'], 82),

-- MAINS AND STEWS (9)
('NIG_CHICKEN_STEW', 'nigerian-chicken-stew', 'Nigerian Chicken Stew', 'Rich tomato-based stew with tender chicken pieces. The backbone of Nigerian cuisine, served with rice, yam, or bread.', 'stew', 'iconic', 'nationwide', 'chicken', 'stewed', 60, 2, false, false, true, true, ARRAY[]::TEXT[], ARRAY['chicken', 'tomato', 'stew', 'everyday'], 95),
('NIG_BEEF_STEW', 'nigerian-beef-stew', 'Nigerian Beef Stew', 'Hearty tomato stew with tender beef chunks, slow-cooked until the meat falls apart. A Sunday lunch staple.', 'stew', 'iconic', 'nationwide', 'beef', 'stewed', 90, 2, false, false, true, true, ARRAY[]::TEXT[], ARRAY['beef', 'tomato', 'stew', 'sunday-lunch'], 92),
('NIG_PEPPERED_GOAT', 'peppered-goat', 'Peppered Goat Meat (Asun)', 'Spicy grilled goat meat chunks tossed in a fiery pepper sauce. A popular party and celebration dish.', 'main', 'classic', 'southwest', 'goat', 'grilled', 60, 4, false, false, true, true, ARRAY[]::TEXT[], ARRAY['goat', 'spicy', 'party', 'yoruba'], 88),
('NIG_CATFISH_PEPPER_SOUP', 'catfish-pepper-soup', 'Catfish Pepper Soup', 'Spicy and aromatic fish broth made with fresh catfish and traditional pepper soup spices. Known for its medicinal properties.', 'soup', 'classic', 'nationwide', 'fish', 'boiled', 35, 4, false, false, true, true, ARRAY['fish'], ARRAY['catfish', 'spicy', 'medicinal', 'warming'], 88),
('NIG_AYAMASE', 'ayamase', 'Ayamase (Designer Stew)', 'Bold green pepper stew made with green bell peppers and scotch bonnets, cooked in palm oil with assorted meats. A Yoruba specialty.', 'stew', 'classic', 'southwest', 'mixed', 'stewed', 60, 4, false, false, true, true, ARRAY[]::TEXT[], ARRAY['yoruba', 'green-pepper', 'spicy', 'palm-oil'], 85),
('NIG_PORRIDGE_YAM', 'porridge-yam', 'Porridge Yam', 'Comforting one-pot dish of yam cubes cooked in a spiced tomato and palm oil sauce. A hearty everyday meal.', 'main', 'classic', 'nationwide', NULL, 'simmered', 40, 2, true, false, true, true, ARRAY[]::TEXT[], ARRAY['yam', 'one-pot', 'comfort-food', 'everyday'], 82),
('NIG_EWA_AGOYIN', 'ewa-agoyin', 'Ewa Agoyin', 'Mashed beans served with a fiery palm oil and dried pepper sauce. A popular Lagos street food of Beninese origin.', 'main', 'classic', 'southwest', NULL, 'boiled', 90, 4, true, true, true, true, ARRAY[]::TEXT[], ARRAY['beans', 'lagos', 'spicy', 'street-food'], 85),
('NIG_GBEGIRI', 'gbegiri', 'Gbegiri', 'Smooth bean soup traditionally served with ewedu and amala. A Yoruba classic with a creamy, comforting texture.', 'soup', 'traditional', 'southwest', NULL, 'boiled', 60, 2, true, true, true, true, ARRAY[]::TEXT[], ARRAY['beans', 'yoruba', 'smooth', 'traditional'], 78),
('NIG_EWEDU', 'ewedu', 'Ewedu', 'Silky jute leaf soup with a distinctive mucilaginous texture. Traditionally paired with gbegiri and amala.', 'soup', 'classic', 'southwest', NULL, 'boiled', 20, 1, true, true, true, true, ARRAY[]::TEXT[], ARRAY['jute-leaf', 'yoruba', 'slimy', 'traditional'], 80),

-- BEVERAGES AND SNACKS (8)
('NIG_ZOBO', 'zobo', 'Zobo (Hibiscus Drink)', 'Refreshing deep red drink made from dried hibiscus flowers, flavored with ginger, cloves, and citrus. Nigeria''s most popular traditional beverage.', 'beverage', 'iconic', 'nationwide', NULL, 'boiled', 30, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['hibiscus', 'refreshing', 'traditional', 'healthy'], 95),
('NIG_KUNU', 'kunu', 'Kunu', 'Traditional millet-based drink from Northern Nigeria, fermented and flavored with ginger, cloves, and sweet potato. Served cold and refreshing.', 'beverage', 'classic', 'north', NULL, 'fermented', 720, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['millet', 'fermented', 'hausa', 'probiotic'], 82),
('NIG_FURA_DA_NONO', 'fura-da-nono', 'Fura da Nono', 'Traditional Hausa drink combining fura (millet balls) with nono (fermented milk). A nutritious and filling beverage.', 'beverage', 'classic', 'north', NULL, 'fermented', 60, 0, true, false, true, false, ARRAY['dairy'], ARRAY['millet', 'fermented-milk', 'hausa', 'fulani'], 78),
('NIG_PALM_WINE', 'palm-wine', 'Palm Wine', 'Traditional alcoholic beverage tapped from palm trees. Fresh palm wine is sweet and mildly alcoholic, becoming stronger as it ferments.', 'beverage', 'traditional', 'south', NULL, 'fermented', 0, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['palm-tree', 'alcoholic', 'traditional', 'ceremonial'], 75),
('NIG_TIGER_NUT_DRINK', 'tiger-nut-drink', 'Tiger Nut Drink (Kunun Aya)', 'Creamy, sweet drink made from tiger nuts, dates, and coconut. A popular Nigerian health drink.', 'beverage', 'classic', 'north', NULL, 'blended', 30, 0, true, true, true, true, ARRAY[]::TEXT[], ARRAY['tiger-nut', 'healthy', 'creamy', 'hausa'], 80),
('NIG_PAP', 'pap', 'Pap (Ogi/Akamu)', 'Smooth fermented corn porridge, often served as breakfast with akara or moin moin. Can be made from corn, millet, or sorghum.', 'beverage', 'iconic', 'nationwide', NULL, 'fermented', 15, 0, true, false, true, false, ARRAY['dairy'], ARRAY['corn', 'fermented', 'breakfast', 'porridge'], 90),
('NIG_MEAT_PIE', 'nigerian-meat-pie', 'Nigerian Meat Pie', 'Flaky pastry filled with seasoned minced meat, potatoes, and carrots. A beloved Nigerian snack with British colonial origins.', 'snack', 'iconic', 'nationwide', 'beef', 'baked', 60, 1, false, false, false, false, ARRAY['gluten', 'dairy'], ARRAY['pastry', 'meat', 'british-influence', 'snack'], 92),
('NIG_SAUSAGE_ROLL', 'nigerian-sausage-roll', 'Nigerian Sausage Roll', 'Flaky pastry wrapped around seasoned minced meat. A popular Nigerian party snack and breakfast item.', 'snack', 'classic', 'nationwide', 'beef', 'baked', 45, 1, false, false, false, false, ARRAY['gluten', 'dairy'], ARRAY['pastry', 'sausage', 'party', 'snack'], 88);

SELECT 'Inserted 49 Nigerian dishes' AS status;
