-- 26. Augustiner Helles
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('6ff5c1a7-74b2-4d02-a49b-299c69495a23', 'augustiner-helles', 'augustiner-helles', '{"en":"Augustiner Helles"}'::jsonb, 'international_classic', 'lager', 'helles', '{"german","bavarian","lager","munich","crisp","traditional","cult-favorite"}', 'Germany', 'DE', 'Bavaria', 'Munich', '{"en":"Augustiner-Bräu München"}'::jsonb, 1328, 'regional', false, '1328', '{"en":"Augustiner-Bräu is Munich''s oldest independent brewery, founded in 1328 by Augustinian monks. Unlike other Munich breweries, Augustiner has remained fiercely independent and traditional, refusing to export widely or pasteurize their beer. Their Helles, introduced in the early 1900s following the Munich Helles style innovation, is considered by many locals to be the finest beer in Munich. The brewery still uses wooden barrels for some of their draft beer, a rarity in modern brewing. Augustiner maintains a cult following among beer enthusiasts for its uncompromising quality and traditional methods."}'::jsonb, '{}', '{"en":"Named after the Augustinian monks who founded the brewery"}'::jsonb, NULL, '{"en":"The quintessential Munich Helles from the city''s most traditional brewery. Crystal-clear pale golden lager with delicate malt sweetness, noble hop character, and pristine drinkability. Considered by many to be the finest example of the Helles style."}'::jsonb, '{"en":"Munich''s Finest - The Cult Classic Helles"}'::jsonb, 5.2, NULL, NULL, 20, NULL, NULL, 4, NULL, NULL, 'pale_gold', 'clear', 'medium', 'medium', 'bottom_fermented', '{"malty","crisp","clean","balanced","bready","subtle-hop","refreshing"}', '{"en":"Delicate malt sweetness with notes of fresh bread and honey, balanced by subtle noble hop bitterness. Clean lager fermentation character with no fruity esters. Extremely drinkable with a crisp, dry finish that invites another sip."}'::jsonb, '{"en":"Delicate malt bread, light honey, subtle floral and herbal hops"}'::jsonb, '{"en":"Soft malt sweetness with perfect balance and clean lager character"}'::jsonb, '{"en":"Crisp, dry finish with lingering subtle hop bitterness and malt sweetness"}'::jsonb, NULL, 2, 3, '{"Munich malt","Pilsner malt"}', '{"Hallertauer Mittelfrüh","Tettnanger"}', 'Traditional Munich lager yeast', '{}', NULL, '{}', 'mug', 'cold', 6, 8, '{"en":"Pour into a traditional Maßkrug (beer mug) or Willibecher glass at a steady angle to create a 1-2 finger white head. Best enjoyed fresh and cold."}'::jsonb, true, '1-2 fingers', '{"german-food","grilled-meats","salads","light-dishes"}', '{"en":"Perfect beer garden companion with Hendl (roast chicken), Schweinshaxe (pork knuckle), pretzels, Obatzda cheese spread, and grilled sausages. Also excellent with lighter fare and salads."}'::jsonb, '{"Obatzda","Emmental","Butterkäse","Limburger"}', '{"German","Bavarian","Grilled","Beer Garden Food"}', NULL, '{"all_year","summer","beer-garden"}', '{"casual","beer-garden","dinner","party"}', false, false, false, true, '{"bottle","draft"}', '{"500","330"}', '{"paulaner-hefeweizen","spaten-oktoberfestbier"}', 'year_round', 'mid', 90, 'https://www.augustiner-braeu.de', 'Official Augustiner brewery and Munich beer culture', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 27. Spaten Oktoberfestbier
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('241452ee-7344-4351-a451-ce1bec04c642', 'spaten-oktoberfestbier', 'spaten-oktoberfestbier', '{"en":"Spaten Oktoberfestbier"}'::jsonb, 'international_classic', 'lager', 'marzen', '{"german","bavarian","lager","oktoberfest","munich","amber","festbier","seasonal"}', 'Germany', 'DE', 'Bavaria', 'Munich', '{"en":"Spaten-Franziskaner-Bräu"}'::jsonb, 1397, 'regional', false, '1872', '{"en":"Spaten is one of Munich''s legendary breweries, founded in 1397. In 1872, Spaten brewer Josef Sedlmayr created the Oktoberfestbier style specifically for the Oktoberfest celebration, introducing the amber Märzen-style beer that became synonymous with the festival. Before this, darker beers dominated. Spaten''s innovation revolutionized Oktoberfest and created a new beer category. The brewery was also a pioneer in lager brewing techniques and refrigeration technology in the 19th century. Today, Spaten remains one of the six official Oktoberfest breweries allowed to serve at the festival, and their Oktoberfestbier is considered the original and most authentic version of this celebrated style."}'::jsonb, '{}', '{"en":"Spaten means \"spade\" in German, referencing the brewery''s historic brewing tools"}'::jsonb, NULL, '{"en":"The original Oktoberfest beer created in 1872. Rich amber lager with toasty malt character, subtle caramel sweetness, and clean finish. This is the beer that defined the Märzen/Oktoberfest style and remains the authentic taste of Munich''s most famous celebration."}'::jsonb, '{"en":"The Original Oktoberfest Beer Since 1872"}'::jsonb, 5.9, NULL, NULL, 22, NULL, NULL, 14, NULL, NULL, 'amber', 'clear', 'medium', 'medium', 'bottom_fermented', '{"malty","toasty","caramel","bready","clean","balanced","smooth"}', '{"en":"Rich toasted malt with notes of fresh bread, caramel, and subtle toffee. Smooth malt sweetness balanced by moderate noble hop bitterness. Clean lager fermentation with no fruity esters. Full-bodied yet remarkably drinkable, with a dry finish that prevents cloying sweetness."}'::jsonb, '{"en":"Toasted bread, caramel malt, subtle toffee, light noble hops"}'::jsonb, '{"en":"Rich malty sweetness with toasty character and smooth body"}'::jsonb, '{"en":"Clean, dry finish with lingering malt character and subtle hop bitterness"}'::jsonb, NULL, 2, 4, '{"Munich malt","Vienna malt","Pilsner malt"}', '{"Hallertauer Tradition","Tettnanger"}', 'Traditional Munich lager yeast', '{}', NULL, '{}', 'mug', 'cold', 7, 9, '{"en":"Serve in a traditional 1-liter Maßkrug (Oktoberfest mug). Pour at steady angle to create a dense 2-finger head. Traditional at Oktoberfest tents."}'::jsonb, true, '2-3 fingers', '{"german-food","grilled-meats","sausages","roasted-dishes"}', '{"en":"Classic pairing with Oktoberfest foods: Hendl (roast chicken), Schweinshaxe (roasted pork knuckle), bratwurst, pretzels with Obatzda, roasted meats, and hearty Bavarian fare."}'::jsonb, '{"Obatzda","Emmental","Gruyère","Aged Cheddar"}', '{"German","Bavarian","Grilled","Roasted Meats"}', NULL, '{"fall","oktoberfest","autumn"}', '{"oktoberfest","celebration","party","festival","dinner"}', false, false, false, true, '{"bottle","draft","can"}', '{"500","330"}', '{"paulaner-oktoberfest","augustiner-helles"}', 'seasonal', 'mid', 85, 'https://www.spaten.de', 'Official Spaten brewery and Oktoberfest history', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 28. Erdinger Weissbier
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('deb3bb14-ca24-4570-8fa1-3389e614269f', 'erdinger-weissbier', 'erdinger-weissbier', '{"en":"Erdinger Weissbier"}'::jsonb, 'international_classic', 'wheat', 'hefeweizen', '{"german","bavarian","wheat","unfiltered","banana","clove","world-leader","traditional"}', 'Germany', 'DE', 'Bavaria', 'Erding', '{"en":"Erdinger Weißbräu"}'::jsonb, 1886, 'regional', false, '1886', '{"en":"Erdinger Weißbräu was founded in 1886 by Johann Kienle in the town of Erding, northeast of Munich. The name \"Erdinger\" comes from the town''s name. Initially a small local brewery, Erdinger focused exclusively on wheat beer when most breweries were diversifying. This specialization proved brilliant - today Erdinger is the world''s largest wheat beer brewery. The brewery remains family-owned and has become synonymous with premium Bavarian wheat beer globally. They pioneered modern wheat beer production techniques while maintaining traditional yeast strains and recipes. Erdinger is particularly proud of their yeast management, using the same proprietary strain for over a century."}'::jsonb, '{}', '{"en":"Named after the town of Erding in Bavaria where the brewery is located"}'::jsonb, NULL, '{"en":"The world''s most popular wheat beer from Bavaria''s largest wheat beer brewery. Classic Hefeweizen with pronounced banana and clove character, cloudy golden color, and refreshing drinkability. Erdinger represents the pinnacle of modern wheat beer production while honoring traditional Bavarian brewing."}'::jsonb, '{"en":"World''s Leading Wheat Beer"}'::jsonb, 5.3, NULL, NULL, 13, NULL, NULL, 6, NULL, NULL, 'gold', 'hazy', 'high', 'medium', 'top_fermented', '{"banana","clove","creamy","refreshing","wheaty","fruity","spicy","smooth"}', '{"en":"Classic Bavarian wheat beer profile with prominent banana and clove phenols from their proprietary yeast. Smooth wheat malt character with hints of vanilla and citrus. High carbonation creates a lively mouthfeel. Clean, refreshing finish with minimal bitterness that makes it exceptionally drinkable."}'::jsonb, '{"en":"Banana, clove, subtle vanilla, hints of citrus and bubblegum"}'::jsonb, '{"en":"Smooth, creamy wheat character with lively banana-clove yeast expression"}'::jsonb, '{"en":"Clean, refreshing finish with lingering fruity yeast character"}'::jsonb, NULL, 1, 3, '{"Wheat malt (55%)","Barley malt"}', '{"Hallertauer Tradition","Perle"}', 'Proprietary Erdinger wheat beer yeast (100+ year old strain)', '{}', NULL, '{}', 'weizen', 'cold', 6, 8, '{"en":"Use the classic Erdinger vase-shaped Weizen glass. Pour 2/3 of bottle at angle, leave remaining beer. Gently roll bottle to resuspend yeast, then pour remainder creating a thick, fluffy head."}'::jsonb, true, '3-4 fingers', '{"german-food","seafood","salads","breakfast","light-dishes"}', '{"en":"Traditional with Weisswurst and pretzels for Bavarian breakfast. Also excellent with grilled fish, seafood platters, Caesar salad, omelets, mild cheeses, and fruit-based desserts."}'::jsonb, '{"Obatzda","Brie","Camembert","Fresh Goat Cheese"}', '{"German","Bavarian","Seafood","Brunch"}', NULL, '{"all_year","summer","spring"}', '{"brunch","casual","party","dinner","sports"}', false, false, false, true, '{"bottle","draft","can"}', '{"500","330"}', '{"paulaner-hefeweizen","weihenstephaner-hefeweissbier"}', 'year_round', 'mid', 91, 'https://www.erdinger.de', 'Official Erdinger brewery and world wheat beer leader', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 29. Bitburger Premium Pils
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('899c5555-e378-4ae1-b258-2135d6b59dc8', 'bitburger-premium-pils', 'bitburger-premium-pils', '{"en":"Bitburger Premium Pils"}'::jsonb, 'international_classic', 'lager', 'pilsner', '{"german","pilsner","lager","crisp","hoppy","traditional","premium"}', 'Germany', 'DE', 'Rhineland-Palatinate', 'Bitburg', '{"en":"Bitburger Brauerei"}'::jsonb, 1817, 'regional', false, '1817', '{"en":"Bitburger Brewery was founded in 1817 by Johann Peter Wallenborn in the small Eifel town of Bitburg. The brewery began brewing pilsner in 1883, adopting the new bottom-fermented style that originated in Pilsen. Bitburger pioneered the German Pilsner style, which is hoppier and drier than Czech Pilsner. Their famous slogan \"Bitte ein Bit\" (A Bit, please) became one of Germany''s most successful advertising campaigns. The brewery has remained family-owned for seven generations. Today, Bitburger is one of Germany''s largest and most exported beers, representing the pinnacle of German Pilsner brewing with its distinctively crisp, hoppy character."}'::jsonb, '{}', '{"en":"Named after the town of Bitburg where the brewery was founded"}'::jsonb, NULL, '{"en":"Germany''s definitive premium pilsner. Crystal-clear pale golden lager with pronounced noble hop aroma, crisp bitterness, and clean, dry finish. Bitburger exemplifies the German Pilsner style with its perfect balance of hop character and drinkability."}'::jsonb, '{"en":"Bitte ein Bit - Germany''s Premium Pilsner"}'::jsonb, 4.8, NULL, NULL, 37, NULL, NULL, 3, NULL, NULL, 'pale_gold', 'clear', 'high', 'light', 'bottom_fermented', '{"hoppy","crisp","clean","bitter","dry","refreshing","balanced"}', '{"en":"Pronounced noble hop bitterness with herbal, floral, and spicy notes. Clean pilsner malt backbone provides subtle sweetness that balances the assertive hop character. High carbonation and dry finish create exceptional refreshment. Crisp, clean lager fermentation with no fruity esters."}'::jsonb, '{"en":"Noble hops with floral, herbal, and spicy notes, light pilsner malt"}'::jsonb, '{"en":"Crisp hop bitterness with clean malt character and lively carbonation"}'::jsonb, '{"en":"Dry, crisp finish with lingering noble hop bitterness"}'::jsonb, NULL, 4, 2, '{"Pilsner malt"}', '{"Hallertauer","Tettnanger","Perle"}', 'German Pilsner lager yeast', '{}', NULL, '{}', 'pilsner', 'cold', 4, 6, '{"en":"Serve in a traditional pilsner glass (tall, tapered). Pour down the center to create a dense 2-3 finger white head. The tall glass showcases clarity and carbonation."}'::jsonb, true, '2-3 fingers', '{"german-food","fried-food","seafood","spicy-food"}', '{"en":"Excellent with fried foods, fish and chips, schnitzel, grilled sausages, spicy dishes, salads, and shellfish. The crisp bitterness cuts through rich, fatty foods perfectly."}'::jsonb, '{"Gouda","Emmental","Gruyère","Aged Cheddar"}', '{"German","Fried Food","Asian","Seafood"}', NULL, '{"all_year","summer","spring"}', '{"casual","dinner","party","sports","outdoor"}', false, false, false, true, '{"bottle","draft","can"}', '{"500","330","275"}', '{"augustiner-helles","spaten-oktoberfestbier"}', 'year_round', 'mid', 87, 'https://www.bitburger.de', 'Official Bitburger brewery and German Pilsner tradition', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 30. Sierra Nevada Pale Ale
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('4ffaf8d5-accb-435f-b633-791bd74b877d', 'sierra-nevada-pale-ale', 'sierra-nevada-pale-ale-craft-ipa', '{"en":"Sierra Nevada Pale Ale"}'::jsonb, 'craft_classic', 'ale', 'american_pale_ale', '{"craft","american","pioneer","hoppy","iconic"}', 'United States', 'US', NULL, 'Chico, California', '{"en":"Sierra Nevada Brewing Co."}'::jsonb, 1980, 'craft', false, '1980', '{"en":"Sierra Nevada Pale Ale is the beer that launched the American craft beer revolution. Founded by Ken Grossman and Paul Camusi in 1980, it was one of the first breweries to use whole-cone Cascade hops, creating a bold, piney flavor that defined the American Pale Ale style. This beer single-handedly inspired countless brewers and remains a benchmark for the style."}'::jsonb, '{"Great American Beer Festival Gold","World Beer Cup Winner"}', '{"en":"Named after the Sierra Nevada mountain range in California"}'::jsonb, NULL, '{"en":"A revolutionary American Pale Ale featuring bold Cascade hops with piney, citrus notes. Medium-bodied with a perfect balance of malt sweetness and hop bitterness, it set the standard for craft beer in America."}'::jsonb, '{"en":"The Original Craft Beer Revolution"}'::jsonb, 5.6, NULL, NULL, 38, NULL, NULL, 11, NULL, NULL, 'amber', 'clear', 'medium', 'medium', 'top_fermented', '{"hoppy","piney","citrus","balanced","crisp"}', '{"en":"Bold pine and citrus hop character balanced by a smooth malt backbone. Cascade hops provide distinctive grapefruit and floral notes with a clean, dry finish."}'::jsonb, '{"en":"Piney Cascade hops with grapefruit, floral notes, and subtle caramel malt"}'::jsonb, NULL, '{"en":"Clean, dry finish with lingering hop bitterness"}'::jsonb, NULL, 4, 2, '{"Pale malt","Caramel malt"}', '{"Cascade","Magnum"}', 'Ale yeast', '{}', NULL, '{}', 'pint', 'cool', 7, 10, '{"en":"Pour into a clean glass at a slight angle, creating a 1-2 finger white head"}'::jsonb, true, NULL, '{"burgers","grilled-meats","spicy-foods"}', '{"en":"Perfect with burgers, grilled salmon, spicy Mexican food, and aged cheddar. The hop bitterness cuts through rich, fatty foods."}'::jsonb, '{"Aged Cheddar","Gruyere","Blue cheese"}', '{"American","Mexican","BBQ"}', NULL, '{"all_year","summer"}', '{"casual","bbq","sports","dinner"}', false, false, false, true, '{"bottle","can","draft"}', '{"355","473"}', '{}', 'year_round', 'mid', 92, 'https://sierranevada.com', 'Official Sierra Nevada website and craft beer history', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


