-- 36. Newcastle Brown Ale
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('824c0f51-1644-4147-b27e-3cb25a27f24c', 'newcastle-brown-ale', 'newcastle-brown-ale-british-ale', '{"en":"Newcastle Brown Ale"}'::jsonb, 'international_classic', 'ale', 'brown_ale', '{"british","brown-ale","iconic","geordie","classic"}', 'United Kingdom', 'GB', NULL, 'Newcastle upon Tyne', '{"en":"Newcastle Breweries"}'::jsonb, 1927, 'macro', false, '1927', '{"en":"Created in 1927 by Colonel Jim Porter, Newcastle Brown Ale quickly became the most popular bottled beer in the UK. The beer was specifically developed to appeal to the working-class population of Newcastle. Its distinctive blue star logo became iconic, and the beer earned the nickname \"The Dog\" among locals. It won the Challenge Cup for Champion Beer of Britain in its first year of production."}'::jsonb, '{"Challenge Cup 1927","International Beer Challenge Gold"}', '{"en":"Named after the city of Newcastle upon Tyne in Northeast England"}'::jsonb, NULL, '{"en":"A smooth, easy-drinking English brown ale with a distinctive ruby-brown color. This iconic beer combines a subtle sweetness with a gentle nutty character, creating a balanced and approachable beer that has become synonymous with British brewing tradition."}'::jsonb, '{"en":"The One and Only"}'::jsonb, 4.7, NULL, NULL, 23, NULL, NULL, 18, NULL, NULL, 'brown', 'clear', 'medium', 'medium', 'top_fermented', '{"smooth","nutty","caramel","malty","sweet","balanced"}', '{"en":"Smooth and mellow with flavors of caramel, toffee, and toasted nuts. A subtle sweetness is balanced by gentle hop bitterness. The beer has a creamy mouthfeel with notes of dried fruit and a hint of chocolate in the background."}'::jsonb, '{"en":"Gentle malt sweetness with caramel, toffee, and nutty notes; subtle fruity esters and minimal hop presence"}'::jsonb, NULL, '{"en":"Smooth, clean finish with lingering sweetness and a gentle dry note"}'::jsonb, NULL, 2, 3, '{"Pale malt","Crystal malt","Chocolate malt"}', '{"English hops","Fuggles","Goldings"}', 'English ale yeast', '{}', NULL, '{}', 'nonic', 'cool', 8, 10, '{"en":"Pour in one smooth motion into a tilted glass to create a small creamy head"}'::jsonb, true, NULL, '{"pub-food","grilled-meats","hearty-dishes"}', '{"en":"Excellent with hearty British fare: meat pies, grilled sausages, roasted chicken, burgers, and sharp cheddar. The nutty sweetness pairs well with barbecue and smoked meats. Also great with chocolate desserts."}'::jsonb, '{"Sharp Cheddar","Gouda","Gruyère","Blue cheese"}', '{"British","American BBQ","Pub fare","Comfort food"}', NULL, '{"all_year","autumn","winter"}', '{"casual","pub_night","sports","relaxing","bbq"}', false, false, false, true, '{"bottle","can","draft"}', '{"330","500","550"}', '{}', 'year_round', 'value', 82, 'https://www.newcastlebrown.com', 'Official Newcastle Brown Ale website and brewing history', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 37. Bass Pale Ale
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('811d4b42-2f1a-47c5-8c59-aac917f15da2', 'bass-pale-ale', 'bass-pale-ale-british-ale', '{"en":"Bass Pale Ale"}'::jsonb, 'international_classic', 'ale', 'pale_ale', '{"british","historic","pale-ale","burton","iconic"}', 'United Kingdom', 'GB', NULL, 'Burton upon Trent', '{"en":"Bass Brewery"}'::jsonb, 1777, 'macro', false, '1777', '{"en":"Founded by William Bass in 1777, Bass Pale Ale became one of the world''s first truly global beer brands. The famous red triangle trademark, registered in 1876, was the UK''s first registered trademark. Bass pioneered pale ale brewing in Burton upon Trent, utilizing the town''s unique mineral-rich water. The beer''s quality was so renowned that it appeared in Édouard Manet''s famous painting \"A Bar at the Folies-Bergère\" (1882)."}'::jsonb, '{"First UK Registered Trademark 1876","International Brewing Awards"}', '{"en":"Named after founder William Bass and the pale ale style it helped define"}'::jsonb, NULL, '{"en":"A historic English pale ale brewed with the legendary Burton water. This pioneering beer showcases a balanced malt character with distinctive hop bitterness, representing the classic Burton pale ale style that influenced brewers worldwide. The iconic red triangle makes it one of the most recognizable beer brands in history."}'::jsonb, '{"en":"The Original Pale Ale"}'::jsonb, 5.1, NULL, NULL, 34, NULL, NULL, 10, NULL, NULL, 'amber', 'brilliant', 'medium', 'medium', 'top_fermented', '{"balanced","hoppy","malty","biscuity","crisp","traditional"}', '{"en":"Well-balanced pale ale with a firm malt backbone featuring biscuit and light caramel notes. The Burton water imparts a distinctive mineral quality that enhances the hop bitterness. Classic English hop character provides earthy, floral, and subtle spicy notes. Crisp and refreshing with a clean, dry finish."}'::jsonb, '{"en":"Malt-forward with biscuity sweetness, earthy English hops, and subtle fruity esters with mineral undertones"}'::jsonb, NULL, '{"en":"Clean, dry finish with lingering hop bitterness and subtle malt sweetness"}'::jsonb, NULL, 3, 2, '{"Pale malt","Crystal malt"}', '{"Fuggles","Goldings","Challenger"}', 'Bass house yeast strain', '{}', 'Burton upon Trent water (high in calcium sulfate)', '{}', 'nonic', 'cool', 8, 11, '{"en":"Pour steadily into a tilted glass, then straighten to form a moderate creamy head"}'::jsonb, true, NULL, '{"british-classics","roasted-meats","traditional-fare"}', '{"en":"Perfect companion to traditional British dishes: roast beef, Yorkshire pudding, meat pies, ploughman''s lunch, and aged cheddar. The balanced profile works well with grilled meats, fish and chips, and hearty stews. Also pairs nicely with curry dishes."}'::jsonb, '{"Aged Cheddar","Stilton","Lancashire","Double Gloucester"}', '{"British","English","Indian curry","Roasted meats"}', NULL, '{"all_year","autumn","winter"}', '{"casual","pub_night","dinner","tasting","pairing_dinner"}', false, false, false, true, '{"bottle","can","draft"}', '{"330","440","500"}', '{}', 'year_round', 'mid', 75, 'https://en.wikipedia.org/wiki/Bass_Brewery', 'Historic brewing records and Bass Brewery heritage information', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 38. Boddingtons Pub Ale
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('f1ecb70f-9b8b-455e-bdaf-2bc908456d85', 'boddingtons-pub-ale', 'boddingtons-pub-ale-british-ale', '{"en":"Boddingtons Pub Ale"}'::jsonb, 'international_classic', 'ale', 'cream_ale', '{"british","cream-ale","nitro","smooth","manchester"}', 'United Kingdom', 'GB', NULL, 'Manchester', '{"en":"Boddingtons Brewery"}'::jsonb, 1778, 'macro', false, '1778', '{"en":"Founded in 1778 at the Strangeways Brewery in Manchester, Boddingtons became famous for its distinctively smooth and creamy texture. The beer gained national prominence in the 1990s with its memorable \"Cream of Manchester\" advertising campaign. Originally a cask ale, Boddingtons pioneered the use of nitrogen widget technology in cans, creating the signature creamy head that made it a pub favorite across Britain."}'::jsonb, '{"CAMRA Awards","British Brewing Awards"}', '{"en":"Named after the Boddington family, founders of the brewery"}'::jsonb, NULL, '{"en":"A smooth, creamy golden ale famous for its velvety texture and tight, long-lasting head. Known as \"The Cream of Manchester,\" this beer delivers a light, refreshing taste with a distinctive smooth mouthfeel created by nitrogen dispense. The perfect balance of malt sweetness and hop bitterness makes it incredibly drinkable."}'::jsonb, '{"en":"The Cream of Manchester"}'::jsonb, 4.7, NULL, NULL, 20, NULL, NULL, 6, NULL, NULL, 'gold', 'clear', 'medium', 'medium_light', 'top_fermented', '{"smooth","creamy","balanced","malty","refreshing","clean"}', '{"en":"Incredibly smooth and creamy with a light malt sweetness featuring biscuit and bread notes. Gentle hop bitterness provides balance without overpowering. The nitrogen dispense creates a silky, velvety mouthfeel. Light fruit esters add subtle complexity. Clean, refreshing finish with minimal aftertaste."}'::jsonb, '{"en":"Light malt with bready and biscuit notes, subtle hop character, and delicate fruity esters"}'::jsonb, NULL, '{"en":"Smooth, clean finish with a gentle dry note and subtle lingering sweetness"}'::jsonb, NULL, 2, 2, '{"Pale malt","Wheat malt"}', '{"English hops","Fuggles"}', 'English ale yeast', '{}', NULL, '{}', 'pint', 'cool', 6, 8, '{"en":"For canned version: open can, turn upside down into glass for cascading effect. For draft: pour smoothly to create the signature creamy head"}'::jsonb, true, NULL, '{"pub-food","light-dishes","british-classics"}', '{"en":"Excellent with traditional British pub fare: fish and chips, chicken dishes, mild curries, sandwiches, and salads. The smooth, creamy texture pairs well with fried foods. Also complements mild cheeses and light seafood dishes."}'::jsonb, '{"Mild Cheddar","Cheshire","Wensleydale","Lancashire"}', '{"British","Pub fare","Fish and chips","Light meals"}', NULL, '{"all_year","summer"}', '{"casual","pub_night","sports","relaxing","bbq"}', false, false, false, true, '{"can","draft","bottle"}', '{"440","500"}', '{}', 'year_round', 'value', 78, 'https://www.boddingtons.com', 'Official Boddingtons website and brewing heritage information', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 39. Samuel Smith Taddy Porter
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('a29ab182-d415-45b2-be26-a3c719c5df71', 'samuel-smith-taddy-porter', 'samuel-smith-taddy-porter-british-ale', '{"en":"Samuel Smith Taddy Porter"}'::jsonb, 'craft', 'stout_porter', 'porter', '{"british","porter","traditional","yorkshire","classic"}', 'United Kingdom', 'GB', NULL, 'Tadcaster', '{"en":"Samuel Smith Old Brewery"}'::jsonb, 1758, 'regional', false, '1758', '{"en":"Samuel Smith''s Old Brewery in Tadcaster, Yorkshire is Britain''s oldest brewery, dating back to 1758. Taddy Porter represents the brewery''s commitment to traditional methods, using the same Yorkshire Square fermentation system and water from the original well. The brewery still employs coopers to maintain traditional oak casks and uses shire horses for local deliveries. This porter is brewed exactly as it was centuries ago, making it one of the most authentic traditional English porters available."}'::jsonb, '{"Great British Beer Festival Awards","World Beer Awards"}', '{"en":"Named after the town of Tadcaster (nicknamed \"Taddy\") where the brewery is located"}'::jsonb, NULL, '{"en":"A classic English porter brewed using traditional Yorkshire Square fermentation. This deep, dark beer showcases rich roasted malt character with notes of chocolate, coffee, and dried fruit. Smooth and full-bodied with a perfect balance of sweetness and roasted bitterness, representing the authentic taste of historic English porter."}'::jsonb, '{"en":"Traditional Yorkshire Porter"}'::jsonb, 5, NULL, NULL, 30, NULL, NULL, 40, NULL, NULL, 'dark_brown', 'opaque', 'medium', 'medium_full', 'top_fermented', '{"roasty","chocolate","coffee","malty","smooth","complex","fruity"}', '{"en":"Rich and complex with dominant roasted malt flavors of dark chocolate, espresso, and burnt caramel. Subtle notes of dried fruit, licorice, and toffee add depth. The Yorkshire Square fermentation imparts a distinctive fruity character. Smooth, creamy mouthfeel with a perfect balance between malt sweetness and roasted bitterness."}'::jsonb, '{"en":"Rich roasted malt with chocolate, coffee, and caramel notes; subtle dark fruit and licorice undertones"}'::jsonb, NULL, '{"en":"Long, smooth finish with lingering roasted notes and subtle sweetness; dry but not astringent"}'::jsonb, NULL, 3, 3, '{"Pale malt","Crystal malt","Chocolate malt","Black malt"}', '{"Fuggles","Goldings"}', 'Samuel Smith house yeast (Yorkshire Square strain)', '{}', 'Original well water from Tadcaster', '{}', 'pint', 'cellar', 10, 13, '{"en":"Pour gently into a tilted pint glass to minimize foam, then straighten to create a modest tan head. Allow to warm slightly for fuller flavor development."}'::jsonb, true, NULL, '{"roasted-meats","hearty-dishes","desserts","cheese"}', '{"en":"Exceptional with rich, hearty foods: roasted meats, steak and kidney pie, venison, game birds, and aged cheeses. The roasted character pairs beautifully with chocolate desserts, tiramisu, and coffee-based sweets. Also excellent with oysters, smoked fish, and barbecued meats."}'::jsonb, '{"Stilton","Aged Cheddar","Wensleydale","Caerphilly","Roquefort"}', '{"British","Game meats","Chocolate desserts","BBQ"}', NULL, '{"all_year","autumn","winter"}', '{"dinner","pairing_dinner","relaxing","tasting","pub_night"}', false, false, false, true, '{"bottle","draft","cask"}', '{"330","550"}', '{}', 'year_round', 'craft', 70, 'https://www.samuelsmithsbrewery.co.uk', 'Official Samuel Smith Brewery website and traditional brewing methods documentation', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 40. Samuel Smith Oatmeal Stout
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('afe956e4-0368-4b2f-ad52-34c96388d837', 'samuel-smith-oatmeal-stout', 'samuel-smith-oatmeal-stout-british', '{"en":"Samuel Smith Oatmeal Stout"}'::jsonb, 'traditional_classic', 'stout', 'oatmeal_stout', '{"british","yorkshire","traditional","smooth","velvety","historic-brewery","bottle-conditioned"}', 'United Kingdom', 'GB', 'Yorkshire', 'Tadcaster', '{"en":"Samuel Smith''s Old Brewery"}'::jsonb, 1758, 'independent', false, '1980', '{"en":"Samuel Smith''s Old Brewery is Yorkshire''s oldest brewery, founded in 1758. The Oatmeal Stout was introduced in 1980 as a revival of the traditional oatmeal stout style that had largely disappeared after WWII. Samuel Smith still uses traditional Yorkshire Square fermentation vessels and draws water from the original well dug in 1758. The brewery is one of the few remaining independent breweries still using traditional methods and refusing to pasteurize their beers. The addition of oatmeal creates an exceptionally smooth, silky mouthfeel."}'::jsonb, '{"Great British Beer Festival awards","CAMRA recognition"}', '{"en":"Named after founder Samuel Smith and the use of oatmeal in the brewing process"}'::jsonb, '{"en":"Helped revive the oatmeal stout style and represents traditional Yorkshire brewing heritage with historic brewing methods"}'::jsonb, '{"en":"A luxuriously smooth and velvety oatmeal stout brewed with traditional methods. The addition of oats creates an exceptionally silky mouthfeel while roasted malts provide rich coffee and chocolate flavors. Beautifully balanced, complex, and deeply satisfying - a classic example of Yorkshire brewing tradition."}'::jsonb, '{"en":"Silky Smooth Since 1980"}'::jsonb, 5, NULL, NULL, 35, NULL, NULL, 40, NULL, NULL, 'black', 'opaque', 'low', 'full', 'top_fermented', '{"smooth","velvety","roasty","chocolate","coffee","creamy","complex","rich"}', '{"en":"Exceptionally smooth and silky mouthfeel from the oats. Rich roasted malt flavors with notes of dark chocolate, espresso coffee, and toasted grains. Subtle sweetness balanced by gentle roasted bitterness. Hints of caramel and vanilla add complexity. The Yorkshire Square fermentation contributes a subtle fruity character (dark fruit, plum). The finish is long and satisfying with lingering chocolate and coffee notes."}'::jsonb, '{"en":"Roasted malt, dark chocolate, coffee, subtle dark fruit, and gentle sweetness"}'::jsonb, '{"en":"Silky smooth texture with rich chocolate and coffee flavors"}'::jsonb, '{"en":"Long, smooth finish with lingering roasted malt, chocolate, and subtle sweetness"}'::jsonb, '{"en":"Beautifully balanced between roasted bitterness and malt sweetness, with oats providing luxurious smoothness"}'::jsonb, 3, 3, '{"Pale malt","Roasted barley","Crystal malt","Chocolate malt"}', '{"English hops","Fuggles"}', 'Samuel Smith''s house yeast', '{}', NULL, '{"Oatmeal (malted oats)","Yorkshire well water"}', 'nonic', 'cellar', 12, 14, '{"en":"Serve at cellar temperature (12-14°C) to allow the complex flavors to fully express. Pour gently into a pint glass, leaving any sediment in the bottle (bottle-conditioned). Allow a creamy tan-colored head to form. Can be enjoyed slightly warmer than most beers."}'::jsonb, true, '2 fingers', '{"desserts","grilled-meats","comfort-food","cheese"}', '{"en":"Exceptional with chocolate desserts, tiramisu, sticky toffee pudding, and crème brûlée. Pairs beautifully with oysters (classic pairing), grilled meats, beef stew, and blue cheeses. The smooth, roasted character complements rich, savory dishes and sweet desserts alike."}'::jsonb, '{"Stilton","Roquefort","Aged Cheddar","Gorgonzola"}', '{"British comfort food","Desserts","Grilled meats"}', NULL, '{"all_year","autumn","winter"}', '{"dinner","dessert","tasting","contemplative","evening"}', false, false, false, false, '{"bottle"}', '{"550"}', '{"guinness-draught","youngs-double-chocolate-stout"}', 'year_round', 'mid', 80, 'https://www.samuelsmithsbrewery.co.uk', 'Samuel Smith''s brewing heritage and traditional Yorkshire brewing methods', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


