-- ============================================================================
-- BEERS DATABASE SEED (ENGLISH ONLY)
-- ============================================================================
--
-- This file contains INSERT statements for seeding the beers table
-- with ENGLISH ONLY content. Translations will be added separately.
--
-- Total Beers: 45
--
-- Generated: 2025-12-14T04:28:41.945Z
-- ============================================================================


-- ============================================================================
-- BEERS DATABASE SEED (ENGLISH ONLY)
-- ============================================================================
--
-- This file contains INSERT statements for seeding the beers table
-- with ENGLISH ONLY content. Translations will be added separately.
--
-- Total Beers: 45
--
-- Generated: 2025-12-14T04:28:41.945Z
-- ============================================================================


-- 1. Heineken
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('8bd93716-e9b3-40c2-8cc8-8472658c0838', 'heineken', 'heineken-international-lager', '{"en":"Heineken"}'::jsonb, 'international_classic', 'lager', 'pilsner', '{"international","premium","dutch","iconic","green-bottle"}', 'Netherlands', 'NL', NULL, 'Amsterdam', '{"en":"Heineken Brewery"}'::jsonb, 1864, 'macro', false, '1873', '{"en":"Gerard Adriaan Heineken purchased the De Hooiberg brewery in Amsterdam in 1864 and transformed it into one of the world''s most recognized beer brands. The distinctive A-yeast was developed in the 1880s by Dr. Elion, a student of Louis Pasteur, giving Heineken its signature taste."}'::jsonb, '{"World Beer Cup Gold","European Beer Star"}', '{"en":"Named after the Heineken family, founders of the brewery"}'::jsonb, NULL, '{"en":"A premium pale lager known worldwide for its balanced taste, slight bitterness, and refreshing finish. The iconic green bottle and red star have made it one of the most recognizable beers globally."}'::jsonb, '{"en":"Open Your World"}'::jsonb, 5, NULL, NULL, 19, NULL, NULL, 4, NULL, NULL, 'pale', 'brilliant', 'medium', 'light', 'bottom_fermented', '{"crisp","balanced","hoppy","refreshing","clean"}', '{"en":"A well-balanced lager with mild bitterness, subtle fruity notes from the A-yeast, and a clean, slightly sweet malt backbone."}'::jsonb, '{"en":"Light grassy hops with subtle fruit esters and clean malt"}'::jsonb, NULL, '{"en":"Crisp, clean finish with lingering mild bitterness"}'::jsonb, NULL, 2, 2, '{"Pilsner malt","Malted barley"}', '{"European hops","Hallertau"}', 'Heineken A-yeast', '{}', NULL, '{}', 'pilsner', 'cold', 3, 5, '{"en":"Pour at a 45° angle, then straighten to create a 2-finger head"}'::jsonb, true, NULL, '{"seafood","light-dishes","appetizers"}', '{"en":"Excellent with seafood, light salads, mild cheeses, and fried appetizers. The crisp finish cuts through oily foods."}'::jsonb, '{"Gouda","Edam","mild Cheddar"}', '{"Dutch","European","Asian fusion"}', NULL, '{"all_year","summer"}', '{"casual","party","sports","bbq"}', false, false, false, true, '{"bottle","can","draft"}', '{"250","330","500"}', '{}', 'year_round', 'mid', 95, 'https://www.heineken.com', 'Official Heineken website and brewing heritage information', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 2. Corona Extra
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('b4ed4e5e-dba4-4cb4-ac68-c21b1d21ae95', 'corona-extra', 'corona-extra-mexican-lager', '{"en":"Corona Extra"}'::jsonb, 'international_classic', 'lager', 'mexican_lager', '{"mexican","beach","lime","summer","clear-bottle","iconic"}', 'Mexico', 'MX', NULL, 'Mexico City', '{"en":"Grupo Modelo (AB InBev)"}'::jsonb, 1925, 'macro', false, '1925', '{"en":"Corona was first brewed in 1925 at Cervecería Modelo in Mexico City to celebrate Modelo''s 10th anniversary. It became the best-selling beer in Mexico by 1935. The clear bottle was originally chosen to showcase the beer''s clarity and golden color. The tradition of serving with a lime wedge started in the 1980s."}'::jsonb, '{}', '{"en":"Named \"Corona\" meaning \"Crown\" in Spanish, symbolizing the crown of quality"}'::jsonb, NULL, '{"en":"A light, refreshing Mexican lager with a distinctive clear bottle and beach lifestyle image. Best known for being served with a lime wedge, Corona offers a crisp, slightly sweet taste perfect for hot weather."}'::jsonb, '{"en":"Find Your Beach"}'::jsonb, 4.6, NULL, NULL, 18, NULL, NULL, 2, NULL, NULL, 'straw', 'brilliant', 'medium', 'light', 'bottom_fermented', '{"crisp","refreshing","clean","light","slightly_sweet"}', '{"en":"Very light and crisp with subtle malt sweetness, minimal hop bitterness, and a clean finish. The lime wedge (if added) provides citrus brightness."}'::jsonb, '{"en":"Light grain and subtle fruit notes with faint hop presence"}'::jsonb, NULL, '{"en":"Clean, dry, and refreshing with no lingering bitterness"}'::jsonb, NULL, 1, 2, '{"Barley malt","Rice","Corn"}', '{"Galena","Saaz"}', 'Lager yeast', '{}', NULL, '{}', 'bottle', 'very_cold', 1, 4, '{"en":"Traditionally served in the bottle with a lime wedge inserted into the neck. Can also be poured into a pilsner glass."}'::jsonb, true, NULL, '{"mexican-food","seafood","grilled-dishes","spicy-food"}', '{"en":"Perfect with tacos, ceviche, grilled fish, nachos, and spicy Mexican dishes. The light body and citrus (from lime) complement seafood excellently."}'::jsonb, '{}', '{"Mexican","Tex-Mex","Caribbean","Seafood"}', NULL, '{"summer","all_year"}', '{"beach","bbq","casual","party","poolside"}', false, false, false, true, '{"bottle","can"}', '{"330","355","710"}', '{}', 'year_round', 'mid', 92, 'https://www.corona.com', 'Official Corona website and brand history', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 3. Budweiser
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('75b85f64-b0b3-4774-998f-b0977abb35c8', 'budweiser', 'budweiser-american-lager', '{"en":"Budweiser"}'::jsonb, 'international_classic', 'lager', 'american_lager', '{"american","classic","king-of-beers","iconic","beechwood-aged"}', 'United States', 'US', NULL, 'St. Louis, Missouri', '{"en":"Anheuser-Busch (AB InBev)"}'::jsonb, 1852, 'macro', false, '1876', '{"en":"Introduced in 1876 by Carl Conrad & Co., Budweiser was named after the town of Budweis (České Budějovice) in Bohemia, famous for its brewing tradition. Adolphus Busch pioneered pasteurization and refrigerated rail cars to distribute the beer nationally. The \"King of Beers\" slogan was introduced in 1956."}'::jsonb, '{"World Beer Cup medals","Great American Beer Festival awards"}', '{"en":"Named after Budweis (České Budějovice), a Bohemian town known for brewing since the 13th century"}'::jsonb, NULL, '{"en":"America''s best-selling beer, known for its crisp taste and beechwood aging process. A medium-bodied American lager with a clean, refreshing finish and subtle hop bitterness."}'::jsonb, '{"en":"The King of Beers"}'::jsonb, 5, NULL, NULL, 12, NULL, NULL, 3, NULL, NULL, 'straw', 'brilliant', 'high', 'light', 'bottom_fermented', '{"crisp","clean","balanced","refreshing","malty"}', '{"en":"Crisp and clean with a subtle sweetness from rice adjunct, light hop bitterness, and distinctive beechwood-aged smoothness."}'::jsonb, '{"en":"Light malt sweetness with subtle floral hop notes and clean grain"}'::jsonb, NULL, '{"en":"Clean, crisp finish with subtle hop dryness"}'::jsonb, NULL, 2, 2, '{"Two-row barley malt","Rice"}', '{"Hallertau","Saaz","American hops"}', 'Budweiser proprietary lager yeast', '{"Rice"}', NULL, '{"Beechwood chips (for aging)"}', 'pint', 'very_cold', 2, 4, '{"en":"Pour into a tilted glass to create a modest head, then straighten"}'::jsonb, true, NULL, '{"american-food","grilled-dishes","pizza","burgers"}', '{"en":"Perfect with classic American fare: burgers, hot dogs, pizza, BBQ ribs, and fried chicken. The crisp carbonation cuts through fatty foods."}'::jsonb, '{}', '{"American","BBQ","Tex-Mex"}', NULL, '{"all_year","summer"}', '{"casual","sports","bbq","party"}', false, false, false, true, '{"bottle","can","draft"}', '{"330","355","473","710"}', '{}', 'year_round', 'value', 90, 'https://www.budweiser.com', 'Official Budweiser website and brand history', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 4. Stella Artois
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('18c6e44b-5f37-4409-b4a6-ffb896761eb3', 'stella-artois', 'stella-artois-belgian-pilsner', '{"en":"Stella Artois"}'::jsonb, 'international_classic', 'lager', 'pilsner', '{"belgian","premium","christmas-origin","chalice","sophisticated"}', 'Belgium', 'BE', NULL, 'Leuven', '{"en":"Brouwerij Artois (AB InBev)"}'::jsonb, 1366, 'macro', false, '1926', '{"en":"The Den Hoorn brewery was established in Leuven in 1366. Stella Artois was first brewed as a Christmas beer in 1926 - \"Stella\" meaning \"star\" in Latin, referencing the Christmas star. The Artois name was added in honor of master brewer Sebastian Artois who joined in 1708. It became so popular that year-round production began."}'::jsonb, '{}', '{"en":"\"Stella\" (star in Latin) references Christmas, \"Artois\" honors master brewer Sebastian Artois"}'::jsonb, NULL, '{"en":"A premium Belgian pilsner with over 600 years of brewing heritage. Known for its balanced malt sweetness, distinct hop bitterness, and crisp, dry finish. Traditionally served in a signature chalice glass."}'::jsonb, '{"en":"Be Legacy"}'::jsonb, 5.2, NULL, NULL, 30, NULL, NULL, 4, NULL, NULL, 'gold', 'brilliant', 'medium', 'medium_light', 'bottom_fermented', '{"crisp","hoppy","balanced","dry","refreshing"}', '{"en":"Well-balanced with soft malt sweetness, pronounced Saaz hop bitterness, and a crisp, dry finish. More bitter and complex than typical mass-market lagers."}'::jsonb, '{"en":"Floral and spicy Saaz hops with clean malt backbone"}'::jsonb, NULL, '{"en":"Dry, crisp finish with lingering noble hop bitterness"}'::jsonb, NULL, 3, 2, '{"Pilsner malt","Maize"}', '{"Saaz hops"}', 'Stella Artois proprietary yeast', '{}', NULL, '{}', 'goblet', 'cold', 3, 5, '{"en":"The 9-step pouring ritual: Purification, The Sacrifice, The Pour, The Head, The Skimming, The Second Pour, The Cleansing, The Bestowal, The Admiration"}'::jsonb, true, '2 fingers', '{"seafood","mussels","frites","light-dishes"}', '{"en":"Classic pairing with moules-frites (mussels and fries). Also excellent with seafood, light salads, grilled white fish, and mild cheeses."}'::jsonb, '{"Brie","Camembert","Goat cheese"}', '{"Belgian","French","Seafood"}', NULL, '{"all_year","christmas"}', '{"dinner","date_night","celebration","casual"}', false, false, false, true, '{"bottle","can","draft"}', '{"284","330","500"}', '{}', 'year_round', 'premium', 88, 'https://www.stellaartois.com', 'Official Stella Artois website and 600+ years of brewing heritage', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 5. Peroni Nastro Azzurro
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('c25a57a3-9e6a-49fa-ae00-9c9d4bbc160d', 'peroni-nastro-azzurro', 'peroni-nastro-azzurro-italian-lager', '{"en":"Peroni Nastro Azzurro"}'::jsonb, 'international_classic', 'lager', 'pilsner', '{"italian","premium","elegant","blue-ribbon","fashion","aperitivo"}', 'Italy', 'IT', NULL, 'Rome', '{"en":"Birra Peroni (Asahi)"}'::jsonb, 1846, 'macro', false, '1963', '{"en":"Peroni was founded in 1846 in Vigevano by Francesco Peroni. Nastro Azzurro (\"Blue Ribbon\") was created in 1963 to celebrate Italian style and elegance. It quickly became associated with Italian fashion, design, and the dolce vita lifestyle. The beer is brewed with Italian maize for a distinctive crisp taste."}'::jsonb, '{}', '{"en":"\"Nastro Azzurro\" means \"Blue Ribbon\" in Italian, symbolizing premium quality and Italian excellence"}'::jsonb, NULL, '{"en":"Italy''s number one premium lager, known for its distinctive crisp and refreshing taste. Brewed with Italian maize, it embodies Italian style, elegance, and the spirit of aperitivo culture."}'::jsonb, '{"en":"Live Every Moment"}'::jsonb, 5.1, NULL, NULL, 24, NULL, NULL, 3, NULL, NULL, 'straw', 'brilliant', 'medium', 'light', 'bottom_fermented', '{"crisp","clean","citrus","refreshing","elegant"}', '{"en":"Distinctively crisp and clean with subtle citrus notes from the Italian maize. Light bitterness, delicate malt sweetness, and an effervescent, refreshing finish."}'::jsonb, '{"en":"Subtle citrus and floral hop notes with clean malt"}'::jsonb, NULL, '{"en":"Clean, crisp, and elegantly dry"}'::jsonb, NULL, 2, 2, '{"Two-row barley","Italian maize"}', '{"German hops","Saaz-Saaz"}', 'Peroni proprietary lager yeast', '{}', NULL, '{}', 'pilsner', 'cold', 3, 5, '{"en":"Pour slowly at an angle to preserve carbonation, finish with a finger of foam"}'::jsonb, true, NULL, '{"italian-food","seafood","pizza","aperitivo"}', '{"en":"Perfect aperitivo companion. Pairs beautifully with Italian antipasti, seafood risotto, thin-crust pizza, grilled fish, and light pasta dishes."}'::jsonb, '{"Mozzarella","Burrata","Parmigiano-Reggiano"}', '{"Italian","Mediterranean","Seafood"}', NULL, '{"all_year","summer"}', '{"aperitivo","dinner","date_night","casual"}', false, false, false, true, '{"bottle","draft"}', '{"330","500","620"}', '{}', 'year_round', 'premium', 85, 'https://www.peroni.com', 'Official Peroni website and Italian brewing heritage', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


