-- 21. Founders Breakfast Stout
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('123af9a7-0a87-4b73-9fcd-91e7aad031ef', 'founders-breakfast-stout', 'founders-breakfast-stout-imperial', '{"en":"Founders Breakfast Stout"}'::jsonb, 'craft', 'stout_porter', 'imperial_stout', '{"craft","american","imperial-stout","coffee","chocolate","oats","michigan","bold","breakfast"}', 'United States', 'US', 'Michigan', 'Grand Rapids', '{"en":"Founders Brewing Company"}'::jsonb, 1997, 'craft', false, '2001', '{"en":"Founders Brewing Company launched Breakfast Stout in 2001 as one of the first American imperial stouts brewed with coffee and oats. The beer combines two of the most important things in life: breakfast and beer. Made with Sumatra and Kona coffee, flaked oats for silky texture, and chocolate malts, it became an instant cult classic. The beer helped establish Founders as a premier craft brewery and inspired countless coffee stouts. Originally a seasonal release, high demand made it year-round in 2017."}'::jsonb, '{"Great American Beer Festival Gold","World Beer Cup Gold","Top-rated imperial stout"}', '{"en":"Named for the breakfast staples used: coffee, oats, and chocolate - the most important meal of the day"}'::jsonb, '{"en":"One of the most influential American coffee stouts, pioneering the imperial breakfast stout category"}'::jsonb, '{"en":"A bold imperial stout brewed with coffee and oats. Pitch black with a thick tan head, it delivers intense coffee and chocolate flavors with smooth oatmeal texture. The double dose of coffee (Sumatra and Kona) creates a rich espresso character balanced by chocolate malt sweetness."}'::jsonb, '{"en":"The coffee lover''s consummate beer"}'::jsonb, 8.3, NULL, NULL, 60, NULL, NULL, 45, NULL, NULL, 'black', 'opaque', 'medium', 'full', 'top_fermented', '{"coffee","chocolate","roasty","bold","smooth","espresso","oaty","rich"}', '{"en":"Intense coffee flavors dominate with rich espresso, dark chocolate, and roasted malt character. The oats provide a silky, smooth mouthfeel that balances the bold coffee bitterness. Notes of cocoa, caramel, and dark fruit complexity. Strong but remarkably drinkable with coffee that shines through without being harsh."}'::jsonb, '{"en":"Strong roasted coffee, dark chocolate, cocoa, caramel, and roasted malt"}'::jsonb, '{"en":"Bold coffee punch with smooth, velvety oat texture"}'::jsonb, '{"en":"Long, rich coffee finish with chocolate and roasted malt lingering"}'::jsonb, NULL, 4, 3, '{"Pale malt","Chocolate malt","Roasted barley","Caramel malt","Flaked oats"}', '{"Magnum","Cascade"}', 'American ale yeast', '{}', NULL, '{"Sumatra coffee","Kona coffee","Flaked oats"}', 'snifter', 'cellar', 10, 13, '{"en":"Pour into a tulip or snifter glass to concentrate the coffee aromatics. Allow to warm slightly for full flavor development."}'::jsonb, true, '0.5-1 inch', '{"breakfast","dessert","chocolate","cheese","brunch"}', '{"en":"Perfect with brunch dishes, chocolate cake, tiramisu, coffee ice cream, bacon, pancakes, or smoked meats. The coffee pairs excellently with chocolate and breakfast foods."}'::jsonb, '{"Aged cheddar","Smoked gouda","Mascarpone","Blue cheese"}', '{"American","Breakfast","Dessert","BBQ"}', NULL, '{"all_year","winter","autumn"}', '{"brunch","dessert","nightcap","special_occasion"}', false, false, false, true, '{"draft","bottle","can"}', '{"355","473"}', '{"left-hand-milk-stout","old-rasputin"}', 'year_round', 'mid_high', 92, 'https://foundersbrewing.com', 'Official Founders Brewing website and coffee stout innovation since 2001', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 22. Old Rasputin Russian Imperial Stout
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('4ed9ac0d-8606-4db9-b1d8-525276be264f', 'old-rasputin', 'old-rasputin-russian-imperial-stout', '{"en":"Old Rasputin Russian Imperial Stout"}'::jsonb, 'craft', 'stout_porter', 'russian_imperial_stout', '{"craft","american","russian-imperial-stout","bold","intense","california","iconic","high-abv"}', 'United States', 'US', 'California', 'Fort Bragg', '{"en":"North Coast Brewing Company"}'::jsonb, 1988, 'craft', false, '1995', '{"en":"Old Rasputin was first brewed by North Coast Brewing in 1995, named after the famous Russian mystic Grigori Rasputin. It was one of the first American craft interpretations of the Russian Imperial Stout style, which originated in 18th-century England for export to the Russian Imperial Court. The beer features Rasputin''s iconic image on the label. Known for its intense, warming character and complex flavors, Old Rasputin has become one of the most respected and influential imperial stouts in American craft brewing, earning numerous awards and inspiring countless brewers."}'::jsonb, '{"Great American Beer Festival medals","World Beer Cup Gold","Top-rated RIS globally"}', '{"en":"Named after Grigori Rasputin, the Russian mystic and advisor to the Romanov family"}'::jsonb, '{"en":"One of the most iconic American Russian Imperial Stouts, setting the standard for the style in craft brewing"}'::jsonb, '{"en":"A powerful, intensely flavored Russian Imperial Stout. Pitch black with a thick tan head, it delivers massive roasted malt character with rich chocolate, coffee, and dark fruit complexity. Bold, warming alcohol presence balanced by deep malt sweetness and hop bitterness."}'::jsonb, '{"en":"A masterpiece of intensity and balance"}'::jsonb, 9, NULL, NULL, 75, NULL, NULL, 50, NULL, NULL, 'black', 'opaque', 'medium', 'full', 'top_fermented', '{"intense","roasty","chocolate","coffee","dark-fruit","warming","complex","bold"}', '{"en":"Intensely roasted with powerful dark chocolate, espresso, and roasted malt flavors. Rich dark fruit notes (plum, raisin, fig) add complexity. Warming alcohol presence is well-integrated with sweet malt backbone. Hoppy bitterness balances the sweetness. Finishes dry with lingering roasted character and subtle alcohol warmth."}'::jsonb, '{"en":"Rich roasted malt, dark chocolate, coffee, dark fruit, caramel, and subtle hop spice"}'::jsonb, '{"en":"Bold and intense with immediate roasted malt and chocolate power"}'::jsonb, '{"en":"Long, dry, roasty finish with warming alcohol and dark chocolate lingering"}'::jsonb, NULL, 5, 3, '{"Pale malt","Roasted barley","Chocolate malt","Black malt","Crystal malt"}', '{"Magnum","Cascade","Chinook"}', 'American ale yeast', '{}', NULL, '{}', 'snifter', 'cellar', 12, 15, '{"en":"Pour into a snifter or tulip glass to concentrate intense aromatics. Let warm to 55-60°F to allow full flavor complexity to develop. Can be aged for several years."}'::jsonb, true, '0.5-1 inch', '{"dessert","cheese","chocolate","game","hearty-food"}', '{"en":"Excellent with dark chocolate desserts, strong blue cheese, grilled steak, game meats, or rich stews. The intensity matches bold, flavorful foods. Also pairs with cigars."}'::jsonb, '{"Stilton","Roquefort","Aged cheddar","Smoked gouda"}', '{"American","BBQ","Dessert","Hearty"}', NULL, '{"all_year","winter","autumn"}', '{"special_occasion","nightcap","celebration","contemplation"}', false, false, false, true, '{"draft","bottle","can"}', '{"355","650"}', '{"founders-breakfast-stout","guinness-extra-stout"}', 'year_round', 'mid_high', 90, 'https://www.northcoastbrewing.com', 'Official North Coast Brewing website and RIS tradition since 1995', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 23. Fuller's London Porter
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('92269344-728c-45d2-9b26-0ad76e612047', 'fullers-london-porter', 'fullers-london-porter-traditional', '{"en":"Fuller''s London Porter"}'::jsonb, 'international_classic', 'stout_porter', 'porter', '{"porter","english","traditional","historic","london","balanced","sessionable"}', 'United Kingdom', 'GB', 'Chiswick', 'London', '{"en":"Fuller''s Brewery (Fuller, Smith & Turner)"}'::jsonb, 1845, 'regional', false, '1995', '{"en":"Fuller''s London Porter was introduced in 1995 to revive the historic porter style that originated in 18th-century London. Porter was the first beer style to be mass-produced and was the drink of choice for London''s street and river porters, giving it its name. Fuller''s version is based on historical recipes and brewing methods, using traditional brown malt and a complex blend of malts. The beer helped spark the modern porter revival and won Champion Beer of Britain in 2002. It remains one of the finest examples of the traditional London porter style."}'::jsonb, '{"Champion Beer of Britain 2002","CAMRA awards","World Beer Awards medals"}', '{"en":"Named after the historic London porter style and the city''s working-class porters who popularized it"}'::jsonb, '{"en":"One of the finest modern examples of traditional London porter, helping revive the historic style"}'::jsonb, '{"en":"A traditional London porter brewed to historic specifications. Deep mahogany brown with ruby highlights and a tan head. It offers complex roasted malt character with chocolate, coffee, toffee, and biscuit notes. Well-balanced between malt sweetness and roasted bitterness, making it highly drinkable and sessionable."}'::jsonb, '{"en":"A taste of 18th-century London"}'::jsonb, 5.4, NULL, NULL, 35, NULL, NULL, 30, NULL, NULL, 'dark_brown', 'clear', 'medium', 'medium', 'top_fermented', '{"roasty","chocolate","coffee","toffee","balanced","malty","biscuity","sessionable"}', '{"en":"Complex roasted malt profile with chocolate, coffee, and toffee sweetness balanced by gentle roasted bitterness. Notes of dark bread, biscuit, caramel, and subtle hop earthiness. Medium-bodied with smooth carbonation and a dry, roasty finish. Less intense than stout but more complex than brown ale - the perfect balance."}'::jsonb, '{"en":"Roasted malt, chocolate, coffee, toffee, biscuit, and subtle earthy hops"}'::jsonb, '{"en":"Smooth and balanced with gentle roasted character"}'::jsonb, '{"en":"Dry, roasty finish with lingering chocolate and coffee notes"}'::jsonb, NULL, 3, 3, '{"Pale malt","Crystal malt","Brown malt","Chocolate malt"}', '{"Goldings","Target"}', 'Fuller''s proprietary ale yeast', '{}', NULL, '{"Traditional brown malt for historic authenticity"}', 'pint', 'cellar', 10, 13, '{"en":"Pour into a nonic pint glass at cellar temperature (50-55°F). Allow to settle for a modest tan head. Let warm slightly for full flavor development."}'::jsonb, true, '0.5-1 inch', '{"british-food","cheese","meat","stew","pub-food"}', '{"en":"Excellent with traditional British pub fare: meat pies, bangers and mash, fish and chips, beef stew, or ploughman''s lunch. The roasted character pairs well with grilled meats, aged cheeses, and roasted vegetables."}'::jsonb, '{"Cheddar","Stilton","Wensleydale","Aged gouda"}', '{"British","Pub food","BBQ","Comfort food"}', NULL, '{"all_year","autumn","winter"}', '{"pub_night","dinner","casual","relaxation"}', false, false, false, true, '{"draft","bottle","can"}', '{"330","500"}', '{"guinness-draught","founders-breakfast-stout"}', 'year_round', 'mid', 78, 'https://www.fullers.co.uk', 'Official Fuller''s Brewery website and London brewing heritage since 1845', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 24. Paulaner Hefe-Weißbier
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('beceef88-6195-4a4e-b0bf-7a61192c6dd8', 'paulaner-hefeweizen', 'paulaner-hefe-weissbier', '{"en":"Paulaner Hefe-Weißbier"}'::jsonb, 'international_classic', 'wheat', 'hefeweizen', '{"german","bavarian","wheat","unfiltered","banana","clove","munich","oktoberfest"}', 'Germany', 'DE', 'Bavaria', 'Munich', '{"en":"Paulaner Brauerei"}'::jsonb, 1634, 'regional', false, '1634', '{"en":"Paulaner was founded in 1634 by Paulaner monks in Munich. The monks brewed \"liquid bread\" to sustain themselves during Lenten fasting. Their strong beer became famous throughout Bavaria. Today, Paulaner is one of Munich''s \"Big Six\" breweries and a staple at Oktoberfest. Their Hefeweizen is considered one of the finest examples of the Bavarian wheat beer style."}'::jsonb, '{}', '{"en":"Named after the Paulaner monks (followers of St. Francis of Paula) who founded the brewery"}'::jsonb, NULL, '{"en":"A classic Bavarian Hefeweizen with distinctive banana and clove aromas from the traditional wheat beer yeast. Hazy golden-orange color, creamy texture, and refreshing character make it the quintessential German wheat beer."}'::jsonb, '{"en":"The Original Munich Premium Wheat Beer"}'::jsonb, 5.5, NULL, NULL, 12, NULL, NULL, 6, NULL, NULL, 'gold', 'hazy', 'high', 'medium', 'top_fermented', '{"banana","clove","creamy","refreshing","wheaty","fruity","spicy"}', '{"en":"Classic banana and clove phenols from the yeast dominate, with soft wheat character, subtle citrus notes, and a creamy, refreshing finish. Very low bitterness allows the yeast character to shine."}'::jsonb, '{"en":"Banana, clove, subtle vanilla, with hints of bubblegum"}'::jsonb, '{"en":"Creamy wheat character with pronounced banana-clove yeast notes"}'::jsonb, '{"en":"Soft, refreshing finish with lingering wheat and yeast character"}'::jsonb, NULL, 1, 3, '{"Wheat malt (50%+)","Pilsner malt"}', '{"Hallertauer Tradition"}', 'Traditional Bavarian Hefeweizen yeast', '{}', NULL, '{}', 'weizen', 'cold', 5, 8, '{"en":"Rinse glass with cold water. Pour slowly at an angle, leaving some beer in bottle. Swirl bottle to resuspend yeast, then pour remaining beer into glass."}'::jsonb, true, '3-4 fingers', '{"german-food","seafood","salads","breakfast"}', '{"en":"Traditional with Weisswurst (white sausage) and soft pretzels. Also excellent with seafood, light salads, egg dishes, and mild cheeses."}'::jsonb, '{"Bavarian Obatzda","Camembert","Brie"}', '{"German","Bavarian","Brunch"}', NULL, '{"all_year","summer","oktoberfest"}', '{"brunch","casual","party","dinner"}', false, false, false, true, '{"bottle","draft"}', '{"500","330"}', '{"paulaner-dunkel","paulaner-oktoberfest"}', 'year_round', 'mid', 88, 'https://www.paulaner.com', 'Official Paulaner website and Bavarian brewing heritage', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 25. Weihenstephaner Hefeweissbier
INSERT INTO beers (id, slug, stable_key, name, status, style_category, style, tags, origin_country, origin_country_code, origin_region, origin_city, brewery, brewery_founded, brewery_type, is_trappist, first_brewed, history_story, history_awards, history_named_after, history_significance, description, tagline, abv, abv_min, abv_max, ibu, ibu_min, ibu_max, srm, og, fg, color, clarity, carbonation, body, fermentation, flavor_profile, taste_description, taste_aroma, taste_first_impression, taste_finish, taste_balance, bitterness_level, sweetness_level, ingredients_malts, ingredients_hops, ingredients_yeast, ingredients_adjuncts, ingredients_water, ingredients_special, serving_glass, serving_temperature, serving_temp_min, serving_temp_max, serving_pouring_notes, serving_head_retention, serving_ideal_head, pairing_food_categories, pairing_food, pairing_cheese, pairing_cuisine, pairing_avoid, season_tags, occasion_tags, is_gluten_free, is_non_alcoholic, is_organic, is_vegan, available_formats, available_sizes, related_beers, availability, price_tier, popularity, source_url, source_note, version)
VALUES ('1aefd357-6602-4cbe-81a1-2d7f5cb287be', 'weihenstephaner-hefeweissbier', 'weihenstephaner-hefeweissbier', '{"en":"Weihenstephaner Hefeweissbier"}'::jsonb, 'international_classic', 'wheat', 'hefeweizen', '{"german","bavarian","wheat","unfiltered","banana","clove","oldest-brewery","traditional"}', 'Germany', 'DE', 'Bavaria', 'Freising', '{"en":"Weihenstephan Brewery"}'::jsonb, 1040, 'regional', false, '1040', '{"en":"Weihenstephan holds the title of the world''s oldest continuously operating brewery, founded by Benedictine monks in 1040. Located on the historic Weihenstephan hill in Freising, Bavaria, the brewery has nearly 1,000 years of brewing expertise. The monastery received the official brewing license from the city of Freising in 1040. Today, it is owned by the Bavarian state and closely tied to the Technical University of Munich''s brewing science program. Their Hefeweissbier is considered the gold standard for the style."}'::jsonb, '{}', '{"en":"Named after the Weihenstephan Abbey, where the brewery was founded"}'::jsonb, NULL, '{"en":"The definitive Bavarian Hefeweizen from the world''s oldest brewery. Features a perfect balance of banana and clove aromatics from traditional wheat beer yeast, cloudy golden appearance, and silky smooth texture. The benchmark by which all other wheat beers are measured."}'::jsonb, '{"en":"World''s Oldest Brewery''s Finest Wheat Beer"}'::jsonb, 5.4, NULL, NULL, 14, NULL, NULL, 7, NULL, NULL, 'gold', 'hazy', 'high', 'medium', 'top_fermented', '{"banana","clove","creamy","refreshing","wheaty","fruity","spicy","balanced"}', '{"en":"Harmonious banana and clove esters from traditional Weihenstephan yeast strain, smooth wheat malt foundation, subtle citrus and vanilla notes, with a clean, refreshing finish. Impeccably balanced with low bitterness that showcases the yeast character."}'::jsonb, '{"en":"Prominent banana and clove, subtle vanilla, hints of citrus and bubblegum"}'::jsonb, '{"en":"Silky smooth wheat character with perfectly balanced banana-clove yeast expression"}'::jsonb, '{"en":"Clean, refreshing finish with delicate wheat sweetness and lingering yeast character"}'::jsonb, NULL, 1, 3, '{"Wheat malt (60%)","Barley malt"}', '{"Hallertauer Tradition","Perle"}', 'Proprietary Weihenstephan Hefeweizen yeast strain', '{}', NULL, '{}', 'weizen', 'cold', 6, 8, '{"en":"Use a chilled Weizen glass. Pour slowly at 45-degree angle until 3/4 full. Gently swirl bottle to resuspend yeast sediment, then pour remainder to create a thick, creamy head."}'::jsonb, true, '3-4 fingers', '{"german-food","seafood","salads","breakfast","light-dishes"}', '{"en":"Perfect with traditional Bavarian Weisswurst and sweet mustard. Excellent with grilled fish, shellfish, Caesar salad, eggs Benedict, fresh mozzarella, and fruit-based desserts."}'::jsonb, '{"Bavarian Obatzda","Fresh Mozzarella","Camembert","Brie"}', '{"German","Bavarian","Seafood","Brunch"}', NULL, '{"all_year","summer","spring"}', '{"brunch","casual","party","dinner","celebration"}', false, false, false, true, '{"bottle","draft"}', '{"500","330"}', '{"paulaner-hefeweizen","erdinger-weissbier"}', 'year_round', 'mid', 92, 'https://www.weihenstephaner.de', 'Official Weihenstephan website and world''s oldest brewery heritage', 1)
ON CONFLICT (slug) DO UPDATE SET
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  style_category = EXCLUDED.style_category,
  style = EXCLUDED.style,
  tags = EXCLUDED.tags,
  origin_country = EXCLUDED.origin_country,
  origin_country_code = EXCLUDED.origin_country_code,
  origin_region = EXCLUDED.origin_region,
  origin_city = EXCLUDED.origin_city,
  brewery = EXCLUDED.brewery,
  brewery_founded = EXCLUDED.brewery_founded,
  brewery_type = EXCLUDED.brewery_type,
  is_trappist = EXCLUDED.is_trappist,
  first_brewed = EXCLUDED.first_brewed,
  history_story = EXCLUDED.history_story,
  history_awards = EXCLUDED.history_awards,
  history_named_after = EXCLUDED.history_named_after,
  history_significance = EXCLUDED.history_significance,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  abv = EXCLUDED.abv,
  ibu = EXCLUDED.ibu,
  srm = EXCLUDED.srm,
  color = EXCLUDED.color,
  clarity = EXCLUDED.clarity,
  carbonation = EXCLUDED.carbonation,
  body = EXCLUDED.body,
  fermentation = EXCLUDED.fermentation,
  flavor_profile = EXCLUDED.flavor_profile,
  taste_description = EXCLUDED.taste_description,
  taste_aroma = EXCLUDED.taste_aroma,
  taste_finish = EXCLUDED.taste_finish,
  bitterness_level = EXCLUDED.bitterness_level,
  sweetness_level = EXCLUDED.sweetness_level,
  serving_glass = EXCLUDED.serving_glass,
  serving_temperature = EXCLUDED.serving_temperature,
  serving_pouring_notes = EXCLUDED.serving_pouring_notes,
  pairing_food = EXCLUDED.pairing_food,
  pairing_cheese = EXCLUDED.pairing_cheese,
  pairing_cuisine = EXCLUDED.pairing_cuisine,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_non_alcoholic = EXCLUDED.is_non_alcoholic,
  is_vegan = EXCLUDED.is_vegan,
  available_formats = EXCLUDED.available_formats,
  available_sizes = EXCLUDED.available_sizes,
  availability = EXCLUDED.availability,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


