-- ============================================================================
-- GUDBRO Pizza Database - Batch 06
-- Pizzas 26 to 30 of 62
-- ============================================================================
-- Pizzas in this batch:
--   - Sausage and Broccoli Rabe (salsiccia-friarielli)
--   - Caprese Pizza (caprese)
--   - Carbonara Pizza (carbonara)
--   - Sicilian Sfincione (sfincione)
--   - Roman Pizza by the Slice (pizza-al-taglio)
-- ============================================================================

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '00176044-cc61-4663-b649-c5729b5454dd',
    'salsiccia-friarielli',
    'pizza-salsiccia-friarielli',
    '{"en":"Sausage and Broccoli Rabe","it":"Salsiccia e Friarielli","vi":"Pizza Xuc Xich Va Rau Cai Xanh"}'::jsonb,
    '{"en":"Neapolitan specialty: crumbled Italian sausage with bitter friarielli (broccoli rabe) and smoked provola. A taste of Naples.","it":"Specialità napoletana: salsiccia sbriciolata con friarielli amari e provola affumicata. Un assaggio di Napoli."}'::jsonb,
    NULL,
    'regional',
    'napoletana',
    '{"neapolitan","sausage","bitter-greens","traditional","regional"}',
    '{"country":"Italy","country_code":"IT","region":"Campania","city":"Naples"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_fior_di_latte',
    '{"provolone"}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_SCAMORZA","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_SAUSAGE_ITALIAN","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_SPINACH","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_GARLIC","quantity":{"amount":5,"unit":"g"}},{"ingredient_id":"ING_PEPERONCINO","quantity":{"amount":3,"unit":"g"},"is_optional":true},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":485,"time_seconds":100}'::jsonb,
    '{"profile":["savory","bitter","smoky","robust"],"description":{"en":"The slight bitterness of the greens perfectly balances the rich, fatty sausage.","it":"La leggera amarezza dei friarielli bilancia perfettamente la ricchezza della salsiccia."},"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","milk"],"calories_estimate":880}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":6,"ideal_temperature":"hot","wine_pairing":["Lacryma Christi","Aglianico"],"beer_pairing":["Pilsner","Pale Ale"]}'::jsonb,
    NULL,
    78,
    '{"neapolitan-food-lovers","adventurous-eaters"}',
    '{"boscaiola","diavola"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '7a89e010-ec9b-4f01-9084-b383b17c779b',
    'caprese',
    'pizza-caprese',
    '{"en":"Caprese Pizza","it":"Pizza Caprese","vi":"Pizza Caprese"}'::jsonb,
    '{"en":"The beloved Capri salad as a pizza: fresh tomatoes, buffalo mozzarella, basil, and balsamic glaze.","it":"L''amata insalata caprese come pizza: pomodori freschi, mozzarella di bufala, basilico e glassa balsamica."}'::jsonb,
    NULL,
    'classic',
    'napoletana',
    '{"fresh","caprese","summer","vegetarian","light"}',
    '{"country":"Italy","country_code":"IT","region":"Campania","city":"Capri"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_bufala',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_BUFALA_DOP","quantity":{"amount":125,"unit":"g"}},{"ingredient_id":"ING_CHERRY_TOMATOES","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_BASIL_FRESH","quantity":{"amount":10,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_BALSAMIC_GLAZE","quantity":{"amount":15,"unit":"ml"},"is_topping":true},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":15,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":485,"time_seconds":90,"notes":{"en":"Buffalo mozzarella, fresh basil, and balsamic glaze are added after baking.","it":"Mozzarella di bufala, basilico fresco e glassa balsamica vengono aggiunti dopo la cottura."}}'::jsonb,
    '{"profile":["fresh","sweet","herbaceous","tangy"],"description":{"en":"Light and refreshing with the sweetness of ripe tomatoes and creamy buffalo mozzarella.","it":"Leggera e rinfrescante con la dolcezza dei pomodori maturi e la cremosità della bufala."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk"],"calories_estimate":800}'::jsonb,
    '{"suggested_modes":["whole"],"portions_whole":6,"ideal_temperature":"warm","wine_pairing":["Falanghina","Vermentino","Rosé"],"beer_pairing":["Wheat Beer","Pilsner"]}'::jsonb,
    NULL,
    84,
    '{"summer-dining","vegetarians","light-meal-seekers"}',
    '{"margherita-bufala","burrata"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'af460ad1-c97b-4442-bb2c-32fb33934a70',
    'carbonara',
    'pizza-carbonara',
    '{"en":"Carbonara Pizza","it":"Pizza alla Carbonara","vi":"Pizza Carbonara"}'::jsonb,
    '{"en":"The beloved pasta as a pizza: creamy egg base, crispy guanciale, pecorino romano, and black pepper.","it":"L''amata pasta come pizza: base cremosa all''uovo, guanciale croccante, pecorino romano e pepe nero."}'::jsonb,
    NULL,
    'gourmet',
    'romana',
    '{"roman","carbonara","egg","guanciale","creamy"}',
    '{"country":"Italy","country_code":"IT","region":"Lazio","city":"Rome"}'::jsonb,
    NULL,
    'white',
    'mozzarella_fior_di_latte',
    '{"parmesan"}',
    'roman',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_PECORINO_ROMANO_DOP","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_GUANCIALE","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_EGG","quantity":{"amount":1,"unit":"piece"}},{"ingredient_id":"ING_RICOTTA","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":450,"time_seconds":120,"notes":{"en":"The egg is cracked in the center during the last 30 seconds for a runny yolk.","it":"L''uovo viene rotto al centro negli ultimi 30 secondi per un tuorlo morbido."}}'::jsonb,
    '{"profile":["rich","creamy","smoky","peppery"],"description":{"en":"All the comforting flavors of carbonara: smoky guanciale, rich egg, sharp pecorino.","it":"Tutti i sapori confortanti della carbonara: guanciale affumicato, uovo ricco, pecorino sapido."},"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","milk","eggs"],"calories_estimate":950}'::jsonb,
    '{"suggested_modes":["whole"],"portions_whole":6,"ideal_temperature":"hot","wine_pairing":["Frascati","Orvieto"],"beer_pairing":["Pilsner","Lager"]}'::jsonb,
    NULL,
    80,
    '{"carbonara-lovers","roman-food-enthusiasts"}',
    '{"amatriciana","cacio-e-pepe"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '212a1c7e-f3e2-4b5f-8721-d0533b69a511',
    'sfincione',
    'pizza-sfincione-siciliano',
    '{"en":"Sicilian Sfincione","it":"Sfincione Palermitano","vi":"Pizza Sfincione Sicily"}'::jsonb,
    '{"en":"Traditional Sicilian thick pizza with tomatoes, onions, anchovies, and breadcrumbs. Palermo''s street food pride.","it":"Pizza siciliana tradizionale spessa con pomodoro, cipolle, acciughe e pangrattato. L''orgoglio dello street food di Palermo."}'::jsonb,
    NULL,
    'regional',
    'siciliana',
    '{"sicilian","traditional","thick","street-food","anchovies"}',
    '{"country":"Italy","country_code":"IT","region":"Sicily","city":"Palermo"}'::jsonb,
    '{"story":{"en":"A traditional Sicilian Christmas Eve pizza, sfincione has deep cultural roots in Palermo. It''s sold by street vendors and is a beloved part of Sicilian culinary heritage.","it":"Pizza tradizionale della vigilia di Natale siciliana, lo sfincione ha profonde radici culturali a Palermo. Venduto dai venditori ambulanti, è parte amata del patrimonio culinario siciliano."}}'::jsonb,
    'tomato',
    'none',
    '{}',
    'sicilian',
    '[{"ingredient_id":"ING_SEMOLINA_FLOUR","quantity":{"amount":300,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":150,"unit":"g"}},{"ingredient_id":"ING_ONION_CARAMELIZED","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_ANCHOVIES","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_PECORINO_ROMANO_DOP","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_OREGANO","quantity":{"amount":3,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":5,"unit":"g"}}]'::jsonb,
    '{"method":"pan","temperature_celsius":220,"time_seconds":1200}'::jsonb,
    '{"profile":["savory","briny","sweet","crunchy"],"description":{"en":"Sweet caramelized onions contrast with salty anchovies, topped with crispy breadcrumbs.","it":"Le cipolle caramellate dolci contrastano con le acciughe salate, guarnite con pangrattato croccante."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk","fish"],"calories_estimate":850}'::jsonb,
    '{"suggested_modes":["slice","weight"],"portions_whole":12,"ideal_temperature":"warm","wine_pairing":["Nero d''Avola","Grillo"],"beer_pairing":["Pilsner","Amber Ale"]}'::jsonb,
    NULL,
    65,
    '{"sicilian-food-lovers","street-food-enthusiasts","adventurous-eaters"}',
    '{"pizza-al-taglio","focaccia"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '333e7d58-06a2-4a34-ad96-5b48801a71e0',
    'pizza-al-taglio',
    'pizza-al-taglio-romana',
    '{"en":"Roman Pizza by the Slice","it":"Pizza al Taglio","vi":"Pizza Cat Mien"}'::jsonb,
    '{"en":"Rome''s famous rectangular pizza sold by weight. Light, airy, and crispy. Choose your toppings and pay by the gram.","it":"La famosa pizza rettangolare romana venduta a peso. Leggera, ariosa e croccante. Scegli i tuoi topping e paga al grammo."}'::jsonb,
    NULL,
    'regional',
    'al_taglio',
    '{"roman","by-weight","street-food","crispy","rectangular"}',
    '{"country":"Italy","country_code":"IT","region":"Lazio","city":"Rome"}'::jsonb,
    '{"story":{"en":"Pizza al taglio evolved in post-WWII Rome as a quick, affordable street food. The long-fermented dough creates a light, digestible crust with large air pockets.","it":"La pizza al taglio si è sviluppata nella Roma del dopoguerra come street food veloce e accessibile. L''impasto a lunga lievitazione crea una crosta leggera e digeribile con grandi bolle d''aria."}}'::jsonb,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'roman',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":500,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":200,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":200,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":2,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":300,"time_seconds":600,"notes":{"en":"High-hydration dough (80%+) with 24-72 hour cold fermentation for optimal texture.","it":"Impasto ad alta idratazione (80%+) con 24-72 ore di lievitazione a freddo per una consistenza ottimale."}}'::jsonb,
    '{"profile":["light","crispy","airy","versatile"],"description":{"en":"Light and airy with a crispy bottom and soft, bubbly interior.","it":"Leggera e ariosa con fondo croccante e interno morbido e alveolato."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk"],"calories_estimate":250}'::jsonb,
    '{"suggested_modes":["weight","slice"],"ideal_temperature":"warm","wine_pairing":["Frascati","Orvieto"],"beer_pairing":["Pilsner","Lager"]}'::jsonb,
    NULL,
    88,
    '{"street-food-lovers","quick-lunch","rome-visitors"}',
    '{"sfincione","focaccia"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();