-- ============================================================================
-- GUDBRO Pizza Database - Batch 04
-- Pizzas 16 to 20 of 62
-- ============================================================================
-- Pizzas in this batch:
--   - Supreme (supreme)
--   - Buffalo Chicken (buffalo-chicken)
--   - White Pizza (white-pizza)
--   - Greek Pizza (greek)
--   - Mexicana (mexicana)
-- ============================================================================

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '45951fb6-fbe8-4a6d-8b3c-7e0065fb20fc',
    'supreme',
    'pizza-supreme',
    '{"en":"Supreme","it":"Supreme","vi":"Pizza Supreme"}'::jsonb,
    '{"en":"The complete package: pepperoni, sausage, bell peppers, onions, mushrooms, and olives. A little bit of everything.","it":"Il pacchetto completo: pepperoni, salsiccia, peperoni, cipolle, funghi e olive. Un po'' di tutto."}'::jsonb,
    NULL,
    'international',
    'american',
    '{"american","loaded","variety","classic","popular"}',
    '{"country":"United States","country_code":"US","year_created":"1977"}'::jsonb,
    '{"story":{"en":"Popularized by Pizza Hut in 1977, the Supreme became the go-to choice for groups who couldn''t decide on toppings.","it":"Resa popolare da Pizza Hut nel 1977, la Supreme è diventata la scelta ideale per gruppi indecisi sui topping."}}'::jsonb,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'american',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":300,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":130,"unit":"g"}},{"ingredient_id":"ING_PEPPERONI","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_SAUSAGE_ITALIAN","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_BELL_PEPPER_RED","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_ONION_RED","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_MUSHROOMS_CHAMPIGNON","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_OLIVES_BLACK","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":4,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":260,"time_seconds":660}'::jsonb,
    '{"profile":["savory","balanced","complex","satisfying"],"description":{"en":"A harmonious blend of meats and vegetables - something for everyone in every bite.","it":"Un mix armonioso di carni e verdure - qualcosa per tutti in ogni morso."},"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","milk"],"calories_estimate":950}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot","wine_pairing":["Sangiovese","Merlot"],"beer_pairing":["Amber Ale","Lager"]}'::jsonb,
    NULL,
    92,
    '{"groups","families","indecisive-eaters"}',
    '{"meat-lovers","veggie-supreme"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'da6e6fe0-0cde-45b0-9bef-82b88bb0f8fb',
    'buffalo-chicken',
    'pizza-buffalo-chicken',
    '{"en":"Buffalo Chicken","it":"Pollo Buffalo","vi":"Pizza Ga Buffalo"}'::jsonb,
    '{"en":"Spicy buffalo sauce, crispy chicken, creamy ranch or blue cheese base, topped with celery and blue cheese crumbles.","it":"Salsa buffalo piccante, pollo croccante, base cremosa di ranch o gorgonzola, guarnita con sedano e gorgonzola sbriciolato."}'::jsonb,
    NULL,
    'international',
    'american',
    '{"american","spicy","chicken","buffalo","tangy"}',
    '{"country":"United States","country_code":"US","region":"New York","city":"Buffalo"}'::jsonb,
    '{"story":{"en":"Inspired by Buffalo wings from Buffalo, NY, this pizza brings the beloved bar food flavors to pizza form.","it":"Ispirata alle Buffalo wings di Buffalo, NY, questa pizza porta i sapori amati del bar food in forma di pizza."}}'::jsonb,
    'buffalo',
    'mozzarella_fior_di_latte',
    '{"gorgonzola"}',
    'american',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":280,"unit":"g"}},{"ingredient_id":"ING_BUFFALO_SAUCE","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_CHICKEN_GRILLED","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_GORGONZOLA_DOP","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_ONION_RED","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":4,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":260,"time_seconds":600}'::jsonb,
    '{"profile":["spicy","tangy","creamy","bold"],"description":{"en":"Fiery buffalo heat balanced by cool, tangy blue cheese and creamy mozzarella.","it":"Il calore infuocato del buffalo bilanciato dal gorgonzola fresco e acidulo e dalla mozzarella cremosa."},"spice_level":3}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"allergens":["gluten","milk"],"calories_estimate":880}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot","wine_pairing":["Riesling","Gewurztraminer"],"beer_pairing":["IPA","Pilsner","Blue Moon"]}'::jsonb,
    NULL,
    82,
    '{"spicy-lovers","wing-lovers","game-day"}',
    '{"bbq-chicken","hot-honey"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '034b3127-2166-4261-8268-8650cb725808',
    'white-pizza',
    'pizza-bianca-american',
    '{"en":"White Pizza","it":"Pizza Bianca","vi":"Pizza Trang"}'::jsonb,
    '{"en":"No tomato sauce here - just garlic-infused olive oil, ricotta, mozzarella, and parmesan with fresh herbs.","it":"Niente salsa di pomodoro - solo olio d''oliva all''aglio, ricotta, mozzarella e parmigiano con erbe fresche."}'::jsonb,
    NULL,
    'classic',
    'american',
    '{"white","garlic","creamy","no-tomato","vegetarian"}',
    '{"country":"United States","country_code":"US"}'::jsonb,
    NULL,
    'garlic_oil',
    'mozzarella_fior_di_latte',
    '{"ricotta","parmesan"}',
    'american',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":280,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":30,"unit":"ml"}},{"ingredient_id":"ING_GARLIC","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_RICOTTA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_PARMIGIANO_REGGIANO_DOP","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_BASIL_FRESH","quantity":{"amount":5,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_OREGANO","quantity":{"amount":2,"unit":"g"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":4,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":260,"time_seconds":540}'::jsonb,
    '{"profile":["garlicky","creamy","herbaceous","rich"],"description":{"en":"Rich and garlicky with the creaminess of ricotta and the sharpness of parmesan.","it":"Ricca e agliata con la cremosità della ricotta e la sapidità del parmigiano."},"spice_level":1}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk"],"calories_estimate":900}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot","wine_pairing":["Pinot Grigio","Chardonnay"],"beer_pairing":["Wheat Beer","Pilsner"]}'::jsonb,
    NULL,
    78,
    '{"garlic-lovers","vegetarians","tomato-avoiders"}',
    '{"quattro-formaggi","aglio-olio"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '687b9e22-760f-4c6f-a691-eb842c583c93',
    'greek',
    'pizza-greek',
    '{"en":"Greek Pizza","it":"Pizza Greca","vi":"Pizza Hy Lap"}'::jsonb,
    '{"en":"Mediterranean flavors: feta cheese, kalamata olives, red onions, tomatoes, and oregano. A taste of Greece.","it":"Sapori mediterranei: feta, olive kalamata, cipolle rosse, pomodori e origano. Un assaggio della Grecia."}'::jsonb,
    NULL,
    'fusion',
    'fusion',
    '{"mediterranean","greek","feta","olives","vegetarian"}',
    '{"country":"Greece","country_code":"GR"}'::jsonb,
    NULL,
    'tomato',
    'feta',
    '{}',
    'american',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":280,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_FETA","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_OLIVES_BLACK","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_ONION_RED","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_CHERRY_TOMATOES","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_OREGANO","quantity":{"amount":3,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":15,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":4,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":260,"time_seconds":540}'::jsonb,
    '{"profile":["tangy","briny","herbaceous","fresh"],"description":{"en":"Tangy feta and briny olives transport you to the Greek islands with every bite.","it":"La feta acidula e le olive salate ti trasportano nelle isole greche ad ogni morso."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk"],"calories_estimate":800}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot","wine_pairing":["Assyrtiko","Moschofilero"],"beer_pairing":["Pilsner","Wheat Beer"]}'::jsonb,
    NULL,
    72,
    '{"mediterranean-lovers","vegetarians","feta-fans"}',
    '{"mediterranean","caprese"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'd779343e-2e00-4aef-8961-6d78a0720e2a',
    'mexicana',
    'pizza-mexicana',
    '{"en":"Mexicana","it":"Messicana","vi":"Pizza Mexico"}'::jsonb,
    '{"en":"Spicy fiesta: ground beef, jalapenos, red onions, bell peppers, and cheddar. Olé!","it":"Fiesta piccante: carne macinata, jalapenos, cipolle rosse, peperoni e cheddar. Olé!"}'::jsonb,
    NULL,
    'fusion',
    'fusion',
    '{"mexican","spicy","beef","jalapeno","fusion"}',
    '{"country":"Mexico","country_code":"MX"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'american',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":280,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_GROUND_BEEF","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_JALAPENO","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_ONION_RED","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_BELL_PEPPER_RED","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_CORN","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":4,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":260,"time_seconds":600}'::jsonb,
    '{"profile":["spicy","savory","bold","zesty"],"description":{"en":"Bold Mexican flavors with the kick of fresh jalapenos and seasoned beef.","it":"Sapori messicani decisi con il tocco piccante dei jalapenos freschi e carne condita."},"spice_level":3}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk"],"calories_estimate":920}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot","wine_pairing":["Malbec","Tempranillo"],"beer_pairing":["Mexican Lager","Corona","Dos Equis"]}'::jsonb,
    NULL,
    76,
    '{"spicy-lovers","mexican-food-fans"}',
    '{"taco-pizza","tex-mex"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();