-- ============================================================================
-- GUDBRO Pizza Database - Batch 09
-- Pizzas 41 to 45 of 62
-- ============================================================================
-- Pizzas in this batch:
--   - Bolognese Pizza (bolognese)
--   - Speck Pizza (speck)
--   - Calabrese (calabrese)
--   - Nduja Pizza (nduja)
--   - Sarda (sarda)
-- ============================================================================

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '93073321-7cf8-46b3-b3f8-b521d19486c7',
    'bolognese',
    'pizza_bolognese',
    '{"en":"Bolognese Pizza","it":"Pizza Bolognese","es":"Pizza Boloñesa","de":"Bolognese Pizza","fr":"Pizza Bolognaise"}'::jsonb,
    '{"en":"Pizza topped with traditional meat ragù bolognese, mozzarella, and parmesan","it":"Pizza condita con ragù alla bolognese tradizionale, mozzarella e parmigiano","es":"Pizza cubierta con ragú boloñés tradicional, mozzarella y parmesano","de":"Pizza mit traditionellem Fleisch-Ragù Bolognese, Mozzarella und Parmesan","fr":"Pizza garnie de ragù bolognaise traditionnel, mozzarella et parmesan"}'::jsonb,
    NULL,
    'regional',
    'other',
    '{"bologna","meat","ragu","hearty"}',
    '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna","city":"Bologna"}'::jsonb,
    '{"story":{"en":"Bringing Bologna''s famous meat ragù to pizza, this hearty creation is a pizza interpretation of the world-renowned pasta bolognese.","it":"Portando il famoso ragù di carne di Bologna sulla pizza, questa creazione sostanziosa è un''interpretazione in pizza della pasta alla bolognese famosa nel mondo."}}'::jsonb,
    'tomato',
    'mozzarella_fior_di_latte',
    '{"parmesan"}',
    'neapolitan',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ragu_bolognese","quantity":{"amount":150,"unit":"g"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"parmesan","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"olive_oil","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":450,"time_seconds":90}'::jsonb,
    '{"profile":["meaty","rich","savory","umami"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    72,
    '{"meat-lovers","pasta-fans"}',
    '{"meat-lovers","salsiccia"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '60403383-f8fd-439a-b72e-09c023a7c270',
    'speck',
    'pizza_speck',
    '{"en":"Speck Pizza","it":"Pizza allo Speck","es":"Pizza con Speck","de":"Speck Pizza","fr":"Pizza au Speck"}'::jsonb,
    '{"en":"Alto Adige-inspired pizza with speck ham, brie or taleggio, arugula, and walnuts","it":"Pizza ispirata all''Alto Adige con speck, brie o taleggio, rucola e noci","es":"Pizza inspirada en Alto Adigio con jamón speck, brie o taleggio, rúcula y nueces","de":"Südtirol-inspirierte Pizza mit Speck, Brie oder Taleggio, Rucola und Walnüssen","fr":"Pizza inspirée du Haut-Adige avec speck, brie ou taleggio, roquette et noix"}'::jsonb,
    NULL,
    'regional',
    'gourmet',
    '{"alto-adige","speck","arugula","nuts","alpine"}',
    '{"country":"Italy","country_code":"IT","region":"Trentino-Alto Adige"}'::jsonb,
    '{"story":{"en":"Celebrating the flavors of the Alpine region, this pizza features speck - the famous smoked ham from Alto Adige - paired with creamy cheese and peppery arugula.","it":"Celebrando i sapori della regione alpina, questa pizza presenta lo speck - il famoso prosciutto affumicato dell''Alto Adige - abbinato a formaggio cremoso e rucola piccante."}}'::jsonb,
    'white',
    'taleggio',
    '{"mozzarella_fior_di_latte"}',
    'neapolitan',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"taleggio","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"speck","quantity":{"amount":80,"unit":"g"},"is_topping":true},{"ingredient_id":"arugula","quantity":{"amount":30,"unit":"g"},"is_topping":true},{"ingredient_id":"walnuts","quantity":{"amount":20,"unit":"g"},"is_topping":true},{"ingredient_id":"olive_oil","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":450,"time_seconds":90,"notes":{"en":"Speck, arugula and walnuts added after baking","it":"Speck, rucola e noci aggiunti dopo la cottura"}}'::jsonb,
    '{"profile":["smoky","peppery","nutty","creamy"],"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy","tree_nuts"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    78,
    '{"ham-lovers","alpine-cuisine-fans"}',
    '{"prosciutto-crudo-e-rucola"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '4fc2e6cc-ec48-472d-a7f3-49a44e62008b',
    'calabrese',
    'pizza_calabrese',
    '{"en":"Calabrese","it":"Calabrese","es":"Calabresa","de":"Calabrese","fr":"Calabraise"}'::jsonb,
    '{"en":"Spicy pizza from Calabria with nduja, hot salami, caciocavallo cheese, and Calabrian chili","it":"Pizza piccante calabrese con nduja, salame piccante, caciocavallo e peperoncino calabrese","es":"Pizza picante de Calabria con nduja, salami picante, queso caciocavallo y chile calabrés","de":"Scharfe Pizza aus Kalabrien mit Nduja, scharfer Salami, Caciocavallo-Käse und kalabrischem Chili","fr":"Pizza épicée de Calabre avec nduja, salami épicé, fromage caciocavallo et piment calabrais"}'::jsonb,
    NULL,
    'regional',
    'other',
    '{"calabria","spicy","nduja","hot","salami"}',
    '{"country":"Italy","country_code":"IT","region":"Calabria"}'::jsonb,
    '{"story":{"en":"A fiery pizza showcasing Calabria''s famous spicy ingredients - nduja (spreadable spicy pork paste) and the region''s beloved peperoncino.","it":"Una pizza piccante che mette in mostra i famosi ingredienti piccanti della Calabria - la nduja e l''amato peperoncino della regione."}}'::jsonb,
    'tomato',
    'mozzarella_fior_di_latte',
    '{"provolone"}',
    'neapolitan',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"san_marzano_tomatoes","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"nduja","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"spicy_salami","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"provolone","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"calabrian_chili","quantity":{"amount":10,"unit":"g"}},{"ingredient_id":"olive_oil","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":450,"time_seconds":90}'::jsonb,
    '{"profile":["spicy","smoky","rich","intense"],"spice_level":4}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    76,
    '{"spicy-lovers","adventurous-eaters"}',
    '{"diavola","nduja"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '10fef608-4c51-4647-9d49-92af13cc1e6b',
    'nduja',
    'pizza_nduja',
    '{"en":"Nduja Pizza","it":"Pizza alla Nduja","es":"Pizza de Nduja","de":"Nduja Pizza","fr":"Pizza à la Nduja"}'::jsonb,
    '{"en":"Spicy pizza featuring Calabrian nduja spread, burrata, and honey drizzle","it":"Pizza piccante con nduja calabrese, burrata e filo di miele","es":"Pizza picante con nduja calabresa, burrata y chorrito de miel","de":"Scharfe Pizza mit kalabrischer Nduja, Burrata und Honigtopping","fr":"Pizza épicée avec nduja calabraise, burrata et filet de miel"}'::jsonb,
    NULL,
    'gourmet',
    'gourmet',
    '{"calabria","nduja","spicy","burrata","honey"}',
    '{"country":"Italy","country_code":"IT","region":"Calabria","city":"Spilinga"}'::jsonb,
    '{"story":{"en":"A modern gourmet pizza that highlights nduja - the spreadable spicy pork paste from Spilinga - balanced with creamy burrata and a touch of honey.","it":"Una pizza gourmet moderna che mette in risalto la nduja - la pasta di maiale piccante spalmabile da Spilinga - bilanciata con burrata cremosa e un tocco di miele."}}'::jsonb,
    'tomato',
    'burrata',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"san_marzano_tomatoes","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"nduja","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"burrata","quantity":{"amount":125,"unit":"g"},"is_topping":true},{"ingredient_id":"honey","quantity":{"amount":1,"unit":"tbsp"},"is_topping":true},{"ingredient_id":"fresh_basil","quantity":{"amount":5,"unit":"piece"},"is_topping":true}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":450,"time_seconds":90,"notes":{"en":"Burrata, honey, and basil added after baking","it":"Burrata, miele e basilico aggiunti dopo la cottura"}}'::jsonb,
    '{"profile":["spicy","creamy","sweet","savory"],"spice_level":3}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    80,
    '{"spicy-lovers","gourmet-enthusiasts"}',
    '{"calabrese","burrata"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '0e519776-b8dd-45cf-8226-51ca24589e80',
    'sarda',
    'pizza_sarda',
    '{"en":"Sarda","it":"Sarda","es":"Sarda","de":"Sarda","fr":"Sarde"}'::jsonb,
    '{"en":"Sardinian pizza with sausage, pecorino sardo, olives, and bottarga","it":"Pizza sarda con salsiccia, pecorino sardo, olive e bottarga","es":"Pizza de Cerdeña con salchicha, pecorino sardo, aceitunas y bottarga","de":"Sardische Pizza mit Wurst, Pecorino Sardo, Oliven und Bottarga","fr":"Pizza sarde avec saucisse, pecorino sardo, olives et bottarga"}'::jsonb,
    NULL,
    'regional',
    'other',
    '{"sardinia","sausage","pecorino","bottarga","olives"}',
    '{"country":"Italy","country_code":"IT","region":"Sardinia"}'::jsonb,
    '{"story":{"en":"A celebration of Sardinia''s unique flavors, featuring the island''s famous pecorino cheese and optional bottarga (cured fish roe) for a taste of the sea.","it":"Una celebrazione dei sapori unici della Sardegna, con il famoso pecorino dell''isola e bottarga opzionale (uova di pesce essiccate) per un tocco di mare."}}'::jsonb,
    'tomato',
    'pecorino',
    '{"mozzarella_fior_di_latte"}',
    'neapolitan',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"san_marzano_tomatoes","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"italian_sausage","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"pecorino_sardo","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"black_olives","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"bottarga","quantity":{"amount":10,"unit":"g"},"is_optional":true,"is_topping":true}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":450,"time_seconds":90}'::jsonb,
    '{"profile":["savory","briny","rich","umami"],"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy","fish"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    62,
    '{"adventurous-eaters","seafood-lovers"}',
    '{"salsiccia","pugliese"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();