-- ============================================================================
-- GUDBRO Pizza Database - Batch 02
-- Pizzas 6 to 10 of 62
-- ============================================================================
-- Pizzas in this batch:
--   - Ham and Mushrooms (prosciutto-funghi)
--   - Prosciutto and Arugula (prosciutto-crudo-rucola)
--   - Napoli (Anchovy Pizza) (napoli)
--   - Tuna and Onion (tonno-cipolla)
--   - Vegetarian (vegetariana)
-- ============================================================================

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '624b1c17-859a-45a3-93a1-2271c6935c99',
    'prosciutto-funghi',
    'pizza-prosciutto-funghi',
    '{"en":"Ham and Mushrooms","it":"Prosciutto e Funghi","vi":"Pizza Thit Heo Va Nam"}'::jsonb,
    '{"en":"A timeless Italian combination of cooked ham and fresh mushrooms on a bed of tomato and mozzarella.","it":"Un classico intramontabile italiano con prosciutto cotto e funghi freschi su un letto di pomodoro e mozzarella."}'::jsonb,
    NULL,
    'classic',
    'napoletana',
    '{"classic","meat","mushrooms","popular"}',
    '{"country":"Italy","country_code":"IT"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_PROSCIUTTO_COTTO","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_MUSHROOMS_CHAMPIGNON","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_OREGANO","quantity":{"amount":1,"unit":"g"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":480,"time_seconds":100}'::jsonb,
    '{"profile":["savory","earthy","umami"],"description":{"en":"Classic and comforting with the savory ham complementing the earthy mushrooms.","it":"Classica e confortante con il prosciutto saporito che si abbina ai funghi terrosi."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","milk"],"calories_estimate":850}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":6,"ideal_temperature":"hot","wine_pairing":["Barbera","Dolcetto"],"beer_pairing":["Pilsner","Helles"]}'::jsonb,
    NULL,
    88,
    '{"families","classic-lovers"}',
    '{"capricciosa","boscaiola"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '17426ffe-47da-491f-b46d-0b7a4bd68972',
    'prosciutto-crudo-rucola',
    'pizza-prosciutto-crudo-rucola',
    '{"en":"Prosciutto and Arugula","it":"Prosciutto Crudo e Rucola","vi":"Pizza Prosciutto Va Rau Rocket"}'::jsonb,
    '{"en":"Thin slices of aged prosciutto di Parma DOP with fresh peppery arugula and parmesan shavings, added after baking.","it":"Fette sottili di prosciutto di Parma DOP stagionato con rucola fresca e scaglie di parmigiano, aggiunti dopo la cottura."}'::jsonb,
    NULL,
    'gourmet',
    'napoletana',
    '{"gourmet","prosciutto","fresh","elegant"}',
    '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_PROSCIUTTO_CRUDO_DOP","quantity":{"amount":60,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_ARUGULA","quantity":{"amount":30,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_PARMIGIANO_REGGIANO_DOP","quantity":{"amount":20,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":485,"time_seconds":90,"notes":{"en":"Prosciutto, arugula, and parmesan are added fresh after baking to preserve their texture and flavor.","it":"Prosciutto, rucola e parmigiano vengono aggiunti freschi dopo la cottura per preservare consistenza e sapore."}}'::jsonb,
    '{"profile":["savory","peppery","fresh","salty"],"description":{"en":"Luxurious and fresh: the saltiness of aged prosciutto balanced by peppery arugula and nutty parmesan.","it":"Lussuosa e fresca: la sapidità del prosciutto stagionato bilanciata dalla rucola pepata e dal parmigiano nocciolato."},"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","milk"],"calories_estimate":880}'::jsonb,
    '{"suggested_modes":["whole"],"portions_whole":6,"ideal_temperature":"warm","wine_pairing":["Prosecco","Lambrusco","Sangiovese"],"beer_pairing":["Pilsner","Saison"]}'::jsonb,
    NULL,
    90,
    '{"gourmet-lovers","date-night","italian-food-enthusiasts"}',
    '{"bresaola-rucola","burrata"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'a0fcfb57-adf9-4002-a255-24f2f88a39cb',
    'napoli',
    'pizza-napoli-acciughe',
    '{"en":"Napoli (Anchovy Pizza)","it":"Napoli","vi":"Pizza Napoli Ca Com"}'::jsonb,
    '{"en":"Traditional Neapolitan pizza with anchovies, capers, and olives. A bold, briny classic.","it":"Pizza napoletana tradizionale con acciughe, capperi e olive. Un classico deciso e saporito."}'::jsonb,
    NULL,
    'classic',
    'napoletana',
    '{"classic","seafood","anchovies","traditional","salty"}',
    '{"country":"Italy","country_code":"IT","region":"Campania","city":"Naples"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_SAN_MARZANO_TOMATOES","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_ANCHOVIES","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_CAPERS","quantity":{"amount":15,"unit":"g"}},{"ingredient_id":"ING_OLIVES_BLACK","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_OREGANO","quantity":{"amount":2,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":485,"time_seconds":90}'::jsonb,
    '{"profile":["briny","savory","umami","salty"],"description":{"en":"Intensely savory with the umami punch of anchovies, briny capers, and salty olives.","it":"Intensamente saporita con il gusto umami delle acciughe, capperi salati e olive."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk","fish"],"calories_estimate":780}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":6,"ideal_temperature":"hot","wine_pairing":["Greco di Tufo","Fiano"],"beer_pairing":["Pilsner","Hefeweizen"]}'::jsonb,
    NULL,
    70,
    '{"anchovy-lovers","traditionalists","adventurous-eaters"}',
    '{"marinara","frutti-di-mare"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'd2927c4f-d342-4301-bee1-abed2c58e071',
    'tonno-cipolla',
    'pizza-tonno-cipolla',
    '{"en":"Tuna and Onion","it":"Tonno e Cipolla","vi":"Pizza Ca Ngu Va Hanh"}'::jsonb,
    '{"en":"Italian classic with tuna, red onions, and sometimes capers. Popular summer pizza.","it":"Classico italiano con tonno, cipolle rosse e talvolta capperi. Pizza estiva popolare."}'::jsonb,
    NULL,
    'classic',
    'napoletana',
    '{"classic","seafood","tuna","summer"}',
    '{"country":"Italy","country_code":"IT"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_TUNA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_ONION_RED","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_CAPERS","quantity":{"amount":10,"unit":"g"},"is_optional":true},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":480,"time_seconds":100}'::jsonb,
    '{"profile":["savory","fresh","umami"],"description":{"en":"Light and fresh with flaky tuna and the sweet bite of red onion.","it":"Leggera e fresca con tonno sfaldato e il morso dolce della cipolla rossa."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk","fish"],"calories_estimate":800}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":6,"ideal_temperature":"hot","wine_pairing":["Vermentino","Pinot Grigio"],"beer_pairing":["Pilsner","Witbier"]}'::jsonb,
    NULL,
    75,
    '{"seafood-lovers","light-meal-seekers"}',
    '{"napoli","frutti-di-mare"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '41f01dce-b2fc-4b3f-9de0-cb288387257e',
    'vegetariana',
    'pizza-vegetariana',
    '{"en":"Vegetarian","it":"Vegetariana","vi":"Pizza Chay"}'::jsonb,
    '{"en":"A colorful medley of seasonal roasted vegetables: bell peppers, zucchini, eggplant, and mushrooms.","it":"Un colorato mix di verdure di stagione arrostite: peperoni, zucchine, melanzane e funghi."}'::jsonb,
    NULL,
    'classic',
    'napoletana',
    '{"vegetarian","healthy","colorful","seasonal"}',
    '{"country":"Italy","country_code":"IT"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_BELL_PEPPER_RED","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_BELL_PEPPER_YELLOW","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_ZUCCHINI","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_EGGPLANT","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_MUSHROOMS_CHAMPIGNON","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_OLIVES_BLACK","quantity":{"amount":20,"unit":"g"},"is_optional":true},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":480,"time_seconds":120}'::jsonb,
    '{"profile":["fresh","earthy","sweet","vegetal"],"description":{"en":"Fresh and vibrant with the natural sweetness of roasted vegetables.","it":"Fresca e vivace con la dolcezza naturale delle verdure arrostite."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk"],"calories_estimate":750}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":6,"ideal_temperature":"hot","wine_pairing":["Soave","Verdicchio"],"beer_pairing":["Wheat Beer","Saison"]}'::jsonb,
    NULL,
    80,
    '{"vegetarians","health-conscious","families"}',
    '{"ortolana","primavera"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();