-- ============================================================================
-- GUDBRO Pizza Database - Batch 05
-- Pizzas 21 to 25 of 62
-- ============================================================================
-- Pizzas in this batch:
--   - Veggie Supreme (veggie-supreme)
--   - Black Truffle Pizza (tartufo)
--   - Burrata Pizza (burrata)
--   - Mortadella and Pistachio (mortadella-pistacchio)
--   - Woodsman Pizza (boscaiola)
-- ============================================================================

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '9b21f8a2-2e6d-4194-a273-175d10ce75a9',
    'veggie-supreme',
    'pizza-veggie-supreme',
    '{"en":"Veggie Supreme","it":"Vegetariana Supreme","vi":"Pizza Rau Cu Tong Hop"}'::jsonb,
    '{"en":"A garden of flavors: mushrooms, bell peppers, onions, olives, tomatoes, spinach, and artichokes.","it":"Un giardino di sapori: funghi, peperoni, cipolle, olive, pomodori, spinaci e carciofi."}'::jsonb,
    NULL,
    'classic',
    'american',
    '{"vegetarian","loaded","healthy","colorful","garden"}',
    '{"country":"United States","country_code":"US"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'american',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":280,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_MUSHROOMS_CHAMPIGNON","quantity":{"amount":40,"unit":"g"}},{"ingredient_id":"ING_BELL_PEPPER_RED","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_BELL_PEPPER_YELLOW","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_ONION_RED","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_OLIVES_BLACK","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"ING_SPINACH","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_ARTICHOKES","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":4,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":260,"time_seconds":600}'::jsonb,
    '{"profile":["fresh","earthy","colorful","balanced"],"description":{"en":"A rainbow of roasted vegetables delivering varied textures and fresh flavors.","it":"Un arcobaleno di verdure arrostite che offre texture variate e sapori freschi."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk"],"calories_estimate":780}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot","wine_pairing":["Sauvignon Blanc","Vermentino"],"beer_pairing":["Wheat Beer","Saison"]}'::jsonb,
    NULL,
    80,
    '{"vegetarians","health-conscious","variety-seekers"}',
    '{"vegetariana","primavera"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'fa4cb484-7690-4130-a57e-4ef747a17cae',
    'tartufo',
    'pizza-tartufo-nero',
    '{"en":"Black Truffle Pizza","it":"Pizza al Tartufo Nero","vi":"Pizza Nam Truffle Den"}'::jsonb,
    '{"en":"Luxurious white pizza with black truffle shavings, truffle cream, mushrooms, and parmesan. Pure decadence.","it":"Lussuosa pizza bianca con scaglie di tartufo nero, crema al tartufo, funghi e parmigiano. Pura decadenza."}'::jsonb,
    NULL,
    'gourmet',
    'gourmet',
    '{"luxury","truffle","gourmet","premium","white"}',
    '{"country":"Italy","country_code":"IT","region":"Umbria/Piedmont"}'::jsonb,
    NULL,
    'white',
    'mozzarella_fior_di_latte',
    '{"parmesan"}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_TRUFFLE_BLACK","quantity":{"amount":10,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_TRUFFLE_OIL","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_MUSHROOMS_PORCINI","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_PARMIGIANO_REGGIANO_DOP","quantity":{"amount":30,"unit":"g"}},{"ingredient_id":"ING_RICOTTA","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":450,"time_seconds":120,"notes":{"en":"Fresh truffle shavings are added after baking to preserve their aroma.","it":"Le scaglie di tartufo fresco vengono aggiunte dopo la cottura per preservare l''aroma."}}'::jsonb,
    '{"profile":["earthy","luxurious","umami","aromatic"],"description":{"en":"Intensely earthy and aromatic with the unmistakable fragrance of black truffle.","it":"Intensamente terrosa e aromatica con l''inconfondibile fragranza del tartufo nero."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","milk"],"calories_estimate":850}'::jsonb,
    '{"suggested_modes":["whole"],"portions_whole":6,"ideal_temperature":"hot","wine_pairing":["Barolo","Barbaresco","Brunello di Montalcino"],"beer_pairing":["Belgian Tripel","Saison"]}'::jsonb,
    NULL,
    85,
    '{"special-occasions","truffle-lovers","gourmet-enthusiasts"}',
    '{"funghi-porcini","quattro-formaggi"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '0d9a1167-db51-4984-bdef-a59632bda272',
    'burrata',
    'pizza-burrata',
    '{"en":"Burrata Pizza","it":"Pizza con Burrata","vi":"Pizza Burrata"}'::jsonb,
    '{"en":"Creamy burrata placed on top after baking, with cherry tomatoes, prosciutto crudo, and arugula. Instagram''s favorite.","it":"Cremosa burrata posizionata sopra dopo la cottura, con pomodorini, prosciutto crudo e rucola. La preferita di Instagram."}'::jsonb,
    NULL,
    'gourmet',
    'napoletana',
    '{"gourmet","burrata","instagrammable","fresh","premium"}',
    '{"country":"Italy","country_code":"IT","region":"Puglia"}'::jsonb,
    NULL,
    'tomato',
    'burrata',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_SAN_MARZANO_TOMATOES","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_BURRATA","quantity":{"amount":125,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_PROSCIUTTO_CRUDO_DOP","quantity":{"amount":40,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_ARUGULA","quantity":{"amount":20,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_CHERRY_TOMATOES","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_BALSAMIC_GLAZE","quantity":{"amount":10,"unit":"ml"},"is_topping":true,"is_optional":true},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":485,"time_seconds":90,"notes":{"en":"The whole burrata is placed in the center after baking. Cut it open at the table for dramatic effect.","it":"La burrata intera viene posizionata al centro dopo la cottura. Tagliarla al tavolo per un effetto scenico."}}'::jsonb,
    '{"profile":["creamy","fresh","salty","peppery"],"description":{"en":"The creamy stracciatella center of the burrata flows over the pizza, creating a luxurious sauce.","it":"Il cuore cremoso di stracciatella della burrata si spande sulla pizza, creando una salsa lussuosa."},"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","milk"],"calories_estimate":920}'::jsonb,
    '{"suggested_modes":["whole"],"portions_whole":6,"ideal_temperature":"warm","wine_pairing":["Prosecco","Franciacorta","Rosé"],"beer_pairing":["Pilsner","Wheat Beer"]}'::jsonb,
    NULL,
    92,
    '{"date-night","instagram-lovers","cheese-enthusiasts"}',
    '{"prosciutto-crudo-rucola","caprese"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '38396db3-c0b4-4966-9f8c-f4dd3bcc552e',
    'mortadella-pistacchio',
    'pizza-mortadella-pistacchio',
    '{"en":"Mortadella and Pistachio","it":"Mortadella e Pistacchio","vi":"Pizza Mortadella Hat De Cuoi"}'::jsonb,
    '{"en":"Trending Italian gourmet: silky mortadella, crushed Bronte pistachios, stracciatella, and a drizzle of pistachio cream.","it":"Gourmet italiano di tendenza: mortadella setosa, pistacchi di Bronte tritati, stracciatella e un filo di crema di pistacchio."}'::jsonb,
    NULL,
    'gourmet',
    'napoletana',
    '{"gourmet","mortadella","pistachio","trending","premium"}',
    '{"country":"Italy","country_code":"IT","region":"Campania/Sicily"}'::jsonb,
    NULL,
    'white',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_MORTADELLA","quantity":{"amount":80,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_PISTACHIO","quantity":{"amount":30,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_RICOTTA","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":480,"time_seconds":100,"notes":{"en":"Mortadella and pistachios are added after baking to preserve their texture.","it":"Mortadella e pistacchi vengono aggiunti dopo la cottura per preservare la consistenza."}}'::jsonb,
    '{"profile":["savory","nutty","creamy","rich"],"description":{"en":"The silky, fatty mortadella pairs perfectly with the sweet, nutty crunch of pistachios.","it":"La mortadella setosa e grassa si abbina perfettamente alla dolcezza e croccantezza dei pistacchi."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":false,"is_kosher":false,"allergens":["gluten","milk","tree_nuts"],"calories_estimate":950}'::jsonb,
    '{"suggested_modes":["whole"],"portions_whole":6,"ideal_temperature":"warm","wine_pairing":["Lambrusco","Prosecco"],"beer_pairing":["Pilsner","Blonde Ale"]}'::jsonb,
    NULL,
    88,
    '{"gourmet-lovers","italian-food-enthusiasts","trend-followers"}',
    '{"burrata","prosciutto-crudo-rucola"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'c6bf8583-0f20-4953-b18e-c5ca913fcf2d',
    'boscaiola',
    'pizza-boscaiola',
    '{"en":"Woodsman Pizza","it":"Boscaiola","vi":"Pizza Kieu Tho San"}'::jsonb,
    '{"en":"From the woods: wild mushrooms, Italian sausage, mozzarella, and a touch of truffle oil. Rustic and satisfying.","it":"Dal bosco: funghi selvatici, salsiccia italiana, mozzarella e un tocco di olio al tartufo. Rustica e soddisfacente."}'::jsonb,
    NULL,
    'regional',
    'napoletana',
    '{"rustic","mushrooms","sausage","earthy","hearty"}',
    '{"country":"Italy","country_code":"IT","region":"Tuscany/Emilia-Romagna"}'::jsonb,
    NULL,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_TOMATO_PASSATA","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_MOZZARELLA_FIOR_DI_LATTE","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_MUSHROOMS_PORCINI","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_SAUSAGE_ITALIAN","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"ING_GARLIC","quantity":{"amount":5,"unit":"g"}},{"ingredient_id":"ING_TRUFFLE_OIL","quantity":{"amount":5,"unit":"ml"},"is_topping":true,"is_optional":true},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":10,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":480,"time_seconds":110}'::jsonb,
    '{"profile":["earthy","savory","meaty","rustic"],"description":{"en":"Deep forest flavors from porcini mushrooms combined with savory fennel-spiced sausage.","it":"Profondi sapori di bosco dai funghi porcini combinati con salsiccia saporita al finocchio."},"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","milk"],"calories_estimate":900}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":6,"ideal_temperature":"hot","wine_pairing":["Chianti Classico","Brunello"],"beer_pairing":["Brown Ale","Amber Ale"]}'::jsonb,
    NULL,
    82,
    '{"meat-lovers","mushroom-fans","autumn-dining"}',
    '{"funghi","salsiccia"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();