-- ============================================================================
-- GUDBRO Pizza Database - Batch 07
-- Pizzas 31 to 35 of 62
-- ============================================================================
-- Pizzas in this batch:
--   - Vegan Margherita (vegan-margherita)
--   - Cacio e Pepe (cacio-e-pepe)
--   - Amatriciana (amatriciana)
--   - Pizza Fritta (pizza-fritta)
--   - Montanara (montanara)
-- ============================================================================

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'b8a47ce7-b2b5-45d2-beac-c74281a9ce9e',
    'vegan-margherita',
    'pizza-vegan-margherita',
    '{"en":"Vegan Margherita","it":"Margherita Vegana","vi":"Pizza Margherita Chay"}'::jsonb,
    '{"en":"Plant-based version of the classic: tomato sauce, vegan mozzarella, fresh basil, and olive oil.","it":"Versione vegetale del classico: salsa di pomodoro, mozzarella vegana, basilico fresco e olio d''oliva."}'::jsonb,
    NULL,
    'vegan',
    'napoletana',
    '{"vegan","plant-based","dairy-free","classic-alternative"}',
    '{"country":"Italy","country_code":"IT"}'::jsonb,
    NULL,
    'tomato',
    'vegan_cheese',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"ING_PIZZA_FLOUR_00","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ING_SAN_MARZANO_TOMATOES","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"ING_VEGAN_MOZZARELLA","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"ING_BASIL_FRESH","quantity":{"amount":5,"unit":"g"},"is_topping":true},{"ingredient_id":"ING_OLIVE_OIL_EVO","quantity":{"amount":15,"unit":"ml"}},{"ingredient_id":"ING_YEAST_FRESH","quantity":{"amount":3,"unit":"g"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":485,"time_seconds":90}'::jsonb,
    '{"profile":["savory","fresh","herbaceous"],"description":{"en":"All the classic margherita flavors without any animal products.","it":"Tutti i sapori classici della margherita senza prodotti animali."},"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten"],"calories_estimate":700}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":6,"ideal_temperature":"hot","wine_pairing":["Vegan wines","Natural wines"],"beer_pairing":["Craft Lager","IPA"]}'::jsonb,
    NULL,
    70,
    '{"vegans","dairy-free","plant-based-eaters"}',
    '{"marinara","vegan-veggie"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '268718e0-fc57-4aa0-992e-cbf4864eee39',
    'cacio-e-pepe',
    'pizza_cacio_e_pepe',
    '{"en":"Cacio e Pepe","it":"Cacio e Pepe","es":"Cacio e Pepe","de":"Cacio e Pepe","fr":"Cacio e Pepe"}'::jsonb,
    '{"en":"Roman-inspired pizza with pecorino romano cream and generous black pepper","it":"Pizza ispirata alla tradizione romana con crema di pecorino romano e pepe nero abbondante","es":"Pizza inspirada en Roma con crema de pecorino romano y abundante pimienta negra","de":"Von Rom inspirierte Pizza mit Pecorino Romano Creme und reichlich schwarzem Pfeffer","fr":"Pizza inspirée de Rome avec crème de pecorino romano et poivre noir généreux"}'::jsonb,
    '{"en":"The Roman pasta classic, reimagined","it":"Il classico romano, reinterpretato"}'::jsonb,
    'gourmet',
    'romana',
    '{"roman","cheese","spicy","vegetarian","pasta-inspired"}',
    '{"country":"Italy","country_code":"IT","region":"Lazio","city":"Rome"}'::jsonb,
    '{"story":{"en":"A pizza interpretation of the beloved Roman pasta dish cacio e pepe, combining the same simple but powerful flavors of aged pecorino and black pepper.","it":"Un''interpretazione in pizza del famoso piatto romano cacio e pepe, che combina gli stessi sapori semplici ma potenti del pecorino stagionato e pepe nero."}}'::jsonb,
    'white',
    'pecorino',
    '{"mozzarella_fior_di_latte"}',
    'roman',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"pecorino_romano","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"black_pepper","quantity":{"amount":2,"unit":"tsp"}},{"ingredient_id":"olive_oil","quantity":{"amount":2,"unit":"tbsp"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":320,"time_seconds":300}'::jsonb,
    '{"profile":["sharp","peppery","savory","rich"],"spice_level":2}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    78,
    '{"cheese-lovers","pasta-fans","roman-cuisine"}',
    '{"carbonara","quattro-formaggi"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '8bdd7441-873e-46cb-987c-7c3d30959efe',
    'amatriciana',
    'pizza_amatriciana',
    '{"en":"Amatriciana","it":"Amatriciana","es":"Amatriciana","de":"Amatriciana","fr":"Amatriciana"}'::jsonb,
    '{"en":"Pizza inspired by the famous pasta dish from Amatrice with guanciale, tomato, pecorino, and a hint of chili","it":"Pizza ispirata al famoso piatto di Amatrice con guanciale, pomodoro, pecorino e un tocco di peperoncino","es":"Pizza inspirada en el famoso plato de Amatrice con guanciale, tomate, pecorino y un toque de chile","de":"Pizza inspiriert vom berühmten Gericht aus Amatrice mit Guanciale, Tomate, Pecorino und Chili","fr":"Pizza inspirée du célèbre plat d''Amatrice avec guanciale, tomate, pecorino et piment"}'::jsonb,
    NULL,
    'regional',
    'romana',
    '{"roman","guanciale","spicy","pasta-inspired","traditional"}',
    '{"country":"Italy","country_code":"IT","region":"Lazio","city":"Amatrice"}'::jsonb,
    '{"story":{"en":"Based on the iconic pasta all''Amatriciana from the town of Amatrice in Lazio, this pizza brings the same bold flavors of guanciale and pecorino to a crispy Roman base.","it":"Basata sull''iconica pasta all''Amatriciana dalla città di Amatrice nel Lazio, questa pizza porta gli stessi sapori decisi del guanciale e pecorino su una base romana croccante."}}'::jsonb,
    'tomato',
    'pecorino',
    '{"mozzarella_fior_di_latte"}',
    'roman',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"san_marzano_tomatoes","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"guanciale","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"pecorino_romano","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"red_chili","quantity":{"amount":1,"unit":"piece"}},{"ingredient_id":"olive_oil","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":320,"time_seconds":300}'::jsonb,
    '{"profile":["savory","spicy","smoky","tangy"],"spice_level":2}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    75,
    '{"meat-lovers","pasta-fans","spicy-food"}',
    '{"carbonara","cacio-e-pepe"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '6baee110-1d1c-4dce-9470-9af9576d4c86',
    'pizza-fritta',
    'pizza_fritta',
    '{"en":"Pizza Fritta","it":"Pizza Fritta","es":"Pizza Frita","de":"Frittierte Pizza","fr":"Pizza Frite"}'::jsonb,
    '{"en":"Traditional Neapolitan deep-fried pizza filled with ricotta, cicoli, and provola cheese","it":"Pizza fritta napoletana tradizionale ripiena di ricotta, cicoli e provola","es":"Pizza napolitana frita tradicional rellena de ricotta, cicoli y queso provola","de":"Traditionelle frittierte neapolitanische Pizza gefüllt mit Ricotta, Cicoli und Provola","fr":"Pizza napolitaine frite traditionnelle farcie de ricotta, cicoli et provola"}'::jsonb,
    NULL,
    'regional',
    'napoletana',
    '{"neapolitan","fried","street-food","traditional","stuffed"}',
    '{"country":"Italy","country_code":"IT","region":"Campania","city":"Naples","year_created":"1940s"}'::jsonb,
    '{"story":{"en":"Born in post-war Naples when wood for ovens was scarce, pizza fritta was made by frying the dough in lard. It became a beloved street food and is still popular in Naples today.","it":"Nata nella Napoli del dopoguerra quando la legna per i forni scarseggiava, la pizza fritta veniva preparata friggendo l''impasto nello strutto. È diventata uno street food amato ed è ancora popolare a Napoli oggi."},"fun_fact":{"en":"The famous scene in the movie \"L''Oro di Napoli\" by Vittorio De Sica shows Sophia Loren making pizza fritta.","it":"La famosa scena nel film \"L''Oro di Napoli\" di Vittorio De Sica mostra Sophia Loren che prepara la pizza fritta."}}'::jsonb,
    'none',
    'ricotta',
    '{"provolone"}',
    'neapolitan',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"ricotta","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"provolone","quantity":{"amount":60,"unit":"g"}},{"ingredient_id":"cicoli","quantity":{"amount":50,"unit":"g"},"notes":{"en":"Traditional pork cracklings"}},{"ingredient_id":"black_pepper","quantity":{"amount":1,"unit":"tsp"}}]'::jsonb,
    '{"method":"pan","temperature_celsius":180,"time_seconds":180,"notes":{"en":"Deep fried in vegetable oil or traditionally in lard","it":"Fritta in olio vegetale o tradizionalmente nello strutto"}}'::jsonb,
    '{"profile":["rich","creamy","savory","crispy"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole"],"portions_whole":1,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    70,
    '{"adventurous-eaters","street-food-lovers"}',
    '{"calzone"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '12066986-56a2-4925-bff4-8a6a4c195663',
    'montanara',
    'pizza_montanara',
    '{"en":"Montanara","it":"Montanara","es":"Montanara","de":"Montanara","fr":"Montanara"}'::jsonb,
    '{"en":"Semi-fried Neapolitan pizza topped with tomato, mozzarella, and basil after frying","it":"Pizza napoletana semi-fritta condita con pomodoro, mozzarella e basilico dopo la frittura","es":"Pizza napolitana semi-frita cubierta con tomate, mozzarella y albahaca después de freír","de":"Halb-frittierte neapolitanische Pizza mit Tomate, Mozzarella und Basilikum nach dem Frittieren","fr":"Pizza napolitaine semi-frite garnie de tomate, mozzarella et basilic après friture"}'::jsonb,
    NULL,
    'regional',
    'napoletana',
    '{"neapolitan","fried","street-food","traditional"}',
    '{"country":"Italy","country_code":"IT","region":"Campania","city":"Naples"}'::jsonb,
    '{"story":{"en":"A hybrid between pizza fritta and regular pizza, the montanara is lightly fried then topped and finished in the oven, giving it a unique crispy-soft texture.","it":"Un ibrido tra pizza fritta e pizza normale, la montanara viene leggermente fritta poi condita e finita in forno, dandole una texture unica croccante-morbida."}}'::jsonb,
    'tomato',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":200,"unit":"g"}},{"ingredient_id":"san_marzano_tomatoes","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"fresh_basil","quantity":{"amount":5,"unit":"piece"}},{"ingredient_id":"parmesan","quantity":{"amount":20,"unit":"g"}},{"ingredient_id":"olive_oil","quantity":{"amount":1,"unit":"tbsp"}}]'::jsonb,
    '{"method":"wood_fired","temperature_celsius":450,"time_seconds":90,"notes":{"en":"Fried first for 30 seconds, then topped and baked in wood oven","it":"Prima fritta per 30 secondi, poi condita e cotta in forno a legna"}}'::jsonb,
    '{"profile":["savory","fresh","crispy","aromatic"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole"],"portions_whole":1,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    65,
    '{"adventurous-eaters","texture-lovers"}',
    '{"pizza-fritta","margherita"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();