-- ============================================================================
-- GUDBRO Pizza Database - Batch 13
-- Pizzas 61 to 62 of 62
-- ============================================================================
-- Pizzas in this batch:
--   - Pulled Pork BBQ (pulled-pork)
--   - Philly Cheesesteak (philly-cheesesteak)
-- ============================================================================

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'ace122b2-42bc-4a9f-a620-c56f693e781d',
    'pulled-pork',
    'pizza_pulled_pork',
    '{"en":"Pulled Pork BBQ","it":"Pulled Pork BBQ","es":"Cerdo Desmenuzado BBQ","de":"Pulled Pork BBQ","fr":"Porc Effiloché BBQ"}'::jsonb,
    '{"en":"American BBQ pizza with slow-smoked pulled pork, coleslaw, pickles, and tangy BBQ sauce","it":"Pizza BBQ americana con pulled pork affumicato lentamente, coleslaw, cetriolini e salsa BBQ","es":"Pizza BBQ americana con cerdo desmenuzado ahumado, ensalada de col, pepinillos y salsa BBQ","de":"Amerikanische BBQ-Pizza mit langsam geräuchertem Pulled Pork, Krautsalat, Gurken und BBQ-Sauce","fr":"Pizza BBQ américaine avec porc effiloché fumé, coleslaw, cornichons et sauce BBQ"}'::jsonb,
    NULL,
    'fusion',
    'fusion',
    '{"american","bbq","pork","smoked","southern"}',
    '{"country":"USA","country_code":"US","region":"Southern States"}'::jsonb,
    NULL,
    'bbq',
    'mozzarella_fior_di_latte',
    '{"provolone"}',
    'american',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"bbq_sauce","quantity":{"amount":80,"unit":"ml"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"provolone","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"pulled_pork","quantity":{"amount":150,"unit":"g"}},{"ingredient_id":"coleslaw","quantity":{"amount":50,"unit":"g"},"is_topping":true},{"ingredient_id":"pickles","quantity":{"amount":30,"unit":"g"},"is_topping":true},{"ingredient_id":"red_onion","quantity":{"amount":30,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":260,"time_seconds":480}'::jsonb,
    '{"profile":["smoky","sweet","tangy","savory"],"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    77,
    '{"bbq-lovers","meat-lovers"}',
    '{"bbq-chicken","meat-lovers"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '2a92c487-117c-47f6-bf2a-67b21af77ef4',
    'philly-cheesesteak',
    'pizza_philly_cheesesteak',
    '{"en":"Philly Cheesesteak","it":"Philly Cheesesteak","es":"Philly Cheesesteak","de":"Philly Cheesesteak","fr":"Philly Cheesesteak"}'::jsonb,
    '{"en":"Pizza inspired by Philadelphia''s famous sandwich with sliced steak, peppers, onions, and cheese sauce","it":"Pizza ispirata al famoso panino di Philadelphia con bistecca a fette, peperoni, cipolle e salsa al formaggio","es":"Pizza inspirada en el famoso sándwich de Filadelfia con bistec en rodajas, pimientos, cebollas y salsa de queso","de":"Pizza inspiriert vom berühmten Philadelphia-Sandwich mit Steak, Paprika, Zwiebeln und Käsesauce","fr":"Pizza inspirée du célèbre sandwich de Philadelphie avec steak tranché, poivrons, oignons et sauce au fromage"}'::jsonb,
    NULL,
    'fusion',
    'fusion',
    '{"american","steak","cheese","philadelphia","peppers"}',
    '{"country":"USA","country_code":"US","city":"Philadelphia"}'::jsonb,
    NULL,
    'white',
    'provolone',
    '{}',
    'american',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"cheese_sauce","quantity":{"amount":80,"unit":"ml"}},{"ingredient_id":"provolone","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"sliced_steak","quantity":{"amount":150,"unit":"g"}},{"ingredient_id":"green_pepper","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"onion","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"mushrooms","quantity":{"amount":40,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":260,"time_seconds":480}'::jsonb,
    '{"profile":["savory","cheesy","rich","meaty"],"spice_level":0}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    74,
    '{"steak-lovers","american-food-fans"}',
    '{"meat-lovers"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();