-- ============================================================================
-- GUDBRO Pizza Database - Batch 11
-- Pizzas 51 to 55 of 62
-- ============================================================================
-- Pizzas in this batch:
--   - Korean BBQ (korean-bbq)
--   - Thai Chicken (thai-chicken)
--   - Chicken Tikka Masala (tikka-masala)
--   - Tandoori Pizza (tandoori)
--   - Taco Pizza (taco-pizza)
-- ============================================================================

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '4cd7234f-dc1a-479d-9dbb-7e9ec0bb1493',
    'korean-bbq',
    'pizza_korean_bbq',
    '{"en":"Korean BBQ","it":"BBQ Coreano","es":"BBQ Coreano","de":"Koreanisches BBQ","fr":"BBQ Coréen","ko":"코리안 바베큐"}'::jsonb,
    '{"en":"Korean-inspired pizza with bulgogi beef, kimchi, gochujang, and sesame","it":"Pizza ispirata alla Corea con manzo bulgogi, kimchi, gochujang e sesamo","es":"Pizza inspirada en Corea con carne bulgogi, kimchi, gochujang y sésamo","de":"Koreanisch inspirierte Pizza mit Bulgogi-Rind, Kimchi, Gochujang und Sesam","fr":"Pizza d''inspiration coréenne avec bœuf bulgogi, kimchi, gochujang et sésame"}'::jsonb,
    NULL,
    'fusion',
    'fusion',
    '{"korean","asian","beef","spicy","kimchi"}',
    '{"country":"USA / Korea","country_code":"US"}'::jsonb,
    '{"story":{"en":"A modern fusion pizza that brings the bold flavors of Korean BBQ to pizza, featuring marinated bulgogi beef, fermented kimchi, and spicy gochujang sauce.","it":"Una pizza fusion moderna che porta i sapori decisi del BBQ coreano sulla pizza, con manzo bulgogi marinato, kimchi fermentato e salsa gochujang piccante."}}'::jsonb,
    'none',
    'mozzarella_fior_di_latte',
    '{}',
    'american',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"gochujang_sauce","quantity":{"amount":60,"unit":"ml"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":120,"unit":"g"}},{"ingredient_id":"bulgogi_beef","quantity":{"amount":150,"unit":"g"}},{"ingredient_id":"kimchi","quantity":{"amount":60,"unit":"g"},"is_topping":true},{"ingredient_id":"green_onion","quantity":{"amount":20,"unit":"g"},"is_topping":true},{"ingredient_id":"sesame_seeds","quantity":{"amount":1,"unit":"tbsp"},"is_topping":true},{"ingredient_id":"sesame_oil","quantity":{"amount":1,"unit":"tsp"},"is_topping":true}]'::jsonb,
    '{"method":"electric","temperature_celsius":280,"time_seconds":420}'::jsonb,
    '{"profile":["spicy","sweet","umami","fermented"],"spice_level":3}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy","soy","sesame"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    70,
    '{"asian-food-lovers","spicy-lovers"}',
    '{"teriyaki-chicken"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    '9e8ae8f6-2643-44c6-8689-1b7d6f258eca',
    'thai-chicken',
    'pizza_thai_chicken',
    '{"en":"Thai Chicken","it":"Pollo Thai","es":"Pollo Tailandés","de":"Thai Hähnchen","fr":"Poulet Thaï","th":"ไก่ไทย"}'::jsonb,
    '{"en":"Thai-inspired pizza with peanut sauce, chicken, bean sprouts, cilantro, and lime","it":"Pizza ispirata alla Thailandia con salsa di arachidi, pollo, germogli di soia, coriandolo e lime","es":"Pizza inspirada en Tailandia con salsa de cacahuete, pollo, brotes de soja, cilantro y lima","de":"Thai-inspirierte Pizza mit Erdnusssauce, Hähnchen, Sojasprossen, Koriander und Limette","fr":"Pizza d''inspiration thaïlandaise avec sauce cacahuète, poulet, germes de soja, coriandre et citron vert"}'::jsonb,
    NULL,
    'fusion',
    'california',
    '{"thai","asian","peanut","chicken","cilantro"}',
    '{"country":"USA","country_code":"US","city":"California","year_created":"1985","creator":"Ed LaDou / California Pizza Kitchen"}'::jsonb,
    '{"story":{"en":"One of the original California-style gourmet pizzas, the Thai Chicken pizza helped revolutionize American pizza in the 1980s by incorporating Asian flavors.","it":"Una delle pizze gourmet originali in stile californiano, la pizza Thai Chicken ha contribuito a rivoluzionare la pizza americana negli anni ''80 incorporando sapori asiatici."}}'::jsonb,
    'none',
    'mozzarella_fior_di_latte',
    '{}',
    'american',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"peanut_sauce","quantity":{"amount":80,"unit":"ml"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"chicken_breast","quantity":{"amount":120,"unit":"g"}},{"ingredient_id":"bean_sprouts","quantity":{"amount":50,"unit":"g"},"is_topping":true},{"ingredient_id":"cilantro","quantity":{"amount":1,"unit":"handful"},"is_topping":true},{"ingredient_id":"green_onion","quantity":{"amount":20,"unit":"g"},"is_topping":true},{"ingredient_id":"lime","quantity":{"amount":1,"unit":"slice"},"is_topping":true},{"ingredient_id":"crushed_peanuts","quantity":{"amount":2,"unit":"tbsp"},"is_topping":true},{"ingredient_id":"carrot","quantity":{"amount":30,"unit":"g"}}]'::jsonb,
    '{"method":"electric","temperature_celsius":280,"time_seconds":420}'::jsonb,
    '{"profile":["nutty","tangy","savory","fresh"],"spice_level":1}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":false,"allergens":["gluten","dairy","peanuts"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    74,
    '{"asian-food-lovers","california-style-fans"}',
    '{"teriyaki-chicken","korean-bbq"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'c5f282f7-38dc-4f05-8550-c3b5cc36c73d',
    'tikka-masala',
    'pizza_tikka_masala',
    '{"en":"Chicken Tikka Masala","it":"Pollo Tikka Masala","es":"Pollo Tikka Masala","de":"Hähnchen Tikka Masala","fr":"Poulet Tikka Masala","hi":"चिकन टिक्का मसाला"}'::jsonb,
    '{"en":"Indian-inspired pizza with tikka masala sauce, tandoori chicken, cilantro, and red onions","it":"Pizza ispirata all''India con salsa tikka masala, pollo tandoori, coriandolo e cipolle rosse","es":"Pizza inspirada en India con salsa tikka masala, pollo tandoori, cilantro y cebolla roja","de":"Indisch inspirierte Pizza mit Tikka Masala Sauce, Tandoori-Hähnchen, Koriander und roten Zwiebeln","fr":"Pizza d''inspiration indienne avec sauce tikka masala, poulet tandoori, coriandre et oignons rouges"}'::jsonb,
    NULL,
    'fusion',
    'fusion',
    '{"indian","tikka-masala","chicken","spicy","fusion"}',
    '{"country":"UK / India","country_code":"GB"}'::jsonb,
    '{"story":{"en":"Combining Britain''s favorite curry with pizza, this fusion creation brings the creamy, aromatic tikka masala sauce to a pizza base for a unique East-meets-West experience.","it":"Combinando il curry preferito della Gran Bretagna con la pizza, questa creazione fusion porta la salsa tikka masala cremosa e aromatica su una base di pizza per un''esperienza unica Est-incontra-Ovest."}}'::jsonb,
    'none',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"tikka_masala_sauce","quantity":{"amount":100,"unit":"ml"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"tandoori_chicken","quantity":{"amount":150,"unit":"g"}},{"ingredient_id":"red_onion","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"cilantro","quantity":{"amount":1,"unit":"handful"},"is_topping":true},{"ingredient_id":"green_chili","quantity":{"amount":1,"unit":"piece"},"is_optional":true}]'::jsonb,
    '{"method":"electric","temperature_celsius":280,"time_seconds":420}'::jsonb,
    '{"profile":["creamy","spicy","aromatic","rich"],"spice_level":2}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":false,"allergens":["gluten","dairy","tree_nuts"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    73,
    '{"indian-food-lovers","curry-fans"}',
    '{"tandoori"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'ea33f8ee-6362-439c-ae23-4c62a0fceefb',
    'tandoori',
    'pizza_tandoori',
    '{"en":"Tandoori Pizza","it":"Pizza Tandoori","es":"Pizza Tandoori","de":"Tandoori Pizza","fr":"Pizza Tandoori","hi":"तंदूरी पिज़्ज़ा"}'::jsonb,
    '{"en":"Indian-inspired pizza with tandoori-spiced chicken, peppers, onions, and mint yogurt drizzle","it":"Pizza ispirata all''India con pollo speziato tandoori, peperoni, cipolle e yogurt alla menta","es":"Pizza inspirada en India con pollo especiado tandoori, pimientos, cebollas y yogur con menta","de":"Indisch inspirierte Pizza mit Tandoori-gewürztem Hähnchen, Paprika, Zwiebeln und Minzjoghurt","fr":"Pizza d''inspiration indienne avec poulet épicé tandoori, poivrons, oignons et yaourt à la menthe"}'::jsonb,
    NULL,
    'fusion',
    'fusion',
    '{"indian","tandoori","chicken","yogurt","spicy"}',
    '{"country":"UK / India","country_code":"GB"}'::jsonb,
    NULL,
    'none',
    'mozzarella_fior_di_latte',
    '{}',
    'neapolitan',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"tomato_sauce","quantity":{"amount":80,"unit":"ml"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":100,"unit":"g"}},{"ingredient_id":"tandoori_chicken","quantity":{"amount":150,"unit":"g"}},{"ingredient_id":"red_pepper","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"red_onion","quantity":{"amount":50,"unit":"g"}},{"ingredient_id":"mint_yogurt","quantity":{"amount":3,"unit":"tbsp"},"is_topping":true},{"ingredient_id":"cilantro","quantity":{"amount":1,"unit":"handful"},"is_topping":true}]'::jsonb,
    '{"method":"electric","temperature_celsius":280,"time_seconds":420}'::jsonb,
    '{"profile":["smoky","spicy","tangy","aromatic"],"spice_level":2}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    71,
    '{"indian-food-lovers","spicy-lovers"}',
    '{"tikka-masala"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();

INSERT INTO pizzas (
    id, slug, stable_key,
    name, description, tagline,
    status, style, tags,
    origin, history,
    base, primary_cheese, additional_cheeses, dough_type,
    ingredients, cooking, flavor, dietary, serving,
    variations, popularity, recommended_for, related_pizzas,
    media, source_url, source_note, version
) VALUES (
    'ee665e47-e792-454a-b37e-7d7ad7516565',
    'taco-pizza',
    'pizza_taco',
    '{"en":"Taco Pizza","it":"Pizza Taco","es":"Pizza Taco","de":"Taco Pizza","fr":"Pizza Taco"}'::jsonb,
    '{"en":"Mexican-inspired pizza with seasoned ground beef, cheddar, lettuce, tomato, sour cream, and salsa","it":"Pizza ispirata al Messico con manzo macinato speziato, cheddar, lattuga, pomodoro, panna acida e salsa","es":"Pizza inspirada en México con carne molida sazonada, cheddar, lechuga, tomate, crema agria y salsa","de":"Mexikanisch inspirierte Pizza mit gewürztem Rinderhack, Cheddar, Salat, Tomate, Sauerrahm und Salsa","fr":"Pizza d''inspiration mexicaine avec bœuf haché assaisonné, cheddar, laitue, tomate, crème aigre et salsa"}'::jsonb,
    NULL,
    'fusion',
    'fusion',
    '{"mexican","taco","beef","cheddar","tex-mex"}',
    '{"country":"USA","country_code":"US","region":"Midwest","year_created":"1970s"}'::jsonb,
    '{"story":{"en":"Taco pizza originated in the American Midwest and became a popular fusion dish, combining the flavors of a taco with the format of a pizza.","it":"La pizza taco ha origine nel Midwest americano ed è diventata un piatto fusion popolare, combinando i sapori di un taco con il formato di una pizza."}}'::jsonb,
    'none',
    'mozzarella_fior_di_latte',
    '{}',
    'american',
    '[{"ingredient_id":"pizza_dough","quantity":{"amount":250,"unit":"g"}},{"ingredient_id":"refried_beans","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"mozzarella_fior_di_latte","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"cheddar","quantity":{"amount":80,"unit":"g"}},{"ingredient_id":"seasoned_ground_beef","quantity":{"amount":150,"unit":"g"}},{"ingredient_id":"lettuce","quantity":{"amount":50,"unit":"g"},"is_topping":true},{"ingredient_id":"tomato","quantity":{"amount":50,"unit":"g"},"is_topping":true},{"ingredient_id":"sour_cream","quantity":{"amount":3,"unit":"tbsp"},"is_topping":true},{"ingredient_id":"salsa","quantity":{"amount":3,"unit":"tbsp"},"is_topping":true}]'::jsonb,
    '{"method":"electric","temperature_celsius":260,"time_seconds":480}'::jsonb,
    '{"profile":["savory","tangy","fresh","spicy"],"spice_level":2}'::jsonb,
    '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"allergens":["gluten","dairy"]}'::jsonb,
    '{"suggested_modes":["whole","slice"],"portions_whole":8,"ideal_temperature":"hot"}'::jsonb,
    NULL,
    76,
    '{"taco-lovers","families"}',
    '{"mexicana"}',
    NULL,
    NULL,
    NULL,
    1
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tagline = EXCLUDED.tagline,
    status = EXCLUDED.status,
    style = EXCLUDED.style,
    tags = EXCLUDED.tags,
    origin = EXCLUDED.origin,
    history = EXCLUDED.history,
    base = EXCLUDED.base,
    primary_cheese = EXCLUDED.primary_cheese,
    additional_cheeses = EXCLUDED.additional_cheeses,
    dough_type = EXCLUDED.dough_type,
    ingredients = EXCLUDED.ingredients,
    cooking = EXCLUDED.cooking,
    flavor = EXCLUDED.flavor,
    dietary = EXCLUDED.dietary,
    serving = EXCLUDED.serving,
    variations = EXCLUDED.variations,
    popularity = EXCLUDED.popularity,
    recommended_for = EXCLUDED.recommended_for,
    related_pizzas = EXCLUDED.related_pizzas,
    media = EXCLUDED.media,
    source_url = EXCLUDED.source_url,
    source_note = EXCLUDED.source_note,
    version = EXCLUDED.version,
    updated_at = NOW();