-- Swiss New Ingredients
-- Generated by inventory-checker v2.2
-- Date: 2025-12-25
-- GUDBRO Database Standards v1.7
-- NOTE: 6 ingredients removed (already exist with plural forms in cache)
-- FIX: Using valid enum categories (proteins instead of meat)

INSERT INTO ingredients (id, name, slug, category) VALUES
('ING_APPLESAUCE', 'Applesauce', 'applesauce', 'condiments'),
('ING_BUNDNERFLEISCH', 'Bundnerfleisch', 'bundnerfleisch', 'proteins'),
('ING_CANDIED_LEMON', 'Candied Lemon Peel', 'candied-lemon-peel', 'other'),
('ING_CURED_HAM', 'Cured Ham', 'cured-ham', 'proteins'),
('ING_DOUBLE_CREAM', 'Double Cream', 'double-cream', 'dairy'),
('ING_DRIED_PEAR', 'Dried Pear', 'dried-pear', 'fruits'),
('ING_EMMENTAL', 'Emmental Cheese', 'emmental-cheese', 'cheese'),
('ING_GARLIC_SAUCE', 'Garlic Sauce', 'garlic-sauce', 'sauces'),
('ING_PORK_RIND', 'Pork Rind', 'pork-rind', 'proteins'),
('ING_RACLETTE_CHEESE', 'Raclette Cheese', 'raclette-cheese', 'cheese'),
('ING_SAUCISSE_CHOUX', 'Cabbage Sausage', 'cabbage-sausage', 'proteins'),
('ING_VACHERIN', 'Vacherin Cheese', 'vacherin-cheese', 'cheese')
ON CONFLICT (id) DO NOTHING;
