-- ============================================
-- Swiss Cuisine - Data Insert
-- Created: 2025-12-25
-- Total dishes: 38
-- ============================================

-- CHEESE DISHES (5 dishes)
INSERT INTO swiss (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('SUI_FONDUE', 'cheese-fondue', 'Cheese Fondue', 'Fondue au Fromage', 'Melted cheese blend of Gruyère and Emmental with white wine and kirsch, served in a caquelon with bread cubes for dipping', 'cheese_dishes', 'nationwide', 'classic', NULL, 'melted', 30, 0, 24.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy', 'gluten'], ARRAY[]::TEXT[], ARRAY['ING_GRUYERE', 'ING_EMMENTAL', 'ING_WHITE_WINE', 'ING_KIRSCH', 'ING_GARLIC', 'ING_CORNSTARCH', 'ING_NUTMEG', 'ING_BREAD'], ARRAY['iconic', 'sharing', 'winter', 'alpine'], 98),
('SUI_RACLETTE', 'raclette', 'Raclette', 'Raclette', 'Melted raclette cheese scraped onto boiled potatoes, served with pickles, pickled onions, and cured meats', 'cheese_dishes', 'valais', 'classic', NULL, 'melted', 45, 0, 22.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy'], ARRAY[]::TEXT[], ARRAY['ING_RACLETTE_CHEESE', 'ING_POTATO', 'ING_CORNICHONS', 'ING_PICKLED_ONION', 'ING_CURED_HAM'], ARRAY['iconic', 'alpine', 'winter', 'sharing'], 95),
('SUI_FONDUE_MOITIE', 'fondue-moitie-moitie', 'Fondue Moitié-Moitié', 'Fondue Moitié-Moitié', 'Classic Fribourg-style fondue with half Gruyère and half Vacherin cheese, extra creamy and aromatic', 'cheese_dishes', 'vaud', 'traditional', NULL, 'melted', 30, 0, 26.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy', 'gluten'], ARRAY[]::TEXT[], ARRAY['ING_GRUYERE', 'ING_VACHERIN', 'ING_WHITE_WINE', 'ING_KIRSCH', 'ING_GARLIC', 'ING_BREAD'], ARRAY['creamy', 'fribourg', 'cheese'], 85),
('SUI_FONDUE_BOURGUIGNONNE', 'fondue-bourguignonne', 'Fondue Bourguignonne', 'Fondue Bourguignonne', 'Swiss-origin meat fondue where cubes of beef are cooked in hot oil, served with various dipping sauces', 'cheese_dishes', 'nationwide', 'popular', 'beef', 'deep_fried', 30, 0, 32.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_BEEF_TENDERLOIN', 'ING_VEGETABLE_OIL', 'ING_MAYONNAISE', 'ING_MUSTARD', 'ING_KETCHUP', 'ING_GARLIC_SAUCE'], ARRAY['meat', 'sharing', 'festive'], 78),
('SUI_FONDUE_CHINOISE', 'fondue-chinoise', 'Fondue Chinoise', 'Fondue Chinoise', 'Hot pot style fondue popular in Switzerland, thin slices of meat cooked in simmering broth', 'cheese_dishes', 'nationwide', 'popular', 'mixed', 'boiled', 30, 0, 29.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_BEEF', 'ING_CHICKEN', 'ING_BEEF_BROTH', 'ING_SOY_SAUCE', 'ING_GINGER', 'ING_SCALLION'], ARRAY['hot_pot', 'sharing', 'christmas'], 75);

-- MAINS (6 dishes)
INSERT INTO swiss (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('SUI_GESCHNETZELTES', 'zurcher-geschnetzeltes', 'Zürcher Geschnetzeltes', 'Zürcher Geschnetzeltes', 'Zürich-style sliced veal in creamy white wine and mushroom sauce, traditionally served with rösti', 'mains', 'zurich', 'classic', 'veal', 'sauteed', 35, 0, 28.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy', 'gluten'], ARRAY[]::TEXT[], ARRAY['ING_VEAL', 'ING_MUSHROOM', 'ING_HEAVY_CREAM', 'ING_WHITE_WINE', 'ING_BUTTER', 'ING_SHALLOT', 'ING_FLOUR', 'ING_BEEF_BROTH'], ARRAY['iconic', 'zurich', 'creamy', 'elegant'], 92),
('SUI_CORDON_BLEU', 'cordon-bleu', 'Cordon Bleu', 'Cordon Bleu', 'Breaded veal or chicken cutlet stuffed with ham and melted Gruyère cheese, pan-fried until golden', 'mains', 'nationwide', 'classic', 'veal', 'pan_fried', 40, 0, 26.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'eggs', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_VEAL', 'ING_HAM', 'ING_GRUYERE', 'ING_EGG', 'ING_BREADCRUMB', 'ING_FLOUR', 'ING_BUTTER'], ARRAY['iconic', 'breaded', 'stuffed', 'comfort_food'], 90),
('SUI_CAPUNS', 'capuns', 'Capuns', 'Capuns', 'Graubünden specialty of spätzle dough with dried meat wrapped in chard leaves, baked in cream', 'mains', 'graubunden', 'regional', 'mixed', 'baked', 60, 0, 22.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'eggs', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_MILK', 'ING_BUNDNERFLEISCH', 'ING_SWISS_CHARD', 'ING_HEAVY_CREAM', 'ING_CHEESE'], ARRAY['graubunden', 'wrapped', 'hearty', 'alpine'], 72),
('SUI_CHOLERA', 'cholera', 'Cholera', 'Cholera', 'Rustic Valais vegetable and cheese pie with potatoes, apples, leeks, and local cheese in pastry', 'mains', 'valais', 'regional', NULL, 'baked', 75, 0, 18.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_POTATO', 'ING_APPLE', 'ING_LEEK', 'ING_ONION', 'ING_CHEESE', 'ING_HEAVY_CREAM'], ARRAY['valais', 'pie', 'vegetarian', 'rustic'], 65),
('SUI_PAPET_VAUDOIS', 'papet-vaudois', 'Papet Vaudois', 'Papet Vaudois', 'Traditional Vaud dish of leeks and potatoes slow-cooked together, served with cabbage sausage', 'mains', 'vaud', 'traditional', 'pork', 'braised', 90, 0, 21.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy'], ARRAY[]::TEXT[], ARRAY['ING_LEEK', 'ING_POTATO', 'ING_SAUCISSE_CHOUX', 'ING_BUTTER', 'ING_HEAVY_CREAM', 'ING_WHITE_WINE'], ARRAY['vaud', 'comfort_food', 'winter', 'sausage'], 75),
('SUI_ALPLERMAGRONEN', 'alplermagronen', 'Älplermagronen', 'Älplermagronen', 'Alpine macaroni with potatoes, cheese, cream and crispy fried onions, served with applesauce', 'mains', 'central', 'classic', NULL, 'baked', 45, 0, 16.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_MACARONI', 'ING_POTATO', 'ING_GRUYERE', 'ING_HEAVY_CREAM', 'ING_ONION', 'ING_BUTTER', 'ING_APPLESAUCE'], ARRAY['alpine', 'comfort_food', 'hearty', 'vegetarian'], 88);

-- SIDES (4 dishes)
INSERT INTO swiss (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('SUI_ROSTI', 'rosti', 'Rösti', 'Rösti', 'Iconic Swiss potato pancake, crispy on outside, soft inside, originally a Bernese farmer breakfast', 'sides', 'bern', 'classic', NULL, 'pan_fried', 30, 0, 8.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['dairy'], ARRAY[]::TEXT[], ARRAY['ING_POTATO', 'ING_BUTTER', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY['iconic', 'potato', 'crispy', 'comfort_food'], 95),
('SUI_ROSTI_CHEESE', 'rosti-with-cheese', 'Rösti with Cheese', 'Käserösti', 'Classic rösti topped with melted Raclette or Gruyère cheese', 'sides', 'bern', 'popular', NULL, 'pan_fried', 35, 0, 12.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['dairy'], ARRAY[]::TEXT[], ARRAY['ING_POTATO', 'ING_BUTTER', 'ING_GRUYERE', 'ING_SALT'], ARRAY['cheese', 'potato', 'comfort_food'], 88),
('SUI_SPATZLE', 'spatzle', 'Spätzle', 'Spätzle', 'Soft egg noodles popular in German-speaking Switzerland, often served with cheese or as a side', 'sides', 'zurich', 'traditional', NULL, 'boiled', 25, 0, 7.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_MILK', 'ING_SALT', 'ING_NUTMEG', 'ING_BUTTER'], ARRAY['noodles', 'comfort_food', 'german_swiss'], 80),
('SUI_KASESPATZLE', 'kasespatzle', 'Käsespätzle', 'Käsespätzle', 'Spätzle layered with melted cheese and topped with crispy fried onions', 'sides', 'zurich', 'popular', NULL, 'baked', 35, 0, 14.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_MILK', 'ING_EMMENTAL', 'ING_ONION', 'ING_BUTTER'], ARRAY['cheese', 'noodles', 'comfort_food'], 82);

-- SAUSAGES (5 dishes)
INSERT INTO swiss (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('SUI_CERVELAT', 'cervelat', 'Cervelat', 'Cervelat', 'Switzerland national sausage, lightly smoked beef and pork sausage, often grilled or eaten cold', 'sausages', 'nationwide', 'classic', 'mixed', 'grilled', 15, 0, 6.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_BEEF', 'ING_PORK', 'ING_PORK_RIND', 'ING_SALT', 'ING_CORIANDER', 'ING_GARLIC'], ARRAY['national', 'sausage', 'bbq', 'picnic'], 90),
('SUI_BRATWURST', 'st-galler-bratwurst', 'St. Galler Bratwurst', 'St. Galler Bratwurst', 'Famous white veal bratwurst from St. Gallen, traditionally served without mustard in a bun', 'sausages', 'zurich', 'classic', 'veal', 'grilled', 15, 0, 8.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_VEAL', 'ING_PORK', 'ING_MILK', 'ING_BREAD_ROLL', 'ING_SALT', 'ING_WHITE_PEPPER'], ARRAY['st_gallen', 'sausage', 'street_food'], 88),
('SUI_BUNDNERFLEISCH', 'bundnerfleisch', 'Bündnerfleisch', 'Bündnerfleisch', 'Air-dried beef from Graubünden, cured with salt, wine and herbs, sliced paper thin', 'sausages', 'graubunden', 'classic', 'beef', 'cured', 10, 0, 18.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_BEEF', 'ING_SALT', 'ING_WHITE_WINE', 'ING_ONION', 'ING_BAY_LEAF', 'ING_JUNIPER_BERRIES'], ARRAY['cured', 'dried', 'graubunden', 'appetizer'], 85),
('SUI_SAUCISSON_VAUDOIS', 'saucisson-vaudois', 'Saucisson Vaudois', 'Saucisson Vaudois', 'Smoked pork sausage from Vaud, traditionally poached and served with Papet Vaudois', 'sausages', 'vaud', 'traditional', 'pork', 'poached', 45, 0, 12.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_PORK', 'ING_PORK_BELLY', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_GARLIC', 'ING_WHITE_WINE'], ARRAY['vaud', 'smoked', 'sausage'], 75),
('SUI_LONGEOLE', 'longeole', 'Longeole', 'Longeole', 'Geneva specialty sausage made with pork and fennel seeds, typically served with lentils', 'sausages', 'geneva', 'regional', 'pork', 'poached', 60, 0, 14.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_PORK', 'ING_PORK_RIND', 'ING_FENNEL_SEED', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_LENTILS'], ARRAY['geneva', 'fennel', 'sausage', 'winter'], 68);

-- SOUPS (3 dishes)
INSERT INTO swiss (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('SUI_GERSTENSUPPE', 'bundner-gerstensuppe', 'Bündner Gerstensuppe', 'Bündner Gerstensuppe', 'Hearty Graubünden barley soup with smoked meat, vegetables, and dried beef', 'soups', 'graubunden', 'classic', 'mixed', 'simmered', 90, 0, 12.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_BARLEY', 'ING_BUNDNERFLEISCH', 'ING_BACON', 'ING_CARROT', 'ING_CELERY', 'ING_LEEK', 'ING_POTATO', 'ING_HEAVY_CREAM', 'ING_BAY_LEAF'], ARRAY['graubunden', 'hearty', 'winter', 'mountain'], 82),
('SUI_BASLER_MEHLSUPPE', 'basler-mehlsuppe', 'Basler Mehlsuppe', 'Basler Mehlsuppe', 'Traditional Basel flour soup served at Fasnacht carnival, made with toasted flour and onions', 'soups', 'basel', 'traditional', NULL, 'simmered', 45, 0, 9.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_ONION', 'ING_BEEF_BROTH', 'ING_GRUYERE', 'ING_BLACK_PEPPER'], ARRAY['basel', 'fasnacht', 'carnival', 'traditional'], 70),
('SUI_ZWIEBELSUPPE', 'swiss-onion-soup', 'Swiss Onion Soup', 'Zwiebelsuppe', 'Rich onion soup topped with crusty bread and melted cheese, Swiss Alpine version', 'soups', 'nationwide', 'traditional', NULL, 'simmered', 60, 0, 11.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_ONION', 'ING_BUTTER', 'ING_WHITE_WINE', 'ING_BEEF_BROTH', 'ING_BREAD', 'ING_GRUYERE', 'ING_THYME'], ARRAY['onion', 'cheese', 'comfort_food', 'winter'], 75);

-- DESSERTS (6 dishes)
INSERT INTO swiss (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('SUI_KIRSCHTORTE', 'zuger-kirschtorte', 'Zuger Kirschtorte', 'Zuger Kirschtorte', 'Legendary Zug cherry cake with kirsch-soaked sponge, buttercream, and pink marzipan topping', 'desserts', 'central', 'classic', NULL, 'baked', 90, 0, 8.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": false, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'eggs', 'dairy', 'nuts'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_SUGAR', 'ING_BUTTER', 'ING_KIRSCH', 'ING_ALMOND', 'ING_HAZELNUTS', 'ING_MARZIPAN'], ARRAY['iconic', 'zug', 'cherry', 'cake'], 88),
('SUI_NUSSTORTE', 'engadiner-nusstorte', 'Engadiner Nusstorte', 'Engadiner Nusstorte', 'Signature Engadine walnut tart with caramelized walnut filling in buttery shortcrust pastry', 'desserts', 'graubunden', 'classic', NULL, 'baked', 75, 0, 9.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": false, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'dairy', 'nuts'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_EGG', 'ING_SUGAR', 'ING_WALNUT', 'ING_HEAVY_CREAM', 'ING_HONEY'], ARRAY['iconic', 'engadine', 'walnut', 'tart'], 92),
('SUI_VERMICELLES', 'vermicelles', 'Vermicelles', 'Vermicelles', 'Chestnut purée dessert pressed through a sieve into spaghetti-like strands, topped with whipped cream and meringue', 'desserts', 'nationwide', 'classic', NULL, 'assembled', 45, 0, 7.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": false, "is_halal": true, "is_kosher": true}', ARRAY['dairy', 'nuts', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_CHESTNUTS', 'ING_SUGAR', 'ING_VANILLA', 'ING_KIRSCH', 'ING_HEAVY_CREAM', 'ING_MERINGUE'], ARRAY['iconic', 'autumn', 'chestnut', 'elegant'], 85),
('SUI_MERINGUE_CREAM', 'meringues-double-cream', 'Meringues with Double Cream', 'Meringues à la crème double de la Gruyère', 'Crispy meringues served with thick Gruyère double cream, a Fribourg specialty', 'desserts', 'vaud', 'traditional', NULL, 'baked', 120, 0, 8.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['eggs', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_EGG_WHITE', 'ING_SUGAR', 'ING_DOUBLE_CREAM', 'ING_VANILLA'], ARRAY['fribourg', 'meringue', 'cream', 'simple'], 80),
('SUI_RUEBLITORTE', 'aargauer-rueblitorte', 'Aargauer Rüeblitorte', 'Aargauer Rüeblitorte', 'Famous Swiss carrot cake from Aargau, moist and nutty with marzipan carrot decorations', 'desserts', 'zurich', 'classic', NULL, 'baked', 60, 0, 7.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": false, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'nuts'], ARRAY[]::TEXT[], ARRAY['ING_CARROT', 'ING_ALMOND', 'ING_EGG', 'ING_SUGAR', 'ING_FLOUR', 'ING_LEMON', 'ING_CINNAMON', 'ING_MARZIPAN'], ARRAY['iconic', 'aargau', 'carrot', 'cake'], 90),
('SUI_SCHOKOLADE', 'swiss-chocolate-truffle', 'Swiss Chocolate Truffles', 'Schweizer Schokoladentrüffel', 'Handcrafted chocolate truffles with rich ganache center, dusted with cocoa powder', 'desserts', 'nationwide', 'classic', NULL, 'assembled', 60, 0, 12.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['dairy'], ARRAY[]::TEXT[], ARRAY['ING_DARK_CHOCOLATE', 'ING_HEAVY_CREAM', 'ING_BUTTER', 'ING_COCOA_POWDER', 'ING_VANILLA'], ARRAY['iconic', 'chocolate', 'luxury', 'handmade'], 95);

-- PASTRIES (6 dishes)
INSERT INTO swiss (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('SUI_LACKERLI', 'basler-lackerli', 'Basler Läckerli', 'Basler Läckerli', 'Traditional Basel gingerbread cookies with honey, almonds, candied peel, and kirsch glaze', 'pastries', 'basel', 'classic', NULL, 'baked', 45, 0, 6.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": false, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'nuts'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_HONEY', 'ING_ALMOND', 'ING_CANDIED_ORANGE', 'ING_CANDIED_LEMON', 'ING_CINNAMON', 'ING_NUTMEG', 'ING_CLOVE', 'ING_KIRSCH'], ARRAY['basel', 'christmas', 'gingerbread', 'traditional'], 82),
('SUI_BIRNBROT', 'birnbrot', 'Birnbrot', 'Birnbrot', 'Swiss pear bread from Eastern Switzerland, filled with dried pears, nuts, and spices', 'pastries', 'zurich', 'traditional', NULL, 'baked', 120, 0, 8.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": false, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'nuts', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_DRIED_PEAR', 'ING_WALNUT', 'ING_FIGS', 'ING_RAISIN', 'ING_CINNAMON', 'ING_STAR_ANISE'], ARRAY['christmas', 'fruit', 'eastern_swiss', 'bread'], 70),
('SUI_GIPFELI', 'gipfeli', 'Gipfeli', 'Gipfeli', 'Swiss croissant, lighter and less buttery than French version, staple breakfast pastry', 'pastries', 'nationwide', 'classic', NULL, 'baked', 180, 0, 2.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_YEAST', 'ING_MILK', 'ING_EGG', 'ING_SUGAR', 'ING_SALT'], ARRAY['breakfast', 'pastry', 'daily'], 88),
('SUI_ZOPF', 'zopf', 'Zopf', 'Zopf', 'Traditional Swiss braided bread, enriched with butter and eggs, served on Sundays', 'pastries', 'nationwide', 'classic', NULL, 'baked', 120, 0, 5.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_EGG', 'ING_MILK', 'ING_YEAST', 'ING_SALT', 'ING_SUGAR'], ARRAY['sunday', 'bread', 'traditional', 'breakfast'], 90),
('SUI_MAILANDELI', 'mailunderli', 'Mailänderli', 'Mailänderli', 'Traditional Swiss butter cookies with lemon zest, shaped and baked golden, Christmas favorite', 'pastries', 'nationwide', 'traditional', NULL, 'baked', 45, 0, 5.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_SUGAR', 'ING_EGG', 'ING_LEMON', 'ING_VANILLA'], ARRAY['christmas', 'cookies', 'butter', 'lemon'], 78),
('SUI_BRUNSLI', 'brunsli', 'Brunsli', 'Brunsli', 'Swiss chocolate almond cookies from Basel, chewy and intensely chocolatey, Christmas specialty', 'pastries', 'basel', 'traditional', NULL, 'baked', 40, 0, 6.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": false, "is_halal": false, "is_kosher": false}', ARRAY['nuts', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_ALMOND', 'ING_SUGAR', 'ING_DARK_CHOCOLATE', 'ING_EGG_WHITE', 'ING_CINNAMON', 'ING_CLOVE', 'ING_KIRSCH'], ARRAY['basel', 'christmas', 'chocolate', 'almond'], 75);

-- BREAKFAST (3 dishes)
INSERT INTO swiss (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('SUI_BIRCHERMUESLI', 'birchermuesli', 'Birchermüesli', 'Birchermüesli', 'Original Swiss muesli invented by Dr. Bircher-Benner, oats soaked overnight with apple, lemon, nuts and cream', 'breakfast', 'zurich', 'classic', NULL, 'raw', 15, 0, 8.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": false, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'dairy', 'nuts'], ARRAY[]::TEXT[], ARRAY['ING_ROLLED_OAT', 'ING_APPLE', 'ING_LEMON', 'ING_HAZELNUTS', 'ING_HEAVY_CREAM', 'ING_HONEY', 'ING_YOGURT'], ARRAY['iconic', 'healthy', 'original', 'zurich'], 95),
('SUI_ROSTI_EGG', 'rosti-with-egg', 'Rösti with Fried Egg', 'Rösti mit Spiegelei', 'Classic breakfast rösti topped with a perfectly fried egg, popular farmer breakfast', 'breakfast', 'bern', 'classic', 'egg', 'pan_fried', 25, 0, 12.99, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['eggs', 'dairy'], ARRAY[]::TEXT[], ARRAY['ING_POTATO', 'ING_BUTTER', 'ING_EGG', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY['breakfast', 'hearty', 'farm_style'], 85),
('SUI_ROSTI_BACON', 'rosti-with-bacon', 'Rösti with Bacon', 'Speckrösti', 'Rösti cooked with crispy bacon pieces mixed throughout, hearty Swiss breakfast', 'breakfast', 'bern', 'popular', 'pork', 'pan_fried', 30, 0, 14.99, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy'], ARRAY[]::TEXT[], ARRAY['ING_POTATO', 'ING_BACON', 'ING_BUTTER', 'ING_ONION', 'ING_SALT'], ARRAY['breakfast', 'bacon', 'hearty'], 82);

-- Verification
SELECT category, COUNT(*) as count FROM swiss GROUP BY category ORDER BY category;
SELECT 'Total Swiss dishes: ' || COUNT(*) as total FROM swiss;
