-- Turkish Cuisine Data Import
-- 86 dishes across 10 categories
-- Database Standards v1.1 compliant
-- Created: 2025-12-19

-- Clear existing data
DELETE FROM turkish WHERE id LIKE 'TRK_%';

-- KEBABS (10 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_DONER_KEBAB', 'doner-kebab', 'Döner Kebab', 'Iconic Turkish rotating spit-roasted meat, thinly sliced and served with flatbread, rice or in a wrap with vegetables and sauces', 'Döner Kebab', 'kebabs', 'signature', 'national', 'mixed_meat', 'spit_roasted', true, false, false, true, '["gluten"]'::jsonb, false, true, true, false, false, true, 650, 35, 45, 38, 1, '["kebab", "street-food", "iconic", "rotating-spit"]'::jsonb, 98),
('TRK_ISKENDER_KEBAB', 'iskender-kebab', 'Iskender Kebab', 'Bursa specialty with thin döner slices over pide bread, topped with tomato sauce, melted butter and served with yogurt', 'İskender Kebabı', 'kebabs', 'signature', 'marmara', 'lamb', 'spit_roasted', false, false, false, true, '["gluten", "dairy"]'::jsonb, false, false, true, false, false, true, 780, 42, 38, 52, 1, '["iskender", "bursa", "butter", "yogurt", "premium"]'::jsonb, 95),
('TRK_ADANA_KEBAB', 'adana-kebab', 'Adana Kebab', 'Spicy minced lamb kebab from Adana, hand-mixed with tail fat and red pepper flakes, grilled on wide flat skewers', 'Adana Kebabı', 'kebabs', 'signature', 'southeastern', 'lamb', 'grilled', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 520, 38, 5, 42, 3, '["adana", "spicy", "minced", "lamb", "southeastern"]'::jsonb, 92),
('TRK_URFA_KEBAB', 'urfa-kebab', 'Urfa Kebab', 'Mild version of Adana kebab from Şanlıurfa, seasoned with smoky isot pepper instead of hot chili', 'Urfa Kebabı', 'kebabs', 'traditional', 'southeastern', 'lamb', 'grilled', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 510, 36, 5, 40, 1, '["urfa", "mild", "isot-pepper", "smoky"]'::jsonb, 85),
('TRK_SHISH_KEBAB', 'shish-kebab', 'Şiş Kebab', 'Classic cubed lamb or beef threaded on skewers with vegetables, marinated and grilled over charcoal', 'Şiş Kebab', 'kebabs', 'classic', 'national', 'lamb', 'grilled', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 480, 40, 8, 32, 1, '["shish", "skewered", "classic", "charcoal-grilled"]'::jsonb, 90),
('TRK_TAVUK_SIS', 'tavuk-sis', 'Tavuk Şiş', 'Marinated chicken breast cubes grilled on skewers, tender and juicy with Turkish spices', 'Tavuk Şiş', 'kebabs', 'popular', 'national', 'chicken', 'grilled', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 380, 42, 5, 18, 1, '["chicken", "skewered", "healthy", "lean"]'::jsonb, 88),
('TRK_BEYTI_KEBAB', 'beyti-kebab', 'Beyti Kebab', 'Spiced minced meat wrapped in lavash bread, sliced and served with tomato sauce and yogurt', 'Beyti Kebabı', 'kebabs', 'signature', 'istanbul', 'mixed_meat', 'grilled', false, false, false, true, '["gluten", "dairy"]'::jsonb, false, false, true, false, false, true, 620, 38, 32, 42, 2, '["beyti", "wrapped", "istanbul", "lavash"]'::jsonb, 82),
('TRK_KOFTE_KEBAB', 'kofte-kebab', 'Köfte Kebab', 'Grilled Turkish meatballs made with minced lamb and beef, onions and spices, served with bread and salad', 'Köfte', 'kebabs', 'classic', 'national', 'mixed_meat', 'grilled', true, false, false, true, '["gluten"]'::jsonb, false, true, true, false, false, true, 450, 32, 12, 32, 1, '["kofte", "meatballs", "classic", "comfort-food"]'::jsonb, 90),
('TRK_PATLICAN_KEBAB', 'patlican-kebab', 'Patlıcan Kebab', 'Grilled eggplant and meat kebab layered on skewers, smoky and rich from charred vegetables', 'Patlıcan Kebabı', 'kebabs', 'traditional', 'southeastern', 'lamb', 'grilled', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 420, 28, 15, 30, 1, '["eggplant", "vegetables", "smoky", "southeastern"]'::jsonb, 78),
('TRK_CIGER_KEBAB', 'ciger-kebab', 'Ciğer Kebab', 'Grilled lamb liver kebab, an Edirne specialty served with onions, parsley and lavash bread', 'Ciğer Kebabı', 'kebabs', 'regional', 'marmara', 'lamb', 'grilled', true, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 320, 28, 8, 18, 2, '["liver", "offal", "edirne", "traditional"]'::jsonb, 65);

-- PIDE & LAHMACUN (8 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_LAHMACUN', 'lahmacun', 'Lahmacun', 'Thin crispy flatbread topped with spiced minced meat, tomatoes, peppers and herbs, rolled with fresh vegetables and lemon', 'Lahmacun', 'pide_lahmacun', 'signature', 'southeastern', 'lamb', 'baked', true, false, false, true, '["gluten"]'::jsonb, false, true, true, false, false, true, 280, 14, 32, 12, 2, '["lahmacun", "flatbread", "street-food", "thin-crust"]'::jsonb, 95),
('TRK_PIDE_KIYMALI', 'kiymali-pide', 'Kıymalı Pide', 'Boat-shaped Turkish pizza with spiced ground meat filling, baked in wood-fired oven until golden', 'Kıymalı Pide', 'pide_lahmacun', 'signature', 'black_sea', 'mixed_meat', 'baked', false, false, false, true, '["gluten"]'::jsonb, false, true, true, false, false, true, 520, 26, 48, 26, 1, '["pide", "meat", "boat-shaped", "wood-fired"]'::jsonb, 92),
('TRK_PIDE_KASARLI', 'kasarli-pide', 'Kaşarlı Pide', 'Turkish pide filled with melted kaşar cheese, stretchy and golden from the wood-fired oven', 'Kaşarlı Pide', 'pide_lahmacun', 'popular', 'black_sea', 'vegetarian', 'baked', false, false, false, true, '["gluten", "dairy"]'::jsonb, false, false, true, false, true, true, 480, 22, 45, 24, 0, '["pide", "cheese", "vegetarian", "kasar"]'::jsonb, 88),
('TRK_PIDE_SUCUKLU', 'sucuklu-pide', 'Sucuklu Pide', 'Pide topped with Turkish sucuk sausage and egg, the perfect combination of spicy and savory', 'Sucuklu Yumurtalı Pide', 'pide_lahmacun', 'popular', 'national', 'beef', 'baked', false, false, true, true, '["gluten", "eggs"]'::jsonb, false, true, true, false, false, true, 580, 28, 42, 34, 2, '["pide", "sucuk", "egg", "breakfast", "spicy"]'::jsonb, 90),
('TRK_PIDE_KUSBASI', 'kusbasi-pide', 'Kuşbaşılı Pide', 'Pide filled with small cubed meat pieces, peppers and tomatoes, hearty and satisfying', 'Kuşbaşılı Pide', 'pide_lahmacun', 'traditional', 'black_sea', 'lamb', 'baked', false, false, false, true, '["gluten"]'::jsonb, false, true, true, false, false, true, 560, 32, 45, 28, 1, '["pide", "cubed-meat", "hearty", "black-sea"]'::jsonb, 82),
('TRK_PIDE_ISPANAKLI', 'ispanakli-pide', 'Ispanaklı Pide', 'Vegetarian pide with spinach and cheese filling, light and nutritious', 'Ispanaklı Pide', 'pide_lahmacun', 'active', 'national', 'vegetarian', 'baked', false, false, false, true, '["gluten", "dairy"]'::jsonb, false, false, true, false, true, true, 420, 18, 42, 20, 0, '["pide", "spinach", "vegetarian", "healthy"]'::jsonb, 75),
('TRK_BAFRA_PIDE', 'bafra-pide', 'Bafra Pidesi', 'Closed pide from Bafra with ground meat filling, shaped like a closed pocket', 'Bafra Pidesi', 'pide_lahmacun', 'regional', 'black_sea', 'mixed_meat', 'baked', false, false, false, true, '["gluten"]'::jsonb, false, true, true, false, false, true, 540, 28, 50, 26, 1, '["pide", "bafra", "closed", "black-sea", "regional"]'::jsonb, 70),
('TRK_ETLI_EKMEK', 'etli-ekmek', 'Etli Ekmek', 'Konya specialty - extra long thin flatbread with spiced minced meat topping, crispy and flavorful', 'Etli Ekmek', 'pide_lahmacun', 'regional', 'central_anatolia', 'lamb', 'baked', false, false, false, true, '["gluten"]'::jsonb, false, true, true, false, false, true, 380, 20, 38, 18, 2, '["etli-ekmek", "konya", "long", "crispy", "central-anatolia"]'::jsonb, 78);

-- MEZES (12 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_HUMMUS', 'hummus-turkish', 'Humus', 'Creamy chickpea dip with tahini, lemon and garlic, drizzled with olive oil and served with warm bread', 'Humus', 'mezes', 'classic', 'southeastern', 'vegan', 'raw', false, true, true, false, '["sesame"]'::jsonb, true, true, true, true, true, true, 180, 8, 18, 10, 0, '["hummus", "chickpea", "dip", "vegan", "healthy"]'::jsonb, 92),
('TRK_BABAGANOUSH', 'babaganoush', 'Babaganuş', 'Smoky roasted eggplant dip with tahini, garlic and lemon, silky smooth texture', 'Babaganuş', 'mezes', 'classic', 'southeastern', 'vegan', 'roasted', false, true, false, false, '["sesame"]'::jsonb, true, true, true, true, true, true, 120, 4, 12, 8, 0, '["eggplant", "smoky", "dip", "vegan"]'::jsonb, 85),
('TRK_CACIK', 'cacik', 'Cacık', 'Refreshing yogurt dip with cucumber, garlic, dill and mint, perfect accompaniment to grilled meats', 'Cacık', 'mezes', 'signature', 'national', 'vegetarian', 'raw', false, true, true, false, '["dairy"]'::jsonb, true, false, true, false, true, true, 80, 5, 6, 4, 0, '["yogurt", "cucumber", "refreshing", "cooling"]'::jsonb, 95),
('TRK_HAYDARI', 'haydari', 'Haydari', 'Thick strained yogurt dip with garlic, dill and walnuts, rich and creamy', 'Haydari', 'mezes', 'popular', 'national', 'vegetarian', 'raw', false, true, false, false, '["dairy", "tree_nuts"]'::jsonb, true, false, false, false, true, true, 140, 8, 5, 10, 0, '["yogurt", "garlic", "walnut", "creamy"]'::jsonb, 80),
('TRK_EZME', 'ezme-salata', 'Ezme', 'Spicy tomato and pepper paste salad finely chopped with onion, parsley and pomegranate molasses', 'Ezme', 'mezes', 'signature', 'southeastern', 'vegan', 'raw', false, true, false, false, '[]'::jsonb, true, true, true, true, true, true, 65, 2, 10, 3, 3, '["spicy", "tomato", "pepper", "fresh", "southeastern"]'::jsonb, 88),
('TRK_KISIR', 'kisir', 'Kısır', 'Turkish bulgur salad with tomato paste, fresh vegetables and herbs, tangy with pomegranate molasses', 'Kısır', 'mezes', 'classic', 'southeastern', 'vegan', 'raw', false, true, false, false, '["gluten"]'::jsonb, false, true, true, true, true, true, 160, 5, 28, 5, 1, '["bulgur", "salad", "healthy", "fresh"]'::jsonb, 82),
('TRK_PATLICAN_SALATA', 'patlican-salatasi', 'Patlıcan Salatası', 'Smoky roasted eggplant salad with peppers, tomatoes and garlic, charred and flavorful', 'Patlıcan Salatası', 'mezes', 'classic', 'aegean', 'vegan', 'roasted', false, true, false, false, '[]'::jsonb, true, true, true, true, true, true, 90, 2, 12, 5, 0, '["eggplant", "roasted", "smoky", "salad"]'::jsonb, 78),
('TRK_ATOM', 'atom-meze', 'Atom', 'Very spicy pepper and walnut paste, fiery hot spread from southeastern Turkey', 'Atom', 'mezes', 'regional', 'southeastern', 'vegan', 'raw', false, true, false, false, '["tree_nuts"]'::jsonb, true, true, false, true, true, true, 120, 4, 8, 9, 5, '["spicy", "hot", "walnut", "pepper", "extreme"]'::jsonb, 60),
('TRK_ACILI_EZME', 'acili-ezme', 'Acılı Ezme', 'Hot and spicy version of ezme with extra chili peppers and isot pepper', 'Acılı Ezme', 'mezes', 'popular', 'southeastern', 'vegan', 'raw', false, true, false, false, '[]'::jsonb, true, true, true, true, true, true, 70, 2, 10, 3, 4, '["spicy", "hot", "ezme", "southeastern"]'::jsonb, 75),
('TRK_MUHAMMARA', 'muhammara', 'Muhammara', 'Roasted red pepper and walnut dip with pomegranate molasses, sweet and tangy', 'Muhammara', 'mezes', 'classic', 'southeastern', 'vegan', 'roasted', false, true, false, false, '["tree_nuts"]'::jsonb, true, true, false, true, true, true, 150, 4, 12, 11, 1, '["pepper", "walnut", "pomegranate", "dip"]'::jsonb, 80),
('TRK_SIGARA_BOREGI', 'sigara-boregi', 'Sigara Böreği', 'Crispy fried cigar-shaped pastries filled with feta cheese and parsley', 'Sigara Böreği', 'mezes', 'signature', 'national', 'vegetarian', 'fried', true, true, true, true, '["gluten", "dairy"]'::jsonb, false, false, true, false, true, true, 180, 8, 14, 12, 0, '["borek", "fried", "cheese", "crispy", "appetizer"]'::jsonb, 92),
('TRK_MIDYE_DOLMA', 'midye-dolma', 'Midye Dolma', 'Stuffed mussels with aromatic rice, pine nuts, currants and spices, served cold with lemon', 'Midye Dolma', 'mezes', 'signature', 'istanbul', 'seafood', 'steamed', true, true, false, false, '["shellfish", "tree_nuts"]'::jsonb, true, true, false, false, false, true, 120, 8, 14, 4, 0, '["mussels", "stuffed", "street-food", "istanbul", "seafood"]'::jsonb, 88);

-- BÖREK (8 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_SU_BOREGI', 'su-boregi', 'Su Böreği', 'Layered boiled dough sheets with feta cheese filling, soft and moist texture unlike fried boreks', 'Su Böreği', 'borek', 'signature', 'national', 'vegetarian', 'baked', false, false, true, true, '["gluten", "dairy", "eggs"]'::jsonb, false, false, true, false, true, true, 320, 14, 28, 18, 0, '["borek", "layered", "cheese", "breakfast", "soft"]'::jsonb, 95),
('TRK_KIYMALI_BOREK', 'kiymali-borek', 'Kıymalı Börek', 'Flaky phyllo pastry filled with spiced ground meat and onions, baked until golden', 'Kıymalı Börek', 'borek', 'classic', 'national', 'mixed_meat', 'baked', false, false, false, true, '["gluten", "eggs"]'::jsonb, false, true, true, false, false, true, 380, 18, 26, 24, 1, '["borek", "meat", "phyllo", "savory"]'::jsonb, 88),
('TRK_ISPANAKLI_BOREK', 'ispanakli-borek', 'Ispanaklı Börek', 'Spinach and feta cheese filled phyllo börek, healthy and flavorful vegetarian option', 'Ispanaklı Börek', 'borek', 'popular', 'national', 'vegetarian', 'baked', false, false, true, true, '["gluten", "dairy", "eggs"]'::jsonb, false, false, true, false, true, true, 280, 12, 24, 16, 0, '["borek", "spinach", "cheese", "vegetarian", "healthy"]'::jsonb, 85),
('TRK_PATATESLI_BOREK', 'patatesli-borek', 'Patatesli Börek', 'Potato-filled börek with herbs, comforting and satisfying vegetarian pastry', 'Patatesli Börek', 'borek', 'active', 'national', 'vegetarian', 'baked', false, false, true, true, '["gluten", "eggs"]'::jsonb, false, true, true, false, true, true, 300, 8, 35, 15, 0, '["borek", "potato", "vegetarian", "comfort-food"]'::jsonb, 75),
('TRK_TALAS_BOREGI', 'talas-boregi', 'Talaş Böreği', 'Individual puff pastry packets filled with cubed meat, a specialty from Kayseri', 'Talaş Böreği', 'borek', 'regional', 'central_anatolia', 'lamb', 'baked', false, false, false, true, '["gluten", "eggs"]'::jsonb, false, true, true, false, false, true, 420, 22, 28, 26, 1, '["borek", "puff-pastry", "meat", "kayseri"]'::jsonb, 72),
('TRK_GOZLEME', 'gozleme', 'Gözleme', 'Thin hand-rolled flatbread filled with cheese, spinach or meat, cooked on a convex griddle', 'Gözleme', 'borek', 'signature', 'national', 'vegetarian', 'baked', true, false, true, true, '["gluten", "dairy"]'::jsonb, false, false, true, false, true, true, 350, 14, 38, 16, 0, '["gozleme", "flatbread", "street-food", "rustic"]'::jsonb, 92),
('TRK_GOZLEME_KIYMALI', 'kiymali-gozleme', 'Kıymalı Gözleme', 'Gözleme filled with spiced ground meat and onions, hearty and satisfying', 'Kıymalı Gözleme', 'borek', 'popular', 'national', 'mixed_meat', 'baked', true, false, false, true, '["gluten"]'::jsonb, false, true, true, false, false, true, 420, 20, 36, 22, 1, '["gozleme", "meat", "street-food", "filling"]'::jsonb, 88),
('TRK_SARAY_BOREGI', 'saray-boregi', 'Saray Böreği', 'Palace-style layered börek with ground meat, fit for sultans with its elaborate preparation', 'Saray Böreği', 'borek', 'traditional', 'istanbul', 'mixed_meat', 'baked', false, false, false, true, '["gluten", "dairy", "eggs"]'::jsonb, false, false, true, false, false, true, 450, 22, 32, 28, 1, '["borek", "palace", "ottoman", "elaborate", "istanbul"]'::jsonb, 70);

-- SOUPS (10 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_MERCIMEK_CORBASI', 'mercimek-corbasi', 'Mercimek Corbasi', 'Classic Turkish red lentil soup, velvety smooth and flavored with cumin, served with lemon wedges and crusty bread', 'Mercimek Corbasi', 'soups', 'signature', 'national', 'vegan', 'stewed', false, false, false, true, '[]'::jsonb, true, true, true, true, true, true, 180, 12, 28, 4, 1, '["lentil", "soup", "vegan", "comfort-food", "healthy"]'::jsonb, 98),
('TRK_EZOGELIN_CORBASI', 'ezogelin-corbasi', 'Ezogelin Corbasi', 'Bride soup with red lentils, bulgur and rice, spiced with dried mint and red pepper flakes', 'Ezogelin Corbasi', 'soups', 'classic', 'southeastern', 'vegan', 'stewed', false, false, false, true, '["gluten"]'::jsonb, false, true, true, true, true, true, 160, 8, 26, 3, 2, '["lentil", "bulgur", "spicy", "traditional"]'::jsonb, 88),
('TRK_ISKEMBE_CORBASI', 'iskembe-corbasi', 'Iskembe Corbasi', 'Traditional tripe soup served with garlic vinegar sauce, a late-night favorite believed to cure hangovers', 'Iskembe Corbasi', 'soups', 'traditional', 'national', 'beef', 'stewed', true, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 220, 18, 8, 14, 2, '["tripe", "offal", "late-night", "traditional"]'::jsonb, 70),
('TRK_YAYLA_CORBASI', 'yayla-corbasi', 'Yayla Corbasi', 'Creamy yogurt soup with rice and dried mint, light and refreshing, perfect for summer', 'Yayla Corbasi', 'soups', 'classic', 'central_anatolia', 'vegetarian', 'stewed', false, false, false, true, '["dairy"]'::jsonb, true, false, true, false, true, true, 140, 6, 18, 5, 0, '["yogurt", "rice", "mint", "light", "summer"]'::jsonb, 82),
('TRK_TARHANA_CORBASI', 'tarhana-corbasi', 'Tarhana Corbasi', 'Fermented grain and yogurt soup with distinctive tangy flavor, ancient Turkish comfort food', 'Tarhana Corbasi', 'soups', 'traditional', 'national', 'vegetarian', 'stewed', false, false, true, true, '["gluten", "dairy"]'::jsonb, false, false, true, false, true, true, 150, 6, 22, 4, 1, '["fermented", "tangy", "ancient", "breakfast"]'::jsonb, 78),
('TRK_TAVUK_SUYU', 'tavuk-suyu-corbasi', 'Tavuk Suyu Corbasi', 'Clear Turkish chicken soup with vermicelli noodles, light and healing comfort food', 'Tavuk Suyu Corbasi', 'soups', 'popular', 'national', 'chicken', 'stewed', false, false, false, true, '["gluten"]'::jsonb, false, true, true, false, false, true, 120, 10, 12, 4, 0, '["chicken", "noodle", "light", "healing"]'::jsonb, 85),
('TRK_DOMATES_CORBASI', 'domates-corbasi', 'Domates Corbasi', 'Velvety Turkish tomato soup with rice, garnished with croutons and fresh herbs', 'Domates Corbasi', 'soups', 'popular', 'national', 'vegetarian', 'stewed', false, false, false, true, '["gluten", "dairy"]'::jsonb, false, false, true, false, true, true, 130, 4, 18, 5, 0, '["tomato", "comfort-food", "classic"]'::jsonb, 80),
('TRK_SEHRIYE_CORBASI', 'sehriye-corbasi', 'Sehriye Corbasi', 'Light vermicelli noodle soup in chicken or vegetable broth, simple and satisfying', 'Sehriye Corbasi', 'soups', 'active', 'national', 'vegetarian', 'stewed', false, false, false, true, '["gluten"]'::jsonb, false, true, true, true, true, true, 100, 4, 18, 2, 0, '["noodle", "light", "simple"]'::jsonb, 72),
('TRK_KELLE_PACA', 'kelle-paca-corbasi', 'Kelle Paca Corbasi', 'Rich sheep head and trotter soup, collagen-rich traditional delicacy served with garlic', 'Kelle Paca Corbasi', 'soups', 'traditional', 'central_anatolia', 'lamb', 'stewed', true, false, true, true, '[]'::jsonb, true, true, true, false, false, true, 280, 22, 5, 20, 1, '["offal", "traditional", "collagen", "hearty"]'::jsonb, 55),
('TRK_BEYRAN', 'beyran-corbasi', 'Beyran Corbasi', 'Spicy lamb soup from Gaziantep with rice and garlic, fiery red and deeply flavorful', 'Beyran Corbasi', 'soups', 'regional', 'southeastern', 'lamb', 'stewed', true, false, true, true, '[]'::jsonb, true, true, true, false, false, true, 320, 24, 18, 18, 4, '["spicy", "lamb", "gaziantep", "hearty", "breakfast"]'::jsonb, 75);

-- RICE & PILAV (8 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_PILAV', 'tereyagli-pilav', 'Tereyagli Pilav', 'Classic Turkish buttered rice pilaf, fluffy and fragrant, the essential side dish for kebabs', 'Tereyagli Pilav', 'rice_pilav', 'signature', 'national', 'vegetarian', 'steamed', false, false, false, true, '["dairy"]'::jsonb, true, false, true, false, true, true, 220, 4, 38, 7, 0, '["rice", "pilaf", "side-dish", "classic"]'::jsonb, 95),
('TRK_IC_PILAV', 'ic-pilav', 'Ic Pilav', 'Festive rice with liver, pine nuts and currants, aromatic with cinnamon and allspice', 'Ic Pilav', 'rice_pilav', 'traditional', 'istanbul', 'lamb', 'steamed', false, false, false, true, '["tree_nuts"]'::jsonb, true, true, false, false, false, true, 320, 12, 42, 12, 0, '["festive", "liver", "pine-nuts", "ottoman"]'::jsonb, 78),
('TRK_NOHUTLU_PILAV', 'nohutlu-pilav', 'Nohutlu Pilav', 'Rice pilaf with tender chickpeas, a hearty and nutritious staple dish', 'Nohutlu Pilav', 'rice_pilav', 'popular', 'national', 'vegan', 'steamed', true, false, false, true, '[]'::jsonb, true, true, true, true, true, true, 280, 10, 48, 5, 0, '["chickpea", "street-food", "hearty", "vegan"]'::jsonb, 88),
('TRK_TAVUKLU_PILAV', 'tavuklu-pilav', 'Tavuklu Pilav', 'Chicken rice pilaf with tender chicken pieces, a complete and satisfying meal', 'Tavuklu Pilav', 'rice_pilav', 'popular', 'national', 'chicken', 'steamed', true, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 380, 28, 42, 12, 0, '["chicken", "complete-meal", "street-food"]'::jsonb, 90),
('TRK_BULGUR_PILAVI', 'bulgur-pilavi', 'Bulgur Pilavi', 'Nutty bulgur wheat pilaf with tomato paste and peppers, healthier alternative to rice', 'Bulgur Pilavi', 'rice_pilav', 'classic', 'southeastern', 'vegan', 'steamed', false, false, false, true, '["gluten"]'::jsonb, false, true, true, true, true, true, 200, 7, 38, 3, 1, '["bulgur", "healthy", "fiber", "southeastern"]'::jsonb, 82),
('TRK_DOMATESLI_PILAV', 'domatesli-pilav', 'Domatesli Pilav', 'Tomato-flavored rice pilaf, vibrant red color with sweet tomato taste', 'Domatesli Pilav', 'rice_pilav', 'active', 'national', 'vegetarian', 'steamed', false, false, false, true, '["dairy"]'::jsonb, true, false, true, false, true, true, 230, 5, 40, 6, 0, '["tomato", "colorful", "side-dish"]'::jsonb, 75),
('TRK_SEHRIYELI_PILAV', 'sehriyeli-pilav', 'Sehriyeli Pilav', 'Rice pilaf with toasted vermicelli noodles, nutty flavor from browned pasta', 'Sehriyeli Pilav', 'rice_pilav', 'classic', 'national', 'vegetarian', 'steamed', false, false, false, true, '["gluten", "dairy"]'::jsonb, false, false, true, false, true, true, 250, 6, 44, 7, 0, '["vermicelli", "toasted", "classic", "side-dish"]'::jsonb, 85),
('TRK_FIRIKLI_PILAV', 'firikli-pilav', 'Firikli Pilav', 'Pilaf made with freekeh (green wheat), smoky and nutritious ancient grain dish', 'Firikli Pilav', 'rice_pilav', 'regional', 'southeastern', 'vegan', 'steamed', false, false, false, true, '["gluten"]'::jsonb, false, true, true, true, true, true, 190, 8, 35, 2, 0, '["freekeh", "ancient-grain", "smoky", "healthy"]'::jsonb, 60);

-- DOLMA & SARMA (10 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_YAPRAK_SARMA', 'yaprak-sarma', 'Yaprak Sarma', 'Grape leaves stuffed with aromatic rice, pine nuts and currants, served cold with olive oil and lemon', 'Yaprak Sarma', 'dolma_sarma', 'signature', 'aegean', 'vegan', 'steamed', false, true, false, false, '["tree_nuts"]'::jsonb, true, true, false, true, true, true, 150, 4, 22, 6, 0, '["grape-leaves", "stuffed", "cold", "olive-oil", "meze"]'::jsonb, 92),
('TRK_ETLI_YAPRAK_SARMA', 'etli-yaprak-sarma', 'Etli Yaprak Sarma', 'Grape leaves stuffed with minced meat and rice, served hot with yogurt sauce', 'Etli Yaprak Sarma', 'dolma_sarma', 'classic', 'national', 'mixed_meat', 'steamed', false, false, false, true, '["dairy"]'::jsonb, true, false, true, false, false, true, 220, 14, 18, 12, 1, '["grape-leaves", "meat", "hot", "yogurt"]'::jsonb, 85),
('TRK_BIBER_DOLMA', 'biber-dolmasi', 'Biber Dolmasi', 'Bell peppers stuffed with spiced rice and herbs, can be made with or without meat', 'Biber Dolmasi', 'dolma_sarma', 'classic', 'national', 'vegan', 'baked', false, true, false, false, '[]'::jsonb, true, true, true, true, true, true, 140, 4, 24, 5, 0, '["pepper", "stuffed", "vegetarian", "colorful"]'::jsonb, 88),
('TRK_DOMATES_DOLMA', 'domates-dolmasi', 'Domates Dolmasi', 'Tomatoes stuffed with aromatic rice filling, juicy and sweet from roasting', 'Domates Dolmasi', 'dolma_sarma', 'classic', 'aegean', 'vegan', 'baked', false, true, false, false, '[]'::jsonb, true, true, true, true, true, true, 130, 3, 22, 4, 0, '["tomato", "stuffed", "summer", "light"]'::jsonb, 82),
('TRK_KABAK_DOLMA', 'kabak-dolmasi', 'Kabak Dolmasi', 'Zucchini stuffed with rice and meat, served with garlicky yogurt sauce', 'Kabak Dolmasi', 'dolma_sarma', 'popular', 'national', 'mixed_meat', 'steamed', false, false, false, true, '["dairy"]'::jsonb, true, false, true, false, false, true, 200, 12, 18, 10, 0, '["zucchini", "meat", "yogurt", "home-cooking"]'::jsonb, 78),
('TRK_PATLICAN_DOLMA', 'patlican-dolmasi', 'Patlican Dolmasi', 'Small eggplants stuffed with spiced meat and rice, rich and satisfying', 'Patlican Dolmasi', 'dolma_sarma', 'traditional', 'southeastern', 'mixed_meat', 'baked', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 240, 14, 20, 14, 1, '["eggplant", "meat", "stuffed", "hearty"]'::jsonb, 80),
('TRK_LAHANA_SARMASI', 'lahana-sarmasi', 'Lahana Sarmasi', 'Cabbage rolls stuffed with meat and rice, winter comfort food served with yogurt', 'Lahana Sarmasi', 'dolma_sarma', 'traditional', 'black_sea', 'mixed_meat', 'steamed', false, false, false, true, '["dairy"]'::jsonb, true, false, true, false, false, true, 230, 15, 20, 12, 0, '["cabbage", "winter", "comfort-food", "black-sea"]'::jsonb, 75),
('TRK_KURU_DOLMA', 'kuru-dolma', 'Kuru Dolma', 'Dried vegetables (peppers, eggplant) rehydrated and stuffed with meat and rice', 'Kuru Dolma', 'dolma_sarma', 'regional', 'southeastern', 'mixed_meat', 'stewed', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 260, 16, 22, 14, 1, '["dried", "preserved", "winter", "traditional"]'::jsonb, 65),
('TRK_ENGINAR_DOLMA', 'enginar-dolmasi', 'Enginar Dolmasi', 'Artichokes stuffed with aromatic rice, dill and lemon, elegant Aegean dish', 'Enginar Dolmasi', 'dolma_sarma', 'regional', 'aegean', 'vegan', 'steamed', false, true, false, false, '[]'::jsonb, true, true, true, true, true, true, 160, 5, 26, 5, 0, '["artichoke", "elegant", "aegean", "spring"]'::jsonb, 70),
('TRK_ZEYTINYAGLI_SARMA', 'zeytinyagli-sarma', 'Zeytinyagli Sarma', 'Olive oil-based vegetarian grape leaf rolls, a cornerstone of Turkish meze culture', 'Zeytinyagli Sarma', 'dolma_sarma', 'signature', 'aegean', 'vegan', 'steamed', false, true, false, false, '["tree_nuts"]'::jsonb, true, true, false, true, true, true, 140, 3, 20, 7, 0, '["olive-oil", "cold", "meze", "classic", "aegean"]'::jsonb, 90);

-- STEWS (10 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_KARNIYARIK', 'karniyarik', 'Karniyarik', 'Split belly eggplants stuffed with minced meat, onions and tomatoes, baked until tender', 'Karniyarik', 'stews', 'signature', 'national', 'mixed_meat', 'baked', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 380, 22, 18, 26, 1, '["eggplant", "stuffed", "home-cooking", "comfort-food"]'::jsonb, 92),
('TRK_IMAM_BAYILDI', 'imam-bayildi', 'Imam Bayildi', 'The Imam fainted - eggplants braised in olive oil with tomatoes and onions, legendary vegetarian dish', 'Imam Bayildi', 'stews', 'signature', 'aegean', 'vegan', 'braised', false, true, false, false, '[]'::jsonb, true, true, true, true, true, true, 220, 4, 22, 15, 0, '["eggplant", "olive-oil", "cold", "legendary", "aegean"]'::jsonb, 88),
('TRK_HUNKAR_BEGENDI', 'hunkar-begendi', 'Hunkar Begendi', 'The Sultan liked it - lamb stew served over smoky eggplant puree with bechamel, Ottoman palace cuisine', 'Hunkar Begendi', 'stews', 'signature', 'istanbul', 'lamb', 'stewed', false, false, false, true, '["dairy"]'::jsonb, true, false, true, false, false, true, 520, 32, 18, 38, 1, '["ottoman", "palace", "lamb", "eggplant", "elegant"]'::jsonb, 85),
('TRK_TAS_KEBABI', 'tas-kebabi', 'Tas Kebabi', 'Pot kebab - tender lamb cubes braised with potatoes and vegetables in rich tomato sauce', 'Tas Kebabi', 'stews', 'classic', 'national', 'lamb', 'stewed', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 450, 35, 25, 28, 1, '["lamb", "stew", "potato", "hearty"]'::jsonb, 82),
('TRK_GUVEC', 'guvec', 'Guvec', 'Traditional clay pot casserole with meat and seasonal vegetables, slow-cooked for hours', 'Guvec', 'stews', 'traditional', 'central_anatolia', 'mixed_meat', 'stewed', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 420, 28, 30, 24, 1, '["clay-pot", "slow-cooked", "vegetables", "traditional"]'::jsonb, 78),
('TRK_ETLI_NOHUT', 'etli-nohut', 'Etli Nohut', 'Lamb and chickpea stew, hearty and nutritious home-style dish', 'Etli Nohut', 'stews', 'classic', 'national', 'lamb', 'stewed', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 380, 30, 28, 18, 0, '["chickpea", "lamb", "home-cooking", "nutritious"]'::jsonb, 80),
('TRK_FASULYE', 'kuru-fasulye', 'Kuru Fasulye', 'White bean stew with tomato sauce and pastirma, Turkey national comfort food served with rice', 'Kuru Fasulye', 'stews', 'signature', 'national', 'beef', 'stewed', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 320, 18, 38, 12, 1, '["beans", "comfort-food", "national", "hearty"]'::jsonb, 90),
('TRK_TURLU', 'turlu-guvec', 'Turlu', 'Mixed vegetable stew with zucchini, eggplant, peppers and tomatoes, light and healthy', 'Turlu', 'stews', 'classic', 'aegean', 'vegan', 'stewed', false, false, false, true, '[]'::jsonb, true, true, true, true, true, true, 180, 5, 28, 8, 0, '["vegetables", "light", "summer", "healthy"]'::jsonb, 75),
('TRK_SARAY_SARMASI', 'saray-sarmasi', 'Saray Sarmasi', 'Palace-style rolled meat wrapped in caul fat, braised in tomato sauce with vegetables', 'Saray Sarmasi', 'stews', 'traditional', 'istanbul', 'lamb', 'braised', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 420, 30, 15, 28, 1, '["palace", "ottoman", "rolled", "elegant"]'::jsonb, 65),
('TRK_ORMAN_KEBABI', 'orman-kebabi', 'Orman Kebabi', 'Forest kebab - lamb braised with potatoes, carrots and peas in aromatic sauce', 'Orman Kebabi', 'stews', 'popular', 'national', 'lamb', 'stewed', false, false, false, true, '[]'::jsonb, true, true, true, false, false, true, 400, 32, 28, 22, 0, '["lamb", "vegetables", "one-pot", "family-style"]'::jsonb, 78);

-- SEAFOOD (10 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_BALIK_EKMEK', 'balik-ekmek', 'Balik Ekmek', 'Iconic Istanbul fish sandwich - grilled mackerel in crusty bread with onions, lettuce and lemon', 'Balik Ekmek', 'seafood', 'signature', 'istanbul', 'fish', 'grilled', true, false, false, true, '["fish", "gluten"]'::jsonb, false, true, true, false, false, true, 420, 28, 38, 18, 0, '["fish", "street-food", "istanbul", "iconic", "bosphorus"]'::jsonb, 95),
('TRK_LEVREK_IZGARA', 'levrek-izgara', 'Levrek Izgara', 'Grilled sea bass with olive oil and lemon, simple preparation showcasing fresh Aegean fish', 'Levrek Izgara', 'seafood', 'popular', 'aegean', 'fish', 'grilled', false, false, false, true, '["fish"]'::jsonb, true, true, true, false, false, true, 280, 35, 2, 14, 0, '["sea-bass", "grilled", "aegean", "healthy", "elegant"]'::jsonb, 88),
('TRK_CIUPRA_IZGARA', 'ciupra-izgara', 'Ciupra Izgara', 'Grilled gilt-head bream, Turkey most popular fish, served with rocket salad and lemon', 'Ciupra Izgara', 'seafood', 'popular', 'aegean', 'fish', 'grilled', false, false, false, true, '["fish"]'::jsonb, true, true, true, false, false, true, 260, 32, 2, 12, 0, '["bream", "grilled", "popular", "healthy"]'::jsonb, 90),
('TRK_HAMSI_TAVA', 'hamsi-tava', 'Hamsi Tava', 'Crispy fried Black Sea anchovies, coated in cornmeal and pan-fried until golden', 'Hamsi Tava', 'seafood', 'signature', 'black_sea', 'fish', 'fried', true, true, false, true, '["fish", "gluten"]'::jsonb, false, true, true, false, false, true, 320, 22, 18, 20, 0, '["anchovy", "fried", "black-sea", "crispy", "meze"]'::jsonb, 85),
('TRK_KARIDES_GUVEC', 'karides-guvec', 'Karides Guvec', 'Shrimp baked in clay pot with tomatoes, peppers and melted cheese, bubbling hot', 'Karides Guvec', 'seafood', 'popular', 'aegean', 'seafood', 'baked', false, true, false, true, '["shellfish", "dairy"]'::jsonb, true, false, true, false, false, true, 350, 25, 12, 24, 1, '["shrimp", "clay-pot", "cheese", "appetizer"]'::jsonb, 82),
('TRK_LUFER_IZGARA', 'lufer-izgara', 'Lufer Izgara', 'Grilled bluefish, prized seasonal fish from the Bosphorus with rich oily flesh', 'Lufer Izgara', 'seafood', 'regional', 'istanbul', 'fish', 'grilled', false, false, false, true, '["fish"]'::jsonb, true, true, true, false, false, true, 300, 30, 0, 18, 0, '["bluefish", "seasonal", "bosphorus", "premium"]'::jsonb, 78),
('TRK_KALAMAR_TAVA', 'kalamar-tava', 'Kalamar Tava', 'Deep-fried calamari rings, crispy and tender, served with tarator sauce', 'Kalamar Tava', 'seafood', 'popular', 'aegean', 'seafood', 'fried', false, true, false, true, '["shellfish", "gluten"]'::jsonb, false, true, true, false, false, true, 340, 18, 22, 22, 0, '["calamari", "fried", "crispy", "appetizer"]'::jsonb, 85),
('TRK_BALIK_BUGLAMA', 'balik-buglama', 'Balik Buglama', 'Fish poached with vegetables in its own juices, delicate and healthy preparation', 'Balik Buglama', 'seafood', 'traditional', 'black_sea', 'fish', 'steamed', false, false, false, true, '["fish"]'::jsonb, true, true, true, false, false, true, 220, 28, 10, 8, 0, '["poached", "healthy", "light", "traditional"]'::jsonb, 70),
('TRK_AHTAPOT_IZGARA', 'ahtapot-izgara', 'Ahtapot Izgara', 'Grilled octopus tentacles, tender and smoky, drizzled with olive oil and lemon', 'Ahtapot Izgara', 'seafood', 'popular', 'aegean', 'seafood', 'grilled', false, true, false, true, '["shellfish"]'::jsonb, true, true, true, false, false, true, 180, 24, 4, 8, 0, '["octopus", "grilled", "meze", "aegean"]'::jsonb, 75),
('TRK_MIDYE_TAVA', 'midye-tava', 'Midye Tava', 'Fried mussels on a stick, crispy battered and served with tarator garlic sauce', 'Midye Tava', 'seafood', 'signature', 'istanbul', 'seafood', 'fried', true, false, false, true, '["shellfish", "gluten"]'::jsonb, false, true, false, false, false, true, 280, 16, 20, 18, 0, '["mussels", "fried", "street-food", "istanbul"]'::jsonb, 82);

-- DESSERTS (12 dishes)
INSERT INTO turkish (id, slug, name, description, turkish_name, category, status, region, protein_type, cooking_method, is_street_food, is_meze, is_breakfast_item, served_hot, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity) VALUES
('TRK_BAKLAVA', 'baklava', 'Baklava', 'Legendary layered phyllo pastry with pistachios and honey syrup, Gaziantep specialty', 'Baklava', 'desserts', 'signature', 'southeastern', 'vegetarian', 'baked', false, false, false, false, '["gluten", "tree_nuts"]'::jsonb, false, true, false, false, true, true, 350, 6, 42, 20, 0, '["baklava", "pistachio", "honey", "gaziantep", "iconic"]'::jsonb, 98),
('TRK_KUNEFE', 'kunefe', 'Kunefe', 'Hot shredded phyllo dessert with stretchy cheese filling, soaked in sweet syrup and topped with pistachios', 'Kunefe', 'desserts', 'signature', 'southeastern', 'vegetarian', 'baked', false, false, false, true, '["gluten", "dairy", "tree_nuts"]'::jsonb, false, false, false, false, true, true, 420, 10, 52, 22, 0, '["kunefe", "cheese", "hot-dessert", "hatay", "stretchy"]'::jsonb, 95),
('TRK_LOKUM', 'turkish-delight', 'Lokum', 'Turkish delight - soft gel candy in many flavors, rose, lemon, pomegranate with pistachios', 'Lokum', 'desserts', 'signature', 'istanbul', 'vegan', 'raw', false, false, false, false, '["tree_nuts"]'::jsonb, true, true, false, true, true, true, 120, 1, 28, 2, 0, '["turkish-delight", "candy", "rose", "gift", "iconic"]'::jsonb, 92),
('TRK_SUTLAC', 'sutlac', 'Sutlac', 'Turkish rice pudding with caramelized top, creamy and comforting baked dessert', 'Sutlac', 'desserts', 'classic', 'national', 'vegetarian', 'baked', false, false, false, false, '["dairy"]'::jsonb, true, false, true, false, true, true, 220, 6, 38, 6, 0, '["rice-pudding", "baked", "comfort", "classic"]'::jsonb, 88),
('TRK_KAZANDIBI', 'kazandibi', 'Kazandibi', 'Bottom of the cauldron - milk pudding with caramelized burnt bottom, unique Turkish creation', 'Kazandibi', 'desserts', 'traditional', 'istanbul', 'vegetarian', 'baked', false, false, false, false, '["dairy"]'::jsonb, true, false, true, false, true, true, 200, 5, 32, 6, 0, '["milk-pudding", "caramelized", "unique", "ottoman"]'::jsonb, 80),
('TRK_ASURE', 'asure', 'Asure', 'Noah pudding - grain and dried fruit pudding with religious significance, shared with neighbors', 'Asure', 'desserts', 'traditional', 'national', 'vegan', 'stewed', false, false, false, false, '["gluten", "tree_nuts"]'::jsonb, false, true, false, true, true, true, 250, 6, 48, 5, 0, '["noah-pudding", "grains", "religious", "sharing"]'::jsonb, 72),
('TRK_REVANI', 'revani', 'Revani', 'Semolina cake soaked in light syrup, soft and moist with subtle citrus flavor', 'Revani', 'desserts', 'classic', 'national', 'vegetarian', 'baked', false, false, false, false, '["gluten", "dairy", "eggs"]'::jsonb, false, false, true, false, true, true, 280, 5, 48, 8, 0, '["semolina", "syrup", "cake", "moist"]'::jsonb, 78),
('TRK_SEKERPARE', 'sekerpare', 'Sekerpare', 'Sweet almond cookies soaked in syrup, melt-in-your-mouth texture with hazelnut on top', 'Sekerpare', 'desserts', 'classic', 'national', 'vegetarian', 'baked', false, false, false, false, '["gluten", "tree_nuts", "eggs"]'::jsonb, false, true, false, false, true, true, 180, 3, 28, 8, 0, '["cookies", "syrup", "almond", "traditional"]'::jsonb, 82),
('TRK_DONDURMA', 'maras-dondurmasi', 'Maras Dondurmasi', 'Famous Turkish stretchy ice cream from Kahramanmaras, made with salep and mastic, chewy texture', 'Maras Dondurmasi', 'desserts', 'signature', 'southeastern', 'vegetarian', 'raw', true, false, false, false, '["dairy"]'::jsonb, true, false, true, false, true, true, 180, 4, 28, 7, 0, '["ice-cream", "stretchy", "maras", "salep", "iconic"]'::jsonb, 90),
('TRK_TAVUK_GOGSU', 'tavuk-gogsu', 'Tavuk Gogsu', 'Unique chicken breast pudding - milk dessert with shredded chicken, surprisingly sweet and creamy', 'Tavuk Gogsu', 'desserts', 'traditional', 'istanbul', 'chicken', 'stewed', false, false, false, false, '["dairy"]'::jsonb, true, false, true, false, false, true, 190, 8, 28, 5, 0, '["chicken", "pudding", "unique", "ottoman", "unusual"]'::jsonb, 65),
('TRK_KADAYIF', 'tel-kadayif', 'Tel Kadayif', 'Shredded phyllo threads baked with walnuts or pistachios, crispy and syrup-soaked', 'Tel Kadayif', 'desserts', 'classic', 'national', 'vegetarian', 'baked', false, false, false, false, '["gluten", "tree_nuts"]'::jsonb, false, true, false, false, true, true, 320, 5, 44, 16, 0, '["kadayif", "shredded", "crispy", "syrup", "walnut"]'::jsonb, 85),
('TRK_MUHALLEBI', 'muhallebi', 'Muhallebi', 'Simple milk pudding with rose water, light and delicate topped with cinnamon', 'Muhallebi', 'desserts', 'classic', 'national', 'vegetarian', 'stewed', false, false, false, false, '["dairy"]'::jsonb, true, false, true, false, true, true, 150, 5, 24, 4, 0, '["milk-pudding", "rose", "light", "simple"]'::jsonb, 75);

-- Summary
DO $$
DECLARE
  total_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO total_count FROM turkish;
  RAISE NOTICE 'Turkish data imported successfully!';
  RAISE NOTICE 'Total dishes: %', total_count;
END $$;
