-- ============================================
-- German Cuisine - Data Insert
-- Created: 2025-12-24
-- Total dishes: 50
-- ============================================

-- SAUSAGES (8 dishes)
INSERT INTO german (id, slug, name, german_name, description, category, region, status, ingredient_ids, allergens, dietary, spice_level, serving_temp, preparation_time_min, popularity, price_category)
VALUES
('GER_BRATWURST', 'bratwurst', 'Bratwurst', 'Bratwurst', 'Traditional German grilled pork sausage, seasoned with caraway, nutmeg and ginger. Served with mustard and sauerkraut.', 'sausages', 'nationwide', 'classic', ARRAY['ING_PORK', 'ING_SAUSAGE_CASING', 'ING_CARAWAY', 'ING_NUTMEG', 'ING_GINGER', 'ING_SALT', 'ING_WHITE_PEPPER'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 1, 'hot', 20, 95, 'budget'),
('GER_CURRYWURST', 'currywurst', 'Currywurst', 'Currywurst', 'Berlin specialty of steamed then fried pork sausage sliced and smothered in curry ketchup sauce, served with fries.', 'sausages', 'berlin', 'classic', ARRAY['ING_PORK_SAUSAGE', 'ING_KETCHUP', 'ING_CURRY_POWDER', 'ING_WORCESTERSHIRE_SAUCE', 'ING_PAPRIKA', 'ING_ONION'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 2, 'hot', 15, 92, 'budget'),
('GER_WEISSWURST', 'weisswurst', 'White Sausage', 'Weißwurst', 'Traditional Bavarian white sausage made from minced veal and pork back bacon, flavored with parsley, lemon and mace. Served with sweet mustard and pretzels.', 'sausages', 'bavaria', 'classic', ARRAY['ING_VEAL', 'ING_PORK_BELLY', 'ING_PARSLEY', 'ING_LEMON_ZEST', 'ING_MACE', 'ING_ONION', 'ING_SALT'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 25, 85, 'moderate'),
('GER_BOCKWURST', 'bockwurst', 'Bockwurst', 'Bockwurst', 'Smoked sausage made from veal and pork, traditionally flavored with paprika, salt and chives. Often served with bock beer.', 'sausages', 'berlin', 'classic', ARRAY['ING_VEAL', 'ING_PORK', 'ING_CHIVES', 'ING_PAPRIKA', 'ING_SALT', 'ING_WHITE_PEPPER'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 1, 'hot', 15, 75, 'budget'),
('GER_THUERINGER', 'thueringer-rostbratwurst', 'Thuringian Bratwurst', 'Thüringer Rostbratwurst', 'Protected regional specialty from Thuringia, made with finely ground pork and beef, seasoned with caraway, marjoram and garlic.', 'sausages', 'thuringia', 'regional', ARRAY['ING_PORK', 'ING_BEEF', 'ING_CARAWAY', 'ING_MARJORAM', 'ING_GARLIC', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 1, 'hot', 20, 80, 'moderate'),
('GER_NUERNBERGER', 'nuernberger-rostbratwurst', 'Nuremberg Bratwurst', 'Nürnberger Rostbratwurst', 'Small finger-sized bratwurst from Franconia, typically served 6-12 at a time. Distinctively seasoned with marjoram.', 'sausages', 'franconia', 'regional', ARRAY['ING_PORK', 'ING_MARJORAM', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_NUTMEG'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 1, 'hot', 15, 82, 'moderate'),
('GER_LEBERKASE', 'leberkaese', 'Bavarian Meatloaf', 'Leberkäse', 'Baked loaf of finely ground beef, pork and bacon. Despite the name, contains neither liver nor cheese. Served sliced in rolls or with fried eggs.', 'sausages', 'bavaria', 'classic', ARRAY['ING_BEEF', 'ING_PORK', 'ING_BACON', 'ING_ONION', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_MARJORAM'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 90, 78, 'budget'),
('GER_FRANKFURTER', 'frankfurter-wuerstchen', 'Frankfurt Sausage', 'Frankfurter Würstchen', 'Thin smoked sausage made from pure pork in a sheep casing. The original hot dog sausage, protected by EU law.', 'sausages', 'rhineland', 'classic', ARRAY['ING_PORK', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_PAPRIKA'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 10, 75, 'budget');

-- MAINS (11 dishes)
INSERT INTO german (id, slug, name, german_name, description, category, region, status, ingredient_ids, allergens, dietary, spice_level, serving_temp, preparation_time_min, popularity, price_category)
VALUES
('GER_SCHNITZEL', 'wiener-schnitzel', 'Wiener Schnitzel', 'Wiener Schnitzel', 'Breaded and pan-fried veal cutlet, pounded thin and coated in flour, egg and breadcrumbs. Served with lemon wedge and potato salad.', 'mains', 'nationwide', 'classic', ARRAY['ING_VEAL', 'ING_FLOUR', 'ING_EGG', 'ING_BREADCRUMBS', 'ING_BUTTER', 'ING_LEMON', 'ING_SALT'], ARRAY['gluten', 'eggs'], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'hot', 30, 98, 'moderate'),
('GER_SCHWEINESCHNITZEL', 'schweineschnitzel', 'Pork Schnitzel', 'Schweineschnitzel', 'German-style breaded pork cutlet, similar to Wiener Schnitzel but made with pork instead of veal.', 'mains', 'nationwide', 'classic', ARRAY['ING_PORK_LOIN', 'ING_FLOUR', 'ING_EGG', 'ING_BREADCRUMBS', 'ING_BUTTER', 'ING_LEMON', 'ING_SALT'], ARRAY['gluten', 'eggs'], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'hot', 30, 90, 'budget'),
('GER_SAUERBRATEN', 'sauerbraten', 'Sauerbraten', 'Sauerbraten', 'Germany''s national dish. Beef roast marinated for days in vinegar, wine and spices, then braised until tender. Served with red cabbage and potato dumplings.', 'mains', 'rhineland', 'classic', ARRAY['ING_BEEF_ROAST', 'ING_RED_WINE_VINEGAR', 'ING_RED_WINE', 'ING_ONION', 'ING_CARROT', 'ING_BAY_LEAF', 'ING_JUNIPER_BERRIES', 'ING_CLOVE', 'ING_PEPPERCORN'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 1, 'hot', 180, 88, 'premium'),
('GER_SCHWEINSHAXE', 'schweinshaxe', 'Pork Knuckle', 'Schweinshaxe', 'Bavarian roasted pork knuckle with crispy crackling skin and tender meat. Typically served with sauerkraut and dumplings.', 'mains', 'bavaria', 'classic', ARRAY['ING_PORK_KNUCKLE', 'ING_CARAWAY', 'ING_GARLIC', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_BEER'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 1, 'hot', 180, 85, 'premium'),
('GER_ROULADEN', 'rinderrouladen', 'Beef Roulades', 'Rinderrouladen', 'Thin slices of beef wrapped around bacon, onions, pickles and mustard, braised in rich gravy. A German Sunday dinner classic.', 'mains', 'nationwide', 'classic', ARRAY['ING_BEEF_EYE_ROUND', 'ING_BACON', 'ING_ONION', 'ING_PICKLE', 'ING_MUSTARD', 'ING_BEEF_BROTH', 'ING_RED_WINE'], ARRAY['mustard'], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 1, 'hot', 120, 82, 'premium'),
('GER_MAULTASCHEN', 'maultaschen', 'Swabian Ravioli', 'Maultaschen', 'Large Swabian pasta pockets filled with minced meat, spinach, onions and breadcrumbs. Legend says monks invented them to hide meat during Lent.', 'mains', 'swabia', 'regional', ARRAY['ING_FLOUR', 'ING_EGG', 'ING_PORK', 'ING_VEAL', 'ING_SPINACH', 'ING_ONION', 'ING_BREADCRUMBS', 'ING_PARSLEY', 'ING_NUTMEG'], ARRAY['gluten', 'eggs'], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 90, 78, 'moderate'),
('GER_KASSLER', 'kassler', 'Smoked Pork Chop', 'Kassler', 'Salted and smoked pork chop or loin, typically served with sauerkraut and mashed potatoes. Named after a Berlin butcher.', 'mains', 'berlin', 'classic', ARRAY['ING_PORK_LOIN', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_JUNIPER_BERRIES'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 45, 75, 'moderate'),
('GER_KOENIGSBERGER', 'koenigsberger-klopse', 'Königsberg Meatballs', 'Königsberger Klopse', 'Poached meatballs made from veal and pork in a creamy white caper sauce. A classic East Prussian dish.', 'mains', 'berlin', 'classic', ARRAY['ING_VEAL', 'ING_PORK', 'ING_ONION', 'ING_EGG', 'ING_BREADCRUMBS', 'ING_ANCHOVY', 'ING_CAPERS', 'ING_HEAVY_CREAM', 'ING_LEMON_JUICE'], ARRAY['gluten', 'eggs', 'fish'], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'hot', 60, 72, 'moderate'),
('GER_ZWIEBELROSTBRATEN', 'zwiebelrostbraten', 'Roast Beef with Onions', 'Zwiebelrostbraten', 'Pan-fried beef steak topped with caramelized onions, served with pan juices. A Swabian specialty.', 'mains', 'swabia', 'regional', ARRAY['ING_BEEF_STEAK', 'ING_ONION', 'ING_BUTTER', 'ING_BEEF_BROTH', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'hot', 40, 74, 'premium'),
('GER_EISBEIN', 'eisbein', 'Pickled Pork Knuckle', 'Eisbein', 'Cured and boiled pork knuckle, different from the Bavarian roasted version. Served with sauerkraut and pea puree. A Berlin specialty.', 'mains', 'berlin', 'regional', ARRAY['ING_PORK_KNUCKLE', 'ING_BAY_LEAF', 'ING_JUNIPER_BERRIES', 'ING_PEPPERCORN', 'ING_SALT'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 180, 70, 'moderate'),
('GER_JAEGERSCHNITZEL', 'jaegerschnitzel', 'Hunter''s Schnitzel', 'Jägerschnitzel', 'Breaded pork schnitzel topped with a rich mushroom cream sauce. A hearty German comfort food classic.', 'mains', 'nationwide', 'classic', ARRAY['ING_PORK_LOIN', 'ING_FLOUR', 'ING_EGG', 'ING_BREADCRUMBS', 'ING_MUSHROOM', 'ING_ONION', 'ING_HEAVY_CREAM', 'ING_WHITE_WINE'], ARRAY['gluten', 'eggs'], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'hot', 45, 85, 'moderate');

-- SIDES (10 dishes)
INSERT INTO german (id, slug, name, german_name, description, category, region, status, ingredient_ids, allergens, dietary, spice_level, serving_temp, preparation_time_min, popularity, price_category)
VALUES
('GER_SPAETZLE', 'spaetzle', 'Spätzle', 'Spätzle', 'Soft Swabian egg noodles made from flour, eggs and water. Often served as a side dish or with cheese as Käsespätzle.', 'sides', 'swabia', 'classic', ARRAY['ING_FLOUR', 'ING_EGG', 'ING_SALT', 'ING_NUTMEG', 'ING_BUTTER'], ARRAY['gluten', 'eggs'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'hot', 30, 88, 'budget'),
('GER_KAESESPAETZLE', 'kaesespaetzle', 'Cheese Spätzle', 'Käsespätzle', 'Spätzle noodles layered with melted cheese and topped with crispy caramelized onions. German mac and cheese.', 'sides', 'swabia', 'classic', ARRAY['ING_FLOUR', 'ING_EGG', 'ING_SWISS_CHEESE', 'ING_GRUYERE', 'ING_ONION', 'ING_BUTTER', 'ING_SALT'], ARRAY['gluten', 'eggs', 'dairy'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'hot', 45, 85, 'moderate'),
('GER_KARTOFFELKLOESSE', 'kartoffelkloesse', 'Potato Dumplings', 'Kartoffelklöße', 'Traditional German potato dumplings made from cooked and raw potatoes. Perfect for soaking up gravy.', 'sides', 'thuringia', 'classic', ARRAY['ING_POTATO', 'ING_POTATO_STARCH', 'ING_EGG', 'ING_SALT', 'ING_NUTMEG'], ARRAY['eggs'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": true, "is_kosher": true}', 0, 'hot', 60, 80, 'budget'),
('GER_SAUERKRAUT', 'sauerkraut', 'Sauerkraut', 'Sauerkraut', 'Fermented cabbage with a tangy, sour flavor. Traditional German side dish served with sausages and pork.', 'sides', 'nationwide', 'classic', ARRAY['ING_CABBAGE', 'ING_SALT', 'ING_CARAWAY', 'ING_JUNIPER_BERRIES', 'ING_BAY_LEAF'], ARRAY[]::TEXT[], '{"is_vegetarian": true, "is_vegan": true, "is_gluten_free": true, "is_dairy_free": true, "is_halal": true, "is_kosher": true}', 0, 'hot', 30, 85, 'budget'),
('GER_ROTKOHL', 'rotkohl', 'Red Cabbage', 'Rotkohl', 'Braised red cabbage cooked with apples, vinegar and spices. Sweet and sour side dish for festive meals.', 'sides', 'nationwide', 'classic', ARRAY['ING_RED_CABBAGE', 'ING_APPLE', 'ING_ONION', 'ING_RED_WINE_VINEGAR', 'ING_SUGAR', 'ING_CLOVE', 'ING_BAY_LEAF'], ARRAY[]::TEXT[], '{"is_vegetarian": true, "is_vegan": true, "is_gluten_free": true, "is_dairy_free": true, "is_halal": true, "is_kosher": true}', 0, 'hot', 60, 78, 'budget'),
('GER_KARTOFFELPUFFER', 'kartoffelpuffer', 'Potato Pancakes', 'Kartoffelpuffer', 'Crispy pan-fried potato pancakes made from grated raw potatoes, onions and eggs. Served with applesauce or sour cream.', 'sides', 'rhineland', 'classic', ARRAY['ING_POTATO', 'ING_ONION', 'ING_EGG', 'ING_FLOUR', 'ING_SALT', 'ING_VEGETABLE_OIL'], ARRAY['gluten', 'eggs'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": true, "is_halal": true, "is_kosher": true}', 0, 'hot', 30, 82, 'budget'),
('GER_BRATKARTOFFELN', 'bratkartoffeln', 'German Fried Potatoes', 'Bratkartoffeln', 'Pan-fried sliced potatoes with onions and bacon. A classic German side dish for any meal.', 'sides', 'nationwide', 'classic', ARRAY['ING_POTATO', 'ING_ONION', 'ING_BACON', 'ING_BUTTER', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_PARSLEY'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'hot', 35, 80, 'budget'),
('GER_KARTOFFELSALAT', 'kartoffelsalat', 'German Potato Salad', 'Kartoffelsalat', 'Warm potato salad dressed with vinegar, oil and mustard (Southern style) or mayonnaise (Northern style).', 'sides', 'nationwide', 'classic', ARRAY['ING_POTATO', 'ING_ONION', 'ING_PICKLE', 'ING_BEEF_BROTH', 'ING_VINEGAR', 'ING_VEGETABLE_OIL', 'ING_MUSTARD', 'ING_PARSLEY'], ARRAY['mustard'], '{"is_vegetarian": true, "is_vegan": true, "is_gluten_free": true, "is_dairy_free": true, "is_halal": true, "is_kosher": true}', 0, 'warm', 40, 85, 'budget'),
('GER_SEMMELKNOEDEL', 'semmelknoedel', 'Bread Dumplings', 'Semmelknödel', 'Bavarian dumplings made from stale bread, milk, eggs and parsley. Perfect accompaniment for roast meats.', 'sides', 'bavaria', 'classic', ARRAY['ING_BREAD', 'ING_MILK', 'ING_EGG', 'ING_ONION', 'ING_PARSLEY', 'ING_BUTTER', 'ING_NUTMEG'], ARRAY['gluten', 'eggs', 'dairy'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'hot', 45, 75, 'budget'),
('GER_HIMMEL_ERDE', 'himmel-und-erde', 'Heaven and Earth', 'Himmel und Erde', 'Traditional Rhineland dish of mashed potatoes (earth) and apple sauce (heaven), typically served with blood sausage.', 'sides', 'rhineland', 'regional', ARRAY['ING_POTATO', 'ING_APPLE', 'ING_ONION', 'ING_BUTTER', 'ING_SUGAR', 'ING_SALT'], ARRAY[]::TEXT[], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'hot', 40, 65, 'budget');

-- SOUPS (6 dishes)
INSERT INTO german (id, slug, name, german_name, description, category, region, status, ingredient_ids, allergens, dietary, spice_level, serving_temp, preparation_time_min, popularity, price_category)
VALUES
('GER_KARTOFFELSUPPE', 'kartoffelsuppe', 'German Potato Soup', 'Kartoffelsuppe', 'Hearty potato soup with leeks, carrots and celery, often garnished with bacon and fresh herbs.', 'soups', 'nationwide', 'classic', ARRAY['ING_POTATO', 'ING_LEEK', 'ING_CARROT', 'ING_CELERY', 'ING_ONION', 'ING_BACON', 'ING_VEGETABLE_BROTH', 'ING_HEAVY_CREAM', 'ING_PARSLEY'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'hot', 45, 78, 'budget'),
('GER_ERBSENSUPPE', 'erbsensuppe', 'Split Pea Soup', 'Erbsensuppe', 'Thick and hearty split pea soup cooked with smoked pork and vegetables. A German winter staple.', 'soups', 'nationwide', 'classic', ARRAY['ING_SPLIT_PEAS', 'ING_SMOKED_PORK', 'ING_ONION', 'ING_CARROT', 'ING_CELERY', 'ING_LEEK', 'ING_BAY_LEAF', 'ING_MARJORAM'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 90, 72, 'budget'),
('GER_LINSENSUPPE', 'linsensuppe', 'Lentil Soup', 'Linsensuppe', 'Traditional German lentil soup with root vegetables and smoked sausage, finished with a splash of vinegar.', 'soups', 'swabia', 'classic', ARRAY['ING_LENTILS', 'ING_SMOKED_SAUSAGE', 'ING_ONION', 'ING_CARROT', 'ING_CELERY', 'ING_POTATO', 'ING_VINEGAR', 'ING_BAY_LEAF'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 60, 75, 'budget'),
('GER_GULASCHSUPPE', 'gulaschsuppe', 'Goulash Soup', 'Gulaschsuppe', 'German-style goulash soup with tender beef cubes, peppers and potatoes in a rich paprika broth.', 'soups', 'nationwide', 'classic', ARRAY['ING_BEEF', 'ING_ONION', 'ING_BELL_PEPPER', 'ING_POTATO', 'ING_TOMATO_PASTE', 'ING_PAPRIKA', 'ING_CARAWAY', 'ING_BEEF_BROTH'], ARRAY[]::TEXT[], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": true, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 1, 'hot', 90, 80, 'moderate'),
('GER_HOCHZEITSSUPPE', 'hochzeitssuppe', 'Wedding Soup', 'Hochzeitssuppe', 'Clear beef broth with tiny meatballs, egg drops and vegetables. Traditional German celebration soup.', 'soups', 'nationwide', 'classic', ARRAY['ING_BEEF_BROTH', 'ING_BEEF', 'ING_EGG', 'ING_BREADCRUMBS', 'ING_CARROT', 'ING_LEEK', 'ING_PARSLEY', 'ING_NUTMEG'], ARRAY['gluten', 'eggs'], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 75, 68, 'moderate'),
('GER_LEBERKNOEDESUPPE', 'leberknoedelsuppe', 'Liver Dumpling Soup', 'Leberknödelsuppe', 'Clear beef broth with large liver dumplings. A Bavarian specialty often served as a first course.', 'soups', 'bavaria', 'regional', ARRAY['ING_BEEF_LIVER', 'ING_BEEF_BROTH', 'ING_BREAD', 'ING_EGG', 'ING_ONION', 'ING_MARJORAM', 'ING_PARSLEY', 'ING_SALT'], ARRAY['gluten', 'eggs'], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'hot', 60, 65, 'moderate');

-- BAKED (6 dishes)
INSERT INTO german (id, slug, name, german_name, description, category, region, status, ingredient_ids, allergens, dietary, spice_level, serving_temp, preparation_time_min, popularity, price_category)
VALUES
('GER_BREZEL', 'brezel', 'German Pretzel', 'Brezel', 'Traditional Bavarian soft pretzel with a dark, chewy crust and soft interior, topped with coarse salt.', 'baked', 'bavaria', 'classic', ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_BUTTER', 'ING_SALT', 'ING_BAKING_SODA', 'ING_WATER'], ARRAY['gluten'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'warm', 90, 92, 'budget'),
('GER_LAUGENBROETCHEN', 'laugenbroetchen', 'Lye Roll', 'Laugenbrötchen', 'Soft bread roll dipped in lye solution before baking, giving it a distinctive brown crust. Perfect for sandwiches.', 'baked', 'swabia', 'classic', ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_BUTTER', 'ING_SALT', 'ING_BAKING_SODA', 'ING_MILK'], ARRAY['gluten', 'dairy'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'room_temp', 75, 78, 'budget'),
('GER_ROGGENBROT', 'roggenbrot', 'German Rye Bread', 'Roggenbrot', 'Dense, dark sourdough rye bread. A staple of German cuisine, often topped with butter and cold cuts.', 'baked', 'nationwide', 'classic', ARRAY['ING_RYE_FLOUR', 'ING_SOURDOUGH', 'ING_CARAWAY', 'ING_SALT', 'ING_WATER'], ARRAY['gluten'], '{"is_vegetarian": true, "is_vegan": true, "is_gluten_free": false, "is_dairy_free": true, "is_halal": true, "is_kosher": true}', 0, 'room_temp', 240, 80, 'budget'),
('GER_PUMPERNICKEL', 'pumpernickel', 'Pumpernickel', 'Pumpernickel', 'Very dark, dense bread made from coarsely ground rye. Slow-baked for up to 24 hours, developing a sweet, malty flavor.', 'baked', 'rhineland', 'classic', ARRAY['ING_RYE_FLOUR', 'ING_RYE_BERRIES', 'ING_MOLASSES', 'ING_SALT'], ARRAY['gluten'], '{"is_vegetarian": true, "is_vegan": true, "is_gluten_free": false, "is_dairy_free": true, "is_halal": true, "is_kosher": true}', 0, 'room_temp', 1440, 70, 'moderate'),
('GER_BROETCHEN', 'broetchen', 'German Bread Roll', 'Brötchen', 'Small, crusty bread rolls essential to German breakfast. Known by different names across Germany.', 'baked', 'nationwide', 'classic', ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_SALT', 'ING_WATER', 'ING_BUTTER'], ARRAY['gluten'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'room_temp', 120, 88, 'budget'),
('GER_ZWIEBELBROT', 'zwiebelbrot', 'Onion Bread', 'Zwiebelbrot', 'Savory bread studded with caramelized onions and sometimes bacon. Popular in Southern Germany.', 'baked', 'bavaria', 'regional', ARRAY['ING_FLOUR', 'ING_RYE_FLOUR', 'ING_YEAST', 'ING_ONION', 'ING_BACON', 'ING_CARAWAY', 'ING_SALT'], ARRAY['gluten'], '{"is_vegetarian": false, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": true, "is_halal": false, "is_kosher": false}', 0, 'warm', 150, 68, 'budget');

-- DESSERTS (9 dishes)
INSERT INTO german (id, slug, name, german_name, description, category, region, status, ingredient_ids, allergens, dietary, spice_level, serving_temp, preparation_time_min, popularity, price_category)
VALUES
('GER_SCHWARZWAELDER', 'schwarzwaelder-kirschtorte', 'Black Forest Cake', 'Schwarzwälder Kirschtorte', 'Iconic German layered chocolate cake with whipped cream, cherries and Kirsch (cherry schnapps). Originated in the Black Forest region.', 'desserts', 'swabia', 'classic', ARRAY['ING_FLOUR', 'ING_COCOA_POWDER', 'ING_EGG', 'ING_SUGAR', 'ING_HEAVY_CREAM', 'ING_CHERRY', 'ING_KIRSCH', 'ING_DARK_CHOCOLATE'], ARRAY['gluten', 'eggs', 'dairy'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'cold', 180, 95, 'premium'),
('GER_APFELSTRUDEL', 'apfelstrudel', 'Apple Strudel', 'Apfelstrudel', 'Paper-thin pastry filled with spiced apples, raisins and breadcrumbs. Served warm with vanilla sauce or ice cream.', 'desserts', 'bavaria', 'classic', ARRAY['ING_FLOUR', 'ING_APPLE', 'ING_RAISIN', 'ING_BREADCRUMBS', 'ING_BUTTER', 'ING_CINNAMON', 'ING_SUGAR', 'ING_LEMON_ZEST'], ARRAY['gluten'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'warm', 90, 90, 'moderate'),
('GER_BERLINER', 'berliner-pfannkuchen', 'Jelly Donut', 'Berliner Pfannkuchen', 'Deep-fried yeast doughnut filled with jam and dusted with powdered sugar. A Carnival tradition throughout Germany.', 'desserts', 'berlin', 'classic', ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_BUTTER', 'ING_EGG', 'ING_MILK', 'ING_STRAWBERRY_JAM', 'ING_POWDERED_SUGAR', 'ING_VEGETABLE_OIL'], ARRAY['gluten', 'eggs', 'dairy'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'room_temp', 120, 88, 'budget'),
('GER_ROTE_GRUETZE', 'rote-gruetze', 'Red Berry Pudding', 'Rote Grütze', 'Northern German dessert of mixed red berries thickened with starch, served with cream or vanilla sauce.', 'desserts', 'nationwide', 'classic', ARRAY['ING_RASPBERRY', 'ING_STRAWBERRY', 'ING_CURRANTS', 'ING_CHERRY', 'ING_SUGAR', 'ING_CORNSTARCH', 'ING_VANILLA'], ARRAY[]::TEXT[], '{"is_vegetarian": true, "is_vegan": true, "is_gluten_free": true, "is_dairy_free": true, "is_halal": true, "is_kosher": true}', 0, 'cold', 30, 75, 'budget'),
('GER_KAISERSCHMARRN', 'kaiserschmarrn', 'Emperor''s Pancake', 'Kaiserschmarrn', 'Fluffy shredded pancake with raisins, dusted with powdered sugar. Served with apple sauce or plum compote. Austrian origin, popular in Bavaria.', 'desserts', 'bavaria', 'classic', ARRAY['ING_FLOUR', 'ING_EGG', 'ING_MILK', 'ING_BUTTER', 'ING_RAISIN', 'ING_POWDERED_SUGAR', 'ING_VANILLA', 'ING_RUM'], ARRAY['gluten', 'eggs', 'dairy'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'hot', 30, 82, 'moderate'),
('GER_BIENENSTICH', 'bienenstich', 'Bee Sting Cake', 'Bienenstich', 'Yeast cake filled with vanilla custard and topped with caramelized honey-almond crust.', 'desserts', 'nationwide', 'classic', ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_BUTTER', 'ING_HONEY', 'ING_ALMOND', 'ING_HEAVY_CREAM', 'ING_VANILLA', 'ING_EGG'], ARRAY['gluten', 'eggs', 'dairy', 'nuts'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'room_temp', 180, 78, 'moderate'),
('GER_LEBKUCHEN', 'lebkuchen', 'German Gingerbread', 'Lebkuchen', 'Traditional German spiced cookie made with honey, nuts and warming spices. A Christmas market staple from Nuremberg.', 'desserts', 'franconia', 'seasonal', ARRAY['ING_FLOUR', 'ING_HONEY', 'ING_HAZELNUTS', 'ING_ALMOND', 'ING_CINNAMON', 'ING_NUTMEG', 'ING_CLOVE', 'ING_GINGER', 'ING_EGG'], ARRAY['gluten', 'eggs', 'nuts'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": true, "is_halal": true, "is_kosher": true}', 1, 'room_temp', 120, 85, 'moderate'),
('GER_STOLLEN', 'dresdner-stollen', 'Dresden Christmas Stollen', 'Dresdner Stollen', 'Rich fruit bread with dried fruits, nuts and marzipan, coated in butter and powdered sugar. Traditional Christmas bread from Dresden.', 'desserts', 'saxony', 'seasonal', ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_MARZIPAN', 'ING_RAISIN', 'ING_CANDIED_CITRUS', 'ING_ALMOND', 'ING_RUM', 'ING_POWDERED_SUGAR'], ARRAY['gluten', 'dairy', 'nuts'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": false, "is_kosher": false}', 0, 'room_temp', 300, 88, 'premium'),
('GER_DAMPFNUDELN', 'dampfnudeln', 'Steamed Dumplings', 'Dampfnudeln', 'Sweet steamed yeast dumplings with a golden crust on the bottom, served with vanilla sauce.', 'desserts', 'bavaria', 'regional', ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_MILK', 'ING_BUTTER', 'ING_SUGAR', 'ING_EGG', 'ING_SALT', 'ING_VANILLA'], ARRAY['gluten', 'eggs', 'dairy'], '{"is_vegetarian": true, "is_vegan": false, "is_gluten_free": false, "is_dairy_free": false, "is_halal": true, "is_kosher": true}', 0, 'hot', 90, 70, 'budget');

-- Verification
SELECT category, COUNT(*) as count FROM german GROUP BY category ORDER BY category;
SELECT 'Total German dishes: ' || COUNT(*) as total FROM german;
