-- Malaysian Cuisine - Data
-- GUDBRO Database Standards v1.7
-- Generated: 2025-12-25
--
-- Total dishes: 57

-- =====================================================
-- INSERT DISHES
-- =====================================================

INSERT INTO malaysian (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, dietary, allergens, tags, popularity)
VALUES
('MAL_NASI_LEMAK', 'nasi-lemak', 'Nasi Lemak', 'Nasi Lemak', 'Malaysia''s national dish featuring fragrant coconut rice cooked with pandan leaves, served with sambal, fried anchovies, roasted peanuts, cucumber slices, and hard-boiled egg', 'rice', 'nationwide', 'iconic', 'chicken', 'steamed', 45, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": false, "is_halal": true, "is_kosher": false}'::jsonb, '{peanuts,fish}', '{national_dish,breakfast,street_food,coconut}', 98),
('MAL_NASI_GORENG', 'nasi-goreng-malaysia', 'Nasi Goreng', 'Nasi Goreng', 'Malaysian-style fried rice stir-fried with sweet soy sauce, shrimp paste, chilies, egg, and choice of protein, garnished with crispy shallots', 'rice', 'nationwide', 'iconic', 'mixed', 'stir_fried', 20, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish,soy,eggs}', '{fried_rice,street_food,wok}', 92),
('MAL_NASI_KANDAR', 'nasi-kandar', 'Nasi Kandar', 'Nasi Kandar', 'Penang specialty of steamed rice served with a variety of curries and side dishes, with the rice generously ladled with flavorful curry sauces', 'rice', 'penang', 'iconic', 'mixed', 'steamed', 60, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy}', '{penang,curry,mamak}', 88),
('MAL_NASI_KERABU', 'nasi-kerabu', 'Nasi Kerabu', 'Nasi Kerabu', 'Blue-colored rice dish from Kelantan, tinted with butterfly pea flowers, served with fish, crackers, pickled vegetables, and fresh herbs', 'rice', 'kelantan', 'traditional', 'fish', 'steamed', 50, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish}', '{kelantan,colorful,herbal}', 82),
('MAL_NASI_DAGANG', 'nasi-dagang', 'Nasi Dagang', 'Nasi Dagang', 'East coast specialty of glutinous rice mixed with regular rice, steamed in coconut milk, served with tuna curry, pickled vegetables, and hard-boiled eggs', 'rice', 'kelantan', 'traditional', 'fish', 'steamed', 60, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish,eggs}', '{breakfast,east_coast,glutinous}', 78),
('MAL_NASI_ULAM', 'nasi-ulam', 'Nasi Ulam', 'Nasi Ulam', 'Traditional herbed rice mixed with finely sliced fresh herbs, dried shrimp, coconut, and aromatic spices, a healthy and fragrant dish', 'rice', 'kelantan', 'traditional', 'shrimp', 'mixed', 40, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish}', '{herbal,healthy,aromatic}', 72),
('MAL_CHAR_KWAY_TEOW', 'char-kway-teow', 'Char Kway Teow', 'Char Kway Teow', 'Iconic stir-fried flat rice noodles with prawns, cockles, Chinese sausage, bean sprouts, and chives, cooked in dark soy sauce with wok hei', 'noodles', 'penang', 'iconic', 'seafood', 'stir_fried', 15, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{shellfish,soy,eggs}', '{street_food,wok_hei,penang,hawker}', 95),
('MAL_LAKSA_PENANG', 'penang-laksa', 'Penang Asam Laksa', 'Asam Laksa', 'Tangy and spicy fish-based noodle soup with thick rice noodles, mackerel flakes, cucumber, onions, pineapple, mint, and shrimp paste', 'noodles', 'penang', 'iconic', 'fish', 'boiled', 60, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish,shellfish}', '{sour,spicy,penang,world_famous}', 94),
('MAL_LAKSA_SARAWAK', 'sarawak-laksa', 'Sarawak Laksa', 'Laksa Sarawak', 'Creamy coconut-based noodle soup from Sarawak with vermicelli, prawns, shredded chicken, and omelet strips in a complex spice paste broth', 'noodles', 'sarawak', 'iconic', 'mixed', 'boiled', 75, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish,eggs}', '{sarawak,kuching,creamy,coconut}', 90),
('MAL_CURRY_LAKSA', 'curry-laksa', 'Curry Laksa', 'Laksa Lemak', 'Rich and creamy coconut curry noodle soup with yellow noodles and vermicelli, tofu puffs, prawns, cockles, and bean sprouts', 'noodles', 'kuala_lumpur', 'iconic', 'seafood', 'boiled', 50, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish,soy}', '{curry,coconut,creamy,hawker}', 88),
('MAL_KOLO_MEE', 'kolo-mee', 'Kolo Mee', 'Kolo Mee', 'Sarawak dry noodles tossed in sauce and lard, topped with sliced char siu barbecued pork, minced pork, and fried onions', 'noodles', 'sarawak', 'iconic', 'pork', 'boiled', 20, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{gluten,soy}', '{sarawak,dry_noodle,char_siu}', 85),
('MAL_HOKKIEN_MEE', 'hokkien-mee-kl', 'Hokkien Mee', 'Hokkien Mee', 'KL-style dark braised noodles in thick soy sauce gravy with pork, prawns, squid, and pork lard cracklings', 'noodles', 'kuala_lumpur', 'classic', 'mixed', 'braised', 45, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{shellfish,gluten,soy}', '{dark_sauce,braised,pork}', 82),
('MAL_PAN_MEE', 'pan-mee', 'Pan Mee', 'Pan Mee', 'Hand-torn flour noodles served in anchovy broth with minced pork, fried anchovies, leafy greens, and poached egg', 'noodles', 'kuala_lumpur', 'classic', 'pork', 'boiled', 30, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{gluten,fish,eggs}', '{handmade,soup,comfort_food}', 80),
('MAL_MEE_REBUS', 'mee-rebus', 'Mee Rebus', 'Mee Rebus', 'Yellow noodles in a thick, sweet potato-thickened gravy, topped with hard-boiled egg, tofu, bean sprouts, and green chilies', 'noodles', 'nationwide', 'classic', 'beef', 'boiled', 50, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,soy,eggs}', '{gravy,mamak,comfort_food}', 78),
('MAL_SATAY_AYAM', 'satay-ayam', 'Chicken Satay', 'Satay Ayam', 'Marinated chicken skewers grilled over charcoal, served with peanut sauce, ketupat (rice cakes), cucumber, and onions', 'satay', 'nationwide', 'iconic', 'chicken', 'grilled', 45, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": false, "is_halal": true, "is_kosher": false}'::jsonb, '{peanuts}', '{street_food,skewers,charcoal_grilled,national_dish}', 96),
('MAL_SATAY_DAGING', 'satay-daging', 'Beef Satay', 'Satay Daging', 'Tender beef skewers marinated in a blend of spices and grilled, served with classic peanut dipping sauce', 'satay', 'nationwide', 'iconic', 'beef', 'grilled', 50, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": false, "is_halal": true, "is_kosher": false}'::jsonb, '{peanuts}', '{street_food,skewers,charcoal_grilled}', 90),
('MAL_SATAY_CELUP', 'satay-celup', 'Satay Celup', 'Satay Celup', 'Malacca specialty where raw ingredients on skewers are dipped into a communal pot of simmering satay peanut sauce', 'satay', 'malacca', 'iconic', 'mixed', 'simmered', 20, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": false, "is_halal": false, "is_kosher": false}'::jsonb, '{peanuts,shellfish,soy}', '{malacca,hotpot_style,interactive,communal}', 88),
('MAL_SATAY_KAJANG', 'satay-kajang', 'Satay Kajang', 'Satay Kajang', 'Famous satay from Kajang town known for its larger, juicier pieces and sweeter peanut sauce', 'satay', 'kuala_lumpur', 'regional', 'mixed', 'grilled', 50, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": false, "is_halal": true, "is_kosher": false}'::jsonb, '{peanuts}', '{kajang,famous_street_food,larger_portions}', 84),
('MAL_AYAM_PERCIK', 'ayam-percik', 'Ayam Percik', 'Ayam Percik', 'Kelantan-style grilled chicken marinated in coconut milk and spices, slowly grilled while basted with the marinade', 'satay', 'kelantan', 'iconic', 'chicken', 'grilled', 90, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{kelantan,charcoal_grilled,coconut,slow_cooked}', 86),
('MAL_IKAN_BAKAR', 'ikan-bakar', 'Ikan Bakar', 'Ikan Bakar', 'Malaysian-style grilled fish marinated in a sambal paste, wrapped in banana leaves and grilled over charcoal', 'satay', 'nationwide', 'classic', 'fish', 'grilled', 40, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish}', '{seafood,charcoal_grilled,banana_leaf}', 82),
('MAL_KARI_AYAM', 'kari-ayam', 'Malaysian Chicken Curry', 'Kari Ayam', 'Rich chicken curry cooked with Malaysian curry powder, coconut milk, potatoes, and aromatic spices, often served with roti canai', 'curry', 'nationwide', 'iconic', 'chicken', 'braised', 60, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{curry,coconut,comfort_food,mamak}', 92),
('MAL_KARI_IKAN', 'kari-ikan', 'Fish Head Curry', 'Kari Kepala Ikan', 'Famous Malaysian-Indian curry with a large fish head cooked in tangy tamarind and coconut curry sauce with vegetables', 'curry', 'kuala_lumpur', 'iconic', 'fish', 'braised', 50, 4, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish}', '{fish_head,tamarind,sour,indian_influence}', 85),
('MAL_RENDANG_DAGING', 'rendang-daging', 'Beef Rendang', 'Rendang Daging', 'Slow-cooked dry beef curry with rich coconut milk, lemongrass, galangal, and a complex spice paste until the meat is tender and caramelized', 'curry', 'nationwide', 'iconic', 'beef', 'braised', 180, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{dry_curry,slow_cooked,festive,world_famous}', 96),
('MAL_RENDANG_AYAM', 'rendang-ayam', 'Chicken Rendang', 'Rendang Ayam', 'Classic dry chicken curry cooked in coconut milk until the sauce is absorbed and the chicken is coated in aromatic spices', 'curry', 'nationwide', 'classic', 'chicken', 'braised', 90, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{dry_curry,festive,comfort_food}', 88),
('MAL_GULAI_KAWAH', 'gulai-kawah', 'Gulai Kawah', 'Gulai Kawah', 'Northern Malaysian curry cooked in a large wok (kawah) with mutton, beef, or offal in a rich coconut curry base', 'curry', 'kelantan', 'traditional', 'beef', 'braised', 120, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{kelantan,festive,large_pot,communal}', 75),
('MAL_CURRY_KAPITAN', 'curry-kapitan', 'Curry Kapitan', 'Kari Kapitan', 'Penang Nyonya-style dry chicken curry with a tangy tamarind undertone and candlenuts for richness', 'curry', 'penang', 'classic', 'chicken', 'braised', 60, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": false, "is_halal": true, "is_kosher": false}'::jsonb, '{tree_nuts}', '{nyonya,penang,tamarind,peranakan}', 80),
('MAL_BAK_KUT_TEH', 'bak-kut-teh', 'Bak Kut Teh', 'Bak Kut Teh', 'Hokkien-style pork ribs soup simmered with Chinese herbs, garlic, and spices, served with rice and you tiao', 'soup', 'kuala_lumpur', 'iconic', 'pork', 'simmered', 120, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}'::jsonb, '{soy,gluten}', '{herbal,chinese,breakfast,comfort_food}', 90),
('MAL_SUP_KAMBING', 'sup-kambing', 'Mutton Soup', 'Sup Kambing', 'Aromatic mutton soup with bone-in mutton, celery, carrots, and Indian spices, served with bread for dipping', 'soup', 'nationwide', 'classic', 'lamb', 'simmered', 90, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{mamak,warming,late_night}', 82),
('MAL_SUP_TULANG', 'sup-tulang', 'Sup Tulang', 'Sup Tulang', 'Spicy bone marrow soup where beef or mutton bones are simmered and the marrow is sucked out, popular late-night street food', 'soup', 'kuala_lumpur', 'classic', 'beef', 'simmered', 120, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{bone_marrow,late_night,street_food}', 78),
('MAL_TOM_YAM_SEAFOOD', 'tom-yam-seafood-malaysian', 'Malaysian Tom Yam', 'Tom Yam', 'Malaysian version of tom yam soup with a creamier, spicier broth loaded with seafood, mushrooms, and aromatic herbs', 'soup', 'nationwide', 'classic', 'seafood', 'boiled', 30, 4, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish,dairy}', '{thai_influenced,spicy,sour,seafood}', 85),
('MAL_SOTO_AYAM', 'soto-ayam-malaysia', 'Soto Ayam', 'Soto Ayam', 'Indonesian-influenced yellow turmeric chicken soup with glass noodles, boiled egg, potato, and fried shallots', 'soup', 'nationwide', 'classic', 'chicken', 'simmered', 60, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{eggs}', '{javanese,turmeric,comfort_food}', 80),
('MAL_NASI_GORENG_KAMPUNG', 'nasi-goreng-kampung', 'Kampung Fried Rice', 'Nasi Goreng Kampung', 'Village-style fried rice with ikan bilis (dried anchovies), local vegetables, and sambal belacan for authentic Malaysian flavor', 'fried', 'nationwide', 'iconic', 'fish', 'stir_fried', 20, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish,shellfish}', '{village_style,street_food,authentic}', 88),
('MAL_MEE_GORENG_MAMAK', 'mee-goreng-mamak', 'Mee Goreng Mamak', 'Mee Goreng Mamak', 'Indian-Muslim style fried noodles with a sweet and spicy tomato-based sauce, tofu, potato, and egg', 'fried', 'nationwide', 'iconic', 'egg', 'stir_fried', 15, 2, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,soy,eggs}', '{mamak,street_food,late_night}', 90),
('MAL_AYAM_GORENG', 'ayam-goreng-berempah', 'Spiced Fried Chicken', 'Ayam Goreng Berempah', 'Malaysian-style fried chicken marinated with turmeric and spices, deep-fried until golden and crispy', 'fried', 'nationwide', 'classic', 'chicken', 'deep_fried', 45, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{}', '{fried_chicken,turmeric,crispy}', 85),
('MAL_KANGKONG_BELACAN', 'kangkong-belacan', 'Water Spinach with Shrimp Paste', 'Kangkong Belacan', 'Stir-fried water spinach with sambal belacan (shrimp paste chili), a ubiquitous vegetable dish in Malaysia', 'fried', 'nationwide', 'classic', 'vegetable', 'stir_fried', 10, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish}', '{vegetable,side_dish,sambal}', 82),
('MAL_SAMBAL_UDANG', 'sambal-udang', 'Sambal Prawns', 'Sambal Udang', 'Prawns cooked in a rich, spicy sambal sauce with shrimp paste, chilies, and tamarind, a classic Malay dish', 'fried', 'nationwide', 'classic', 'shrimp', 'stir_fried', 25, 4, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish}', '{sambal,seafood,spicy}', 80),
('MAL_SAMBAL_PETAI', 'sambal-petai', 'Sambal Petai', 'Sambal Petai Udang', 'Stir-fried stink beans with prawns in a fiery sambal paste, an acquired taste loved by Malaysians', 'fried', 'nationwide', 'traditional', 'shrimp', 'stir_fried', 20, 4, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish}', '{petai,stink_beans,pungent,unique}', 72),
('MAL_ROTI_CANAI', 'roti-canai', 'Roti Canai', 'Roti Canai', 'Malaysian flaky flatbread of Indian origin, made by stretching and folding dough, served with dhal curry and sambal', 'bread', 'nationwide', 'iconic', 'none', 'pan_fried', 30, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,dairy}', '{breakfast,street_food,mamak,worlds_best_bread}', 98),
('MAL_ROTI_TELUR', 'roti-telur', 'Roti Telur', 'Roti Telur', 'Roti canai stuffed with beaten egg, folded and pan-fried until crispy with a soft egg center', 'bread', 'nationwide', 'iconic', 'egg', 'pan_fried', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,eggs,dairy}', '{breakfast,mamak,egg_stuffed}', 92),
('MAL_ROTI_PISANG', 'roti-pisang', 'Roti Pisang', 'Roti Pisang', 'Sweet version of roti canai filled with sliced banana, sprinkled with sugar or condensed milk', 'bread', 'nationwide', 'classic', 'none', 'pan_fried', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,dairy}', '{sweet,dessert,banana}', 85),
('MAL_ROTI_TISSUE', 'roti-tissue', 'Roti Tissue', 'Roti Tisu', 'Paper-thin crispy roti formed into a tall cone, drizzled with condensed milk and sugar, more of a dessert', 'bread', 'nationwide', 'classic', 'none', 'pan_fried', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,dairy}', '{crispy,sweet,show_piece}', 82),
('MAL_MURTABAK', 'murtabak', 'Murtabak', 'Murtabak', 'Stuffed pan-fried bread with spiced minced meat, onions, and egg, served with curry sauce and pickled onions', 'bread', 'nationwide', 'iconic', 'beef', 'pan_fried', 35, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,eggs,dairy}', '{stuffed,mamak,filling}', 88),
('MAL_ROTI_JOHN', 'roti-john', 'Roti John', 'Roti John', 'Malaysian-style sandwich with minced meat and egg mixture cooked on a split baguette, drizzled with chili and mayonnaise', 'bread', 'kuala_lumpur', 'classic', 'beef', 'pan_fried', 15, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,eggs,dairy}', '{street_food,sandwich,unique}', 78),
('MAL_UDANG_GALAH', 'udang-galah', 'Giant River Prawn', 'Udang Galah Bakar', 'Grilled giant freshwater prawns basted with butter and garlic, a premium seafood dish', 'seafood', 'nationwide', 'classic', 'shrimp', 'grilled', 30, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish,dairy}', '{premium,grilled,river_prawn}', 82),
('MAL_CHILI_CRAB', 'chili-crab-malaysian', 'Malaysian Chili Crab', 'Ketam Cili', 'Mud crab cooked in a sweet and spicy tomato-chili sauce, a Malaysian interpretation of the famous dish', 'seafood', 'kuala_lumpur', 'classic', 'crab', 'stir_fried', 40, 3, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish,eggs}', '{crab,spicy,premium}', 85),
('MAL_BUTTER_PRAWN', 'butter-prawn', 'Butter Prawns', 'Udang Butter', 'Crispy fried prawns coated in a buttery sauce with curry leaves and chili padi for a sweet-savory taste', 'seafood', 'kuala_lumpur', 'classic', 'shrimp', 'deep_fried', 25, 2, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish,dairy,eggs}', '{butter,crispy,curry_leaf}', 88),
('MAL_SIAKAP_SWEET_SOUR', 'siakap-sweet-sour', 'Sweet and Sour Sea Bass', 'Siakap Masam Manis', 'Whole fried sea bass topped with a tangy sweet and sour sauce, colorful vegetables, and pineapple', 'seafood', 'nationwide', 'classic', 'fish', 'deep_fried', 35, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish,soy}', '{sweet_sour,whole_fish,banquet}', 80),
('MAL_STEAMED_FISH', 'ikan-stim-limau', 'Lime Steamed Fish', 'Ikan Stim Limau', 'Whole fish steamed with lime juice, garlic, and ginger, finished with hot oil and soy sauce', 'seafood', 'nationwide', 'classic', 'fish', 'steamed', 25, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{fish,soy}', '{healthy,light,chinese_style}', 78),
('MAL_SOTONG_GORENG', 'sotong-goreng-tepung', 'Fried Squid', 'Sotong Goreng Tepung', 'Crispy battered squid rings deep-fried to golden perfection, served with chili sauce', 'seafood', 'nationwide', 'classic', 'squid', 'deep_fried', 20, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{shellfish,gluten}', '{crispy,appetizer,street_food}', 82),
('MAL_CENDOL', 'cendol', 'Cendol', 'Cendol', 'Iconic Malaysian dessert with green pandan jelly noodles, coconut milk, palm sugar syrup, and shaved ice', 'desserts', 'penang', 'iconic', 'none', 'chilled', 30, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{}', '{iced_dessert,pandan,palm_sugar,refreshing}', 95),
('MAL_ABC', 'ais-batu-campur', 'Ais Batu Campur', 'ABC', 'Malaysian shaved ice dessert loaded with sweet corn, red beans, grass jelly, and colorful syrups topped with evaporated milk', 'desserts', 'nationwide', 'iconic', 'none', 'chilled', 15, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}'::jsonb, '{dairy}', '{shaved_ice,colorful,refreshing}', 90),
('MAL_KUIH_LAPIS', 'kuih-lapis', 'Kuih Lapis', 'Kuih Lapis', 'Traditional steamed layer cake with alternating colored layers, made from rice flour, coconut milk, and sugar', 'desserts', 'nationwide', 'traditional', 'none', 'steamed', 90, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{}', '{kuih,festive,colorful,steamed}', 82),
('MAL_ONDEH_ONDEH', 'ondeh-ondeh', 'Ondeh Ondeh', 'Onde Onde', 'Chewy pandan-flavored glutinous rice balls filled with liquid palm sugar, coated in fresh grated coconut', 'desserts', 'malacca', 'iconic', 'none', 'boiled', 45, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{}', '{kuih,pandan,palm_sugar,nyonya}', 88),
('MAL_AGAR_AGAR', 'agar-agar-santan', 'Coconut Agar Jelly', 'Agar-Agar Santan', 'Layered coconut milk jelly set with agar-agar, often colored and served at festive occasions', 'desserts', 'nationwide', 'traditional', 'none', 'chilled', 60, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{}', '{jelly,festive,colorful}', 75),
('MAL_SAGO_GULA_MELAKA', 'sago-gula-melaka', 'Sago Gula Melaka', 'Sago Gula Melaka', 'Chilled sago pearl pudding served with rich palm sugar syrup and creamy coconut milk', 'desserts', 'malacca', 'classic', 'none', 'chilled', 45, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{}', '{sago,palm_sugar,nyonya}', 85),
('MAL_PISANG_GORENG', 'pisang-goreng', 'Fried Banana Fritters', 'Pisang Goreng', 'Ripe bananas coated in a light batter and deep-fried until golden, a beloved Malaysian street snack', 'desserts', 'nationwide', 'iconic', 'none', 'deep_fried', 15, 0, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}'::jsonb, '{gluten}', '{street_food,fried,tea_time}', 92),
('MAL_APAM_BALIK', 'apam-balik', 'Apam Balik', 'Apam Balik', 'Crispy turnover pancake filled with peanuts, sugar, and creamy corn, a popular night market snack', 'desserts', 'nationwide', 'classic', 'none', 'pan_fried', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": false, "is_halal": true, "is_kosher": false}'::jsonb, '{gluten,peanuts,eggs}', '{pancake,night_market,crispy}', 85);

-- =====================================================
-- VERIFICATION
-- =====================================================
SELECT 'Malaysian dishes' AS status, COUNT(*) AS count FROM malaysian;
