-- ============================================
-- BREAKFAST - Complete Import (65 items)
-- ============================================
-- Run this SECOND after 01-breakfast-missing-ingredients.sql
-- Creates the breakfast table and imports all dishes
-- ============================================
-- DATABASE-STANDARDS v1.1 COMPLIANT
-- - TEXT + CHECK constraints (no ENUM)
-- - JSONB for arrays
-- - All dietary fields
-- ============================================

-- Drop existing table if needed (uncomment if reimporting)
-- DROP TABLE IF EXISTS breakfast CASCADE;

-- Create the breakfast table
CREATE TABLE IF NOT EXISTS breakfast (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,

  -- Classification (TEXT + CHECK)
  category TEXT NOT NULL CHECK (category IN ('eggs', 'pancakes_waffles', 'pastries', 'cereals_bowls', 'savory', 'international')),
  origin TEXT NOT NULL CHECK (origin IN ('american', 'british', 'french', 'italian', 'spanish', 'german', 'japanese', 'korean', 'chinese', 'mexican', 'middle_eastern', 'israeli', 'turkish', 'brazilian', 'australian', 'scandinavian', 'indian', 'international')),
  meal_time TEXT NOT NULL CHECK (meal_time IN ('early_breakfast', 'breakfast', 'brunch', 'all_day')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'classic', 'popular', 'signature', 'seasonal', 'premium', 'traditional', 'trending', 'iconic')),

  -- Ingredients
  ingredient_ids JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Sistema 5 Dimensioni - Allergens
  allergens JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Sistema 5 Dimensioni - Dietary
  is_gluten_free BOOLEAN NOT NULL DEFAULT false,
  is_dairy_free BOOLEAN NOT NULL DEFAULT false,
  is_nut_free BOOLEAN NOT NULL DEFAULT true,
  is_vegan BOOLEAN NOT NULL DEFAULT false,
  is_vegetarian BOOLEAN NOT NULL DEFAULT false,
  is_halal BOOLEAN NOT NULL DEFAULT true,
  is_kosher BOOLEAN NOT NULL DEFAULT true,

  -- Sistema 5 Dimensioni - Nutrition
  calories_per_serving INTEGER,
  protein_g INTEGER,
  carbs_g INTEGER,
  fat_g INTEGER,

  -- Sistema 5 Dimensioni - Spice
  spice_level INTEGER NOT NULL DEFAULT 0 CHECK (spice_level >= 0 AND spice_level <= 5),

  -- Metadata
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  popularity INTEGER NOT NULL DEFAULT 50 CHECK (popularity >= 0 AND popularity <= 100),

  -- Optional fields
  serving_size_g INTEGER,
  prep_time_minutes INTEGER,
  is_sweet BOOLEAN NOT NULL DEFAULT false,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_breakfast_category ON breakfast(category);
CREATE INDEX IF NOT EXISTS idx_breakfast_origin ON breakfast(origin);
CREATE INDEX IF NOT EXISTS idx_breakfast_meal_time ON breakfast(meal_time);
CREATE INDEX IF NOT EXISTS idx_breakfast_popularity ON breakfast(popularity DESC);
CREATE INDEX IF NOT EXISTS idx_breakfast_is_sweet ON breakfast(is_sweet);

-- ============================================
-- EGGS CATEGORY (10 items)
-- ============================================
INSERT INTO breakfast (id, slug, name, description, category, origin, meal_time, status, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity, serving_size_g, prep_time_minutes, is_sweet) VALUES
('BRK_EGGS_BENEDICT', 'eggs-benedict', 'Eggs Benedict', 'Poached eggs on toasted English muffin with Canadian bacon, topped with silky hollandaise sauce. The quintessential brunch classic.', 'eggs', 'american', 'brunch', 'classic', '["ING_EGG", "ING_ENGLISH_MUFFIN", "ING_CANADIAN_BACON", "ING_BUTTER", "ING_LEMON", "ING_EGG_YOLK", "ING_CHIVES"]'::jsonb, '["eggs", "gluten", "milk"]'::jsonb, false, false, true, false, false, false, false, 550, 25, 28, 38, 0, '["brunch", "classic", "hollandaise", "poached-eggs"]'::jsonb, 95, 280, 25, false),
('BRK_EGGS_FLORENTINE', 'eggs-florentine', 'Eggs Florentine', 'Vegetarian variation of Eggs Benedict with wilted spinach instead of bacon, topped with creamy hollandaise on an English muffin.', 'eggs', 'american', 'brunch', 'popular', '["ING_EGG", "ING_ENGLISH_MUFFIN", "ING_SPINACH", "ING_BUTTER", "ING_LEMON", "ING_EGG_YOLK", "ING_NUTMEG"]'::jsonb, '["eggs", "gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 480, 20, 28, 32, 0, '["brunch", "vegetarian", "spinach", "hollandaise"]'::jsonb, 85, 260, 25, false),
('BRK_EGGS_ROYALE', 'eggs-royale', 'Eggs Royale', 'Luxurious Eggs Benedict variation with smoked salmon replacing the bacon. A brunch favorite with Scottish roots.', 'eggs', 'british', 'brunch', 'premium', '["ING_EGG", "ING_ENGLISH_MUFFIN", "ING_SMOKED_SALMON", "ING_BUTTER", "ING_LEMON", "ING_EGG_YOLK", "ING_DILL"]'::jsonb, '["eggs", "gluten", "milk", "fish"]'::jsonb, false, false, true, false, false, true, false, 520, 28, 26, 35, 0, '["brunch", "premium", "salmon", "scottish"]'::jsonb, 88, 270, 25, false),
('BRK_OMELETTE_WESTERN', 'western-omelette', 'Western Omelette', 'Classic American omelette filled with diced ham, bell peppers, onions, and cheddar cheese. Hearty and satisfying.', 'eggs', 'american', 'breakfast', 'classic', '["ING_EGG", "ING_HAM", "ING_BELL_PEPPER", "ING_ONION", "ING_CHEDDAR", "ING_BUTTER", "ING_BLACK_PEPPER"]'::jsonb, '["eggs", "milk"]'::jsonb, true, false, true, false, false, false, false, 420, 28, 6, 32, 0, '["american", "diner", "classic", "hearty"]'::jsonb, 88, 250, 15, false),
('BRK_OMELETTE_FRENCH', 'french-omelette', 'French Omelette', 'Elegant, soft-folded omelette with a creamy, barely-set center. The ultimate test of a chef''s skill, finished with fresh herbs.', 'eggs', 'french', 'breakfast', 'classic', '["ING_EGG", "ING_BUTTER", "ING_CHIVES", "ING_SALT", "ING_WHITE_PEPPER"]'::jsonb, '["eggs", "milk"]'::jsonb, true, false, true, false, true, true, true, 280, 18, 2, 22, 0, '["french", "technique", "elegant", "classic"]'::jsonb, 80, 180, 10, false),
('BRK_SCRAMBLED_EGGS', 'scrambled-eggs', 'Scrambled Eggs', 'Soft, creamy scrambled eggs cooked low and slow with butter. Simple perfection, the foundation of breakfast.', 'eggs', 'international', 'breakfast', 'classic', '["ING_EGG", "ING_BUTTER", "ING_CREAM", "ING_CHIVES", "ING_SALT", "ING_BLACK_PEPPER"]'::jsonb, '["eggs", "milk"]'::jsonb, true, false, true, false, true, true, true, 220, 14, 2, 18, 0, '["classic", "simple", "comfort", "versatile"]'::jsonb, 92, 150, 8, false),
('BRK_SHAKSHUKA', 'shakshuka', 'Shakshuka', 'North African and Middle Eastern dish of eggs poached in spiced tomato and pepper sauce. Served sizzling in the skillet with crusty bread.', 'eggs', 'middle_eastern', 'brunch', 'popular', '["ING_EGG", "ING_TOMATO", "ING_BELL_PEPPER", "ING_ONION", "ING_GARLIC", "ING_CUMIN", "ING_PAPRIKA", "ING_CHILI_FLAKES", "ING_OLIVE_OIL", "ING_FETA"]'::jsonb, '["eggs", "milk"]'::jsonb, true, false, true, false, true, true, true, 320, 18, 18, 22, 2, '["middle-eastern", "israeli", "spiced", "one-pan"]'::jsonb, 88, 350, 30, false),
('BRK_HUEVOS_RANCHEROS', 'huevos-rancheros', 'Huevos Rancheros', 'Mexican ranch-style eggs: fried eggs on corn tortillas topped with salsa roja, refried beans, avocado, and crumbled queso fresco.', 'eggs', 'mexican', 'breakfast', 'classic', '["ING_EGG", "ING_CORN_TORTILLA", "ING_SALSA_ROJA", "ING_REFRIED_BEANS", "ING_AVOCADO", "ING_QUESO_FRESCO", "ING_CILANTRO", "ING_LIME"]'::jsonb, '["eggs", "milk"]'::jsonb, true, false, true, false, true, true, true, 450, 22, 35, 26, 2, '["mexican", "hearty", "spicy", "traditional"]'::jsonb, 90, 380, 20, false),
('BRK_TAMAGOYAKI', 'tamagoyaki', 'Tamagoyaki', 'Japanese rolled omelette made by layering thin sheets of seasoned egg. Slightly sweet, served in traditional bento or as breakfast side.', 'eggs', 'japanese', 'breakfast', 'traditional', '["ING_EGG", "ING_DASHI", "ING_SOY_SAUCE", "ING_MIRIN", "ING_SUGAR", "ING_VEGETABLE_OIL"]'::jsonb, '["eggs", "soy", "fish"]'::jsonb, true, true, true, false, false, true, false, 180, 12, 6, 12, 0, '["japanese", "bento", "technique", "umami"]'::jsonb, 75, 120, 15, true),
('BRK_EGGS_EN_COCOTTE', 'eggs-en-cocotte', 'Eggs en Cocotte', 'French baked eggs in individual ramekins with cream, herbs, and optional toppings like mushrooms or smoked salmon. Elegant and custardy.', 'eggs', 'french', 'brunch', 'premium', '["ING_EGG", "ING_CREAM", "ING_BUTTER", "ING_CHIVES", "ING_GRUYERE", "ING_BLACK_PEPPER", "ING_NUTMEG"]'::jsonb, '["eggs", "milk"]'::jsonb, true, false, true, false, true, true, true, 320, 16, 4, 28, 0, '["french", "baked", "elegant", "brunch"]'::jsonb, 72, 180, 20, false)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- PANCAKES & WAFFLES CATEGORY (10 items)
-- ============================================
INSERT INTO breakfast (id, slug, name, description, category, origin, meal_time, status, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity, serving_size_g, prep_time_minutes, is_sweet) VALUES
('BRK_AMERICAN_PANCAKES', 'american-pancakes', 'American Pancakes', 'Fluffy buttermilk pancakes stacked high, served with butter and maple syrup. The iconic American breakfast.', 'pancakes_waffles', 'american', 'breakfast', 'iconic', '["ING_FLOUR", "ING_BUTTERMILK", "ING_EGG", "ING_BUTTER", "ING_BAKING_POWDER", "ING_SUGAR", "ING_MAPLE_SYRUP", "ING_SALT"]'::jsonb, '["gluten", "eggs", "milk"]'::jsonb, false, false, true, false, true, true, true, 520, 12, 68, 22, 0, '["american", "iconic", "sweet", "maple-syrup"]'::jsonb, 96, 300, 20, true),
('BRK_BLUEBERRY_PANCAKES', 'blueberry-pancakes', 'Blueberry Pancakes', 'Fluffy American pancakes studded with fresh blueberries, bursting with sweetness. Topped with whipped cream and extra berries.', 'pancakes_waffles', 'american', 'breakfast', 'popular', '["ING_FLOUR", "ING_BUTTERMILK", "ING_EGG", "ING_BUTTER", "ING_BLUEBERRIES", "ING_MAPLE_SYRUP", "ING_WHIPPED_CREAM", "ING_SUGAR"]'::jsonb, '["gluten", "eggs", "milk"]'::jsonb, false, false, true, false, true, true, true, 580, 12, 78, 24, 0, '["american", "berries", "sweet", "popular"]'::jsonb, 92, 340, 25, true),
('BRK_BELGIAN_WAFFLES', 'belgian-waffles', 'Belgian Waffles', 'Light and crispy waffles with deep pockets, made with yeast for extra airiness. Served with fresh strawberries and whipped cream.', 'pancakes_waffles', 'international', 'brunch', 'classic', '["ING_FLOUR", "ING_MILK", "ING_EGG", "ING_BUTTER", "ING_YEAST", "ING_SUGAR", "ING_STRAWBERRIES", "ING_WHIPPED_CREAM", "ING_POWDERED_SUGAR"]'::jsonb, '["gluten", "eggs", "milk"]'::jsonb, false, false, true, false, true, true, true, 480, 10, 58, 24, 0, '["belgian", "crispy", "brunch", "berries"]'::jsonb, 90, 280, 30, true),
('BRK_FRENCH_TOAST', 'french-toast', 'French Toast', 'Thick slices of brioche bread soaked in vanilla custard and pan-fried golden. Dusted with cinnamon sugar and served with maple syrup.', 'pancakes_waffles', 'french', 'brunch', 'classic', '["ING_BRIOCHE", "ING_EGG", "ING_MILK", "ING_VANILLA", "ING_CINNAMON", "ING_BUTTER", "ING_MAPLE_SYRUP", "ING_POWDERED_SUGAR"]'::jsonb, '["gluten", "eggs", "milk"]'::jsonb, false, false, true, false, true, true, true, 520, 14, 62, 26, 0, '["french", "brioche", "vanilla", "cinnamon"]'::jsonb, 94, 280, 20, true),
('BRK_CREPES_SUZETTE', 'crepes-suzette', 'Crepes Suzette', 'Thin French crepes flambéed in orange butter sauce with Grand Marnier. An elegant, theatrical dessert-breakfast hybrid.', 'pancakes_waffles', 'french', 'brunch', 'premium', '["ING_FLOUR", "ING_EGG", "ING_MILK", "ING_BUTTER", "ING_ORANGE", "ING_ORANGE_LIQUEUR", "ING_SUGAR", "ING_ORANGE_ZEST"]'::jsonb, '["gluten", "eggs", "milk", "alcohol"]'::jsonb, false, false, true, false, true, false, true, 380, 8, 42, 20, 0, '["french", "flambeed", "orange", "elegant"]'::jsonb, 78, 200, 25, true),
('BRK_CREPES_NUTELLA', 'crepes-nutella', 'Nutella Crepes', 'Delicate French crepes spread with Nutella and topped with fresh banana slices, whipped cream, and a dusting of powdered sugar.', 'pancakes_waffles', 'french', 'breakfast', 'popular', '["ING_FLOUR", "ING_EGG", "ING_MILK", "ING_BUTTER", "ING_NUTELLA", "ING_BANANA", "ING_WHIPPED_CREAM", "ING_POWDERED_SUGAR"]'::jsonb, '["gluten", "eggs", "milk", "nuts"]'::jsonb, false, false, false, false, true, true, true, 480, 10, 58, 24, 0, '["french", "nutella", "banana", "indulgent"]'::jsonb, 92, 250, 15, true),
('BRK_DUTCH_BABY', 'dutch-baby', 'Dutch Baby Pancake', 'Dramatic oven-baked German pancake that puffs up dramatically. Served with lemon juice, powdered sugar, and fresh berries.', 'pancakes_waffles', 'german', 'brunch', 'signature', '["ING_FLOUR", "ING_EGG", "ING_MILK", "ING_BUTTER", "ING_VANILLA", "ING_LEMON", "ING_POWDERED_SUGAR", "ING_MIXED_BERRIES"]'::jsonb, '["gluten", "eggs", "milk"]'::jsonb, false, false, true, false, true, true, true, 420, 12, 48, 22, 0, '["german", "oven-baked", "dramatic", "lemon"]'::jsonb, 80, 300, 30, true),
('BRK_JAPANESE_SOUFFLE_PANCAKES', 'japanese-souffle-pancakes', 'Japanese Souffle Pancakes', 'Ultra-fluffy, jiggly Japanese pancakes made with whipped meringue. Cloud-like texture, served with butter and maple syrup.', 'pancakes_waffles', 'japanese', 'brunch', 'trending', '["ING_EGG", "ING_FLOUR", "ING_MILK", "ING_SUGAR", "ING_BAKING_POWDER", "ING_VANILLA", "ING_BUTTER", "ING_WHIPPED_CREAM"]'::jsonb, '["gluten", "eggs", "milk"]'::jsonb, false, false, true, false, true, true, true, 380, 10, 42, 20, 0, '["japanese", "fluffy", "trending", "instagram"]'::jsonb, 88, 220, 35, true),
('BRK_BANANA_PANCAKES', 'banana-pancakes', 'Banana Pancakes', 'Fluffy pancakes with mashed banana in the batter, topped with sliced bananas, walnuts, and a drizzle of honey.', 'pancakes_waffles', 'american', 'breakfast', 'popular', '["ING_FLOUR", "ING_BANANA", "ING_EGG", "ING_BUTTERMILK", "ING_BUTTER", "ING_WALNUTS", "ING_HONEY", "ING_CINNAMON"]'::jsonb, '["gluten", "eggs", "milk", "nuts"]'::jsonb, false, false, false, false, true, true, true, 520, 14, 65, 24, 0, '["american", "banana", "honey", "walnuts"]'::jsonb, 86, 320, 20, true),
('BRK_CHICKEN_WAFFLES', 'chicken-and-waffles', 'Chicken and Waffles', 'Southern soul food classic: crispy fried chicken served on a fluffy waffle, drizzled with maple syrup and hot sauce. Sweet meets savory.', 'pancakes_waffles', 'american', 'brunch', 'signature', '["ING_CHICKEN_BREAST", "ING_FLOUR", "ING_BUTTERMILK", "ING_EGG", "ING_BUTTER", "ING_MAPLE_SYRUP", "ING_HOT_SAUCE", "ING_PAPRIKA"]'::jsonb, '["gluten", "eggs", "milk"]'::jsonb, false, false, true, false, false, true, false, 780, 38, 62, 42, 1, '["southern", "soul-food", "fried-chicken", "sweet-savory"]'::jsonb, 88, 420, 40, false)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- PASTRIES CATEGORY (10 items)
-- ============================================
INSERT INTO breakfast (id, slug, name, description, category, origin, meal_time, status, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity, serving_size_g, prep_time_minutes, is_sweet) VALUES
('BRK_CROISSANT', 'croissant', 'Butter Croissant', 'Classic French laminated pastry with 27 layers of butter-folded dough. Golden, flaky exterior with a soft, airy interior.', 'pastries', 'french', 'breakfast', 'classic', '["ING_FLOUR", "ING_BUTTER", "ING_MILK", "ING_YEAST", "ING_SUGAR", "ING_SALT", "ING_EGG"]'::jsonb, '["gluten", "milk", "eggs"]'::jsonb, false, false, true, false, true, true, true, 280, 5, 32, 15, 0, '["french", "flaky", "laminated", "classic"]'::jsonb, 96, 75, 5, false),
('BRK_PAIN_AU_CHOCOLAT', 'pain-au-chocolat', 'Pain au Chocolat', 'Rectangular croissant dough wrapped around two bars of dark chocolate. The quintessential French chocolate pastry.', 'pastries', 'french', 'breakfast', 'classic', '["ING_FLOUR", "ING_BUTTER", "ING_MILK", "ING_YEAST", "ING_SUGAR", "ING_DARK_CHOCOLATE", "ING_EGG"]'::jsonb, '["gluten", "milk", "eggs"]'::jsonb, false, false, true, false, true, true, true, 340, 6, 38, 18, 0, '["french", "chocolate", "pastry", "indulgent"]'::jsonb, 94, 85, 5, true),
('BRK_ALMOND_CROISSANT', 'almond-croissant', 'Almond Croissant', 'Day-old croissant filled with frangipane almond cream, topped with sliced almonds and powdered sugar. Twice-baked to perfection.', 'pastries', 'french', 'brunch', 'premium', '["ING_FLOUR", "ING_BUTTER", "ING_ALMONDS", "ING_ALMOND_FLOUR", "ING_SUGAR", "ING_EGG", "ING_POWDERED_SUGAR"]'::jsonb, '["gluten", "milk", "eggs", "nuts"]'::jsonb, false, false, false, false, true, true, true, 420, 10, 42, 26, 0, '["french", "almond", "frangipane", "premium"]'::jsonb, 88, 100, 5, true),
('BRK_DANISH_PASTRY', 'danish-pastry', 'Danish Pastry', 'Flaky Viennese-style pastry with fruit filling or custard center. Glazed with sweet icing, a Scandinavian breakfast staple.', 'pastries', 'scandinavian', 'breakfast', 'classic', '["ING_FLOUR", "ING_BUTTER", "ING_SUGAR", "ING_EGG", "ING_YEAST", "ING_VANILLA_CUSTARD", "ING_POWDERED_SUGAR"]'::jsonb, '["gluten", "milk", "eggs"]'::jsonb, false, false, true, false, true, true, true, 320, 5, 38, 17, 0, '["danish", "fruit", "custard", "glazed"]'::jsonb, 82, 90, 5, true),
('BRK_CINNAMON_ROLL', 'cinnamon-roll', 'Cinnamon Roll', 'Soft, yeasted dough rolled with cinnamon-sugar filling, topped with cream cheese frosting. A beloved American and Swedish classic.', 'pastries', 'scandinavian', 'breakfast', 'popular', '["ING_FLOUR", "ING_BUTTER", "ING_SUGAR", "ING_CINNAMON", "ING_YEAST", "ING_CREAM_CHEESE", "ING_MILK", "ING_EGG"]'::jsonb, '["gluten", "milk", "eggs"]'::jsonb, false, false, true, false, true, true, true, 420, 6, 58, 20, 0, '["cinnamon", "frosted", "comfort", "swedish"]'::jsonb, 92, 120, 5, true),
('BRK_BLUEBERRY_MUFFIN', 'blueberry-muffin', 'Blueberry Muffin', 'Tender, domed muffin bursting with fresh blueberries, topped with streusel crumble. A quintessential American breakfast treat.', 'pastries', 'american', 'breakfast', 'classic', '["ING_FLOUR", "ING_BUTTER", "ING_SUGAR", "ING_EGG", "ING_BLUEBERRIES", "ING_BUTTERMILK", "ING_BAKING_POWDER", "ING_VANILLA"]'::jsonb, '["gluten", "milk", "eggs"]'::jsonb, false, false, true, false, true, true, true, 380, 5, 52, 17, 0, '["american", "berries", "classic", "streusel"]'::jsonb, 88, 110, 5, true),
('BRK_ENGLISH_SCONE', 'english-scone', 'English Scone', 'Traditional British tea scone with a crumbly, tender texture. Served warm with clotted cream and strawberry jam.', 'pastries', 'british', 'brunch', 'traditional', '["ING_FLOUR", "ING_BUTTER", "ING_SUGAR", "ING_BAKING_POWDER", "ING_MILK", "ING_EGG", "ING_CLOTTED_CREAM", "ING_STRAWBERRY_JAM"]'::jsonb, '["gluten", "milk", "eggs"]'::jsonb, false, false, true, false, true, true, true, 340, 6, 42, 18, 0, '["british", "tea-time", "cream-tea", "traditional"]'::jsonb, 80, 100, 5, true),
('BRK_BRIOCHE', 'brioche', 'French Brioche', 'Rich, buttery French bread with a golden crust and soft, pillowy interior. Enhanced with eggs and butter for an indulgent texture.', 'pastries', 'french', 'breakfast', 'classic', '["ING_FLOUR", "ING_BUTTER", "ING_EGG", "ING_SUGAR", "ING_YEAST", "ING_MILK", "ING_SALT"]'::jsonb, '["gluten", "milk", "eggs"]'::jsonb, false, false, true, false, true, true, true, 260, 7, 28, 14, 0, '["french", "buttery", "enriched", "classic"]'::jsonb, 84, 70, 5, false),
('BRK_SFOGLIATELLA', 'sfogliatella', 'Sfogliatella', 'Neapolitan shell-shaped pastry with countless crispy layers filled with sweet ricotta, semolina, and candied citrus.', 'pastries', 'italian', 'breakfast', 'traditional', '["ING_FLOUR", "ING_LARD", "ING_RICOTTA", "ING_SEMOLINA", "ING_SUGAR", "ING_CANDIED_CITRUS", "ING_CINNAMON", "ING_VANILLA"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, false, false, 280, 6, 32, 15, 0, '["italian", "neapolitan", "ricotta", "crispy"]'::jsonb, 75, 80, 5, true),
('BRK_CHURROS', 'churros', 'Churros con Chocolate', 'Fried dough pastry coated in cinnamon-sugar, served with thick Spanish hot chocolate for dipping. A Madrid breakfast tradition.', 'pastries', 'spanish', 'breakfast', 'traditional', '["ING_FLOUR", "ING_VEGETABLE_OIL", "ING_SUGAR", "ING_CINNAMON", "ING_DARK_CHOCOLATE", "ING_MILK", "ING_SALT"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 420, 6, 52, 22, 0, '["spanish", "fried", "chocolate", "cinnamon"]'::jsonb, 88, 150, 10, true)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- CEREALS & BOWLS CATEGORY (10 items)
-- ============================================
INSERT INTO breakfast (id, slug, name, description, category, origin, meal_time, status, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity, serving_size_g, prep_time_minutes, is_sweet) VALUES
('BRK_ACAI_BOWL', 'acai-bowl', 'Acai Bowl', 'Brazilian superfood bowl made from frozen acai berry puree, topped with granola, fresh fruits, coconut, and honey drizzle.', 'cereals_bowls', 'brazilian', 'breakfast', 'trending', '["ING_ACAI", "ING_BANANA", "ING_GRANOLA", "ING_BLUEBERRIES", "ING_STRAWBERRIES", "ING_COCONUT_FLAKES", "ING_HONEY", "ING_ALMOND_MILK"]'::jsonb, '["nuts"]'::jsonb, true, true, false, true, true, true, true, 380, 8, 62, 12, 0, '["brazilian", "superfood", "healthy", "instagram"]'::jsonb, 92, 350, 10, true),
('BRK_SMOOTHIE_BOWL', 'smoothie-bowl', 'Green Smoothie Bowl', 'Thick blended smoothie bowl with spinach, banana, and mango base. Topped with chia seeds, kiwi, and granola.', 'cereals_bowls', 'american', 'breakfast', 'trending', '["ING_SPINACH", "ING_BANANA", "ING_MANGO", "ING_CHIA_SEEDS", "ING_GRANOLA", "ING_KIWI", "ING_ALMOND_MILK", "ING_HONEY"]'::jsonb, '["nuts"]'::jsonb, true, true, false, true, true, true, true, 340, 10, 58, 10, 0, '["healthy", "green", "vegan", "superfood"]'::jsonb, 85, 320, 10, true),
('BRK_OVERNIGHT_OATS', 'overnight-oats', 'Overnight Oats', 'No-cook oatmeal soaked overnight in milk with chia seeds. Layered with fresh berries, nut butter, and maple syrup.', 'cereals_bowls', 'international', 'breakfast', 'trending', '["ING_ROLLED_OATS", "ING_MILK", "ING_CHIA_SEEDS", "ING_MAPLE_SYRUP", "ING_MIXED_BERRIES", "ING_ALMOND_BUTTER", "ING_VANILLA"]'::jsonb, '["gluten", "milk", "nuts"]'::jsonb, false, false, false, false, true, true, true, 380, 14, 52, 14, 0, '["meal-prep", "healthy", "convenient", "cold"]'::jsonb, 88, 300, 5, true),
('BRK_STEEL_CUT_OATMEAL', 'steel-cut-oatmeal', 'Steel Cut Oatmeal', 'Hearty Irish-style oatmeal made from whole oat groats. Served with brown sugar, cinnamon, toasted walnuts, and fresh apple slices.', 'cereals_bowls', 'british', 'breakfast', 'classic', '["ING_STEEL_CUT_OATS", "ING_MILK", "ING_BROWN_SUGAR", "ING_CINNAMON", "ING_WALNUTS", "ING_APPLE", "ING_BUTTER"]'::jsonb, '["gluten", "milk", "nuts"]'::jsonb, false, false, false, false, true, true, true, 420, 12, 62, 16, 0, '["irish", "hearty", "warm", "traditional"]'::jsonb, 78, 350, 30, true),
('BRK_PORRIDGE', 'scottish-porridge', 'Scottish Porridge', 'Traditional Scottish oat porridge made with water and a pinch of salt. Served with cream, honey, and fresh berries.', 'cereals_bowls', 'british', 'early_breakfast', 'traditional', '["ING_ROLLED_OATS", "ING_CREAM", "ING_HONEY", "ING_MIXED_BERRIES", "ING_SALT"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 320, 10, 48, 12, 0, '["scottish", "traditional", "warm", "comforting"]'::jsonb, 72, 300, 15, true),
('BRK_GRANOLA_PARFAIT', 'granola-parfait', 'Granola Yogurt Parfait', 'Layered Greek yogurt with house-made granola, fresh berries, and honey. A protein-packed healthy breakfast option.', 'cereals_bowls', 'american', 'breakfast', 'popular', '["ING_GREEK_YOGURT", "ING_GRANOLA", "ING_BLUEBERRIES", "ING_STRAWBERRIES", "ING_HONEY", "ING_ALMONDS"]'::jsonb, '["milk", "nuts", "gluten"]'::jsonb, false, false, false, false, true, true, true, 380, 18, 48, 14, 0, '["healthy", "protein", "yogurt", "layered"]'::jsonb, 86, 320, 5, true),
('BRK_CHIA_PUDDING', 'chia-pudding', 'Chia Seed Pudding', 'Creamy pudding made from chia seeds soaked in coconut milk. Topped with tropical fruits, coconut flakes, and passionfruit.', 'cereals_bowls', 'international', 'breakfast', 'trending', '["ING_CHIA_SEEDS", "ING_COCONUT_MILK", "ING_MANGO", "ING_PASSION_FRUIT", "ING_COCONUT_FLAKES", "ING_MAPLE_SYRUP"]'::jsonb, '[]'::jsonb, true, true, true, true, true, true, true, 320, 10, 38, 16, 0, '["vegan", "superfood", "tropical", "meal-prep"]'::jsonb, 82, 280, 5, true),
('BRK_BIRCHER_MUESLI', 'bircher-muesli', 'Bircher Muesli', 'Swiss overnight oats created by Dr. Bircher-Benner. Raw oats soaked with apple, yogurt, lemon juice, and hazelnuts.', 'cereals_bowls', 'german', 'breakfast', 'classic', '["ING_ROLLED_OATS", "ING_GREEK_YOGURT", "ING_APPLE", "ING_LEMON", "ING_HAZELNUTS", "ING_HONEY", "ING_MILK"]'::jsonb, '["gluten", "milk", "nuts"]'::jsonb, false, false, false, false, true, true, true, 360, 14, 52, 12, 0, '["swiss", "healthy", "raw", "traditional"]'::jsonb, 76, 300, 5, true),
('BRK_CONGEE', 'congee', 'Congee', 'Silky Chinese rice porridge slow-cooked to a creamy consistency. Topped with century egg, ginger, scallions, and crispy shallots.', 'cereals_bowls', 'chinese', 'early_breakfast', 'traditional', '["ING_RICE", "ING_CHICKEN_BROTH", "ING_CENTURY_EGG", "ING_GINGER", "ING_SCALLION", "ING_CRISPY_SHALLOTS", "ING_SOY_SAUCE", "ING_SESAME_OIL"]'::jsonb, '["eggs", "soy", "sesame"]'::jsonb, true, true, true, false, false, true, false, 280, 12, 42, 8, 0, '["chinese", "comfort", "savory", "rice-porridge"]'::jsonb, 78, 400, 60, false),
('BRK_QUINOA_BOWL', 'quinoa-breakfast-bowl', 'Quinoa Breakfast Bowl', 'Warm quinoa bowl with almond milk, cinnamon, and vanilla. Topped with fresh berries, sliced almonds, and a drizzle of agave.', 'cereals_bowls', 'american', 'breakfast', 'trending', '["ING_QUINOA", "ING_ALMOND_MILK", "ING_CINNAMON", "ING_VANILLA", "ING_MIXED_BERRIES", "ING_ALMONDS", "ING_AGAVE"]'::jsonb, '["nuts"]'::jsonb, true, true, false, true, true, true, true, 340, 12, 52, 10, 0, '["protein", "gluten-free", "superfood", "healthy"]'::jsonb, 80, 300, 20, true)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- SAVORY CATEGORY (10 items)
-- ============================================
INSERT INTO breakfast (id, slug, name, description, category, origin, meal_time, status, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity, serving_size_g, prep_time_minutes, is_sweet) VALUES
('BRK_FULL_ENGLISH', 'full-english-breakfast', 'Full English Breakfast', 'The iconic British fry-up: bacon, sausages, eggs, baked beans, grilled tomatoes, mushrooms, toast, and black pudding.', 'savory', 'british', 'breakfast', 'iconic', '["ING_BACON", "ING_PORK_SAUSAGE", "ING_EGG", "ING_BAKED_BEANS", "ING_TOMATO", "ING_MUSHROOMS", "ING_TOAST", "ING_BLACK_PUDDING", "ING_BUTTER"]'::jsonb, '["gluten", "eggs"]'::jsonb, false, false, true, false, false, false, false, 850, 42, 48, 58, 0, '["british", "fry-up", "hearty", "iconic"]'::jsonb, 92, 550, 25, false),
('BRK_FULL_IRISH', 'full-irish-breakfast', 'Full Irish Breakfast', 'Similar to English but with white pudding, soda bread, and rashers. A hearty start to the day in Ireland.', 'savory', 'british', 'breakfast', 'traditional', '["ING_IRISH_BACON", "ING_PORK_SAUSAGE", "ING_EGG", "ING_WHITE_PUDDING", "ING_BLACK_PUDDING", "ING_BAKED_BEANS", "ING_TOMATO", "ING_SODA_BREAD", "ING_BUTTER"]'::jsonb, '["gluten", "eggs"]'::jsonb, false, false, true, false, false, false, false, 880, 44, 52, 60, 0, '["irish", "fry-up", "hearty", "traditional"]'::jsonb, 82, 580, 25, false),
('BRK_BREAKFAST_BURRITO', 'breakfast-burrito', 'Breakfast Burrito', 'Large flour tortilla stuffed with scrambled eggs, crispy bacon, hash browns, cheese, and salsa. A Tex-Mex morning favorite.', 'savory', 'mexican', 'breakfast', 'popular', '["ING_FLOUR_TORTILLA", "ING_EGG", "ING_BACON", "ING_HASH_BROWNS", "ING_CHEDDAR", "ING_SALSA", "ING_SOUR_CREAM", "ING_CHIVES"]'::jsonb, '["gluten", "eggs", "milk"]'::jsonb, false, false, true, false, false, false, false, 620, 28, 48, 36, 1, '["tex-mex", "portable", "hearty", "filling"]'::jsonb, 90, 380, 20, false),
('BRK_AVOCADO_TOAST', 'avocado-toast', 'Avocado Toast', 'Smashed ripe avocado on artisan sourdough, topped with poached egg, cherry tomatoes, microgreens, and everything bagel seasoning.', 'savory', 'australian', 'brunch', 'trending', '["ING_SOURDOUGH", "ING_AVOCADO", "ING_EGG", "ING_CHERRY_TOMATOES", "ING_MICROGREENS", "ING_EVERYTHING_SEASONING", "ING_OLIVE_OIL", "ING_CHILI_FLAKES"]'::jsonb, '["gluten", "eggs"]'::jsonb, false, true, true, false, true, true, true, 420, 16, 32, 28, 1, '["australian", "trendy", "instagram", "healthy"]'::jsonb, 94, 280, 15, false),
('BRK_HASH_BROWNS', 'hash-browns-platter', 'Hash Browns Platter', 'Crispy golden hash browns topped with melted cheese, sour cream, and chives. Served with sunny-side up eggs.', 'savory', 'american', 'breakfast', 'classic', '["ING_POTATO", "ING_BUTTER", "ING_CHEDDAR", "ING_SOUR_CREAM", "ING_CHIVES", "ING_EGG", "ING_SALT", "ING_BLACK_PEPPER"]'::jsonb, '["milk", "eggs"]'::jsonb, true, false, true, false, true, true, true, 480, 18, 42, 28, 0, '["american", "diner", "crispy", "comfort"]'::jsonb, 86, 350, 20, false),
('BRK_CROQUE_MADAME', 'croque-madame', 'Croque Madame', 'French grilled ham and cheese sandwich covered in béchamel, topped with a fried egg. The elegant cousin of croque monsieur.', 'savory', 'french', 'brunch', 'classic', '["ING_BRIOCHE", "ING_HAM", "ING_GRUYERE", "ING_BUTTER", "ING_FLOUR", "ING_MILK", "ING_EGG", "ING_NUTMEG", "ING_DIJON"]'::jsonb, '["gluten", "milk", "eggs"]'::jsonb, false, false, true, false, false, false, false, 580, 28, 38, 36, 0, '["french", "grilled", "elegant", "indulgent"]'::jsonb, 84, 300, 20, false),
('BRK_BACON_EGG_CHEESE', 'bacon-egg-cheese', 'Bacon Egg and Cheese', 'New York bodega classic: crispy bacon, fried egg, and melted American cheese on a toasted roll. Salt-pepper-ketchup optional.', 'savory', 'american', 'early_breakfast', 'iconic', '["ING_KAISER_ROLL", "ING_BACON", "ING_EGG", "ING_AMERICAN_CHEESE", "ING_BUTTER", "ING_SALT", "ING_BLACK_PEPPER"]'::jsonb, '["gluten", "eggs", "milk"]'::jsonb, false, false, true, false, false, false, false, 520, 24, 32, 34, 0, '["new-york", "bodega", "quick", "iconic"]'::jsonb, 92, 220, 10, false),
('BRK_BISCUITS_GRAVY', 'biscuits-and-gravy', 'Biscuits and Gravy', 'Southern American breakfast of fluffy buttermilk biscuits smothered in creamy sausage gravy. Comfort food at its finest.', 'savory', 'american', 'breakfast', 'traditional', '["ING_FLOUR", "ING_BUTTERMILK", "ING_BUTTER", "ING_BAKING_POWDER", "ING_PORK_SAUSAGE", "ING_MILK", "ING_BLACK_PEPPER", "ING_SAGE"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, false, false, false, 680, 22, 52, 44, 1, '["southern", "comfort", "hearty", "traditional"]'::jsonb, 85, 400, 25, false),
('BRK_EGGS_SARDOU', 'eggs-sardou', 'Eggs Sardou', 'New Orleans brunch specialty: poached eggs on artichoke bottoms with creamed spinach and hollandaise. Named for a French playwright.', 'savory', 'american', 'brunch', 'signature', '["ING_EGG", "ING_ARTICHOKE", "ING_SPINACH", "ING_CREAM", "ING_BUTTER", "ING_EGG_YOLK", "ING_LEMON", "ING_CAYENNE"]'::jsonb, '["eggs", "milk"]'::jsonb, true, false, true, false, true, true, true, 480, 18, 16, 40, 1, '["new-orleans", "brunch", "elegant", "hollandaise"]'::jsonb, 74, 320, 30, false),
('BRK_CORNED_BEEF_HASH', 'corned-beef-hash', 'Corned Beef Hash', 'Classic American diner dish of crispy corned beef with diced potatoes and onions. Topped with sunny-side eggs.', 'savory', 'american', 'breakfast', 'classic', '["ING_CORNED_BEEF", "ING_POTATO", "ING_ONION", "ING_BUTTER", "ING_EGG", "ING_BLACK_PEPPER", "ING_PARSLEY"]'::jsonb, '["eggs"]'::jsonb, true, false, true, false, false, false, false, 520, 28, 32, 34, 0, '["american", "diner", "hearty", "classic"]'::jsonb, 80, 380, 25, false)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- INTERNATIONAL CATEGORY (15 items)
-- ============================================
INSERT INTO breakfast (id, slug, name, description, category, origin, meal_time, status, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_kosher, calories_per_serving, protein_g, carbs_g, fat_g, spice_level, tags, popularity, serving_size_g, prep_time_minutes, is_sweet) VALUES
('BRK_JAPANESE_BREAKFAST', 'japanese-breakfast', 'Traditional Japanese Breakfast', 'Complete Japanese morning meal: grilled salmon, steamed rice, miso soup, pickled vegetables, tamagoyaki, and natto.', 'international', 'japanese', 'early_breakfast', 'traditional', '["ING_SALMON", "ING_RICE", "ING_MISO", "ING_TOFU", "ING_NATTO", "ING_NORI", "ING_PICKLED_VEGETABLES", "ING_EGG", "ING_SOY_SAUCE"]'::jsonb, '["fish", "soy", "eggs"]'::jsonb, true, true, true, false, false, true, false, 520, 32, 58, 18, 0, '["japanese", "traditional", "balanced", "healthy"]'::jsonb, 82, 480, 30, false),
('BRK_TURKISH_BREAKFAST', 'turkish-breakfast', 'Turkish Breakfast (Kahvalti)', 'Lavish Turkish spread: olives, tomatoes, cucumbers, cheeses, honey, kaymak, eggs, simit bread, and endless cups of tea.', 'international', 'turkish', 'breakfast', 'traditional', '["ING_FETA", "ING_OLIVES", "ING_TOMATO", "ING_CUCUMBER", "ING_HONEY", "ING_KAYMAK", "ING_EGG", "ING_SIMIT", "ING_BLACK_TEA"]'::jsonb, '["gluten", "milk", "eggs"]'::jsonb, false, false, true, false, true, true, false, 680, 24, 62, 38, 0, '["turkish", "spread", "communal", "generous"]'::jsonb, 85, 600, 20, false),
('BRK_ISRAELI_BREAKFAST', 'israeli-breakfast', 'Israeli Breakfast', 'Colorful Israeli breakfast platter: fresh salads, hummus, labneh, olives, eggs, and warm pita bread.', 'international', 'israeli', 'breakfast', 'popular', '["ING_HUMMUS", "ING_LABNEH", "ING_TOMATO", "ING_CUCUMBER", "ING_OLIVES", "ING_EGG", "ING_PITA", "ING_OLIVE_OIL", "ING_ZAATAR"]'::jsonb, '["gluten", "eggs", "sesame"]'::jsonb, false, false, true, false, true, true, true, 580, 22, 52, 32, 0, '["israeli", "mediterranean", "fresh", "healthy"]'::jsonb, 84, 520, 15, false),
('BRK_INDIAN_BREAKFAST', 'south-indian-breakfast', 'South Indian Breakfast', 'Authentic South Indian meal: crispy dosa or idli served with coconut chutney and sambar. Vegetarian and gluten-free.', 'international', 'indian', 'breakfast', 'traditional', '["ING_RICE_FLOUR", "ING_URAD_DAL", "ING_COCONUT", "ING_MUSTARD_SEEDS", "ING_CURRY_LEAVES", "ING_SAMBAR", "ING_GHEE", "ING_GREEN_CHILI"]'::jsonb, '[]'::jsonb, true, false, true, false, true, true, true, 420, 14, 62, 14, 2, '["indian", "south-indian", "vegetarian", "fermented"]'::jsonb, 80, 400, 25, false),
('BRK_MEXICAN_CHILAQUILES', 'chilaquiles', 'Chilaquiles', 'Mexican breakfast of fried tortilla chips simmered in salsa verde or roja, topped with crema, queso fresco, and fried eggs.', 'international', 'mexican', 'brunch', 'classic', '["ING_CORN_TORTILLA", "ING_SALSA_VERDE", "ING_CREMA", "ING_QUESO_FRESCO", "ING_EGG", "ING_ONION", "ING_CILANTRO", "ING_AVOCADO"]'::jsonb, '["milk", "eggs"]'::jsonb, true, false, true, false, true, true, true, 480, 18, 38, 30, 2, '["mexican", "traditional", "comfort", "spicy"]'::jsonb, 86, 380, 20, false),
('BRK_KOREAN_BREAKFAST', 'korean-breakfast', 'Korean Breakfast', 'Traditional Korean morning meal: steamed rice, doenjang jjigae (soybean stew), kimchi, grilled fish, and banchan side dishes.', 'international', 'korean', 'early_breakfast', 'traditional', '["ING_RICE", "ING_DOENJANG", "ING_TOFU", "ING_KIMCHI", "ING_MACKEREL", "ING_SESAME_OIL", "ING_SCALLION", "ING_EGG"]'::jsonb, '["soy", "fish", "eggs"]'::jsonb, true, true, true, false, false, true, false, 520, 28, 56, 22, 2, '["korean", "traditional", "fermented", "healthy"]'::jsonb, 78, 500, 30, false),
('BRK_CONTINENTAL', 'continental-breakfast', 'Continental Breakfast', 'Light European breakfast: assorted pastries, fresh bread, butter, jam, sliced cold cuts, cheese, and fresh fruit with coffee.', 'international', 'international', 'breakfast', 'classic', '["ING_CROISSANT", "ING_BAGUETTE", "ING_BUTTER", "ING_JAM", "ING_HAM", "ING_CHEESE_ASSORTED", "ING_FRESH_FRUIT", "ING_ORANGE_JUICE"]'::jsonb, '["gluten", "milk"]'::jsonb, false, false, true, false, false, false, false, 480, 18, 58, 22, 0, '["european", "hotel", "light", "classic"]'::jsonb, 88, 400, 10, false),
('BRK_DIM_SUM', 'dim-sum-breakfast', 'Dim Sum Breakfast', 'Cantonese breakfast tradition: selection of har gow, siu mai, char siu bao, and cheung fun served with jasmine tea.', 'international', 'chinese', 'brunch', 'traditional', '["ING_SHRIMP", "ING_PORK", "ING_RICE_FLOUR", "ING_WHEAT_FLOUR", "ING_CHAR_SIU", "ING_SOY_SAUCE", "ING_GINGER", "ING_JASMINE_TEA"]'::jsonb, '["gluten", "shellfish", "soy"]'::jsonb, false, true, true, false, false, false, false, 520, 24, 58, 22, 0, '["cantonese", "dim-sum", "sharing", "steamed"]'::jsonb, 86, 450, 45, false),
('BRK_MENEMEN', 'menemen', 'Menemen', 'Turkish scrambled eggs cooked with tomatoes, peppers, and spices in a single pan. Served with crusty bread for dipping.', 'international', 'turkish', 'breakfast', 'traditional', '["ING_EGG", "ING_TOMATO", "ING_GREEN_PEPPER", "ING_ONION", "ING_BUTTER", "ING_PAPRIKA", "ING_CHILI_FLAKES", "ING_CRUSTY_BREAD"]'::jsonb, '["eggs", "gluten", "milk"]'::jsonb, false, false, true, false, true, true, true, 380, 16, 28, 24, 1, '["turkish", "eggs", "one-pan", "traditional"]'::jsonb, 80, 320, 15, false),
('BRK_FUL_MEDAMES', 'ful-medames', 'Ful Medames', 'Ancient Egyptian breakfast of slow-cooked fava beans mashed with olive oil, garlic, lemon, and cumin. Served with pita.', 'international', 'middle_eastern', 'breakfast', 'traditional', '["ING_FAVA_BEANS", "ING_OLIVE_OIL", "ING_GARLIC", "ING_LEMON", "ING_CUMIN", "ING_PARSLEY", "ING_PITA", "ING_EGG"]'::jsonb, '["gluten", "eggs"]'::jsonb, false, true, true, false, true, true, true, 420, 18, 52, 18, 1, '["egyptian", "ancient", "protein", "vegan-adaptable"]'::jsonb, 75, 380, 20, false),
('BRK_AUSSIE_BREAKFAST', 'australian-big-breakfast', 'Australian Big Breakfast', 'Modern Australian brunch: poached eggs, smashed avo, bacon, halloumi, roasted tomatoes, spinach, and sourdough toast.', 'international', 'australian', 'brunch', 'popular', '["ING_EGG", "ING_AVOCADO", "ING_BACON", "ING_HALLOUMI", "ING_TOMATO", "ING_SPINACH", "ING_SOURDOUGH", "ING_OLIVE_OIL"]'::jsonb, '["eggs", "milk", "gluten"]'::jsonb, false, false, true, false, false, false, false, 680, 36, 32, 48, 0, '["australian", "brunch", "modern", "instagram"]'::jsonb, 88, 480, 25, false),
('BRK_SWEDISH_BREAKFAST', 'swedish-breakfast', 'Swedish Breakfast', 'Scandinavian spread: crispbread with butter and cheese, smoked salmon, boiled eggs, muesli, and strong coffee (fika).', 'international', 'scandinavian', 'breakfast', 'traditional', '["ING_CRISPBREAD", "ING_BUTTER", "ING_CHEESE_ASSORTED", "ING_SMOKED_SALMON", "ING_EGG", "ING_MUESLI", "ING_MILK", "ING_LINGONBERRY_JAM"]'::jsonb, '["gluten", "milk", "eggs", "fish"]'::jsonb, false, false, true, false, false, true, false, 520, 28, 48, 26, 0, '["swedish", "scandinavian", "healthy", "fika"]'::jsonb, 76, 420, 10, false),
('BRK_VIETNAMESE_BREAKFAST', 'vietnamese-breakfast', 'Vietnamese Breakfast (Pho)', 'Traditional Vietnamese morning pho: aromatic beef broth with rice noodles, rare beef slices, fresh herbs, and condiments.', 'international', 'international', 'early_breakfast', 'traditional', '["ING_BEEF_BROTH", "ING_RICE_NOODLES", "ING_BEEF_SIRLOIN", "ING_STAR_ANISE", "ING_CINNAMON", "ING_BEAN_SPROUTS", "ING_THAI_BASIL", "ING_HOISIN", "ING_SRIRACHA"]'::jsonb, '["soy"]'::jsonb, true, true, true, false, false, true, false, 480, 32, 52, 14, 1, '["vietnamese", "pho", "soup", "aromatic"]'::jsonb, 84, 600, 15, false),
('BRK_BRAZILIAN_BREAKFAST', 'brazilian-breakfast', 'Brazilian Breakfast', 'Traditional Brazilian café da manhã: pão de queijo (cheese bread), fresh tropical fruits, cold cuts, and strong coffee with milk.', 'international', 'brazilian', 'breakfast', 'traditional', '["ING_TAPIOCA_FLOUR", "ING_CHEESE", "ING_EGG", "ING_PAPAYA", "ING_PINEAPPLE", "ING_HAM", "ING_BUTTER", "ING_COFFEE"]'::jsonb, '["milk", "eggs"]'::jsonb, true, false, true, false, false, false, false, 480, 18, 52, 24, 0, '["brazilian", "tropical", "pao-de-queijo", "coffee"]'::jsonb, 78, 400, 15, false),
('BRK_SPANISH_BREAKFAST', 'spanish-breakfast', 'Spanish Breakfast', 'Classic Spanish desayuno: pan con tomate (bread with tomato), jamón serrano, tortilla española, and café con leche.', 'international', 'spanish', 'breakfast', 'traditional', '["ING_BAGUETTE", "ING_TOMATO", "ING_OLIVE_OIL", "ING_JAMON_SERRANO", "ING_EGG", "ING_POTATO", "ING_ONION", "ING_COFFEE"]'::jsonb, '["gluten", "eggs"]'::jsonb, false, true, true, false, false, false, false, 520, 24, 42, 30, 0, '["spanish", "tortilla", "jamon", "mediterranean"]'::jsonb, 82, 380, 20, false)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- Enable Row Level Security
-- ============================================
ALTER TABLE breakfast ENABLE ROW LEVEL SECURITY;

-- Create public read policy
DROP POLICY IF EXISTS "Allow public read access" ON breakfast;
CREATE POLICY "Allow public read access" ON breakfast
  FOR SELECT USING (true);

-- ============================================
-- Verification Query
-- ============================================
-- After running, verify with:
-- SELECT category, COUNT(*) FROM breakfast GROUP BY category ORDER BY category;
-- Expected: eggs(10), pancakes_waffles(10), pastries(10), cereals_bowls(10), savory(10), international(15)
-- Total: 65 records
