INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('1fdd9b60-eee2-468b-8205-5d188ad9de47', 'tequila-slammer', 'a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5', '{"en":"Tequila Slammer"}'::jsonb, 'famous', NULL, '{"highball","long-drink","famous","tequila","shot","party","interactive","fizzy"}', '{"en":"A festive party drink combining tequila with lemon-lime soda or champagne, served with a slam-and-shoot ritual. The Tequila Slammer is as much about the performance as the taste, creating an effervescent, fizzy shot that''s become a nightclub staple."}'::jsonb, '{"created_year":"1970","origin":{"city":"Mexico","country":"Mexico"},"story":{"en":"The Tequila Slammer (also known as \"Tequila Boom Boom\") originated in Mexico in the 1970s and gained international popularity in the 1980s. The ritual involves covering the glass with your hand, slamming it on the bar to create fizz, then shooting it quickly while it''s still bubbling. The drink became synonymous with party culture and was popularized by Tom Cruise in the 1988 film \"Cocktail.\" Two versions exist: one with lemon-lime soda (7-Up or Sprite) and a more upscale version with champagne."},"named_after":{"en":"Named after the \"slamming\" action of banging the glass on the bar to activate the carbonation before shooting it."}}'::jsonb, '{"profile":["sweet","citrus","fizzy","agave"],"description":{"en":"Bright citrus sweetness with tequila''s agave notes, enhanced by intense carbonation from the slamming action. The fizz creates a unique tingling sensation and makes the drink surprisingly smooth and easy to shoot despite the tequila base."},"first_impression":{"en":"Intense fizz and citrus with agave warmth"},"finish":{"en":"Quick, clean finish with lingering tequila warmth"},"balance":{"en":"The soda sweetness balances the tequila''s bite, while carbonation makes it dangerously easy to drink"}}'::jsonb, '{"best_time":["night","late_night"],"occasions":["party","celebration","nightclub","birthday"],"seasons":["all-year"],"food_pairings":{"en":"Typically consumed as a party shot without food. If pairing, works with Mexican appetizers, nachos, tacos, and salty snacks."},"ideal_for":{"en":"Perfect for party atmospheres and celebrations. Great for groups who enjoy interactive drinking rituals. Popular in nightclubs and birthday parties. Not for those seeking sophisticated cocktails."}}'::jsonb, '[{"ingredient_id":"ING_TEQUILA_SILVER","quantity":{"amount":30,"unit":"ml"},"display_name":"Tequila (silver)","notes":null},{"ingredient_id":"ING_LEMON_LIME_SODA","quantity":{"amount":30,"unit":"ml"},"display_name":"Lemon-lime soda (7-Up or Sprite)","notes":null}]'::jsonb, 'build', '{"en":"Pour tequila into a rocks glass or highball glass. Add lemon-lime soda. Cover the top of the glass firmly with your hand. Slam the glass down on the bar to create fizz. Immediately shoot the drink while it''s still fizzing."}'::jsonb, 'Rocks glass or Highball glass', '{"en":"None (optional lime wedge)"}'::jsonb, 'none', 'straight_up', '{"ING_TEQUILA_SILVER"}', '{"sweet","citrus","fizzy","agave"}', 20, 95, 'easy', 20, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"all-year"}', '{"party","celebration","nightclub"}', false, false, '{"tequila-boom-boom","champagne-slammer"}', 'Champagne version uses equal parts tequila and champagne - more expensive but smoother. Demonstrate the slam technique to customers. Use sturdy glassware. Popular as a group shot. Equal parts (50/50) ratio is standard.', 'low', 75, 'https://www.diffordsguide.com/cocktails/recipe/1242/tequila-slammer', 'Mexican party shot popularized in 1980s, featured in "Cocktail" (1988).', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 213. Test Pilot


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('e76c1571-670a-45f8-af7a-52b9d0eb453a', 'test-pilot', 'test_pilot_famous_tiki_tropical_cocktail', '{"en":"Test Pilot"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","complex","strong"}', '{"en":"The Test Pilot is a sophisticated tiki cocktail created by Don the Beachcomber, featuring a complex blend of rums with falernum, Pernod, and citrus. This potent drink showcases the depth and complexity that defines classic tiki mixology."}'::jsonb, '{"created_year":"1941","origin":{"city":"Hollywood","bar":"Don the Beachcomber","country":"USA"},"creator":{"name":"Ernest Raymond Beaumont Gantt (Donn Beach)","profession":"bartender"},"story":{"en":"The Test Pilot was created around 1941 by Don the Beachcomber (Ernest Raymond Beaumont Gantt) at his Hollywood restaurant. The drink emerged during the early days of World War II when aviation was prominent in public consciousness. Don the Beachcomber was known for creating incredibly complex rum cocktails with multiple rums and exotic ingredients, and the Test Pilot exemplifies this approach. The recipe combines three different rums with falernum (a Caribbean spiced syrup), Pernod (anise liqueur), and fresh citrus, creating layers of flavor that were revolutionary for the era. Like many Don the Beachcomber creations, the recipe was kept secret and coded, only being deciphered decades later by tiki historians like Jeff \"Beachbum\" Berry."},"named_after":{"en":"Named after World War II aviation test pilots, reflecting the drink''s daring, adventurous nature and potent strength."}}'::jsonb, '{"profile":["complex","spiced","citrus"],"description":{"en":"Extraordinarily complex with layers of rum, spice, anise, and citrus. The Test Pilot balances multiple rums with the warming spice of falernum, subtle anise from Pernod, and bright lime. Each sip reveals new dimensions of flavor - a true test of bartending mastery."},"first_impression":{"en":"Bright lime and anise hit first, followed by warming spice and complex rum depth"},"finish":{"en":"Long, complex finish with lingering spice, anise, and aged rum notes"},"balance":{"en":"Masterfully balanced complexity - each ingredient plays its part without overwhelming the others"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["tiki_bar","special_occasion","connoisseur_gathering"],"seasons":["year_round"],"food_pairings":{"en":"Perfect with Polynesian-style appetizers, teriyaki dishes, grilled pineapple, or spiced pork. Also pairs well with Caribbean jerk chicken and tropical fruit desserts."},"ideal_for":{"en":"Perfect for serious tiki enthusiasts and rum connoisseurs seeking an authentic Don the Beachcomber experience. Ideal for those who appreciate complex, multi-layered cocktails. Not for beginners - this is advanced tiki drinking."}}'::jsonb, '[{"ingredient_id":"ING_RUM_DARK","quantity":{"amount":45,"unit":"ml"},"display_name":"Dark rum (Jamaican)","notes":null},{"ingredient_id":"ING_RUM_DEMERARA","quantity":{"amount":15,"unit":"ml"},"display_name":"Demerara rum (151 proof)","notes":null},{"ingredient_id":"ING_ORANGE_CURACAO","quantity":{"amount":15,"unit":"ml"},"display_name":"Orange curaçao","notes":null},{"ingredient_id":"ING_FALERNUM","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Falernum","notes":null},{"ingredient_id":"ING_PERNOD","quantity":{"amount":3,"unit":"ml"},"display_name":"Pernod (absinthe)","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":2,"unit":"dash"},"display_name":"Angostura bitters","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a double old-fashioned glass filled with crushed ice. Garnish with mint sprig and lime wheel."}'::jsonb, 'Double old-fashioned', '{"en":"Fresh mint sprig, lime wheel"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_RUM_DARK","ING_RUM_DEMERARA"}', '{"complex","spiced","citrus"}', 22, 220, 'hard', 120, '{"sulphites","wormwood"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 2, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"year_round"}', '{"tiki_bar","special_occasion","connoisseur_gathering"}', false, false, '{"don-the-beachcomber-test-pilot"}', 'Original Don the Beachcomber recipe circa 1941, decoded by Jeff Berry. Complex recipe requires precise measurements. Falernum is essential - contains clove, almond, lime. Just a dash of Pernod - too much will overpower. Use 151-proof Demerara if available. Very strong and complex.', 'premium', 62, 'https://beachbumberry.com/test-pilot.html', 'Original Don the Beachcomber recipe circa 1941, decoded by Jeff "Beachbum" Berry in Sippin'' Safari.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 214. Tiramisu Martini


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('a76fe2c0-2376-43c3-bcac-27340c8dff70', 'tiramisu-martini', 'tiramisu_martini_vodka_kahlua_baileys_cream', '{"en":"Tiramisu Martini"}'::jsonb, 'famous', NULL, '{"creamy","dessert","famous","coffee","chocolate","sweet","vodka-based","martini-style"}', '{"en":"A liquid version of the beloved Italian dessert, combining vodka, coffee liqueur, Irish cream, and cream to recreate the flavors of tiramisu in cocktail form. This indulgent martini captures the essence of coffee-soaked ladyfingers and mascarpone cream."}'::jsonb, '{"created_year":"2000s","origin":{"country":"USA"},"story":{"en":"The Tiramisu Martini emerged in the early 2000s as bartenders sought to create cocktail versions of popular desserts. Inspired by the classic Italian tiramisu dessert, mixologists combined coffee liqueur, Irish cream, and vodka to mimic the coffee, cream, and mascarpone flavors of the original dish. The cocktail became popular in upscale Italian restaurants and cocktail bars, offering a sophisticated way to enjoy tiramisu flavors without the fork. It represents the trend of dessert-inspired cocktails that dominated the 2000s."},"named_after":{"en":"Named after the classic Italian dessert \"Tiramisu,\" which means \"pick me up\" in Italian, referring to its coffee content."}}'::jsonb, '{"profile":["creamy","sweet","coffee","chocolate"],"description":{"en":"A perfect recreation of tiramisu flavors: rich coffee notes balanced with sweet cream and hints of chocolate. The Irish cream adds a mascarpone-like richness while the coffee liqueur provides the espresso character. Sweet, indulgent, and remarkably similar to the dessert."},"first_impression":{"en":"Coffee and cream hit first, immediately reminiscent of tiramisu"},"finish":{"en":"Long, sweet finish with coffee and cocoa notes, just like the dessert"},"balance":{"en":"Well-balanced for a dessert cocktail, with coffee and cream in harmony"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["dessert","date_night","italian_dinner","celebration"],"seasons":["all_seasons"],"food_pairings":{"en":"Perfect as a dessert replacement, especially after Italian meals. Can accompany biscotti, chocolate desserts, or coffee-flavored sweets. Also pairs with cannoli and panna cotta."},"ideal_for":{"en":"Perfect for tiramisu lovers who want a liquid version of their favorite dessert. Ideal for Italian restaurant endings, coffee enthusiasts, and anyone seeking an indulgent after-dinner cocktail with familiar flavors."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":30,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_COFFEE_LIQUEUR","quantity":{"amount":30,"unit":"ml"},"display_name":"Coffee liqueur (Kahlúa)","notes":null},{"ingredient_id":"ING_IRISH_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Irish cream (Baileys)","notes":null},{"ingredient_id":"ING_HEAVY_CREAM","quantity":{"amount":15,"unit":"ml"},"display_name":"Heavy cream","notes":null}]'::jsonb, 'shake', '{"en":"Rim a chilled martini glass with cocoa powder. Add all ingredients to a cocktail shaker filled with ice. Shake vigorously for 15 seconds until well-chilled and frothy. Double strain into the prepared martini glass. Dust the top with cocoa powder to mimic the traditional tiramisu presentation."}'::jsonb, 'Martini glass', '{"en":"Cocoa powder dusting, chocolate shavings, or ladyfinger cookie"}'::jsonb, 'none', 'up', '{"ING_VODKA"}', '{"creamy","sweet","coffee","chocolate"}', 17, 340, 'easy', 90, '{"milk"}', '{"lactose","alcohol","caffeine"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 0, '{"vegetarian","gluten-free"}', '{"all-seasons"}', '{"dessert","date-night","celebration"}', false, false, '{"espresso-tiramisu-martini","frozen-tiramisu-martini","tiramisu-white-russian"}', 'The cocoa powder rim and dusting is essential for authentic tiramisu look. Some recipes use amaretto instead of vodka. Can add a shot of espresso for more coffee intensity. Popular in Italian restaurants as a liquid dessert option. High calorie content.', 'mid', 75, 'https://www.allrecipes.com/recipe/228654/tiramisu-martini/', 'Dessert-inspired cocktail popular in the 2000s.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 215. Toasted Almond


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('d07ac9b8-33e8-4a35-bd6d-60f3ce0eeb47', 'toasted-almond', 'toasted_almond_amaretto_kahlua_cream', '{"en":"Toasted Almond"}'::jsonb, 'famous', NULL, '{"creamy","dessert","famous","coffee","nutty","sweet"}', '{"en":"A smooth, nutty dessert cocktail combining amaretto, coffee liqueur, and cream. The Toasted Almond offers a perfect balance of almond and coffee flavors wrapped in silky cream, creating an irresistible after-dinner treat."}'::jsonb, '{"created_year":"1970s","origin":{"country":"USA"},"story":{"en":"The Toasted Almond emerged in the 1970s during the golden age of creamy cocktails in America. It''s often considered a variation of the Sombrero (Kahlúa and cream) or a cousin to the Orgasm family of shooters. The drink became popular in bars and restaurants as an accessible, crowd-pleasing dessert cocktail that showcased the then-trendy amaretto liqueur. Its simple recipe and delicious flavor profile have kept it popular in casual dining establishments."},"named_after":{"en":"Named for the \"toasted\" almond flavor achieved by combining amaretto with coffee liqueur, evoking the taste of roasted almonds."}}'::jsonb, '{"profile":["creamy","sweet","nutty","coffee"],"description":{"en":"Rich and creamy with pronounced almond and coffee notes. The amaretto provides sweet nuttiness while the coffee liqueur adds depth and a subtle roasted quality, all softened by cream into a smooth, dessert-like drink."},"first_impression":{"en":"Sweet almond cream with immediate coffee undertones"},"finish":{"en":"Smooth, lingering almond and coffee sweetness"},"balance":{"en":"Well-balanced between nutty and coffee flavors, though decidedly sweet and dessert-focused"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["digestivo","casual","dessert","nightcap"],"seasons":["all_seasons"],"food_pairings":{"en":"Perfect with almond-based desserts, biscotti, tiramisu, or chocolate cake. Also pairs well with vanilla ice cream and amaretti cookies."},"ideal_for":{"en":"Perfect for those who enjoy nutty, coffee-flavored dessert drinks. Ideal for casual dining settings and anyone seeking a simple but delicious after-dinner cocktail. Great alternative to Irish Coffee or White Russian."}}'::jsonb, '[{"ingredient_id":"ING_AMARETTO","quantity":{"amount":30,"unit":"ml"},"display_name":"Amaretto","notes":null},{"ingredient_id":"ING_COFFEE_LIQUEUR","quantity":{"amount":30,"unit":"ml"},"display_name":"Coffee liqueur (Kahlúa)","notes":null},{"ingredient_id":"ING_HEAVY_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Heavy cream","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake well for 10-15 seconds until chilled and frothy. Strain into an ice-filled rocks glass or serve up in a coupe glass. Can also be built directly in glass over ice and stirred."}'::jsonb, 'Rocks glass (or Coupe)', '{"en":"Toasted sliced almonds (optional)"}'::jsonb, 'cubes', 'on_the_rocks', '{"ING_AMARETTO"}', '{"creamy","sweet","nutty","coffee"}', 14, 280, 'easy', 45, '{"milk","tree_nuts"}', '{"lactose","alcohol","caffeine","nut_allergy"}', '{"vegetarian","pescatarian","gluten_free"}', 0, '{"vegetarian","gluten-free"}', '{"all-seasons"}', '{"digestivo","casual","dessert","nightcap"}', false, false, '{"toasted-almond-shooter","frozen-toasted-almond","italian-toasted-almond"}', 'Simple three-ingredient recipe. Can be served on rocks or up depending on preference. Some recipes add vodka for extra strength. Contains nut liqueur - always check for allergies. Popular as both a cocktail and a shooter.', 'low', 65, 'https://www.liquor.com/recipes/toasted-almond/', 'Popular creamy cocktail from the 1970s American bar scene.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 216. Tokyo Tea


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('af3f84a9-bf0d-4ef0-a28e-8bafff4cebdc', 'tokyo-tea', 'd5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4', '{"en":"Tokyo Tea"}'::jsonb, 'famous', NULL, '{"highball","long-drink","famous","strong","party","melon","multi-spirit","green"}', '{"en":"A vibrant green variation of the Long Island Iced Tea, featuring Midori melon liqueur instead of cola. This potent cocktail combines five spirits with sweet and sour mix and lemon-lime soda, creating a dangerously drinkable party favorite."}'::jsonb, '{"created_year":"1990","origin":{"city":"United States","country":"USA"},"story":{"en":"The Tokyo Tea emerged in the 1990s as part of the \"geography-themed iced tea\" trend that included Long Island, Long Beach, Miami, and other variations. The name references Tokyo and Japanese culture through the use of Midori, a Japanese melon liqueur. The vibrant green color makes it visually striking and Instagram-worthy. Like its cousins, it contains multiple spirits making it extremely strong despite tasting sweet and fruity. The drink became popular in nightclubs and college bars where the sweet melon flavor masked its substantial alcohol content."},"named_after":{"en":"Named after Tokyo, Japan, referencing Japanese culture through Midori melon liqueur, which is produced in Japan."}}'::jsonb, '{"profile":["sweet","fruity","melon","strong"],"description":{"en":"Sweet and fruity with prominent melon flavor from Midori, masking the considerable alcohol content from five spirits. The lemon-lime soda adds effervescence while the sweet and sour mix provides citrus balance. Dangerously smooth and deceptively strong."},"first_impression":{"en":"Sweet melon with citrus and fruity complexity"},"finish":{"en":"Long, warming finish with melon sweetness and multi-spirit heat"},"balance":{"en":"Very sweet with melon dominating - the substantial alcohol is well-masked, making it dangerously easy to drink"}}'::jsonb, '{"best_time":["evening","night","late_night"],"occasions":["party","celebration","nightclub","birthday"],"seasons":["all-year"],"food_pairings":{"en":"Best enjoyed as a party drink without food. If pairing, works with Asian fusion appetizers, sushi, and light party snacks."},"ideal_for":{"en":"Perfect for party-goers who love sweet, colorful drinks. Great for celebrations and nightclub settings. WARNING: Extremely high alcohol content - pace yourself and drink responsibly."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":15,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_WHITE_RUM","quantity":{"amount":15,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_GIN","quantity":{"amount":15,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_TEQUILA_SILVER","quantity":{"amount":15,"unit":"ml"},"display_name":"Tequila (silver)","notes":null},{"ingredient_id":"ING_MIDORI","quantity":{"amount":15,"unit":"ml"},"display_name":"Midori melon liqueur","notes":null},{"ingredient_id":"ING_SWEET_AND_SOUR","quantity":{"amount":30,"unit":"ml"},"display_name":"Sweet and sour mix","notes":null},{"ingredient_id":"ING_LEMON_LIME_SODA","quantity":{"amount":30,"unit":"ml"},"display_name":"Lemon-lime soda (7-Up or Sprite)","notes":null}]'::jsonb, 'shake', '{"en":"Add vodka, rum, gin, tequila, Midori, and sweet and sour mix to a cocktail shaker with ice. Shake vigorously. Strain into a tall glass filled with fresh ice. Top with lemon-lime soda. Stir gently. Garnish with a cherry and lemon wheel."}'::jsonb, 'Collins glass or Hurricane glass', '{"en":"Maraschino cherry and lemon wheel"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA","ING_WHITE_RUM","ING_GIN","ING_TEQUILA_SILVER","ING_MIDORI"}', '{"sweet","fruity","melon","strong"}', 22, 260, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"all-year"}', '{"party","celebration","nightclub"}', false, false, '{"long-island-iced-tea","long-beach-iced-tea","miami-iced-tea"}', 'EXTREMELY STRONG - 5 spirits total. The green color makes it visually appealing. Midori is essential for authentic Tokyo Tea. Warn customers about high alcohol content.', 'mid', 70, 'https://www.diffordsguide.com/cocktails/recipe/1251/tokyo-tea', 'Part of 1990s "geography iced tea" trend, featuring Midori melon liqueur.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 217. Tom Collins


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('28752f91-1580-4804-9839-3eb75fb8a3ce', 'tom-collins', 'c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2', '{"en":"Tom Collins"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","gin","citrus","refreshing","sparkling"}', '{"en":"A timeless gin fizz that''s essentially lemonade for adults. The Tom Collins combines gin with fresh lemon juice, sugar, and soda water to create a tall, refreshing drink that''s perfect for warm weather. Simple, elegant, and endlessly drinkable."}'::jsonb, '{"created_year":"1876","origin":{"city":"London","bar":"Unknown (possibly Limmer''s Hotel)","country":"United Kingdom"},"creator":{"name":"John Collins (disputed)","profession":"bartender"},"story":{"en":"The Tom Collins has a fascinating and somewhat convoluted history. The drink first appeared in Jerry Thomas''s 1876 \"Bartender''s Guide,\" but its name derives from an elaborate practical joke called \"The Great Tom Collins Hoax of 1874.\" People would tell their friends that a man named Tom Collins was spreading rumors about them at a local bar, sending victims on wild goose chases. When the joke became popular, bartenders started creating a drink to match the fictional character. The name might also reference John Collins, a waiter at Limmer''s Hotel in London who supposedly created a similar drink with Old Tom Gin, hence \"Tom Collins.\" The drink became one of the most popular cocktails of the late 1800s and remains a classic today."},"named_after":{"en":"Named after either the \"Great Tom Collins Hoax\" of 1874 or John Collins, a waiter at Limmer''s Hotel who may have created the drink with Old Tom Gin."}}'::jsonb, '{"profile":["citrus","refreshing","effervescent"],"description":{"en":"Bright, refreshing, and perfectly balanced. The Tom Collins tastes like sophisticated lemonade with a juniper kick. The gin''s botanicals shine through the lemon''s tartness, while soda water adds effervescence and drinkability."},"first_impression":{"en":"Crisp lemon acidity with gentle gin botanicals and refreshing bubbles"},"finish":{"en":"Clean, refreshing finish with lingering citrus and subtle juniper notes"},"balance":{"en":"Masterfully balanced between sweet and tart, with gin adding complexity without overwhelming"}}'::jsonb, '{"best_time":["afternoon","early_evening"],"occasions":["social","outdoor","brunch","casual"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with light fare: salads, sandwiches, grilled chicken, seafood, and brunch dishes. Also pairs well with Mediterranean and Middle Eastern cuisine."},"ideal_for":{"en":"Perfect for those who enjoy refreshing, citrus-forward cocktails. Ideal for warm weather drinking, outdoor gatherings, and anyone who wants a classic gin drink that''s easy to enjoy."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":45,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":15,"unit":"ml"},"display_name":"Simple syrup","notes":null},{"ingredient_id":"ING_SODA_WATER","quantity":{"amount":60,"unit":"ml"},"display_name":"Soda water","notes":null}]'::jsonb, 'shake', '{"en":"Add gin, lemon juice, and simple syrup to a cocktail shaker with ice. Shake well until chilled. Strain into a tall glass filled with fresh ice. Top with soda water and stir gently. Garnish with a lemon wheel and cherry."}'::jsonb, 'Collins glass (Highball)', '{"en":"Lemon wheel and maraschino cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_GIN"}', '{"citrus","refreshing","effervescent"}', 10, 160, 'easy', 90, '{}', '{"alcohol"}', '{"vegetarian","vegan","pescatarian","gluten_free","nut_free","dairy_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"spring","summer"}', '{"social","outdoor","brunch","casual"}', false, false, '{"john-collins","vodka-collins","rum-collins"}', 'Always use fresh lemon juice. The key is proper dilution from shaking before adding soda. Use Old Tom Gin for a historically accurate version. Don''t over-pour the soda - it should enhance, not dilute.', 'mid', 80, 'https://www.diffordsguide.com/cocktails/recipe/2161/tom-collins', 'Classic recipe from Jerry Thomas''s Bartender''s Guide (1876) with modern adaptations.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 218. Trade Winds


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('f5daeff3-129c-4d20-897d-f1af1726c0ee', 'trade-winds', 'trade-winds-tiki-tropical-famous-2025', '{"en":"Trade Winds"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","plum","exotic","classic-tiki"}', '{"en":"A sophisticated tiki cocktail featuring rum, plum brandy, and tropical citrus. The Trade Winds offers a complex blend of sweet, tart, and fruity flavors with an exotic plum character that sets it apart from typical tiki drinks."}'::jsonb, '{"created_year":"1940s","origin":{"city":"Oakland","bar":"Trader Vic''s","country":"USA"},"creator":{"name":"Victor Bergeron (Trader Vic)","profession":"bartender"},"story":{"en":"The Trade Winds was created by Victor \"Trader Vic\" Bergeron in the 1940s at his legendary Trader Vic''s restaurant in Oakland, California. As one of the pioneers of tiki culture alongside Don the Beachcomber, Trader Vic crafted this cocktail to showcase the exotic flavors that defined his establishment. The drink''s name references the prevailing winds that blow from east to west near the equator, essential for historical maritime trade routes - a fitting tribute to the exotic ingredients and Polynesian-inspired culture that tiki bars celebrated. Unlike many tiki drinks that rely heavily on tropical fruit juices, the Trade Winds stands out with its sophisticated use of plum brandy (slivovitz), creating a more complex, less sweet profile."},"named_after":{"en":"Named after the trade winds - prevailing tropical winds near the equator that were essential for historical maritime trade routes, symbolizing exotic travel and cultural exchange."}}'::jsonb, '{"profile":["fruity","tart","complex"],"description":{"en":"Complex and sophisticated with tart citrus, exotic plum notes, and rum warmth. The plum brandy provides an unusual fruity depth that elevates this beyond standard tiki fare. Balanced between sweet and sour with intriguing complexity."},"first_impression":{"en":"Bright citrus with unexpected exotic plum and spice notes"},"finish":{"en":"Long, complex finish with lingering plum, rum warmth, and citrus brightness"},"balance":{"en":"Beautifully balanced between sweet, sour, and bitter - more complex and less sweet than typical tiki drinks"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["tiki_bar","cocktail_appreciation","date_night","special_occasion"],"seasons":["summer","spring","year_round"],"food_pairings":{"en":"Pairs excellently with grilled pork, duck, Asian plum sauce dishes, tropical fruit platters, or Polynesian-style cuisine. Also complements spicy Thai or Vietnamese dishes."},"ideal_for":{"en":"Perfect for tiki enthusiasts seeking something more sophisticated than typical tropical drinks. Ideal for cocktail connoisseurs who appreciate complexity and balance. A great choice for those who find standard tiki drinks too sweet."}}'::jsonb, '[{"ingredient_id":"ING_RUM_GOLD","quantity":{"amount":45,"unit":"ml"},"display_name":"Gold rum","notes":null},{"ingredient_id":"ING_PLUM_BRANDY","quantity":{"amount":15,"unit":"ml"},"display_name":"Plum brandy (slivovitz)","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":22,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":22,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_ORGEAT","quantity":{"amount":15,"unit":"ml"},"display_name":"Orgeat syrup","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well chilled. Strain into a tiki mug or old fashioned glass filled with crushed ice. Garnish with lime wheel and fresh mint sprig."}'::jsonb, 'Tiki mug / Old fashioned glass', '{"en":"Lime wheel and fresh mint sprig"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_RUM_GOLD"}', '{"fruity","tart","complex"}', 16, 200, 'medium', 120, '{"sulphites","tree_nuts"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"summer","spring","year_round"}', '{"tiki_bar","cocktail_appreciation","date_night"}', false, false, '{"trader-vic-original"}', 'Classic Trader Vic''s creation. Plum brandy (slivovitz) is essential - don''t substitute. Orgeat contains almonds. Less sweet than typical tiki drinks - appeals to sophisticated palates. Fresh juices crucial for balance.', 'mid', 60, 'https://www.smugglerscovesf.com/store/smugglers-cove-exotic-cocktails-rum-and-the-cult-of-tiki', 'Classic Trader Vic recipe. From tiki cocktail history archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 219. Trinidad Especial


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('77625525-56be-4c3b-8b77-329284b646a9', 'trinidad-especial', '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a07', '{"en":"Trinidad Especial"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","rum","bitter","complex"}', '{"en":"An audacious cocktail featuring Angostura bitters as the primary ingredient, balanced with orgeat, rye whiskey, and lemon juice. The Trinidad Especial is a bold, spice-forward drink that challenges cocktail conventions."}'::jsonb, '{"created_year":"2009","origin":{"city":"San Francisco","bar":"Clyde Common","country":"USA"},"creator":{"name":"Giuseppe González","profession":"bartender"},"story":{"en":"Created by Giuseppe González in 2009 while working at Clyde Common in San Francisco, the Trinidad Especial is one of the most unusual modern classics. González boldly flipped traditional proportions by using a full 1.5 ounces of Angostura bitters as the base spirit - something previously unheard of. The result is a surprisingly balanced cocktail that showcases the complex spice notes of Angostura bitters. The drink quickly gained cult status among adventurous bartenders and cocktail enthusiasts."},"named_after":{"en":"Named after Trinidad, where Angostura bitters are produced. \"Especial\" emphasizes the drink''s special, unconventional character."}}'::jsonb, '{"profile":["spicy","bitter","complex"],"description":{"en":"Intensely aromatic and spicy with surprising balance. The dominant Angostura bitters provide warm spice notes of cinnamon, clove, and gentian. Orgeat adds almond sweetness and creamy texture, while rye whiskey and lemon juice provide structure and brightness."},"first_impression":{"en":"Bold bitters and warm spices hit immediately, followed by almond sweetness and whiskey depth"},"finish":{"en":"Long, warming finish with lingering baking spices and almond notes"},"balance":{"en":"Remarkably balanced despite unconventional proportions - orgeat sweetness tames the intense bitters"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["cocktail_hour","special_occasion","adventurous_tasting"],"seasons":["autumn","winter"],"food_pairings":{"en":"Excellent with spiced desserts, dark chocolate, roasted nuts, and strong cheeses. The complex spice profile complements rich, bold flavors."},"ideal_for":{"en":"Perfect for adventurous drinkers who appreciate bold, unconventional cocktails. Ideal for bitters enthusiasts and those seeking truly unique experiences."}}'::jsonb, '[{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":45,"unit":"ml"},"display_name":"Angostura bitters","notes":null},{"ingredient_id":"ING_ORGEAT","quantity":{"amount":30,"unit":"ml"},"display_name":"Orgeat","notes":null},{"ingredient_id":"ING_RYE_WHISKEY","quantity":{"amount":15,"unit":"ml"},"display_name":"Rye whiskey","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a chilled coupe glass. Garnish with a lemon twist."}'::jsonb, 'Coupe', '{"en":"Lemon twist"}'::jsonb, 'none', 'up', '{"ING_ANGOSTURA_BITTERS"}', '{"spicy","bitter","complex"}', 26, 175, 'medium', 90, '{"tree_nuts","sulphites"}', '{"alcohol","sulphites_intolerance","nut_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free"}', 3, '{"vegan","gluten-free","dairy-free"}', '{"autumn","winter"}', '{"cocktail_hour","special_occasion","adventurous_tasting"}', false, false, '{"trinidad-sour"}', 'Yes, the recipe calls for 1.5 oz of Angostura bitters as the base! This is intentional and creates the signature character. Use quality orgeat (preferably house-made). Warn guests about the unconventional nature before serving.', 'mid', 65, 'Created by Giuseppe González, 2009', 'One of the most unconventional modern classics. Featured in numerous cocktail publications.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 220. Tropical Itch


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('0203b337-f66a-4541-afa4-557de9a84bdd', 'tropical-itch', 'tropical-itch-tiki-tropical-famous-2025', '{"en":"Tropical Itch"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","bourbon","exotic","theatrical"}', '{"en":"A unique tiki cocktail combining rum and bourbon with tropical juices and passion fruit. Famously served with a bamboo back scratcher as a swizzle stick, the Tropical Itch offers a complex blend of Caribbean and American spirits in a theatrical presentation."}'::jsonb, '{"created_year":"1950s","origin":{"city":"Honolulu","bar":"Hawaiian Village Hotel","country":"USA"},"creator":{"name":"Harry Yee","profession":"bartender"},"story":{"en":"The Tropical Itch was created in the 1950s by legendary Hawaiian bartender Harry Yee at the Hawaiian Village Hotel in Waikiki, Honolulu. Yee, who is also credited with creating the Blue Hawaii and being the first to garnish drinks with orchids and paper umbrellas, designed this drink to be both delicious and memorable. The signature element is the bamboo back scratcher that serves as the swizzle stick - a playful nod to the drink''s name and a theatrical touch that made it instantly recognizable. The unusual combination of rum and bourbon was innovative for its time, creating a bridge between tiki culture and classic American cocktails."},"named_after":{"en":"Named for the bamboo back scratcher used as a swizzle stick, playfully suggesting the drink is so good it gives you an irresistible \"itch\" to have another."}}'::jsonb, '{"profile":["fruity","tropical","complex"],"description":{"en":"Complex and layered with tropical passion fruit, citrus brightness, rum sweetness, and bourbon depth. The combination of rum and bourbon creates an unusual but harmonious flavor profile that''s both exotic and familiar. Rich, fruity, and surprisingly sophisticated."},"first_impression":{"en":"Bright tropical passion fruit and citrus with underlying bourbon oakiness"},"finish":{"en":"Long, complex finish with tropical fruit, bourbon warmth, and subtle spice"},"balance":{"en":"Expertly balanced between tropical sweetness and bourbon complexity - unique flavor profile unlike typical tiki drinks"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["tiki_bar","special_occasion","cocktail_appreciation","hawaiian_theme"],"seasons":["summer","year_round"],"food_pairings":{"en":"Pairs excellently with Hawaiian poke, teriyaki dishes, grilled pineapple, kalua pork, or tropical fruit platters. Also complements American BBQ surprisingly well due to the bourbon component."},"ideal_for":{"en":"Perfect for tiki enthusiasts and bourbon lovers seeking something unique. Ideal for Hawaiian-themed parties or those who appreciate theatrical cocktail presentation. Great for adventurous drinkers who enjoy complex, unexpected flavor combinations."}}'::jsonb, '[{"ingredient_id":"ING_RUM_DARK","quantity":{"amount":30,"unit":"ml"},"display_name":"Dark rum","notes":null},{"ingredient_id":"ING_BOURBON","quantity":{"amount":30,"unit":"ml"},"display_name":"Bourbon whiskey","notes":null},{"ingredient_id":"ING_PASSION_FRUIT_SYRUP","quantity":{"amount":30,"unit":"ml"},"display_name":"Passion fruit syrup","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":60,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well chilled. Strain into a tall tiki glass or hurricane glass filled with crushed ice. Garnish with pineapple wedge, cherry, and the signature bamboo back scratcher swizzle stick."}'::jsonb, 'Tiki glass / Hurricane glass', '{"en":"Pineapple wedge, maraschino cherry, and bamboo back scratcher"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_RUM_DARK","ING_BOURBON"}', '{"fruity","tropical","complex"}', 15, 260, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"summer","year_round"}', '{"tiki_bar","special_occasion","cocktail_appreciation"}', false, false, '{"virgin-tropical-itch"}', 'Created by Harry Yee, inventor of Blue Hawaii. Signature bamboo back scratcher is essential for authentic presentation. Unusual rum-bourbon combo - explain to curious guests. Use fresh juices for best results. Theatrical presentation makes great conversation starter.', 'mid', 65, 'https://www.diffordsguide.com/cocktails/recipe/4686/tropical-itch', 'Classic Harry Yee creation from Hawaiian Village Hotel, Honolulu.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 221. Twentieth Century


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('53122ab7-470a-4a45-a5a1-89da7ed645bd', 'twentieth-century', 'c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4', '{"en":"Twentieth Century"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","gin","elegant","white"}', '{"en":"An elegant white cocktail featuring gin, Lillet Blanc, white crème de cacao, and lemon juice. The Twentieth Century is a sophisticated blend of botanical, floral, and subtle chocolate notes with bright citrus balance."}'::jsonb, '{"created_year":"1937","origin":{"city":"London","bar":"Unknown","country":"UK"},"creator":{"name":"C.A. Tuck","profession":"bartender"},"story":{"en":"Created by British bartender C.A. Tuck and published in the \"Café Royal Cocktail Book\" (1937). Named after the luxurious 20th Century Limited train that ran between New York and Chicago from 1902-1967. This cocktail celebrates the glamour and sophistication of early 20th-century luxury travel. The white color evokes the train''s elegant dining cars and Art Deco aesthetic."},"named_after":{"en":"Named after the legendary 20th Century Limited luxury train that symbolized elegance, speed, and sophistication in early 20th-century America."}}'::jsonb, '{"profile":["elegant","floral","citrus"],"description":{"en":"Sophisticated and elegant with gin botanicals, Lillet''s floral-wine notes, subtle white chocolate from crème de cacao, and bright lemon acidity. Delicate yet complex with a beautiful white appearance."},"first_impression":{"en":"Bright lemon and floral Lillet notes with subtle chocolate hints"},"finish":{"en":"Clean, elegant finish with lingering botanicals and gentle sweetness"},"balance":{"en":"Perfectly balanced elegance - bright yet subtle, complex yet refined"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["brunch","aperitivo","date_night","celebration"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with light seafood, oysters, delicate desserts, or as an elegant aperitif. Pairs beautifully with French cuisine and white chocolate."},"ideal_for":{"en":"Perfect for gin lovers seeking elegant, white cocktails with subtle complexity. Ideal for those who appreciate delicate flavors and sophisticated presentation."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":45,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_LILLET_BLANC","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Lillet Blanc","notes":null},{"ingredient_id":"ING_WHITE_CREME_DE_CACAO","quantity":{"amount":15,"unit":"ml"},"display_name":"White crème de cacao","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Double strain into a chilled coupe or cocktail glass. Garnish with a lemon twist, expressing the oils over the drink."}'::jsonb, 'Coupe glass', '{"en":"Lemon twist"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"elegant","floral","citrus"}', 22, 170, 'easy', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"brunch","aperitivo","date_night","celebration"}', false, false, '{"twentieth-century-moderne"}', 'Use WHITE crème de cacao to maintain the elegant white color. Lillet Blanc essential - do not substitute with vermouth. Double strain for perfect clarity. Fresh lemon juice only. The drink should be pristine white like the train''s dining cars.', 'mid', 60, 'https://www.diffordsguide.com/cocktails/recipe/1556/twentieth-century-cocktail', 'Café Royal Cocktail Book (1937). Named after the legendary 20th Century Limited luxury train.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


