INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('1869cd4a-371f-4b42-90f0-ec414ce0b04f', 'bees-kiss', 'e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4', '{"en":"Bee''s Kiss"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","rum","sweet","creamy"}', '{"en":"A luscious Prohibition-era cocktail featuring rum, honey, and heavy cream. The Bee''s Kiss is a forgotten classic that delivers smooth sweetness with a velvety texture and tropical warmth."}'::jsonb, '{"created_year":"1930","origin":{"city":"Unknown","bar":"Unknown","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Bee''s Kiss appeared in the early 1930s as Prohibition was ending. Featured in Frank Meier''s \"The Artistry of Mixing Drinks\" (1936), this cocktail was part of the \"Bee''s Knees\" family of drinks that used honey to sweeten and mask lower-quality spirits. The creamy version became popular in Cuba and eventually made its way to American cocktail bars."},"named_after":{"en":"Named after the sweetness of a bee''s kiss, referencing the honey used in the recipe and the smooth, sweet character of the drink."}}'::jsonb, '{"profile":["sweet","creamy","smooth"],"description":{"en":"Rich and velvety with honey sweetness balanced by the warmth of rum and smoothness of cream. A decadent, dessert-like cocktail with tropical undertones."},"first_impression":{"en":"Creamy honey sweetness upfront with gentle rum warmth"},"finish":{"en":"Smooth, lingering honey finish with subtle rum spice"},"balance":{"en":"Well-balanced between sweetness and spirit - indulgent but not cloying"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["date_night","dessert","nightcap","special_occasion"],"seasons":["autumn","winter"],"food_pairings":{"en":"Excellent with chocolate desserts, banana foster, crème brûlée, or as a dessert replacement. Pairs well with tropical fruits and caramelized sweets."},"ideal_for":{"en":"Perfect for rum lovers who enjoy creamy, dessert-style cocktails. Ideal for those seeking a sweet, indulgent drink with vintage charm."}}'::jsonb, '[{"ingredient_id":"ING_WHITE_RUM","quantity":{"amount":45,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_HEAVY_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Heavy cream","notes":null},{"ingredient_id":"ING_HONEY_SYRUP","quantity":{"amount":15,"unit":"ml"},"display_name":"Honey syrup","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake vigorously until well-chilled and properly emulsified. Strain into a chilled coupe glass. No garnish needed."}'::jsonb, 'Coupe glass', '{"en":"None"}'::jsonb, 'none', 'up', '{"ING_WHITE_RUM"}', '{"sweet","creamy","smooth"}', 15, 240, 'easy', 60, '{"milk","sulphites"}', '{"lactose","alcohol","sulphites_intolerance"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 0, '{"vegetarian","gluten-free"}', '{"autumn","winter"}', '{"date_night","dessert","nightcap","special_occasion"}', false, false, '{"bees-knees","gold-rush"}', 'Shake hard to properly emulsify cream with honey. Use honey syrup (3:1 honey to water) for easier mixing. Can substitute aged rum for deeper flavor. Ensure all ingredients are well-chilled before shaking.', 'mid', 55, 'https://www.diffordsguide.com/cocktails/recipe/384/bees-kiss', 'Based on Frank Meier''s 1936 recipe. Historical information from vintage cocktail books.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 122. Bijou


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('b079dc71-8004-44af-a431-f16160f50bc6', 'bijou', 'f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5', '{"en":"Bijou"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","gin","complex","botanical"}', '{"en":"An elegant cocktail combining gin, green Chartreuse, and sweet vermouth with a dash of orange bitters. Named after the French word for \"jewel,\" the Bijou is a sophisticated blend of botanical, herbal, and sweet flavors."}'::jsonb, '{"created_year":"1900","origin":{"city":"Unknown","bar":"Unknown","country":"USA"},"creator":{"name":"Harry Johnson","profession":"bartender"},"story":{"en":"The Bijou first appeared in Harry Johnson''s \"Bartender''s Manual\" in 1900. The name references the three \"jewel-colored\" liqueurs: gin (diamond), green Chartreuse (emerald), and sweet vermouth (ruby). This cocktail represents the golden age of bartending when complex, spirit-forward drinks were highly prized."},"named_after":{"en":"French for \"jewel,\" referencing the three jewel-colored ingredients: diamond (gin), emerald (Chartreuse), and ruby (vermouth)."}}'::jsonb, '{"profile":["complex","herbal","botanical"],"description":{"en":"Intensely complex with herbal green Chartreuse, botanical gin, and sweet vermouth creating layers of flavor. Bold, aromatic, and beautifully balanced with a long, sophisticated finish."},"first_impression":{"en":"Powerful herbal Chartreuse and juniper hit immediately with sweet vermouth rounding"},"finish":{"en":"Long, warming finish with complex herbal and botanical notes lingering"},"balance":{"en":"Perfectly balanced trinity of herbal, botanical, and sweet - bold yet harmonious"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["aperitivo","date_night","digestivo","special_occasion"],"seasons":["autumn","winter"],"food_pairings":{"en":"Excellent with aged cheeses, charcuterie, roasted game, or dark chocolate. Perfect as a digestif after rich meals."},"ideal_for":{"en":"Perfect for adventurous drinkers who appreciate complex, spirit-forward cocktails. An excellent choice for gin lovers seeking something more sophisticated than a martini."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":30,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_GREEN_CHARTREUSE","quantity":{"amount":30,"unit":"ml"},"display_name":"Green Chartreuse","notes":null},{"ingredient_id":"ING_SWEET_VERMOUTH","quantity":{"amount":30,"unit":"ml"},"display_name":"Sweet vermouth","notes":null},{"ingredient_id":"ING_ORANGE_BITTERS","quantity":{"amount":1,"unit":"dash"},"display_name":"Orange bitters","notes":null}]'::jsonb, 'stir', '{"en":"Add all ingredients to a mixing glass filled with ice. Stir gently for 30-40 seconds until well-chilled. Strain into a chilled coupe or Nick & Nora glass. Garnish with a lemon twist, expressing the oils over the drink."}'::jsonb, 'Coupe glass', '{"en":"Lemon twist"}'::jsonb, 'none', 'up', '{"ING_GIN","ING_GREEN_CHARTREUSE"}', '{"complex","herbal","botanical"}', 28, 190, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"autumn","winter"}', '{"aperitivo","date_night","digestivo","special_occasion"}', false, false, '{"bijou-moderne","reverse-bijou"}', 'Equal parts recipe creates perfect balance. Stir gently to avoid over-dilution given the potency of ingredients. Green Chartreuse is essential - yellow Chartreuse is NOT a substitute. Express lemon oils generously for aromatic impact.', 'premium', 60, 'https://www.diffordsguide.com/cocktails/recipe/353/bijou-cocktail', 'Harry Johnson''s 1900 Bartender''s Manual. Historical cocktail from the golden age of bartending.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 123. Blood and Sand


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('f6b9969e-f02d-4fe2-b062-1849c972a077', 'blood-and-sand', 'g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6', '{"en":"Blood and Sand"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","scotch","fruity","complex","unusual"}', '{"en":"One of the few classic cocktails to feature Scotch whisky, the Blood and Sand combines unexpected ingredients - Scotch, sweet vermouth, cherry liqueur, and orange juice - into a surprisingly harmonious and complex drink. Named after a 1922 bullfighting film, it''s as dramatic as its namesake."}'::jsonb, '{"created_year":"1922","origin":{"city":"London","bar":"Unknown","country":"United Kingdom"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Blood and Sand first appeared in Harry Craddock''s \"The Savoy Cocktail Book\" in 1930, though it was likely created around 1922 to coincide with the release of the Rudolph Valentino film of the same name. The film, about a matador torn between two women, was a major hit, and the cocktail''s dramatic red-orange color evokes the blood and sand of the bullring. The drink fell into obscurity for decades but experienced a revival in the 2000s when bartenders rediscovered its surprisingly balanced flavor profile. The equal-parts recipe creates an unexpected harmony between smoky Scotch, sweet cherry, bitter vermouth, and bright orange."},"named_after":{"en":"Named after the 1922 silent film \"Blood and Sand\" starring Rudolph Valentino as a Spanish bullfighter."}}'::jsonb, '{"profile":["fruity","complex","smoky"],"description":{"en":"A fascinating balance of contrasting flavors. The Blood and Sand is simultaneously smoky, sweet, fruity, and herbal. The Scotch provides a smoky backbone, cherry liqueur adds sweetness and depth, vermouth contributes herbal complexity, and orange juice brings brightness and acidity. It''s unexpectedly harmonious."},"first_impression":{"en":"Sweet cherry and orange fruit forward, followed by smoky Scotch complexity"},"finish":{"en":"Medium finish with lingering smoke, cherry sweetness, and herbal notes"},"balance":{"en":"The equal-parts formula creates surprising balance - each ingredient is distinct yet harmonious"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["sophisticated","date_night","aperitivo","conversation"],"seasons":["autumn","winter","spring"],"food_pairings":{"en":"Pairs well with charcuterie, aged cheeses, duck, game meats, and chocolate desserts. Also excellent with Spanish tapas and Mediterranean cuisine."},"ideal_for":{"en":"Perfect for adventurous cocktail enthusiasts who appreciate complex, unusual flavor combinations. Ideal for Scotch lovers looking for something different and bartenders who want to showcase creativity."}}'::jsonb, '[{"ingredient_id":"ING_SCOTCH_WHISKY","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Scotch whisky","notes":null},{"ingredient_id":"ING_SWEET_VERMOUTH","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Sweet vermouth","notes":null},{"ingredient_id":"ING_CHERRY_HEERING","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Cherry Heering","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh orange juice","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake well until chilled. Strain into a chilled coupe or cocktail glass. No garnish needed, though an orange twist is optional."}'::jsonb, 'Coupe or Cocktail glass', '{"en":"None (or optional orange twist)"}'::jsonb, 'none', 'up', '{"ING_SCOTCH_WHISKY"}', '{"fruity","complex","smoky"}', 20, 180, 'medium', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","nut_free","dairy_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"autumn","winter","spring"}', '{"sophisticated","date_night","aperitivo","conversation"}', false, false, '{"bobby-burns","modern-blood-and-sand"}', 'Use fresh orange juice - bottled won''t work. Cherry Heering is traditional, but other cherry liqueurs can substitute. Use a blended Scotch, not single malt. The equal-parts formula is classic, but some prefer 1.5 parts Scotch for more whisky presence. Always shake vigorously to properly integrate.', 'mid', 55, 'https://www.diffordsguide.com/cocktails/recipe/312/blood-and-sand', 'Classic recipe from Harry Craddock''s The Savoy Cocktail Book (1930).', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 124. Blue Hawaiian


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('a6d6e70a-b890-468a-8fd3-6576354e6a60', 'blue-hawaiian', 'blue_hawaiian_famous_tiki_tropical_cocktail', '{"en":"Blue Hawaiian"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","creamy","sweet","blue"}', '{"en":"The Blue Hawaiian is a vibrant tropical cocktail featuring rum, blue curaçao, pineapple juice, and cream of coconut. Its striking blue color evokes Hawaiian waters, making it a visually stunning and deliciously tropical vacation drink."}'::jsonb, '{"created_year":"1957","origin":{"city":"Honolulu","bar":"Hilton Hawaiian Village","country":"USA"},"creator":{"name":"Harry Yee","profession":"bartender"},"story":{"en":"The Blue Hawaiian was created in 1957 by legendary bartender Harry Yee at the Hilton Hawaiian Village in Waikiki. Yee invented the drink as a showcase for Bols Blue Curaçao, which had just been introduced to Hawaii. The stunning blue color was meant to evoke the crystal-clear Hawaiian waters. Harry Yee is also credited with being the first bartender to garnish drinks with orchids and paper umbrellas, innovations that became synonymous with tiki culture. The Blue Hawaiian became an instant classic and remains one of Hawaii''s signature cocktails."},"named_after":{"en":"Named for the vibrant blue color reminiscent of Hawaiian ocean waters and tropical paradise."}}'::jsonb, '{"profile":["tropical","creamy","sweet"],"description":{"en":"Tropical and refreshing with a perfect balance of citrus and coconut. The Blue Hawaiian combines bright orange notes from blue curaçao with pineapple sweetness and coconut creaminess, all lifted by rum. Smooth, creamy, and undeniably tropical."},"first_impression":{"en":"Sweet tropical fruits and orange citrus hit first, followed by creamy coconut waves"},"finish":{"en":"Smooth, creamy finish with lingering coconut and tropical fruit notes"},"balance":{"en":"Well-balanced between sweet tropical flavors and creamy texture, with rum providing subtle backbone"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["beach","pool_party","luau","vacation"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with Hawaiian poke, kalua pork, grilled fish, coconut shrimp, or tropical fruit platters. Also pairs well with teriyaki dishes and island-style BBQ."},"ideal_for":{"en":"Perfect for tropical vacation seekers and Instagram-worthy drink enthusiasts. Ideal for anyone who wants a visually stunning cocktail that tastes as good as it looks. Great for pool parties and beachside celebrations."}}'::jsonb, '[{"ingredient_id":"ING_RUM_WHITE","quantity":{"amount":45,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_BLUE_CURACAO","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Blue curaçao","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":90,"unit":"ml"},"display_name":"Pineapple juice","notes":null},{"ingredient_id":"ING_COCONUT_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Cream of coconut","notes":null}]'::jsonb, 'blend', '{"en":"Add all ingredients to a blender with 1 cup of crushed ice. Blend until smooth and creamy. Pour into a hurricane glass. Garnish with pineapple wedge and maraschino cherry."}'::jsonb, 'Hurricane glass', '{"en":"Pineapple wedge, maraschino cherry, orchid flower"}'::jsonb, 'blended', 'frozen', '{"ING_RUM_WHITE"}', '{"tropical","creamy","sweet"}', 10, 300, 'easy', 120, '{"coconut","sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"beach","pool_party","luau","vacation"}', false, false, '{"blue-hawaii","swimming-pool"}', 'Created by Harry Yee, pioneer of tiki garnishes. Can be shaken instead of blended for a non-frozen version. The vibrant blue color is essential - use quality blue curaçao. Garnish with orchid if available for authentic Hawaiian presentation.', 'mid', 88, 'https://www.diffordsguide.com/cocktails/recipe/506/blue-hawaiian', 'Created by Harry Yee at Hilton Hawaiian Village, 1957. Historical information from tiki cocktail archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 125. Blue Lagoon


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('02105a27-0358-4615-9d7d-5c3ab91bb56b', 'blue-lagoon', 'blue-lagoon-tiki-tropical-famous-2025', '{"en":"Blue Lagoon"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","vodka","blue-curacao","colorful","instagram"}', '{"en":"A visually stunning cocktail featuring vodka, blue curaçao, and lemonade, creating an electric blue color reminiscent of tropical lagoons. The Blue Lagoon is as beautiful as it is refreshing, delivering citrus sweetness with a vibrant presentation."}'::jsonb, '{"created_year":"1960s","origin":{"city":"Paris","bar":"Harry''s New York Bar","country":"France"},"creator":{"name":"Andy MacElhone","profession":"bartender"},"story":{"en":"The Blue Lagoon was created in the 1960s by Andy MacElhone at Harry''s New York Bar in Paris, the same legendary establishment that gave us the Bloody Mary and French 75. The cocktail was designed to showcase blue curaçao, a liqueur that was gaining popularity at the time. Its striking electric blue color made it an instant hit, especially as color photography became more prevalent in advertising. The drink gained even more fame when it shared its name with the 1980 film \"The Blue Lagoon,\" starring Brooke Shields."},"named_after":{"en":"Named for its stunning electric blue color that evokes crystal-clear tropical lagoons and azure waters of paradise islands."}}'::jsonb, '{"profile":["citrus","sweet","refreshing"],"description":{"en":"Sweet and citrusy with orange notes from the blue curaçao and tart lemon from the lemonade. The vodka provides a clean, neutral base. Light, refreshing, and crowd-pleasing with a beautiful tropical character."},"first_impression":{"en":"Bright lemon sweetness with orange citrus notes from curaçao"},"finish":{"en":"Clean, crisp finish with lingering citrus and subtle vodka warmth"},"balance":{"en":"Well-balanced sweetness with bright citrus acidity - refreshing without being cloying"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["pool_party","beach","celebration","instagram","summer_gathering"],"seasons":["summer","spring"],"food_pairings":{"en":"Pairs well with light appetizers, seafood, grilled fish, tropical fruit platters, or coconut shrimp. Also excellent with Asian fusion cuisine and sushi."},"ideal_for":{"en":"Perfect for pool parties, beach gatherings, and tropical-themed events. Ideal for those who love visually striking cocktails and sweet, easy-drinking beverages. A guaranteed Instagram hit and conversation starter."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":45,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_BLUE_CURACAO","quantity":{"amount":30,"unit":"ml"},"display_name":"Blue curaçao","notes":null},{"ingredient_id":"ING_LEMONADE","quantity":{"amount":90,"unit":"ml"},"display_name":"Lemonade","notes":null}]'::jsonb, 'build', '{"en":"Fill a highball glass with ice. Add vodka and blue curaçao. Top with lemonade and stir gently. Garnish with lemon wheel and maraschino cherry."}'::jsonb, 'Highball glass', '{"en":"Lemon wheel and maraschino cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA"}', '{"citrus","sweet","refreshing"}', 10, 200, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"summer","spring"}', '{"pool_party","beach","celebration","instagram"}', false, false, '{"electric-lemonade","blue-hawaiian","swimming-pool"}', 'Very easy to make and visually stunning. The electric blue color is the main attraction. Can substitute Sprite for lemonade if unavailable. Popular for Instagram photos - ensure good presentation. Some recipes use lemon-lime soda instead of lemonade.', 'low', 80, 'https://www.liquor.com/recipes/blue-lagoon/', 'Classic cocktail from Harry''s New York Bar, Paris. Recipe variations exist.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 126. Brandy Alexander


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('01a41d85-480f-4b31-9ba0-ee98f10e9088', 'brandy-alexander', 'brandy_alexander_cognac_cacao_cream', '{"en":"Brandy Alexander"}'::jsonb, 'famous', NULL, '{"creamy","dessert","famous","classic","chocolate","brandy-based"}', '{"en":"The most popular variation of the Alexander, made with brandy (or cognac) instead of gin. This elegant, creamy cocktail combines the warmth of brandy with the richness of chocolate and cream, creating a sophisticated after-dinner indulgence."}'::jsonb, '{"created_year":"1920s","origin":{"city":"London","country":"England"},"story":{"en":"The Brandy Alexander emerged in the 1920s-30s as a more refined variation of the original gin-based Alexander. While the exact origin is debated, it became the definitive version of the drink, especially popular during the mid-20th century. The cocktail enjoyed particular fame after being featured in the film \"Days of Wine and Roses\" (1962) and was reportedly a favorite of John Lennon. Its popularity peaked in the 1970s as a glamorous after-dinner drink."},"named_after":{"en":"Named after the original Alexander cocktail, with \"Brandy\" added to distinguish it from the gin-based version."}}'::jsonb, '{"profile":["creamy","sweet","chocolate","boozy"],"description":{"en":"Luxuriously smooth and velvety with a perfect marriage of chocolate, cream, and warming brandy. More complex than its gin-based predecessor, with deeper, richer flavors and a sophisticated finish."},"first_impression":{"en":"Silky chocolate cream followed immediately by warm brandy notes"},"finish":{"en":"Long, warming finish with nutmeg spice and lingering cocoa"},"balance":{"en":"Beautifully balanced between sweetness, cream, and spirit - more sophisticated than most dessert cocktails"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["digestivo","date_night","celebration","nightcap"],"seasons":["autumn","winter","all_seasons"],"food_pairings":{"en":"Excellent with chocolate desserts, crème brûlée, tiramisu, or as a dessert replacement. Pairs beautifully with aged cheese, chocolate truffles, and espresso."},"ideal_for":{"en":"Perfect for brandy and cognac lovers who appreciate creamy, indulgent cocktails. Ideal for those seeking a sophisticated dessert drink with historical pedigree. A classic choice for elegant dinners and special occasions."}}'::jsonb, '[{"ingredient_id":"ING_COGNAC","quantity":{"amount":40,"unit":"ml"},"display_name":"Cognac (or Brandy)","notes":null},{"ingredient_id":"ING_CREME_DE_CACAO_DARK","quantity":{"amount":30,"unit":"ml"},"display_name":"Crème de Cacao (dark)","notes":null},{"ingredient_id":"ING_HEAVY_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Heavy cream","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously for 10-15 seconds until well-chilled and frothy. Double strain into a chilled coupe or martini glass. Grate fresh nutmeg over the top."}'::jsonb, 'Coupe (or Martini)', '{"en":"Freshly grated nutmeg"}'::jsonb, 'none', 'up', '{"ING_COGNAC"}', '{"creamy","sweet","chocolate","boozy"}', 20, 290, 'easy', 60, '{"milk","sulphites"}', '{"lactose","alcohol","sulphites_intolerance"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 0, '{"vegetarian","gluten-free"}', '{"autumn","winter","all-seasons"}', '{"digestivo","date-night","celebration","nightcap"}', false, false, '{"alexander","coffee-alexander","alexander-sister"}', 'This is the more popular version of the Alexander. Always use freshly grated nutmeg. Shake hard to properly emulsify cream. Can use quality brandy instead of cognac for cost savings. Some recipes call for equal parts (30ml each) - adjust to guest preference.', 'mid', 70, 'https://www.diffordsguide.com/cocktails/recipe/253/brandy-alexander', 'Classic variation of the Alexander, more popular than the original gin-based version.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 127. Bronx


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('7b4d0294-c3cc-4970-b6a5-08b43b29280b', 'bronx', 'k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0', '{"en":"Bronx"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","gin","citrus","vermouth","pre-prohibition"}', '{"en":"A perfect martini meets orange juice in this pre-Prohibition classic. The Bronx combines gin with both sweet and dry vermouth plus fresh orange juice, creating a sophisticated yet approachable cocktail. Once America''s third most popular cocktail, it deserves a comeback."}'::jsonb, '{"created_year":"1906","origin":{"city":"Philadelphia","bar":"Waldorf-Astoria Hotel","country":"USA"},"creator":{"name":"Johnnie Solon","profession":"bartender"},"story":{"en":"The Bronx was created around 1906 by bartender Johnnie Solon at the Waldorf-Astoria Hotel''s bar (then located in Philadelphia). According to Solon, a customer asked him to create something new, and inspiration struck after a recent visit to the Bronx Zoo. The cocktail combines gin, sweet and dry vermouth, and orange juice - essentially a Perfect Martini with orange juice added. It became wildly popular in the 1910s and 1920s, rivaling the Martini and Manhattan in popularity. Albert Stevens Crockett wrote in \"Old Waldorf Bar Days\" (1931) that \"the Bronx was to the cocktail world what the zipper has been to the clothing industry.\" However, after Prohibition, the drink faded from prominence as vodka-based cocktails rose to dominance. Modern bartenders are rediscovering its elegant balance."},"named_after":{"en":"Named after the Bronx Zoo in New York, which bartender Johnnie Solon had recently visited when he created the drink."}}'::jsonb, '{"profile":["citrus","herbal","balanced"],"description":{"en":"Bright, citrusy, and beautifully complex. The Bronx balances gin''s botanicals with the herbal complexity of both vermouths, while fresh orange juice adds fruity brightness without overwhelming. It''s like a sophisticated orange creamsicle for grown-ups."},"first_impression":{"en":"Fresh orange juice brightness followed by gin botanicals and herbal vermouth"},"finish":{"en":"Medium finish with lingering orange, juniper, and subtle vermouth complexity"},"balance":{"en":"Expertly balanced between spirit, citrus, and vermouth - each element distinct yet harmonious"}}'::jsonb, '{"best_time":["brunch","afternoon","early_evening"],"occasions":["brunch","aperitivo","social","sophisticated"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Perfect with brunch classics: eggs Benedict, smoked salmon, French toast, and fruit salads. Also pairs well with light seafood, salads, and Mediterranean cuisine."},"ideal_for":{"en":"Perfect for gin enthusiasts who want something more approachable than a martini. Ideal for brunch gatherings and those exploring pre-Prohibition cocktail history. A great choice for orange juice lovers seeking sophistication."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":45,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_SWEET_VERMOUTH","quantity":{"amount":15,"unit":"ml"},"display_name":"Sweet vermouth","notes":null},{"ingredient_id":"ING_DRY_VERMOUTH","quantity":{"amount":15,"unit":"ml"},"display_name":"Dry vermouth","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh orange juice","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a chilled cocktail glass. Garnish with an orange twist."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"Orange twist"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"citrus","herbal","balanced"}', 18, 155, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","nut_free","dairy_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"spring","summer","autumn"}', '{"brunch","aperitivo","social","sophisticated"}', false, false, '{"income-tax","satan-whiskers","golden-bronx"}', 'Must use fresh orange juice - never bottled or concentrate. The classic ratio is 3:1:1:1.5 (gin:sweet vermouth:dry vermouth:orange juice). Use quality vermouths and keep them fresh. Shake hard to properly integrate the orange juice.', 'mid', 50, 'https://www.diffordsguide.com/cocktails/recipe/358/bronx', 'Classic recipe from Waldorf-Astoria (1906), documented in various early 20th century cocktail books.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 128. Brown Derby


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('ce1707a4-7898-43a9-945b-175e0d0bea99', 'brown-derby', '5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a11', '{"en":"Brown Derby"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","bourbon","citrus","refreshing"}', '{"en":"A simple yet sophisticated bourbon cocktail featuring grapefruit juice and honey syrup. The Brown Derby is a refreshing, citrus-forward drink with a touch of sweetness that became a Hollywood favorite."}'::jsonb, '{"created_year":"1930","origin":{"city":"Los Angeles","bar":"Brown Derby Restaurant","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"Created at the legendary Brown Derby Restaurant in Los Angeles during the 1930s, this cocktail became a favorite among Hollywood celebrities. The Brown Derby was one of the most famous restaurants of the Golden Age of Hollywood, frequented by stars like Clark Gable and Greta Garbo. The cocktail''s simple recipe of bourbon, grapefruit, and honey created a refreshing drink that matched the California lifestyle. After falling into obscurity, it was rediscovered during the modern cocktail renaissance."},"named_after":{"en":"Named after the Brown Derby Restaurant, a Hollywood landmark famous for its distinctive hat-shaped building."}}'::jsonb, '{"profile":["citrus","sweet","refreshing"],"description":{"en":"Bright and refreshing with balanced sweetness. Bourbon provides a warm, oaky backbone, fresh grapefruit juice adds tart citrus notes, and honey syrup brings natural sweetness and smooth texture. The combination is deceptively simple but perfectly balanced."},"first_impression":{"en":"Tart grapefruit and honey sweetness hit first, followed by warming bourbon"},"finish":{"en":"Clean, refreshing finish with lingering citrus and subtle honey notes"},"balance":{"en":"Perfectly balanced between tart grapefruit and sweet honey, with bourbon providing depth"}}'::jsonb, '{"best_time":["afternoon","early_evening"],"occasions":["brunch","poolside","summer_party","casual_gathering"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with brunch dishes, grilled chicken, citrus salads, and light seafood. The bright citrus complements fresh, summery flavors."},"ideal_for":{"en":"Perfect for bourbon lovers seeking a lighter, more refreshing serve. Ideal for those who enjoy citrus-forward cocktails with natural sweetness."}}'::jsonb, '[{"ingredient_id":"ING_BOURBON","quantity":{"amount":45,"unit":"ml"},"display_name":"Bourbon","notes":null},{"ingredient_id":"ING_GRAPEFRUIT_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Fresh grapefruit juice","notes":null},{"ingredient_id":"ING_HONEY_SYRUP","quantity":{"amount":15,"unit":"ml"},"display_name":"Honey syrup (1:1)","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a chilled coupe glass. Garnish with a grapefruit twist."}'::jsonb, 'Coupe', '{"en":"Grapefruit twist"}'::jsonb, 'none', 'up', '{"ING_BOURBON"}', '{"citrus","sweet","refreshing"}', 18, 160, 'easy', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"brunch","poolside","summer_party","casual_gathering"}', false, false, '{"whiskey-sour","gold-rush"}', 'Use fresh grapefruit juice for best results. Honey syrup should be 1:1 ratio (honey:hot water). Shake hard to properly emulsify the honey. Can serve on rocks for a longer drink.', 'mid', 76, 'Brown Derby Restaurant, Los Angeles, 1930s', 'Classic Hollywood cocktail. Rediscovered during modern cocktail renaissance.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 129. Buttery Nipple


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('5dfbe6f6-d14b-412f-995c-01edff825ac0', 'buttery-nipple', 'buttery_nipple_butterscotch_baileys_shot', '{"en":"Buttery Nipple"}'::jsonb, 'famous', NULL, '{"creamy","dessert","famous","shooter","sweet","layered"}', '{"en":"A popular layered shooter combining butterscotch schnapps and Irish cream. This sweet, creamy shot has a smooth buttery flavor that makes it a favorite at bars and parties, despite its provocative name."}'::jsonb, '{"created_year":"1980s","origin":{"country":"USA"},"story":{"en":"The Buttery Nipple emerged in the 1980s during the shooter craze that swept American bars. It became one of the most popular layered shots of the era, known for its sweet, approachable flavor and eye-catching presentation. The drink''s popularity was driven by the rise of schnapps and cream liqueurs in American drinking culture. Its suggestive name made it a frequent request at parties and bachelor/bachelorette celebrations. The shot remains popular today as a gateway drink for those new to spirits."},"named_after":{"en":"The suggestive name refers to the creamy, buttery appearance and smooth texture of the layered shot."}}'::jsonb, '{"profile":["creamy","sweet","buttery","caramel"],"description":{"en":"Extremely sweet with pronounced butterscotch and caramel flavors balanced by creamy Irish cream. The combination creates a smooth, buttery shot that goes down easily with minimal alcohol burn."},"first_impression":{"en":"Sweet butterscotch cream with immediate caramel notes"},"finish":{"en":"Smooth, sweet finish with lingering butterscotch"},"balance":{"en":"Very sweet and dessert-focused - designed for easy drinking rather than complexity"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["party","celebration","casual","bachelor_party"],"seasons":["all_seasons"],"food_pairings":{"en":"Typically consumed as a standalone shot between other drinks. Can accompany desserts or be served as a liquid dessert itself."},"ideal_for":{"en":"Perfect for those new to shots or who prefer very sweet drinks. Ideal for parties, celebrations, and social drinking occasions. Popular with guests who want an easy, non-threatening shot experience."}}'::jsonb, '[{"ingredient_id":"ING_BUTTERSCOTCH_SCHNAPPS","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Butterscotch schnapps","notes":null},{"ingredient_id":"ING_IRISH_CREAM","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Irish cream (Baileys)","notes":null}]'::jsonb, 'layer', '{"en":"Pour butterscotch schnapps into a shot glass. Using the back of a bar spoon, slowly layer the Irish cream on top by pouring it gently over the spoon. The two liqueurs should form distinct layers. Shoot or sip slowly to enjoy the layered effect."}'::jsonb, 'Shot glass', '{"en":"None"}'::jsonb, 'none', 'shot', '{"ING_BUTTERSCOTCH_SCHNAPPS"}', '{"creamy","sweet","buttery","caramel"}', 17, 150, 'easy', 30, '{"milk"}', '{"lactose","alcohol"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 0, '{"vegetarian","gluten-free"}', '{"all-seasons"}', '{"party","celebration","casual"}', false, false, '{"slippery-nipple","comfortable-screw","buttery-finger"}', 'Very popular party shot. Layering technique is important for visual appeal - pour slowly. Can add vodka on bottom for "Slippery Nipple" variation. Very sweet - warn guests. Name may require discretion with certain clientele.', 'low', 70, 'https://www.liquor.com/recipes/buttery-nipple/', 'Classic 1980s layered shooter, popular at parties.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 130. Cable Car


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('57f3fc9d-700f-4070-9f58-58ac71722e24', 'cable-car', '4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a12', '{"en":"Cable Car"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","rum","citrus","sweet"}', '{"en":"A San Francisco classic featuring spiced rum, orange curaçao, lemon juice, and a cinnamon-sugar rim. The Cable Car is a sophisticated variation on the Sidecar with warming spice notes."}'::jsonb, '{"created_year":"1996","origin":{"city":"San Francisco","bar":"The Starlight Room","country":"USA"},"creator":{"name":"Tony Abou-Ganim","profession":"bartender"},"story":{"en":"Created by legendary bartender Tony Abou-Ganim in 1996 at The Starlight Room atop the Sir Francis Drake Hotel in San Francisco. Abou-Ganim designed the Cable Car as a tribute to San Francisco''s iconic cable car system. He elevated the classic Sidecar by substituting spiced rum for cognac and adding a cinnamon-sugar rim, creating a cocktail that captures the spirit of the city. The drink became immensely popular and is now considered a modern classic, especially in San Francisco."},"named_after":{"en":"Named after San Francisco''s iconic cable car system, a symbol of the city since 1873."}}'::jsonb, '{"profile":["citrus","spicy","sweet"],"description":{"en":"Bright and citrusy with warming spice notes. Spiced rum provides a rich backbone with vanilla and cinnamon, orange curaçao adds sweet orange flavor, lemon juice brings tartness, and the cinnamon-sugar rim enhances the spice character throughout."},"first_impression":{"en":"Sweet cinnamon-sugar rim hits first, followed by citrus and spiced rum warmth"},"finish":{"en":"Long, warming finish with lingering spice and citrus notes"},"balance":{"en":"Well-balanced between sweet, tart, and spicy, with the cinnamon-sugar rim adding extra dimension"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["cocktail_hour","date_night","celebration"],"seasons":["autumn","winter"],"food_pairings":{"en":"Excellent with spiced desserts, apple pie, crème brûlée, and roasted nuts. The spice notes complement warm, sweet flavors."},"ideal_for":{"en":"Perfect for rum lovers who enjoy citrus cocktails with a spicy twist. Ideal for those visiting or reminiscing about San Francisco."}}'::jsonb, '[{"ingredient_id":"ING_SPICED_RUM","quantity":{"amount":45,"unit":"ml"},"display_name":"Spiced rum","notes":null},{"ingredient_id":"ING_CURACAO_ORANGE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Orange curaçao","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Simple syrup","notes":null}]'::jsonb, 'shake', '{"en":"Rim a chilled coupe glass with cinnamon-sugar. Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into the prepared glass. Garnish with an orange twist."}'::jsonb, 'Coupe', '{"en":"Cinnamon-sugar rim and orange twist"}'::jsonb, 'none', 'up', '{"ING_SPICED_RUM"}', '{"citrus","spicy","sweet"}', 20, 185, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 2, '{"vegan","gluten-free","dairy-free"}', '{"autumn","winter"}', '{"cocktail_hour","date_night","celebration"}', false, false, '{"sidecar","margarita"}', 'Rim glass with cinnamon-sugar (mix cinnamon and sugar 1:4 ratio). Use quality spiced rum for best results. The cinnamon-sugar rim is essential to the drink''s character - don''t skip it!', 'mid', 77, 'Created by Tony Abou-Ganim at The Starlight Room, 1996', 'Modern classic and San Francisco signature cocktail. Featured in The Modern Mixologist.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


