INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('fb27aea3-c041-4d86-9d01-0e684f51baa9', 'sherry-cobbler', 'b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6', '{"en":"Sherry Cobbler"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","classic","sherry","low-abv","refreshing","historical"}', '{"en":"A historic low-ABV cocktail featuring sherry wine, fresh citrus, and seasonal berries served over crushed ice. One of the first drinks to popularize the use of a drinking straw, the Sherry Cobbler was the height of sophistication in 19th century America."}'::jsonb, '{"created_year":"1830","origin":{"city":"New York City","bar":"Unknown","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Sherry Cobbler emerged in the 1830s-1840s and became phenomenally popular in America during the mid-19th century. It was one of the first cocktails to be served with crushed ice and a drinking straw - both innovations at the time. The drink was so fashionable that it helped create demand for imported sherry in the United States. Charles Dickens mentioned it in his writings, and it appeared in Jerry Thomas''s seminal 1862 cocktail book. The cobbler style (spirit, sugar, fruit, crushed ice) spawned many variations."},"named_after":{"en":"The term \"cobbler\" in cocktails likely refers to the drink''s cobbled or rough appearance from the crushed ice and fruit garnishes piled on top."}}'::jsonb, '{"profile":["fruity","wine-forward","refreshing","delicate"],"description":{"en":"Elegant and refreshing with nutty, oxidized sherry flavors complemented by bright citrus and sweet berries. The crushed ice dilution makes it incredibly easy to drink while preserving the wine''s character."},"first_impression":{"en":"Sweet berry and citrus aromatics with delicate sherry undertones"},"finish":{"en":"Clean, refreshing finish with lingering nutty sherry notes"},"balance":{"en":"Beautifully balanced between wine character, fruit sweetness, and refreshing dilution"}}'::jsonb, '{"best_time":["afternoon","early_evening","aperitif"],"occasions":["aperitivo","brunch","garden_party","afternoon_social"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Excellent with Spanish tapas, jamón ibérico, manchego cheese, olives, almonds, and light seafood dishes."},"ideal_for":{"en":"Perfect for sherry enthusiasts and those seeking elegant, low-ABV options. Ideal for afternoon sipping and as a sophisticated aperitif. Great for history buffs interested in 19th century cocktail culture."}}'::jsonb, '[{"ingredient_id":"ING_SHERRY_AMONTILLADO","quantity":{"amount":90,"unit":"ml"},"display_name":"Amontillado sherry","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Simple syrup","notes":null},{"ingredient_id":"ING_ORANGE_SLICE","quantity":{"amount":2,"unit":"slices"},"display_name":"Orange slices","notes":null},{"ingredient_id":"ING_SEASONAL_BERRIES","quantity":{"amount":4,"unit":"pieces"},"display_name":"Seasonal berries","notes":null}]'::jsonb, 'build', '{"en":"Fill a wine glass or goblet with crushed ice. Add sherry and simple syrup. Stir briefly to combine. Add more crushed ice to fill the glass. Garnish generously with orange slices and seasonal berries (strawberries, raspberries, or blackberries). Serve with a straw and optionally a spoon."}'::jsonb, 'Wine glass or Goblet', '{"en":"Orange slices and seasonal berries (strawberries, raspberries, blackberries)"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_SHERRY_AMONTILLADO"}', '{"fruity","wine-forward","refreshing","delicate"}', 10, 150, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free","low-abv"}', '{"spring","summer","autumn"}', '{"aperitivo","brunch","casual"}', false, false, '{"port-cobbler","champagne-cobbler","whiskey-cobbler"}', 'Amontillado sherry is traditional but can use Fino or Oloroso. Crushed ice is essential for proper dilution. Generous fruit garnish is part of the experience. Historically served with a straw.', 'mid', 60, 'https://iba-world.com/sherry-cobbler/', 'IBA Official Recipe. Historical references from Jerry Thomas''s 1862 "The Bon Vivant''s Companion".', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 102. Southside


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('8cbc79d6-6c40-49ed-9299-1a0e7be11d4a', 'southside', 'e5g7b9d1f3a5c7e9b1d3f5a7c9e1b3d5', '{"en":"Southside"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","prohibition-era","refreshing","minty","classic"}', '{"en":"A refreshing Prohibition-era cocktail combining gin, fresh lemon juice, simple syrup, and mint. Often described as a \"gin Mojito,\" the Southside is a bright, herbaceous drink that perfectly balances citrus tartness with cooling mint."}'::jsonb, '{"created_year":"1920","origin":{"city":"Chicago / New York","bar":"Multiple claims","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Southside''s origins are debated, with two main origin stories. One claims it was created during Prohibition in Chicago, named after the South Side neighborhood and favored by gangsters like Al Capone - the mint was added to mask the harsh taste of bathtub gin. The other story attributes it to the Southside Sportsmen''s Club on Long Island, New York, where it was served as a refined country club drink. Regardless of its true origin, the Southside became a staple of the Prohibition era and has enjoyed a major revival in modern cocktail bars."},"named_after":{"en":"Named either after Chicago''s South Side neighborhood or the Southside Sportsmen''s Club on Long Island - both stories have their advocates."}}'::jsonb, '{"profile":["refreshing","citrus","minty","herbaceous"],"description":{"en":"Bright and invigorating. The gin provides botanical complexity, fresh lemon juice adds tartness, simple syrup balances with sweetness, and fresh mint brings cooling herbal notes. The result is a perfectly balanced, garden-fresh cocktail."},"first_impression":{"en":"Fresh mint and bright lemon hit first, followed by the botanical character of gin"},"finish":{"en":"Clean, refreshing finish with lingering mint and citrus"},"balance":{"en":"Beautifully balanced between tart, sweet, and herbal - neither too sour nor too sweet"}}'::jsonb, '{"best_time":["afternoon","evening","brunch"],"occasions":["garden_party","brunch","summer_gathering","cocktail_hour"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with light summer fare: salads, grilled fish, fresh oysters, cucumber sandwiches, and herb-crusted chicken. Also pairs beautifully with Vietnamese and Thai cuisine."},"ideal_for":{"en":"Perfect for those who enjoy refreshing, herbaceous cocktails. Ideal for gin lovers seeking something lighter and more refreshing than a traditional martini. Great for anyone who loves Mojitos but wants to explore gin-based drinks."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":60,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":15,"unit":"ml"},"display_name":"Simple syrup","notes":null},{"ingredient_id":"ING_MINT_LEAVES","quantity":{"amount":6,"unit":"leaves"},"display_name":"Fresh mint leaves","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker. Gently muddle the mint leaves (do not over-muddle). Add ice and shake well until properly chilled. Double strain into a chilled cocktail glass. Garnish with a fresh mint sprig."}'::jsonb, 'Coupe glass (or Cocktail glass)', '{"en":"Fresh mint sprig"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"refreshing","citrus","minty","herbaceous"}', 18, 160, 'easy', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"garden_party","brunch","summer_gathering"}', false, false, '{"southside-fizz","southside-royale","basil-southside"}', 'Use fresh mint - never dried or wilted. Gently muddle mint to release oils without making it bitter (bruising releases chlorophyll which makes it bitter). Fresh lemon juice is essential. Double strain to remove mint particles. Can be served as a Collins (Southside Fizz) by adding soda water and serving over ice. Some recipes call for lime instead of lemon - both are acceptable.', 'mid', 80, 'https://iba-world.com/southside/', 'IBA Official Recipe. Prohibition-era cocktail with dual origin claims (Chicago South Side vs. Long Island country club).', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 103. Spicy Fifty


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('f822b10e-0973-4316-af4e-422a7bd2fe4d', 'spicy-fifty', 'a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1', '{"en":"Spicy Fifty"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","modern","vodka","spicy","sophisticated","elegant"}', '{"en":"An elegant and spicy modern cocktail featuring vanilla vodka, elderflower liqueur, and fresh chili pepper. This sophisticated creation balances floral sweetness with a subtle heat, creating a refined drinking experience that showcases the versatility of contemporary mixology."}'::jsonb, '{"created_year":"2009","origin":{"city":"London","bar":"Skybar at Trader Vic''s","country":"United Kingdom"},"creator":{"name":"Salvatore Calabrese","profession":"bartender"},"story":{"en":"Created by legendary bartender Salvatore Calabrese at the Skybar at Trader Vic''s in London in 2009 to celebrate his 50th birthday. The \"Fifty\" in the name refers to both his milestone birthday and the drink''s elegant sophistication. Calabrese wanted to create something that reflected his passion for balance and innovation, combining unexpected elements like vanilla, elderflower, and chili. The cocktail won multiple awards and became a modern classic, showcasing how spice can be incorporated elegantly into cocktails."},"named_after":{"en":"Named \"Fifty\" to celebrate Salvatore Calabrese''s 50th birthday and the drink''s sophisticated elegance befitting a milestone celebration."}}'::jsonb, '{"profile":["spicy","floral","citrus","sophisticated"],"description":{"en":"Beautifully layered with vanilla vodka''s smoothness, elderflower''s delicate floral notes, bright citrus from lemon and grapefruit, and a gentle warming heat from fresh chili. The spice builds gradually without overwhelming, creating an elegant complexity."},"first_impression":{"en":"Floral elderflower and citrus with vanilla smoothness, followed by gentle heat"},"finish":{"en":"Lingering warmth with floral and citrus notes, gentle spicy tingle"},"balance":{"en":"Perfectly balanced between sweet floral notes, tart citrus, vanilla smoothness, and controlled heat"}}'::jsonb, '{"best_time":["evening","aperitif","late_night"],"occasions":["aperitivo","date_night","celebration","cocktail_party"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Excellent with spicy Asian cuisine, ceviche, sushi, grilled seafood, and Thai dishes. Also pairs well with fresh oysters."},"ideal_for":{"en":"Perfect for adventurous drinkers who appreciate sophisticated spice in cocktails. Ideal for those seeking an elegant aperitif with a twist. Great for impressing guests with a modern classic."}}'::jsonb, '[{"ingredient_id":"ING_VODKA_VANILLA","quantity":{"amount":50,"unit":"ml"},"display_name":"Vanilla vodka","notes":null},{"ingredient_id":"ING_ELDERFLOWER_LIQUEUR","quantity":{"amount":15,"unit":"ml"},"display_name":"Elderflower liqueur","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_HONEY_SYRUP","quantity":{"amount":10,"unit":"ml"},"display_name":"Honey syrup","notes":null},{"ingredient_id":"ING_RED_CHILI_PEPPER","quantity":{"amount":1,"unit":"slice"},"display_name":"Fresh red chili pepper (1 slice)","notes":null}]'::jsonb, 'shake', '{"en":"Muddle one slice of red chili pepper in a cocktail shaker (adjust quantity for desired heat level). Add vanilla vodka, elderflower liqueur, lemon juice, honey syrup, and ice. Shake vigorously until well-chilled. Double strain into a chilled Martini glass. Float a thin slice of red chili on top as garnish."}'::jsonb, 'Martini glass (Cocktail)', '{"en":"Thin slice of fresh red chili pepper (floating)"}'::jsonb, 'none', 'up', '{"ING_VODKA_VANILLA"}', '{"spicy","floral","citrus","sophisticated"}', 17, 170, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 2, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer","autumn"}', '{"aperitivo","date_night","celebration"}', false, false, '{"extra-spicy-fifty","spicy-fifty-on-rocks"}', 'Adjust chili quantity based on guest preference - one slice is moderate. St-Germain is standard elderflower liqueur. Honey syrup is 1:1 honey to water. Double strain to remove chili seeds.', 'mid', 75, 'https://iba-world.com/spicy-fifty/', 'IBA Official Recipe. Created by Salvatore Calabrese at Skybar, Trader Vic''s London, 2009.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 104. Spritz Veneziano


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('a2c2bd7e-c3a4-41ff-bdef-345a475b83d9', 'spritz', 'd6c5b4a3e2f10987564382910047563829174638', '{"en":"Spritz Veneziano"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","aperitivo","bitter","italian","sparkling"}', '{"en":"Italy''s iconic aperitivo cocktail combining prosecco, bitter liqueur (Aperol or Campari), and soda water. Born in Venice, the Spritz is the quintessential Italian happy hour drink with its brilliant orange color and refreshingly bitter-sweet taste."}'::jsonb, '{"created_year":"1800","origin":{"city":"Venice","bar":"Various cafés","country":"Italy"},"creator":{"name":"Austrian soldiers","profession":"military"},"story":{"en":"The Spritz originated in Venice during the 19th century Habsburg occupation. Austrian soldiers found Italian wines too strong and requested them to be \"spritzed\" (spritzen in German means \"to spray\") with water. This evolved into adding soda water to wine. In the 1920s, the Aperol company popularized the modern version by promoting their bitter liqueur as the perfect addition. The classic Venetian formula is 3-2-1: three parts prosecco, two parts Aperol (or Campari for a more bitter version), and one part soda water. It became globally popular in the 2010s, particularly the Aperol Spritz variant."},"named_after":{"en":"Named after the German word \"spritzen\" (to spray/spritz), referring to the addition of soda water."}}'::jsonb, '{"profile":["bitter","refreshing","sparkling"],"description":{"en":"Light, refreshing, and effervescent with a perfect balance of bitter orange, herbal complexity, and prosecco bubbles. The Aperol version is sweeter and more approachable; Campari makes it more intensely bitter."},"first_impression":{"en":"Bright, fizzy prosecco bubbles followed by bittersweet orange and herbs"},"finish":{"en":"Clean, refreshing finish with lingering pleasant bitterness"},"balance":{"en":"Perfectly balanced between bitter, sweet, and sparkling - the ultimate aperitivo"}}'::jsonb, '{"best_time":["afternoon","early_evening"],"occasions":["aperitivo","casual","brunch","social_gathering"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Perfect with Italian aperitivo snacks: olives, chips, focaccia, prosciutto, cheese, bruschetta. The bitterness stimulates appetite and cuts through rich foods."},"ideal_for":{"en":"Perfect for aperitivo hour (5-7pm) and anyone who enjoys light, refreshing, low-ABV drinks. Great for those new to bitter cocktails - start with Aperol before trying Campari."}}'::jsonb, '[{"ingredient_id":"ING_PROSECCO","quantity":{"amount":90,"unit":"ml"},"display_name":"Prosecco","notes":null},{"ingredient_id":"ING_APEROL","quantity":{"amount":60,"unit":"ml"},"display_name":"Aperol (or Campari)","notes":null},{"ingredient_id":"ING_SODA_WATER","quantity":{"amount":30,"unit":"ml"},"display_name":"Soda water","notes":null}]'::jsonb, 'build', '{"en":"Fill a large wine glass or rocks glass with ice. Pour prosecco, then Aperol (or Campari), then soda water. Stir gently to combine. Garnish with an orange slice."}'::jsonb, 'Wine glass or Rocks glass', '{"en":"Orange slice"}'::jsonb, 'cubes', 'on_the_rocks', '{"ING_PROSECCO"}', '{"bitter","refreshing","sparkling"}', 8, 140, 'easy', 30, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer","autumn"}', '{"aperitivo","casual","brunch","social_gathering"}', false, false, '{"aperol-spritz","campari-spritz","select-spritz","hugo-spritz"}', 'Classic ratio is 3-2-1 (prosecco-Aperol-soda). Aperol = sweeter and more approachable. Campari = more bitter and traditional. Always serve in a large glass filled with ice. Don''t overstir - keep it bubbly.', 'low', 98, 'https://iba-world.com/spritz/', 'IBA Official Recipe. Historical information from Venetian aperitivo culture and Aperol company archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 105. Spritz Veneziano


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('4372e7f1-9979-468f-a5a7-93d47e027d6b', 'spritz-veneziano', 'b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8', '{"en":"Spritz Veneziano"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","italian","aperitivo","prosecco","bitter","iconic"}', '{"en":"The iconic Italian aperitivo cocktail combining Prosecco, Aperol, and soda water. This refreshing, low-ABV drink with its distinctive sunset-orange color has become a global phenomenon, embodying the Italian art of aperitivo hour and la dolce vita lifestyle."}'::jsonb, '{"created_year":"1919","origin":{"city":"Venice","bar":"Unknown","country":"Italy"},"creator":{"name":"Unknown","profession":"unknown"},"story":{"en":"The Spritz originated in Venice during the 19th century when the Austro-Hungarian Empire controlled the region. Austrian soldiers found Italian wine too strong and requested it be \"spritzed\" (sprayed) with water. The modern Aperol Spritz emerged after Aperol''s creation in 1919 in Padua. While Spritzes were popular locally for decades, the Aperol Spritz exploded globally in the 2000s-2010s, becoming one of the world''s most recognized cocktails. Its 3-2-1 ratio (3 parts Prosecco, 2 parts Aperol, 1 splash soda) became the standard serve."},"named_after":{"en":"\"Spritz\" comes from the German word \"spritzen\" (to spray/spritz), referencing the original practice of diluting wine with water."}}'::jsonb, '{"profile":["bitter","bubbly","refreshing","light"],"description":{"en":"Light and refreshing with Aperol''s signature bitter-orange flavor, Prosecco''s fruity effervescence, and a gentle splash of soda. The bitterness is mild and approachable, balanced by sweet citrus notes and sparkling wine brightness. Incredibly sessionable and refreshing."},"first_impression":{"en":"Sparkling effervescence with gentle bitter-orange and citrus sweetness"},"finish":{"en":"Clean, refreshing finish with subtle bitter notes and citrus brightness"},"balance":{"en":"Perfectly balanced between bitter, sweet, and bubbly - the quintessential aperitivo"}}'::jsonb, '{"best_time":["afternoon","early_evening","aperitif"],"occasions":["aperitivo","social_gathering","casual","outdoor_dining","summer_party"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Perfect with Italian cicchetti, olives, salted nuts, prosciutto, bruschetta, light seafood, and cheese plates."},"ideal_for":{"en":"Perfect for aperitivo hour and social drinking. Ideal for those seeking a light, refreshing, low-ABV option. Great for introducing people to Italian aperitivo culture and outdoor cafe life."}}'::jsonb, '[{"ingredient_id":"ING_PROSECCO","quantity":{"amount":90,"unit":"ml"},"display_name":"Prosecco","notes":null},{"ingredient_id":"ING_APEROL","quantity":{"amount":60,"unit":"ml"},"display_name":"Aperol","notes":null},{"ingredient_id":"ING_SODA_WATER","quantity":{"amount":30,"unit":"ml"},"display_name":"Soda water (splash)","notes":null}]'::jsonb, 'build', '{"en":"Fill a large wine glass or rocks glass with ice cubes. Add Aperol, then Prosecco. Top with a splash of soda water. Stir gently once to combine. Garnish with an orange slice."}'::jsonb, 'Large wine glass (or Rocks glass)', '{"en":"Orange slice (half-wheel)"}'::jsonb, 'cubes', 'on_the_rocks', '{"ING_PROSECCO"}', '{"bitter","bubbly","refreshing","light"}', 8, 140, 'easy', 30, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free","low-abv"}', '{"spring","summer","autumn"}', '{"aperitivo","casual","social","outdoor"}', false, false, '{"campari-spritz","select-spritz","limoncello-spritz"}', 'Classic ratio is 3-2-1 (Prosecco-Aperol-Soda). Use large wine glass filled with ice. Aperol is essential - Campari makes a different drink (Negroni Sbagliato). Garnish with orange slice, not twist.', 'mid', 100, 'https://iba-world.com/spritz/', 'IBA Official Recipe. Originated in Venice, popularized globally in 2000s-2010s.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 106. Suffering Bastard


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('49eeb82a-b3a9-4e13-baef-0689139e5c2e', 'suffering-bastard', 'e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4', '{"en":"Suffering Bastard"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","gin","brandy","tiki","refreshing","hangover"}', '{"en":"A legendary hangover cure from Cairo combining gin and brandy with lime, ginger beer, and Angostura bitters. Refreshing, spicy, and supposedly medicinal - perfect for \"suffering bastards.\""}'::jsonb, '{"created_year":"1942","origin":{"city":"Cairo","bar":"Shepheard''s Hotel","country":"Egypt"},"creator":{"name":"Joe Scialom","profession":"bartender"},"story":{"en":"Created by Joe Scialom at Shepheard''s Hotel in Cairo during World War II. The drink was allegedly invented as a hangover cure for British officers stationed in North Africa. The name refers to the hungover soldiers who would stumble into the bar seeking relief. The drink became so popular that Scialom reportedly made \"by the barrel\" during the war years."},"named_after":{"en":"Named after the hungover British officers who were \"suffering bastards\" in need of a cure."}}'::jsonb, '{"profile":["spicy","refreshing","complex"],"description":{"en":"Complex blend of gin and brandy with bright lime, spicy ginger beer, and aromatic bitters. Refreshing, warming, and surprisingly balanced despite the multiple spirits."},"first_impression":{"en":"Bright citrus and spicy ginger with herbal gin notes"},"finish":{"en":"Long, warming finish with ginger spice and aromatic bitters"},"balance":{"en":"Well-balanced between spirit strength, citrus brightness, and ginger spice"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["brunch","recovery","party","casual"],"seasons":["summer","spring"],"food_pairings":{"en":"Excellent with spicy foods, Middle Eastern cuisine, grilled meats, or as a brunch refresher."},"ideal_for":{"en":"Perfect for those seeking a refreshing, complex drink or a legendary hangover cure. Ideal for tiki enthusiasts and history buffs."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":30,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_BRANDY","quantity":{"amount":30,"unit":"ml"},"display_name":"Brandy","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_GINGER_BEER","quantity":{"amount":120,"unit":"ml"},"display_name":"Ginger beer","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":2,"unit":"dashes"},"display_name":"Angostura bitters","notes":null}]'::jsonb, 'build', '{"en":"Pour gin, brandy, and lime juice into a highball glass filled with ice. Top with ginger beer. Add two dashes of Angostura bitters. Stir gently."}'::jsonb, 'Highball glass', '{"en":"Mint sprig and lime wheel"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_GIN","ING_BRANDY"}', '{"spicy","refreshing","complex"}', 10, 180, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 2, '{"vegan","gluten-free","dairy-free"}', '{"summer","spring"}', '{"brunch","party","casual"}', false, false, '{"original-suffering-bastard"}', 'Use quality ginger beer for best results. The combination of gin and brandy is traditional - don''t substitute. Originally created as a hangover cure.', 'mid', 55, 'https://iba-world.com/suffering-bastard/', 'IBA Official Recipe', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 107. Three Dots and a Dash


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('87024b08-eaa1-4ffe-a31f-fa72a312f565', 'three-dots-and-a-dash', 'e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3', '{"en":"Three Dots and a Dash"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","tiki","rum","tropical","complex"}', '{"en":"A complex tiki classic combining multiple rums with tropical fruit flavors and exotic spices. The name refers to Morse code for \"V\" (for Victory), created during World War II. This elaborate cocktail showcases the artistry of tiki culture with its layered flavors and dramatic presentation."}'::jsonb, '{"created_year":"1941","origin":{"city":"Hollywood","bar":"Don the Beachcomber''s","country":"USA"},"creator":{"name":"Donn Beach (Ernest Raymond Beaumont Gantt)","profession":"bartender"},"story":{"en":"Created by Donn Beach (Don the Beachcomber) in 1941 during World War II. The cocktail''s name comes from Morse code: three dots and a dash represents the letter \"V\" for Victory. The garnish of three cherries and a pineapple chunk on a skewer literally illustrates the Morse code pattern. It became one of the most celebrated tiki drinks, exemplifying the complex, multi-rum style that defined the era."},"named_after":{"en":"Named after Morse code for the letter \"V\" (Victory) - three dots and a dash (···-), a symbol of Allied victory in World War II."}}'::jsonb, '{"profile":["tropical","fruity","complex","spiced"],"description":{"en":"Complex and layered with tropical fruit flavors, warm spice notes, and a balanced rum backbone. The combination of multiple rums creates depth while citrus and allspice add brightness and exotic character."},"first_impression":{"en":"Tropical fruit sweetness with honey and citrus brightness"},"finish":{"en":"Long, warm finish with lingering spice and rum character"},"balance":{"en":"Perfectly balanced between sweet, sour, and spirit strength with complex spice undertones"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["celebration","tiki_party","summer_gathering","special_occasion"],"seasons":["spring","summer"],"food_pairings":{"en":"Pairs wonderfully with Polynesian cuisine, grilled pineapple, coconut shrimp, teriyaki chicken, and tropical fruit platters."},"ideal_for":{"en":"Perfect for tiki enthusiasts and rum lovers who appreciate complex, multi-layered cocktails. Ideal for those seeking an authentic piece of cocktail history with dramatic presentation."}}'::jsonb, '[{"ingredient_id":"ING_RUM_AGED","quantity":{"amount":45,"unit":"ml"},"display_name":"Aged rum","notes":null},{"ingredient_id":"ING_RUM_DEMERARA","quantity":{"amount":15,"unit":"ml"},"display_name":"Demerara rum","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_HONEY_SYRUP","quantity":{"amount":15,"unit":"ml"},"display_name":"Honey syrup","notes":null},{"ingredient_id":"ING_FALERNUM","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Falernum","notes":null},{"ingredient_id":"ING_ALLSPICE_DRAM","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Allspice dram (Pimento dram)","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":1,"unit":"dash"},"display_name":"Angostura bitters","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with crushed ice. Shake vigorously until well-chilled. Pour unstrained (with the ice) into a tiki mug or tall glass. Garnish elaborately with three cherries and a pineapple chunk on a cocktail pick, representing the Morse code pattern."}'::jsonb, 'Tiki mug or tall glass', '{"en":"Three maraschino cherries and pineapple chunk on a pick (representing Morse code ···-)"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_RUM_AGED","ING_RUM_DEMERARA"}', '{"tropical","fruity","complex","spiced"}', 15, 240, 'hard', 180, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 2, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"celebration","party","special_occasion"}', false, false, '{"modern-tiki-variations"}', 'Multiple rum blend is essential for authenticity. Honey syrup is 1:1 honey to water. Falernum and allspice dram are specialty tiki ingredients - keep in stock. Garnish is important for visual storytelling.', 'premium', 70, 'https://iba-world.com/three-dots-and-a-dash/', 'IBA Official Recipe. Historical information from Beachbum Berry''s tiki cocktail research.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 108. Tipperary


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('3ae218f3-6021-49b8-a0fc-5676c7185bfa', 'tipperary', 'c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2', '{"en":"Tipperary"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","whiskey","herbal","classic","irish"}', '{"en":"An elegant Irish whiskey cocktail that combines the smoothness of Irish whiskey with the herbal complexity of sweet vermouth and the distinctive flavor of green Chartreuse."}'::jsonb, '{"created_year":"1916","origin":{"city":"New York City","bar":"Unknown","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Tipperary cocktail first appeared in Hugo Ensslin''s 1916 \"Recipes for Mixed Drinks.\" Named after the Irish county and the popular WWI song \"It''s a Long Way to Tipperary,\" this cocktail celebrates Irish whiskey with a sophisticated blend of vermouth and Chartreuse. It gained renewed popularity during the craft cocktail renaissance of the 2000s."},"named_after":{"en":"Named after County Tipperary in Ireland and the WWI song \"It''s a Long Way to Tipperary.\""}}'::jsonb, '{"profile":["herbal","complex","smooth"],"description":{"en":"Smooth Irish whiskey with herbal, honeyed notes from the Chartreuse and sweet vermouth. Complex and well-balanced with a warming finish."},"first_impression":{"en":"Herbal and honeyed with Irish whiskey warmth"},"finish":{"en":"Long, warming finish with lingering herbal complexity"},"balance":{"en":"Well-balanced between whiskey smoothness, vermouth sweetness, and Chartreuse herbal notes"}}'::jsonb, '{"best_time":["evening","afternoon"],"occasions":["aperitivo","celebration","date_night","st_patricks_day"],"seasons":["autumn","winter","spring"],"food_pairings":{"en":"Excellent with Irish stew, shepherd''s pie, aged cheddar, or as a pre-dinner aperitif."},"ideal_for":{"en":"Perfect for Irish whiskey enthusiasts and those who appreciate herbal, complex cocktails. Ideal for St. Patrick''s Day or anyone exploring classic cocktails."}}'::jsonb, '[{"ingredient_id":"ING_WHISKEY_IRISH","quantity":{"amount":50,"unit":"ml"},"display_name":"Irish whiskey","notes":null},{"ingredient_id":"ING_VERMOUTH_SWEET","quantity":{"amount":25,"unit":"ml"},"display_name":"Sweet vermouth","notes":null},{"ingredient_id":"ING_CHARTREUSE_GREEN","quantity":{"amount":25,"unit":"ml"},"display_name":"Green Chartreuse","notes":null}]'::jsonb, 'stir', '{"en":"Pour all ingredients into a mixing glass filled with ice. Stir well until chilled. Strain into a chilled cocktail glass."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"Orange twist"}'::jsonb, 'none', 'up', '{"ING_WHISKEY_IRISH"}', '{"herbal","complex","smooth"}', 30, 180, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring"}', '{"aperitivo","celebration","date_night"}', false, false, '{"tipperary-no-2"}', 'Stir, don''t shake, to maintain clarity. The green Chartreuse provides a distinctive herbal character. Some variations use equal parts of all three ingredients.', 'mid', 60, 'https://iba-world.com/tipperary/', 'IBA Official Recipe', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 109. Tommy's Margarita


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('f65d9035-90a5-41f3-a9e0-af9ffd3569cd', 'tommys-margarita', 'f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1', '{"en":"Tommy''s Margarita"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","tequila","agave","citrus","modern-classic"}', '{"en":"A refined variation of the classic Margarita that replaces triple sec with agave nectar. This simpler, purer version showcases the tequila''s flavor and has become a modern classic."}'::jsonb, '{"created_year":"1990","origin":{"city":"San Francisco","bar":"Tommy''s Mexican Restaurant","country":"USA"},"creator":{"name":"Julio Bermejo","profession":"bartender"},"story":{"en":"Created in 1990 by Julio Bermejo at his family''s Tommy''s Mexican Restaurant in San Francisco. Bermejo, a tequila advocate, wanted to create a Margarita that better showcased 100% agave tequila. By replacing orange liqueur with agave nectar, he created a cleaner, more tequila-forward version that gained worldwide recognition. The drink helped launch the premium tequila movement and established Tommy''s as a tequila destination."},"named_after":{"en":"Named after Tommy''s Mexican Restaurant in San Francisco where it was created."}}'::jsonb, '{"profile":["agave","citrus","clean"],"description":{"en":"Pure agave sweetness from tequila and nectar, bright lime tartness, and clean finish. More tequila-forward than traditional Margarita with no orange notes."},"first_impression":{"en":"Clean agave and bright lime with tequila character"},"finish":{"en":"Long, clean finish with lingering agave sweetness"},"balance":{"en":"Perfectly balanced between tequila strength, agave sweetness, and lime tartness"}}'::jsonb, '{"best_time":["evening","afternoon"],"occasions":["casual","party","mexican_dinner","taco_night"],"seasons":["all_seasons"],"food_pairings":{"en":"Excellent with Mexican cuisine, tacos, ceviche, guacamole, or grilled meats."},"ideal_for":{"en":"Perfect for tequila purists and those who want to taste quality agave spirits. Ideal for anyone seeking a cleaner, more authentic Margarita."}}'::jsonb, '[{"ingredient_id":"ING_TEQUILA_BLANCO","quantity":{"amount":60,"unit":"ml"},"display_name":"Blanco tequila","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_AGAVE_NECTAR","quantity":{"amount":15,"unit":"ml"},"display_name":"Agave nectar","notes":null}]'::jsonb, 'shake', '{"en":"Shake all ingredients with ice. Strain into a rocks glass filled with ice. Optionally rim with salt."}'::jsonb, 'Rocks glass', '{"en":"Lime wheel (optional salt rim)"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_TEQUILA_BLANCO"}', '{"agave","citrus","clean"}', 20, 160, 'easy', 45, '{}', '{"alcohol"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"all-season"}', '{"casual","party","mexican_dinner"}', false, false, '{}', 'Use 100% agave tequila for best results. Agave nectar is essential - don''t substitute with simple syrup. Salt rim is optional but traditional.', 'mid', 85, 'https://iba-world.com/tommys-margarita/', 'IBA Official Recipe', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 110. Trinidad Sour


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('b0999727-6026-42c4-a941-66ed98b0326c', 'trinidad-sour', 'f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0', '{"en":"Trinidad Sour"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","modern","sour","bitter","revolutionary","bold"}', '{"en":"A revolutionary modern cocktail that flips the traditional formula by using Angostura bitters as the base spirit instead of an accent. This bold creation showcases how bitters can be the star, balanced with rye whiskey, orgeat, and lemon. The result is an intensely aromatic and complex drink."}'::jsonb, '{"created_year":"2009","origin":{"city":"New York City","bar":"Clover Club","country":"USA"},"creator":{"name":"Giuseppe Gonzalez","profession":"bartender"},"story":{"en":"Created by Giuseppe Gonzalez at Clover Club in Brooklyn in 2009, the Trinidad Sour was a groundbreaking cocktail that challenged conventional thinking. Gonzalez wanted to showcase Angostura bitters - traditionally used by the dash - as the primary ingredient. The audacious proportions (1.5 oz of bitters!) shouldn''t work on paper, but the careful balance with orgeat''s sweetness, lemon''s acidity, and rye''s spice creates something remarkably drinkable and complex. It inspired bartenders worldwide to rethink ingredient hierarchies."},"named_after":{"en":"Named after Trinidad, the birthplace of Angostura bitters (House of Angostura was founded in Trinidad in 1824)."}}'::jsonb, '{"profile":["bitter","spicy","aromatic","complex"],"description":{"en":"Intensely aromatic with powerful baking spices, clove, cinnamon, and gentian bitterness balanced by almond-sweet orgeat and bright lemon acidity. The rye adds a spicy backbone that ties everything together. Surprisingly smooth despite the bold bitters content."},"first_impression":{"en":"Powerful aromatic spices and bitterness with almond sweetness"},"finish":{"en":"Long, warming finish with lingering spice and bitter complexity"},"balance":{"en":"Remarkably balanced given the extreme proportions - bitter, sweet, sour, and spicy in harmony"}}'::jsonb, '{"best_time":["evening","after_dinner"],"occasions":["digestivo","cocktail_party","date_night","tasting_menu"],"seasons":["autumn","winter"],"food_pairings":{"en":"Pairs well with rich meats, dark chocolate, spiced desserts, aged cheeses, and bold Caribbean cuisine."},"ideal_for":{"en":"Perfect for adventurous cocktail enthusiasts who appreciate bitter flavors and innovative mixology. Ideal for amaro and bitters lovers. Great as a conversation starter and digestif."}}'::jsonb, '[{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":45,"unit":"ml"},"display_name":"Angostura bitters","notes":null},{"ingredient_id":"ING_RYE_WHISKEY","quantity":{"amount":15,"unit":"ml"},"display_name":"Rye whiskey","notes":null},{"ingredient_id":"ING_ORGEAT","quantity":{"amount":30,"unit":"ml"},"display_name":"Orgeat syrup","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled (15-20 seconds is crucial for proper dilution). Double strain into a chilled coupe or Nick & Nora glass. Garnish with a lemon twist, expressing the oils over the drink."}'::jsonb, 'Coupe or Nick & Nora glass', '{"en":"Lemon twist (expressed)"}'::jsonb, 'none', 'up', '{"ING_ANGOSTURA_BITTERS"}', '{"bitter","spicy","aromatic","complex"}', 20, 180, 'easy', 90, '{"tree_nuts","sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free"}', 3, '{"vegan","gluten-free","dairy-free"}', '{"autumn","winter"}', '{"digestivo","date_night","cocktail_party"}', false, false, '{"bourbon-trinidad-sour","trinidad-especial"}', 'Yes, 1.5 oz of Angostura is correct! Proper dilution through shaking is critical. Quality orgeat is essential. Express lemon oils generously. This drink converts bitter skeptics.', 'mid', 70, 'https://iba-world.com/trinidad-sour/', 'IBA Official Recipe. Created by Giuseppe Gonzalez at Clover Club, Brooklyn, 2009.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


