INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('33eac286-54ab-45af-9ac8-2b1585671180', 'rusty-nail', 'b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7', '{"en":"Rusty Nail"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","two-ingredient","stirred","after-dinner","scottish"}', '{"en":"A classic Scottish two-ingredient cocktail combining Scotch whisky with Drambuie, the honey and herb liqueur. Simple yet sophisticated, the Rusty Nail is warming, smooth, and perfect for sipping slowly. The golden color and rich flavor make it an ideal after-dinner drink."}'::jsonb, '{"created_year":"1960s","origin":{"city":"Unknown","bar":"21 Club (popularized)","country":"USA/Scotland"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"While the exact origins are unclear, the Rusty Nail gained popularity in the 1960s and 1970s, particularly after being championed by the Rat Pack (Frank Sinatra, Dean Martin, and their crew) at New York''s 21 Club. The drink showcases Drambuie, a Scotch-based liqueur flavored with honey, herbs, and spices, which was created from a secret recipe given to the MacKinnon family by Bonnie Prince Charlie in 1746. The name \"Rusty Nail\" likely refers to the drink''s rusty golden color."},"named_after":{"en":"Named for the rusty golden color of the drink."}}'::jsonb, '{"profile":["sweet","herbal","warming"],"description":{"en":"Rich and warming with smoky Scotch balanced by sweet, honeyed Drambuie. The honey and herbal notes from Drambuie soften the whisky''s edges while maintaining complexity. Smooth and satisfying with a long, warming finish."},"first_impression":{"en":"Sweet honey and herbs followed by smoky Scotch"},"finish":{"en":"Long, warming finish with lingering honey, herbs, and smoke"},"balance":{"en":"Well-balanced between sweet Drambuie and smoky Scotch"}}'::jsonb, '{"best_time":["after_dinner","evening","nightcap"],"occasions":["digestivo","nightcap","contemplative","fireside"],"seasons":["autumn","winter"],"food_pairings":{"en":"Perfect as a digestif with desserts, especially those with caramel, honey, or nuts. Pairs well with Scottish shortbread, chocolate, aged cheese, or smoked meats."},"ideal_for":{"en":"Perfect for Scotch enthusiasts who enjoy sweeter, more approachable whisky drinks. Ideal for those seeking a warming, simple yet sophisticated after-dinner cocktail."}}'::jsonb, '[{"ingredient_id":"ING_SCOTCH_WHISKY","quantity":{"amount":45,"unit":"ml"},"display_name":"Scotch whisky","notes":null},{"ingredient_id":"ING_DRAMBUIE","quantity":{"amount":25,"unit":"ml"},"display_name":"Drambuie","notes":null}]'::jsonb, 'build', '{"en":"Pour all ingredients directly into an old fashioned glass filled with ice. Stir gently. Garnish with lemon zest."}'::jsonb, 'Old Fashioned glass', '{"en":"Lemon zest"}'::jsonb, 'cubes', 'on_the_rocks', '{"ING_SCOTCH_WHISKY"}', '{"sweet","herbal","warming"}', 32, 180, 'easy', 30, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","gluten-free","dairy-free"}', '{"autumn","winter"}', '{"digestivo","nightcap","contemplative"}', false, false, '{"rob-roy","bobby-burns","godfather"}', 'The official IBA ratio is 9 parts Scotch to 5 parts Drambuie (45ml:25ml). Can be adjusted to taste - some prefer equal parts. Build directly in glass for simplicity. Drambuie is essential - no substitutes. Stir gently to avoid over-dilution.', 'mid', 65, 'https://iba-world.com/iba-cocktail/rusty-nail/', 'IBA Official Recipe. Historical information from Drambuie history and 1960s cocktail culture.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 32. Sazerac


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('0cc34d51-78a3-4f96-93d4-03b822e7257c', 'sazerac', 'a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6', '{"en":"Sazerac"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","new-orleans","stirred","strong","official-cocktail"}', '{"en":"New Orleans'' official cocktail, the Sazerac is a bold, spirit-forward classic combining cognac or rye whiskey with Peychaud''s bitters, sugar, and an absinthe rinse. One of America''s oldest cocktails, it embodies the soul of the Crescent City."}'::jsonb, '{"created_year":"1838","origin":{"city":"New Orleans","bar":"Sazerac Coffee House","country":"USA"},"creator":{"name":"Antoine Amédée Peychaud","profession":"pharmacist/bartender"},"story":{"en":"The Sazerac is a local variation of a cognac or whiskey cocktail originally from New Orleans, named for the Sazerac de Forge et Fils brand of cognac that served as its original main ingredient. Created around 1838 by Antoine Amédée Peychaud, a Creole apothecary who invented Peychaud''s bitters. The original recipe changed after the American Civil War when rye whiskey substituted cognac as it became hard to obtain. In 2008, the Louisiana Legislature declared the Sazerac as New Orleans'' official cocktail. The Sazerac Coffee House, where it was popularized, is now a protected historic site."},"named_after":{"en":"Named after Sazerac de Forge et Fils, the cognac brand originally used in the drink."}}'::jsonb, '{"profile":["complex","herbal","anise"],"description":{"en":"Bold and complex with anise and herbal notes from absinthe dominating the aroma, followed by the rich warmth of cognac or rye. Peychaud''s bitters provide distinctive fruity-floral complexity. The sugar softens the edges while lemon oils add brightness."},"first_impression":{"en":"Anise and herbal aromatics, followed by bold spirit and bitters"},"finish":{"en":"Long, warming finish with lingering anise, bitters, and lemon"},"balance":{"en":"Spirit-forward with aromatic complexity from absinthe and bitters"}}'::jsonb, '{"best_time":["aperitivo","evening","pre_dinner"],"occasions":["aperitivo","contemplative","sophisticated_gathering","celebration"],"seasons":["autumn","winter","spring","summer"],"food_pairings":{"en":"Excellent with rich Creole cuisine like gumbo, jambalaya, or blackened fish. Pairs well with oysters, spicy foods, or as a powerful aperitif before a hearty meal."},"ideal_for":{"en":"Perfect for whiskey or cognac enthusiasts who appreciate bold, aromatic cocktails with historical significance. Ideal for those who enjoy spirit-forward drinks with complex flavor profiles."}}'::jsonb, '[{"ingredient_id":"ING_COGNAC","quantity":{"amount":50,"unit":"ml"},"display_name":"Cognac","notes":null},{"ingredient_id":"ING_ABSINTHE","quantity":{"amount":10,"unit":"ml"},"display_name":"Absinthe","notes":null},{"ingredient_id":"ING_SUGAR_CUBE","quantity":{"amount":1,"unit":"cube"},"display_name":"Sugar cube","notes":null},{"ingredient_id":"ING_PEYCHAUDS_BITTERS","quantity":{"amount":2,"unit":"dash"},"display_name":"Peychaud''s bitters","notes":null}]'::jsonb, 'stir', '{"en":"Rinse a chilled old-fashioned glass with the absinthe, add crushed ice and set it aside. Stir the remaining ingredients over ice in a mixing glass. Discard the ice and any excess absinthe from the prepared glass, strain the mixed drink into the glass. Add the lemon peel for garnish."}'::jsonb, 'Old Fashioned glass', '{"en":"Lemon peel"}'::jsonb, 'none', 'up', '{"ING_COGNAC"}', '{"complex","herbal","anise"}', 35, 150, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring","summer"}', '{"aperitivo","contemplative","sophisticated_gathering"}', false, false, '{"rye-sazerac","old-fashioned","vieux-carre"}', 'The absinthe rinse is essential - coat the glass and discard excess. Peychaud''s bitters are specific and non-negotiable. Traditional recipe uses cognac, but rye whiskey is also acceptable (and often preferred in New Orleans today). Express lemon oils over drink but traditionally don''t drop the peel in.', 'premium', 70, 'https://iba-world.com/iba-cocktail/sazerac/', 'IBA Official Recipe. Historical information from New Orleans cocktail history and Antoine Amédée Peychaud documentation.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 33. Screwdriver


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('725547c7-5f19-42ab-83d6-306e5cd3f9fc', 'screwdriver', 'd4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3', '{"en":"Screwdriver"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","simple","refreshing","brunch"}', '{"en":"One of the simplest and most popular vodka cocktails, combining just vodka and fresh orange juice. The Screwdriver is refreshing, easy to make, and endlessly customizable - a true crowd-pleaser that works any time of day."}'::jsonb, '{"created_year":"1949","origin":{"city":"Unknown","bar":"Oil fields","country":"USA/Middle East"},"creator":{"name":"American oil workers","profession":"oil workers"},"story":{"en":"The Screwdriver''s origin is debated, but the most popular story dates it to the late 1940s or early 1950s when American oil workers in the Persian Gulf would discreetly add vodka to their orange juice and stir it with a screwdriver - the only tool readily available. The drink gained popularity in America during the 1950s and 1960s, coinciding with vodka''s rise in popularity in the United States. Smirnoff vodka heavily marketed the drink in the 1950s, helping establish it as a staple cocktail. Its simplicity and refreshing taste made it an instant classic."},"named_after":{"en":"Named after the screwdriver tool allegedly used by oil workers to stir vodka into their orange juice when proper bar tools weren''t available."}}'::jsonb, '{"profile":["refreshing","citrus","light"],"description":{"en":"Bright, refreshing, and naturally sweet. The Screwdriver balances the clean neutrality of vodka with the vibrant citrus sweetness and acidity of fresh orange juice."},"first_impression":{"en":"Bright orange citrus sweetness with a subtle vodka backbone"},"finish":{"en":"Clean, refreshing finish with lingering orange citrus notes"},"balance":{"en":"Well-balanced between spirit and juice - vodka provides structure without overpowering the fresh orange flavor"}}'::jsonb, '{"best_time":["morning","afternoon","brunch"],"occasions":["brunch","casual_drink","poolside","beach","party"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with brunch foods - eggs benedict, pancakes, French toast. Also pairs well with light breakfast pastries, fruit salads, and casual appetizers like bruschetta or chips and dip."},"ideal_for":{"en":"Perfect for those who enjoy simple, refreshing drinks. An excellent choice for brunch, poolside relaxation, or anyone new to cocktails. Its simplicity makes it universally appealing and easy to customize to taste."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":50,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":100,"unit":"ml"},"display_name":"Orange juice","notes":null}]'::jsonb, 'build', '{"en":"Pour vodka into a highball glass filled with ice. Add orange juice and stir gently. Garnish with an orange slice."}'::jsonb, 'Highball glass', '{"en":"Orange slice"}'::jsonb, 'cubes', 'on_the_rocks', '{"ING_VODKA"}', '{"refreshing","citrus","light"}', 12, 160, 'easy', 30, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"brunch","casual","poolside","beach"}', false, false, '{"harvey-wallbanger","fuzzy-navel","slow-screw"}', 'Always use fresh-squeezed orange juice when possible - never bottled concentrate. Can adjust vodka-to-juice ratio to guest preference (standard is 1:2). Some guests prefer it built in the glass, others shaken. The Harvey Wallbanger is a popular variant (add Galliano float). Simple to batch for parties.', 'low', 90, 'https://iba-world.com/screwdriver/', 'IBA Official Recipe. Historical information from cocktail history sources and Smirnoff marketing archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 34. Sidecar


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('ece2682c-56f6-41c6-b7e3-0327453bdd1d', 'sidecar', 'sidecar_iba_unforgettables', '{"en":"Sidecar"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","sour","cognac"}', '{"en":"An elegant and refined classic cocktail blending cognac, triple sec, and fresh lemon juice. This sophisticated drink emerged from the golden age of Parisian cocktail culture in the 1920s and remains a timeless favorite."}'::jsonb, '{"created_year":"1922","origin":{"city":"Paris","bar":"Ritz Paris / Harry''s New York Bar","country":"France"},"creator":{"name":"Frank Meier / Pat MacGarry / Harry MacElhone","profession":"bartender"},"story":{"en":"The Sidecar''s origin is one of cocktail history''s most famous disputes. Three establishments claim its invention: the Ritz Paris (bartender Frank Meier), Buck''s Club London (Pat MacGarry), and Harry''s New York Bar in Paris (Harry MacElhone). The first recipes appeared in 1922 in Robert Vermeire''s \"Cocktails and How to Mix Them\" and MacElhone''s \"Harry''s ABC of Mixing Cocktails.\" According to legend, an American Army Captain during World War I would arrive at a Paris bar via motorcycle sidecar. He wanted cognac to warm up before dinner, but the bartender deemed it too strong for early evening, so he mixed it with Cointreau and lemon juice. The drink became immensely popular in Paris and London during the early 1920s Jazz Age. Today, the Ritz Paris still serves an ultra-premium version using pre-phylloxera cognac for around $1,800."},"named_after":{"en":"Named after the motorcycle sidecar in which an American Army Captain would arrive at the bar. The drink warmed him up before dinner without being too strong for early evening."}}'::jsonb, '{"profile":["sour","sweet","citrus","elegant"],"description":{"en":"An exquisitely balanced cocktail with the rich, warming complexity of cognac beautifully complemented by bright citrus and subtle orange sweetness. The Sidecar is sophisticated yet approachable, offering layers of flavor from grape brandy, orange liqueur, and tart lemon in perfect harmony. Neither too sweet nor too sour, it epitomizes the golden ratio of classic cocktail balance."},"first_impression":{"en":"The first sip opens with a bright citrus burst that quickly reveals the sophisticated warmth and fruity complexity of quality cognac, rounded out by orange liqueur."},"finish":{"en":"A clean, elegant finish with lingering cognac warmth and a pleasant citrus-orange afterglow. The finish is smooth and sophisticated, inviting another sip."},"balance":{"en":"The IBA ratio of 50:20:20 creates impeccable balance. The cognac provides structure and depth, triple sec adds orange sweetness and complexity, while lemon juice brings brightness and prevents cloying sweetness. Some bartenders prefer equal parts (33:33:33) for a more spirit-forward profile."}}'::jsonb, '{"best_time":["evening","afternoon"],"occasions":["aperitivo","date_night","cocktail_party","special_occasion"],"seasons":["all_year","fall","winter"],"food_pairings":{"en":"Pairs beautifully with French cuisine, oysters, pâté, foie gras, soft cheeses like Brie or Camembert, duck confit, citrus-based desserts, crème brûlée, and chocolate truffles. The cognac and citrus combination complements rich, fatty foods."},"ideal_for":{"en":"Perfect for cognac enthusiasts seeking a refined cocktail experience. An excellent choice for special occasions, romantic evenings, or as a sophisticated aperitif. Ideal for those who appreciate classic French elegance and balanced sour cocktails."}}'::jsonb, '[{"ingredient_id":"ING_COGNAC","quantity":{"amount":50,"unit":"ml"},"display_name":"Cognac","notes":null},{"ingredient_id":"ING_TRIPLE_SEC","quantity":{"amount":20,"unit":"ml"},"display_name":"Triple Sec","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":20,"unit":"ml"},"display_name":"Fresh Lemon Juice","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake well to chill and dilute. Strain into a chilled cocktail glass. Optionally, rim the glass with sugar for a sweeter presentation."}'::jsonb, 'Cocktail glass', '{"en":"No garnish (optionally sugar rim)"}'::jsonb, 'none', 'up', '{"ING_COGNAC"}', '{"sour","citrus","sweet","elegant","smooth"}', 22, 185, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"all_year","fall","winter"}', '{"aperitivo","date_night","cocktail_party","special_occasion"}', false, false, '{"French Sidecar (equal parts 33:33:33)","Chelsea Sidecar (with gin instead of cognac)","Boston Sidecar (with rum instead of cognac)","Between the Sheets (adds rum)"}', 'Use quality cognac - VS or VSOP grade works well. Cointreau is the gold standard for triple sec, but Grand Marnier adds richer orange flavor. Always use fresh lemon juice. The IBA official ratio is 50:20:20 (cognac:triple sec:lemon), but many bartenders prefer the "French" style equal parts 33:33:33 for more citrus presence. Some guests prefer a sugar rim - to prepare, moisten the rim with lemon and dip in superfine sugar before pouring. Serve well-chilled in a pre-chilled cocktail glass for best experience.', 'mid', 85, 'https://iba-world.com/sidecar/', 'IBA Official Recipe. Historical research from Robert Vermeire''s 1922 "Cocktails and How to Mix Them" and Harry MacElhone''s 1922 "Harry''s ABC of Mixing Cocktails".', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 35. Stinger


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('187178fd-f36a-4c76-9685-a701f6bfaa2f', 'stinger', 'f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5', '{"en":"Stinger"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","after-dinner","digestif","two-ingredient"}', '{"en":"A sophisticated two-ingredient after-dinner cocktail combining cognac with white crème de menthe. The Stinger is refreshingly minty yet warming - a classic digestif that''s both simple and elegant, perfect for ending an evening on a refined note."}'::jsonb, '{"created_year":"1890s","origin":{"city":"New York City","bar":"Unknown","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Stinger likely originated in the 1890s and became particularly popular during Prohibition (1920-1933) when the mint helped mask inferior spirits. The drink gained significant cultural cache in the mid-20th century, becoming the preferred nightcap of high society and appearing in numerous films and novels. It was famously enjoyed by characters in works by F. Scott Fitzgerald and Evelyn Waugh. The simplicity of just two ingredients belies its sophisticated appeal."},"named_after":{"en":"Named for the \"sting\" of mint combined with the warmth of brandy."}}'::jsonb, '{"profile":["minty","warming","smooth"],"description":{"en":"Cool, refreshing mint balanced by warming cognac. The white crème de menthe provides clean, crisp mint flavor without heaviness, while the cognac adds depth, warmth, and complexity. Smooth and sophisticated."},"first_impression":{"en":"Cool mint followed immediately by warming brandy"},"finish":{"en":"Long, warming finish with lingering mint freshness"},"balance":{"en":"Perfect balance between cooling mint and warming cognac"}}'::jsonb, '{"best_time":["after_dinner","late_night","nightcap"],"occasions":["digestivo","nightcap","sophisticated_gathering","date_night"],"seasons":["autumn","winter","spring","summer"],"food_pairings":{"en":"Perfect as a digestif after dinner, especially after rich meals. Pairs well with dark chocolate, chocolate mint desserts, or as a palate cleanser between courses."},"ideal_for":{"en":"Perfect for cognac lovers seeking a refreshing twist. Ideal for those who enjoy after-dinner drinks and appreciate the combination of mint and brandy."}}'::jsonb, '[{"ingredient_id":"ING_COGNAC","quantity":{"amount":50,"unit":"ml"},"display_name":"Cognac","notes":null},{"ingredient_id":"ING_CREME_DE_MENTHE_WHITE","quantity":{"amount":20,"unit":"ml"},"display_name":"White crème de menthe","notes":null}]'::jsonb, 'stir', '{"en":"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"None (or mint leaf optional)"}'::jsonb, 'none', 'up', '{"ING_COGNAC"}', '{"minty","warming","smooth"}', 30, 160, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring","summer"}', '{"digestivo","nightcap","date_night"}', false, false, '{"vodka-stinger","brandy-alexander","grasshopper"}', 'Use white crème de menthe (not green) for a clear appearance. Can be served on the rocks if preferred. Quality cognac is important - the simplicity means there''s nowhere to hide. Some guests may request it shaken for extra chill.', 'mid', 50, 'https://iba-world.com/iba-cocktail/stinger/', 'IBA Official Recipe. Historical information from cocktail history sources and literary references.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 36. Tuxedo


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('280e882e-5653-4967-bfbb-1db43a9b62dc', 'tuxedo', 'b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1', '{"en":"Tuxedo"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","stirred","dry","sophisticated","martini-variation"}', '{"en":"A sophisticated variation on the classic Martini that adds maraschino liqueur to dry vermouth and a hint of absinthe to the final mix. The Tuxedo is dry, elegant, and complex - as refined as the formal attire it''s named after."}'::jsonb, '{"created_year":"1880s","origin":{"city":"New York City","bar":"Tuxedo Club","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Tuxedo cocktail is believed to have originated at the Tuxedo Club in Tuxedo Park, New York, in the late 1880s - the same exclusive club where the tuxedo dinner jacket was popularized. The drink is a variation on the classic Martini, adding maraschino liqueur and absinthe for extra complexity. It represents the height of pre-Prohibition cocktail sophistication."},"named_after":{"en":"Named after the Tuxedo Club in Tuxedo Park, New York, where both the cocktail and the tuxedo formal wear were popularized."}}'::jsonb, '{"profile":["dry","herbal","complex"],"description":{"en":"Dry and botanical with the gin and vermouth foundation enhanced by subtle cherry-almond notes from maraschino and a whisper of herbal absinthe. Orange bitters add aromatic complexity. Elegant and refined."},"first_impression":{"en":"Dry gin with subtle cherry and herbal notes"},"finish":{"en":"Clean, dry finish with lingering botanical and maraschino complexity"},"balance":{"en":"Dry and spirit-forward with subtle sweet and herbal modifiers"}}'::jsonb, '{"best_time":["aperitivo","evening","pre_dinner"],"occasions":["aperitivo","formal_event","date_night","sophisticated_gathering"],"seasons":["autumn","winter","spring","summer"],"food_pairings":{"en":"Excellent with oysters, caviar, smoked salmon, or other elegant appetizers. Pairs well with olives, nuts, and sophisticated canapés."},"ideal_for":{"en":"Perfect for Martini lovers seeking a more complex variation. Ideal for sophisticated drinkers who appreciate dry, spirit-forward cocktails with subtle complexity."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":30,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_DRY_VERMOUTH","quantity":{"amount":30,"unit":"ml"},"display_name":"Dry vermouth","notes":null},{"ingredient_id":"ING_MARASCHINO","quantity":{"amount":5,"unit":"ml"},"display_name":"Maraschino liqueur","notes":null},{"ingredient_id":"ING_ABSINTHE","quantity":{"amount":2,"unit":"barspoon"},"display_name":"Absinthe","notes":null},{"ingredient_id":"ING_ORANGE_BITTERS","quantity":{"amount":3,"unit":"dash"},"display_name":"Orange bitters","notes":null}]'::jsonb, 'stir', '{"en":"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass. Garnish with a cherry and a twist of lemon zest."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"Maraschino cherry and lemon twist"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"dry","herbal","complex"}', 28, 150, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring","summer"}', '{"aperitivo","formal_event","date_night"}', false, false, '{"dry-martini","martinez","aviation"}', 'Stir gently but thoroughly for proper dilution. The equal parts gin and vermouth make this wetter than a modern Martini. Maraschino and absinthe should be subtle - don''t overdo. Express lemon oils over drink before garnishing.', 'mid', 45, 'https://iba-world.com/iba-cocktail/tuxedo/', 'IBA Official Recipe. Historical information from Tuxedo Club history and pre-Prohibition cocktail documentation.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 37. Vieux Carré


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('c0f66767-8ba0-4ae4-baa8-a600527e2abb', 'vieux-carre', 'e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9', '{"en":"Vieux Carré"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","stirred","complex","new-orleans"}', '{"en":"A sophisticated New Orleans classic that masterfully blends rye whiskey, cognac, and sweet vermouth with the herbal complexity of Bénédictine and aromatic Peychaud''s bitters. Named after the French Quarter, this cocktail represents the cultural fusion of French and American spirits."}'::jsonb, '{"created_year":"1938","origin":{"city":"New Orleans","bar":"Hotel Monteleone","country":"USA"},"creator":{"name":"Walter Bergeron","profession":"Head Bartender"},"story":{"en":"The Vieux Carré was invented by Walter Bergeron, Head Bartender at the Hotel Monteleone in New Orleans, in the early or mid-1930s. \"Vieux Carré\" translates as \"old square\" and refers to the original name of the French Quarter in New Orleans. The cocktail was one of 6 drinks added to The Unforgettables category in the 2020 IBA update, cementing its place among classic cocktails. The Hotel Monteleone, where it was created, still operates today and features a famous rotating carousel bar."},"named_after":{"en":"Named after the French Quarter in New Orleans, originally called \"Vieux Carré\" (Old Square)."}}'::jsonb, '{"profile":["complex","herbal","boozy"],"description":{"en":"Rich, complex, and beautifully balanced. The combination of rye and cognac creates depth and warmth, while sweet vermouth adds smoothness. Bénédictine brings herbal complexity, and Peychaud''s bitters provide a distinctive anise-forward spice."},"first_impression":{"en":"Herbal and spicy with anise notes, followed by warming whiskey and brandy"},"finish":{"en":"Long, warming finish with lingering herbal complexity and gentle sweetness"},"balance":{"en":"Masterfully balanced between multiple spirits and modifiers"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["aperitivo","digestivo","date_night","contemplative","celebration"],"seasons":["autumn","winter","spring"],"food_pairings":{"en":"Excellent with Creole cuisine, grilled meats, aged cheeses, or dark chocolate. Pairs beautifully with New Orleans classics like jambalaya, gumbo, or bread pudding."},"ideal_for":{"en":"Perfect for adventurous drinkers who enjoy complex, spirit-forward cocktails. Ideal for whiskey and cognac lovers seeking something unique that showcases both spirits equally."}}'::jsonb, '[{"ingredient_id":"ING_RYE_WHISKEY","quantity":{"amount":30,"unit":"ml"},"display_name":"Rye whiskey","notes":null},{"ingredient_id":"ING_COGNAC","quantity":{"amount":30,"unit":"ml"},"display_name":"Cognac","notes":null},{"ingredient_id":"ING_SWEET_VERMOUTH","quantity":{"amount":30,"unit":"ml"},"display_name":"Sweet vermouth","notes":null},{"ingredient_id":"ING_BENEDICTINE","quantity":{"amount":5,"unit":"ml"},"display_name":"Bénédictine","notes":null},{"ingredient_id":"ING_PEYCHAUDS_BITTERS","quantity":{"amount":2,"unit":"dash"},"display_name":"Peychaud''s bitters","notes":null}]'::jsonb, 'stir', '{"en":"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled cocktail glass. Garnish with orange zest and a maraschino cherry."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"Orange zest and maraschino cherry"}'::jsonb, 'none', 'up', '{"ING_RYE_WHISKEY","ING_COGNAC"}', '{"complex","herbal","boozy"}', 32, 210, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring"}', '{"aperitivo","digestivo","date_night","contemplative"}', false, false, '{"manhattan","sazerac","remember-the-maine"}', 'Bénédictine is essential - don''t substitute. Use Peychaud''s bitters specifically, not Angostura. Equal parts of rye, cognac, and vermouth make this unique. Stir well for proper dilution. Express orange oils over the drink before garnishing.', 'premium', 60, 'https://iba-world.com/iba-cocktail/vieux-carre/', 'IBA Official Recipe. Historical information from Hotel Monteleone and New Orleans cocktail history.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 38. Whiskey Sour


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('1388c221-b95f-41f9-8cc1-1afd4016e837', 'whiskey-sour', 'whiskey_sour_iba_unforgettables', '{"en":"Whiskey Sour"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","sour"}', '{"en":"A timeless classic balancing bourbon whiskey with fresh lemon juice and sugar syrup, optionally topped with a silky egg white foam. One of the most beloved sour cocktails in the world."}'::jsonb, '{"created_year":"1862","origin":{"city":"New York","bar":"Unknown","country":"United States"},"creator":{"name":"Sailors / Jerry Thomas","profession":"bartender"},"story":{"en":"The Whiskey Sour has roots dating back to sailors in the 1800s who added citrus to their whiskey to prevent scurvy during long voyages. The first written mention appeared in 1862 in Jerry Thomas''s \"Bartenders Guide.\" The Wisconsin newspaper Waukesha Plain Dealer first referenced the \"Whisky Sour\" in 1870. In 1872, former ship steward Elliot Staub is credited with \"inventing\" the drink in a bar in Iquique, then part of Peru. The addition of egg white became popular in the 1920s, creating the signature silky foam. Today, the Whiskey Sour is celebrated annually on August 25th and remains one of the most enduring classic cocktails."},"named_after":{"en":"Named after the \"sour\" category of cocktails, which combine spirits with citrus juice and sugar."}}'::jsonb, '{"profile":["sour","sweet","smooth"],"description":{"en":"A perfect harmony of sweet and sour, with the robust character of bourbon whiskey shining through bright lemon citrus and balanced sweetness. The optional egg white adds a luxurious, velvety texture and mellows the acidity. Each sip delivers warmth from the bourbon followed by refreshing citrus tang."},"first_impression":{"en":"The first sip greets you with a bright citrus punch tempered by sweetness, followed immediately by the warm, oaky notes of bourbon."},"finish":{"en":"A clean, slightly dry finish with lingering bourbon warmth and a subtle citrus echo. The egg white version leaves a soft, creamy aftertaste."},"balance":{"en":"Impeccably balanced between sweet and sour, with the bourbon providing a solid foundation. The ratio of 45:25:20 creates a drink that is neither too tart nor too sweet."}}'::jsonb, '{"best_time":["evening","afternoon"],"occasions":["aperitivo","casual_gathering","date_night"],"seasons":["all_year"],"food_pairings":{"en":"Pairs excellently with smoked meats, barbecue ribs, aged cheeses, roasted nuts, dark chocolate desserts, and charcuterie boards. The citrus cuts through rich, fatty foods beautifully."},"ideal_for":{"en":"Perfect for bourbon lovers seeking a refreshing citrus twist, and an ideal introduction to whiskey cocktails for those who find straight whiskey too strong. Great as a pre-dinner drink or evening sipper."}}'::jsonb, '[{"ingredient_id":"ING_BOURBON","quantity":{"amount":45,"unit":"ml"},"display_name":"Bourbon Whiskey","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":25,"unit":"ml"},"display_name":"Fresh Lemon Juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":20,"unit":"ml"},"display_name":"Sugar Syrup","notes":null},{"ingredient_id":"ING_EGG_WHITE","quantity":{"amount":1,"unit":"dash"},"display_name":"Egg White (Optional)","optional":true,"notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake well (shake harder if using egg white to release and incorporate the foam). Strain into a chilled cobbler glass, or for an on-the-rocks version, strain into an old fashioned glass with ice."}'::jsonb, 'Cobbler glass', '{"en":"Half orange slice and maraschino cherry, with optional orange zest"}'::jsonb, 'cubed', 'up', '{"ING_BOURBON"}', '{"sour","sweet","citrus","smooth"}', 18, 160, 'easy', 90, '{"sulphites","egg"}', '{"alcohol","sulphites_intolerance","egg_intolerance"}', '{"pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"gluten-free","dairy-free"}', '{"all_year"}', '{"aperitivo","casual_gathering","date_night"}', false, false, '{"New York Sour (with red wine float)","Boston Sour (with egg white)","Ward Eight (with grenadine and orange)"}', 'When making with egg white, dry shake first (without ice) for 10 seconds to emulsify, then add ice and shake again vigorously for 15-20 seconds. The IBA recipe calls for "few drops" of egg white, but modern bartenders typically use one full egg white for better foam. Always use fresh lemon juice - never bottled. Can be served either up in a cobbler glass or on the rocks in an old fashioned glass per customer preference.', 'mid', 95, 'https://iba-world.com/whiskey-sour/', 'IBA Official Recipe. Historical research from Jerry Thomas''s 1862 Bartenders Guide, Waukesha Plain Dealer 1870, and modern cocktail historians.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 39. White Lady


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('fd7cf733-0bbe-4dec-8890-e324a085c544', 'white-lady', 'a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0', '{"en":"White Lady"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","sour","citrus","elegant"}', '{"en":"An elegant gin sour featuring the perfect trinity of gin, Cointreau, and fresh lemon juice. The White Lady is crisp, balanced, and sophisticated - a true symbol of classic cocktail refinement that has remained popular for nearly a century."}'::jsonb, '{"created_year":"1929","origin":{"city":"London","bar":"Harry''s New York Bar","country":"UK"},"creator":{"name":"Harry MacElhone","profession":"bartender"},"story":{"en":"First created by Harry MacElhone in 1919, the White Lady underwent a transformation in 1929 when gin replaced crème de menthe, defining the recipe we know today. Originally served at Ciro''s Club in London, this cocktail has traveled through decades, becoming a symbol of sophistication in bars worldwide. Some variations add egg white for extra silkiness, though the IBA standard recipe does not include it."},"named_after":{"en":"Named for its pale, elegant appearance and refined character."}}'::jsonb, '{"profile":["citrus","sharp","refreshing"],"description":{"en":"Crisp and bracingly tart with bright lemon leading the way, balanced by the orange sweetness of Cointreau and the botanical complexity of gin. Clean, refreshing, and perfectly balanced."},"first_impression":{"en":"Bright, sharp lemon with orange sweetness"},"finish":{"en":"Clean, crisp finish with lingering citrus and botanical notes"},"balance":{"en":"Perfect balance between tart lemon, sweet orange, and botanical gin"}}'::jsonb, '{"best_time":["aperitivo","evening","pre_dinner"],"occasions":["aperitivo","date_night","celebration","sophisticated_gathering"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Excellent with oysters, smoked salmon, light seafood, or as an aperitif before dinner. Pairs beautifully with citrus-based dishes and fresh salads."},"ideal_for":{"en":"Perfect for gin enthusiasts who appreciate clean, citrus-forward cocktails. Ideal for those who enjoy Margaritas or Daiquiris but prefer gin as their base spirit."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":40,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_TRIPLE_SEC","quantity":{"amount":30,"unit":"ml"},"display_name":"Triple sec (Cointreau)","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":20,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"Lemon twist"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"citrus","sharp","refreshing"}', 22, 180, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"spring","summer","autumn"}', '{"aperitivo","date_night","celebration"}', false, false, '{"white-lady-with-egg-white","clover-club","aviation"}', 'Use Cointreau for best results - quality triple sec is essential. Fresh lemon juice only. Some guests may request egg white for silkiness - add 15ml if requested. Shake hard for proper dilution and chill.', 'mid', 75, 'https://iba-world.com/iba-cocktail/white-lady/', 'IBA Official Recipe. Historical information from Harry MacElhone and cocktail history sources.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 40. B-52


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('dd3091ea-e646-4c16-b9a3-99259f8a4ece', 'b-52', 'b_52_iba_contemporary_classic', '{"en":"B-52"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","layered","shot","coffee","sweet","party","flaming"}', '{"en":"A visually stunning layered shot combining coffee liqueur, Irish cream, and orange liqueur. Famous for its three distinct layers and often served flaming, the B-52 is a party favorite and a bartender''s showcase of layering technique."}'::jsonb, '{"created_year":"1970s","origin":{"city":"Calgary","bar":"Keg Steakhouse","country":"Canada"},"creator":{"name":"Peter Fich","profession":"bartender"},"story":{"en":"Created by bartender Peter Fich at the Keg Steakhouse in Calgary, Alberta, Canada in the late 1970s. The drink is named after the B-52 Stratofortress long-range bomber aircraft used by the United States Air Force. Fich created a series of layered shots named after military aircraft. The B-52 became the most famous of this family, which also includes the B-51, B-53, and B-54. The drink gained international popularity in the 1980s and became a staple of the shooter/layered shot category."},"named_after":{"en":"Named after the Boeing B-52 Stratofortress, a long-range strategic bomber aircraft. The layered presentation supposedly resembles the layers of the bomber''s structure."}}'::jsonb, '{"profile":["creamy","sweet","citrus","smooth"],"description":{"en":"A harmonious blend of coffee, cream, and orange flavors. Kahlúa provides rich coffee base, Baileys adds creamy sweetness, and Grand Marnier brings bright orange citrus notes. Sweet, smooth, and dangerously easy to drink."},"first_impression":{"en":"Orange citrus brightness followed by creamy coffee sweetness"},"finish":{"en":"Smooth, warming finish with coffee and cream lingering"},"balance":{"en":"Well-balanced layers of distinct flavors - coffee, cream, and orange working in harmony"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["party","celebration","casual","nightcap"],"seasons":["autumn","winter","spring","summer"],"food_pairings":{"en":"Typically served as a standalone shot or after-dinner drink. Not usually paired with food, but works well after dessert or as a digestif."},"ideal_for":{"en":"Perfect for party settings and groups. Ideal for those who enjoy sweet, layered shots and want to see impressive bartending technique. Popular with younger crowds and celebration occasions."}}'::jsonb, '[{"ingredient_id":"ING_COFFEE_LIQUEUR","quantity":{"amount":20,"unit":"ml"},"display_name":"Coffee liqueur (Kahlúa)","notes":null},{"ingredient_id":"ING_IRISH_CREAM","quantity":{"amount":20,"unit":"ml"},"display_name":"Irish cream (Baileys)","notes":null},{"ingredient_id":"ING_TRIPLE_SEC","quantity":{"amount":20,"unit":"ml"},"display_name":"Triple sec (Grand Marnier)","notes":null}]'::jsonb, 'layer', '{"en":"Layer ingredients one by one into a shot glass in the order listed. Start with coffee liqueur at the bottom, carefully layer Baileys on top using the back of a bar spoon, then layer Grand Marnier on top. The key is to pour slowly and gently to maintain distinct layers. Can be served flaming (ignite the Grand Marnier layer) but must be extinguished before drinking."}'::jsonb, 'Shot glass', '{"en":"None (optional: flame the top layer)"}'::jsonb, 'none', 'shot', '{"ING_COFFEE_LIQUEUR","ING_IRISH_CREAM","ING_TRIPLE_SEC"}', '{"creamy","sweet","citrus","smooth"}', 25, 180, 'medium', 90, '{"milk","sulphites"}', '{"lactose","alcohol","sulphites_intolerance","caffeine"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 0, '{"vegetarian","gluten-free"}', '{"autumn","winter","spring","summer"}', '{"party","celebration","casual"}', false, false, '{"b-51","b-53","b-54","flaming-b-52","b-52-bomber"}', 'Layering requires patience and steady hand. Pour slowly over the back of a bar spoon to maintain layers. Kahlúa (heaviest) goes first, then Baileys, then Grand Marnier (lightest). If flaming: light only the top layer, ensure guest knows to blow out flame before drinking. Never serve a flaming shot without safety instructions. Practice layering technique before service. Equal parts = perfect visual layers.', 'low', 75, 'https://iba-world.com/b-52/', 'IBA Official Recipe. Historical information from cocktail history sources and Peter Fich interviews.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


