INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('0a6a50d5-ad2c-4b07-be9c-27d3afb3cfc9', 'navy-grog', 'navy_grog_famous_tiki_tropical_cocktail', '{"en":"Navy Grog"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","citrus","strong"}', '{"en":"The Navy Grog is a classic tiki cocktail created by Don the Beachcomber, featuring three types of rum with honey, citrus, and club soda. Traditionally served with an ice cone, this refreshing yet potent drink honors naval grog traditions with a tiki twist."}'::jsonb, '{"created_year":"1941","origin":{"city":"Hollywood","bar":"Don the Beachcomber","country":"USA"},"creator":{"name":"Ernest Raymond Beaumont Gantt (Donn Beach)","profession":"bartender"},"story":{"en":"The Navy Grog was created in 1941 by Ernest Raymond Beaumont Gantt, better known as Don the Beachcomber, at his Hollywood restaurant. The drink pays homage to traditional naval grog - the rum ration given to British sailors since the 18th century. Don''s version elevated the simple rum-and-water mixture into a sophisticated tiki cocktail by combining three different rums with honey, fresh citrus, and club soda. The signature presentation features a carved ice cone in the center of the glass, which slowly dilutes the drink as it melts. During World War II, the Navy Grog became particularly popular with servicemen on leave. The recipe remained a closely guarded secret for decades."},"named_after":{"en":"Named after traditional naval grog, the daily rum ration given to British Royal Navy sailors from 1740 to 1970."}}'::jsonb, '{"profile":["citrus","refreshing","strong"],"description":{"en":"Bright and refreshing with complex rum depth and honeyed citrus character. The Navy Grog balances three different rums with tart grapefruit and lime, sweetened with honey and lengthened with soda. The ice cone provides controlled dilution, making it refreshing yet substantial."},"first_impression":{"en":"Bright citrus and honey hit first, followed by the complex warmth of triple rum blend"},"finish":{"en":"Long, refreshing finish with lingering citrus and subtle rum complexity, smoothed by honey"},"balance":{"en":"Well-balanced between strong rum foundation and refreshing citrus-soda lift, honey provides smooth integration"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["tiki_bar","summer_gathering","outdoor_party"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with Caribbean jerk dishes, grilled seafood, fish tacos, or Polynesian appetizers. Also pairs well with spicy Asian cuisine and tropical fruit salads."},"ideal_for":{"en":"Perfect for tiki purists and rum enthusiasts seeking an authentic Don the Beachcomber experience. Ideal for those who appreciate balanced, citrus-forward cocktails with serious rum complexity. Great for hot weather refreshment."}}'::jsonb, '[{"ingredient_id":"ING_RUM_WHITE","quantity":{"amount":30,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_RUM_DARK","quantity":{"amount":30,"unit":"ml"},"display_name":"Dark rum (Jamaican)","notes":null},{"ingredient_id":"ING_RUM_DEMERARA","quantity":{"amount":30,"unit":"ml"},"display_name":"Demerara rum","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_GRAPEFRUIT_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh grapefruit juice","notes":null},{"ingredient_id":"ING_HONEY_SYRUP","quantity":{"amount":15,"unit":"ml"},"display_name":"Honey syrup","notes":null},{"ingredient_id":"ING_CLUB_SODA","quantity":{"amount":30,"unit":"ml"},"display_name":"Club soda","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients except club soda to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Pour unstrained into a double old-fashioned glass. Add club soda. Traditionally, place an ice cone in the center of the drink. Garnish with mint sprig."}'::jsonb, 'Double old-fashioned', '{"en":"Fresh mint sprig, ice cone (traditional)"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_RUM_WHITE","ING_RUM_DARK","ING_RUM_DEMERARA"}', '{"citrus","refreshing","strong"}', 16, 240, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"tiki_bar","summer_gathering","outdoor_party"}', false, false, '{"don-the-beachcomber-navy-grog"}', 'Original Don the Beachcomber recipe from 1941. Three-rum blend is essential - each rum adds unique character. Ice cone is traditional but optional - if making cone, carve from block ice. Honey syrup is 1:1 honey to water. Pour unstrained for authentic presentation.', 'premium', 70, 'https://beachbumberry.com/navy-grog.html', 'Original Don the Beachcomber recipe from 1941. Jeff "Beachbum" Berry''s Sippin'' Safari. Tiki cocktail archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 183. Nutty Irishman


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('cc82fa84-07e8-41ed-8b79-2209d1341151', 'nutty-irishman', 'nutty_irishman_baileys_frangelico_coffee', '{"en":"Nutty Irishman"}'::jsonb, 'famous', NULL, '{"creamy","dessert","famous","coffee","nutty","sweet","hot"}', '{"en":"A delicious hot coffee cocktail combining Irish cream and hazelnut liqueur with hot coffee. This warming drink blends the creamy sweetness of Baileys with the nutty notes of Frangelico for an indulgent coffee experience."}'::jsonb, '{"created_year":"1980s","origin":{"country":"USA"},"story":{"en":"The Nutty Irishman emerged in the 1980s as bartenders experimented with combining different liqueurs in hot coffee drinks. The pairing of Baileys Irish Cream with Frangelico hazelnut liqueur proved to be a winning combination, creating a drink that was more complex than simple Irish Cream Coffee but still approachable and sweet. The cocktail became popular in bars and restaurants as a dessert coffee option, especially in colder months. It can be served hot or as a chilled cocktail over ice."},"named_after":{"en":"Named for the combination of Irish cream and the \"nutty\" flavor from hazelnut liqueur."}}'::jsonb, '{"profile":["creamy","sweet","nutty","coffee"],"description":{"en":"Rich and creamy with pronounced hazelnut and chocolate notes balanced by hot coffee. The Frangelico adds a sophisticated nutty dimension to the sweet Irish cream, creating a more complex flavor profile than standard Irish cream coffee."},"first_impression":{"en":"Hot, sweet coffee with immediate hazelnut and cream notes"},"finish":{"en":"Warm, lingering hazelnut sweetness with coffee undertones"},"balance":{"en":"Well-balanced between nutty sweetness and coffee bitterness, more complex than simple cream liqueur drinks"}}'::jsonb, '{"best_time":["morning","afternoon","evening"],"occasions":["brunch","dessert","winter","casual","nightcap"],"seasons":["autumn","winter"],"food_pairings":{"en":"Perfect with hazelnut desserts, chocolate cake, tiramisu, or biscotti. Also pairs well with breakfast pastries and nutella-based treats."},"ideal_for":{"en":"Perfect for hazelnut lovers and those who enjoy flavored coffee drinks. Ideal for cold weather, après-ski, brunch occasions, and anyone seeking a more sophisticated alternative to Irish Cream Coffee."}}'::jsonb, '[{"ingredient_id":"ING_IRISH_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Irish cream (Baileys)","notes":null},{"ingredient_id":"ING_FRANGELICO","quantity":{"amount":30,"unit":"ml"},"display_name":"Frangelico (hazelnut liqueur)","notes":null},{"ingredient_id":"ING_HOT_COFFEE","quantity":{"amount":120,"unit":"ml"},"display_name":"Hot coffee","notes":null},{"ingredient_id":"ING_WHIPPED_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Whipped cream","optional":true,"notes":null}]'::jsonb, 'build', '{"en":"Warm an Irish coffee glass or heat-resistant mug with hot water, then discard. Pour Irish cream and Frangelico into the warmed glass. Add freshly brewed hot coffee and stir gently. Top with whipped cream if desired. Optionally garnish with crushed hazelnuts or chocolate shavings. Serve immediately while hot."}'::jsonb, 'Irish coffee glass (or mug)', '{"en":"Whipped cream, crushed hazelnuts, or chocolate shavings"}'::jsonb, 'none', 'hot', '{"ING_IRISH_CREAM","ING_FRANGELICO"}', '{"creamy","sweet","nutty","coffee"}', 10, 250, 'easy', 45, '{"milk","tree_nuts"}', '{"lactose","alcohol","caffeine","nut_allergy"}', '{"vegetarian","pescatarian","gluten_free"}', 0, '{"vegetarian","gluten-free"}', '{"autumn","winter"}', '{"brunch","dessert","casual","nightcap"}', false, false, '{"iced-nutty-irishman","nutty-irishman-shooter","nutty-coffee-martini"}', 'Contains hazelnut liqueur - always check for nut allergies. Can also be served over ice as a cold cocktail. Frangelico is essential for authentic flavor. Popular as a dessert coffee option. Some guests may want extra Frangelico for stronger hazelnut flavor.', 'mid', 65, 'https://www.liquor.com/recipes/nutty-irishman/', 'Popular hot coffee cocktail combining Irish cream and hazelnut liqueur.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 184. Oaxaca Old Fashioned


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('9a480d1b-65eb-4bb1-8308-bbc7b7462333', 'oaxaca-old-fashioned', '726354849302847563829104857362918475638291', '{"en":"Oaxaca Old Fashioned"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","mezcal","tequila","smoky"}', '{"en":"A revolutionary modern classic that reimagines the Old Fashioned with agave spirits. Created by Phil Ward, this cocktail combines reposado tequila and mezcal with agave nectar and bitters, creating a smoky, complex drink that respects the Old Fashioned format while being entirely its own."}'::jsonb, '{"created_year":"2007","origin":{"city":"New York City","bar":"Death & Co","country":"USA"},"creator":{"name":"Phil Ward","profession":"bartender"},"story":{"en":"Phil Ward created the Oaxaca Old Fashioned in 2007 at Death & Co, one of New York''s pioneering craft cocktail bars. Ward wanted to showcase mezcal but knew many guests were intimidated by its intense smoky flavor. By splitting the base between reposado tequila and mezcal, and using agave nectar instead of simple syrup, he created a more approachable introduction to mezcal while maintaining complexity. The drink became an instant sensation and is considered one of the most influential modern cocktails, helping launch the mezcal boom of the 2010s."},"named_after":{"en":"Named after Oaxaca, Mexico, the heartland of mezcal production and the source of the cocktail''s smoky soul."}}'::jsonb, '{"profile":["smoky","agave","complex","stirred"],"description":{"en":"Beautifully balanced and complex. Reposado tequila provides a smooth agave base with vanilla and oak notes, while mezcal adds smoky depth without overwhelming. Agave nectar enhances the agave character, and mole bitters add chocolate-spice complexity. Richer and earthier than a whiskey Old Fashioned, with a silky texture and long finish."},"first_impression":{"en":"Smooth agave and subtle smoke hit first, followed by chocolate-spice notes"},"finish":{"en":"Long, warming finish with lingering smoke, agave, and mole spice"},"balance":{"en":"Expertly balanced - tequila smooths mezcal''s intensity, creating approachable complexity"}}'::jsonb, '{"best_time":["evening","late_night","contemplative"],"occasions":["date_night","contemplative_drinking","digestivo","special_occasion"],"seasons":["autumn","winter","spring","summer"],"food_pairings":{"en":"Excellent with Mexican cuisine, especially mole dishes, grilled meats, or dark chocolate desserts. Also pairs well with aged cheeses, smoked foods, and rich, savory dishes."},"ideal_for":{"en":"Perfect for Old Fashioned lovers seeking new experiences. Ideal for those exploring agave spirits or wanting an introduction to mezcal. Great for contemplative sipping and conversation."}}'::jsonb, '[{"ingredient_id":"ING_TEQUILA_REPOSADO","quantity":{"amount":45,"unit":"ml"},"display_name":"Reposado tequila","notes":null},{"ingredient_id":"ING_MEZCAL","quantity":{"amount":15,"unit":"ml"},"display_name":"Mezcal","notes":null},{"ingredient_id":"ING_AGAVE_SYRUP","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Agave syrup","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":2,"unit":"dashes"},"display_name":"Angostura bitters","notes":null},{"ingredient_id":"ING_MOLE_BITTERS","quantity":{"amount":1,"unit":"dash"},"display_name":"Mole bitters","optional":true,"notes":null}]'::jsonb, 'stir', '{"en":"Add all ingredients to a mixing glass filled with ice. Stir gently for 30-40 seconds until properly chilled and diluted. Strain into a rocks glass over a large ice cube. Garnish with a flamed orange peel, expressing oils over the drink."}'::jsonb, 'Rocks glass', '{"en":"Flamed orange peel"}'::jsonb, 'large_cube', 'on_the_rocks', '{"ING_TEQUILA_REPOSADO","ING_MEZCAL"}', '{"smoky","agave","complex","stirred"}', 32, 180, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring","summer"}', '{"date_night","contemplative_drinking","digestivo","special_occasion"}', false, false, '{"mezcal-old-fashioned","tequila-old-fashioned","sotol-old-fashioned"}', 'Mole bitters essential for authentic version - adds chocolate-spice complexity. Flame orange peel for theatrical presentation and caramelization. Use quality reposado and artisanal mezcal. Large ice cube minimizes dilution.', 'premium', 85, 'https://www.deathandcompany.com/', 'Created by Phil Ward at Death & Co, New York City, 2007. One of the most influential modern cocktails.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 185. Orgasm


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('e929f5bc-0cd2-4dcf-b8ca-92661e6180f4', 'orgasm', 'orgasm_amaretto_kahlua_baileys_cream', '{"en":"Orgasm"}'::jsonb, 'famous', NULL, '{"creamy","dessert","famous","shooter","sweet","coffee","nutty"}', '{"en":"A decadent shooter combining amaretto, coffee liqueur, Irish cream, and cream. This infamous shot delivers an explosion of sweet, creamy flavors with notes of almond, coffee, and chocolate in one indulgent gulp."}'::jsonb, '{"created_year":"1980s","origin":{"country":"USA"},"story":{"en":"The Orgasm shot emerged in the 1980s during the height of the shooter craze in American bars. Its provocative name and intensely sweet, creamy flavor made it an instant hit at parties and nightclubs. The drink became part of a family of similarly-named shots (Screaming Orgasm, Multiple Orgasm, etc.) that dominated bar culture in the late 1980s and 1990s. While some consider the name dated, the delicious combination of amaretto, coffee liqueur, and cream remains popular as both a shot and a cocktail."},"named_after":{"en":"The provocative name refers to the intensely pleasurable, indulgent experience of drinking this sweet, creamy shot."}}'::jsonb, '{"profile":["creamy","sweet","coffee","nutty"],"description":{"en":"Intensely sweet and creamy with harmonious notes of almond, coffee, and chocolate. The amaretto provides nutty sweetness, the Kahlúa adds coffee depth, and the Baileys and cream create a silky, indulgent texture. Very dessert-forward and smooth."},"first_impression":{"en":"Sweet cream explosion with immediate almond and coffee notes"},"finish":{"en":"Lingering sweetness with coffee, almond, and cream"},"balance":{"en":"Very sweet and indulgent - designed for pleasure rather than balance"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["party","celebration","bachelor_party","casual"],"seasons":["all_seasons"],"food_pairings":{"en":"Typically consumed as a standalone shot. Can accompany desserts or serve as a liquid dessert itself."},"ideal_for":{"en":"Perfect for those who enjoy very sweet, creamy shots. Ideal for parties, celebrations, and social drinking occasions. Popular with guests seeking an indulgent, dessert-like shot experience."}}'::jsonb, '[{"ingredient_id":"ING_AMARETTO","quantity":{"amount":15,"unit":"ml"},"display_name":"Amaretto","notes":null},{"ingredient_id":"ING_COFFEE_LIQUEUR","quantity":{"amount":15,"unit":"ml"},"display_name":"Coffee liqueur (Kahlúa)","notes":null},{"ingredient_id":"ING_IRISH_CREAM","quantity":{"amount":15,"unit":"ml"},"display_name":"Irish cream (Baileys)","notes":null},{"ingredient_id":"ING_HEAVY_CREAM","quantity":{"amount":15,"unit":"ml"},"display_name":"Heavy cream","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake well for 10 seconds until chilled. Strain into a shot glass. Shoot in one gulp or sip slowly to enjoy the flavors. Can also be served on the rocks in a rocks glass for a longer drinking experience."}'::jsonb, 'Shot glass (or Rocks glass)', '{"en":"None"}'::jsonb, 'none', 'shot', '{"ING_AMARETTO"}', '{"creamy","sweet","coffee","nutty"}', 15, 180, 'easy', 30, '{"milk","tree_nuts"}', '{"lactose","alcohol","caffeine","nut_allergy"}', '{"vegetarian","pescatarian","gluten_free"}', 0, '{"vegetarian","gluten-free"}', '{"all-seasons"}', '{"party","celebration","casual"}', false, false, '{"screaming-orgasm","multiple-orgasm","slow-comfortable-screw"}', 'Contains nut liqueur - check for allergies. Name may require discretion with certain clientele. Can be made as a cocktail over ice for slower consumption. Very popular party shot. Some recipes add vodka (becomes Screaming Orgasm).', 'low', 75, 'https://www.liquor.com/recipes/orgasm/', 'Classic 1980s party shooter with provocative name.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 186. Painkiller


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('caa55fab-25dd-4a38-a8e4-4d793bed0c8e', 'painkiller', 'painkiller_famous_tiki_tropical_cocktail', '{"en":"Painkiller"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","creamy","sweet"}', '{"en":"The Painkiller is the signature cocktail of the British Virgin Islands, combining dark rum with pineapple juice, orange juice, and coconut cream. This creamy tropical drink topped with nutmeg is the ultimate island escape in a glass."}'::jsonb, '{"created_year":"1970","origin":{"city":"White Bay","bar":"Soggy Dollar Bar","country":"British Virgin Islands"},"creator":{"name":"Daphne Henderson","profession":"bar owner"},"story":{"en":"The Painkiller was created in the 1970s by Daphne Henderson at the Soggy Dollar Bar on Jost Van Dyke in the British Virgin Islands. The bar got its name because customers had to swim to shore to reach it, arriving with soggy dollar bills. In 1989, Pusser''s Rum trademarked the name \"Painkiller\" and established the official recipe. The drink became so popular that it spawned numerous variations and inspired tropical cocktail culture worldwide."},"named_after":{"en":"Named for its reputation as a hangover cure and the perfect remedy for any ailment while on vacation in paradise."}}'::jsonb, '{"profile":["tropical","creamy","sweet"],"description":{"en":"Rich and indulgent with layers of tropical fruit flavors. The Painkiller balances pineapple brightness with orange tang, coconut creaminess, and the deep, warming notes of aged rum, finished with aromatic nutmeg."},"first_impression":{"en":"Sweet tropical fruits and coconut cream hit immediately, with rum warmth building underneath"},"finish":{"en":"Long, creamy finish with lingering nutmeg spice and rum warmth"},"balance":{"en":"Perfectly balanced between sweet tropical juices and rich coconut cream, with enough rum to keep it interesting"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["beach","pool_party","vacation","summer_gathering"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with Caribbean jerk chicken, fish tacos, coconut shrimp, or tropical fruit platters. Also excellent with spicy foods as the cream helps balance the heat."},"ideal_for":{"en":"Perfect for beach lovers and tropical cocktail enthusiasts. Ideal for anyone seeking a vacation vibe or looking to escape to an island paradise. Great for those who enjoy creamy, dessert-like cocktails."}}'::jsonb, '[{"ingredient_id":"ING_RUM_DARK","quantity":{"amount":60,"unit":"ml"},"display_name":"Dark rum (Pusser''s)","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":120,"unit":"ml"},"display_name":"Pineapple juice","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Orange juice","notes":null},{"ingredient_id":"ING_COCONUT_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Cream of coconut","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a hurricane glass filled with crushed ice. Garnish generously with freshly grated nutmeg on top."}'::jsonb, 'Hurricane glass', '{"en":"Freshly grated nutmeg, pineapple wedge, orange slice"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_RUM_DARK"}', '{"tropical","creamy","sweet"}', 12, 320, 'easy', 90, '{"coconut","sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 1, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"beach","pool_party","vacation","summer_gathering"}', false, false, '{"painkiller-2","painkiller-3","painkiller-4"}', 'Original recipe calls for Pusser''s Navy Rum. Ratios vary: Painkiller #2 (2oz rum), #3 (3oz rum), #4 (4oz rum). Always use freshly grated nutmeg, not pre-ground. Crushed ice is essential for proper dilution.', 'mid', 85, 'https://pussersrum.com/painkiller-cocktail/', 'Official Pusser''s Rum recipe. Historical information from Soggy Dollar Bar and Caribbean cocktail sources.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 187. Pearl Diver


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('d61f9b1a-51db-4fcd-a6eb-db3c50f46705', 'pearl-diver', 'pearl_diver_famous_tiki_tropical_cocktail', '{"en":"Pearl Diver"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","creamy","unique"}', '{"en":"The Pearl Diver is an exotic tiki cocktail created by Don the Beachcomber, famous for its unusual use of a butter-based mix that creates a rich, velvety texture. This complex drink combines rum with citrus and exotic spices in a uniquely luxurious presentation."}'::jsonb, '{"created_year":"1937","origin":{"city":"Hollywood","bar":"Don the Beachcomber","country":"USA"},"creator":{"name":"Ernest Raymond Beaumont Gantt (Donn Beach)","profession":"bartender"},"story":{"en":"The Pearl Diver was created in 1937 by Don the Beachcomber and became famous for its revolutionary ingredient: \"Gardenia Mix,\" a butter-based emulsion that Don created specifically for this drink. In an era before cream liqueurs were common, the idea of adding butter to a cocktail was shocking and innovative. The Gardenia Mix (made from butter, honey, and spices) creates an impossibly smooth, rich texture that was unlike anything else in cocktail culture. The name \"Pearl Diver\" evokes the exotic romance of South Pacific pearl diving, fitting perfectly into Don''s escapist tiki narrative. The recipe remained one of Don''s most closely guarded secrets for decades. When finally decoded, it revealed an incredibly complex formula that pushed the boundaries of what a cocktail could be."},"named_after":{"en":"Named after pearl divers of the South Pacific, evoking exotic romance and adventure in tropical waters."}}'::jsonb, '{"profile":["rich","creamy","complex"],"description":{"en":"Extraordinarily rich and velvety with unprecedented texture from the butter-honey emulsion. The Pearl Diver balances complex rum depth with bright citrus, warming spices, and the signature Gardenia Mix that creates a luxurious, almost dessert-like smoothness. Unique among tiki drinks."},"first_impression":{"en":"Rich, creamy texture hits immediately, followed by tropical rum and citrus complexity"},"finish":{"en":"Long, luxurious finish with lingering butter-honey richness and warm spice notes"},"balance":{"en":"Uniquely balanced between rich butter-honey luxury and bright tropical freshness"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["tiki_bar","special_occasion","dessert_replacement"],"seasons":["autumn","winter"],"food_pairings":{"en":"Perfect with rich desserts, coconut cake, tropical fruit tarts, or as a standalone dessert drink. Also pairs with spiced dishes and holiday treats."},"ideal_for":{"en":"Perfect for tiki collectors and adventurous drinkers seeking the most unique Don the Beachcomber experience. Ideal for those who appreciate innovative, boundary-pushing cocktails. A must-try for serious tiki enthusiasts."}}'::jsonb, '[{"ingredient_id":"ING_RUM_DARK","quantity":{"amount":45,"unit":"ml"},"display_name":"Dark rum","notes":null},{"ingredient_id":"ING_RUM_DEMERARA","quantity":{"amount":15,"unit":"ml"},"display_name":"Demerara rum","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_GARDENIA_MIX","quantity":{"amount":30,"unit":"ml"},"display_name":"Gardenia Mix (butter-honey blend)","notes":null},{"ingredient_id":"ING_FALERNUM","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Falernum","notes":null}]'::jsonb, 'blend', '{"en":"Add all ingredients to a blender with 1 cup of crushed ice. Blend at high speed until smooth and frothy. Pour into a tiki mug or hurricane glass. Garnish with orchid and orange slice. Note: Gardenia Mix must be prepared in advance (butter, honey, vanilla, cinnamon)."}'::jsonb, 'Tiki mug / Hurricane glass', '{"en":"Orchid flower, orange slice, cinnamon stick"}'::jsonb, 'blended', 'frozen', '{"ING_RUM_DARK","ING_RUM_DEMERARA"}', '{"rich","creamy","complex"}', 15, 340, 'hard', 180, '{"milk","sulphites"}', '{"lactose","alcohol","sulphites_intolerance"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 1, '{"vegetarian","gluten-free"}', '{"autumn","winter"}', '{"tiki_bar","special_occasion","dessert_replacement"}', false, false, '{"don-the-beachcomber-pearl-diver"}', 'ADVANCED RECIPE - requires pre-made Gardenia Mix (butter, honey, vanilla, cinnamon blend). Created by Don the Beachcomber 1937. Must be blended to properly emulsify butter. Contains dairy. Unique texture unlike any other cocktail. Spectacular presentation piece.', 'premium', 55, 'https://beachbumberry.com/pearl-diver.html', 'Original Don the Beachcomber recipe from 1937, decoded by Jeff "Beachbum" Berry. Gardenia Mix formula revealed in Sippin'' Safari.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 188. Pegu Club


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('fff6731c-e791-41b5-a2bc-e05949988138', 'pegu-club', 'm3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2', '{"en":"Pegu Club"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","gin","citrus","colonial","exotic"}', '{"en":"An exotic gin sour from British Colonial Burma. The Pegu Club combines gin with orange curaçao, lime juice, and aromatic bitters for a sophisticated, citrus-forward cocktail with a touch of tropical intrigue. Named after the legendary gentlemen''s club in Rangoon, it''s a taste of colonial elegance."}'::jsonb, '{"created_year":"1920","origin":{"city":"Rangoon (Yangon)","bar":"Pegu Club","country":"Burma (Myanmar)"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Pegu Club cocktail was created at the legendary Pegu Club, a colonial-era gentlemen''s club in Rangoon (now Yangon), Burma (now Myanmar), established in the 1880s. The club, named after the nearby Pegu River, was the social center for British colonial officers and elite expatriates. The cocktail first appeared in print in Harry MacElhone''s \"Harry''s ABC of Mixing Cocktails\" (1922) and later in Harry Craddock''s \"The Savoy Cocktail Book\" (1930). The drink embodies the exotic sophistication of British colonial bar culture - a gin sour elevated with orange liqueur and bitters. After World War II, the Pegu Club fell into decline, and the cocktail became obscure. It was revived in the 2000s when Audrey Saunders opened a New York cocktail bar named \"Pegu Club\" in its honor, reintroducing this forgotten classic to modern drinkers."},"named_after":{"en":"Named after the Pegu Club, a famous colonial-era gentlemen''s club in Rangoon, Burma, which was named after the Pegu River."}}'::jsonb, '{"profile":["citrus","bitter","sophisticated"],"description":{"en":"Crisp, citrusy, and elegantly bitter. The Pegu Club balances gin''s botanicals with bright lime acidity, orange curaçao''s sweetness, and the aromatic complexity of bitters. It''s a more sophisticated, exotic take on the classic gin sour."},"first_impression":{"en":"Sharp lime acidity with orange sweetness, followed by gin botanicals and aromatic bitters"},"finish":{"en":"Clean, crisp finish with lingering lime, orange, and subtle bitter spice"},"balance":{"en":"Perfectly balanced between tart lime, sweet orange, and aromatic bitters - sophisticated and complex"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["aperitivo","sophisticated","date_night","colonial_theme"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Pairs beautifully with Southeast Asian cuisine, Indian dishes, curry, grilled seafood, and spicy appetizers. Also excellent with British colonial fare and afternoon tea snacks."},"ideal_for":{"en":"Perfect for gin lovers who appreciate citrus-forward sours with complexity. Ideal for cocktail historians and those who enjoy exotic, colonial-era drinks. A sophisticated choice for tropical or Asian-themed gatherings."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":60,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_ORANGE_CURACAO","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Orange curaçao","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":1,"unit":"dash"},"display_name":"Angostura bitters","notes":null},{"ingredient_id":"ING_ORANGE_BITTERS","quantity":{"amount":1,"unit":"dash"},"display_name":"Orange bitters","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a chilled cocktail glass. Garnish with a lime wheel or twist."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"Lime wheel or twist"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"citrus","bitter","sophisticated"}', 24, 165, 'medium', 60, '{}', '{"alcohol"}', '{"vegetarian","vegan","pescatarian","gluten_free","nut_free","dairy_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"spring","summer","autumn"}', '{"aperitivo","sophisticated","date_night"}', false, false, '{"modern-pegu-club","rangoon-ruby"}', 'Always use fresh lime juice. Both Angostura and orange bitters are essential - don''t skip either. Pierre Ferrand Dry Curaçao or Cointreau work best. Shake hard to properly chill and dilute. The classic ratio is roughly 8:3:3 (gin:curaçao:lime).', 'mid', 55, 'https://www.diffordsguide.com/cocktails/recipe/1617/pegu-club', 'Classic recipe from The Savoy Cocktail Book (1930) and Harry''s ABC of Mixing Cocktails (1922).', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 189. Penicillin


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('e9067482-b7fd-4317-b020-2dd1f928118c', 'penicillin', '625344938475629384756293847562938475629384', '{"en":"Penicillin"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","whisky","ginger","scotch"}', '{"en":"One of the most influential modern cocktails, the Penicillin combines blended Scotch, fresh lemon, honey-ginger syrup, and a smoky Islay whisky float. Created by Sam Ross, this drink is both medicinal and indulgent, with warming ginger spice, bright citrus, honey sweetness, and a distinctive smoky finish."}'::jsonb, '{"created_year":"2005","origin":{"city":"New York City","bar":"Milk & Honey","country":"USA"},"creator":{"name":"Sam Ross","profession":"bartender"},"story":{"en":"Sam Ross created the Penicillin in 2005 at the legendary Milk & Honey bar in New York City. Inspired by classic Gold Rush and Whiskey Sour formulas, Ross added ginger for spice and health benefits, and a smoky Islay Scotch float for aromatic complexity. The name references both the drink''s medicinal qualities (honey, ginger, lemon) and its \"curative\" properties after a long night. It became an instant modern classic and is now on cocktail menus worldwide, helping introduce American drinkers to Scotch whisky."},"named_after":{"en":"Named after penicillin, the antibiotic, referencing the cocktail''s medicinal ingredients (honey, ginger, lemon) traditionally used to treat colds."}}'::jsonb, '{"profile":["spicy","smoky","honey","citrus"],"description":{"en":"Complex, warming, and perfectly balanced. Blended Scotch provides a smooth whisky base, while honey-ginger syrup adds warming spice and floral sweetness. Fresh lemon contributes brightness, and the Islay Scotch float delivers an aromatic smoky finish that doesn''t overpower. Medicinal yet indulgent, with layers of flavor that evolve with each sip."},"first_impression":{"en":"Honey and ginger warmth hit first, followed by smoke and citrus"},"finish":{"en":"Long, smoky finish with lingering ginger spice and peat"},"balance":{"en":"Expertly balanced - sweet, sour, spicy, and smoky in perfect harmony"}}'::jsonb, '{"best_time":["evening","late_night","winter"],"occasions":["digestivo","date_night","contemplative_drinking","cold_weather"],"seasons":["autumn","winter","spring"],"food_pairings":{"en":"Excellent with smoked salmon, aged cheeses, roasted meats, or dark chocolate. Also pairs well with Scottish dishes, seafood, and rich, savory foods. Traditional pairing: oysters."},"ideal_for":{"en":"Perfect for whisky lovers exploring Scotch. Ideal for those who enjoy complex, layered cocktails with warming qualities. Great for cold weather and contemplative sipping. A must-try for any serious cocktail enthusiast."}}'::jsonb, '[{"ingredient_id":"ING_BLENDED_SCOTCH","quantity":{"amount":60,"unit":"ml"},"display_name":"Blended Scotch whisky","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_HONEY_GINGER_SYRUP","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Honey-ginger syrup","notes":null},{"ingredient_id":"ING_ISLAY_SCOTCH","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Islay Scotch (float)","notes":null}]'::jsonb, 'shake', '{"en":"Add blended Scotch, lemon juice, and honey-ginger syrup to a cocktail shaker filled with ice. Shake vigorously until well chilled. Strain into a rocks glass over fresh ice. Float Islay Scotch on top by gently pouring over the back of a barspoon. Garnish with candied ginger."}'::jsonb, 'Rocks glass', '{"en":"Candied ginger"}'::jsonb, 'cubes', 'on_the_rocks', '{"ING_BLENDED_SCOTCH"}', '{"spicy","smoky","honey","citrus"}', 22, 190, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance","honey_intolerance","ginger_intolerance"}', '{"vegetarian","gluten_free","dairy_free","nut_free"}', 2, '{"vegetarian","gluten-free","dairy-free"}', '{"autumn","winter","spring"}', '{"digestivo","date_night","contemplative_drinking","cold_weather"}', false, false, '{"mexican-penicillin","bourbon-penicillin","rye-penicillin"}', 'Honey-ginger syrup: simmer equal parts honey, water, and sliced ginger, then strain. Use smoky Islay like Laphroaig or Ardbeg for float. Float technique essential - pour gently over barspoon back. Fresh lemon juice only.', 'mid', 90, 'https://www.liquor.com/recipes/penicillin/', 'Created by Sam Ross at Milk & Honey, New York City, 2005. One of the most influential modern cocktails.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 190. Pickleback


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('825db886-95c8-450f-99d1-7efd73435ce9', 'pickleback', 'pickleback_shot_famous_whiskey_pickle_brine_chaser', '{"en":"Pickleback"}'::jsonb, 'famous', NULL, '{"shot","shooter","famous","whiskey","savory","pickle","chaser","brooklyn"}', '{"en":"A shot of whiskey followed immediately by a shot of pickle brine as a chaser. This unconventional combination became a Brooklyn bar phenomenon, with the pickle juice cutting through the whiskey burn and leaving a surprisingly clean finish."}'::jsonb, '{"created_year":"2006","origin":{"city":"Brooklyn","bar":"Bushwick Country Club","country":"USA"},"creator":{"name":"Reggie Cunningham","profession":"bartender"},"story":{"en":"The Pickleback was invented in 2006 by bartender Reggie Cunningham at the Bushwick Country Club in Brooklyn, New York. The story goes that a regular customer requested pickle juice to chase his whiskey shot, and the combination was so surprisingly effective that it caught on. The drink spread rapidly through Brooklyn''s bar scene and eventually became a nationwide phenomenon, spawning variations with different pickle brines and spirits."},"named_after":{"en":"Named \"Pickleback\" because the pickle brine acts as a \"back\" (chaser) for the whiskey shot."}}'::jsonb, '{"profile":["savory","salty","sour","briny"],"description":{"en":"The whiskey hits first with its characteristic burn and warmth. The pickle brine chaser immediately follows, cutting through the alcohol with tangy, salty, vinegar-forward flavor. The combination neutralizes the whiskey burn surprisingly well, leaving a clean, refreshing finish."},"first_impression":{"en":"Whiskey burn followed by tangy, salty pickle brine"},"finish":{"en":"Surprisingly clean and refreshing with lingering pickle flavor"},"balance":{"en":"The pickle brine perfectly neutralizes whiskey burn - oddly satisfying"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["party","casual","bar_hopping","dive_bar"],"seasons":["all_seasons"],"food_pairings":{"en":"Excellent with bar snacks, fried foods, burgers, and deli sandwiches. The savory nature complements salty, fatty foods perfectly."},"ideal_for":{"en":"Perfect for whiskey drinkers who want an easier chaser than beer or water. Great for those who love pickles and savory drinks. A fun novelty that actually works remarkably well."}}'::jsonb, '[{"ingredient_id":"ING_WHISKEY","quantity":{"amount":45,"unit":"ml"},"display_name":"Whiskey (bourbon or rye)","notes":null},{"ingredient_id":"ING_PICKLE_BRINE","quantity":{"amount":45,"unit":"ml"},"display_name":"Pickle Brine (dill pickle juice)","notes":null}]'::jsonb, 'pour', '{"en":"Pour whiskey into one shot glass and pickle brine into another. Drink the whiskey shot first, immediately followed by the pickle brine chaser. Do not pause between shots."}'::jsonb, 'Shot glass (two required)', '{"en":"Pickle spear (optional, on the side)"}'::jsonb, 'none', 'shot', '{"ING_WHISKEY"}', '{"savory","salty","sour","briny"}', 20, 100, 'easy', 20, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","vegetarian","gluten-free","dairy-free"}', '{"all-seasons"}', '{"party","casual","bar-hopping"}', false, false, '{"tequila-pickleback","mezcal-pickleback","vodka-pickleback","kimchi-back"}', 'Use dill pickle brine from good quality pickles - avoid sweet pickle juice. Some customers prefer spicy pickle brine. Serve both shots at the same time. Can substitute with other whiskeys or even tequila/mezcal. Very polarizing - some love it, others hate the idea.', 'low', 70, 'https://en.wikipedia.org/wiki/Pickleback', 'Brooklyn bar invention from 2006. Whiskey shot with pickle brine chaser.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 191. Piña Colada (Famous Variant)


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('03ce8a51-61a4-40cb-bad9-392cb4c1d2c2', 'pina-colada-famous', 'pina-colada-famous-variant-tiki-tropical-2025', '{"en":"Piña Colada (Famous Variant)"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","creamy","frozen","popular"}', '{"en":"The popular frozen variant of the classic Piña Colada, blended to a smooth, slushie-like consistency. This beach resort favorite combines rum, coconut cream, and pineapple juice into an indulgent frozen treat that epitomizes tropical vacation vibes."}'::jsonb, '{"created_year":"1970s","origin":{"city":"Various","bar":"Beach Resorts","country":"Puerto Rico / USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"While the original Piña Colada was created in Puerto Rico in the 1950s (claimed by both Ramón \"Monchito\" Marrero at Caribe Hilton and Ricardo García at Barrachina), the frozen blended version became the dominant style in the 1970s with the widespread availability of electric blenders. This frozen variant, immortalized in the 1979 Rupert Holmes song \"Escape (The Piña Colada Song),\" became the quintessential beach resort cocktail. The frozen version is now so ubiquitous that most people think of it as the \"original\" way to serve a Piña Colada. It became the official drink of Puerto Rico in 1978."},"named_after":{"en":"Spanish for \"strained pineapple,\" referring to the fresh pineapple juice that is a key ingredient. The name remained the same from the original recipe."}}'::jsonb, '{"profile":["creamy","tropical","sweet"],"description":{"en":"Incredibly creamy and smooth with pronounced coconut and pineapple flavors. The frozen texture makes it like a tropical milkshake - rich, indulgent, and refreshing. Sweet and luscious with the rum providing subtle warmth beneath the cold, creamy surface."},"first_impression":{"en":"Cold, creamy coconut and sweet pineapple with smooth frozen texture"},"finish":{"en":"Long, creamy finish with lingering coconut sweetness and gentle rum warmth"},"balance":{"en":"Sweet and creamy with good coconut-pineapple balance - the frozen format makes it more like a dessert than a cocktail"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["beach","pool_party","vacation","cruise","tropical_celebration"],"seasons":["summer","year_round"],"food_pairings":{"en":"Perfect as a dessert replacement or alongside tropical fruit platters, coconut shrimp, fish tacos, or light Caribbean fare. Also pairs well with grilled pineapple and coconut cake."},"ideal_for":{"en":"Perfect for beach vacations, pool parties, and cruise ships. Ideal for those who love creamy, dessert-like cocktails. The ultimate tropical indulgence and beach resort staple. Great for hot summer days."}}'::jsonb, '[{"ingredient_id":"ING_RUM_WHITE","quantity":{"amount":60,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_CREAM_OF_COCONUT","quantity":{"amount":45,"unit":"ml"},"display_name":"Cream of coconut","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":90,"unit":"ml"},"display_name":"Fresh pineapple juice","notes":null}]'::jsonb, 'blend', '{"en":"Add rum, cream of coconut, pineapple juice, and 1.5 cups of ice to a blender. Blend on high speed until smooth and creamy, with a consistency like a frozen milkshake. Pour into a hurricane glass or tiki mug. Garnish with pineapple wedge and maraschino cherry."}'::jsonb, 'Hurricane glass', '{"en":"Pineapple wedge and maraschino cherry"}'::jsonb, 'blended', 'frozen', '{"ING_RUM_WHITE"}', '{"creamy","tropical","sweet"}', 10, 320, 'easy', 90, '{"sulphites","tree_nuts"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","pescatarian","gluten_free","dairy_free"}', 0, '{"vegetarian","gluten-free"}', '{"summer","year_round"}', '{"beach","pool_party","vacation","cruise"}', false, false, '{"pina-colada-iba-official","virgin-pina-colada","strawberry-colada","lava-flow"}', 'This is the popular frozen version, different from IBA official recipe. Blend until smooth like a milkshake. Use Coco López or similar cream of coconut (NOT coconut milk). Fresh pineapple juice highly recommended. Official drink of Puerto Rico since 1978. Made famous by Rupert Holmes song. Very popular at beach resorts.', 'mid', 95, 'https://www.liquor.com/recipes/pina-colada/', 'Popular frozen variant. Official drink of Puerto Rico. Different from IBA official recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


