INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('db40ae2d-053a-4cbe-81bf-508eebbfd901', 'margarita-contemporary', 'margarita_iba_contemporary_2025', '{"en":"Margarita"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","classic","tequila","citrus","salty"}', '{"en":"The world''s most popular tequila cocktail, combining tequila, lime juice, and orange liqueur, typically served with a salt rim. Perfectly balanced between sweet, sour, and salty, making it an endlessly refreshing classic."}'::jsonb, '{"created_year":"1938","origin":{"city":"Tijuana","bar":"Rancho La Gloria","country":"Mexico"},"creator":{"name":"Carlos \"Danny\" Herrera","profession":"bartender"},"story":{"en":"The Margarita''s origins are disputed, with several bartenders claiming its creation. The most accepted story credits Carlos \"Danny\" Herrera, who created it in 1938 at his Rancho La Gloria restaurant near Tijuana for customer Margarita Henkel, a showgirl who was allergic to all spirits except tequila. Other claims include bartender Francisco \"Pancho\" Morales in 1942. Regardless of its true origin, the Margarita became the most popular tequila cocktail worldwide."},"named_after":{"en":"Most likely named after Margarita Henkel, though some say it''s Spanish for \"daisy\" (the cocktail family it belongs to)."}}'::jsonb, '{"profile":["citrus","sweet","salty","tart"],"description":{"en":"Bright, tangy, and refreshing. The salt rim enhances the citrus flavors, tequila provides earthy agave notes, Cointreau adds orange sweetness, and fresh lime brings tartness. A perfect balance of all taste elements."},"first_impression":{"en":"Salty-citrus burst from the rim, followed by tart lime"},"finish":{"en":"Clean, crisp finish with lingering agave and citrus notes"},"balance":{"en":"Perfectly balanced trinity of sweet, sour, and salty"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["casual","party","celebration","beach","bbq"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Excellent with Mexican cuisine, tacos, guacamole, ceviche, grilled fish, spicy foods, and chips with salsa. The acidity cuts through rich, fatty foods perfectly."},"ideal_for":{"en":"Perfect for tequila lovers and anyone who enjoys bright, citrus-forward cocktails. A crowd-pleasing favorite that works for any occasion."}}'::jsonb, '[{"ingredient_id":"ING_TEQUILA","quantity":{"amount":50,"unit":"ml"},"display_name":"Tequila 100% agave","notes":null},{"ingredient_id":"ING_COINTREAU","quantity":{"amount":20,"unit":"ml"},"display_name":"Cointreau","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_SALT","quantity":{"amount":1,"unit":"pinch"},"display_name":"Salt","notes":null}]'::jsonb, 'shake', '{"en":"Rub the rim of a chilled cocktail glass with lime wedge and dip in salt. Pour all ingredients into shaker with ice cubes. Shake well. Strain into the prepared glass. Garnish with a lime wheel."}'::jsonb, 'Cocktail glass (Margarita)', '{"en":"Salt rim and lime wheel"}'::jsonb, 'none', 'up', '{"ING_TEQUILA"}', '{"citrus","sweet","salty","tart"}', 27, 170, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer","autumn"}', '{"casual","party","celebration","beach","bbq"}', false, false, '{"frozen-margarita","strawberry-margarita","spicy-margarita","cadillac-margarita"}', 'Use 100% agave tequila for best results. Cointreau is preferred over cheaper triple sec. Fresh lime juice is essential - never use bottled. Salt rim is optional - ask customer preference. Can serve on the rocks or frozen.', 'mid', 100, 'https://iba-world.com/margarita/', 'IBA Official Recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 62. Mimosa


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('02f58ed2-b8d2-4a41-bfc7-db1947d123e9', 'mimosa', 'mimosa_iba_contemporary_classic', '{"en":"Mimosa"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","brunch","celebration","sparkling","simple"}', '{"en":"An elegant and refreshing champagne cocktail combining sparkling wine with fresh orange juice. The quintessential brunch cocktail, beloved for its simplicity and bright, effervescent character."}'::jsonb, '{"created_year":"1925","origin":{"city":"Paris","bar":"Hôtel Ritz Paris","country":"France"},"creator":{"name":"Frank Meier","profession":"bartender"},"story":{"en":"Created at the Hôtel Ritz Paris in 1925, allegedly by bartender Frank Meier. The drink was named after the mimosa flower due to its similar yellow-orange color. It became the signature drink of the Parisian elite and gained international fame as the ultimate brunch cocktail."},"named_after":{"en":"Named after the mimosa flower, which has a similar yellow-orange color to the cocktail."}}'::jsonb, '{"profile":["citrus","sparkling","refreshing"],"description":{"en":"Light, bright, and effervescent. Fresh orange juice provides natural sweetness and acidity, while champagne adds sophisticated bubbles and crisp dryness. Simple yet elegant."},"first_impression":{"en":"Bright citrus and lively bubbles"},"finish":{"en":"Clean, crisp finish with lingering orange notes"},"balance":{"en":"Perfect balance between champagne dryness and orange sweetness"}}'::jsonb, '{"best_time":["morning","afternoon"],"occasions":["brunch","celebration","wedding","holiday"],"seasons":["spring","summer","autumn","winter"],"food_pairings":{"en":"Perfect with brunch dishes like eggs Benedict, French toast, pastries, and fresh fruit. Also excellent with light appetizers and seafood."},"ideal_for":{"en":"Ideal for anyone who enjoys light, refreshing cocktails. The perfect choice for brunch celebrations, morning gatherings, or any occasion calling for elegance."}}'::jsonb, '[{"ingredient_id":"ING_CHAMPAGNE","quantity":{"amount":75,"unit":"ml"},"display_name":"Champagne (or sparkling wine)","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":75,"unit":"ml"},"display_name":"Fresh orange juice","notes":null}]'::jsonb, 'build', '{"en":"Pour orange juice into a champagne flute. Gently top with chilled champagne. Stir gently and briefly. Optionally garnish with an orange twist."}'::jsonb, 'Champagne flute', '{"en":"Orange twist (optional)"}'::jsonb, 'none', 'up', '{"ING_CHAMPAGNE"}', '{"citrus","sparkling","refreshing"}', 6, 120, 'easy', 30, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer","autumn","winter"}', '{"brunch","celebration","wedding","holiday"}', false, false, '{"grand-mimosa","poinsettia","bellini"}', 'Always use fresh-squeezed orange juice for best results. Champagne should be well-chilled. Pour orange juice first, then top with champagne. Traditional ratio is 1:1 but can be adjusted to taste.', 'mid', 95, 'https://iba-world.com/mimosa/', 'IBA Official Recipe. Historical information from Ritz Paris archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 63. Mint Julep


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('259affa3-adce-4502-9d16-085338100c27', 'mint-julep-contemporary', 'mint_julep_contemporary_iba_classic', '{"en":"Mint Julep"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","bourbon","mint","southern","kentucky-derby","refreshing"}', '{"en":"The iconic bourbon cocktail of the American South, traditionally served in a frosted silver cup. Fresh mint, bourbon, and crushed ice create a refreshing masterpiece - the official drink of the Kentucky Derby."}'::jsonb, '{"created_year":"1780","origin":{"city":"Virginia / Kentucky","bar":"Unknown","country":"USA"},"creator":{"name":"Unknown","profession":"unknown"},"story":{"en":"The Mint Julep dates back to the late 1700s in the American South. It became the signature drink of the Kentucky Derby in 1938. Traditionally served in a silver or pewter cup that frosts when filled with crushed ice. The drink is deeply rooted in Southern hospitality and Kentucky bourbon culture."},"named_after":{"en":"The word \"julep\" comes from the Arabic \"julab,\" meaning rosewater - referring to sweet drinks."}}'::jsonb, '{"profile":["minty","sweet","boozy"],"description":{"en":"Refreshingly minty with robust bourbon warmth. Fresh mint provides cooling aromatics, sugar adds sweetness, and bourbon delivers oak and caramel notes. The crushed ice makes it incredibly refreshing."},"first_impression":{"en":"Fresh mint aromatics with sweet bourbon"},"finish":{"en":"Long, warming finish with lingering mint and oak"},"balance":{"en":"Well-balanced between mint freshness, sugar sweetness, and bourbon warmth"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["kentucky_derby","southern_gathering","outdoor","special_event"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with Southern cuisine - fried chicken, barbecue, ham biscuits, and bourbon-infused desserts."},"ideal_for":{"en":"Perfect for bourbon lovers and anyone experiencing Southern hospitality. A must-have for Kentucky Derby parties and summer gatherings."}}'::jsonb, '[{"ingredient_id":"ING_BOURBON","quantity":{"amount":60,"unit":"ml"},"display_name":"Bourbon","notes":null},{"ingredient_id":"ING_FRESH_MINT","quantity":{"amount":4,"unit":"sprigs"},"display_name":"Fresh mint sprigs","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":10,"unit":"ml"},"display_name":"Simple syrup","notes":null},{"ingredient_id":"ING_WATER","quantity":{"amount":10,"unit":"ml"},"display_name":"Water","notes":null}]'::jsonb, 'muddle', '{"en":"In a Julep cup or rocks glass, gently muddle the mint with simple syrup and water. Fill the glass with crushed ice and add bourbon. Stir until the cup frosts. Top with more crushed ice to form a dome. Garnish with a large mint bouquet and serve with a straw."}'::jsonb, 'Julep cup (silver) or rocks glass', '{"en":"Mint bouquet (large bunch of mint)"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_BOURBON"}', '{"minty","sweet","boozy"}', 25, 180, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"kentucky_derby","southern_gathering","outdoor","special_event"}', false, false, '{"georgia-mint-julep","mojito","whiskey-smash"}', 'Traditionally served in a silver or pewter Julep cup. Muddle mint gently - don''t over-bruise. Use plenty of crushed ice and stir until cup frosts. The mint bouquet garnish should be large and aromatic. Serve with a short straw so the drinker''s nose is near the mint. Official drink of Kentucky Derby since 1938.', 'mid', 75, 'https://iba-world.com/mint-julep/', 'IBA Official Recipe. Official drink of the Kentucky Derby.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 64. Mojito


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('9605523d-7d35-4368-8876-678986e9f155', 'mojito', 'mojito_iba_contemporary_2025', '{"en":"Mojito"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","refreshing","mint","summer","classic"}', '{"en":"Cuba''s most famous cocktail, combining white rum, fresh mint, lime juice, sugar, and soda water. Refreshingly herbaceous and perfectly balanced between sweet, sour, and minty freshness. A timeless summer classic."}'::jsonb, '{"created_year":"1586","origin":{"city":"Havana","bar":"La Bodeguita del Medio","country":"Cuba"},"story":{"en":"The Mojito has roots dating back to the 16th century with \"El Draque,\" a medicinal drink made by pirates with aguardiente, sugar, lime, and mint. The modern Mojito evolved in the 1800s when rum replaced aguardiente. It gained international fame at La Bodeguita del Medio in Havana, frequented by Ernest Hemingway who famously said \"My mojito in La Bodeguita, my daiquiri in El Floridita.\""},"named_after":{"en":"The name \"mojito\" likely comes from \"mojo,\" a Cuban seasoning, or from \"mojadito\" meaning \"a little wet\" in Spanish."}}'::jsonb, '{"profile":["refreshing","minty","citrus","sweet"],"description":{"en":"Bright, fresh, and incredibly refreshing. Fresh mint provides aromatic coolness, lime adds tartness, rum brings smoothness, and soda water creates effervescence. A perfectly balanced summer refresher."},"first_impression":{"en":"Burst of fresh mint and lime, cool and invigorating"},"finish":{"en":"Clean, refreshing finish with lingering mint and citrus"},"balance":{"en":"Perfectly balanced between sweet sugar, tart lime, and fresh mint"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["casual","beach","party","bbq","brunch"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with Cuban cuisine, grilled seafood, ceviche, light salads, tropical fruits, and spicy foods. The mint and lime cut through rich flavors beautifully."},"ideal_for":{"en":"Perfect for anyone who loves fresh, herbaceous cocktails. Ideal for hot weather and outdoor gatherings. A universally loved crowd-pleaser."}}'::jsonb, '[{"ingredient_id":"ING_RUM_WHITE","quantity":{"amount":45,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":20,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_MINT","quantity":{"amount":6,"unit":"leaves"},"display_name":"Fresh mint leaves","notes":null},{"ingredient_id":"ING_SUGAR","quantity":{"amount":2,"unit":"tsp"},"display_name":"White sugar","notes":null},{"ingredient_id":"ING_SODA_WATER","quantity":{"amount":1,"unit":"splash"},"display_name":"Soda water","notes":null}]'::jsonb, 'muddle', '{"en":"Muddle mint leaves with sugar and lime juice in a highball glass. Fill the glass with ice cubes. Add rum and top with soda water. Stir gently to combine. Garnish with mint sprig and lime wheel."}'::jsonb, 'Highball glass', '{"en":"Mint sprig and lime wheel"}'::jsonb, 'cubes', 'built', '{"ING_RUM_WHITE"}', '{"refreshing","minty","citrus","sweet"}', 10, 150, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"casual","beach","party","bbq","brunch"}', false, false, '{"virgin-mojito","strawberry-mojito","blackberry-mojito","coconut-mojito"}', 'Gently muddle mint - don''t over-muddle or it becomes bitter. Use fresh mint only, never dried. Build in serving glass to preserve carbonation. Can use simple syrup instead of sugar for easier dissolution.', 'low', 98, 'https://iba-world.com/mojito/', 'IBA Official Recipe. Historical information from Cuban cocktail archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 65. Moscow Mule


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('838acf34-d9c3-4d0e-af7c-7d19283a7006', 'moscow-mule', 'moscow_mule_iba_contemporary_classic', '{"en":"Moscow Mule"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","refreshing","spicy","vodka","iconic","copper-mug"}', '{"en":"An iconic vodka cocktail served in a distinctive copper mug. Vodka, spicy ginger beer, and fresh lime create a refreshing, zingy drink that launched vodka''s popularity in America."}'::jsonb, '{"created_year":"1941","origin":{"city":"Los Angeles","bar":"Cock ''n'' Bull","country":"USA"},"creator":{"name":"John Martin & Jack Morgan","profession":"bartenders/businessmen"},"story":{"en":"Created around 1941 at the Cock ''n'' Bull pub in Los Angeles by John Martin (Smirnoff vodka distributor) and Jack Morgan (bar owner with excess ginger beer). They added lime and served it in copper mugs to create a marketing sensation. The drink single-handedly launched vodka''s popularity in America and created the copper mug tradition."},"named_after":{"en":"Named \"Moscow Mule\" - \"Moscow\" for vodka''s Russian origins and \"Mule\" for ginger beer''s kick."}}'::jsonb, '{"profile":["spicy","citrus","refreshing"],"description":{"en":"Crisp, refreshing, and spicy. Ginger beer provides warming spice and effervescence, lime adds bright citrus, and vodka keeps it clean. The copper mug keeps it ice-cold. Invigorating and thirst-quenching."},"first_impression":{"en":"Bright lime and spicy ginger with clean vodka"},"finish":{"en":"Clean, spicy finish with lingering ginger warmth"},"balance":{"en":"Well-balanced between ginger spice, lime tartness, and vodka smoothness"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["casual","outdoor","summer_gathering","brunch"],"seasons":["spring","summer","autumn","winter"],"food_pairings":{"en":"Pairs well with spicy foods, Asian cuisine, burgers, barbecue, and appetizers. The ginger complements bold flavors."},"ideal_for":{"en":"Perfect for anyone seeking a refreshing, easy-drinking cocktail. Great for vodka lovers and those who enjoy ginger''s spicy kick."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":45,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_GINGER_BEER","quantity":{"amount":120,"unit":"ml"},"display_name":"Ginger beer","notes":null}]'::jsonb, 'build', '{"en":"Combine vodka and lime juice in a copper mug filled with ice. Top with ginger beer. Stir gently. Garnish with a lime wedge and fresh mint sprig."}'::jsonb, 'Copper mug (or highball glass)', '{"en":"Lime wedge and fresh mint sprig"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA"}', '{"spicy","citrus","refreshing"}', 10, 180, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 2, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer","autumn","winter"}', '{"casual","outdoor","summer_gathering","brunch"}', false, false, '{"kentucky-mule","mexican-mule","london-mule"}', 'Traditionally served in a copper mug which keeps the drink ice-cold and adds to the experience. Use quality ginger beer (not ginger ale). Fresh lime juice is essential. The Kentucky Mule uses bourbon, Mexican Mule uses tequila.', 'low', 90, 'https://iba-world.com/moscow-mule/', 'IBA Official Recipe. The drink that made vodka popular in America.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 66. Piña Colada


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('1c540b10-8d5f-47ab-8272-39359478daf4', 'pina-colada', 'pina_colada_iba_contemporary_classic', '{"en":"Piña Colada"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","tropical","creamy","summer","beach","iconic"}', '{"en":"The national drink of Puerto Rico - a luscious blend of rum, coconut cream, and pineapple juice. Creamy, tropical, and utterly refreshing, it''s the quintessential beach cocktail that tastes like paradise."}'::jsonb, '{"created_year":"1954","origin":{"city":"San Juan","bar":"Caribe Hilton Hotel","country":"Puerto Rico"},"creator":{"name":"Ramón \"Monchito\" Marrero","profession":"bartender"},"story":{"en":"Created by bartender Ramón \"Monchito\" Marrero at the Caribe Hilton Hotel in San Juan, Puerto Rico in 1954. Marrero spent three months perfecting the recipe to capture the essence of Puerto Rico. The drink became the hotel''s signature cocktail and later Puerto Rico''s national drink. The name means \"strained pineapple\" in Spanish."},"named_after":{"en":"Spanish for \"strained pineapple,\" referring to the fresh pineapple juice used in the cocktail."}}'::jsonb, '{"profile":["tropical","creamy","sweet"],"description":{"en":"Rich, creamy, and intensely tropical. Coconut cream provides luxurious texture while pineapple adds bright, tangy sweetness. White rum ties it together with subtle warmth. Like a vacation in a glass."},"first_impression":{"en":"Sweet coconut and bright pineapple with creamy texture"},"finish":{"en":"Long, tropical finish with lingering coconut sweetness"},"balance":{"en":"Well-balanced between creamy richness and fruity brightness"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["beach","pool_party","tropical_party","vacation"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with Caribbean cuisine, grilled seafood, jerk chicken, tropical fruits, and coconut-based desserts."},"ideal_for":{"en":"Ideal for anyone seeking a tropical escape. Perfect for beach vacations, poolside relaxation, or bringing summer vibes to any occasion."}}'::jsonb, '[{"ingredient_id":"ING_WHITE_RUM","quantity":{"amount":50,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_COCONUT_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Coconut cream","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":50,"unit":"ml"},"display_name":"Fresh pineapple juice","notes":null}]'::jsonb, 'blend', '{"en":"Blend all ingredients with ice in an electric blender at high speed. Pour into a large goblet or Hurricane glass. Garnish with a pineapple wedge and maraschino cherry."}'::jsonb, 'Hurricane glass', '{"en":"Pineapple wedge and maraschino cherry"}'::jsonb, 'blended', 'frozen', '{"ING_WHITE_RUM"}', '{"tropical","creamy","sweet"}', 10, 300, 'easy', 90, '{"sulphites","tree_nuts"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"beach","pool_party","tropical_party","vacation"}', false, false, '{"miami-vice","chi-chi","amaretto-colada"}', 'Blend with plenty of ice for proper frozen consistency. Use Coco López or similar coconut cream, not coconut milk. Fresh pineapple juice is essential. Can be made in batches for parties. The Miami Vice combines with frozen Strawberry Daiquiri.', 'mid', 95, 'https://iba-world.com/pina-colada/', 'IBA Official Recipe. National drink of Puerto Rico since 1978.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 67. Pisco Sour


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('9284d9cf-7b71-47a4-abcd-790660498628', 'pisco-sour', 'pisco_sour_iba_contemporary_2025', '{"en":"Pisco Sour"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","peruvian","sour","classic","foamy"}', '{"en":"Peru''s national cocktail, combining pisco (grape brandy) with lime juice, simple syrup, egg white, and Angostura bitters. The egg white creates a luxurious foam cap, making this sour cocktail exceptionally smooth and elegant."}'::jsonb, '{"created_year":"1920","origin":{"city":"Lima","bar":"Morris'' Bar","country":"Peru"},"creator":{"name":"Victor Vaughen Morris","profession":"bartender"},"story":{"en":"Created by American bartender Victor Vaughen Morris in the early 1920s at his bar in Lima, Peru. Morris adapted the classic whiskey sour recipe using pisco, Peru''s national spirit made from grapes. The drink became Peru''s national cocktail and is celebrated annually on the first Saturday of February as \"Pisco Sour Day.\" Chile also claims the Pisco Sour, leading to an ongoing friendly rivalry between the two countries."},"named_after":{"en":"Named after pisco, the grape brandy spirit that forms its base."}}'::jsonb, '{"profile":["sour","citrus","smooth","aromatic"],"description":{"en":"Silky smooth with a perfect balance of tart and sweet. Fresh lime provides bright acidity, pisco brings floral, fruity grape notes, and egg white creates velvety texture. Angostura bitters add aromatic complexity to the foam."},"first_impression":{"en":"Aromatic foam with bitters, followed by tart lime"},"finish":{"en":"Clean, crisp finish with lingering citrus and grape notes"},"balance":{"en":"Perfectly balanced sour cocktail with luxurious texture"}}'::jsonb, '{"best_time":["aperitivo","evening"],"occasions":["aperitivo","celebration","date_night"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Excellent with Peruvian ceviche, seafood, grilled fish, empanadas, and light appetizers. The acidity complements seafood beautifully."},"ideal_for":{"en":"Perfect for sour cocktail lovers and those who appreciate elegant, classic drinks. Great for special occasions and introducing people to pisco."}}'::jsonb, '[{"ingredient_id":"ING_PISCO","quantity":{"amount":45,"unit":"ml"},"display_name":"Pisco","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":20,"unit":"ml"},"display_name":"Simple syrup","notes":null},{"ingredient_id":"ING_EGG_WHITE","quantity":{"amount":1,"unit":"whole"},"display_name":"Egg white","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":3,"unit":"dash"},"display_name":"Angostura bitters","notes":null}]'::jsonb, 'shake', '{"en":"Add pisco, lime juice, simple syrup, and egg white to shaker. Dry shake (without ice) vigorously for 15 seconds. Add ice and shake again until well chilled. Strain into a chilled cocktail glass. Drop 3 dashes of Angostura bitters on foam and garnish."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"3 drops Angostura bitters on foam"}'::jsonb, 'none', 'up', '{"ING_PISCO"}', '{"sour","citrus","smooth","aromatic"}', 15, 180, 'medium', 120, '{"eggs","sulphites"}', '{"alcohol","eggs","sulphites_intolerance"}', '{"pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"gluten-free","dairy-free"}', '{"spring","summer","autumn"}', '{"aperitivo","celebration","date_night"}', false, false, '{"chilean-pisco-sour","pisco-punch"}', 'Dry shake first (no ice) to emulsify egg white properly. Then add ice and shake again. Use fresh egg white - pasteurized works but creates less foam. Drop bitters precisely on foam for visual effect.', 'mid', 75, 'https://iba-world.com/pisco-sour/', 'IBA Official Recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 68. Rabo-de-Galo


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('9ace6646-50db-4c22-85e0-3b607daba9b9', 'rabo-de-galo', 'rabo_de_galo_iba_contemporary_2025', '{"en":"Rabo-de-Galo"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","brazilian","simple","strong"}', '{"en":"Brazil''s classic cachaça cocktail, combining cachaça with sweet vermouth and a touch of Cynar. Simple yet sophisticated, this drink showcases the grassy, vegetal notes of cachaça balanced with Italian bitters."}'::jsonb, '{"created_year":"1940","origin":{"city":"São Paulo","country":"Brazil"},"story":{"en":"The Rabo-de-Galo (meaning \"rooster''s tail\" in Portuguese) is a traditional Brazilian cocktail that emerged in São Paulo bars in the 1940s. It represents Brazil''s embrace of its national spirit cachaça mixed with European liqueurs. The drink gained official recognition when added to the IBA Contemporary Classics list, bringing Brazilian cocktail culture to international bartending."},"named_after":{"en":"Named \"Rabo-de-Galo\" (rooster''s tail) possibly referring to the drink''s appearance or the colorful nature of Brazilian cocktail culture."}}'::jsonb, '{"profile":["herbal","sweet","bitter"],"description":{"en":"Complex and balanced. Cachaça brings grassy, vegetal notes, sweet vermouth adds richness and spice, while Cynar contributes artichoke bitterness. A sophisticated sip showcasing Brazilian spirit culture."},"first_impression":{"en":"Sweet vermouth and herbal notes, followed by cachaça grassiness"},"finish":{"en":"Lingering bitter-sweet finish with artichoke and spice notes"},"balance":{"en":"Well-balanced between sweet vermouth and bitter Cynar"}}'::jsonb, '{"best_time":["aperitivo","evening"],"occasions":["aperitivo","digestivo","date_night"],"seasons":["autumn","winter","spring"],"food_pairings":{"en":"Excellent as an aperitivo with Brazilian snacks, coxinha, pão de queijo, olives, or charcuterie. The bitter notes stimulate appetite."},"ideal_for":{"en":"Perfect for those who appreciate bitter, complex cocktails and want to explore Brazilian spirits. Great for aperitivo hour."}}'::jsonb, '[{"ingredient_id":"ING_CACHACA","quantity":{"amount":40,"unit":"ml"},"display_name":"Cachaça","notes":null},{"ingredient_id":"ING_VERMOUTH_SWEET","quantity":{"amount":20,"unit":"ml"},"display_name":"Sweet vermouth","notes":null},{"ingredient_id":"ING_CYNAR","quantity":{"amount":10,"unit":"ml"},"display_name":"Cynar","notes":null}]'::jsonb, 'stir', '{"en":"Pour all ingredients into a mixing glass with ice. Stir well. Strain into a chilled cocktail glass. Garnish with an orange twist."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"Orange twist"}'::jsonb, 'none', 'up', '{"ING_CACHACA"}', '{"herbal","sweet","bitter"}', 25, 140, 'medium', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring"}', '{"aperitivo","digestivo","date_night"}', false, false, '{"rabo-de-galo-aged"}', 'Stir, don''t shake - maintains clarity. Use quality cachaça (aged is nice but not required). Cynar is essential - don''t substitute. Express orange oils over drink before garnishing.', 'mid', 45, 'https://iba-world.com/rabo-de-galo/', 'IBA Official Recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 69. Sea Breeze


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('f3da168c-9548-4e17-8629-54dd1a8b3110', 'sea-breeze', 'sea_breeze_iba_contemporary_classic', '{"en":"Sea Breeze"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","refreshing","fruity","summer","beach"}', '{"en":"A refreshing vodka-based cocktail combining cranberry and grapefruit juices. Light, fruity, and perfectly balanced, it''s the ideal beach-side companion with its beautiful pink hue."}'::jsonb, '{"created_year":"1920","origin":{"city":"Unknown","bar":"Unknown","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Sea Breeze evolved from earlier gin-based recipes in the 1920s-30s. The modern vodka version with cranberry and grapefruit juice became popular in the 1970s, particularly during the cranberry juice marketing boom by Ocean Spray."},"named_after":{"en":"Named for its refreshing, ocean-breeze quality - perfect for seaside enjoyment."}}'::jsonb, '{"profile":["fruity","tart","refreshing"],"description":{"en":"Bright and refreshing with a perfect balance of sweet and tart. Cranberry provides tartness while grapefruit adds citrusy bitterness. Vodka keeps it clean and crisp."},"first_impression":{"en":"Tart cranberry and citrus grapefruit with clean vodka"},"finish":{"en":"Clean, refreshing finish with lingering fruit notes"},"balance":{"en":"Well-balanced between tart cranberry and bitter grapefruit"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["beach","pool_party","summer_gathering","casual"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with seafood, grilled fish, summer salads, and light appetizers. Also pairs well with beach snacks and barbecue."},"ideal_for":{"en":"Ideal for anyone seeking a light, refreshing cocktail. Perfect for beach days, poolside relaxation, or any summer occasion."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":40,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_CRANBERRY_JUICE","quantity":{"amount":120,"unit":"ml"},"display_name":"Cranberry juice","notes":null},{"ingredient_id":"ING_GRAPEFRUIT_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Grapefruit juice","notes":null}]'::jsonb, 'build', '{"en":"Build all ingredients in a highball glass filled with ice. Stir gently. Garnish with a lime wedge."}'::jsonb, 'Highball glass', '{"en":"Lime wedge"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA"}', '{"fruity","tart","refreshing"}', 8, 180, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"beach","pool_party","summer_gathering","casual"}', false, false, '{"bay-breeze","cape-codder","madras"}', 'Use fresh-squeezed grapefruit juice when possible. The Bay Breeze variation uses pineapple instead of grapefruit. Build in glass - no shaking needed.', 'low', 75, 'https://iba-world.com/sea-breeze/', 'IBA Official Recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 70. Sex on the Beach


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('f5be1793-da74-46f9-98d4-009bcdf48d9b', 'sex-on-the-beach', 'sex_on_the_beach_iba_contemporary_classic', '{"en":"Sex on the Beach"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","fruity","sweet","beach","party","fun"}', '{"en":"A playfully named fruity cocktail combining vodka, peach schnapps, cranberry, and orange juice. Sweet, easy-drinking, and perfect for beach parties - this is the ultimate fun-in-the-sun cocktail."}'::jsonb, '{"created_year":"1987","origin":{"city":"Fort Lauderdale","bar":"Confetti''s Bar","country":"USA"},"creator":{"name":"Ted Pizio","profession":"bartender"},"story":{"en":"Created by bartender Ted Pizio at Confetti''s Bar in Fort Lauderdale, Florida in 1987. The provocative name was designed to attract attention during spring break season. The drink became wildly popular at beach bars and spread internationally, becoming synonymous with beach party culture."},"named_after":{"en":"Provocatively named to attract spring break crowds in Fort Lauderdale beach bars."}}'::jsonb, '{"profile":["fruity","sweet","refreshing"],"description":{"en":"Sweet, fruity, and tropical. Peach schnapps provides peachy sweetness, cranberry adds tartness and color, orange juice brings citrus brightness, and vodka keeps it smooth. Easy-drinking and refreshing."},"first_impression":{"en":"Sweet peach and orange with tart cranberry"},"finish":{"en":"Clean, fruity finish with lingering peach notes"},"balance":{"en":"Well-balanced between sweet peach and tart cranberry"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["beach","pool_party","spring_break","casual_party"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with beach snacks, barbecue, grilled seafood, tropical fruits, and party appetizers."},"ideal_for":{"en":"Perfect for beach parties, pool gatherings, and anyone seeking a fun, easy-drinking cocktail. Great for crowds and party atmospheres."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":40,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_PEACH_SCHNAPPS","quantity":{"amount":20,"unit":"ml"},"display_name":"Peach schnapps","notes":null},{"ingredient_id":"ING_CRANBERRY_JUICE","quantity":{"amount":40,"unit":"ml"},"display_name":"Cranberry juice","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":40,"unit":"ml"},"display_name":"Orange juice","notes":null}]'::jsonb, 'build', '{"en":"Build all ingredients in a highball glass filled with ice. Stir gently. Garnish with an orange slice and cherry."}'::jsonb, 'Highball glass', '{"en":"Orange slice and maraschino cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA"}', '{"fruity","sweet","refreshing"}', 12, 210, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"beach","pool_party","spring_break","casual_party"}', false, false, '{"woo-woo","fuzzy-navel","hairy-navel"}', 'Very popular party drink. Can be made in large batches. The Woo Woo is similar but without orange juice. Easy to customize ratios based on guest preferences. Some variations add pineapple juice.', 'low', 85, 'https://iba-world.com/sex-on-the-beach/', 'IBA Official Recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


