INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('653dae60-f792-4713-bbbf-aaa1a1cb5d24', 'gold-rush', 'b4c3d2e1f0a9182736455463728192021222324252', '{"en":"Gold Rush"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","whiskey","sour","honey"}', '{"en":"A modern whiskey sour that replaces simple syrup with honey syrup, creating a richer, more complex flavor profile. The Gold Rush is essentially a Whiskey Sour meets Bee''s Knees, combining bourbon''s warmth with honey''s floral sweetness and lemon''s bright acidity."}'::jsonb, '{"created_year":"2001","origin":{"city":"New York City","bar":"Milk & Honey","country":"USA"},"creator":{"name":"T.J. Siegel","profession":"bartender"},"story":{"en":"The Gold Rush was created by T.J. Siegel at the legendary Milk & Honey bar in New York City around 2001. Siegel wanted to create a bourbon cocktail that showcased the spirit''s natural sweetness without being too sweet. By using honey syrup instead of simple syrup, he created a drink with more depth and complexity. The name references the California Gold Rush, playing on the golden color of both bourbon and honey. The drink became an instant modern classic and remains one of the most popular contemporary cocktails."},"named_after":{"en":"Named after the California Gold Rush of the mid-1800s, referencing the golden color of bourbon and honey."}}'::jsonb, '{"profile":["honey","citrus","bourbon","balanced"],"description":{"en":"Rich, smooth, and perfectly balanced. Bourbon provides vanilla, oak, and caramel notes that harmonize beautifully with honey''s floral sweetness. Fresh lemon adds brightness and cuts through the richness. The honey syrup creates a silkier texture than simple syrup, making this more luxurious than a standard whiskey sour."},"first_impression":{"en":"Honey and lemon hit first, followed by warm bourbon notes"},"finish":{"en":"Medium-long finish with lingering honey, vanilla, and oak"},"balance":{"en":"Expertly balanced - honey sweetness perfectly matches lemon tartness"}}'::jsonb, '{"best_time":["evening","afternoon","cocktail_hour"],"occasions":["aperitivo","date_night","celebration","casual"],"seasons":["autumn","winter","spring"],"food_pairings":{"en":"Excellent with barbecue, grilled meats, aged cheeses, or charcuterie. Also pairs well with roasted nuts, honey-glazed dishes, and caramelized desserts."},"ideal_for":{"en":"Perfect for bourbon lovers who enjoy balanced sours. Ideal for those who find traditional whiskey sours too sharp or simple syrup too plain. Great gateway cocktail for whiskey newcomers."}}'::jsonb, '[{"ingredient_id":"ING_BOURBON","quantity":{"amount":60,"unit":"ml"},"display_name":"Bourbon whiskey","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_HONEY_SYRUP","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Honey syrup (3:1)","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well chilled. Strain into a rocks glass over fresh ice or serve up in a coupe glass. Garnish with a lemon twist."}'::jsonb, 'Rocks glass', '{"en":"Lemon twist"}'::jsonb, 'cubes', 'on_the_rocks', '{"ING_BOURBON"}', '{"honey","citrus","bourbon","balanced"}', 20, 180, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance","honey_intolerance"}', '{"vegetarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","gluten-free","dairy-free"}', '{"autumn","winter","spring"}', '{"aperitivo","date_night","celebration","casual"}', false, false, '{"rye-gold-rush","mezcal-gold-rush","smoky-gold-rush"}', 'Honey syrup is 3 parts honey to 1 part hot water, cooled. Use fresh lemon juice only. Can serve up in coupe or on rocks - both work well. Quality honey matters - use local, floral honey for best results.', 'mid', 90, 'https://www.liquor.com/recipes/gold-rush/', 'Created by T.J. Siegel at Milk & Honey, New York City, circa 2001.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 153. Golden Cadillac


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('8432cb47-9ad0-4d01-8752-af6313a32861', 'golden-cadillac', 'golden_cadillac_galliano_cacao_cream', '{"en":"Golden Cadillac"}'::jsonb, 'famous', NULL, '{"creamy","dessert","famous","vintage","chocolate"}', '{"en":"A luxurious, golden-hued dessert cocktail combining Galliano, white crème de cacao, and cream. This vintage classic from the 1950s delivers a unique blend of herbal vanilla notes from Galliano with sweet chocolate cream."}'::jsonb, '{"created_year":"1952","origin":{"city":"El Dorado","bar":"Poor Red''s BBQ","country":"USA"},"creator":{"name":"Frank Klein","profession":"bartender"},"story":{"en":"The Golden Cadillac was created in 1952 by bartender Frank Klein at Poor Red''s BBQ in El Dorado, California. According to legend, a couple came into the bar after purchasing a new Cadillac and asked Klein to create a drink to celebrate. Klein mixed Galliano, white crème de cacao, and cream, creating a golden cocktail that matched the color of luxury Cadillacs of that era. The drink became a sensation in the 1950s-60s during the golden age of creamy cocktails."},"named_after":{"en":"Named after the luxury Cadillac automobile, referencing both the golden color and the luxurious, premium nature of the drink."}}'::jsonb, '{"profile":["creamy","sweet","herbal","vanilla"],"description":{"en":"Sweet and creamy with distinctive herbal-vanilla notes from Galliano balanced by white chocolate sweetness. Smooth and indulgent with a unique flavor profile that sets it apart from other creamy cocktails."},"first_impression":{"en":"Creamy vanilla sweetness with immediate herbal complexity from Galliano"},"finish":{"en":"Smooth, lingering vanilla and anise notes with creamy texture"},"balance":{"en":"Well-balanced between herbal complexity and creamy sweetness - more interesting than simple chocolate cream drinks"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["digestivo","retro_party","celebration","nightcap"],"seasons":["autumn","winter","all_seasons"],"food_pairings":{"en":"Pairs beautifully with vanilla desserts, panna cotta, white chocolate mousse, or tiramisu. Also complements almond biscotti and shortbread cookies."},"ideal_for":{"en":"Perfect for those who enjoy vintage cocktails and appreciate Galliano''s unique flavor. Ideal for retro-themed events and anyone seeking a sophisticated dessert drink with historical charm. Great for Cadillac owners!"}}'::jsonb, '[{"ingredient_id":"ING_GALLIANO","quantity":{"amount":30,"unit":"ml"},"display_name":"Galliano","notes":null},{"ingredient_id":"ING_CREME_DE_CACAO_WHITE","quantity":{"amount":30,"unit":"ml"},"display_name":"White crème de cacao","notes":null},{"ingredient_id":"ING_HEAVY_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Heavy cream","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously for 10-15 seconds until well-chilled and frothy. Strain into a chilled coupe or champagne saucer. The drink should have a beautiful golden hue."}'::jsonb, 'Coupe (or Champagne saucer)', '{"en":"None (golden color is the visual appeal)"}'::jsonb, 'none', 'up', '{"ING_GALLIANO"}', '{"creamy","sweet","herbal","vanilla"}', 15, 260, 'easy', 60, '{"milk"}', '{"lactose","alcohol"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 0, '{"vegetarian","gluten-free"}', '{"autumn","winter","all-seasons"}', '{"digestivo","celebration","nightcap"}', false, false, '{"golden-dream","yellow-cadillac","pink-cadillac"}', 'Classic 1950s cocktail. Galliano is essential for authentic flavor - do not substitute. Some modern recipes add orange juice, but original is just the three ingredients. Can be served frozen for a more dessert-like experience. The golden color should be prominent.', 'mid', 45, 'https://www.diffordsguide.com/cocktails/recipe/1313/golden-cadillac', 'Classic 1950s dessert cocktail from California.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 154. Goombay Smash


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('3b81a2b0-55bb-4fd7-8085-078b51bb839b', 'goombay-smash', 'goombay-smash-tiki-tropical-famous-2025', '{"en":"Goombay Smash"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","bahamas","fruity","signature"}', '{"en":"The signature cocktail of the Bahamas, combining coconut rum with apricot brandy and tropical fruit juices. The Goombay Smash is a potent yet refreshing blend that captures the spirit of island celebration and Caribbean culture."}'::jsonb, '{"created_year":"1960s","origin":{"city":"Green Turtle Cay","bar":"Miss Emily''s Blue Bee Bar","country":"Bahamas"},"creator":{"name":"Emily Cooper","profession":"bartender"},"story":{"en":"The Goombay Smash was created by Miss Emily Cooper at her legendary Blue Bee Bar on Green Turtle Cay in the Abaco Islands, Bahamas, during the 1960s. The drink became so popular that it''s now considered the national cocktail of the Bahamas. \"Goombay\" refers to a style of Bahamian music and dance with African roots, celebrating the islands'' cultural heritage. Miss Emily''s original recipe was kept secret for years, and she famously made each drink herself, refusing to let anyone else prepare it. The cocktail gained international fame and is now served throughout the Caribbean, though purists insist the best version is still made at the original Blue Bee Bar."},"named_after":{"en":"Named after \"Goombay,\" a traditional Bahamian music and dance style with African origins, celebrating the islands'' rich cultural heritage and festive spirit."}}'::jsonb, '{"profile":["fruity","tropical","sweet"],"description":{"en":"Complex and tropical with layers of coconut, apricot, pineapple, and citrus. The coconut rum provides a sweet, tropical base while apricot brandy adds depth and sophistication. Dangerously smooth and deceptively strong."},"first_impression":{"en":"Sweet coconut and tropical fruit burst with subtle apricot complexity"},"finish":{"en":"Long, warming finish with lingering coconut, apricot, and rum notes"},"balance":{"en":"Well-balanced sweetness with tropical complexity - the apricot brandy prevents it from being one-dimensional"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["beach","celebration","vacation","caribbean_theme","special_occasion"],"seasons":["summer","year_round"],"food_pairings":{"en":"Perfect with Bahamian conch fritters, grilled lobster, coconut shrimp, jerk chicken, or tropical fruit platters. Also pairs well with spicy Caribbean dishes as the sweetness balances heat."},"ideal_for":{"en":"Perfect for Caribbean vacations, island celebrations, and tropical beach parties. Ideal for those seeking the authentic taste of the Bahamas. A must-try for tiki cocktail enthusiasts and rum lovers."}}'::jsonb, '[{"ingredient_id":"ING_RUM_COCONUT","quantity":{"amount":45,"unit":"ml"},"display_name":"Coconut rum","notes":null},{"ingredient_id":"ING_APRICOT_BRANDY","quantity":{"amount":15,"unit":"ml"},"display_name":"Apricot brandy","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":60,"unit":"ml"},"display_name":"Pineapple juice","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":10,"unit":"ml"},"display_name":"Simple syrup","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well chilled. Strain into a hurricane glass filled with fresh ice. Garnish with pineapple wedge and cherry."}'::jsonb, 'Hurricane glass', '{"en":"Pineapple wedge and maraschino cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_RUM_COCONUT"}', '{"fruity","tropical","sweet"}', 14, 240, 'easy', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"summer","year_round"}', '{"beach","celebration","vacation","caribbean_theme"}', false, false, '{"frozen-goombay-smash","virgin-goombay-smash"}', 'National cocktail of the Bahamas. Original recipe from Miss Emily''s Blue Bee Bar. The apricot brandy is key to authentic flavor. Can be served frozen. Deceptively strong - warn guests. Some recipes include rum floater on top.', 'mid', 70, 'https://www.liquor.com/recipes/goombay-smash/', 'National cocktail of Bahamas. Created by Miss Emily Cooper at Blue Bee Bar.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 155. Greyhound


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('71ec1dda-008d-454c-b4a8-6bda3b28d6e0', 'greyhound', 'e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7', '{"en":"Greyhound"}'::jsonb, 'famous', NULL, '{"highball","long-drink","famous","refreshing","citrus","vodka"}', '{"en":"A refreshing and simple highball cocktail combining vodka with fresh grapefruit juice. The Greyhound is a classic two-ingredient drink that highlights the bitter-sweet flavor of grapefruit, perfect for brunch or warm afternoons."}'::jsonb, '{"created_year":"1930","origin":{"city":"United States","country":"USA"},"story":{"en":"The Greyhound emerged in the 1930s and became particularly popular in the post-war era. Its simple combination of vodka and grapefruit juice made it accessible and refreshing. The drink gained further popularity when the salted rim version, known as the Salty Dog, was created. The name likely refers to the Greyhound bus line, which was expanding across America during this period."},"named_after":{"en":"Named after the Greyhound bus line, which was a popular mode of transportation in mid-20th century America."}}'::jsonb, '{"profile":["citrus","bitter","refreshing"],"description":{"en":"Clean and crisp with bright grapefruit tartness balanced by the neutral vodka base. The natural bitterness of grapefruit provides depth and complexity to this seemingly simple drink."},"first_impression":{"en":"Bright, tangy grapefruit with a clean vodka backbone"},"finish":{"en":"Crisp, slightly bitter citrus finish with lingering grapefruit notes"},"balance":{"en":"Well-balanced between sweet and bitter, with the vodka providing structure without overwhelming the grapefruit"}}'::jsonb, '{"best_time":["afternoon","brunch","daytime"],"occasions":["casual","brunch","poolside","summer_party"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with brunch dishes, smoked salmon, seafood salads, and light appetizers. Pairs well with eggs benedict and avocado toast."},"ideal_for":{"en":"Perfect for those who enjoy light, refreshing cocktails with a citrus edge. Great for brunch enthusiasts or anyone looking for a simple, sophisticated drink without too much sweetness."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":45,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_GRAPEFRUIT_JUICE","quantity":{"amount":120,"unit":"ml"},"display_name":"Fresh grapefruit juice","notes":null}]'::jsonb, 'build', '{"en":"Fill a highball glass with ice. Pour vodka over ice, then top with fresh grapefruit juice. Stir gently to combine. Garnish with a grapefruit wedge."}'::jsonb, 'Highball glass', '{"en":"Grapefruit wedge"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA"}', '{"citrus","bitter","refreshing"}', 8, 150, 'easy', 30, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"casual","brunch","poolside"}', false, false, '{"salty-dog","sea-breeze"}', 'Always use fresh grapefruit juice, not from concentrate. Pink or ruby red grapefruit provides a sweeter profile. If customer wants salt rim, this becomes a Salty Dog.', 'low', 70, 'https://www.diffordsguide.com/cocktails/recipe/1234/greyhound', 'Classic recipe documented in multiple cocktail books and bartending guides.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 156. Harvey Wallbanger


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('b89544ca-06f4-45a5-b1fb-7dbb7c730701', 'harvey-wallbanger', 'e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3', '{"en":"Harvey Wallbanger"}'::jsonb, 'famous', NULL, '{"highball","long-drink","famous","classic","vodka","orange","galliano","1970s"}', '{"en":"A Screwdriver elevated with a float of Galliano liqueur. The Harvey Wallbanger was one of the most popular cocktails of the 1970s, combining vodka, orange juice, and the distinctive herbal-vanilla notes of Galliano in a tall, sunny drink."}'::jsonb, '{"created_year":"1952","origin":{"city":"Los Angeles","state":"California","country":"USA"},"creator":{"name":"Donato \"Duke\" Antone","profession":"bartender"},"story":{"en":"The Harvey Wallbanger was created by bartender Donato \"Duke\" Antone at his Blackwatch Bar in Los Angeles in 1952. The drink became a phenomenon in the 1970s thanks to an aggressive marketing campaign by the Galliano company. The name comes from a fictional surfer named Harvey who loved the drink so much that after drinking several, he would bang into walls while leaving the bar. The cocktail became synonymous with 1970s disco culture and was so popular that Galliano sales skyrocketed during this period."},"named_after":{"en":"Named after a fictional surfer named Harvey who allegedly loved the drink so much he would bang into walls while leaving the bar."}}'::jsonb, '{"profile":["sweet","citrus","herbal","vanilla"],"description":{"en":"Starts like a classic Screwdriver with sweet orange and vodka, then finishes with the distinctive herbal, vanilla, and anise notes of Galliano. The liqueur adds complexity and a touch of elegance to the simple base."},"first_impression":{"en":"Fresh orange juice with subtle herbal notes floating on top"},"finish":{"en":"Sweet vanilla and anise linger with orange citrus notes"},"balance":{"en":"The Galliano float provides aromatic complexity without overpowering the refreshing orange-vodka base"}}'::jsonb, '{"best_time":["afternoon","brunch","evening"],"occasions":["casual","brunch","retro_party","celebration"],"seasons":["all-year"],"food_pairings":{"en":"Pairs well with brunch dishes, eggs benedict, pancakes, and light appetizers. Also works with Italian antipasti given the Italian Galliano liqueur."},"ideal_for":{"en":"Perfect for those who love Screwdrivers but want more complexity. Great for retro-themed parties or anyone curious about classic 1970s cocktails. Ideal for Galliano enthusiasts."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":45,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":90,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_GALLIANO","quantity":{"amount":15,"unit":"ml"},"display_name":"Galliano L''Autentico","notes":null}]'::jsonb, 'build', '{"en":"Fill a highball glass with ice. Pour vodka and orange juice over ice and stir gently. Float Galliano on top by pouring it slowly over the back of a bar spoon. Garnish with an orange slice and cherry."}'::jsonb, 'Highball glass', '{"en":"Orange slice and maraschino cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA"}', '{"sweet","citrus","herbal","vanilla"}', 11, 185, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"all-year"}', '{"casual","brunch","retro_party"}', false, false, '{"screwdriver","freddy-fudpucker"}', 'The Galliano float is key - pour slowly over back of spoon to create visual layers. Use freshly squeezed orange juice. Garnish is important for presentation - this is a showpiece drink.', 'mid', 60, 'https://www.diffordsguide.com/cocktails/recipe/1240/harvey-wallbanger', 'Created by Duke Antone in 1952, popularized in 1970s by Galliano marketing.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 157. Hemingway Daiquiri


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('2489976e-a8b6-4871-8122-919eae330b4e', 'hemingway-daiquiri', 'd0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9', '{"en":"Hemingway Daiquiri"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","rum","tart","cuban","literary"}', '{"en":"A tart, sugar-free variation of the classic daiquiri featuring white rum, lime, grapefruit, and maraschino liqueur. Created for Ernest Hemingway, this cocktail is bright, refreshing, and perfectly balanced without added sugar."}'::jsonb, '{"created_year":"1930","origin":{"city":"Havana","bar":"El Floridita","country":"Cuba"},"creator":{"name":"Constantino Ribalaigua","profession":"bartender"},"story":{"en":"Created at Havana''s legendary El Floridita bar by head bartender Constantino Ribalaigua for Ernest Hemingway in the 1930s. Hemingway, a diabetic, requested a daiquiri without sugar. Constantino crafted this tart masterpiece using double rum, fresh citrus, and maraschino liqueur. Also known as \"Papa Doble\" (Hemingway''s nickname), this drink became his signature order and helped make El Floridita famous worldwide."},"named_after":{"en":"Named after Ernest Hemingway, the legendary American author who lived in Cuba and frequented El Floridita. Also called \"Papa Doble\" after his nickname."}}'::jsonb, '{"profile":["tart","citrus","refreshing"],"description":{"en":"Bright and intensely tart with fresh lime and grapefruit dominating. The maraschino liqueur adds subtle cherry sweetness and complexity, while double rum provides backbone. Refreshing and bracing without sweetness."},"first_impression":{"en":"Sharp citrus tartness hits immediately with grapefruit and lime brightness"},"finish":{"en":"Clean, refreshing finish with lingering citrus and subtle maraschino"},"balance":{"en":"Boldly tart yet balanced - the maraschino provides just enough sweetness to round sharp citrus"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["aperitivo","beach","summer_party","brunch"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with fresh seafood, ceviche, oysters, or light salads. Perfect as a palate-cleansing aperitif before rich meals."},"ideal_for":{"en":"Perfect for those who prefer tart, sugar-free cocktails. Ideal for rum lovers seeking a bright, refreshing drink without sweetness, or anyone following Hemingway''s legendary example."}}'::jsonb, '[{"ingredient_id":"ING_WHITE_RUM","quantity":{"amount":60,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_GRAPEFRUIT_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh grapefruit juice","notes":null},{"ingredient_id":"ING_MARASCHINO_LIQUEUR","quantity":{"amount":15,"unit":"ml"},"display_name":"Maraschino liqueur","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a chilled coupe or cocktail glass. Garnish with a lime wheel or grapefruit twist."}'::jsonb, 'Coupe glass', '{"en":"Lime wheel or grapefruit twist"}'::jsonb, 'none', 'up', '{"ING_WHITE_RUM"}', '{"tart","citrus","refreshing"}', 20, 140, 'easy', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free","sugar_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free","sugar-free"}', '{"spring","summer"}', '{"aperitivo","beach","summer_party","brunch"}', false, false, '{"papa-doble","hemingway-special","daiquiri-natural"}', 'No sugar added - Hemingway was diabetic. Double rum makes this strong. Use fresh grapefruit juice only. Luxardo maraschino is preferred. Legend says Hemingway drank these in quantities of 6-12 per session. Serve very cold.', 'mid', 75, 'https://www.diffordsguide.com/cocktails/recipe/1375/hemingway-daiquiri', 'Created at El Floridita, Havana, 1930s. Hemingway''s signature drink, also known as Papa Doble.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 158. Hurricane


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('430caaa9-1c42-4b33-9171-171dac0df42e', 'hurricane', 'hurricane_famous_tiki_tropical_cocktail', '{"en":"Hurricane"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","fruity","strong"}', '{"en":"The Hurricane is New Orleans'' most famous cocktail, a potent rum punch combining light and dark rum with passion fruit syrup and citrus. Named after the hurricane lamp-shaped glass it''s served in, this sweet and strong drink is a French Quarter institution."}'::jsonb, '{"created_year":"1940","origin":{"city":"New Orleans","bar":"Pat O''Brien''s Bar","country":"USA"},"creator":{"name":"Pat O''Brien","profession":"bar owner"},"story":{"en":"The Hurricane was created in the 1940s by Pat O''Brien at his eponymous French Quarter bar in New Orleans. During World War II, whiskey was scarce but rum was plentiful, so O''Brien created this potent rum cocktail to use up his surplus stock. He served it in a hurricane lamp-shaped glass, and the drink quickly became a hit with sailors on shore leave. The cocktail became synonymous with New Orleans and Bourbon Street nightlife, remaining one of the city''s signature drinks to this day."},"named_after":{"en":"Named after the hurricane lamp-shaped glass in which it is traditionally served, with its distinctive curved design."}}'::jsonb, '{"profile":["fruity","sweet","strong"],"description":{"en":"Bold and tropical with intense passion fruit flavor dominating the palate. The Hurricane combines sweet fruitiness with the warming strength of double rum, balanced by bright citrus notes. Deceptively strong despite its sweet, approachable taste."},"first_impression":{"en":"Intense passion fruit sweetness hits first, masking the strong rum foundation underneath"},"finish":{"en":"Long, warming finish with rum heat and lingering tropical fruit notes"},"balance":{"en":"Sweet and strong with fruit flavors masking significant alcohol content - dangerously drinkable"}}'::jsonb, '{"best_time":["afternoon","evening","late_night"],"occasions":["mardi_gras","party","celebration","festival"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with New Orleans classics like jambalaya, gumbo, po'' boys, or beignets. Also pairs well with Cajun and Creole cuisine, fried seafood, and spicy dishes."},"ideal_for":{"en":"Perfect for party lovers and those seeking a festive, high-energy drink. Ideal for Mardi Gras celebrations or anyone wanting to experience New Orleans nightlife. Great for those who enjoy sweet, fruity cocktails with a serious kick."}}'::jsonb, '[{"ingredient_id":"ING_RUM_WHITE","quantity":{"amount":30,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_RUM_DARK","quantity":{"amount":30,"unit":"ml"},"display_name":"Dark rum","notes":null},{"ingredient_id":"ING_PASSION_FRUIT_SYRUP","quantity":{"amount":60,"unit":"ml"},"display_name":"Passion fruit syrup","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a hurricane glass filled with ice. Garnish with orange slice and maraschino cherry."}'::jsonb, 'Hurricane glass', '{"en":"Orange slice, maraschino cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_RUM_WHITE","ING_RUM_DARK"}', '{"fruity","sweet","strong"}', 14, 280, 'easy', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"mardi_gras","party","celebration","festival"}', false, false, '{"new-orleans-hurricane","french-quarter-hurricane"}', 'Original Pat O''Brien''s recipe is proprietary, but this is the classic formula. Can substitute passion fruit purée for syrup. Glass should be hurricane lamp-shaped. Very strong - warn guests it''s deceptively potent.', 'mid', 90, 'https://www.patobriens.com/hurricane-drink', 'Based on classic New Orleans formula. Historical information from Pat O''Brien''s Bar and New Orleans cocktail archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 159. Income Tax


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('a31e8a51-aa19-49b7-a8f1-2db991c1dd10', 'income-tax', 'l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1', '{"en":"Income Tax"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","gin","citrus","vermouth","prohibition-era"}', '{"en":"A bittersweet Prohibition-era cocktail that lives up to its name - complex, slightly bitter, but ultimately rewarding. The Income Tax combines gin with vermouths, orange juice, and Angostura bitters for a sophisticated drink that''s a close cousin to the Bronx cocktail."}'::jsonb, '{"created_year":"1920","origin":{"city":"Unknown","bar":"Unknown","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Income Tax cocktail emerged during the early 1920s, a time when both Prohibition and the modern income tax system were new and controversial in America. The cocktail first appeared in print in Harry Craddock''s \"The Savoy Cocktail Book\" (1930), where it was described with dark humor as appropriate for the era''s financial pressures. The name perfectly captured the bittersweet nature of both the drink and the tax that inspired it - complex, somewhat bitter, but necessary and ultimately satisfying. The cocktail is essentially a variation of the Bronx, with the addition of Angostura bitters adding extra complexity and bite. Like many Prohibition-era drinks, it fell into obscurity after the 1930s but has been rediscovered by modern bartenders who appreciate its clever name and sophisticated flavor profile."},"named_after":{"en":"Named after the U.S. income tax, which became a significant burden on Americans in the 1920s. The bittersweet drink mirrors the complex feelings toward taxation."}}'::jsonb, '{"profile":["citrus","bitter","complex"],"description":{"en":"Complex, bittersweet, and sophisticated. The Income Tax balances gin''s botanicals with dual vermouths, fresh orange juice, and the distinctive spice of Angostura bitters. More bitter and complex than the Bronx, it''s a drink for contemplation."},"first_impression":{"en":"Orange juice brightness immediately followed by gin botanicals and aromatic bitters"},"finish":{"en":"Medium-long finish with lingering bitters, orange, and herbal vermouth complexity"},"balance":{"en":"The bitters add a distinctive bitter edge that balances the sweetness - complex and adult"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["aperitivo","sophisticated","contemplative","tax_season"],"seasons":["spring","autumn","winter"],"food_pairings":{"en":"Pairs well with savory appetizers, olives, nuts, aged cheeses, and charcuterie. The bitterness cuts through rich foods beautifully. Also good with grilled vegetables and Mediterranean fare."},"ideal_for":{"en":"Perfect for gin and bitter enthusiasts who appreciate complex flavors. Ideal for accountants, tax professionals, and anyone who needs consolation during tax season. A thinking person''s cocktail."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":45,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_DRY_VERMOUTH","quantity":{"amount":15,"unit":"ml"},"display_name":"Dry vermouth","notes":null},{"ingredient_id":"ING_SWEET_VERMOUTH","quantity":{"amount":15,"unit":"ml"},"display_name":"Sweet vermouth","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":2,"unit":"dash"},"display_name":"Angostura bitters","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a chilled cocktail glass. Garnish with an orange twist."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"Orange twist"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"citrus","bitter","complex"}', 18, 160, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","nut_free","dairy_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"spring","autumn","winter"}', '{"aperitivo","sophisticated","contemplative"}', false, false, '{"bronx","satan-whiskers"}', 'Very similar to the Bronx but with added Angostura bitters. Always use fresh orange juice. The bitters are essential - don''t skip them. Some versions use equal parts vermouths, others vary the ratio. Shake well to integrate all ingredients.', 'mid', 35, 'https://www.diffordsguide.com/cocktails/recipe/1143/income-tax', 'Classic recipe from The Savoy Cocktail Book (1930) by Harry Craddock.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 160. Industry Sour


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('7340b48c-8755-4f14-a8b8-d12f7ea08321', 'industry-sour', '322154647382908475638291048573629184756382', '{"en":"Industry Sour"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","whiskey","green-chartreuse","fernet"}', '{"en":"A bartender''s favorite and modern classic, the Industry Sour combines bourbon or rye with Green Chartreuse and Fernet-Branca, creating a complex, herbal, bitter-sweet whiskey sour. Named for the hospitality industry, this drink is beloved by bar professionals for its sophisticated balance of sweet, sour, herbal, and bitter elements."}'::jsonb, '{"created_year":"2011","origin":{"city":"New York City","bar":"Booker and Dax","country":"USA"},"creator":{"name":"Dave Arnold","profession":"bartender"},"story":{"en":"The Industry Sour was created around 2011 by bartender Dave Arnold at Booker and Dax in New York City. Arnold wanted to create a drink specifically for industry professionals - bartenders, servers, and hospitality workers - who appreciate complex, bitter flavors. By combining whiskey with Green Chartreuse (a bartender favorite) and Fernet-Branca (the \"bartender''s handshake\"), he created a sophisticated sour that became a cult favorite among industry insiders. The name directly references the hospitality industry, and the drink is often served as a shift drink or late-night favorite."},"named_after":{"en":"Named after \"the industry\" - a term for hospitality and bar professionals. It''s made by the industry, for the industry."}}'::jsonb, '{"profile":["herbal","bitter","complex","whiskey"],"description":{"en":"Intensely complex and sophisticated. Bourbon or rye provides a rich whiskey base, while Green Chartreuse adds herbal sweetness and complexity. Fernet-Branca contributes menthol-eucalyptus bitterness that cuts through the sweetness. Fresh lemon adds brightness, and simple syrup balances the bitter elements. More complex and contemplative than a standard whiskey sour, with layers of herbal, bitter, sweet, and sour notes."},"first_impression":{"en":"Herbal Chartreuse and whiskey hit first, followed by Fernet''s menthol bite"},"finish":{"en":"Long, bitter finish with lingering menthol, herbs, and whiskey warmth"},"balance":{"en":"Complex balance - sweet, sour, herbal, bitter in sophisticated harmony"}}'::jsonb, '{"best_time":["late_night","evening","after_shift"],"occasions":["industry_gathering","digestivo","contemplative_drinking","bartender_favorite"],"seasons":["autumn","winter","spring","summer"],"food_pairings":{"en":"Excellent as a digestif or with rich, savory foods. Pairs well with aged cheeses, charcuterie, dark chocolate, or bitter greens. Traditional bartender pairing: pizza or late-night snacks."},"ideal_for":{"en":"Perfect for bartenders and industry professionals. Ideal for those who appreciate complex, bitter cocktails with multiple layers. Great for adventurous drinkers who enjoy Fernet and Chartreuse. A rite of passage for serious cocktail enthusiasts."}}'::jsonb, '[{"ingredient_id":"ING_BOURBON","quantity":{"amount":45,"unit":"ml"},"display_name":"Bourbon or rye whiskey","notes":null},{"ingredient_id":"ING_GREEN_CHARTREUSE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Green Chartreuse","notes":null},{"ingredient_id":"ING_FERNET_BRANCA","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Fernet-Branca","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":15,"unit":"ml"},"display_name":"Simple syrup","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well chilled. Strain into a rocks glass over fresh ice or serve up in a coupe. Garnish with a lemon twist and/or mint sprig."}'::jsonb, 'Rocks glass', '{"en":"Lemon twist and/or mint sprig"}'::jsonb, 'cubes', 'on_the_rocks', '{"ING_BOURBON"}', '{"herbal","bitter","complex","whiskey"}', 24, 190, 'medium', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring","summer"}', '{"industry_gathering","digestivo","contemplative_drinking","bartender_favorite"}', false, false, '{"toronto","greenpoint","chartreuse-swizzle"}', 'Bartender favorite - often served as shift drink. Use fresh lemon juice only. Fernet amount is crucial - too much overwhelms. Can use bourbon or rye. Green Chartreuse essential. Popular late-night industry drink.', 'premium', 65, 'https://punchdrink.com/recipes/industry-sour/', 'Created by Dave Arnold at Booker and Dax, New York City, circa 2011. A modern bartender favorite.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 161. Irish Car Bomb


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('928f8857-95d2-4e26-a77a-a6583b155b32', 'irish-car-bomb', 'irish_car_bomb_shot_famous_guinness_baileys_bomb', '{"en":"Irish Car Bomb"}'::jsonb, 'famous', NULL, '{"shot","shooter","famous","bomb","beer","irish","creamy","st-patricks"}', '{"en":"A bomb shot combining Irish whiskey and Baileys Irish Cream dropped into Guinness stout. This potent drink must be consumed quickly before the cream curdles. NOTE: The name is considered offensive in Ireland due to its reference to The Troubles; alternative names include \"Irish Slammer\" or \"Dublin Drop.\""}'::jsonb, '{"created_year":"1979","origin":{"city":"Norwich","bar":"Wilson''s Saloon","country":"USA"},"creator":{"name":"Charles Burke Cronin Oat","profession":"bartender"},"story":{"en":"Created in 1979 by bartender Charles Oat at Wilson''s Saloon in Norwich, Connecticut. While popular in America, especially around St. Patrick''s Day, the drink''s name is highly controversial and considered deeply offensive in Ireland due to its reference to the car bombings during The Troubles (1960s-1990s). Many Irish pubs refuse to serve it, and bartenders recommend using alternative names like \"Irish Slammer\" or simply avoiding the drink in Irish establishments."},"named_after":{"en":"CONTROVERSIAL: Named after car bomb attacks during The Troubles in Northern Ireland. This name is considered highly offensive in Ireland and should be avoided or replaced with \"Irish Slammer\" or \"Dublin Drop.\""}}'::jsonb, '{"profile":["creamy","malty","sweet","boozy"],"description":{"en":"Rich and creamy with chocolate and coffee notes from Baileys, whiskey warmth, and the roasted malt character of Guinness. Creates a surprisingly smooth combination when drunk quickly."},"first_impression":{"en":"Creamy sweetness meets roasted stout bitterness"},"finish":{"en":"Rich, creamy finish with lingering whiskey warmth"},"balance":{"en":"Sweet cream balances bitter stout - must drink quickly before curdling"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["party","st_patricks_day","celebration"],"seasons":["all_seasons"],"food_pairings":{"en":"Not typically paired with food. Best consumed as a standalone drink. If serving around St. Patrick''s Day, pairs with Irish pub food like shepherd''s pie or fish and chips."},"ideal_for":{"en":"Popular in American bars around St. Patrick''s Day. WARNING: Highly offensive in Ireland - use alternative names \"Irish Slammer\" or \"Dublin Drop\" or avoid entirely in Irish establishments. Must be consumed immediately."}}'::jsonb, '[{"ingredient_id":"ING_IRISH_WHISKEY","quantity":{"amount":30,"unit":"ml"},"display_name":"Irish Whiskey","notes":null},{"ingredient_id":"ING_BAILEYS","quantity":{"amount":30,"unit":"ml"},"display_name":"Baileys Irish Cream","notes":null},{"ingredient_id":"ING_GUINNESS","quantity":{"amount":250,"unit":"ml"},"display_name":"Guinness Stout","notes":null}]'::jsonb, 'build', '{"en":"Fill a pint glass 3/4 full with Guinness. In a shot glass, add Irish whiskey and top with Baileys. Drop the shot glass into the pint glass and drink immediately before the Baileys curdles."}'::jsonb, 'Shot glass (dropped into pint glass)', '{"en":"None"}'::jsonb, 'none', 'shot', '{"ING_IRISH_WHISKEY","ING_BAILEYS"}', '{"creamy","malty","sweet","boozy"}', 8, 250, 'easy', 45, '{"milk","sulphites","gluten"}', '{"lactose","alcohol","sulphites_intolerance","gluten_intolerance"}', '{"vegetarian","pescatarian"}', 0, '{"vegetarian"}', '{"all-seasons"}', '{"party","celebration","st-patricks-day"}', false, false, '{"irish-slammer","dublin-drop","irish-bomb"}', 'CULTURAL SENSITIVITY WARNING: This drink''s name is highly offensive in Ireland. Recommend using "Irish Slammer" or "Dublin Drop" as alternative names. NEVER serve this in Irish pubs or to Irish customers. Must be consumed immediately as Baileys will curdle in Guinness. Use fresh Guinness and serve quickly.', 'mid', 65, 'https://en.wikipedia.org/wiki/Irish_Car_Bomb', 'Controversial bomb shot created in 1979. Name is offensive in Ireland - use alternatives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


