INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('79e14a88-00b3-4eac-a1a3-85d7c0ee4f7a', 'singapore-sling', 'singapore_sling_iba_contemporary_classic', '{"en":"Singapore Sling"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","tropical","fruity","classic","iconic"}', '{"en":"A legendary gin-based cocktail with a complex blend of citrus, cherry liqueur, and tropical flavors. Created at the iconic Raffles Hotel, this pink-hued classic is one of the most famous cocktails in the world."}'::jsonb, '{"created_year":"1915","origin":{"city":"Singapore","bar":"Raffles Hotel Long Bar","country":"Singapore"},"creator":{"name":"Ngiam Tong Boon","profession":"bartender"},"story":{"en":"Created by Hainanese-Chinese bartender Ngiam Tong Boon at Raffles Hotel''s Long Bar around 1915. Originally designed to appeal to ladies who weren''t supposed to drink in public, the cocktail''s fruity appearance disguised its alcoholic content. The original recipe was lost and recreated in the 1970s."},"named_after":{"en":"Named after Singapore, where it was created at the legendary Raffles Hotel."}}'::jsonb, '{"profile":["fruity","sweet","tropical"],"description":{"en":"Complex and tropical with layers of cherry, pineapple, and citrus. The gin provides a botanical backbone while Benedictine adds herbal depth. Sweet yet refreshing with a beautiful balance."},"first_impression":{"en":"Bright cherry and pineapple flavors with gin botanicals"},"finish":{"en":"Long, fruity finish with lingering herbal notes from Benedictine"},"balance":{"en":"Well-balanced between sweetness, citrus acidity, and botanical complexity"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["celebration","special_occasion","tropical_party"],"seasons":["spring","summer"],"food_pairings":{"en":"Pairs well with Asian cuisine, especially Singaporean dishes, seafood, and tropical fruits."},"ideal_for":{"en":"Perfect for those who enjoy complex, fruity cocktails with historical significance. A must-try for anyone visiting Singapore."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":30,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_CHERRY_LIQUEUR","quantity":{"amount":15,"unit":"ml"},"display_name":"Cherry liqueur","notes":null},{"ingredient_id":"ING_BENEDICTINE","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Bénédictine","notes":null},{"ingredient_id":"ING_COINTREAU","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Cointreau","notes":null},{"ingredient_id":"ING_GRENADINE","quantity":{"amount":10,"unit":"ml"},"display_name":"Grenadine","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":120,"unit":"ml"},"display_name":"Pineapple juice","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":1,"unit":"dash"},"display_name":"Angostura bitters","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice cubes. Shake well. Strain into a highball glass. Garnish with a slice of pineapple and a maraschino cherry."}'::jsonb, 'Highball glass', '{"en":"Pineapple slice and maraschino cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_GIN"}', '{"fruity","sweet","tropical"}', 12, 240, 'medium', 180, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"celebration","special_occasion","tropical_party"}', false, false, '{"classic-singapore-sling","modern-singapore-sling"}', 'Use fresh pineapple juice if possible. The original recipe was lost and multiple versions exist. This is the IBA official version. Shake vigorously to properly integrate all ingredients.', 'mid', 85, 'https://iba-world.com/singapore-sling/', 'IBA Official Recipe. Historical information from Raffles Hotel archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 72. Tequila Sunrise


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('1d044f05-4dcd-42e9-a76d-4c9000197956', 'tequila-sunrise', 'tequila_sunrise_iba_contemporary_classic', '{"en":"Tequila Sunrise"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","fruity","visual","summer","iconic","easy"}', '{"en":"A visually stunning cocktail that lives up to its name - tequila and orange juice layered with grenadine to create a sunrise effect. Beautiful, fruity, and refreshing, it''s as pleasing to the eye as it is to the palate."}'::jsonb, '{"created_year":"1970","origin":{"city":"Sausalito","bar":"Trident Restaurant","country":"USA"},"creator":{"name":"Bobby Lozoff and Billy Rice","profession":"bartenders"},"story":{"en":"The modern Tequila Sunrise was created in the early 1970s by Bobby Lozoff and Billy Rice at the Trident Restaurant in Sausalito, California. It gained massive popularity when Mick Jagger tried it and ordered the drink everywhere during the Rolling Stones'' 1972 American tour, leading to it being called \"The Tequila Sunrise tour.\""},"named_after":{"en":"Named for the visual effect created by the grenadine settling through the drink, resembling a sunrise."}}'::jsonb, '{"profile":["fruity","sweet","citrus"],"description":{"en":"Bright and refreshing with prominent orange citrus flavor complemented by sweet grenadine. Tequila adds earthy agave notes and warmth. Light, easy-drinking, and crowd-pleasing."},"first_impression":{"en":"Sweet orange and cherry with smooth tequila"},"finish":{"en":"Clean, fruity finish with subtle agave warmth"},"balance":{"en":"Well-balanced between sweet grenadine and citrus orange"}}'::jsonb, '{"best_time":["morning","afternoon","evening"],"occasions":["brunch","beach","pool_party","casual"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with Mexican cuisine, breakfast dishes, fresh fruit, grilled seafood, and light appetizers."},"ideal_for":{"en":"Ideal for anyone seeking a visually appealing, easy-drinking cocktail. Perfect for brunch, poolside, or introducing friends to tequila."}}'::jsonb, '[{"ingredient_id":"ING_TEQUILA","quantity":{"amount":45,"unit":"ml"},"display_name":"Tequila","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":90,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_GRENADINE","quantity":{"amount":15,"unit":"ml"},"display_name":"Grenadine syrup","notes":null}]'::jsonb, 'build', '{"en":"Pour tequila and orange juice directly into a highball glass filled with ice cubes. Add grenadine by carefully pouring it down the side of the glass - it will sink and gradually rise to create a sunrise effect. Do not stir. Garnish with an orange slice and cherry."}'::jsonb, 'Highball glass', '{"en":"Orange slice and maraschino cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_TEQUILA"}', '{"fruity","sweet","citrus"}', 10, 200, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"brunch","beach","pool_party","casual"}', false, false, '{"tequila-sunset","vodka-sunrise","mezcal-sunrise"}', 'DO NOT STIR after adding grenadine - the layered sunrise effect is key to presentation. Pour grenadine slowly down the inside of the glass. Use fresh-squeezed orange juice for best results. Guest can stir before drinking.', 'low', 90, 'https://iba-world.com/tequila-sunrise/', 'IBA Official Recipe. Made famous by The Rolling Stones in the 1970s.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 73. Vesper


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('19ac91b7-9ee9-4476-a9fc-85f9fa447300', 'vesper', 'vesper_iba_contemporary_classic', '{"en":"Vesper"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","james-bond","literary","spirit-forward","iconic"}', '{"en":"James Bond''s signature cocktail - a powerful combination of gin, vodka, and Lillet Blanc. Created by Ian Fleming in Casino Royale, this drink is strong, sophisticated, and distinctly literary."}'::jsonb, '{"created_year":"1953","origin":{"city":"London","bar":"Fictional (Literary)","country":"UK"},"creator":{"name":"Ian Fleming (via James Bond)","profession":"author"},"story":{"en":"The Vesper was invented by author Ian Fleming and appeared in his 1953 James Bond novel \"Casino Royale.\" Bond orders it and names it after Vesper Lynd, the book''s female lead. The original called for Kina Lillet, which no longer exists - modern versions use Lillet Blanc or Cocchi Americano."},"named_after":{"en":"Named after Vesper Lynd, the female protagonist in Ian Fleming''s \"Casino Royale.\""}}'::jsonb, '{"profile":["spirit-forward","dry","citrus"],"description":{"en":"Bold, strong, and bracingly dry. The combination of gin and vodka creates a powerful backbone, while Lillet adds subtle fruitiness and complexity. Lemon provides a bright, aromatic finish."},"first_impression":{"en":"Strong gin botanicals with vodka smoothness and citrus"},"finish":{"en":"Long, dry finish with lingering botanical and citrus notes"},"balance":{"en":"Spirit-forward with subtle aromatic complexity from Lillet"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["special_occasion","celebration","date_night"],"seasons":["autumn","winter","spring","summer"],"food_pairings":{"en":"Pairs well with seafood, particularly oysters, caviar, and smoked salmon. Also excellent with light appetizers and olives."},"ideal_for":{"en":"Perfect for spirit-forward cocktail enthusiasts and James Bond fans. Ideal for those who appreciate strong, sophisticated drinks with literary pedigree."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":60,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_VODKA","quantity":{"amount":15,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_LILLET_BLANC","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Lillet Blanc","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice cubes. Shake well. Strain into a chilled cocktail glass. Garnish with a large, thin slice of lemon peel."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"Large, thin lemon peel"}'::jsonb, 'none', 'up', '{"ING_GIN","ING_VODKA"}', '{"spirit-forward","dry","citrus"}', 28, 190, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring","summer"}', '{"special_occasion","celebration","date_night"}', false, false, '{"vesper-with-cocchi-americano","reverse-vesper"}', 'Bond''s original spec: "Three measures of Gordon''s, one of vodka, half a measure of Kina Lillet. Shake it very well until it''s ice-cold, then add a large thin slice of lemon peel." Modern Lillet Blanc is sweeter than original Kina Lillet - some bartenders prefer Cocchi Americano for authenticity.', 'mid', 70, 'https://iba-world.com/vesper/', 'IBA Official Recipe. Originally from Ian Fleming''s "Casino Royale" (1953).', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 74. White Russian


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('ccb36b0d-3be9-46c7-a72e-89381989a6ef', 'white-russian', 'white_russian_iba_contemporary_classic', '{"en":"White Russian"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","creamy","coffee","dessert","after-dinner","cult-classic"}', '{"en":"A decadent, creamy cocktail that adds fresh cream to the classic Black Russian. Smooth, sweet, and dangerously easy to drink - this coffee-flavored indulgence became a cultural icon thanks to \"The Big Lebowski.\""}'::jsonb, '{"created_year":"1960s","origin":{"city":"Oakland","bar":"Unknown","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The White Russian is a variation of the Black Russian (created 1949), with cream added. The exact origins are unclear, but it gained popularity in the 1960s-70s. The drink was relatively obscure until the 1998 Coen Brothers film \"The Big Lebowski,\" where Jeff Bridges'' character \"The Dude\" drinks White Russians throughout the movie. This catapulted the cocktail to cult status and renewed popularity."},"named_after":{"en":"Named \"White Russian\" due to the white color from cream, contrasting with the \"Black Russian\" which lacks cream."}}'::jsonb, '{"profile":["creamy","sweet","smooth","boozy"],"description":{"en":"Rich and velvety with prominent coffee flavor from Kahlúa, smooth vodka backbone, and luxurious cream. Sweet, indulgent, and dessert-like with balanced coffee and dairy notes."},"first_impression":{"en":"Smooth cream and sweet coffee with vodka warmth"},"finish":{"en":"Long, creamy finish with lingering coffee and vanilla notes"},"balance":{"en":"Well-balanced between sweet coffee liqueur, neutral vodka, and rich cream"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["digestivo","nightcap","casual","celebration"],"seasons":["autumn","winter","spring","summer"],"food_pairings":{"en":"Perfect as a dessert replacement or with chocolate desserts, brownies, tiramisu, coffee cake, or ice cream."},"ideal_for":{"en":"Perfect for dessert cocktail lovers and fans of \"The Big Lebowski.\" Ideal for those who enjoy creamy, sweet drinks with coffee flavor. A great introduction to cocktails for non-drinkers transitioning to spirits."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":50,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_COFFEE_LIQUEUR","quantity":{"amount":20,"unit":"ml"},"display_name":"Coffee liqueur (Kahlúa)","notes":null},{"ingredient_id":"ING_HEAVY_CREAM","quantity":{"amount":30,"unit":"ml"},"display_name":"Fresh cream","notes":null}]'::jsonb, 'build', '{"en":"Pour vodka and coffee liqueur into an old fashioned glass filled with ice cubes. Float fresh cream on top. Stir gently before drinking, or drink through the cream."}'::jsonb, 'Old Fashioned glass', '{"en":"None (optional: coffee beans)"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA"}', '{"creamy","sweet","smooth","boozy"}', 18, 300, 'easy', 45, '{"milk","sulphites"}', '{"lactose","alcohol","sulphites_intolerance","caffeine"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 0, '{"vegetarian","gluten-free"}', '{"autumn","winter","spring","summer"}', '{"digestivo","nightcap","casual","celebration"}', false, false, '{"black-russian","dirty-russian","mudslide","colorado-bulldog"}', 'The cream can be floated on top (layered) for visual appeal, or stirred in for consistency. "The Dude" from The Big Lebowski is famous for drinking these - popular culture reference. Can substitute half-and-half for cream if preferred lighter. Kahlúa is traditional but any coffee liqueur works. Deceptively strong despite creamy sweetness.', 'low', 85, 'https://iba-world.com/white-russian/', 'IBA Official Recipe. Cultural reference from "The Big Lebowski" (1998).', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 75. Zombie


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('b61c950d-42c4-49fe-b36a-a2022af8381f', 'zombie', 'zombie_iba_contemporary_2025', '{"en":"Zombie"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","tiki","strong","complex","tropical"}', '{"en":"A legendary tiki cocktail combining three types of rum with tropical fruit juices and secret spices. Deceptively potent, the Zombie is famous for its ability to \"turn drinkers into zombies\" due to its high alcohol content masked by fruity sweetness."}'::jsonb, '{"created_year":"1934","origin":{"city":"Los Angeles","bar":"Don the Beachcomber","country":"USA"},"creator":{"name":"Donn Beach (Ernest Raymond Beaumont Gantt)","profession":"bartender"},"story":{"en":"Created by Donn Beach (Don the Beachcomber) in 1934 at his Hollywood restaurant. Legend says he created it for a hungover customer who needed help getting through a business meeting. The customer returned days later complaining he had been \"turned into a zombie\" for his entire trip. Don limited customers to two Zombies due to its potency. The original recipe was kept secret for decades, with staff mixing ingredients from coded bottles."},"named_after":{"en":"Named for its zombifying effect on drinkers due to high alcohol content."}}'::jsonb, '{"profile":["tropical","sweet","strong","complex"],"description":{"en":"Complex, fruity, and dangerously drinkable. Multiple rums create depth, tropical juices provide sweetness, and secret spices add complexity. The high alcohol is masterfully hidden beneath layers of flavor."},"first_impression":{"en":"Tropical fruit sweetness with hints of spice"},"finish":{"en":"Long, warm finish revealing the drink''s true strength"},"balance":{"en":"Masterfully balanced to hide extreme alcohol content"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["party","celebration","tiki_bar"],"seasons":["spring","summer"],"food_pairings":{"en":"Best with tropical foods, Caribbean cuisine, jerk chicken, coconut shrimp, or Polynesian dishes. Often enjoyed on its own at tiki bars."},"ideal_for":{"en":"WARNING: Extremely strong cocktail. For experienced drinkers only. Perfect for tiki enthusiasts and special celebrations. Limit to one or two maximum."}}'::jsonb, '[{"ingredient_id":"ING_RUM_DARK","quantity":{"amount":45,"unit":"ml"},"display_name":"Dark rum","notes":null},{"ingredient_id":"ING_RUM_WHITE","quantity":{"amount":45,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_RUM_OVERPROOF","quantity":{"amount":30,"unit":"ml"},"display_name":"Overproof rum","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":20,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_GRAPEFRUIT_JUICE","quantity":{"amount":40,"unit":"ml"},"display_name":"Grapefruit juice","notes":null},{"ingredient_id":"ING_CINNAMON_SYRUP","quantity":{"amount":15,"unit":"ml"},"display_name":"Cinnamon syrup","notes":null},{"ingredient_id":"ING_GRENADINE","quantity":{"amount":15,"unit":"ml"},"display_name":"Grenadine","notes":null},{"ingredient_id":"ING_ABSINTHE","quantity":{"amount":1,"unit":"dash"},"display_name":"Absinthe","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":1,"unit":"dash"},"display_name":"Angostura bitters","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a blender with crushed ice. Blend at high speed for 5 seconds. Pour into a tall glass. Garnish with mint sprig and pineapple wedge."}'::jsonb, 'Tiki mug or Collins glass', '{"en":"Mint sprig and pineapple wedge"}'::jsonb, 'crushed', 'blended', '{"ING_RUM_DARK","ING_RUM_WHITE","ING_RUM_OVERPROOF"}', '{"tropical","sweet","strong","complex"}', 25, 320, 'hard', 120, '{"sulphites","wormwood"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 1, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"party","celebration","tiki_bar"}', false, false, '{"1934-zombie","modern-zombie"}', 'CRITICAL: Extremely high alcohol content. Limit customers to 2 maximum. Original Don the Beachcomber rule. Use quality rums for best results. The exact "Don''s Mix" recipe varies - this is the modern IBA standard.', 'high', 70, 'https://iba-world.com/zombie/', 'IBA Official Recipe. Original recipe by Donn Beach.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 76. Barracuda


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('802b8de2-0f13-4725-adbc-e5245822eb6f', 'barracuda', 'd4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3', '{"en":"Barracuda"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","rum","tropical","sparkling","refreshing"}', '{"en":"A tropical sparkling cocktail combining gold rum with pineapple, lime, and Galliano, topped with sparkling wine. Refreshing and elegant with a perfect balance of tropical fruit and effervescence."}'::jsonb, '{"created_year":"1980","origin":{"city":"Unknown","bar":"Unknown","country":"Unknown"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Barracuda emerged in the 1980s as a tropical variation on the classic Champagne cocktail. Its combination of rum, pineapple, and sparkling wine made it popular in beach resorts and tropical destinations. The addition of Galliano adds a distinctive herbal-vanilla note that sets it apart from simpler tropical drinks."},"named_after":{"en":"Named after the barracuda fish, known for being swift and striking - qualities that match the drink''s refreshing and bold character."}}'::jsonb, '{"profile":["tropical","sparkling","fruity"],"description":{"en":"Tropical pineapple and lime juice balanced with rum warmth, herbal Galliano notes, and celebratory sparkling wine. Light, refreshing, and sophisticated."},"first_impression":{"en":"Bright tropical fruit with sparkling effervescence"},"finish":{"en":"Clean, crisp finish with lingering vanilla and herbal notes"},"balance":{"en":"Perfectly balanced between tropical sweetness, citrus tartness, and sparkling wine elegance"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["celebration","party","brunch","beach"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with tropical fruit platters, seafood dishes, grilled fish, or as a celebratory aperitif."},"ideal_for":{"en":"Perfect for those who enjoy tropical flavors with an elegant twist. Ideal for celebrations or anyone seeking a sophisticated beach cocktail."}}'::jsonb, '[{"ingredient_id":"ING_RUM_GOLD","quantity":{"amount":45,"unit":"ml"},"display_name":"Gold rum","notes":null},{"ingredient_id":"ING_GALLIANO","quantity":{"amount":15,"unit":"ml"},"display_name":"Galliano","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":60,"unit":"ml"},"display_name":"Pineapple juice","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_PROSECCO","quantity":{"amount":60,"unit":"ml"},"display_name":"Prosecco","notes":null}]'::jsonb, 'shake', '{"en":"Shake rum, Galliano, pineapple juice, and lime juice with ice. Strain into a highball glass filled with ice. Top with Prosecco."}'::jsonb, 'Highball glass', '{"en":"Pineapple wedge and cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_RUM_GOLD"}', '{"tropical","sparkling","fruity"}', 12, 210, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"celebration","party","brunch"}', false, false, '{}', 'Add Prosecco last to preserve carbonation. Use fresh pineapple juice for best results. Can substitute Champagne for Prosecco.', 'mid', 65, 'https://iba-world.com/barracuda/', 'IBA Official Recipe', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 77. Bee's Knees


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('fde8c68a-53d6-4a58-a1dc-36a00c42811f', 'bees-knees', 'b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3', '{"en":"Bee''s Knees"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","gin","honey","prohibition","classic"}', '{"en":"A Prohibition-era classic combining gin with honey and lemon. This simple yet sophisticated cocktail features floral honey sweetness balanced by bright citrus - it''s truly \"the bee''s knees!\""}'::jsonb, '{"created_year":"1920","origin":{"city":"Unknown","bar":"Unknown","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Bee''s Knees emerged during Prohibition in the 1920s. The name comes from a popular slang expression of that era meaning \"the best\" or \"the height of excellence.\" During Prohibition, honey was often used to mask the harsh flavor of bathtub gin. The cocktail gained renewed popularity during the craft cocktail revival of the 2000s, appreciated for its simple elegance and historical significance."},"named_after":{"en":"Named after the 1920s slang phrase \"the bee''s knees,\" meaning something excellent or outstanding."}}'::jsonb, '{"profile":["floral","citrus","smooth"],"description":{"en":"Bright lemon tartness balanced by floral honey sweetness and gin botanicals. Smooth, refreshing, and perfectly balanced with a silky texture from the honey."},"first_impression":{"en":"Bright lemon with floral honey and gin botanicals"},"finish":{"en":"Smooth, lingering finish with honey sweetness and gin complexity"},"balance":{"en":"Perfectly balanced between lemon tartness, honey sweetness, and gin dryness"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["brunch","garden_party","afternoon_tea","date_night"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with light salads, goat cheese, honey-glazed appetizers, or afternoon tea sandwiches."},"ideal_for":{"en":"Perfect for gin lovers who enjoy smooth, citrusy cocktails. Ideal for those interested in Prohibition-era classics or anyone seeking a sophisticated yet simple drink."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":50,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":25,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_HONEY_SYRUP","quantity":{"amount":12.5,"unit":"ml"},"display_name":"Honey syrup","notes":null}]'::jsonb, 'shake', '{"en":"Shake all ingredients with ice. Strain into a chilled cocktail glass."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"Lemon twist"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"floral","citrus","smooth"}', 18, 160, 'easy', 45, '{}', '{"alcohol"}', '{"vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","gluten-free","dairy-free"}', '{"spring","summer"}', '{"brunch","garden_party","date_night"}', false, false, '{}', 'Use honey syrup (3:1 honey to water) for easier mixing. Shake vigorously to properly emulsify the honey. Quality honey makes a big difference.', 'mid', 70, 'https://iba-world.com/bees-knees/', 'IBA Official Recipe', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 78. Bramble


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('53dfc02d-1d4f-46d0-bb58-9c81fefa4ba6', 'bramble', 'd0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9', '{"en":"Bramble"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","gin","blackberry","british","fruity"}', '{"en":"A modern British classic combining gin with fresh lemon juice and crème de mûre (blackberry liqueur). This elegant cocktail features a beautiful berry cascade and perfectly balanced sweet-tart flavors."}'::jsonb, '{"created_year":"1984","origin":{"city":"London","bar":"Fred''s Club","country":"UK"},"creator":{"name":"Dick Bradsell","profession":"bartender"},"story":{"en":"Created in 1984 by legendary bartender Dick Bradsell at Fred''s Club in London. Inspired by his memories of picking wild blackberries on the Isle of Wight as a child, Bradsell created this gin cocktail that celebrates British ingredients and flavors. The drink became one of the defining cocktails of the modern British cocktail renaissance and showcases Bradsell''s talent for creating accessible yet sophisticated drinks."},"named_after":{"en":"Named after bramble bushes, the thorny plants that produce blackberries in the British countryside."}}'::jsonb, '{"profile":["fruity","tart","refreshing"],"description":{"en":"Bright gin botanicals with tart lemon and sweet blackberry liqueur. The berry flavor adds depth while maintaining refreshing citrus notes. Complex and beautifully balanced."},"first_impression":{"en":"Bright gin and lemon with sweet blackberry undertones"},"finish":{"en":"Long finish with lingering berry sweetness and gin botanicals"},"balance":{"en":"Perfectly balanced between gin dryness, lemon tartness, and blackberry sweetness"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["garden_party","brunch","date_night","summer_gathering"],"seasons":["summer","spring","autumn"],"food_pairings":{"en":"Excellent with British afternoon tea, scones with clotted cream, berry desserts, or light salads."},"ideal_for":{"en":"Perfect for gin lovers who enjoy fruity, refreshing cocktails. Ideal for those seeking a sophisticated yet approachable British classic."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":40,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":25,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":12.5,"unit":"ml"},"display_name":"Simple syrup","notes":null},{"ingredient_id":"ING_CREME_DE_MURE","quantity":{"amount":15,"unit":"ml"},"display_name":"Crème de mûre","notes":null}]'::jsonb, 'build', '{"en":"Build gin, lemon juice, and simple syrup in a rocks glass filled with crushed ice. Stir gently. Drizzle crème de mûre over the top to create a \"bleeding\" effect."}'::jsonb, 'Rocks glass', '{"en":"Fresh blackberries and lemon slice"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_GIN"}', '{"fruity","tart","refreshing"}', 15, 190, 'easy', 45, '{}', '{"alcohol"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"summer","spring","autumn"}', '{"garden_party","brunch","date_night"}', false, false, '{"bramble-royale"}', 'Drizzle crème de mûre slowly over crushed ice to create the signature "bleeding" cascade effect. Fresh blackberries enhance presentation.', 'mid', 75, 'https://iba-world.com/bramble/', 'IBA Official Recipe', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 79. Canchánchara


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('1fb026fe-d471-4fde-9488-6fa2e2308c2d', 'canchanchara', 'f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5', '{"en":"Canchánchara"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","rum","cuban","historical","simple"}', '{"en":"One of Cuba''s oldest cocktails, the Canchánchara is a simple yet historic blend of rum, honey, and lime. This rustic drink was the precursor to the Daiquiri and remains a beloved Cuban classic."}'::jsonb, '{"created_year":"1868","origin":{"city":"Trinidad","bar":"Unknown","country":"Cuba"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Canchánchara dates back to the Cuban War of Independence (1868-1878). Cuban independence fighters, known as \"mambises,\" would mix aguardiente (a raw rum-like spirit), honey, and lime juice as both refreshment and medicine. The drink is named after a traditional Cuban song and dance. It became popular in Trinidad, Cuba, where it''s still served in traditional clay cups called \"jícaras.\""},"named_after":{"en":"Named after a traditional Cuban song and dance from the independence era."}}'::jsonb, '{"profile":["sweet","citrus","simple"],"description":{"en":"Rustic and straightforward with natural honey sweetness, bright lime tartness, and the raw character of aguardiente or light rum. Simple yet perfectly balanced."},"first_impression":{"en":"Bright lime and honey sweetness with rum warmth"},"finish":{"en":"Clean, sweet finish with lingering honey and citrus notes"},"balance":{"en":"Perfectly balanced between honey sweetness and lime tartness"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["casual","historical_tasting","beach","party"],"seasons":["summer","spring"],"food_pairings":{"en":"Excellent with Cuban cuisine, grilled pork, plantains, or traditional Cuban sandwiches."},"ideal_for":{"en":"Perfect for rum enthusiasts interested in cocktail history. Ideal for those who appreciate simple, rustic drinks with authentic Cuban heritage."}}'::jsonb, '[{"ingredient_id":"ING_RUM_LIGHT","quantity":{"amount":60,"unit":"ml"},"display_name":"Light rum","notes":null},{"ingredient_id":"ING_HONEY","quantity":{"amount":20,"unit":"ml"},"display_name":"Honey","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":20,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_WATER","quantity":{"amount":30,"unit":"ml"},"display_name":"Water","notes":null}]'::jsonb, 'stir', '{"en":"Mix honey with water and lime juice in a traditional clay cup or rocks glass. Add rum and stir well. Add ice if desired."}'::jsonb, 'Rocks glass (or traditional clay cup)', '{"en":"Lime wedge"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_RUM_LIGHT"}', '{"sweet","citrus","simple"}', 18, 150, 'easy', 30, '{}', '{"alcohol"}', '{"vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","gluten-free","dairy-free"}', '{"summer","spring"}', '{"casual","beach","party"}', false, false, '{}', 'Traditionally served in clay cups called "jícaras." Use raw honey for authentic flavor. Can be served with or without ice.', 'low', 50, 'https://iba-world.com/canchanchara/', 'IBA Official Recipe', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 80. Chartreuse Swizzle


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('d91962e8-ec7f-4e51-98bd-9f56e324fcdb', 'chartreuse-swizzle', 'd9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8', '{"en":"Chartreuse Swizzle"}'::jsonb, 'iba_official', 'NewEraDrinks', '{"iba","official","modern","tiki","herbal","refreshing","swizzle"}', '{"en":"A modern tiki classic featuring the herbaceous complexity of Green Chartreuse swizzled with pineapple, lime, and falernum over crushed ice. This refreshing cocktail combines Caribbean swizzle tradition with French herbal liqueur sophistication."}'::jsonb, '{"created_year":"2004","origin":{"city":"San Francisco","bar":"Alembic","country":"USA"},"creator":{"name":"Marcovaldo Dionysos","profession":"bartender"},"story":{"en":"Created by Marcovaldo Dionysos at the Alembic bar in San Francisco around 2004. The drink was inspired by classic Caribbean swizzles but substitutes Green Chartreuse for rum, creating a more herbaceous and complex profile. The swizzle technique, using a traditional swizzle stick or bar spoon, aerates the drink and creates a frosty, diluted consistency perfect for sipping. The cocktail gained popularity during the tiki revival of the 2000s."},"named_after":{"en":"Named for the \"swizzle\" technique of rapidly rotating a stick or spoon in crushed ice to chill and dilute the drink, combined with the dominant Chartreuse flavor."}}'::jsonb, '{"profile":["herbal","tropical","complex","refreshing"],"description":{"en":"Intensely herbaceous with Green Chartreuse''s 130 botanical complexity balanced by tropical pineapple sweetness, tart lime, and aromatic falernum spices. The swizzle dilution makes it remarkably smooth and refreshing."},"first_impression":{"en":"Bold herbal Chartreuse with tropical pineapple and lime brightness"},"finish":{"en":"Long, complex finish with lingering herbal notes and tropical warmth"},"balance":{"en":"Masterfully balanced between intense herbal complexity and tropical fruit sweetness"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["tiki_party","garden_party","special_occasion","summer_gathering"],"seasons":["spring","summer"],"food_pairings":{"en":"Pairs well with Caribbean jerk dishes, grilled seafood, Thai cuisine, tropical fruits, and herb-crusted meats."},"ideal_for":{"en":"Perfect for adventurous drinkers who love herbal complexity in tropical cocktails. Ideal for Chartreuse enthusiasts and those seeking a sophisticated tiki experience. Great for hot weather sipping."}}'::jsonb, '[{"ingredient_id":"ING_CHARTREUSE_GREEN","quantity":{"amount":45,"unit":"ml"},"display_name":"Green Chartreuse","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Pineapple juice","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_FALERNUM","quantity":{"amount":15,"unit":"ml"},"display_name":"Falernum","notes":null}]'::jsonb, 'swizzle', '{"en":"Add all ingredients to a Collins or highball glass. Fill with crushed ice. Insert a swizzle stick or bar spoon and rapidly rotate between your palms for 10-15 seconds until the outside of the glass frosts. Top with more crushed ice to form a snow cone. Garnish with a pineapple frond and fresh mint sprig."}'::jsonb, 'Collins or Highball glass', '{"en":"Pineapple frond and fresh mint sprig"}'::jsonb, 'crushed', 'swizzle', '{"ING_CHARTREUSE_GREEN"}', '{"herbal","tropical","complex","refreshing"}', 14, 210, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 1, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"party","special_occasion"}', false, false, '{"yellow-chartreuse-swizzle","rum-chartreuse-swizzle"}', 'Green Chartreuse is essential (55% ABV). Proper swizzle technique creates frost on outside of glass. Use plenty of crushed ice. Falernum adds essential spice notes. Fresh pineapple juice preferred.', 'premium', 70, 'https://iba-world.com/chartreuse-swizzle/', 'IBA Official Recipe. Created by Marcovaldo Dionysos at Alembic, San Francisco.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


