INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('a1a4a74e-4e29-4f21-9cbd-b801e72be993', 'bellini', 'bellini_iba_contemporary_classic', '{"en":"Bellini"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","italian","brunch","elegant","prosecco","peach"}', '{"en":"Venice''s signature cocktail - an elegant blend of white peach purée and Prosecco. Light, refreshing, and quintessentially Italian, the Bellini is the perfect celebration of summer''s finest peaches."}'::jsonb, '{"created_year":"1948","origin":{"city":"Venice","bar":"Harry''s Bar","country":"Italy"},"creator":{"name":"Giuseppe Cipriani","profession":"bartender"},"story":{"en":"Created by Giuseppe Cipriani, founder of the legendary Harry''s Bar in Venice, between 1934-1948. The drink was named after the 15th-century Venetian artist Giovanni Bellini, as the pink color of the drink reminded Cipriani of a toga in one of Bellini''s paintings. It became the signature drink of Harry''s Bar and spread worldwide."},"named_after":{"en":"Named after the 15th-century Venetian painter Giovanni Bellini, inspired by the pink color of his paintings."}}'::jsonb, '{"profile":["fruity","delicate","sparkling"],"description":{"en":"Delicate, fruity, and effervescent. Fresh white peach purée provides natural sweetness and aroma, while Prosecco adds elegant bubbles and crisp dryness. Light, sophisticated, and incredibly refreshing."},"first_impression":{"en":"Delicate white peach with elegant Prosecco bubbles"},"finish":{"en":"Clean, refreshing finish with lingering peach notes"},"balance":{"en":"Perfectly balanced between peach sweetness and Prosecco dryness"}}'::jsonb, '{"best_time":["morning","afternoon"],"occasions":["brunch","celebration","wedding","summer_gathering"],"seasons":["summer"],"food_pairings":{"en":"Perfect with brunch dishes, Italian appetizers, prosciutto, fresh fruits, and light pastries. Ideal for summer celebrations."},"ideal_for":{"en":"Perfect for brunch lovers and those who appreciate elegant, light cocktails. Ideal for Prosecco enthusiasts and Italian cuisine lovers."}}'::jsonb, '[{"ingredient_id":"ING_PROSECCO","quantity":{"amount":100,"unit":"ml"},"display_name":"Prosecco","notes":null},{"ingredient_id":"ING_WHITE_PEACH_PUREE","quantity":{"amount":50,"unit":"ml"},"display_name":"White peach purée","notes":null}]'::jsonb, 'build', '{"en":"Pour peach purée into a chilled champagne flute. Gently top with chilled Prosecco. Stir gently and briefly. No garnish required, or optionally add a peach slice."}'::jsonb, 'Champagne flute', '{"en":"None (or optional peach slice)"}'::jsonb, 'none', 'up', '{"ING_PROSECCO"}', '{"fruity","delicate","sparkling"}', 7, 120, 'easy', 30, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"summer"}', '{"brunch","celebration","wedding","summer_gathering"}', false, false, '{"rossini","puccini","tintoretto"}', 'Traditionally made with white peaches (pesca bianca), which are in season in summer. Fresh peach purée is essential - avoid commercial peach nectar. The Rossini uses strawberry purée, Puccini uses tangerine juice. Prosecco should be well-chilled. Build gently to preserve bubbles.', 'mid', 85, 'https://iba-world.com/bellini/', 'IBA Official Recipe. Created at Harry''s Bar, Venice.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 42. Black Russian


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('7924dad6-510c-4a86-a703-bc0e530a81e3', 'black-russian', 'black_russian_iba_contemporary_classic', '{"en":"Black Russian"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","simple","coffee","after-dinner","spirit-forward"}', '{"en":"A simple yet sophisticated cocktail combining vodka with coffee liqueur. Strong, smooth, and dangerously easy-drinking - the Black Russian is the perfect after-dinner indulgence."}'::jsonb, '{"created_year":"1949","origin":{"city":"Brussels","bar":"Hotel Metropole","country":"Belgium"},"creator":{"name":"Gustave Tops","profession":"bartender"},"story":{"en":"Created by bartender Gustave Tops at the Hotel Metropole in Brussels, Belgium in 1949. It was created for Perle Mesta, the U.S. Ambassador to Luxembourg. The drink gained popularity during the Cold War era, and its name reflects the Russian origins of vodka. The White Russian variation (adding cream) came later."},"named_after":{"en":"Named \"Black Russian\" for the Russian origins of vodka and the dark color from coffee liqueur."}}'::jsonb, '{"profile":["coffee","sweet","boozy"],"description":{"en":"Rich coffee flavor with smooth vodka backbone. Kahlúa provides sweet coffee notes while vodka adds clean strength. Smooth, slightly sweet, and deceptively strong."},"first_impression":{"en":"Sweet coffee with smooth vodka strength"},"finish":{"en":"Long, warming finish with lingering coffee notes"},"balance":{"en":"Well-balanced between sweet coffee liqueur and clean vodka"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["after-dinner","nightcap","digestivo","casual"],"seasons":["autumn","winter","spring","summer"],"food_pairings":{"en":"Perfect after dinner or with desserts, especially chocolate, tiramisu, or coffee-flavored sweets."},"ideal_for":{"en":"Perfect for coffee and vodka lovers seeking a simple, strong cocktail. Ideal for those who prefer spirit-forward drinks."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":50,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_COFFEE_LIQUEUR","quantity":{"amount":20,"unit":"ml"},"display_name":"Coffee liqueur (Kahlúa)","notes":null}]'::jsonb, 'build', '{"en":"Pour ingredients into an old fashioned glass filled with ice cubes. Stir gently. No garnish required."}'::jsonb, 'Old Fashioned glass', '{"en":"None"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA"}', '{"coffee","sweet","boozy"}', 28, 220, 'easy', 30, '{"sulphites"}', '{"alcohol","sulphites_intolerance","caffeine"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring","summer"}', '{"after-dinner","nightcap","digestivo","casual"}', false, false, '{"white-russian","dirty-russian","blind-russian"}', 'Simple two-ingredient build. The White Russian adds cream on top. Kahlúa is the traditional coffee liqueur, but any good coffee liqueur works. Can be served neat or on the rocks. Deceptively strong - warn guests.', 'low', 70, 'https://iba-world.com/black-russian/', 'IBA Official Recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 43. Bloody Mary


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('7cb9421d-e800-4ece-b9a6-67186eba7f52', 'bloody-mary', 'bloody_mary_iba_contemporary_2025', '{"en":"Bloody Mary"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","savory","brunch","spicy","complex"}', '{"en":"The ultimate brunch cocktail, combining vodka with tomato juice, lemon juice, and savory spices. Famous for its complex, savory flavor and reputation as a hangover cure. Endlessly customizable with garnishes."}'::jsonb, '{"created_year":"1921","origin":{"city":"Paris","bar":"Harry''s New York Bar","country":"France"},"creator":{"name":"Fernand Petiot","profession":"bartender"},"story":{"en":"Created by Fernand Petiot at Harry''s New York Bar in Paris in 1921, mixing vodka with tomato juice. When Petiot moved to New York''s King Cole Bar in the 1930s, he refined the recipe with spices, creating the modern Bloody Mary. The drink became synonymous with brunch culture and hangover remedies."},"named_after":{"en":"Named after Queen Mary I of England (aka \"Bloody Mary\") or a waitress named Mary at a Chicago bar. Origins are disputed."}}'::jsonb, '{"profile":["savory","spicy","umami","citrus"],"description":{"en":"Complex, savory, and thoroughly unique among cocktails. Tomato juice provides umami richness, lemon adds brightness, Worcestershire and Tabasco create depth and heat, while celery salt ties everything together."},"first_impression":{"en":"Savory tomato with immediate spice and acidity"},"finish":{"en":"Long, savory finish with lingering heat and umami"},"balance":{"en":"Complex balance of savory, spicy, sour, and salty elements"}}'::jsonb, '{"best_time":["brunch","morning","afternoon"],"occasions":["brunch","casual","recovery"],"seasons":["all_seasons"],"food_pairings":{"en":"Perfect with brunch dishes: eggs Benedict, bacon, breakfast sandwiches, oysters, shrimp cocktail. Often served as a meal replacement with elaborate garnishes."},"ideal_for":{"en":"Perfect for brunch lovers and those who appreciate savory cocktails. Famous as a hangover remedy. Not for those who prefer sweet drinks."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":45,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_TOMATO_JUICE","quantity":{"amount":90,"unit":"ml"},"display_name":"Tomato juice","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_WORCESTERSHIRE","quantity":{"amount":2,"unit":"dash"},"display_name":"Worcestershire sauce","notes":null},{"ingredient_id":"ING_TABASCO","quantity":{"amount":2,"unit":"dash"},"display_name":"Tabasco sauce","notes":null},{"ingredient_id":"ING_CELERY_SALT","quantity":{"amount":1,"unit":"pinch"},"display_name":"Celery salt","notes":null},{"ingredient_id":"ING_BLACK_PEPPER","quantity":{"amount":1,"unit":"pinch"},"display_name":"Black pepper","notes":null}]'::jsonb, 'roll', '{"en":"Pour all ingredients into a highball glass. Roll gently (pour back and forth between glasses). Garnish with celery stalk and lemon wedge. Season to taste."}'::jsonb, 'Highball glass', '{"en":"Celery stalk and lemon wedge"}'::jsonb, 'cubes', 'built', '{"ING_VODKA"}', '{"savory","spicy","umami","citrus"}', 12, 125, 'easy', 60, '{"sulphites","celery","fish"}', '{"alcohol","sulphites_intolerance","nightshades","histamine"}', '{"vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 2, '{"vegetarian","gluten-free","dairy-free"}', '{"all_seasons"}', '{"brunch","casual","recovery"}', false, false, '{"virgin-mary","bloody-caesar","red-snapper","michelada"}', 'Highly customizable - ask customer about spice preference. Common garnishes include bacon, shrimp, pickles, olives, cheese. Rolling (not shaking) preserves texture. Worcestershire contains anchovies (not vegetarian).', 'low', 90, 'https://iba-world.com/bloody-mary/', 'IBA Official Recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 44. Caipirinha


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('4670d6bd-acf2-4c40-aaf7-2f2f5ea9a8ce', 'caipirinha', 'caipirinha_iba_contemporary_2025', '{"en":"Caipirinha"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","brazilian","refreshing","summer","simple"}', '{"en":"Brazil''s national cocktail, made with cachaça, lime, and sugar. Refreshingly simple yet complex, the Caipirinha showcases cachaça''s grassy, vegetal character. A perfect beach drink that embodies Brazilian spirit."}'::jsonb, '{"created_year":"1918","origin":{"city":"São Paulo","country":"Brazil"},"story":{"en":"The Caipirinha originated in the state of São Paulo in the early 20th century, possibly as a medicinal remedy during the Spanish flu pandemic of 1918. Originally made with garlic, honey, and lime to cure illness, it evolved into the refreshing cocktail we know today. The name comes from \"caipira,\" meaning countryside person or hillbilly in Portuguese. It became Brazil''s national cocktail and gained worldwide popularity in the 1990s."},"named_after":{"en":"Named after \"caipira,\" a Portuguese word for countryside person or rural dweller."}}'::jsonb, '{"profile":["citrus","sweet","refreshing","grassy"],"description":{"en":"Fresh, bright, and incredibly refreshing. Muddled lime releases essential oils and juice, cachaça provides grassy, vegetal notes with slight funk, and sugar balances the acidity. Simple ingredients create complex flavor."},"first_impression":{"en":"Bright lime with grassy cachaça notes"},"finish":{"en":"Clean, refreshing finish with lingering citrus and sugar"},"balance":{"en":"Perfectly balanced between tart lime and sweet sugar"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["beach","party","casual","celebration"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with Brazilian churrasco, feijoada, grilled meats, seafood, ceviche, and spicy foods. Excellent with beach snacks and BBQ."},"ideal_for":{"en":"Perfect for anyone who loves fresh, citrus-forward cocktails. Ideal for beach days and summer parties. Great introduction to cachaça."}}'::jsonb, '[{"ingredient_id":"ING_CACHACA","quantity":{"amount":60,"unit":"ml"},"display_name":"Cachaça","notes":null},{"ingredient_id":"ING_LIME","quantity":{"amount":1,"unit":"whole"},"display_name":"Lime","notes":null},{"ingredient_id":"ING_SUGAR","quantity":{"amount":2,"unit":"tsp"},"display_name":"White sugar","notes":null}]'::jsonb, 'muddle', '{"en":"Place lime wedges and sugar in an Old Fashioned glass. Muddle gently to release lime juice and oils. Fill glass with crushed ice. Add cachaça and stir well. Serve with a straw."}'::jsonb, 'Old Fashioned glass', '{"en":"Lime wedge"}'::jsonb, 'crushed', 'built', '{"ING_CACHACA"}', '{"citrus","sweet","refreshing","grassy"}', 18, 180, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"beach","party","casual","celebration"}', false, false, '{"caipiroska","caipifruta","caipirissima"}', 'Muddle gently - don''t pulverize the lime or it becomes bitter. Use fresh limes only. Crushed ice is traditional and essential for proper dilution. Quality cachaça makes a huge difference.', 'low', 88, 'https://iba-world.com/caipirinha/', 'IBA Official Recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 45. Cardinale


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('d792dbdf-e840-4956-bc2c-415c7a023119', 'cardinale', 'cardinale_iba_contemporary_classic', '{"en":"Cardinale"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","italian","aperitif","bitter","elegant"}', '{"en":"An elegant Italian aperitivo combining gin, dry vermouth, and Campari. Bitter, complex, and sophisticated - a variation of the classic Negroni that showcases Italian aperitif culture."}'::jsonb, '{"created_year":"1950","origin":{"city":"Rome","bar":"Unknown","country":"Italy"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Cardinale is a variation of the Negroni that emerged in Italy in the 1950s. It uses dry vermouth instead of sweet vermouth, creating a drier, more sophisticated profile. The name \"Cardinale\" (Cardinal) refers to the drink''s deep red color, reminiscent of a Catholic cardinal''s robes."},"named_after":{"en":"Named after Catholic cardinals, whose red robes match the drink''s deep red color."}}'::jsonb, '{"profile":["bitter","dry","herbal"],"description":{"en":"Dry, bitter, and complex. Campari provides distinctive bitter orange notes, dry vermouth adds herbal complexity, and gin brings botanical depth. More sophisticated and drier than a Negroni."},"first_impression":{"en":"Bitter Campari with dry herbal notes and gin botanicals"},"finish":{"en":"Long, dry finish with lingering bitter and herbal notes"},"balance":{"en":"Well-balanced between Campari bitterness and dry vermouth complexity"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["aperitif","italian_dining","sophisticated_gathering"],"seasons":["spring","summer","autumn","winter"],"food_pairings":{"en":"Perfect as an aperitivo before Italian meals. Pairs well with antipasti, olives, cured meats, and aged cheeses."},"ideal_for":{"en":"Perfect for Negroni lovers seeking a drier variation. Ideal for those who appreciate bitter Italian aperitifs and sophisticated cocktails."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":30,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_DRY_VERMOUTH","quantity":{"amount":30,"unit":"ml"},"display_name":"Dry vermouth","notes":null},{"ingredient_id":"ING_CAMPARI","quantity":{"amount":30,"unit":"ml"},"display_name":"Campari","notes":null}]'::jsonb, 'stir', '{"en":"Pour all ingredients into a mixing glass filled with ice cubes. Stir well. Strain into a chilled cocktail glass. Garnish with an orange twist."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"Orange twist"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"bitter","dry","herbal"}', 28, 180, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer","autumn","winter"}', '{"aperitif","italian_dining","sophisticated_gathering"}', false, false, '{"negroni","boulevardier","old-pal"}', 'A drier variation of the Negroni using dry vermouth instead of sweet. Equal parts of all three ingredients. Stir, don''t shake. Can also be served on the rocks in an old fashioned glass. Express orange oils over the drink before garnishing.', 'mid', 55, 'https://iba-world.com/cardinale/', 'IBA Official Recipe. A drier variation of the Negroni.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 46. Champagne Cocktail


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('f1140af4-efb5-4df6-88f2-1a7eaba7d764', 'champagne-cocktail', 'champagne_cocktail_iba_contemporary_2025', '{"en":"Champagne Cocktail"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","champagne","elegant","celebratory","classic"}', '{"en":"An elegant classic combining champagne with a sugar cube, Angostura bitters, and cognac. Simple yet sophisticated, this drink elevates champagne with subtle sweetness and aromatic complexity. Perfect for celebrations."}'::jsonb, '{"created_year":"1862","origin":{"country":"USA"},"story":{"en":"The Champagne Cocktail first appeared in Jerry Thomas''s 1862 \"How to Mix Drinks\" bartending guide, making it one of the oldest recorded cocktails. It gained popularity in high society and became synonymous with elegance and celebration. The drink was famously enjoyed in the film \"Casablanca\" (1942) and has remained a symbol of sophistication ever since."},"named_after":{"en":"Named for its primary ingredient, champagne."}}'::jsonb, '{"profile":["bubbly","sweet","aromatic","elegant"],"description":{"en":"Elegant and effervescent. The sugar cube slowly dissolves, creating a gradient of sweetness. Angostura bitters add aromatic spice, cognac provides depth, and champagne delivers crisp bubbles. A refined drinking experience."},"first_impression":{"en":"Aromatic bitters and champagne bubbles"},"finish":{"en":"Clean, crisp finish with lingering aromatic notes"},"balance":{"en":"Well-balanced between champagne dryness and subtle sweetness"}}'::jsonb, '{"best_time":["aperitivo","evening"],"occasions":["celebration","wedding","new_years","formal_event"],"seasons":["all_seasons"],"food_pairings":{"en":"Perfect with oysters, caviar, canapés, smoked salmon, or light appetizers. Excellent for toasting special occasions."},"ideal_for":{"en":"Perfect for celebrations, weddings, New Year''s Eve, and formal events. Ideal for those who appreciate elegant, classic cocktails."}}'::jsonb, '[{"ingredient_id":"ING_CHAMPAGNE","quantity":{"amount":90,"unit":"ml"},"display_name":"Champagne","notes":null},{"ingredient_id":"ING_COGNAC","quantity":{"amount":10,"unit":"ml"},"display_name":"Cognac","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":2,"unit":"dash"},"display_name":"Angostura bitters","notes":null},{"ingredient_id":"ING_SUGAR_CUBE","quantity":{"amount":1,"unit":"cube"},"display_name":"Sugar cube","notes":null}]'::jsonb, 'build', '{"en":"Place sugar cube in a chilled champagne flute. Saturate the sugar cube with Angostura bitters. Add cognac. Top with chilled champagne. Garnish with orange twist or lemon twist."}'::jsonb, 'Champagne flute', '{"en":"Orange twist or lemon twist"}'::jsonb, 'none', 'built', '{"ING_CHAMPAGNE","ING_COGNAC"}', '{"bubbly","sweet","aromatic","elegant"}', 13, 120, 'easy', 30, '{"sulphites"}', '{"alcohol","sulphites_intolerance","histamine"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"all_seasons"}', '{"celebration","wedding","new_years","formal_event"}', false, false, '{"seelbach-cocktail","champagne-royale"}', 'Use quality champagne or good sparkling wine. Saturate sugar cube fully with bitters for best flavor. Build directly in flute to preserve bubbles. Can substitute brandy for cognac if needed.', 'high', 75, 'https://iba-world.com/champagne-cocktail/', 'IBA Official Recipe. First recorded in Jerry Thomas 1862.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 47. Corpse Reviver #2


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('f09794a2-1350-4885-a213-39cd847345a3', 'corpse-reviver-2', 'corpse_reviver_2_iba_contemporary_2025', '{"en":"Corpse Reviver #2"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","classic","brunch","complex","citrus"}', '{"en":"A sophisticated \"hair of the dog\" cocktail combining gin, Cointreau, Lillet Blanc, lemon juice, and a hint of absinthe. Complex, citrus-forward, and refreshing, this drink was designed to cure hangovers and \"revive corpses.\""}'::jsonb, '{"created_year":"1930","origin":{"city":"London","bar":"Savoy Hotel","country":"England"},"creator":{"name":"Harry Craddock","profession":"bartender"},"story":{"en":"Featured in Harry Craddock''s 1930 \"The Savoy Cocktail Book,\" the Corpse Reviver #2 is part of a family of \"corpse reviver\" cocktails meant to cure hangovers. Craddock warned: \"Four of these taken in swift succession will unrevive the corpse again.\" It fell into obscurity but was revived (ironically) during the 2000s cocktail renaissance and is now a modern classic."},"named_after":{"en":"Named for its supposed ability to \"revive corpses\" or cure hangovers. The \"#2\" distinguishes it from other Corpse Reviver variations."}}'::jsonb, '{"profile":["citrus","herbal","complex","refreshing"],"description":{"en":"Bright, complex, and thoroughly refreshing. Lemon provides tartness, Cointreau adds orange sweetness, Lillet brings floral notes, gin provides botanical complexity, and absinthe adds an enigmatic anise touch. Perfectly balanced."},"first_impression":{"en":"Bright citrus with herbal, anise undertones"},"finish":{"en":"Clean, crisp finish with lingering absinthe complexity"},"balance":{"en":"Perfectly balanced between sweet, sour, and herbal elements"}}'::jsonb, '{"best_time":["brunch","afternoon"],"occasions":["brunch","recovery","casual"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect for brunch with eggs, smoked salmon, or light seafood. Excellent before lunch as an aperitif."},"ideal_for":{"en":"Perfect for brunch, morning-after recovery, or anyone who appreciates complex, citrus-forward cocktails. Great introduction to absinthe."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_COINTREAU","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Cointreau","notes":null},{"ingredient_id":"ING_LILLET_BLANC","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Lillet Blanc","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_ABSINTHE","quantity":{"amount":1,"unit":"dash"},"display_name":"Absinthe","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into shaker with ice. Shake well. Strain into chilled cocktail glass. Garnish with orange twist or cherry."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"Orange twist or cherry"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"citrus","herbal","complex","refreshing"}', 24, 160, 'medium', 90, '{"sulphites","wormwood"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"brunch","recovery","casual"}', false, false, '{"corpse-reviver-1","corpse-reviver-blue"}', 'Use absinthe VERY sparingly - a single dash only, or rinse glass and discard excess. Too much will overpower. Originally used Kina Lillet (no longer available) - Lillet Blanc is modern substitute. Historically a morning-after drink.', 'mid', 72, 'https://iba-world.com/corpse-reviver-2/', 'IBA Official Recipe. From The Savoy Cocktail Book 1930.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 48. Cosmopolitan


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('18d6b555-a91a-4108-8255-56d6a323d822', 'cosmopolitan', 'cosmopolitan_iba_contemporary_classic', '{"en":"Cosmopolitan"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","modern-classic","citrus","tart","elegant","iconic"}', '{"en":"The quintessential modern cocktail - vodka, Cointreau, cranberry, and lime in perfect harmony. Made famous by Sex and the City, the Cosmopolitan is sophisticated, pink, and utterly chic."}'::jsonb, '{"created_year":"1987","origin":{"city":"Miami / New York","bar":"Multiple claims","country":"USA"},"creator":{"name":"Toby Cecchini (popularized)","profession":"bartender"},"story":{"en":"While several bartenders claim to have invented the Cosmopolitan in the 1970s-80s, it was Toby Cecchini at The Odeon in Manhattan who created the modern version in 1987-88 using Absolut Citron. The drink exploded in popularity after being featured regularly on HBO''s Sex and the City (1998-2004), becoming synonymous with urban sophistication."},"named_after":{"en":"Named \"Cosmopolitan\" to evoke sophistication, worldliness, and urban elegance."}}'::jsonb, '{"profile":["citrus","tart","fruity"],"description":{"en":"Bright, tart, and perfectly balanced. Cranberry provides tartness and color, lime adds citrus zing, Cointreau brings orange sweetness, and vodka keeps it clean and crisp. Sophisticated and refreshing."},"first_impression":{"en":"Tart cranberry and bright citrus with orange notes"},"finish":{"en":"Clean, crisp finish with lingering citrus"},"balance":{"en":"Perfectly balanced between tart, sweet, and citrus"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["date_night","celebration","girls_night","cocktail_party"],"seasons":["spring","summer","autumn","winter"],"food_pairings":{"en":"Perfect with appetizers, sushi, seafood, light salads, and sophisticated finger foods."},"ideal_for":{"en":"Perfect for anyone seeking a sophisticated, stylish cocktail. The ultimate choice for cosmopolitan urbanites and cocktail connoisseurs."}}'::jsonb, '[{"ingredient_id":"ING_VODKA_CITRON","quantity":{"amount":40,"unit":"ml"},"display_name":"Vodka Citron","notes":null},{"ingredient_id":"ING_COINTREAU","quantity":{"amount":15,"unit":"ml"},"display_name":"Cointreau","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_CRANBERRY_JUICE","quantity":{"amount":30,"unit":"ml"},"display_name":"Cranberry juice","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice cubes. Shake well. Strain into a chilled cocktail glass. Garnish with a flamed orange peel or lime wheel."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"Flamed orange peel or lime wheel"}'::jsonb, 'none', 'up', '{"ING_VODKA_CITRON"}', '{"citrus","tart","fruity"}', 18, 160, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer","autumn","winter"}', '{"date_night","celebration","girls_night","cocktail_party"}', false, false, '{"metropolitan","flirtini","white-cosmopolitan"}', 'Use Absolut Citron or similar citrus vodka for authenticity. Fresh lime juice is essential. Shake hard for proper dilution. The drink should be a distinctive pink color. Flame the orange peel for added aromatics.', 'mid', 90, 'https://iba-world.com/cosmopolitan/', 'IBA Official Recipe. Made famous by Sex and the City.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 49. Cuba Libre


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('2fd916ac-c347-4fce-8b0f-f3dfa21f2a16', 'cuba-libre', 'cuba_libre_iba_contemporary_2025', '{"en":"Cuba Libre"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","refreshing","highball","easy","summer"}', '{"en":"A refreshing highball combining white rum, cola, and fresh lime juice. More than just a \"rum and coke,\" the Cuba Libre''s addition of lime transforms it into a balanced, citrus-forward cocktail with historical significance."}'::jsonb, '{"created_year":"1900","origin":{"city":"Havana","country":"Cuba"},"story":{"en":"The Cuba Libre was born during the Spanish-American War around 1900 in Havana. American soldiers mixed their Coca-Cola (newly arrived in Cuba) with local rum and lime, creating this iconic drink. The name means \"Free Cuba\" in Spanish, celebrating Cuba''s independence from Spain. The drink became a symbol of the Cuban independence movement and American-Cuban friendship of that era."},"named_after":{"en":"Named \"Cuba Libre\" (Free Cuba) to commemorate Cuba''s independence from Spain and the end of Spanish colonial rule."}}'::jsonb, '{"profile":["sweet","refreshing","citrus"],"description":{"en":"Refreshing and balanced. The sweetness of cola is lifted by bright lime acidity, while rum provides a smooth alcoholic backbone. The lime makes all the difference, elevating this beyond a simple mixed drink."},"first_impression":{"en":"Bright lime and cola sweetness hit immediately"},"finish":{"en":"Clean, refreshing finish with lingering citrus notes"},"balance":{"en":"Well-balanced between sweet cola, tart lime, and smooth rum"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["casual","party","beach","bbq"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with Cuban sandwiches, grilled meats, BBQ ribs, burgers, tacos, and spicy foods. The sweetness and citrus cut through rich, fatty foods beautifully."},"ideal_for":{"en":"Perfect for casual gatherings, beach parties, and anyone who wants an easy-drinking, refreshing cocktail. Great for those new to rum cocktails."}}'::jsonb, '[{"ingredient_id":"ING_RUM_WHITE","quantity":{"amount":50,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":12,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_COLA","quantity":{"amount":120,"unit":"ml"},"display_name":"Cola","notes":null}]'::jsonb, 'build', '{"en":"Build all ingredients in a highball glass filled with ice. Pour the lime juice and rum directly over ice, top with cola. Stir gently. Garnish with a lime wedge."}'::jsonb, 'Highball glass', '{"en":"Lime wedge"}'::jsonb, 'cubes', 'built', '{"ING_RUM_WHITE"}', '{"sweet","refreshing","citrus"}', 12, 180, 'easy', 30, '{"sulphites"}', '{"alcohol","caffeine","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"casual","party","beach","bbq"}', false, false, '{"rum-and-coke","cuba-libre-premium"}', 'The lime is what differentiates a Cuba Libre from a simple rum and coke - never skip it. Use fresh lime juice, not bottled. Build in glass to preserve carbonation. Mexican Coke (made with cane sugar) is preferred by some bartenders.', 'low', 95, 'https://iba-world.com/cuba-libre/', 'IBA Official Recipe. Historical information from Cuban cocktail history sources.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 50. French 75


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('fb973726-0961-4473-9804-45cdc9c8d58f', 'french-75', 'french_75_iba_contemporary_2025', '{"en":"French 75"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","champagne","elegant","celebratory","classic"}', '{"en":"A potent, elegant cocktail combining gin, lemon juice, sugar, and champagne. Named after the French 75mm field gun for its powerful kick, this drink is both sophisticated and dangerously smooth."}'::jsonb, '{"created_year":"1915","origin":{"city":"Paris","bar":"Harry''s New York Bar","country":"France"},"creator":{"name":"Harry MacElhone","profession":"bartender"},"story":{"en":"Created around 1915 at Harry''s New York Bar in Paris, though some credit the Buck''s Club in London. The drink was named after the French 75mm field gun used in WWI, suggesting its powerful alcoholic \"kick.\" It gained popularity among WWI soldiers and became a symbol of Parisian café culture. The drink has remained a classic celebration cocktail for over a century."},"named_after":{"en":"Named after the French 75mm field gun, one of the most famous artillery pieces of WWI, for its powerful alcoholic kick."}}'::jsonb, '{"profile":["citrus","bubbly","elegant","strong"],"description":{"en":"Bright, effervescent, and deceptively strong. Fresh lemon provides tartness, sugar balances acidity, gin adds botanical complexity, and champagne brings elegant bubbles. A perfect marriage of sour and sparkle."},"first_impression":{"en":"Bright lemon acidity with champagne bubbles"},"finish":{"en":"Clean, crisp finish with lingering botanical gin notes"},"balance":{"en":"Perfectly balanced between tart lemon and sweet champagne"}}'::jsonb, '{"best_time":["aperitivo","evening"],"occasions":["celebration","wedding","formal_event","brunch"],"seasons":["spring","summer","all_seasons"],"food_pairings":{"en":"Excellent with oysters, caviar, seafood, light appetizers, or French cuisine. Perfect for toasting celebrations."},"ideal_for":{"en":"Perfect for celebrations, weddings, and formal events. Great for those who love champagne cocktails with a citrus twist. Beware - it''s stronger than it tastes!"}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":30,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":15,"unit":"ml"},"display_name":"Simple syrup","notes":null},{"ingredient_id":"ING_CHAMPAGNE","quantity":{"amount":60,"unit":"ml"},"display_name":"Champagne","notes":null}]'::jsonb, 'shake', '{"en":"Pour gin, lemon juice, and simple syrup into shaker with ice. Shake well. Strain into champagne flute. Top with chilled champagne. Garnish with lemon twist."}'::jsonb, 'Champagne flute or Coupe', '{"en":"Lemon twist"}'::jsonb, 'none', 'up', '{"ING_GIN","ING_CHAMPAGNE"}', '{"citrus","bubbly","elegant","strong"}', 18, 140, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance","histamine"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer","all_seasons"}', '{"celebration","wedding","formal_event","brunch"}', false, false, '{"french-76","french-95"}', 'Shake gin/lemon/syrup first, then strain and top with champagne - don''t shake champagne. Use quality champagne or good sparkling wine. Can use cognac instead of gin for a "French 125". Strong drink - warn customers.', 'high', 82, 'https://iba-world.com/french-75/', 'IBA Official Recipe.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


