INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('435f00ec-c83d-4ed2-a695-1fd2a5262fb7', 'mary-pickford', 'e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4', '{"en":"Mary Pickford"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","tropical","prohibition-era","celebrity"}', '{"en":"A delightful Prohibition-era cocktail made with white rum, fresh pineapple juice, grenadine, and Maraschino liqueur. Named after \"America''s Sweetheart,\" silent film star Mary Pickford, this tropical drink is as charming and refreshing as its namesake."}'::jsonb, '{"created_year":"1920s","origin":{"city":"Havana","bar":"Hotel Nacional","country":"Cuba"},"creator":{"name":"Eddie Woelke or Fred Kaufman","profession":"bartender"},"story":{"en":"The Mary Pickford was created in the 1920s during Prohibition at the Hotel Nacional in Havana, Cuba - a popular destination for Americans escaping Prohibition. It was created for silent film star Mary Pickford during her visit to Cuba with husband Douglas Fairbanks. The bartenders, either Eddie Woelke or Fred Kaufman (sources vary), created this elegant tropical drink to honor \"America''s Sweetheart.\" The cocktail was included in the original 1961 IBA list of 50 official cocktails and has remained a classic ever since."},"named_after":{"en":"Named after Mary Pickford, the famous silent film actress known as \"America''s Sweetheart.\""}}'::jsonb, '{"profile":["tropical","sweet","fruity"],"description":{"en":"Bright and tropical with sweet pineapple leading the way, balanced by rum''s warmth and subtle cherry-almond notes from maraschino. Grenadine adds a hint of pomegranate sweetness and a beautiful pink hue."},"first_impression":{"en":"Sweet pineapple with a hint of cherry"},"finish":{"en":"Clean, fruity finish with lingering tropical notes"},"balance":{"en":"Well-balanced between sweet and fruity with subtle complexity"}}'::jsonb, '{"best_time":["afternoon","early_evening","poolside"],"occasions":["brunch","tropical_party","celebration","casual"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with tropical fruit, light seafood, grilled fish, or Asian-inspired appetizers. Pairs wonderfully with coconut shrimp, fish tacos, or fresh fruit salads."},"ideal_for":{"en":"Perfect for rum lovers and those who enjoy fruity, tropical cocktails. Ideal for anyone seeking a refreshing, easy-drinking cocktail with a touch of sophistication."}}'::jsonb, '[{"ingredient_id":"ING_WHITE_RUM","quantity":{"amount":45,"unit":"ml"},"display_name":"White rum","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":45,"unit":"ml"},"display_name":"Fresh pineapple juice","notes":null},{"ingredient_id":"ING_MARASCHINO","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Maraschino Luxardo","notes":null},{"ingredient_id":"ING_GRENADINE","quantity":{"amount":5,"unit":"ml"},"display_name":"Grenadine syrup","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"Maraschino cherry"}'::jsonb, 'none', 'up', '{"ING_WHITE_RUM"}', '{"tropical","sweet","fruity"}', 16, 170, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"brunch","tropical_party","celebration"}', false, false, '{"daiquiri","pina-colada","bacardi-cocktail"}', 'Use fresh pineapple juice for best results. The drink should have a beautiful pink color from the grenadine. Shake well to properly mix and chill. Often served with a cherry garnish in homage to the maraschino.', 'mid', 60, 'https://iba-world.com/iba-cocktail/mary-pickford/', 'IBA Official Recipe. Historical information from Hotel Nacional Havana and Prohibition-era cocktail history.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 22. Mint Julep


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('9cff54b8-2e46-46fa-b62e-88880c7683a8', 'mint-julep', 'mint_julep', '{"en":"Mint Julep"}'::jsonb, 'iba_official', 'Contemporary', '{"iba","official","classic","muddled","american","derby"}', '{"en":"The Mint Julep is an iconic Southern cocktail synonymous with the Kentucky Derby. Built in a traditional julep cup, it combines bourbon, fresh mint, and sugar for a refreshing, aromatic drink that embodies Southern hospitality."}'::jsonb, '{"created_year":"1784","origin":{"city":"Virginia","bar":"Various Southern establishments","country":"United States"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Mint Julep''s roots trace to Persia (julep derives from \"gulab,\" rosewater) where it was a medicinal drink. First recorded in America in 1784 as a cure for stomach ailments, it originated in Virginia before spreading throughout the South. Senator Henry Clay of Kentucky introduced it to Washington D.C. at the Willard Hotel''s Round Robin Bar. When brandy shortages occurred, bourbon became the spirit of choice. The cocktail became inseparably linked with the Kentucky Derby in 1938 when Churchill Downs began serving it in souvenir glasses. Today, nearly 120,000 juleps are served during Derby weekend."},"named_after":{"en":"The word \"julep\" comes from the Persian \"gulab\" (rose water), originally referring to sweet medicinal drinks. \"Mint\" was added when the cocktail evolved to include the fresh herb."}}'::jsonb, '{"profile":["refreshing","minty","sweet","herbaceous"],"description":{"en":"The Mint Julep offers a refreshing combination of cool mint and smooth bourbon sweetness. The muddled mint releases aromatic oils that blend with the caramel and vanilla notes of bourbon, while crushed ice provides a frosty, diluted sipping experience. The sugar balances the herbaceous bite."},"first_impression":{"en":"Intensely aromatic with fresh mint hitting the nose immediately. First sip brings sweet, cool mintiness with underlying bourbon warmth."},"finish":{"en":"Long, refreshing finish with lingering mint coolness and subtle bourbon oak notes. The sweetness fades gradually, leaving clean herbal freshness."},"balance":{"en":"Perfectly balanced between sweet sugar, aromatic mint, and robust bourbon. The crushed ice provides ideal dilution, making it dangerously easy to drink."}}'::jsonb, '{"best_time":["afternoon","evening","summer_day"],"occasions":["kentucky_derby","garden_party","summer_gathering","special_occasion"],"seasons":["summer","spring"],"food_pairings":{"en":"Classic pairing with Southern cuisine: fried chicken, BBQ, country ham, pimento cheese, and Derby pie. Also excellent with grilled meats and rich, savory dishes."},"ideal_for":{"en":"Perfect for Kentucky Derby celebrations, summer garden parties, bourbon enthusiasts, and anyone seeking a refreshing Southern classic. Louisville''s official cocktail."}}'::jsonb, '[{"ingredient_id":"ING_BOURBON","quantity":{"amount":60,"unit":"ml"},"display_name":"Bourbon Whiskey","notes":null},{"ingredient_id":"ING_MINT_SPRIG","quantity":{"amount":4,"unit":"sprig"},"display_name":"Fresh Mint Sprigs","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":1,"unit":"teaspoon"},"display_name":"Powdered Sugar","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":2,"unit":"teaspoon"},"display_name":"Water","notes":null}]'::jsonb, 'build', '{"en":"In a julep stainless steel cup, gently muddle the mint with powdered sugar and water until sugar is dissolved and mint releases its oils. Fill the cup with crushed ice. Add the bourbon and stir well until the cup frosts on the outside. Top with more crushed ice to form a dome. Garnish with a fresh mint sprig. Serve with a straw."}'::jsonb, 'Julep stainless steel cup', '{"en":"Fresh mint sprig"}'::jsonb, 'crushed', 'built', '{"ING_BOURBON"}', '{"refreshing","minty","sweet","herbaceous"}', 18, 156, 'easy', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"summer","spring"}', '{"kentucky_derby","garden_party","special_occasion"}', false, false, '{}', 'Use fresh spearmint for authentic flavor. Muddle gently - bruising mint too aggressively can release bitter flavors. Traditional silver julep cups frost beautifully and keep drinks colder. Crushed ice is essential - use a Lewis bag or ice crusher. The drink should be constantly refreshed with ice as it dilutes. During Derby weekend, pre-batch simple syrup with muddled mint for faster service.', 'mid', 75, 'https://iba-world.com/mint-julep/', 'IBA Official Recipe. Historical information from Kentucky Derby Museum and cocktail historians. Named official cocktail of Louisville, Kentucky in 2015.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 23. Monkey Gland


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('c2e06619-1094-4ed4-9a16-26a5f4ff5351', 'monkey-gland', 'b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0', '{"en":"Monkey Gland"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","gin","fruity","prohibition-era","controversial-name"}', '{"en":"A bold Prohibition-era cocktail combining gin with orange juice, grenadine, and a hint of absinthe. Despite its controversial name, this Harry''s New York Bar classic delivers a fruity, complex flavor profile that has stood the test of time."}'::jsonb, '{"created_year":"1920","origin":{"city":"Paris","bar":"Harry''s New York Bar","country":"France"},"creator":{"name":"Harry MacElhone","profession":"bartender"},"story":{"en":"The Monkey Gland was created by legendary bartender Harry MacElhone at Harry''s New York Bar in Paris during the 1920s. The cocktail''s unusual name references a controversial medical procedure of the era performed by Russian-French surgeon Serge Voronoff, who claimed to restore youth and vitality by transplanting monkey glands into humans. The procedure became a sensation in 1920s Paris, and MacElhone named the drink after this bizarre practice, suggesting the cocktail itself had rejuvenating properties. Despite the strange name, the drink became hugely popular among American expatriates in Paris during Prohibition."},"named_after":{"en":"Named after the controversial \"monkey gland\" transplant procedure performed by Dr. Serge Voronoff in 1920s Paris, which claimed to restore youth and virility."}}'::jsonb, '{"profile":["fruity","citrus","herbal"],"description":{"en":"Bright and fruity with orange juice taking the lead, balanced by botanical gin and a touch of grenadine sweetness. The absinthe adds a subtle anise complexity that elevates the drink beyond a simple gin and orange combination. The result is refreshing, slightly mysterious, and more sophisticated than its playful appearance suggests."},"first_impression":{"en":"Fresh orange juice with herbal gin complexity"},"finish":{"en":"Subtle anise notes from absinthe with lingering citrus"},"balance":{"en":"Well-balanced between fruity sweetness and botanical complexity - playful yet sophisticated"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["brunch","party","conversation","vintage_theme"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with French cuisine, smoked salmon canapés, cheese boards, roasted duck, and citrus-based desserts. Pairs beautifully with Middle Eastern mezze and herb-forward dishes."},"ideal_for":{"en":"Perfect for adventurous gin lovers who appreciate cocktails with history and character. An excellent conversation starter due to its unusual name, ideal for vintage cocktail enthusiasts and those exploring classic Prohibition-era drinks."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":45,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":45,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_GRENADINE","quantity":{"amount":2,"unit":"dash"},"display_name":"Grenadine syrup","notes":null},{"ingredient_id":"ING_ABSINTHE","quantity":{"amount":2,"unit":"dash"},"display_name":"Absinthe","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake well until properly chilled. Strain into a chilled cocktail glass."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"Orange twist (optional)"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"fruity","citrus","herbal"}', 18, 150, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"brunch","party","conversation"}', false, false, '{"monkey-gland-royale","modern-monkey"}', 'Use fresh orange juice for best results. Absinthe should be used sparingly - just a hint to add complexity. Can substitute with pastis if absinthe unavailable. The name often requires explanation to curious guests - be prepared with the historical story.', 'mid', 52, 'https://iba-world.com/monkey-gland/', 'IBA Official Recipe. Historical information from Harry MacElhone''s "Harry''s ABC of Mixing Cocktails" and cocktail history sources.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 24. Negroni


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('8a145bac-ece9-4d62-a98c-4b45c7542715', 'negroni', 'negroni', '{"en":"Negroni"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","italian","bitter","aperitivo"}', '{"en":"The Negroni is a bold, bitter Italian aperitivo cocktail. Perfectly balanced with equal parts gin, Campari, and sweet vermouth, it''s a sophisticated drink that embodies la dolce vita. Voted the most ordered cocktail in the world in 2022."}'::jsonb, '{"created_year":"1919","origin":{"city":"Florence","bar":"Caffè Casoni (now Caffè Giacosa)","country":"Italy"},"creator":{"name":"Fosco Scarselli","profession":"bartender"},"story":{"en":"In 1919 at Caffè Casoni in Florence, Count Camillo Negroni asked bartender Fosco Scarselli to strengthen his favorite cocktail, the Americano, by replacing soda water with gin. Scarselli obliged and also added an orange garnish instead of the traditional lemon to signify the variation. The drink became so popular among other patrons requesting \"Count Negroni''s drink\" that it simply became known as the Negroni. The flamboyant count had returned from America when Prohibition began, having lived as a cowboy in the Wild West and a gambler in New York."},"named_after":{"en":"Named after Count Camillo Negroni, the customer for whom the drink was created in 1919."}}'::jsonb, '{"profile":["bitter","sweet","herbal","complex"],"description":{"en":"The Negroni delivers a complex interplay of flavors. Campari provides distinctive bitter orange notes, the gin adds botanical complexity and juniper backbone, while sweet vermouth brings herbal sweetness and depth. The equal proportions create perfect harmony between bitter and sweet."},"first_impression":{"en":"Immediately bold and bitter with Campari''s distinctive orange peel bitterness, followed quickly by gin''s botanical notes and vermouth''s sweet complexity."},"finish":{"en":"Long, warming finish with persistent bitter orange notes and herbal complexity. The sweetness fades gradually, leaving pleasant bitterness that stimulates the appetite."},"balance":{"en":"Masterfully balanced with the classic 1:1:1 ratio. The three components create synergy where bitter Campari, aromatic gin, and sweet vermouth achieve perfect equilibrium."}}'::jsonb, '{"best_time":["pre-dinner","aperitivo","evening"],"occasions":["aperitivo","date_night","social_gathering"],"seasons":["all_year"],"food_pairings":{"en":"Perfect aperitivo pairing with Italian antipasti: olives, cured meats, aged cheeses, bruschetta, and arancini. The bitterness prepares the palate for a meal."},"ideal_for":{"en":"Perfect for aperitivo hour, those who appreciate bitter flavors, cocktail enthusiasts, and anyone seeking an authentic Italian drinking experience. The world''s most ordered cocktail in 2022."}}'::jsonb, '[{"ingredient_id":"ING_GIN_LONDON_DRY","quantity":{"amount":30,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_CAMPARI","quantity":{"amount":30,"unit":"ml"},"display_name":"Bitter Campari","notes":null},{"ingredient_id":"ING_VERMOUTH_SWEET","quantity":{"amount":30,"unit":"ml"},"display_name":"Sweet Red Vermouth","notes":null}]'::jsonb, 'build', '{"en":"Pour all ingredients directly into an old fashioned glass filled with ice. Stir gently to combine and chill. Express the oils from an orange peel over the drink, then use the peel as garnish."}'::jsonb, 'Old fashioned glass', '{"en":"Half orange slice"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_GIN_LONDON_DRY"}', '{"bitter","sweet","herbal","complex"}', 24, 195, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"all_year"}', '{"aperitivo","date_night","social_gathering"}', false, false, '{}', 'The classic 1:1:1 ratio is essential - never deviate. Use quality Campari (no substitutions for authentic Negroni). Fresh ice is important as dilution affects the drink significantly. Build directly in the glass - no shaking or straining needed. Popular variations include Negroni Sbagliato (prosecco instead of gin) and White Negroni (Suze and Lillet Blanc). June is celebrated as Negroni Week globally.', 'mid', 95, 'https://iba-world.com/negroni/', 'IBA Official Recipe. Historical information from Caffè Giacosa, Florence, and cocktail historians. Voted most ordered cocktail worldwide in 2022 by Drinks International.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 25. Old Fashioned


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('b9f75cad-c532-47fc-8d58-fe16669d23ff', 'old-fashioned', 'old_fashioned', '{"en":"Old Fashioned"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","american","whiskey","stirred"}', '{"en":"The Old Fashioned is the original cocktail, the definition of what a cocktail should be. Simple yet sophisticated, it combines whiskey, sugar, bitters, and water. A timeless American classic that showcases the quality of the spirit."}'::jsonb, '{"created_year":"1800s","origin":{"city":"Louisville","bar":"Pendennis Club","country":"United States"},"creator":{"name":"Unknown / Various bartenders","profession":"bartender"},"story":{"en":"The Old Fashioned represents the original definition of a cocktail: spirits, sugar, water, and bitters. The name emerged in the 1880s when drinkers began requesting their drinks made \"the old-fashioned way\" - a simple, traditional preparation rather than the elaborate cocktails that had become popular. While the Pendennis Club in Louisville claims its invention by bartender Martin Cuneo for Colonel James E. Pepper in the 1880s, this is disputed by historians. The Chicago Daily Tribune mentioned \"old fashioned cocktails\" in 1880, before the Pendennis Club opened. The recipe itself dates to the early 1800s. Named Louisville''s official cocktail in 2015."},"named_after":{"en":"Named for the \"old fashioned way\" of making cocktails - the simple, original method that predated more elaborate cocktail preparations of the late 1800s."}}'::jsonb, '{"profile":["spirit-forward","sweet","aromatic","smooth"],"description":{"en":"The Old Fashioned is spirit-forward, allowing the whiskey''s character to shine. Sugar provides gentle sweetness, while Angostura bitters add complexity with notes of cinnamon, clove, and orange. The muddling and dilution create a smooth, well-integrated drink that highlights the bourbon or rye."},"first_impression":{"en":"Rich bourbon or rye character immediately apparent, with subtle sweetness and aromatic bitters complexity. The orange and cherry garnish provide fruity aromatics."},"finish":{"en":"Long, warming finish with oak, vanilla, and caramel notes from the whiskey, followed by lingering bitters spice. The sweetness fades, leaving pleasant whiskey character."},"balance":{"en":"Perfectly balanced to showcase the whiskey while sugar and bitters provide just enough sweetness and complexity without overwhelming the base spirit."}}'::jsonb, '{"best_time":["evening","after_dinner","winter_evening"],"occasions":["sophisticated_gathering","business_dinner","quiet_contemplation"],"seasons":["fall","winter","all_year"],"food_pairings":{"en":"Excellent with rich, savory foods: grilled steaks, smoked brisket, aged cheeses, dark chocolate, and cigars. The whiskey stands up to bold flavors."},"ideal_for":{"en":"Perfect for whiskey enthusiasts, those who appreciate spirit-forward cocktails, sophisticated evenings, and anyone seeking a timeless classic. Louisville''s official cocktail."}}'::jsonb, '[{"ingredient_id":"ING_BOURBON","quantity":{"amount":45,"unit":"ml"},"display_name":"Bourbon or Rye Whiskey","notes":null},{"ingredient_id":"ING_SUPERFINE_SUGAR","quantity":{"amount":1,"unit":"cube"},"display_name":"Sugar Cube","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":3,"unit":"dash"},"display_name":"Angostura Bitters","notes":null}]'::jsonb, 'build', '{"en":"Place sugar cube in an old fashioned glass and saturate with Angostura bitters. Add a few dashes of plain water. Muddle until the sugar is dissolved. Fill the glass with large ice cubes and add the whiskey. Stir gently for about 20 seconds. Garnish with an orange slice or zest and a cocktail cherry."}'::jsonb, 'Old fashioned glass', '{"en":"Orange slice or zest, and a cocktail cherry"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_BOURBON"}', '{"spirit-forward","sweet","aromatic","smooth"}', 32, 155, 'easy', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"fall","winter","all_year"}', '{"sophisticated_gathering","business_dinner"}', false, false, '{}', 'Use quality bourbon or rye - the spirit is the star. Large ice cubes are essential to minimize dilution. Muddle gently - you want to dissolve the sugar, not pulverize it. The classic garnish is orange and cherry, but some prefer just an expressed orange peel. Wisconsin-style Old Fashioned uses brandy and adds soda - specify which style customer wants. During Louisville''s "Old Fashioned Fortnight" (first two weeks of June), feature this cocktail prominently.', 'mid', 90, 'https://iba-world.com/old-fashioned/', 'IBA Official Recipe. Historical information from Chicago Daily Tribune (1880) and cocktail historians David Wondrich and Robert Simonson. Named official cocktail of Louisville, Kentucky on June 4, 2015.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 26. Paradise


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('dc50cf9b-c2f9-4a25-b9d1-0247575b1355', 'paradise', 'f7e6d5c4b3a29281706958473625140abcdef123', '{"en":"Paradise"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","fruity","citrus","vintage"}', '{"en":"A delightful Prohibition-era cocktail that combines gin''s botanical character with the stone-fruit sweetness of apricot brandy and bright citrus. One of the original IBA cocktails, the Paradise offers a perfect balance of fruity and herbal notes."}'::jsonb, '{"created_year":"1930","origin":{"city":"London","bar":"Savoy Hotel","country":"UK"},"creator":{"name":"Harry Craddock","profession":"bartender"},"story":{"en":"The Paradise cocktail was created by legendary bartender Harry Craddock and appeared in his famous 1930 \"Savoy Cocktail Book.\" It has been part of the IBA cocktail list since its inception—included in the first official IBA Cocktail List of 50 cocktails created and approved in 1961 in Norway. The drink uses the classic 2:1:1 ratio of gin to apricot brandy to orange juice, making it easy to remember and scale."},"named_after":{"en":"Named to evoke the blissful, heavenly combination of flavors."}}'::jsonb, '{"profile":["fruity","citrus","botanical"],"description":{"en":"Bright and fruity with apricot sweetness balanced by citrus acidity and gin''s botanical backbone. The orange juice provides body while lemon adds zing, creating a harmonious and refreshing cocktail."},"first_impression":{"en":"Sweet apricot and orange greet you first, followed by botanical gin"},"finish":{"en":"Clean, citrusy finish with lingering apricot sweetness"},"balance":{"en":"Well-balanced between sweet fruit and tart citrus"}}'::jsonb, '{"best_time":["afternoon","early_evening","aperitivo"],"occasions":["aperitivo","brunch","garden_party","summer_gathering"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with light appetizers, fruit salads, grilled chicken, or seafood. Pairs well with Mediterranean cuisine and fresh salads."},"ideal_for":{"en":"Perfect for gin lovers who enjoy fruity cocktails. Ideal for those seeking a refreshing, not-too-sweet drink with classic pedigree."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":40,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_APRICOT_BRANDY","quantity":{"amount":20,"unit":"ml"},"display_name":"Apricot brandy","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":20,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":10,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass."}'::jsonb, 'Cocktail glass (Martini)', '{"en":"Orange twist or lemon twist"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"fruity","citrus","botanical"}', 18, 160, 'easy', 60, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"aperitivo","brunch","garden_party"}', false, false, '{"aviation","clover-club","white-lady"}', 'Use fresh citrus juices only - bottled will not do. The 2:1:1 ratio is easy to remember. Quality apricot brandy makes a big difference. Shake well for proper dilution and to integrate fruit juices.', 'mid', 50, 'https://iba-world.com/iba-cocktail/paradise/', 'IBA Official Recipe. Historical information from Harry Craddock''s "Savoy Cocktail Book" (1930).', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 27. Planter's Punch


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('70db8fe6-4ff2-42db-a023-b820a59e353a', 'planters-punch', 'd4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3', '{"en":"Planter''s Punch"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","rum","tropical","tiki","punch","refreshing"}', '{"en":"A legendary Caribbean rum punch that epitomizes tropical refreshment. This classic combines dark rum with fresh citrus juices and sugar syrup, creating a perfectly balanced drink that''s been quenching thirsts since the 19th century. Following the traditional \"one of sour, two of sweet, three of strong, four of weak\" formula."}'::jsonb, '{"created_year":"1878","origin":{"city":"Kingston","bar":"Myers Rum Distillery","country":"Jamaica"},"creator":{"name":"Fred L. Myers","profession":"distiller"},"story":{"en":"The Planter''s Punch dates back to 1878 when it first appeared in print in the Jamaican newspaper \"Fun.\" The recipe followed a simple rhyme: \"One of sour, two of sweet, three of strong, four of weak\" - referring to lime juice, sugar syrup, rum, and water. The drink was popularized by Fred L. Myers of the Myers Rum Distillery in Jamaica and became a signature offering at plantation parties. It spread throughout the Caribbean and became a staple of tiki culture in the mid-20th century. The name \"Planter''s\" refers to the colonial plantation owners who would have served this refreshing drink during hot Caribbean days."},"named_after":{"en":"Named after the plantation owners (planters) in the Caribbean who popularized this refreshing rum punch during the colonial era."}}'::jsonb, '{"profile":["tropical","citrus","sweet"],"description":{"en":"Bold and tropical with rich dark rum as the foundation, balanced by tart lime and orange juices. The sugar syrup rounds out the flavors, creating a harmonious blend that''s both refreshing and satisfying. The dark rum provides depth and complexity with notes of molasses and caramel, while the citrus keeps it bright and lively."},"first_impression":{"en":"Bright citrus with dark rum warmth and sweetness"},"finish":{"en":"Long, warming finish with lingering rum spices and tropical fruit notes"},"balance":{"en":"Perfectly balanced following the classic punch formula - sweet without being cloying, strong without being harsh"}}'::jsonb, '{"best_time":["afternoon","evening"],"occasions":["party","celebration","poolside","beach","tiki_night"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with Caribbean cuisine, jerk chicken, grilled seafood, tropical fruits, coconut-based dishes, and spicy island fare. Pairs beautifully with BBQ ribs and plantain chips."},"ideal_for":{"en":"Perfect for rum enthusiasts who love tropical classics. An excellent choice for summer parties, tiki gatherings, or anyone seeking an authentic Caribbean experience. The drink is social and shareable, making it ideal for group celebrations."}}'::jsonb, '[{"ingredient_id":"ING_RUM_DARK","quantity":{"amount":45,"unit":"ml"},"display_name":"Dark rum","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":35,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":35,"unit":"ml"},"display_name":"Fresh pineapple juice","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":20,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_GRENADINE","quantity":{"amount":10,"unit":"ml"},"display_name":"Grenadine syrup","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":10,"unit":"ml"},"display_name":"Simple syrup","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":3,"unit":"dash"},"display_name":"Angostura bitters","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake well until properly chilled. Pour unstrained into a large glass filled with ice (can also strain if preferred)."}'::jsonb, 'Highball glass', '{"en":"Pineapple slice, maraschino cherry, and orange slice"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_RUM_DARK"}', '{"tropical","citrus","sweet"}', 12, 210, 'easy', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"party","celebration","poolside","beach"}', false, false, '{"jamaican-planters-punch","navy-grog","tropical-punch"}', 'Use fresh juices for best results - never use concentrate. The classic ratio is "one of sour, two of sweet, three of strong, four of weak." Myers''s Dark Rum is traditional. Garnish generously for tropical presentation. Can be scaled up for party punch bowls.', 'mid', 70, 'https://iba-world.com/planters-punch/', 'IBA Official Recipe. Historical information from the Jamaican newspaper "Fun" (1878) and Myers Rum Distillery archives.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 28. Porto Flip


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('7039b884-7868-403a-9610-902b90a9b250', 'porto-flip', 'c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8', '{"en":"Porto Flip"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","creamy","rich","after-dinner","historical"}', '{"en":"A rich, velvety historical cocktail combining brandy, ruby port, and egg yolk. Dating back to the 19th century, the Porto Flip is silky smooth, decadent, and warming - a luxurious after-dinner indulgence topped with freshly grated nutmeg."}'::jsonb, '{"created_year":"1887","origin":{"city":"Unknown","bar":"Unknown","country":"USA/UK"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Porto Flip has deep roots dating back to the 19th century. The name \"Porto\" clearly nods to its main ingredient, Ruby Port, a fortified wine from Portugal. This drink first appeared in renowned bartending manuals of the time, including Jerry Thomas''s 1887 book \"How to Mix Drinks or The Bon Vivant''s Companion.\" \"Flip\" cocktails were a popular category in the 1800s, characterized by the addition of a whole egg or egg yolk, which creates a rich, frothy texture. The Porto Flip is a historical after-dinner cocktail that showcases the elegance of classic mixology."},"named_after":{"en":"Named after Porto (Port wine) and the \"flip\" style of cocktails which include egg."}}'::jsonb, '{"profile":["rich","creamy","sweet"],"description":{"en":"Rich and luxurious with velvety egg yolk creating a silky texture. The brandy provides warmth and depth, while ruby port adds sweet, fruity notes with hints of berries and spice. Nutmeg on top adds aromatic complexity. Decadent and satisfying."},"first_impression":{"en":"Rich, creamy texture with sweet port and aromatic nutmeg"},"finish":{"en":"Long, warming finish with lingering port sweetness and spice"},"balance":{"en":"Rich and indulgent with balanced sweetness and warmth"}}'::jsonb, '{"best_time":["after_dinner","late_night","dessert"],"occasions":["digestivo","nightcap","special_occasion","celebration"],"seasons":["autumn","winter"],"food_pairings":{"en":"Perfect with desserts like chocolate cake, tiramisu, or crème brûlée. Also pairs with nuts, dried fruits, aged cheese, or as a dessert replacement."},"ideal_for":{"en":"Perfect for those who enjoy rich, creamy after-dinner drinks. Ideal for brandy and port lovers seeking something unique and historical. Great for adventurous drinkers willing to try egg-based cocktails."}}'::jsonb, '[{"ingredient_id":"ING_BRANDY","quantity":{"amount":15,"unit":"ml"},"display_name":"Brandy","notes":null},{"ingredient_id":"ING_RUBY_PORT","quantity":{"amount":45,"unit":"ml"},"display_name":"Ruby port","notes":null},{"ingredient_id":"ING_EGG_YOLK","quantity":{"amount":1,"unit":"whole"},"display_name":"Egg yolk","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass. Sprinkle with fresh ground nutmeg."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"Freshly grated nutmeg"}'::jsonb, 'none', 'up', '{"ING_BRANDY","ING_RUBY_PORT"}', '{"rich","creamy","sweet"}', 14, 200, 'medium', 90, '{"egg","sulphites"}', '{"egg_intolerance","alcohol","sulphites_intolerance"}', '{"vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","gluten-free","dairy-free"}', '{"autumn","winter"}', '{"digestivo","nightcap","special_occasion"}', false, false, '{"sherry-flip","brandy-flip","alexander"}', 'Use fresh egg yolk only. Shake vigorously to properly emulsify the yolk. Ruby port is traditional - tawny port can also be used. Freshly grate nutmeg over the top just before serving. Some variations use whole egg instead of just yolk.', 'mid', 40, 'https://iba-world.com/iba-cocktail/porto-flip/', 'IBA Official Recipe. Historical information from Jerry Thomas "How to Mix Drinks" (1887) and 19th century cocktail documentation.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 29. Ramos Gin Fizz


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('d11061d4-cfa2-4e8a-990d-10e4522221ad', 'ramos-gin-fizz', 'd9c8b7a6f5e4d3c2b1a098765432109fedcba987', '{"en":"Ramos Gin Fizz"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","creamy","refreshing","fizz","labor-intensive"}', '{"en":"A legendary New Orleans classic known for its rich, creamy texture and refreshing citrus flavor. The Ramos Gin Fizz requires vigorous shaking to achieve its signature frothy, meringue-like consistency. Often called \"the workout in a glass,\" it''s one of the most labor-intensive cocktails."}'::jsonb, '{"created_year":"1888","origin":{"city":"New Orleans","bar":"Imperial Cabinet Saloon","country":"USA"},"creator":{"name":"Henry Charles Ramos","profession":"bartender"},"story":{"en":"The Ramos Gin Fizz was created in 1888 by Henry Charles Ramos at the Imperial Cabinet Saloon on the corner of Gravier and Carondelet Streets in New Orleans, Louisiana. Originally named the \"New Orleans Fizz,\" Henry used to call his famous creation \"the One And Only One.\" According to legend, Ramos himself routinely employed up to 30 bartenders dedicated solely to shaking up the drink, sometimes for 12 minutes apiece, to achieve the perfect consistency. The drink became so popular that during Mardi Gras, the bar had a dedicated \"shaker boy\" assembly line."},"named_after":{"en":"Named after its creator, Henry Charles Ramos."}}'::jsonb, '{"profile":["creamy","citrus","floral"],"description":{"en":"Silky smooth and cloud-like with a perfect balance of tart citrus, floral orange blossom, and creamy richness. The gin provides botanical backbone while the egg white creates an ethereal, meringue-like texture. Vanilla adds subtle sweetness."},"first_impression":{"en":"Fluffy, cloud-like foam with bright citrus and delicate orange blossom aroma"},"finish":{"en":"Clean, refreshing finish with lingering floral notes and gentle cream"},"balance":{"en":"Perfectly balanced between rich creaminess and bright, refreshing citrus"}}'::jsonb, '{"best_time":["brunch","afternoon","early_evening"],"occasions":["brunch","celebration","special_occasion","impressive"],"seasons":["spring","summer"],"food_pairings":{"en":"Perfect with brunch dishes like eggs Benedict, French toast, or fresh fruit. Also pairs well with light seafood, salads, or as a palate cleanser between courses."},"ideal_for":{"en":"Perfect for gin lovers who appreciate classic cocktails and don''t mind waiting for their drink. Ideal for special occasions when you want to impress guests with both flavor and presentation."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":45,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_SIMPLE_SYRUP","quantity":{"amount":30,"unit":"ml"},"display_name":"Sugar syrup","notes":null},{"ingredient_id":"ING_HEAVY_CREAM","quantity":{"amount":60,"unit":"ml"},"display_name":"Cream","notes":null},{"ingredient_id":"ING_EGG_WHITE","quantity":{"amount":30,"unit":"ml"},"display_name":"Egg white","notes":null},{"ingredient_id":"ING_ORANGE_FLOWER_WATER","quantity":{"amount":3,"unit":"dash"},"display_name":"Orange flower water","notes":null},{"ingredient_id":"ING_VANILLA_EXTRACT","quantity":{"amount":2,"unit":"dash"},"display_name":"Vanilla extract","notes":null},{"ingredient_id":"ING_SODA_WATER","quantity":{"amount":30,"unit":"ml"},"display_name":"Soda water","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients except soda water in a cocktail shaker with ice. Shake for two minutes, double strain in a glass, pour the drink back in the shaker and hard shake without ice for one minute. Strain into a highball glass, top up with soda."}'::jsonb, 'Highball glass', '{"en":"None (the foam crown is the garnish)"}'::jsonb, 'none', 'straight_up', '{"ING_GIN"}', '{"creamy","citrus","floral"}', 8, 320, 'hard', 240, '{"egg","milk","sulphites"}', '{"egg_intolerance","lactose","alcohol","sulphites_intolerance"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 0, '{"vegetarian","gluten-free"}', '{"spring","summer"}', '{"brunch","celebration","special_occasion"}', false, false, '{"gin-fizz","silver-fizz","royal-fizz"}', 'This is the most labor-intensive cocktail on the menu. Requires 3 minutes of vigorous shaking total. Use fresh egg white for best foam. Orange flower water is essential - don''t substitute. The double shake method (with ice, then without) is critical for proper texture. Soda should be added last and very gently to preserve the foam crown.', 'premium', 70, 'https://iba-world.com/iba-cocktail/ramos-fizz/', 'IBA Official Recipe. Historical information from New Orleans cocktail history and Henry Charles Ramos documentation.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 30. Remember the Maine


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('64bd79bb-dd34-4e8f-9ba0-72f8d7e15d4c', 'remember-the-maine', 'f8e7d6c5b4a3928170695847362514039281fade', '{"en":"Remember the Maine"}'::jsonb, 'iba_official', 'Unforgettables', '{"iba","official","classic","stirred","strong","complex"}', '{"en":"A richly complex, Prohibition-era classic that blends the bold character of rye whiskey with the herbal depth of sweet vermouth, a touch of cherry liqueur, and a whisper of absinthe. Named after the rallying cry that sparked the Spanish-American War."}'::jsonb, '{"created_year":"1933","origin":{"city":"Havana","bar":"Unknown","country":"Cuba"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"Charles H. Baker Jr., in his book \"The Gentleman''s Companion\" (1939), states that he encountered this cocktail in Havana, Cuba during the Cuban Revolution of 1933. The cocktail is named after the press slogan \"Remember the Maine, to Hell with Spain!\" which blamed Spain for the unexplained sinking of the U.S.S. Maine off Cuba in 1898, helping provoke the Spanish-American War."},"named_after":{"en":"Named after the U.S.S. Maine battleship and the rallying cry \"Remember the Maine, to Hell with Spain!\" which became a slogan during the Spanish-American War."}}'::jsonb, '{"profile":["complex","herbal","boozy"],"description":{"en":"Complex and sophisticated with spicy rye whiskey at the forefront, balanced by sweet vermouth and enhanced with cherry notes from the liqueur. The absinthe rinse adds an elegant herbal whisper without overpowering the drink."},"first_impression":{"en":"Anise and herbal notes from absinthe, followed by bold rye spice"},"finish":{"en":"Long, warming finish with lingering cherry sweetness and herbal complexity"},"balance":{"en":"Beautifully balanced between strong spirit and aromatic modifiers"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["aperitivo","date_night","contemplative","nightcap"],"seasons":["autumn","winter","spring"],"food_pairings":{"en":"Excellent with charcuterie, aged cheeses, dark chocolate, or smoked meats. Also pairs well with rich desserts like chocolate cake or bread pudding."},"ideal_for":{"en":"Perfect for whiskey enthusiasts who appreciate complex, spirit-forward cocktails with historical significance. Ideal for those who enjoy Manhattan variations and bold, aromatic drinks."}}'::jsonb, '[{"ingredient_id":"ING_RYE_WHISKEY","quantity":{"amount":60,"unit":"ml"},"display_name":"Rye whiskey","notes":null},{"ingredient_id":"ING_SWEET_VERMOUTH","quantity":{"amount":20,"unit":"ml"},"display_name":"Sweet vermouth","notes":null},{"ingredient_id":"ING_CHERRY_HEERING","quantity":{"amount":10,"unit":"ml"},"display_name":"Cherry Heering","notes":null},{"ingredient_id":"ING_ABSINTHE","quantity":{"amount":2,"unit":"barspoon"},"display_name":"Absinthe","notes":null}]'::jsonb, 'stir', '{"en":"Pour the absinthe into a coupe glass and swirl to completely coat the inside. Discard the absinthe and set the glass aside. Add the other ingredients to a mixing glass and fill it 3/4 full with ice. Stir until chilled, then strain into the glass rinsed with the absinthe."}'::jsonb, 'Coupe glass', '{"en":"None (or lemon twist optional)"}'::jsonb, 'none', 'up', '{"ING_RYE_WHISKEY"}', '{"complex","herbal","boozy"}', 30, 180, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegetarian","vegan","gluten-free","dairy-free"}', '{"autumn","winter","spring"}', '{"aperitivo","date_night","contemplative","nightcap"}', false, false, '{"manhattan","brooklyn","vieux-carre"}', 'The absinthe rinse is essential - don''t skip it. Use Cherry Heering for authenticity. Can substitute bourbon for rye if needed, but rye''s spice is traditional. Ensure proper stirring to achieve ideal dilution.', 'mid', 55, 'https://iba-world.com/iba-cocktail/remember-the-maine/', 'IBA Official Recipe. Historical information from Charles H. Baker Jr. "The Gentleman''s Companion" (1939).', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


