INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('9d10d5ca-e730-4256-ada7-f41808ea2671', 'vegas-bomb', 'vegas_bomb_shot_famous_energy_drink_bomb_coconut', '{"en":"Vegas Bomb"}'::jsonb, 'famous', NULL, '{"shot","shooter","famous","bomb","energy-drink","party","fruity"}', '{"en":"A fruity bomb shot featuring Crown Royal whisky, peach schnapps, Malibu coconut rum, and cranberry juice, dropped into Red Bull. This party favorite combines tropical flavors with an energy boost, embodying the wild spirit of Las Vegas nightlife."}'::jsonb, '{"created_year":"2000s","origin":{"city":"Las Vegas","bar":"Unknown","country":"USA"},"story":{"en":"The Vegas Bomb emerged in Las Vegas during the early 2000s as a sweeter, more approachable alternative to the Jäger Bomb. Created to appeal to a broader audience who wanted the energy drink bomb experience without the intense herbal flavors, it quickly became a staple in Vegas bars and spread to nightclubs nationwide."},"named_after":{"en":"Named after Las Vegas, the city where it was created and popularized in the casino nightclub scene."}}'::jsonb, '{"profile":["sweet","fruity","tropical","energizing"],"description":{"en":"Sweet and tropical with peach, coconut, and cranberry flavors. The Crown Royal adds smoothness while the Red Bull provides sweetness and energy. Much sweeter and fruitier than a Jäger Bomb."},"first_impression":{"en":"Sweet tropical fruit flavors with energy drink base"},"finish":{"en":"Smooth, fruity finish with energizing caffeine kick"},"balance":{"en":"Very sweet and approachable, designed for easy drinking"}}'::jsonb, '{"best_time":["late_night"],"occasions":["party","nightlife","celebration","vegas_trip","bachelor_bachelorette"],"seasons":["all_seasons"],"food_pairings":{"en":"Not typically paired with food. Best as a standalone party shot or nightclub drink."},"ideal_for":{"en":"Perfect for Vegas trips, bachelorette parties, and nightclub celebrations. Great for those who want a sweeter alternative to Jäger Bombs. WARNING: Contains high amounts of caffeine and alcohol."}}'::jsonb, '[{"ingredient_id":"ING_CANADIAN_WHISKY","quantity":{"amount":15,"unit":"ml"},"display_name":"Crown Royal Whisky","notes":null},{"ingredient_id":"ING_PEACH_SCHNAPPS","quantity":{"amount":15,"unit":"ml"},"display_name":"Peach Schnapps","notes":null},{"ingredient_id":"ING_MALIBU","quantity":{"amount":15,"unit":"ml"},"display_name":"Malibu Coconut Rum","notes":null},{"ingredient_id":"ING_CRANBERRY_JUICE","quantity":{"amount":15,"unit":"ml"},"display_name":"Cranberry Juice","notes":null},{"ingredient_id":"ING_RED_BULL","quantity":{"amount":120,"unit":"ml"},"display_name":"Red Bull (or energy drink)","notes":null}]'::jsonb, 'build', '{"en":"Fill a pint glass halfway with Red Bull or energy drink. In a shot glass, combine Crown Royal, peach schnapps, Malibu, and cranberry juice. Drop the shot glass into the pint glass and consume immediately."}'::jsonb, 'Shot glass (dropped into pint glass)', '{"en":"None"}'::jsonb, 'none', 'shot', '{"ING_CANADIAN_WHISKY","ING_PEACH_SCHNAPPS","ING_MALIBU"}', '{"sweet","fruity","tropical","energizing"}', 10, 220, 'easy', 45, '{"sulphites","caffeine"}', '{"alcohol","sulphites_intolerance","caffeine_sensitivity"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","vegetarian","gluten-free","dairy-free"}', '{"all-seasons"}', '{"party","nightlife","celebration"}', false, false, '{"irish-vegas-bomb","tropical-vegas-bomb","cherry-vegas-bomb"}', 'Mix shot ingredients in shot glass before dropping. Some variations use different ratios or substitute ingredients. WARNING: High caffeine and alcohol content - serve responsibly. Very popular for Vegas trips and bachelor/bachelorette parties.', 'mid', 85, 'https://www.liquor.com/recipes/vegas-bomb/', 'Popular Las Vegas bomb shot from the early 2000s.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 223. Vieux Mot


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('c4c08fa8-5435-46d6-9949-b34249107961', 'vieux-mot', '8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a08', '{"en":"Vieux Mot"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","gin","herbal","floral"}', '{"en":"A sophisticated gin cocktail featuring elderflower liqueur, lemon juice, and green Chartreuse. The Vieux Mot is a floral, herbal variation on the Last Word that showcases French liqueurs."}'::jsonb, '{"created_year":"2007","origin":{"city":"Seattle","bar":"Vessel","country":"USA"},"creator":{"name":"Jamie Boudreau","profession":"bartender"},"story":{"en":"Created by Jamie Boudreau at Vessel in Seattle in 2007, the Vieux Mot is an elegant variation on the classic Last Word cocktail. Boudreau substituted St-Germain elderflower liqueur for maraschino, creating a more floral, French-inspired interpretation. The name \"Vieux Mot\" means \"old word\" in French, a clever play on the original Last Word name while highlighting the French character of the elderflower liqueur and Chartreuse."},"named_after":{"en":"\"Vieux Mot\" (old word in French) is a bilingual pun on \"Last Word\" while emphasizing the French liqueurs used."}}'::jsonb, '{"profile":["floral","herbal","citrus"],"description":{"en":"Elegant and floral with herbal complexity. Gin provides a juniper backbone, elderflower liqueur adds delicate floral sweetness, green Chartreuse contributes intense herbal notes, and lemon juice brings bright acidity."},"first_impression":{"en":"Bright elderflower and gin botanicals hit first, followed by intense Chartreuse and citrus"},"finish":{"en":"Long, herbal finish with lingering floral and botanical notes"},"balance":{"en":"Perfectly balanced between floral sweetness and herbal intensity, complex yet harmonious"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["cocktail_hour","date_night","spring_celebration"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with fresh cheeses, herb-forward dishes, light seafood, and spring vegetables. The floral-herbal profile complements delicate, aromatic flavors."},"ideal_for":{"en":"Perfect for gin lovers who appreciate floral, botanical cocktails. Ideal for those who enjoy Chartreuse and French liqueurs."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_ELDERFLOWER_LIQUEUR","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Elderflower liqueur (St-Germain)","notes":null},{"ingredient_id":"ING_CHARTREUSE_GREEN","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Green Chartreuse","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a chilled coupe glass. Garnish with a lemon twist or edible flower."}'::jsonb, 'Coupe', '{"en":"Lemon twist or edible flower"}'::jsonb, 'none', 'up', '{"ING_GIN"}', '{"floral","herbal","citrus"}', 25, 170, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"cocktail_hour","date_night","spring_celebration"}', false, false, '{"last-word","final-ward"}', 'Use St-Germain elderflower liqueur for best results. Equal parts recipe like the Last Word. Shake hard to properly chill and dilute the strong spirits.', 'premium', 71, 'Created by Jamie Boudreau at Vessel, 2007', 'Modern variation on the Last Word cocktail. Featured in craft cocktail publications.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 224. Vodka Martini


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('a7f329a9-fda9-4298-863b-57cd5fefb8d4', 'vodka-martini', 'e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4', '{"en":"Vodka Martini"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","vodka","sophisticated","iconic","james-bond"}', '{"en":"The vodka variation of the classic Martini, made famous by James Bond''s preference for it \"shaken, not stirred.\" Cleaner and less botanical than a gin martini, the Vodka Martini is the ultimate expression of minimalist sophistication."}'::jsonb, '{"created_year":"1950","origin":{"city":"United States","bar":"Various","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Vodka Martini emerged in the 1950s during vodka''s rise to popularity in America. While gin purists considered it sacrilege, the vodka variation quickly gained a following for its clean, neutral character. The drink was catapulted to iconic status by Ian Fleming''s James Bond, who ordered it \"shaken, not stirred\" in the novels and films. Bond''s specific order - the Vesper - called for vodka, gin, and Kina Lillet. The standard Vodka Martini became the drink of choice for those who wanted the sophistication of a martini without gin''s assertive botanicals. By the 1980s and 90s, the Vodka Martini had become more popular than the original gin version in many American bars."},"named_after":{"en":"Named as the vodka variation of the classic Martini cocktail. Made globally famous by James Bond''s signature order."}}'::jsonb, '{"profile":["clean","smooth","crisp"],"description":{"en":"Exceptionally clean and smooth with a silky mouthfeel. The Vodka Martini is all about the quality of the vodka and the subtle vermouth influence. When made well, it''s crystal clear in flavor - smooth, slightly herbal from the vermouth, with a cold, clean finish."},"first_impression":{"en":"Ice-cold smoothness with subtle herbal notes from vermouth"},"finish":{"en":"Clean, crisp finish with lingering coolness and subtle vermouth complexity"},"balance":{"en":"The balance is about vodka quality and vermouth quantity - adjust vermouth from \"perfect\" to \"very dry\" based on preference"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["sophisticated","date_night","aperitivo","celebration"],"seasons":["autumn","winter","spring"],"food_pairings":{"en":"Classic pairings include oysters, caviar, smoked salmon, and other delicate seafood. Also excellent with olives, almonds, and light appetizers."},"ideal_for":{"en":"Perfect for those who appreciate clean, minimalist cocktails. Ideal for vodka enthusiasts who want the sophistication of a martini without gin''s botanical complexity. The choice of sophisticates and James Bond fans worldwide."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":60,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_DRY_VERMOUTH","quantity":{"amount":10,"unit":"ml"},"display_name":"Dry vermouth","notes":null}]'::jsonb, 'stir', '{"en":"Pour vodka and vermouth into a mixing glass with ice. Stir gently for 30-40 seconds until well-chilled. Strain into a chilled martini glass. Garnish with a lemon twist or olives. Note: James Bond prefers it shaken, though stirring is the traditional method."}'::jsonb, 'Martini glass (Cocktail)', '{"en":"Lemon twist or olives"}'::jsonb, 'none', 'up', '{"ING_VODKA"}', '{"clean","smooth","crisp"}', 28, 140, 'medium', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","nut_free","dairy_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"autumn","winter","spring"}', '{"sophisticated","date_night","aperitivo","celebration"}', false, false, '{"vesper","dirty-martini","espresso-martini"}', 'Use premium vodka - quality is paramount here. Store vodka and vermouth in freezer for extra-cold serve. Traditional method is stirred, but offer shaken if requested (Bond-style). Vermouth amount varies: "dry" = less vermouth, "wet" = more vermouth, "dirty" = add olive brine. Always use fresh vermouth.', 'mid', 90, 'https://www.diffordsguide.com/cocktails/recipe/2374/vodka-martini', 'Classic recipe with James Bond cultural influence. Various cocktail history sources.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 225. Vodka Tonic


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('1daf6ddb-13df-4c51-8b26-f92e0dccaaad', 'vodka-tonic', 'f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0', '{"en":"Vodka Tonic"}'::jsonb, 'famous', NULL, '{"highball","long-drink","famous","vodka","tonic","refreshing","simple"}', '{"en":"A crisp, refreshing highball combining vodka with tonic water and lime. The Vodka Tonic is the vodka lover''s answer to the Gin & Tonic, offering a cleaner, more neutral base that lets the tonic''s botanicals shine."}'::jsonb, '{"created_year":"1950","origin":{"city":"United States","country":"USA"},"story":{"en":"The Vodka Tonic emerged in the 1950s as vodka gained popularity in America. While the Gin & Tonic had been popular since the 19th century for its quinine content (used to prevent malaria), the vodka version offered a less botanical, more neutral alternative. The drink became extremely popular in the 1960s and 1970s during the vodka boom, appealing to those who wanted the refreshing qualities of tonic without gin''s distinctive juniper flavor. Today, with the craft tonic water renaissance, the Vodka Tonic has gained new appreciation."},"named_after":{"en":"Simply named after its two main ingredients: vodka and tonic water."}}'::jsonb, '{"profile":["bitter","refreshing","crisp","citrus"],"description":{"en":"Clean and crisp with the tonic''s characteristic bitterness from quinine. The vodka provides a neutral backbone that allows the tonic''s botanicals to shine, while lime adds bright citrus notes. More straightforward and less complex than a Gin & Tonic."},"first_impression":{"en":"Crisp tonic bitterness with clean vodka and bright lime"},"finish":{"en":"Clean, refreshing finish with lingering quinine bitterness"},"balance":{"en":"Well-balanced between vodka neutrality and tonic bitterness, with lime brightening the whole drink"}}'::jsonb, '{"best_time":["afternoon","evening","happy_hour"],"occasions":["casual","social","aperitivo","summer"],"seasons":["spring","summer"],"food_pairings":{"en":"Pairs well with light appetizers, seafood, sushi, salads, and Mediterranean dishes. Excellent with oysters, ceviche, and light cheese plates."},"ideal_for":{"en":"Perfect for those who enjoy the refreshing bitterness of tonic but prefer vodka''s neutrality over gin''s botanical character. Great for warm weather, aperitivo hour, or anyone seeking a clean, crisp drink."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":50,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_TONIC_WATER","quantity":{"amount":100,"unit":"ml"},"display_name":"Tonic water","notes":null},{"ingredient_id":"ING_LIME","quantity":{"amount":1,"unit":"wedge"},"display_name":"Lime wedge","notes":null}]'::jsonb, 'build', '{"en":"Fill a highball glass with ice. Pour vodka over ice. Top with tonic water. Squeeze lime wedge over drink and drop it in. Stir gently once."}'::jsonb, 'Highball glass', '{"en":"Lime wedge"}'::jsonb, 'cubed', 'on_the_rocks', '{"ING_VODKA"}', '{"bitter","refreshing","crisp","citrus"}', 10, 120, 'easy', 20, '{"sulphites"}', '{"alcohol","sulphites_intolerance","quinine_sensitivity"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"casual","social","aperitivo"}', false, false, '{"gin-and-tonic","vodka-soda"}', 'Quality of tonic water is crucial - premium tonics like Fever-Tree make a huge difference. Use fresh lime, not bottled juice. Ratio is flexible - typically 1:2 vodka to tonic.', 'low', 85, 'https://www.diffordsguide.com/cocktails/recipe/1247/vodka-tonic', 'Popular variation of Gin & Tonic, emerged during 1950s vodka boom.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 226. Voodoo Doctor


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('4df6c821-dd67-4872-95ab-88f76384fcd7', 'voodoo-doctor', 'voodoo-doctor-tiki-tropical-famous-2025', '{"en":"Voodoo Doctor"}'::jsonb, 'famous', NULL, '{"tiki","tropical","famous","rum","spiced","mysterious","theatrical"}', '{"en":"A mysterious and potent tiki cocktail blending spiced rum with tropical juices and exotic liqueurs. The Voodoo Doctor offers a complex, mystical flavor profile with Caribbean spices and tropical sweetness that casts a delicious spell on your palate."}'::jsonb, '{"created_year":"1980s","origin":{"city":"New Orleans","bar":"Tiki Bars","country":"USA"},"creator":{"name":"Unknown","profession":"bartender"},"story":{"en":"The Voodoo Doctor emerged in the 1980s from the tiki bar renaissance, particularly popular in New Orleans where voodoo culture and tiki aesthetics merged. The cocktail draws inspiration from New Orleans'' rich voodoo history and mystical traditions, combining them with classic tiki flavors. The name references the spiritual healers and practitioners of voodoo, suggesting this drink has \"magical\" restorative powers. While the exact origin is disputed, the cocktail became a staple at themed tiki bars that embraced the mysterious, supernatural elements of Polynesian and Caribbean cultures."},"named_after":{"en":"Named after voodoo spiritual healers and practitioners, suggesting the drink has mystical, restorative \"magical\" powers to cure what ails you."}}'::jsonb, '{"profile":["spiced","tropical","complex"],"description":{"en":"Complex and mysterious with warm spiced rum, tropical fruit sweetness, and exotic spice notes. Layers of cinnamon, vanilla, and Caribbean spices blend with tropical pineapple and citrus. Rich, warming, and enchantingly delicious."},"first_impression":{"en":"Warm spices and tropical fruit with mysterious aromatic complexity"},"finish":{"en":"Long, warming finish with lingering spice, vanilla, and tropical fruit notes"},"balance":{"en":"Well-balanced between spiced warmth and tropical sweetness - complex and layered without being overwhelming"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["tiki_bar","halloween","mysterious_theme","date_night","celebration"],"seasons":["autumn","winter","year_round"],"food_pairings":{"en":"Pairs excellently with Cajun cuisine, jerk chicken, blackened fish, Caribbean stews, or spiced tropical dishes. Also complements dark chocolate desserts and bananas foster."},"ideal_for":{"en":"Perfect for Halloween parties, mysterious themed events, and tiki bars with a darker aesthetic. Ideal for those who love spiced rum and complex, warming cocktails. Great for cool evenings and autumn nights."}}'::jsonb, '[{"ingredient_id":"ING_RUM_SPICED","quantity":{"amount":45,"unit":"ml"},"display_name":"Spiced rum","notes":null},{"ingredient_id":"ING_RUM_DARK","quantity":{"amount":15,"unit":"ml"},"display_name":"Dark rum","notes":null},{"ingredient_id":"ING_FALERNUM","quantity":{"amount":15,"unit":"ml"},"display_name":"Falernum","notes":null},{"ingredient_id":"ING_PINEAPPLE_JUICE","quantity":{"amount":60,"unit":"ml"},"display_name":"Pineapple juice","notes":null},{"ingredient_id":"ING_LIME_JUICE","quantity":{"amount":22,"unit":"ml"},"display_name":"Fresh lime juice","notes":null},{"ingredient_id":"ING_ANGOSTURA_BITTERS","quantity":{"amount":3,"unit":"dash"},"display_name":"Angostura bitters","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake vigorously until well chilled. Strain into a tiki mug filled with crushed ice. Garnish with pineapple fronds, lime wheel, and a dusting of cinnamon."}'::jsonb, 'Tiki mug', '{"en":"Pineapple fronds, lime wheel, and cinnamon dust"}'::jsonb, 'crushed', 'on_the_rocks', '{"ING_RUM_SPICED","ING_RUM_DARK"}', '{"spiced","tropical","complex"}', 16, 220, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegetarian","vegan","pescatarian","gluten_free","dairy_free","nut_free"}', 1, '{"vegetarian","vegan","gluten-free"}', '{"autumn","winter","year_round"}', '{"tiki_bar","halloween","mysterious_theme","date_night"}', false, false, '{"virgin-voodoo-doctor","voodoo-priestess"}', 'Falernum is a spiced Caribbean liqueur - essential for authentic flavor. Spiced rum and dark rum combination creates complexity. Cinnamon garnish adds aroma and visual appeal. Popular for Halloween and mysterious themed events. Can flame dark rum floater for theatrical presentation if desired.', 'mid', 60, 'https://www.diffordsguide.com/cocktails/recipe/5241/voodoo-doctor', 'Modern tiki cocktail. Multiple recipe variations exist.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 227. Ward Eight


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('06106ff3-970f-47e5-8bbf-0037ac420ec7', 'ward-eight', 'j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9', '{"en":"Ward Eight"}'::jsonb, 'famous', NULL, '{"classic","vintage","famous","rye","whiskey","citrus","boston"}', '{"en":"Boston''s answer to the New York Sour, the Ward Eight combines rye whiskey with lemon, orange, and grenadine for a fruity, balanced cocktail with a beautiful sunset color. A forgotten classic that deserves rediscovery, it''s a testament to pre-Prohibition American cocktail creativity."}'::jsonb, '{"created_year":"1898","origin":{"city":"Boston","bar":"Locke-Ober Café","country":"USA"},"creator":{"name":"Tom Hussion (disputed)","profession":"bartender"},"story":{"en":"The Ward Eight was allegedly created in 1898 at Boston''s Locke-Ober Café by bartender Tom Hussion to celebrate the political victory of Martin Lomasney in Boston''s Ward 8 district. The story goes that Democratic party bosses gathered at the bar before the election results were announced, so confident of victory that they commissioned a new cocktail in advance. When Lomasney won, the Ward Eight was born. However, some historians question this origin story, noting that the cocktail didn''t appear in print until much later. Regardless of its true origins, the Ward Eight became a Boston institution and remains the city''s signature cocktail. It''s essentially a whiskey sour with the addition of orange juice and grenadine."},"named_after":{"en":"Named after Ward 8, a political district in Boston where Martin Lomasney won a significant election in 1898."}}'::jsonb, '{"profile":["citrus","fruity","balanced"],"description":{"en":"Bright, fruity, and beautifully balanced. The Ward Eight combines the spicy warmth of rye whiskey with the tartness of lemon, the sweetness of orange, and the pomegranate depth of grenadine. It''s a more complex, fruity take on the whiskey sour."},"first_impression":{"en":"Bright citrus and orange sweetness followed by rye spice"},"finish":{"en":"Medium finish with lingering rye spice, citrus, and subtle pomegranate notes"},"balance":{"en":"Well-balanced between tart lemon, sweet orange and grenadine, with rye providing spicy backbone"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["aperitivo","social","sophisticated","celebration"],"seasons":["spring","summer","autumn"],"food_pairings":{"en":"Pairs well with New England seafood, oysters, lobster rolls, clam chowder, and traditional American fare. Also excellent with barbecue and grilled meats."},"ideal_for":{"en":"Perfect for rye whiskey enthusiasts and cocktail historians. Ideal for those who enjoy fruity yet sophisticated sours. A must-try for anyone visiting Boston or exploring American cocktail heritage."}}'::jsonb, '[{"ingredient_id":"ING_RYE_WHISKEY","quantity":{"amount":60,"unit":"ml"},"display_name":"Rye whiskey","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_ORANGE_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh orange juice","notes":null},{"ingredient_id":"ING_GRENADINE","quantity":{"amount":7.5,"unit":"ml"},"display_name":"Grenadine","notes":null}]'::jsonb, 'shake', '{"en":"Pour all ingredients into a cocktail shaker filled with ice. Shake vigorously until well-chilled. Strain into a chilled cocktail glass. Garnish with orange slice and cherry."}'::jsonb, 'Cocktail glass (Coupe)', '{"en":"Orange slice and maraschino cherry"}'::jsonb, 'none', 'up', '{"ING_RYE_WHISKEY"}', '{"citrus","fruity","balanced"}', 22, 170, 'easy', 60, '{}', '{"alcohol"}', '{"vegetarian","vegan","pescatarian","gluten_free","nut_free","dairy_free"}', 0, '{"vegetarian","vegan","gluten-free"}', '{"spring","summer","autumn"}', '{"aperitivo","social","sophisticated","celebration"}', false, false, '{"ward-eight-original","bourbon-ward-eight"}', 'Use fresh juices - never bottled. Real grenadine is essential for proper flavor. Rye is traditional, but bourbon can substitute. Some recipes call for simple syrup in addition to grenadine - adjust based on guest preference. Shake hard to properly emulsify.', 'mid', 45, 'https://www.diffordsguide.com/cocktails/recipe/2375/ward-eight', 'Classic Boston cocktail, documented in various early 20th century cocktail books.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 228. Washington Apple


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('b871ea95-8b3b-4b76-a519-8582016b471f', 'washington-apple', 'washington_apple_shot_famous_whiskey_apple', '{"en":"Washington Apple"}'::jsonb, 'famous', NULL, '{"shot","shooter","famous","whiskey","apple","fruity","sweet"}', '{"en":"A sweet and fruity shooter combining Canadian whisky, sour apple schnapps, and cranberry juice. Named after Washington State, famous for its apple production, this shot delivers a perfect blend of whiskey warmth and tart apple flavor."}'::jsonb, '{"created_year":"1990s","origin":{"city":"Unknown","bar":"Unknown","country":"USA"},"story":{"en":"The Washington Apple shot gained popularity in the 1990s, likely created as a tribute to Washington State''s famous apple orchards. The combination of Crown Royal whisky with apple schnapps created a uniquely smooth and approachable shooter that became a bar staple across North America."},"named_after":{"en":"Named after Washington State, one of the largest apple-producing regions in the United States."}}'::jsonb, '{"profile":["sweet","fruity","smooth"],"description":{"en":"Smooth whiskey base with bright green apple tartness and a hint of cranberry. Sweet and approachable with just enough tartness to keep it interesting. The Crown Royal adds warmth and depth."},"first_impression":{"en":"Tart green apple with sweet whiskey undertones"},"finish":{"en":"Smooth, warming finish with lingering apple and cranberry notes"},"balance":{"en":"Well-balanced between sweet and tart with smooth whiskey warmth"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["party","celebration","nightlife","casual"],"seasons":["autumn","winter"],"food_pairings":{"en":"Pairs well with cheese platters, caramel desserts, or autumn-themed appetizers. Complements pork dishes and roasted nuts."},"ideal_for":{"en":"Perfect for whiskey drinkers who enjoy fruity, approachable shots. A great introduction to whiskey-based shooters for those who prefer sweeter drinks."}}'::jsonb, '[{"ingredient_id":"ING_CANADIAN_WHISKY","quantity":{"amount":20,"unit":"ml"},"display_name":"Canadian Whisky (Crown Royal)","notes":null},{"ingredient_id":"ING_SOUR_APPLE_SCHNAPPS","quantity":{"amount":20,"unit":"ml"},"display_name":"Sour Apple Schnapps","notes":null},{"ingredient_id":"ING_CRANBERRY_JUICE","quantity":{"amount":20,"unit":"ml"},"display_name":"Cranberry Juice","notes":null}]'::jsonb, 'shake', '{"en":"Add all ingredients to a cocktail shaker filled with ice. Shake well until chilled. Strain into a shot glass and serve immediately."}'::jsonb, 'Shot glass', '{"en":"Apple slice (optional)"}'::jsonb, 'none', 'shot', '{"ING_CANADIAN_WHISKY"}', '{"sweet","fruity","smooth"}', 22, 95, 'easy', 45, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","vegetarian","gluten-free","dairy-free"}', '{"autumn","winter"}', '{"party","celebration","nightlife","casual"}', false, false, '{"washington-apple-martini","canadian-apple","crown-apple-shot"}', 'Crown Royal is the traditional choice for this shot, but any Canadian whisky works. DeKuyper Sour Apple Pucker is the most common schnapps used. Can be served as a cocktail over ice in a rocks glass.', 'low', 75, 'https://www.liquor.com/recipes/washington-apple-shot/', 'Popular 1990s shooter featuring Crown Royal and apple schnapps.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 229. White Negroni


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('64ba6623-afc1-4018-98e9-c1518114dcf1', 'white-negroni', '7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a09', '{"en":"White Negroni"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","gin","bitter","aperitivo"}', '{"en":"A pale, elegant variation on the classic Negroni featuring gin, Suze (or gentian liqueur), and Lillet Blanc. The White Negroni offers a more subtle, floral bitterness compared to its red predecessor."}'::jsonb, '{"created_year":"2001","origin":{"city":"Paris","bar":"ECC Chiado","country":"France"},"creator":{"name":"Wayne Collins","profession":"bartender"},"story":{"en":"Created by bartender Wayne Collins in 2001 while working at ECC Chiado in Paris, the White Negroni was born during a Negroni Week event. Collins substituted Suze (a French gentian liqueur) for Campari and Lillet Blanc for sweet vermouth, creating a lighter, more elegant interpretation. The drink gained international recognition and became one of the most popular Negroni variations of the modern era."},"named_after":{"en":"Named \"White Negroni\" for its pale color, distinguishing it from the classic red Negroni."}}'::jsonb, '{"profile":["bitter","floral","herbal"],"description":{"en":"Refined and subtly bitter with floral complexity. Gin provides botanical backbone, Suze contributes elegant gentian bitterness, and Lillet Blanc adds floral sweetness and citrus notes. More delicate than the classic Negroni but equally sophisticated."},"first_impression":{"en":"Gentle bitterness and floral notes hit first, followed by gin botanicals and citrus"},"finish":{"en":"Clean, bitter finish with lingering floral and herbal notes"},"balance":{"en":"Perfectly balanced between bitter and sweet, more subtle than classic Negroni but equally complex"}}'::jsonb, '{"best_time":["late_afternoon","early_evening"],"occasions":["aperitivo","cocktail_hour","date_night"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with light appetizers, seafood, fresh cheeses, and vegetable-based dishes. The gentle bitterness makes it a perfect aperitivo."},"ideal_for":{"en":"Perfect for Negroni lovers seeking a lighter, more delicate variation. Ideal for those who appreciate bitter cocktails with floral complexity."}}'::jsonb, '[{"ingredient_id":"ING_GIN","quantity":{"amount":30,"unit":"ml"},"display_name":"Gin","notes":null},{"ingredient_id":"ING_SUZE","quantity":{"amount":30,"unit":"ml"},"display_name":"Suze (gentian liqueur)","notes":null},{"ingredient_id":"ING_LILLET_BLANC","quantity":{"amount":30,"unit":"ml"},"display_name":"Lillet Blanc","notes":null}]'::jsonb, 'stir', '{"en":"Add all ingredients to a mixing glass filled with ice. Stir until well-chilled, about 30 seconds. Strain into a rocks glass over a large ice cube. Express a lemon twist over the drink and use as garnish."}'::jsonb, 'Rocks glass', '{"en":"Lemon twist"}'::jsonb, 'large_cube', 'on_rocks', '{"ING_GIN"}', '{"bitter","floral","herbal"}', 24, 150, 'easy', 90, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 0, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"aperitivo","cocktail_hour","date_night"}', false, false, '{"negroni","negroni-sbagliato"}', 'Stir, don''t shake. Can substitute other gentian liqueurs if Suze unavailable. Use a large ice cube to minimize dilution. Express lemon oils over drink before adding twist.', 'mid', 80, 'Created by Wayne Collins, 2001', 'Modern variation on the classic Negroni. One of the most popular Negroni variations.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 230. White Russian


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('94060159-486d-4cfe-a7c5-57e211385d05', 'white-russian', 'white_russian_vodka_kahlua_cream', '{"en":"White Russian"}'::jsonb, 'famous', NULL, '{"creamy","dessert","famous","coffee","vodka-based"}', '{"en":"A creamy, sweet cocktail combining vodka, coffee liqueur, and fresh cream. Made famous by \"The Big Lebowski,\" the White Russian is the ultimate indulgent drink that blurs the line between cocktail and dessert."}'::jsonb, '{"created_year":"1960s","origin":{"city":"Unknown","country":"USA"},"story":{"en":"The White Russian emerged in the 1960s as a variation of the Black Russian (vodka and Kahlúa), with the addition of cream. While it enjoyed moderate popularity in the 1970s, the cocktail experienced a massive resurgence after appearing as the signature drink of Jeff Bridges'' character \"The Dude\" in the 1998 Coen Brothers film \"The Big Lebowski.\" The movie popularized the drink among a new generation, making it an icon of laid-back sophistication."},"named_after":{"en":"Named \"White Russian\" due to the addition of cream to the Black Russian, turning it white. The \"Russian\" refers to the vodka base."}}'::jsonb, '{"profile":["creamy","sweet","coffee"],"description":{"en":"Smooth and dessert-like with pronounced coffee flavors balanced by sweet cream and clean vodka. The texture is silky and indulgent, making it more of a treat than a traditional cocktail."},"first_impression":{"en":"Sweet coffee and cream dominate, with a smooth vodka backbone"},"finish":{"en":"Lingering coffee sweetness with creamy texture"},"balance":{"en":"Rich and sweet, designed for dessert lovers rather than those seeking balance"}}'::jsonb, '{"best_time":["evening","late_night"],"occasions":["digestivo","casual","movie_night","nightcap"],"seasons":["all_seasons"],"food_pairings":{"en":"Perfect with chocolate desserts, coffee cake, tiramisu, or as a dessert replacement. Also pairs well with vanilla ice cream and brownie."},"ideal_for":{"en":"Perfect for coffee lovers who enjoy sweet, creamy cocktails. A must-try for fans of \"The Big Lebowski.\" Ideal for those who want a relaxing, indulgent drink without too much alcohol bite."}}'::jsonb, '[{"ingredient_id":"ING_VODKA","quantity":{"amount":50,"unit":"ml"},"display_name":"Vodka","notes":null},{"ingredient_id":"ING_COFFEE_LIQUEUR","quantity":{"amount":25,"unit":"ml"},"display_name":"Coffee liqueur (Kahlúa)","notes":null},{"ingredient_id":"ING_HEAVY_CREAM","quantity":{"amount":25,"unit":"ml"},"display_name":"Fresh cream","notes":null}]'::jsonb, 'build', '{"en":"Fill an Old Fashioned glass with ice. Pour vodka and coffee liqueur over ice. Gently float cream on top by pouring over the back of a spoon. Stir gently before drinking, or enjoy layered."}'::jsonb, 'Old Fashioned', '{"en":"None (or coffee beans optional)"}'::jsonb, 'cubes', 'on_the_rocks', '{"ING_VODKA"}', '{"creamy","sweet","coffee"}', 16, 250, 'easy', 45, '{"milk"}', '{"lactose","alcohol","caffeine"}', '{"vegetarian","pescatarian","gluten_free","nut_free"}', 0, '{"vegetarian","gluten-free"}', '{"all-seasons"}', '{"digestivo","casual","nightcap"}', false, false, '{"black-russian","white-cuban","dirty-russian"}', 'The Dude from "The Big Lebowski" made this drink iconic. Can be built directly in glass or shaken for a frothier texture. Some guests prefer it stirred, others layered. Use good quality coffee liqueur for best results.', 'mid', 85, 'https://www.liquor.com/recipes/white-russian/', 'Classic recipe popularized by "The Big Lebowski" (1998).', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


-- 231. Wildest Redhead


INSERT INTO cocktails (id, slug, stable_key, name, status, iba_category, tags, description, history, taste, recommendations, ingredients, method, instructions, glass, garnish, ice, serving_style, base_spirits, flavor_profile, abv_estimate, calories_estimate, difficulty, prep_time_seconds, computed_allergens, computed_intolerances, computed_diets, computed_spice_level, diet_tags, season_tags, occasion_tags, is_mocktail, is_signature, variants, notes_for_staff, price_tier, popularity, source_url, source_note, version)
VALUES ('0e65dd3d-0085-44c8-b040-e91f5c44b075', 'wildest-redhead', '6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a10', '{"en":"Wildest Redhead"}'::jsonb, 'famous', NULL, '{"modern","classic","famous","bourbon","fruity","spicy"}', '{"en":"A bold bourbon cocktail featuring ginger liqueur, strawberry, lemon juice, and Peychaud''s bitters. The Wildest Redhead is a spicy, fruity drink with a beautiful pink hue and complex flavor profile."}'::jsonb, '{"created_year":"2008","origin":{"city":"New York City","bar":"Pegu Club","country":"USA"},"creator":{"name":"Toby Maloney","profession":"bartender"},"story":{"en":"Created by Toby Maloney at the legendary Pegu Club in New York City in 2008, the Wildest Redhead was designed as a bold, feminine cocktail that plays with strawberry and ginger flavors. Maloney combined bourbon with muddled strawberries and ginger liqueur, creating a drink that balances fruit, spice, and spirit strength. The cocktail''s vibrant color and bold flavor profile made it an instant hit and it quickly became a modern classic."},"named_after":{"en":"Named for its fiery red color (from strawberries) and bold, spicy character (from ginger), evoking the passionate spirit of a \"wild redhead.\""}}'::jsonb, '{"profile":["fruity","spicy","sweet"],"description":{"en":"Bold and fruity with warming spice. Bourbon provides a rich, oaky backbone, fresh strawberries add sweet-tart fruit notes, ginger liqueur contributes spicy warmth, and lemon juice brings bright acidity. Peychaud''s bitters add aromatic complexity."},"first_impression":{"en":"Sweet strawberry and spicy ginger hit first, followed by bourbon warmth and citrus"},"finish":{"en":"Warming finish with lingering spice and fruit notes"},"balance":{"en":"Well-balanced between sweet fruit and spicy heat, with bourbon providing structure"}}'::jsonb, '{"best_time":["evening","late_afternoon"],"occasions":["date_night","cocktail_hour","summer_party"],"seasons":["spring","summer"],"food_pairings":{"en":"Excellent with spicy dishes, grilled meats, berry desserts, and dark chocolate. The fruit and spice complement bold, flavorful foods."},"ideal_for":{"en":"Perfect for bourbon lovers who enjoy fruity, spicy cocktails. Ideal for those seeking something bold and distinctive."}}'::jsonb, '[{"ingredient_id":"ING_BOURBON","quantity":{"amount":60,"unit":"ml"},"display_name":"Bourbon","notes":null},{"ingredient_id":"ING_GINGER_LIQUEUR","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Ginger liqueur","notes":null},{"ingredient_id":"ING_LEMON_JUICE","quantity":{"amount":22.5,"unit":"ml"},"display_name":"Fresh lemon juice","notes":null},{"ingredient_id":"ING_STRAWBERRIES","quantity":{"amount":3,"unit":"pieces"},"display_name":"Fresh strawberries","notes":null},{"ingredient_id":"ING_PEYCHAUDS_BITTERS","quantity":{"amount":2,"unit":"dashes"},"display_name":"Peychaud''s bitters","notes":null}]'::jsonb, 'muddle_shake', '{"en":"Muddle strawberries in a shaker. Add bourbon, ginger liqueur, lemon juice, bitters, and ice. Shake vigorously until well-chilled. Double strain into a chilled coupe glass. Garnish with a strawberry slice."}'::jsonb, 'Coupe', '{"en":"Fresh strawberry slice"}'::jsonb, 'none', 'up', '{"ING_BOURBON"}', '{"fruity","spicy","sweet"}', 18, 180, 'medium', 120, '{"sulphites"}', '{"alcohol","sulphites_intolerance"}', '{"vegan","vegetarian","pescatarian","gluten_free","dairy_free","nut_free"}', 2, '{"vegan","gluten-free","dairy-free"}', '{"spring","summer"}', '{"date_night","cocktail_hour","summer_party"}', false, false, '{"whiskey-smash","strawberry-basil-smash"}', 'Use fresh, ripe strawberries for best flavor. Muddle gently to avoid bitterness. Double strain to remove strawberry seeds and pulp. Can rim glass with sugar for extra sweetness.', 'mid', 74, 'Created by Toby Maloney at Pegu Club, 2008', 'Modern classic cocktail. Featured in craft cocktail publications.', 1)
ON CONFLICT (slug) DO UPDATE SET
  id = EXCLUDED.id,
  stable_key = EXCLUDED.stable_key,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  iba_category = EXCLUDED.iba_category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  history = EXCLUDED.history,
  taste = EXCLUDED.taste,
  recommendations = EXCLUDED.recommendations,
  ingredients = EXCLUDED.ingredients,
  method = EXCLUDED.method,
  instructions = EXCLUDED.instructions,
  glass = EXCLUDED.glass,
  garnish = EXCLUDED.garnish,
  ice = EXCLUDED.ice,
  serving_style = EXCLUDED.serving_style,
  base_spirits = EXCLUDED.base_spirits,
  flavor_profile = EXCLUDED.flavor_profile,
  abv_estimate = EXCLUDED.abv_estimate,
  calories_estimate = EXCLUDED.calories_estimate,
  difficulty = EXCLUDED.difficulty,
  prep_time_seconds = EXCLUDED.prep_time_seconds,
  computed_allergens = EXCLUDED.computed_allergens,
  computed_intolerances = EXCLUDED.computed_intolerances,
  computed_diets = EXCLUDED.computed_diets,
  computed_spice_level = EXCLUDED.computed_spice_level,
  diet_tags = EXCLUDED.diet_tags,
  season_tags = EXCLUDED.season_tags,
  occasion_tags = EXCLUDED.occasion_tags,
  is_mocktail = EXCLUDED.is_mocktail,
  is_signature = EXCLUDED.is_signature,
  variants = EXCLUDED.variants,
  notes_for_staff = EXCLUDED.notes_for_staff,
  price_tier = EXCLUDED.price_tier,
  popularity = EXCLUDED.popularity,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  version = EXCLUDED.version,
  updated_at = NOW();


