-- ============================================
-- POLISH CUISINE - Data Import
-- GUDBRO Database Standards v1.7
-- Total: 42 dishes
-- ============================================

-- ============================================
-- PIEROGI (8 dishes)
-- ============================================

INSERT INTO polish (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('POL_PIEROGI_RUSKIE', 'pierogi-ruskie', 'Pierogi Ruskie', 'Pierogi Ruskie', 'Classic Polish dumplings filled with mashed potato, farmer cheese, and fried onions. The most beloved pierogi variety.', 'dumplings', 'nationwide', 'classic', NULL, 'boiled', 60, 0, 12.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'milk', 'eggs'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_POTATO', 'ING_FARMERS_CHEESE', 'ING_ONION', 'ING_BUTTER', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY['iconic', 'vegetarian', 'comfort-food', 'dumplings'], 98),

('POL_PIEROGI_MEAT', 'pierogi-z-miesem', 'Meat Pierogi', 'Pierogi z Mięsem', 'Traditional dumplings filled with seasoned minced pork and beef, onions, and spices. Hearty and satisfying.', 'dumplings', 'nationwide', 'classic', 'mixed', 'boiled', 75, 1, 14.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_PORK', 'ING_BEEF', 'ING_ONION', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_MARJORAM'], ARRAY['hearty', 'meat', 'traditional'], 90),

('POL_PIEROGI_CABBAGE', 'pierogi-z-kapusta', 'Cabbage and Mushroom Pierogi', 'Pierogi z Kapustą i Grzybami', 'Traditional Christmas Eve pierogi filled with sauerkraut and dried forest mushrooms. A Wigilia essential.', 'dumplings', 'nationwide', 'traditional', NULL, 'boiled', 90, 0, 13.00, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_SAUERKRAUT', 'ING_DRIED_MUSHROOM', 'ING_ONION', 'ING_VEGETABLE_OIL', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY['christmas', 'vegan', 'wigilia', 'traditional'], 88),

('POL_PIEROGI_BLUEBERRY', 'pierogi-z-jagodami', 'Blueberry Pierogi', 'Pierogi z Jagodami', 'Sweet dumplings filled with fresh blueberries, served with sour cream and sugar. Summer favorite.', 'dumplings', 'nationwide', 'traditional', NULL, 'boiled', 45, 0, 14.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'milk', 'eggs'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_BLUEBERRY', 'ING_SUGAR', 'ING_SOUR_CREAM', 'ING_BUTTER'], ARRAY['sweet', 'summer', 'dessert-pierogi', 'fruit'], 82),

('POL_PIEROGI_STRAWBERRY', 'pierogi-z-truskawkami', 'Strawberry Pierogi', 'Pierogi z Truskawkami', 'Sweet dumplings filled with fresh strawberries, dusted with powdered sugar and served with cream.', 'dumplings', 'nationwide', 'popular', NULL, 'boiled', 45, 0, 14.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'milk', 'eggs'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_STRAWBERRY', 'ING_SUGAR', 'ING_POWDERED_SUGAR', 'ING_CREAM'], ARRAY['sweet', 'summer', 'dessert-pierogi', 'fruit'], 80),

('POL_PIEROGI_CHEESE', 'pierogi-z-serem', 'Sweet Cheese Pierogi', 'Pierogi z Serem', 'Sweet dumplings filled with sweetened farmer cheese, served with melted butter and sugar.', 'dumplings', 'nationwide', 'traditional', NULL, 'boiled', 50, 0, 12.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'milk', 'eggs'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_FARMERS_CHEESE', 'ING_SUGAR', 'ING_BUTTER', 'ING_VANILLA'], ARRAY['sweet', 'cheese', 'comfort-food'], 78),

('POL_PIEROGI_SPINACH', 'pierogi-ze-szpinakiem', 'Spinach and Feta Pierogi', 'Pierogi ze Szpinakiem i Fetą', 'Modern pierogi filled with spinach, feta cheese, and garlic. A contemporary vegetarian option.', 'dumplings', 'nationwide', 'popular', NULL, 'boiled', 55, 0, 13.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'milk', 'eggs'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_SPINACH', 'ING_FETA', 'ING_GARLIC', 'ING_BUTTER', 'ING_SALT'], ARRAY['vegetarian', 'modern', 'spinach'], 72),

('POL_USZKA', 'uszka', 'Uszka', 'Uszka', 'Tiny ear-shaped dumplings filled with wild mushrooms, traditionally served in barszcz on Christmas Eve.', 'dumplings', 'nationwide', 'traditional', NULL, 'boiled', 90, 0, 10.00, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_DRIED_MUSHROOM', 'ING_ONION', 'ING_VEGETABLE_OIL', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY['christmas', 'wigilia', 'barszcz', 'tiny-dumplings'], 85)

ON CONFLICT (id) DO NOTHING;

-- ============================================
-- SOUPS (8 dishes)
-- ============================================

INSERT INTO polish (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('POL_ZUREK', 'zurek', 'Zurek', 'Żurek', 'Traditional sour rye soup with white sausage, hard-boiled eggs, and potatoes. Served in a bread bowl or plate.', 'soups', 'nationwide', 'classic', 'pork', 'stewed', 45, 0, 10.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_RYE_FLOUR', 'ING_WHITE_SAUSAGE', 'ING_EGG', 'ING_POTATO', 'ING_GARLIC', 'ING_MARJORAM', 'ING_BAY_LEAF', 'ING_HORSERADISH'], ARRAY['iconic', 'easter', 'sour', 'fermented'], 95),

('POL_BARSZCZ_CZERWONY', 'barszcz-czerwony', 'Red Borscht', 'Barszcz Czerwony', 'Clear beetroot soup with a deep ruby color. Served with uszka dumplings on Christmas Eve or with sour cream.', 'soups', 'nationwide', 'classic', NULL, 'stewed', 60, 0, 9.00, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_BEET', 'ING_CARROT', 'ING_CELERY', 'ING_ONION', 'ING_GARLIC', 'ING_BAY_LEAF', 'ING_ALLSPICE', 'ING_VINEGAR'], ARRAY['iconic', 'christmas', 'wigilia', 'beetroot', 'vegan'], 92),

('POL_BARSZCZ_BIALY', 'barszcz-bialy', 'White Borscht', 'Barszcz Biały', 'Creamy sour soup similar to zurek but made with wheat flour. Served with white sausage and egg.', 'soups', 'silesia', 'traditional', 'pork', 'stewed', 40, 0, 10.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'eggs', 'milk'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_WHITE_SAUSAGE', 'ING_EGG', 'ING_SOUR_CREAM', 'ING_POTATO', 'ING_GARLIC', 'ING_MARJORAM'], ARRAY['silesian', 'sour', 'creamy', 'easter'], 78),

('POL_ROSOL', 'rosol', 'Rosol', 'Rosół', 'Clear golden chicken broth with thin noodles. The Sunday dinner staple of Polish families.', 'soups', 'nationwide', 'classic', 'chicken', 'boiled', 180, 0, 8.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten'], ARRAY[]::TEXT[], ARRAY['ING_CHICKEN', 'ING_CARROT', 'ING_CELERY', 'ING_PARSLEY_ROOT', 'ING_LEEK', 'ING_ONION', 'ING_EGG_NOODLE', 'ING_BAY_LEAF', 'ING_ALLSPICE'], ARRAY['sunday-dinner', 'comfort-food', 'family', 'chicken-soup'], 90),

('POL_KAPUSNIAK', 'kapusniak', 'Kapusniak', 'Kapuśniak', 'Hearty sauerkraut soup with pork ribs, potatoes, and vegetables. A warming winter favorite.', 'soups', 'nationwide', 'traditional', 'pork', 'stewed', 90, 0, 9.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_SAUERKRAUT', 'ING_PORK_RIBS', 'ING_POTATO', 'ING_CARROT', 'ING_ONION', 'ING_BAY_LEAF', 'ING_ALLSPICE', 'ING_BLACK_PEPPER'], ARRAY['winter', 'hearty', 'sauerkraut', 'comfort-food'], 75),

('POL_GROCHOWKA', 'grochowka', 'Grochowka', 'Grochówka', 'Thick split pea soup with smoked bacon and sausage. Traditional army soup, very filling.', 'soups', 'nationwide', 'traditional', 'pork', 'stewed', 120, 0, 9.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_SPLIT_PEA', 'ING_BACON', 'ING_KIELBASA', 'ING_POTATO', 'ING_CARROT', 'ING_ONION', 'ING_MARJORAM', 'ING_BAY_LEAF'], ARRAY['army-soup', 'hearty', 'split-pea', 'filling'], 72),

('POL_POMIDOROWA', 'zupa-pomidorowa', 'Tomato Soup', 'Zupa Pomidorowa', 'Creamy tomato soup served with rice or noodles. A childhood favorite in Polish homes.', 'soups', 'nationwide', 'popular', NULL, 'stewed', 30, 0, 7.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'milk'], ARRAY['lactose'], ARRAY['ING_TOMATO', 'ING_CHICKEN_STOCK', 'ING_CREAM', 'ING_RICE', 'ING_ONION', 'ING_BUTTER', 'ING_SUGAR', 'ING_SALT'], ARRAY['childhood', 'comfort-food', 'simple', 'creamy'], 85),

('POL_OGORKOWA', 'zupa-ogorkowa', 'Pickle Soup', 'Zupa Ogórkowa', 'Tangy soup made with pickled cucumbers and potatoes in a creamy broth. Uniquely Polish.', 'soups', 'nationwide', 'traditional', NULL, 'stewed', 45, 0, 8.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['milk'], ARRAY['lactose'], ARRAY['ING_PICKLED_CUCUMBER', 'ING_POTATO', 'ING_CARROT', 'ING_SOUR_CREAM', 'ING_DILL', 'ING_ONION', 'ING_VEGETABLE_STOCK'], ARRAY['pickle', 'tangy', 'unique', 'creamy'], 70)

ON CONFLICT (id) DO NOTHING;

-- ============================================
-- MAINS (10 dishes)
-- ============================================

INSERT INTO polish (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('POL_BIGOS', 'bigos', 'Bigos', 'Bigos', 'Hunter''s stew made with sauerkraut, fresh cabbage, various meats, and dried mushrooms. Improves over days.', 'mains', 'nationwide', 'classic', 'mixed', 'stewed', 180, 1, 16.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_SAUERKRAUT', 'ING_CABBAGE', 'ING_PORK', 'ING_KIELBASA', 'ING_BACON', 'ING_DRIED_MUSHROOM', 'ING_ONION', 'ING_TOMATO_PASTE', 'ING_BAY_LEAF', 'ING_ALLSPICE', 'ING_PRUNE'], ARRAY['iconic', 'hunters-stew', 'christmas', 'slow-cooked'], 95),

('POL_GOLABKI', 'golabki', 'Golabki', 'Gołąbki', 'Cabbage rolls stuffed with minced pork and rice, baked in tomato sauce. Comfort food classic.', 'mains', 'nationwide', 'classic', 'pork', 'baked', 90, 0, 14.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_CABBAGE', 'ING_PORK', 'ING_RICE', 'ING_ONION', 'ING_TOMATO_SAUCE', 'ING_EGG', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY['iconic', 'cabbage-rolls', 'comfort-food', 'home-cooking'], 92),

('POL_KOTLET_SCHABOWY', 'kotlet-schabowy', 'Kotlet Schabowy', 'Kotlet Schabowy', 'Breaded pork cutlet, similar to Wiener schnitzel. Served with mashed potatoes and cabbage salad.', 'mains', 'nationwide', 'classic', 'pork', 'fried', 30, 0, 15.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'eggs', 'milk'], ARRAY[]::TEXT[], ARRAY['ING_PORK_LOIN', 'ING_BREADCRUMB', 'ING_EGG', 'ING_FLOUR', 'ING_BUTTER', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY['iconic', 'schnitzel', 'fried', 'sunday-dinner'], 94),

('POL_KOTLET_MIELONY', 'kotlet-mielony', 'Kotlet Mielony', 'Kotlet Mielony', 'Polish minced meat cutlets made with pork and beef, breadcrumbs, and onion. Pan-fried until golden.', 'mains', 'nationwide', 'traditional', 'mixed', 'fried', 40, 0, 13.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_PORK', 'ING_BEEF', 'ING_BREADCRUMB', 'ING_EGG', 'ING_ONION', 'ING_GARLIC', 'ING_SALT', 'ING_BLACK_PEPPER', 'ING_MARJORAM'], ARRAY['meatballs', 'home-cooking', 'comfort-food'], 80),

('POL_ZRAZY', 'zrazy-zawijane', 'Zrazy Zawijane', 'Zrazy Zawijane', 'Beef roulades stuffed with bacon, pickled cucumber, and mustard. Braised in rich gravy.', 'mains', 'nationwide', 'traditional', 'beef', 'braised', 120, 0, 18.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_BEEF_STEAK', 'ING_BACON', 'ING_PICKLED_CUCUMBER', 'ING_MUSTARD', 'ING_ONION', 'ING_CARROT', 'ING_BAY_LEAF', 'ING_ALLSPICE'], ARRAY['beef-roulades', 'braised', 'elegant', 'sunday-dinner'], 75),

('POL_GULASZ', 'gulasz-wieprzowy', 'Pork Goulash', 'Gulasz Wieprzowy', 'Polish-style pork goulash with paprika, onions, and peppers. Served with dumplings or bread.', 'mains', 'nationwide', 'popular', 'pork', 'stewed', 90, 1, 15.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_PORK', 'ING_ONION', 'ING_BELL_PEPPER', 'ING_PAPRIKA', 'ING_TOMATO_PASTE', 'ING_GARLIC', 'ING_BAY_LEAF', 'ING_CARAWAY'], ARRAY['goulash', 'stew', 'paprika', 'comfort-food'], 78),

('POL_KLUSKI_SLASKIE', 'kluski-slaskie', 'Silesian Dumplings', 'Kluski Śląskie', 'Soft potato dumplings with a characteristic indentation, served with meat sauce or gravy.', 'mains', 'silesia', 'regional', NULL, 'boiled', 45, 0, 12.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_POTATO', 'ING_POTATO_STARCH', 'ING_EGG', 'ING_SALT'], ARRAY['silesian', 'dumplings', 'regional', 'potato'], 70),

('POL_KACZKA', 'kaczka-z-jablkami', 'Roast Duck with Apples', 'Kaczka z Jabłkami', 'Whole roasted duck stuffed with apples and marjoram. Traditional holiday and celebration dish.', 'mains', 'nationwide', 'traditional', 'poultry', 'roasted', 180, 0, 28.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_DUCK', 'ING_APPLE', 'ING_MARJORAM', 'ING_ONION', 'ING_GARLIC', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY['holiday', 'roasted', 'celebration', 'duck'], 72),

('POL_SCHAB', 'schab-pieczony', 'Roast Pork Loin', 'Schab Pieczony', 'Slow-roasted pork loin with prunes and herbs. Served sliced with potatoes and red cabbage.', 'mains', 'nationwide', 'traditional', 'pork', 'roasted', 120, 0, 17.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_PORK_LOIN', 'ING_PRUNE', 'ING_GARLIC', 'ING_ONION', 'ING_MARJORAM', 'ING_SALT', 'ING_BLACK_PEPPER'], ARRAY['roast', 'sunday-dinner', 'pork-loin', 'traditional'], 82),

('POL_FLAKI', 'flaki-wolowe', 'Flaki', 'Flaki Wołowe', 'Traditional beef tripe soup with vegetables and marjoram. A polarizing Polish delicacy.', 'mains', 'nationwide', 'traditional', 'beef', 'stewed', 240, 1, 12.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_BEEF_TRIPE', 'ING_CARROT', 'ING_CELERY', 'ING_PARSLEY_ROOT', 'ING_ONION', 'ING_MARJORAM', 'ING_NUTMEG', 'ING_GINGER'], ARRAY['tripe', 'traditional', 'offal', 'acquired-taste'], 55)

ON CONFLICT (id) DO NOTHING;

-- ============================================
-- SIDES & STREET FOOD (8 dishes)
-- ============================================

INSERT INTO polish (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('POL_PLACKI_ZIEMNIACZANE', 'placki-ziemniaczane', 'Potato Pancakes', 'Placki Ziemniaczane', 'Crispy golden potato pancakes made from grated potatoes. Served with sour cream or goulash.', 'sides', 'nationwide', 'classic', NULL, 'fried', 30, 0, 10.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'milk'], ARRAY['lactose'], ARRAY['ING_POTATO', 'ING_EGG', 'ING_FLOUR', 'ING_ONION', 'ING_SOUR_CREAM', 'ING_VEGETABLE_OIL', 'ING_SALT'], ARRAY['iconic', 'potato-pancakes', 'crispy', 'comfort-food'], 90),

('POL_KOPYTKA', 'kopytka', 'Kopytka', 'Kopytka', 'Small hoof-shaped potato dumplings, similar to Italian gnocchi. Served with butter and breadcrumbs.', 'sides', 'nationwide', 'traditional', NULL, 'boiled', 40, 0, 9.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'milk'], ARRAY['lactose'], ARRAY['ING_POTATO', 'ING_FLOUR', 'ING_EGG', 'ING_BUTTER', 'ING_BREADCRUMB', 'ING_SALT'], ARRAY['dumplings', 'gnocchi-like', 'potato', 'comfort-food'], 75),

('POL_MIZERIA', 'mizeria', 'Mizeria', 'Mizeria', 'Fresh cucumber salad with sour cream and dill. The classic side dish to kotlet schabowy.', 'sides', 'nationwide', 'classic', NULL, 'raw', 10, 0, 6.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['milk'], ARRAY['lactose'], ARRAY['ING_CUCUMBER', 'ING_SOUR_CREAM', 'ING_DILL', 'ING_SALT', 'ING_WHITE_PEPPER', 'ING_SUGAR'], ARRAY['salad', 'cucumber', 'refreshing', 'side-dish'], 85),

('POL_SUROWKA', 'surowka-z-kapusty', 'Cabbage Salad', 'Surówka z Kapusty', 'Fresh shredded cabbage and carrot salad with vinegar dressing. Traditional side to fried dishes.', 'sides', 'nationwide', 'classic', NULL, 'raw', 15, 0, 5.00, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_CABBAGE', 'ING_CARROT', 'ING_VINEGAR', 'ING_VEGETABLE_OIL', 'ING_SUGAR', 'ING_SALT'], ARRAY['coleslaw', 'fresh', 'vegan', 'side-dish'], 80),

('POL_ZAPIEKANKA', 'zapiekanka', 'Zapiekanka', 'Zapiekanka', 'Polish street food: toasted baguette with mushrooms, cheese, and ketchup. The original Polish pizza.', 'street_food', 'nationwide', 'popular', NULL, 'baked', 15, 0, 8.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'milk'], ARRAY['lactose'], ARRAY['ING_BAGUETTE', 'ING_MUSHROOM', 'ING_CHEESE', 'ING_BUTTER', 'ING_KETCHUP', 'ING_CHIVES'], ARRAY['street-food', 'iconic', 'quick', 'toasted'], 88),

('POL_OSCYPEK', 'oscypek-grillowany', 'Grilled Oscypek', 'Oscypek z Grilla', 'Traditional smoked sheep cheese from Tatra Mountains, grilled and served with cranberry jam.', 'sides', 'podhale', 'regional', NULL, 'grilled', 10, 0, 12.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['milk'], ARRAY['lactose'], ARRAY['ING_OSCYPEK', 'ING_CRANBERRY_JAM'], ARRAY['tatra', 'mountain', 'smoked-cheese', 'regional'], 82),

('POL_KIELBASA_GRILLED', 'kielbasa-z-grilla', 'Grilled Kielbasa', 'Kiełbasa z Grilla', 'Classic Polish sausage grilled to perfection. Served with mustard and bread.', 'street_food', 'nationwide', 'classic', 'pork', 'grilled', 15, 1, 10.00, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['ING_KIELBASA', 'ING_MUSTARD', 'ING_BREAD'], ARRAY['sausage', 'street-food', 'grilled', 'iconic'], 92),

('POL_OBWARZANEK', 'obwarzanek', 'Obwarzanek', 'Obwarzanek Krakowski', 'Traditional Krakow-style braided ring bread, topped with poppy seeds, sesame, or salt.', 'street_food', 'malopolska', 'regional', NULL, 'baked', 5, 0, 3.00, '{"is_vegan": true, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'sesame'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_POPPY_SEED', 'ING_SESAME', 'ING_SALT', 'ING_SUGAR'], ARRAY['krakow', 'bread-ring', 'street-food', 'snack'], 78)

ON CONFLICT (id) DO NOTHING;

-- ============================================
-- DESSERTS (8 dishes)
-- ============================================

INSERT INTO polish (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, price_default, dietary, allergens, intolerances, ingredient_ids, tags, popularity)
VALUES
('POL_PACZKI', 'paczki', 'Paczki', 'Pączki', 'Traditional Polish filled doughnuts, deep-fried and glazed. Eaten on Fat Thursday before Lent.', 'desserts', 'nationwide', 'classic', NULL, 'fried', 180, 0, 4.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'eggs', 'milk'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_BUTTER', 'ING_SUGAR', 'ING_YEAST', 'ING_MILK', 'ING_ROSE_JAM', 'ING_POWDERED_SUGAR', 'ING_VEGETABLE_OIL'], ARRAY['iconic', 'fat-thursday', 'doughnuts', 'carnival'], 95),

('POL_SERNIK', 'sernik', 'Polish Cheesecake', 'Sernik', 'Dense, creamy cheesecake made with twarog (farmer cheese). Often topped with chocolate or fruit.', 'desserts', 'nationwide', 'classic', NULL, 'baked', 90, 0, 8.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'milk'], ARRAY['lactose'], ARRAY['ING_FARMERS_CHEESE', 'ING_EGG', 'ING_SUGAR', 'ING_BUTTER', 'ING_FLOUR', 'ING_VANILLA', 'ING_LEMON_ZEST'], ARRAY['iconic', 'cheesecake', 'creamy', 'christmas'], 92),

('POL_MAKOWIEC', 'makowiec', 'Poppy Seed Roll', 'Makowiec', 'Sweet yeast bread roll filled with poppy seed paste, honey, and raisins. Christmas tradition.', 'desserts', 'nationwide', 'traditional', NULL, 'baked', 180, 0, 10.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": false, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'eggs', 'milk', 'nuts'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_POPPY_SEED', 'ING_HONEY', 'ING_RAISIN', 'ING_WALNUT', 'ING_EGG', 'ING_BUTTER', 'ING_SUGAR', 'ING_YEAST'], ARRAY['christmas', 'poppy-seed', 'rolled-cake', 'wigilia'], 88),

('POL_SZARLOTKA', 'szarlotka', 'Polish Apple Pie', 'Szarlotka', 'Double-crusted apple pie with cinnamon. Served warm with whipped cream or vanilla ice cream.', 'desserts', 'nationwide', 'classic', NULL, 'baked', 75, 0, 7.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'milk'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_APPLE', 'ING_BUTTER', 'ING_SUGAR', 'ING_EGG', 'ING_CINNAMON', 'ING_BREADCRUMB'], ARRAY['apple-pie', 'autumn', 'comfort-food', 'warm'], 90),

('POL_KREMOWKA', 'kremowka', 'Kremowka', 'Kremówka Papieska', 'Puff pastry slice filled with vanilla custard cream. Made famous by Pope John Paul II.', 'desserts', 'malopolska', 'popular', NULL, 'baked', 60, 0, 6.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'milk'], ARRAY['lactose'], ARRAY['ING_PUFF_PASTRY', 'ING_MILK', 'ING_EGG_YOLK', 'ING_SUGAR', 'ING_VANILLA', 'ING_CORNSTARCH', 'ING_POWDERED_SUGAR'], ARRAY['papal', 'wadowice', 'custard', 'puff-pastry'], 85),

('POL_RACUCHY', 'racuchy', 'Racuchy', 'Racuchy z Jabłkami', 'Fluffy apple fritters, pan-fried and dusted with powdered sugar. Perfect autumn treat.', 'desserts', 'nationwide', 'traditional', NULL, 'fried', 30, 0, 8.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'milk'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_APPLE', 'ING_EGG', 'ING_MILK', 'ING_YEAST', 'ING_SUGAR', 'ING_POWDERED_SUGAR', 'ING_VEGETABLE_OIL'], ARRAY['fritters', 'apple', 'autumn', 'fluffy'], 75),

('POL_NALESNIKI', 'nalesniki', 'Nalesniki', 'Naleśniki', 'Thin Polish crepes filled with sweet cheese, fruit jam, or chocolate. Rolled and served warm.', 'desserts', 'nationwide', 'classic', NULL, 'fried', 30, 0, 10.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs', 'milk'], ARRAY['lactose'], ARRAY['ING_FLOUR', 'ING_EGG', 'ING_MILK', 'ING_FARMERS_CHEESE', 'ING_SUGAR', 'ING_BUTTER', 'ING_VANILLA'], ARRAY['crepes', 'sweet', 'versatile', 'comfort-food'], 88),

('POL_PIERNIK', 'piernik', 'Polish Gingerbread', 'Piernik Toruński', 'Traditional spiced honey gingerbread cake from Torun. Dense, aromatic, and filled with plum jam.', 'desserts', 'wielkopolska', 'regional', NULL, 'baked', 120, 1, 12.00, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": true}', ARRAY['gluten', 'eggs'], ARRAY[]::TEXT[], ARRAY['ING_FLOUR', 'ING_HONEY', 'ING_EGG', 'ING_GINGER', 'ING_CINNAMON', 'ING_CLOVE', 'ING_NUTMEG', 'ING_PLUM_JAM', 'ING_COCOA'], ARRAY['torun', 'gingerbread', 'christmas', 'spiced'], 80)

ON CONFLICT (id) DO NOTHING;
