-- Indonesian Cuisine - New Ingredients
-- GUDBRO Database Standards v1.7
-- Generated by inventory-checker agent
-- Total: 5 new ingredients

-- =====================================================
-- INSERT NEW INGREDIENTS
-- =====================================================

INSERT INTO ingredients (id, name, slug, category)
VALUES
  -- Proteins/Offal
  ('ING_BEEF_BRAIN', 'Beef Brain', 'beef-brain', 'proteins'),

  -- Indonesian specific ingredients
  ('ING_CANDLENUT', 'Candlenut (Kemiri)', 'candlenut', 'nuts'),
  ('ING_FRIED_CHICKEN', 'Fried Chicken', 'fried-chicken', 'proteins'),
  ('ING_KELUAK', 'Keluak Nut (Pangium Edule)', 'keluak', 'nuts'),
  ('ING_LONTONG', 'Lontong (Compressed Rice Cake)', 'lontong', 'grains')
ON CONFLICT (id) DO NOTHING;

-- =====================================================
-- VERIFICATION
-- =====================================================
-- Run after insert:
-- SELECT id, name, category FROM ingredients
-- WHERE id IN ('ING_BEEF_BRAIN', 'ING_CANDLENUT', 'ING_FRIED_CHICKEN', 'ING_KELUAK', 'ING_LONTONG');
