/**
 * GUDBRO Cocktail Ingredients - Amari & Vermouth
 *
 * Bitter liqueurs and aromatized wines with complete 5 Dimensioni data.
 *
 * Categories:
 * - Italian Amari (Campari, Aperol, Averna, Montenegro, Fernet)
 * - Vermouth (Sweet, Dry, Bianco, Rosé)
 * - Other Aperitivi (Cynar, Punt e Mes, Lillet)
 *
 * @version 1.0
 * @lastUpdated 2025-12-13
 */

import type { IngredientMaster } from '../../types';

const baseAmariFlags = {
  vegan: true,
  vegetarian: true,
  pescatarian: true,
  gluten_free: true,
  dairy_free: true,
  nut_free: true,
  low_carb: false,
  halal: false,
  kosher: true,
};

export const amariVermouthIngredients: IngredientMaster[] = [
  // ========================================================================
  // ITALIAN AMARI - APERITIVO
  // ========================================================================
  {
    id: 'ING_CAMPARI',
    slug: 'campari',
    name: {
      en: 'Campari',
      it: 'Campari',
      vi: 'Campari',
      ko: '캄파리',
      ja: 'カンパリ',
    },
    description: {
      en: 'Iconic Italian bitter aperitivo, essential for Negroni and Americano',
      it: 'Iconico aperitivo amaro italiano, essenziale per Negroni e Americano',
    },
    category: { main: 'amari', sub: 'aperitivo' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 8,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 80,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_APEROL',
    slug: 'aperol',
    name: {
      en: 'Aperol',
      it: 'Aperol',
      vi: 'Aperol',
      ko: '아페롤',
      ja: 'アペロール',
    },
    description: {
      en: 'Lower-alcohol bitter orange aperitivo, essential for Aperol Spritz',
      it: 'Aperitivo amaro all\'arancia a bassa gradazione, essenziale per Aperol Spritz',
    },
    category: { main: 'amari', sub: 'aperitivo' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 10,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 70,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_SELECT_APERITIVO',
    slug: 'select-aperitivo',
    name: {
      en: 'Select Aperitivo',
      it: 'Select Aperitivo',
      vi: 'Select Aperitivo',
      ko: '셀렉트 아페리티보',
      ja: 'セレクトアペリティーボ',
    },
    description: {
      en: 'Venetian bitter aperitivo, original spritz ingredient',
      it: 'Aperitivo amaro veneziano, ingrediente originale dello spritz',
    },
    category: { main: 'amari', sub: 'aperitivo' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 9,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 75,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // ITALIAN AMARI - DIGESTIVO
  // ========================================================================
  {
    id: 'ING_AVERNA',
    slug: 'averna',
    name: {
      en: 'Amaro Averna',
      it: 'Amaro Averna',
      vi: 'Amaro Averna',
      ko: '아마로 아베르나',
      ja: 'アマーロ・アヴェルナ',
    },
    description: {
      en: 'Sicilian amaro with orange and herb notes',
      it: 'Amaro siciliano con note di arancia ed erbe',
    },
    category: { main: 'amari', sub: 'digestivo' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 14,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 98,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_MONTENEGRO',
    slug: 'amaro-montenegro',
    name: {
      en: 'Amaro Montenegro',
      it: 'Amaro Montenegro',
      vi: 'Amaro Montenegro',
      ko: '아마로 몬테네그로',
      ja: 'アマーロ・モンテネグロ',
    },
    description: {
      en: 'Bolognese amaro, balanced and aromatic',
      it: 'Amaro bolognese, bilanciato e aromatico',
    },
    category: { main: 'amari', sub: 'digestivo' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 13,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 95,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_FERNET_BRANCA',
    slug: 'fernet-branca',
    name: {
      en: 'Fernet-Branca',
      it: 'Fernet-Branca',
      vi: 'Fernet-Branca',
      ko: '페르넷 브랑카',
      ja: 'フェルネット・ブランカ',
    },
    description: {
      en: 'Intensely bitter Italian amaro with menthol notes',
      it: 'Amaro italiano intensamente amaro con note di mentolo',
    },
    category: { main: 'amari', sub: 'digestivo' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 11,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 88,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_AMARO_NONINO',
    slug: 'amaro-nonino',
    name: {
      en: 'Amaro Nonino',
      it: 'Amaro Nonino',
      vi: 'Amaro Nonino',
      ko: '아마로 노니노',
      ja: 'アマーロ・ノニーノ',
    },
    description: {
      en: 'Grappa-based amaro from Friuli, refined and complex',
      it: 'Amaro a base di grappa dal Friuli, raffinato e complesso',
    },
    category: { main: 'amari', sub: 'digestivo' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 10,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 92,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_AMARO_LUCANO',
    slug: 'amaro-lucano',
    name: {
      en: 'Amaro Lucano',
      it: 'Amaro Lucano',
      vi: 'Amaro Lucano',
      ko: '아마로 루카노',
      ja: 'アマーロ・ルカーノ',
    },
    description: {
      en: 'Southern Italian amaro from Basilicata',
      it: 'Amaro del Sud Italia dalla Basilicata',
    },
    category: { main: 'amari', sub: 'digestivo' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 13,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 95,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CYNAR',
    slug: 'cynar',
    name: {
      en: 'Cynar',
      it: 'Cynar',
      vi: 'Cynar',
      ko: '치나르',
      ja: 'チナール',
    },
    description: {
      en: 'Artichoke-based Italian amaro',
      it: 'Amaro italiano a base di carciofo',
    },
    category: { main: 'amari', sub: 'digestivo' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 12,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 90,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RAMAZZOTTI',
    slug: 'ramazzotti',
    name: {
      en: 'Ramazzotti',
      it: 'Ramazzotti',
      vi: 'Ramazzotti',
      ko: '라마조티',
      ja: 'ラマツォッティ',
    },
    description: {
      en: 'Milanese amaro with 33 herbs and roots',
      it: 'Amaro milanese con 33 erbe e radici',
    },
    category: { main: 'amari', sub: 'digestivo' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 14,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 96,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // VERMOUTH - SWEET (ROSSO)
  // ========================================================================
  {
    id: 'ING_VERMOUTH_SWEET',
    slug: 'sweet-vermouth',
    name: {
      en: 'Sweet Vermouth (Rosso)',
      it: 'Vermouth Rosso',
      vi: 'Vermouth Ngọt',
      ko: '스위트 베르무트',
      ja: 'スイートベルモット',
    },
    description: {
      en: 'Sweet red aromatized wine, essential for Negroni and Manhattan',
      it: 'Vino aromatizzato rosso dolce, essenziale per Negroni e Manhattan',
    },
    category: { main: 'vermouth', sub: 'sweet' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 5,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 55,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CARPANO_ANTICA',
    slug: 'carpano-antica-formula',
    name: {
      en: 'Carpano Antica Formula',
      it: 'Carpano Antica Formula',
      vi: 'Carpano Antica Formula',
      ko: '카르파노 안티카 포뮬라',
      ja: 'カルパノ・アンティカ・フォーミュラ',
    },
    description: {
      en: 'Premium Italian sweet vermouth with vanilla and bitter notes',
      it: 'Vermouth dolce italiano premium con note di vaniglia e amaro',
    },
    category: { main: 'vermouth', sub: 'sweet' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 8,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 60,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_PUNT_E_MES',
    slug: 'punt-e-mes',
    name: {
      en: 'Punt e Mes',
      it: 'Punt e Mes',
      vi: 'Punt e Mes',
      ko: '푼트 에 메스',
      ja: 'プント・エ・メス',
    },
    description: {
      en: 'Bittersweet Italian vermouth, "point and a half"',
      it: 'Vermouth italiano agrodolce, "punto e mezzo"',
    },
    category: { main: 'vermouth', sub: 'sweet' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 7,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 58,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // VERMOUTH - DRY
  // ========================================================================
  {
    id: 'ING_VERMOUTH_DRY',
    slug: 'dry-vermouth',
    name: {
      en: 'Dry Vermouth',
      it: 'Vermouth Dry',
      vi: 'Vermouth Khô',
      ko: '드라이 베르무트',
      ja: 'ドライベルモット',
    },
    description: {
      en: 'Dry white aromatized wine, essential for Martini',
      it: 'Vino aromatizzato bianco secco, essenziale per Martini',
    },
    category: { main: 'vermouth', sub: 'dry' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 45,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_NOILLY_PRAT',
    slug: 'noilly-prat',
    name: {
      en: 'Noilly Prat',
      it: 'Noilly Prat',
      vi: 'Noilly Prat',
      ko: '노이이 프라',
      ja: 'ノイリー・プラット',
    },
    description: {
      en: 'Premium French dry vermouth',
      it: 'Vermouth secco francese premium',
    },
    category: { main: 'vermouth', sub: 'dry' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 2,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 48,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_DOLIN_DRY',
    slug: 'dolin-dry',
    name: {
      en: 'Dolin Dry Vermouth',
      it: 'Dolin Vermouth Dry',
      vi: 'Dolin Vermouth Khô',
      ko: '돌린 드라이 베르무트',
      ja: 'ドラン・ドライ・ベルモット',
    },
    description: {
      en: 'French Alpine dry vermouth, light and floral',
      it: 'Vermouth secco alpino francese, leggero e floreale',
    },
    category: { main: 'vermouth', sub: 'dry' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 2,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 46,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // VERMOUTH - BIANCO
  // ========================================================================
  {
    id: 'ING_VERMOUTH_BIANCO',
    slug: 'bianco-vermouth',
    name: {
      en: 'Bianco Vermouth',
      it: 'Vermouth Bianco',
      vi: 'Vermouth Trắng',
      ko: '비앙코 베르무트',
      ja: 'ビアンコベルモット',
    },
    description: {
      en: 'White sweet vermouth, vanilla and citrus notes',
      it: 'Vermouth bianco dolce, note di vaniglia e agrumi',
    },
    category: { main: 'vermouth', sub: 'bianco' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 5,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 52,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // OTHER APERITIF WINES
  // ========================================================================
  {
    id: 'ING_LILLET_BLANC',
    slug: 'lillet-blanc',
    name: {
      en: 'Lillet Blanc',
      it: 'Lillet Blanc',
      vi: 'Lillet Blanc',
      ko: '릴레 블랑',
      ja: 'リレ・ブラン',
    },
    description: {
      en: 'French aperitif wine with citrus and quinine',
      it: 'Vino aperitivo francese con agrumi e china',
    },
    category: { main: 'aperitif-wine', sub: 'blanc' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 6,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 52,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_LILLET_ROSE',
    slug: 'lillet-rose',
    name: {
      en: 'Lillet Rosé',
      it: 'Lillet Rosé',
      vi: 'Lillet Rosé',
      ko: '릴레 로제',
      ja: 'リレ・ロゼ',
    },
    description: {
      en: 'French rosé aperitif wine with berry notes',
      it: 'Vino aperitivo rosé francese con note di frutti di bosco',
    },
    category: { main: 'aperitif-wine', sub: 'rose' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 6,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 52,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_COCCHI_AMERICANO',
    slug: 'cocchi-americano',
    name: {
      en: 'Cocchi Americano',
      it: 'Cocchi Americano',
      vi: 'Cocchi Americano',
      ko: '코키 아메리카노',
      ja: 'コッキ・アメリカーノ',
    },
    description: {
      en: 'Italian aperitif wine, closest substitute for Kina Lillet',
      it: 'Vino aperitivo italiano, sostituto più vicino al Kina Lillet',
    },
    category: { main: 'aperitif-wine', sub: 'quinquina' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 8,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 55,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_DUBONNET',
    slug: 'dubonnet',
    name: {
      en: 'Dubonnet Rouge',
      it: 'Dubonnet Rouge',
      vi: 'Dubonnet Rouge',
      ko: '뒤보네 루주',
      ja: 'デュボネ・ルージュ',
    },
    description: {
      en: 'French quinquina aperitif with herbs and spices',
      it: 'Aperitivo quinquina francese con erbe e spezie',
    },
    category: { main: 'aperitif-wine', sub: 'quinquina' },
    allergens: { sulphites: true },
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 9,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 58,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_SUZE',
    slug: 'suze',
    name: {
      en: 'Suze',
      it: 'Suze',
      vi: 'Suze',
      ko: '쉬즈',
      ja: 'スーズ',
    },
    description: {
      en: 'French gentian liqueur, intensely bitter',
      it: 'Liquore francese alla genziana, intensamente amaro',
    },
    category: { main: 'amari', sub: 'gentian' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseAmariFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 10,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 75,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
];

// ============================================================================
// EXPORTS
// ============================================================================

export const AMARI_VERMOUTH_COUNT = amariVermouthIngredients.length;
