/**
 * GUDBRO Cocktail Ingredients - Garnishes
 *
 * Decorative and aromatic ingredients with complete 5 Dimensioni data.
 *
 * Categories:
 * - Citrus (twists, wedges, wheels)
 * - Olives & Pickles
 * - Cherries
 * - Fresh Herbs (mint, basil, rosemary)
 * - Other Garnishes (nutmeg, cinnamon, salt rim)
 *
 * @version 1.0
 * @lastUpdated 2025-12-13
 */

import type { IngredientMaster } from '../../types';

const baseGarnishFlags = {
  vegan: true,
  vegetarian: true,
  pescatarian: true,
  gluten_free: true,
  dairy_free: true,
  nut_free: true,
  low_carb: true,
  halal: true,
  kosher: true,
};

export const garnishIngredients: IngredientMaster[] = [
  // ========================================================================
  // CITRUS GARNISHES
  // ========================================================================
  {
    id: 'ING_LIME_WEDGE',
    slug: 'lime-wedge',
    name: {
      en: 'Lime Wedge',
      it: 'Spicchio di Lime',
      vi: 'Miếng Chanh',
      ko: '라임 웨지',
      ja: 'ライムウェッジ',
    },
    description: {
      en: 'Fresh lime wedge for squeezing and garnishing',
      it: 'Spicchio di lime fresco per spremere e decorare',
    },
    category: { main: 'garnish', sub: 'citrus' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 3,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_LIME_WHEEL',
    slug: 'lime-wheel',
    name: {
      en: 'Lime Wheel',
      it: 'Rondella di Lime',
      vi: 'Lát Chanh',
      ko: '라임 휠',
      ja: 'ライムホイール',
    },
    description: {
      en: 'Circular lime slice for glass rim garnish',
      it: 'Fetta circolare di lime per decorazione sul bordo',
    },
    category: { main: 'garnish', sub: 'citrus' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 3,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_LEMON_TWIST',
    slug: 'lemon-twist',
    name: {
      en: 'Lemon Twist',
      it: 'Scorza di Limone',
      vi: 'Vỏ Chanh Vàng',
      ko: '레몬 트위스트',
      ja: 'レモンツイスト',
    },
    description: {
      en: 'Lemon peel twist expressing oils',
      it: 'Scorza di limone attorcigliata che rilascia oli',
    },
    category: { main: 'garnish', sub: 'citrus' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 1,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_LEMON_WEDGE',
    slug: 'lemon-wedge',
    name: {
      en: 'Lemon Wedge',
      it: 'Spicchio di Limone',
      vi: 'Miếng Chanh Vàng',
      ko: '레몬 웨지',
      ja: 'レモンウェッジ',
    },
    category: { main: 'garnish', sub: 'citrus' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 3,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_ORANGE_TWIST',
    slug: 'orange-twist',
    name: {
      en: 'Orange Twist',
      it: 'Scorza d\'Arancia',
      vi: 'Vỏ Cam',
      ko: '오렌지 트위스트',
      ja: 'オレンジツイスト',
    },
    description: {
      en: 'Orange peel twist for Old Fashioned and Negroni',
      it: 'Scorza d\'arancia attorcigliata per Old Fashioned e Negroni',
    },
    category: { main: 'garnish', sub: 'citrus' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 2,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_ORANGE_SLICE',
    slug: 'orange-slice',
    name: {
      en: 'Orange Slice/Wheel',
      it: 'Fetta d\'Arancia',
      vi: 'Lát Cam',
      ko: '오렌지 슬라이스',
      ja: 'オレンジスライス',
    },
    category: { main: 'garnish', sub: 'citrus' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 2,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 8,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_GRAPEFRUIT_TWIST',
    slug: 'grapefruit-twist',
    name: {
      en: 'Grapefruit Twist',
      it: 'Scorza di Pompelmo',
      vi: 'Vỏ Bưởi',
      ko: '자몽 트위스트',
      ja: 'グレープフルーツツイスト',
    },
    category: { main: 'garnish', sub: 'citrus' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 2,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // OLIVES & PICKLES
  // ========================================================================
  {
    id: 'ING_OLIVE_GREEN',
    slug: 'green-olive',
    name: {
      en: 'Green Olive',
      it: 'Oliva Verde',
      vi: 'Ô Liu Xanh',
      ko: '그린 올리브',
      ja: 'グリーンオリーブ',
    },
    description: {
      en: 'Pitted green olive for Martinis',
      it: 'Oliva verde snocciolata per Martini',
    },
    category: { main: 'garnish', sub: 'olive' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 1,
      fiber_g: 0,
      calories_kcal: 10,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_OLIVE_STUFFED',
    slug: 'stuffed-olive',
    name: {
      en: 'Blue Cheese Stuffed Olive',
      it: 'Oliva Ripiena di Gorgonzola',
      vi: 'Ô Liu Nhồi Phô Mai',
      ko: '블루 치즈 스터프드 올리브',
      ja: 'ブルーチーズオリーブ',
    },
    description: {
      en: 'Olive stuffed with blue cheese for dirty Martinis',
      it: 'Oliva ripiena di formaggio blu per Martini dirty',
    },
    category: { main: 'garnish', sub: 'olive' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      ...baseGarnishFlags,
      vegan: false,
      dairy_free: false,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 1,
      carbs_g: 0,
      fat_g: 3,
      fiber_g: 0,
      calories_kcal: 25,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_COCKTAIL_ONION',
    slug: 'cocktail-onion',
    name: {
      en: 'Cocktail Onion',
      it: 'Cipollina da Cocktail',
      vi: 'Hành Cocktail',
      ko: '칵테일 양파',
      ja: 'カクテルオニオン',
    },
    description: {
      en: 'Pickled pearl onion for Gibson',
      it: 'Cipollina sottaceto per Gibson',
    },
    category: { main: 'garnish', sub: 'pickle' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 3,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CORNICHON',
    slug: 'cornichon',
    name: {
      en: 'Cornichon',
      it: 'Cetriolino',
      vi: 'Dưa Chuột Nhỏ',
      ko: '코르니숑',
      ja: 'コルニッション',
    },
    description: {
      en: 'Small pickled cucumber',
      it: 'Piccolo cetriolo sottaceto',
    },
    category: { main: 'garnish', sub: 'pickle' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 2,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CELERY_STALK',
    slug: 'celery-stalk',
    name: {
      en: 'Celery Stalk',
      it: 'Gambo di Sedano',
      vi: 'Cọng Cần Tây',
      ko: '셀러리 줄기',
      ja: 'セロリの茎',
    },
    description: {
      en: 'Fresh celery stick for Bloody Mary',
      it: 'Gambo di sedano fresco per Bloody Mary',
    },
    category: { main: 'garnish', sub: 'vegetable' },
    allergens: { celery: true },
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 1,
      calories_kcal: 5,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // CHERRIES
  // ========================================================================
  {
    id: 'ING_MARASCHINO_CHERRY',
    slug: 'maraschino-cherry',
    name: {
      en: 'Maraschino Cherry',
      it: 'Ciliegia Maraschino',
      vi: 'Cherry Maraschino',
      ko: '마라스키노 체리',
      ja: 'マラスキーノチェリー',
    },
    description: {
      en: 'Sweet preserved cherry for Manhattans and Old Fashioned',
      it: 'Ciliegia dolce conservata per Manhattan e Old Fashioned',
    },
    category: { main: 'garnish', sub: 'cherry' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 3,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 10,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_LUXARDO_CHERRY',
    slug: 'luxardo-cherry',
    name: {
      en: 'Luxardo Cherry',
      it: 'Ciliegia Luxardo',
      vi: 'Cherry Luxardo',
      ko: '룩사르도 체리',
      ja: 'ルクサルドチェリー',
    },
    description: {
      en: 'Premium Italian candied cherry',
      it: 'Ciliegia candita italiana premium',
    },
    category: { main: 'garnish', sub: 'cherry' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 5,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 18,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_BRANDIED_CHERRY',
    slug: 'brandied-cherry',
    name: {
      en: 'Brandied Cherry',
      it: 'Ciliegia sotto Brandy',
      vi: 'Cherry Ngâm Brandy',
      ko: '브랜디 체리',
      ja: 'ブランデーチェリー',
    },
    description: {
      en: 'Cherry preserved in brandy',
      it: 'Ciliegia conservata nel brandy',
    },
    category: { main: 'garnish', sub: 'cherry' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: {
      ...baseGarnishFlags,
      halal: false,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 4,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 15,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // FRESH HERBS
  // ========================================================================
  {
    id: 'ING_MINT_SPRIG',
    slug: 'fresh-mint',
    name: {
      en: 'Fresh Mint Sprig',
      it: 'Rametto di Menta Fresca',
      vi: 'Cành Bạc Hà',
      ko: '신선한 민트',
      ja: 'フレッシュミント',
    },
    description: {
      en: 'Aromatic mint for Mojitos and Juleps',
      it: 'Menta aromatica per Mojito e Julep',
    },
    category: { main: 'garnish', sub: 'herb' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 1,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_BASIL_LEAF',
    slug: 'fresh-basil',
    name: {
      en: 'Fresh Basil Leaf',
      it: 'Foglia di Basilico Fresco',
      vi: 'Lá Húng Quế',
      ko: '신선한 바질',
      ja: 'フレッシュバジル',
    },
    description: {
      en: 'Aromatic basil for Italian-inspired cocktails',
      it: 'Basilico aromatico per cocktail ispirati all\'Italia',
    },
    category: { main: 'garnish', sub: 'herb' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 1,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_ROSEMARY_SPRIG',
    slug: 'fresh-rosemary',
    name: {
      en: 'Fresh Rosemary Sprig',
      it: 'Rametto di Rosmarino',
      vi: 'Cành Hương Thảo',
      ko: '신선한 로즈마리',
      ja: 'フレッシュローズマリー',
    },
    description: {
      en: 'Aromatic rosemary for garnish and smoking',
      it: 'Rosmarino aromatico per guarnizione e affumicatura',
    },
    category: { main: 'garnish', sub: 'herb' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 1,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_THYME_SPRIG',
    slug: 'fresh-thyme',
    name: {
      en: 'Fresh Thyme Sprig',
      it: 'Rametto di Timo',
      vi: 'Cành Cỏ Xạ Hương',
      ko: '신선한 타임',
      ja: 'フレッシュタイム',
    },
    category: { main: 'garnish', sub: 'herb' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 1,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_LAVENDER_SPRIG',
    slug: 'fresh-lavender',
    name: {
      en: 'Fresh Lavender Sprig',
      it: 'Rametto di Lavanda',
      vi: 'Cành Oải Hương',
      ko: '신선한 라벤더',
      ja: 'フレッシュラベンダー',
    },
    category: { main: 'garnish', sub: 'herb' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 1,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // FRUIT GARNISHES
  // ========================================================================
  {
    id: 'ING_PINEAPPLE_WEDGE',
    slug: 'pineapple-wedge',
    name: {
      en: 'Pineapple Wedge',
      it: 'Spicchio di Ananas',
      vi: 'Miếng Dứa',
      ko: '파인애플 웨지',
      ja: 'パイナップルウェッジ',
    },
    description: {
      en: 'Fresh pineapple for tropical cocktails',
      it: 'Ananas fresco per cocktail tropicali',
    },
    category: { main: 'garnish', sub: 'fruit' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 3,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 12,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_PINEAPPLE_LEAF',
    slug: 'pineapple-leaf',
    name: {
      en: 'Pineapple Leaf',
      it: 'Foglia di Ananas',
      vi: 'Lá Dứa',
      ko: '파인애플 잎',
      ja: 'パイナップルの葉',
    },
    description: {
      en: 'Decorative pineapple frond',
      it: 'Foglia decorativa di ananas',
    },
    category: { main: 'garnish', sub: 'fruit' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 0,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_STRAWBERRY',
    slug: 'fresh-strawberry',
    name: {
      en: 'Fresh Strawberry',
      it: 'Fragola Fresca',
      vi: 'Dâu Tây Tươi',
      ko: '신선한 딸기',
      ja: 'フレッシュストロベリー',
    },
    category: { main: 'garnish', sub: 'fruit' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 2,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 6,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RASPBERRY',
    slug: 'fresh-raspberry',
    name: {
      en: 'Fresh Raspberry',
      it: 'Lampone Fresco',
      vi: 'Mâm Xôi Tươi',
      ko: '신선한 라즈베리',
      ja: 'フレッシュラズベリー',
    },
    category: { main: 'garnish', sub: 'fruit' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 1,
      calories_kcal: 4,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CUCUMBER_SLICE',
    slug: 'cucumber-slice',
    name: {
      en: 'Cucumber Slice',
      it: 'Fetta di Cetriolo',
      vi: 'Lát Dưa Chuột',
      ko: '오이 슬라이스',
      ja: 'キュウリスライス',
    },
    description: {
      en: 'Fresh cucumber for G&T and refreshing cocktails',
      it: 'Cetriolo fresco per Gin Tonic e cocktail rinfrescanti',
    },
    category: { main: 'garnish', sub: 'vegetable' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 2,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // SPICES & POWDERS
  // ========================================================================
  {
    id: 'ING_NUTMEG_GRATED',
    slug: 'freshly-grated-nutmeg',
    name: {
      en: 'Freshly Grated Nutmeg',
      it: 'Noce Moscata Grattugiata',
      vi: 'Nhục Đậu Khấu Bào',
      ko: '갓 간 넛맥',
      ja: 'おろしたてナツメグ',
    },
    description: {
      en: 'Aromatic spice for flips and cream cocktails',
      it: 'Spezia aromatica per flip e cocktail cremosi',
    },
    category: { main: 'garnish', sub: 'spice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 2,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CINNAMON_STICK',
    slug: 'cinnamon-stick',
    name: {
      en: 'Cinnamon Stick',
      it: 'Stecca di Cannella',
      vi: 'Thanh Quế',
      ko: '시나몬 스틱',
      ja: 'シナモンスティック',
    },
    description: {
      en: 'Aromatic garnish for mulled drinks and toddies',
      it: 'Guarnizione aromatica per bevande calde e toddy',
    },
    category: { main: 'garnish', sub: 'spice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 1,
      calories_kcal: 5,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_STAR_ANISE',
    slug: 'star-anise',
    name: {
      en: 'Star Anise',
      it: 'Anice Stellato',
      vi: 'Hồi',
      ko: '팔각',
      ja: 'スターアニス',
    },
    description: {
      en: 'Decorative star-shaped spice',
      it: 'Spezia decorativa a forma di stella',
    },
    category: { main: 'garnish', sub: 'spice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 2,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_COCOA_POWDER',
    slug: 'cocoa-powder',
    name: {
      en: 'Cocoa Powder',
      it: 'Cacao in Polvere',
      vi: 'Bột Ca Cao',
      ko: '코코아 파우더',
      ja: 'ココアパウダー',
    },
    description: {
      en: 'Dusting for coffee and cream cocktails',
      it: 'Spolverata per cocktail al caffè e panna',
    },
    category: { main: 'garnish', sub: 'powder' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 5,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // RIM GARNISHES
  // ========================================================================
  {
    id: 'ING_SALT_RIM',
    slug: 'salt-rim',
    name: {
      en: 'Rim Salt',
      it: 'Sale per Bordo',
      vi: 'Muối Viền Ly',
      ko: '림 솔트',
      ja: 'リムソルト',
    },
    description: {
      en: 'Coarse salt for Margarita rim',
      it: 'Sale grosso per bordo Margarita',
    },
    category: { main: 'garnish', sub: 'rim' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 0,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_SUGAR_RIM',
    slug: 'sugar-rim',
    name: {
      en: 'Rim Sugar',
      it: 'Zucchero per Bordo',
      vi: 'Đường Viền Ly',
      ko: '림 슈거',
      ja: 'リムシュガー',
    },
    description: {
      en: 'Sugar for sweet cocktail rim',
      it: 'Zucchero per bordo di cocktail dolci',
    },
    category: { main: 'garnish', sub: 'rim' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 2,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 8,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_TAJIN',
    slug: 'tajin-rim',
    name: {
      en: 'Tajín (Chili-Lime)',
      it: 'Tajín (Peperoncino-Lime)',
      vi: 'Tajín',
      ko: '타힌',
      ja: 'タヒン',
    },
    description: {
      en: 'Mexican chili-lime seasoning for micheladas',
      it: 'Condimento messicano al peperoncino e lime per michelada',
    },
    category: { main: 'garnish', sub: 'rim' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 2 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 0,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // EDIBLE FLOWERS
  // ========================================================================
  {
    id: 'ING_EDIBLE_FLOWER',
    slug: 'edible-flower',
    name: {
      en: 'Edible Flower',
      it: 'Fiore Commestibile',
      vi: 'Hoa Ăn Được',
      ko: '식용 꽃',
      ja: 'エディブルフラワー',
    },
    description: {
      en: 'Decorative edible flowers (viola, pansy, nasturtium)',
      it: 'Fiori commestibili decorativi (viola, pensiero, nasturzio)',
    },
    category: { main: 'garnish', sub: 'flower' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 0,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_ORCHID',
    slug: 'orchid-garnish',
    name: {
      en: 'Orchid (Edible)',
      it: 'Orchidea Commestibile',
      vi: 'Hoa Lan',
      ko: '식용 난초',
      ja: '食用蘭',
    },
    description: {
      en: 'Elegant orchid flower for tropical presentations',
      it: 'Elegante fiore di orchidea per presentazioni tropicali',
    },
    category: { main: 'garnish', sub: 'flower' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseGarnishFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 0,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
];

// ============================================================================
// EXPORTS
// ============================================================================

export const GARNISH_COUNT = garnishIngredients.length;
