/**
 * GUDBRO Cocktail Ingredients - Mixers
 *
 * Non-alcoholic ingredients for cocktails with complete 5 Dimensioni data.
 *
 * Categories:
 * - Fresh Juices (lime, lemon, orange, grapefruit, pineapple, cranberry)
 * - Sodas & Carbonated (tonic, soda water, ginger beer, cola)
 * - Syrups (simple, rich, honey, agave, grenadine, orgeat)
 * - Other Mixers (cream, eggs, coconut cream)
 *
 * @version 1.0
 * @lastUpdated 2025-12-13
 */

import type { IngredientMaster } from '../../types';

const baseJuiceFlags = {
  vegan: true,
  vegetarian: true,
  pescatarian: true,
  gluten_free: true,
  dairy_free: true,
  nut_free: true,
  low_carb: false,
  halal: true,
  kosher: true,
};

export const mixersIngredients: IngredientMaster[] = [
  // ========================================================================
  // FRESH CITRUS JUICES
  // ========================================================================
  {
    id: 'ING_LIME_JUICE',
    slug: 'fresh-lime-juice',
    name: {
      en: 'Fresh Lime Juice',
      it: 'Succo di Lime Fresco',
      vi: 'Nước Chanh Tươi',
      ko: '신선한 라임 주스',
      ja: 'フレッシュライムジュース',
    },
    description: {
      en: 'Freshly squeezed lime juice, essential for sours and tropical drinks',
      it: 'Succo di lime appena spremuto, essenziale per sour e drink tropicali',
    },
    category: { main: 'mixers', sub: 'citrus-juice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: { ...baseJuiceFlags, low_carb: true },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 3,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 8, // per 30ml
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_LEMON_JUICE',
    slug: 'fresh-lemon-juice',
    name: {
      en: 'Fresh Lemon Juice',
      it: 'Succo di Limone Fresco',
      vi: 'Nước Chanh Vàng Tươi',
      ko: '신선한 레몬 주스',
      ja: 'フレッシュレモンジュース',
    },
    description: {
      en: 'Freshly squeezed lemon juice for classic sours',
      it: 'Succo di limone appena spremuto per sour classici',
    },
    category: { main: 'mixers', sub: 'citrus-juice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: { ...baseJuiceFlags, low_carb: true },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 2,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 7,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_ORANGE_JUICE',
    slug: 'fresh-orange-juice',
    name: {
      en: 'Fresh Orange Juice',
      it: 'Succo d\'Arancia Fresco',
      vi: 'Nước Cam Tươi',
      ko: '신선한 오렌지 주스',
      ja: 'フレッシュオレンジジュース',
    },
    description: {
      en: 'Freshly squeezed orange juice for brunch cocktails',
      it: 'Succo d\'arancia appena spremuto per cocktail da brunch',
    },
    category: { main: 'mixers', sub: 'citrus-juice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 8,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 33,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_GRAPEFRUIT_JUICE',
    slug: 'fresh-grapefruit-juice',
    name: {
      en: 'Fresh Grapefruit Juice',
      it: 'Succo di Pompelmo Fresco',
      vi: 'Nước Bưởi Tươi',
      ko: '신선한 자몽 주스',
      ja: 'フレッシュグレープフルーツジュース',
    },
    description: {
      en: 'Freshly squeezed grapefruit juice for Palomas',
      it: 'Succo di pompelmo appena spremuto per Paloma',
    },
    category: { main: 'mixers', sub: 'citrus-juice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 7,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 30,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // OTHER JUICES
  // ========================================================================
  {
    id: 'ING_PINEAPPLE_JUICE',
    slug: 'pineapple-juice',
    name: {
      en: 'Pineapple Juice',
      it: 'Succo di Ananas',
      vi: 'Nước Dứa',
      ko: '파인애플 주스',
      ja: 'パイナップルジュース',
    },
    description: {
      en: 'Sweet tropical juice for Tiki and tropical cocktails',
      it: 'Succo tropicale dolce per cocktail Tiki e tropicali',
    },
    category: { main: 'mixers', sub: 'fruit-juice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 10,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 40,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CRANBERRY_JUICE',
    slug: 'cranberry-juice',
    name: {
      en: 'Cranberry Juice',
      it: 'Succo di Mirtillo Rosso',
      vi: 'Nước Nam Việt Quất',
      ko: '크랜베리 주스',
      ja: 'クランベリージュース',
    },
    description: {
      en: 'Tart cranberry juice for Cosmopolitans and Sea Breeze',
      it: 'Succo di mirtillo rosso aspro per Cosmopolitan e Sea Breeze',
    },
    category: { main: 'mixers', sub: 'fruit-juice' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 9,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 35,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_TOMATO_JUICE',
    slug: 'tomato-juice',
    name: {
      en: 'Tomato Juice',
      it: 'Succo di Pomodoro',
      vi: 'Nước Cà Chua',
      ko: '토마토 주스',
      ja: 'トマトジュース',
    },
    description: {
      en: 'Essential base for Bloody Mary',
      it: 'Base essenziale per Bloody Mary',
    },
    category: { main: 'mixers', sub: 'vegetable-juice' },
    allergens: {},
    intolerances: { histamine: true },
    dietary_restrictions: { ...baseJuiceFlags, low_carb: true },
    spice: { level: 0 },
    nutrition: {
      protein_g: 1,
      carbs_g: 3,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 15,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_PASSION_FRUIT_PUREE',
    slug: 'passion-fruit-puree',
    name: {
      en: 'Passion Fruit Purée',
      it: 'Purea di Frutto della Passione',
      vi: 'Chanh Dây Xay',
      ko: '패션프루트 퓨레',
      ja: 'パッションフルーツピューレ',
    },
    description: {
      en: 'Tropical puree for Porn Star Martinis',
      it: 'Purea tropicale per Porn Star Martini',
    },
    category: { main: 'mixers', sub: 'fruit-puree' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 12,
      fat_g: 0,
      fiber_g: 2,
      calories_kcal: 45,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // SODAS & CARBONATED
  // ========================================================================
  {
    id: 'ING_SODA_WATER',
    slug: 'soda-water',
    name: {
      en: 'Soda Water (Club Soda)',
      it: 'Acqua Seltz',
      vi: 'Nước Soda',
      ko: '소다수',
      ja: 'ソーダ水',
    },
    description: {
      en: 'Carbonated water for highballs and fizzes',
      it: 'Acqua gassata per highball e fizz',
    },
    category: { main: 'mixers', sub: 'carbonated' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: { ...baseJuiceFlags, low_carb: true },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 0,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_TONIC_WATER',
    slug: 'tonic-water',
    name: {
      en: 'Tonic Water',
      it: 'Acqua Tonica',
      vi: 'Nước Tonic',
      ko: '토닉 워터',
      ja: 'トニックウォーター',
    },
    description: {
      en: 'Quinine-infused carbonated water for G&Ts',
      it: 'Acqua gassata con chinino per Gin Tonic',
    },
    category: { main: 'mixers', sub: 'carbonated' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 7,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 28,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_GINGER_BEER',
    slug: 'ginger-beer',
    name: {
      en: 'Ginger Beer',
      it: 'Ginger Beer',
      vi: 'Bia Gừng',
      ko: '진저 비어',
      ja: 'ジンジャービア',
    },
    description: {
      en: 'Spicy carbonated ginger drink for Moscow Mules',
      it: 'Bevanda gassata speziata allo zenzero per Moscow Mule',
    },
    category: { main: 'mixers', sub: 'carbonated' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 2 },
    nutrition: {
      protein_g: 0,
      carbs_g: 10,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 40,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_GINGER_ALE',
    slug: 'ginger-ale',
    name: {
      en: 'Ginger Ale',
      it: 'Ginger Ale',
      vi: 'Ginger Ale',
      ko: '진저 에일',
      ja: 'ジンジャーエール',
    },
    description: {
      en: 'Milder ginger-flavored soda',
      it: 'Soda allo zenzero più delicata',
    },
    category: { main: 'mixers', sub: 'carbonated' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 9,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 35,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_COLA',
    slug: 'cola',
    name: {
      en: 'Cola',
      it: 'Cola',
      vi: 'Cola',
      ko: '콜라',
      ja: 'コーラ',
    },
    description: {
      en: 'Classic cola for Cuba Libre and Long Island',
      it: 'Cola classica per Cuba Libre e Long Island',
    },
    category: { main: 'mixers', sub: 'carbonated' },
    allergens: {},
    intolerances: { caffeine: true },
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 11,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 42,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_LEMON_LIME_SODA',
    slug: 'lemon-lime-soda',
    name: {
      en: 'Lemon-Lime Soda (Sprite/7UP)',
      it: 'Soda Limone-Lime',
      vi: 'Soda Chanh',
      ko: '레몬라임 소다',
      ja: 'レモンライムソーダ',
    },
    description: {
      en: 'Clear citrus soda for various highballs',
      it: 'Soda agrumata trasparente per vari highball',
    },
    category: { main: 'mixers', sub: 'carbonated' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 10,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 39,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // SYRUPS - SIMPLE & SUGAR-BASED
  // ========================================================================
  {
    id: 'ING_SIMPLE_SYRUP',
    slug: 'simple-syrup',
    name: {
      en: 'Simple Syrup (1:1)',
      it: 'Sciroppo Semplice',
      vi: 'Siro Đường',
      ko: '심플 시럽',
      ja: 'シンプルシロップ',
    },
    description: {
      en: 'Equal parts sugar and water, essential sweetener',
      it: 'Parti uguali di zucchero e acqua, dolcificante essenziale',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 17,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 65,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RICH_SIMPLE_SYRUP',
    slug: 'rich-simple-syrup',
    name: {
      en: 'Rich Simple Syrup (2:1)',
      it: 'Sciroppo Ricco',
      vi: 'Siro Đường Đậm',
      ko: '리치 심플 시럽',
      ja: 'リッチシンプルシロップ',
    },
    description: {
      en: 'Two parts sugar to one part water, more viscous',
      it: 'Due parti di zucchero per una di acqua, più viscoso',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 22,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 85,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_DEMERARA_SYRUP',
    slug: 'demerara-syrup',
    name: {
      en: 'Demerara Syrup',
      it: 'Sciroppo di Demerara',
      vi: 'Siro Demerara',
      ko: '데메라라 시럽',
      ja: 'デメララシロップ',
    },
    description: {
      en: 'Rich syrup made with demerara sugar, deeper flavor',
      it: 'Sciroppo ricco fatto con zucchero demerara, sapore più profondo',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 20,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 78,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_HONEY_SYRUP',
    slug: 'honey-syrup',
    name: {
      en: 'Honey Syrup',
      it: 'Sciroppo di Miele',
      vi: 'Siro Mật Ong',
      ko: '허니 시럽',
      ja: 'ハニーシロップ',
    },
    description: {
      en: 'Honey diluted with water for easier mixing',
      it: 'Miele diluito con acqua per una miscelazione più facile',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      ...baseJuiceFlags,
      vegan: false, // Contains honey
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 18,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 70,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_AGAVE_SYRUP',
    slug: 'agave-syrup',
    name: {
      en: 'Agave Syrup (Nectar)',
      it: 'Sciroppo di Agave',
      vi: 'Siro Agave',
      ko: '아가베 시럽',
      ja: 'アガベシロップ',
    },
    description: {
      en: 'Natural sweetener from agave, pairs with tequila',
      it: 'Dolcificante naturale da agave, si abbina alla tequila',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 16,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 60,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // SYRUPS - FLAVORED
  // ========================================================================
  {
    id: 'ING_GRENADINE',
    slug: 'grenadine',
    name: {
      en: 'Grenadine',
      it: 'Granatina',
      vi: 'Grenadine',
      ko: '그레나딘',
      ja: 'グレナデン',
    },
    description: {
      en: 'Pomegranate syrup for color and sweetness',
      it: 'Sciroppo di melograno per colore e dolcezza',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 18,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 70,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_ORGEAT',
    slug: 'orgeat-syrup',
    name: {
      en: 'Orgeat Syrup',
      it: 'Sciroppo di Orzata',
      vi: 'Siro Orgeat',
      ko: '오르게트 시럽',
      ja: 'オルジェートシロップ',
    },
    description: {
      en: 'Almond syrup essential for Mai Tai',
      it: 'Sciroppo di mandorla essenziale per Mai Tai',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: { nuts: true }, // Contains almonds
    intolerances: {},
    dietary_restrictions: {
      ...baseJuiceFlags,
      nut_free: false,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 16,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 62,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_GINGER_SYRUP',
    slug: 'ginger-syrup',
    name: {
      en: 'Ginger Syrup',
      it: 'Sciroppo di Zenzero',
      vi: 'Siro Gừng',
      ko: '생강 시럽',
      ja: 'ジンジャーシロップ',
    },
    description: {
      en: 'Spicy-sweet ginger syrup',
      it: 'Sciroppo dolce-speziato allo zenzero',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 2 },
    nutrition: {
      protein_g: 0,
      carbs_g: 15,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 58,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CINNAMON_SYRUP',
    slug: 'cinnamon-syrup',
    name: {
      en: 'Cinnamon Syrup',
      it: 'Sciroppo alla Cannella',
      vi: 'Siro Quế',
      ko: '시나몬 시럽',
      ja: 'シナモンシロップ',
    },
    description: {
      en: 'Warm spiced syrup for autumn cocktails',
      it: 'Sciroppo speziato caldo per cocktail autunnali',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 16,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 62,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_VANILLA_SYRUP',
    slug: 'vanilla-syrup',
    name: {
      en: 'Vanilla Syrup',
      it: 'Sciroppo alla Vaniglia',
      vi: 'Siro Vani',
      ko: '바닐라 시럽',
      ja: 'バニラシロップ',
    },
    description: {
      en: 'Sweet vanilla-flavored syrup',
      it: 'Sciroppo dolce alla vaniglia',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 17,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 65,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_ELDERFLOWER_SYRUP',
    slug: 'elderflower-syrup',
    name: {
      en: 'Elderflower Syrup',
      it: 'Sciroppo di Sambuco',
      vi: 'Siro Hoa Cơm Cháy',
      ko: '엘더플라워 시럽',
      ja: 'エルダーフラワーシロップ',
    },
    description: {
      en: 'Floral elderflower syrup for Hugo cocktails',
      it: 'Sciroppo floreale di fiori di sambuco per cocktail Hugo',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 15,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 58,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // DAIRY & CREAM
  // ========================================================================
  {
    id: 'ING_HEAVY_CREAM',
    slug: 'heavy-cream',
    name: {
      en: 'Heavy Cream',
      it: 'Panna da Montare',
      vi: 'Kem Béo',
      ko: '헤비 크림',
      ja: 'ヘビークリーム',
    },
    description: {
      en: 'Rich cream for creamy cocktails and floats',
      it: 'Panna ricca per cocktail cremosi e float',
    },
    category: { main: 'mixers', sub: 'dairy' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      low_carb: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 1,
      carbs_g: 1,
      fat_g: 11,
      fiber_g: 0,
      calories_kcal: 103,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_HALF_AND_HALF',
    slug: 'half-and-half',
    name: {
      en: 'Half and Half',
      it: 'Panna Leggera',
      vi: 'Half and Half',
      ko: '하프 앤 하프',
      ja: 'ハーフアンドハーフ',
    },
    description: {
      en: 'Half milk, half cream for lighter texture',
      it: 'Metà latte, metà panna per una consistenza più leggera',
    },
    category: { main: 'mixers', sub: 'dairy' },
    allergens: { milk: true },
    intolerances: { lactose: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: false,
      nut_free: true,
      low_carb: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 1,
      carbs_g: 1,
      fat_g: 4,
      fiber_g: 0,
      calories_kcal: 40,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_COCONUT_CREAM',
    slug: 'coconut-cream',
    name: {
      en: 'Coconut Cream',
      it: 'Crema di Cocco',
      vi: 'Kem Dừa',
      ko: '코코넛 크림',
      ja: 'ココナッツクリーム',
    },
    description: {
      en: 'Rich coconut cream for Piña Coladas',
      it: 'Crema di cocco ricca per Piña Colada',
    },
    category: { main: 'mixers', sub: 'coconut' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 1,
      carbs_g: 3,
      fat_g: 12,
      fiber_g: 0,
      calories_kcal: 120,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_COCONUT_MILK',
    slug: 'coconut-milk',
    name: {
      en: 'Coconut Milk',
      it: 'Latte di Cocco',
      vi: 'Nước Cốt Dừa',
      ko: '코코넛 밀크',
      ja: 'ココナッツミルク',
    },
    description: {
      en: 'Lighter coconut milk for tropical drinks',
      it: 'Latte di cocco più leggero per drink tropicali',
    },
    category: { main: 'mixers', sub: 'coconut' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: baseJuiceFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 2,
      fat_g: 5,
      fiber_g: 0,
      calories_kcal: 50,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // EGGS
  // ========================================================================
  {
    id: 'ING_EGG_WHITE',
    slug: 'egg-white',
    name: {
      en: 'Egg White',
      it: 'Albume d\'Uovo',
      vi: 'Lòng Trắng Trứng',
      ko: '달걀 흰자',
      ja: '卵白',
    },
    description: {
      en: 'Creates silky foam for sours and fizzes',
      it: 'Crea una schiuma setosa per sour e fizz',
    },
    category: { main: 'mixers', sub: 'egg' },
    allergens: { eggs: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      low_carb: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 4,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 17,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_WHOLE_EGG',
    slug: 'whole-egg',
    name: {
      en: 'Whole Egg',
      it: 'Uovo Intero',
      vi: 'Trứng Nguyên Quả',
      ko: '전란',
      ja: '全卵',
    },
    description: {
      en: 'For flips and rich creamy cocktails',
      it: 'Per flip e cocktail cremosi ricchi',
    },
    category: { main: 'mixers', sub: 'egg' },
    allergens: { eggs: true },
    intolerances: {},
    dietary_restrictions: {
      vegan: false,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      low_carb: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 6,
      carbs_g: 0,
      fat_g: 5,
      fiber_g: 0,
      calories_kcal: 70,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_AQUAFABA',
    slug: 'aquafaba',
    name: {
      en: 'Aquafaba',
      it: 'Aquafaba',
      vi: 'Aquafaba',
      ko: '아쿠아파바',
      ja: 'アクアファバ',
    },
    description: {
      en: 'Vegan egg white substitute from chickpea water',
      it: 'Sostituto vegano dell\'albume dall\'acqua dei ceci',
    },
    category: { main: 'mixers', sub: 'vegan' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      ...baseJuiceFlags,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 3,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // OTHER MIXERS
  // ========================================================================
  {
    id: 'ING_WORCESTERSHIRE',
    slug: 'worcestershire-sauce',
    name: {
      en: 'Worcestershire Sauce',
      it: 'Salsa Worcestershire',
      vi: 'Nước Sốt Worcestershire',
      ko: '우스터 소스',
      ja: 'ウスターソース',
    },
    description: {
      en: 'Savory sauce for Bloody Marys',
      it: 'Salsa saporita per Bloody Mary',
    },
    category: { main: 'mixers', sub: 'sauce' },
    allergens: { fish: true }, // Contains anchovies
    intolerances: { histamine: true },
    dietary_restrictions: {
      vegan: false,
      vegetarian: false,
      pescatarian: true,
      gluten_free: false, // Contains barley
      dairy_free: true,
      nut_free: true,
      low_carb: true,
      halal: false,
      kosher: false,
    },
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 4,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_TABASCO',
    slug: 'tabasco-sauce',
    name: {
      en: 'Tabasco (Hot Sauce)',
      it: 'Tabasco',
      vi: 'Tương Ớt Tabasco',
      ko: '타바스코 소스',
      ja: 'タバスコ',
    },
    description: {
      en: 'Spicy pepper sauce for Bloody Marys',
      it: 'Salsa piccante per Bloody Mary',
    },
    category: { main: 'mixers', sub: 'sauce' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: { ...baseJuiceFlags, low_carb: true },
    spice: { level: 4 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 0,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_HORSERADISH',
    slug: 'horseradish',
    name: {
      en: 'Horseradish',
      it: 'Rafano',
      vi: 'Cải Ngựa',
      ko: '호스래디시',
      ja: 'ホースラディッシュ',
    },
    description: {
      en: 'Pungent root for Bloody Marys',
      it: 'Radice pungente per Bloody Mary',
    },
    category: { main: 'mixers', sub: 'condiment' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: { ...baseJuiceFlags, low_carb: true },
    spice: { level: 3 },
    nutrition: {
      protein_g: 0,
      carbs_g: 2,
      fat_g: 0,
      fiber_g: 1,
      calories_kcal: 7,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // FRUIT SYRUPS
  // ========================================================================
  {
    id: 'ING_RASPBERRY_SYRUP',
    slug: 'raspberry-syrup',
    name: {
      en: 'Raspberry Syrup',
      it: 'Sciroppo di Lampone',
      vi: 'Siro Mâm Xôi',
      ko: '라즈베리 시럽',
      ja: 'ラズベリーシロップ',
    },
    description: {
      en: 'Sweet raspberry syrup for Clover Club and fruit cocktails',
      it: 'Sciroppo dolce di lampone per Clover Club e cocktail alla frutta',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: { fructose: true },
    dietary_restrictions: { ...baseJuiceFlags },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 65,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 260,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_SUPERFINE_SUGAR',
    slug: 'superfine-sugar',
    name: {
      en: 'Superfine Sugar',
      it: 'Zucchero Semolato Fine',
      vi: 'Đường Siêu Mịn',
      ko: '미세설탕',
      ja: '上白糖',
    },
    description: {
      en: 'Fine sugar that dissolves quickly, essential for Daiquiris',
      it: 'Zucchero fine che si dissolve rapidamente, essenziale per Daiquiri',
    },
    category: { main: 'mixers', sub: 'sweetener' },
    allergens: {},
    intolerances: { fructose: true },
    dietary_restrictions: { ...baseJuiceFlags },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 100,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 387,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_STRAWBERRY_SYRUP',
    slug: 'strawberry-syrup',
    name: {
      en: 'Strawberry Syrup',
      it: 'Sciroppo di Fragola',
      vi: 'Siro Dâu Tây',
      ko: '딸기 시럽',
      ja: 'ストロベリーシロップ',
    },
    description: {
      en: 'Sweet strawberry syrup for fruit cocktails',
      it: 'Sciroppo dolce di fragola per cocktail alla frutta',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: { fructose: true },
    dietary_restrictions: { ...baseJuiceFlags },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 65,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 260,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_PASSION_FRUIT_SYRUP',
    slug: 'passion-fruit-syrup',
    name: {
      en: 'Passion Fruit Syrup',
      it: 'Sciroppo di Frutto della Passione',
      vi: 'Siro Chanh Dây',
      ko: '패션프루트 시럽',
      ja: 'パッションフルーツシロップ',
    },
    description: {
      en: 'Tropical passion fruit syrup for Porn Star Martini and tiki drinks',
      it: 'Sciroppo tropicale di frutto della passione per Porn Star Martini e drink tiki',
    },
    category: { main: 'mixers', sub: 'syrup' },
    allergens: {},
    intolerances: { fructose: true },
    dietary_restrictions: { ...baseJuiceFlags },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 62,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 248,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
];

// ============================================================================
// EXPORTS
// ============================================================================

export const MIXERS_COUNT = mixersIngredients.length;
