/**
 * GUDBRO Cocktail Ingredients - Base Spirits
 *
 * Core distilled spirits used in cocktails with complete 5 Dimensioni data:
 * - Dimensione 1: 30 Allergens (EU14 + Korea7 + Japan7 + GUDBRO2)
 * - Dimensione 2: 10 Intolerances
 * - Dimensione 3: 11 Dietary Flags
 * - Dimensione 4: 9 Nutritional Parameters (per 30ml serving)
 * - Dimensione 5: 6 Spice Levels (0-5)
 *
 * Categories:
 * - Gin (London Dry, Plymouth, Old Tom, etc.)
 * - Vodka (Neutral, Flavored)
 * - Rum (White, Gold, Dark, Spiced, Agricole)
 * - Whiskey (Bourbon, Rye, Scotch, Irish, Japanese)
 * - Tequila & Mezcal
 * - Brandy & Cognac
 * - Other Spirits (Pisco, Cachaça, Absinthe)
 *
 * @version 1.0
 * @lastUpdated 2025-12-13
 */

import type { IngredientMaster } from '../../types';

// Base dietary flags for most spirits (vegan, gluten-free after distillation)
const baseSpiritsFlags = {
  vegan: true,
  vegetarian: true,
  pescatarian: true,
  gluten_free: true, // Distillation removes gluten proteins
  dairy_free: true,
  nut_free: true,
  low_carb: true,
  halal: false, // Contains alcohol
  kosher: true, // Most unflavored spirits are kosher
};

export const spiritsIngredients: IngredientMaster[] = [
  // ========================================================================
  // GIN
  // ========================================================================
  {
    id: 'ING_GIN_LONDON_DRY',
    slug: 'london-dry-gin',
    name: {
      en: 'London Dry Gin',
      it: 'Gin London Dry',
      vi: 'Gin London Dry',
      ko: '런던 드라이 진',
      ja: 'ロンドンドライジン',
    },
    description: {
      en: 'Classic juniper-forward gin, essential for Martinis and G&Ts',
      it: 'Gin classico con ginepro predominante, essenziale per Martini e Gin Tonic',
    },
    category: { main: 'spirits', sub: 'gin' },
    allergens: {},
    intolerances: {
      alcohol: true,
    },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97, // per 30ml (1 oz) at 40% ABV
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_GIN_PLYMOUTH',
    slug: 'plymouth-gin',
    name: {
      en: 'Plymouth Gin',
      it: 'Gin Plymouth',
      vi: 'Gin Plymouth',
      ko: '플리머스 진',
      ja: 'プリマスジン',
    },
    description: {
      en: 'Slightly sweeter and more earthy than London Dry',
      it: 'Leggermente più dolce e terroso del London Dry',
    },
    category: { main: 'spirits', sub: 'gin' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_GIN_OLD_TOM',
    slug: 'old-tom-gin',
    name: {
      en: 'Old Tom Gin',
      it: 'Gin Old Tom',
      vi: 'Gin Old Tom',
      ko: '올드 톰 진',
      ja: 'オールドトムジン',
    },
    description: {
      en: 'Slightly sweetened gin, bridge between London Dry and Genever',
      it: 'Gin leggermente dolcificato, ponte tra London Dry e Genever',
    },
    category: { main: 'spirits', sub: 'gin' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 2,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 105,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_GIN_SLOE',
    slug: 'sloe-gin',
    name: {
      en: 'Sloe Gin',
      it: 'Sloe Gin',
      vi: 'Sloe Gin',
      ko: '슬로 진',
      ja: 'スロージン',
    },
    description: {
      en: 'Red liqueur made from gin infused with sloe berries',
      it: 'Liquore rosso fatto con gin infuso con bacche di prugnolo',
    },
    category: { main: 'spirits', sub: 'gin' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 10,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 110,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // VODKA
  // ========================================================================
  {
    id: 'ING_VODKA',
    slug: 'vodka',
    name: {
      en: 'Vodka',
      it: 'Vodka',
      vi: 'Vodka',
      ko: '보드카',
      ja: 'ウォッカ',
    },
    description: {
      en: 'Neutral spirit, versatile base for countless cocktails',
      it: 'Distillato neutro, base versatile per innumerevoli cocktail',
    },
    category: { main: 'spirits', sub: 'vodka' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_VODKA_CITRUS',
    slug: 'citrus-vodka',
    name: {
      en: 'Citrus Vodka',
      it: 'Vodka agli Agrumi',
      vi: 'Vodka Cam Chanh',
      ko: '시트러스 보드카',
      ja: 'シトラスウォッカ',
    },
    description: {
      en: 'Vodka infused with lemon or citrus flavors',
      it: 'Vodka infusa con aromi di limone o agrumi',
    },
    category: { main: 'spirits', sub: 'vodka' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_VODKA_VANILLA',
    slug: 'vanilla-vodka',
    name: {
      en: 'Vanilla Vodka',
      it: 'Vodka alla Vaniglia',
      vi: 'Vodka Vani',
      ko: '바닐라 보드카',
      ja: 'バニラウォッカ',
    },
    category: { main: 'spirits', sub: 'vodka' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 1,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 100,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // RUM
  // ========================================================================
  {
    id: 'ING_RUM_WHITE',
    slug: 'white-rum',
    name: {
      en: 'White Rum',
      it: 'Rum Bianco',
      vi: 'Rum Trắng',
      ko: '화이트 럼',
      ja: 'ホワイトラム',
    },
    description: {
      en: 'Light-bodied rum, essential for Mojitos and Daiquiris',
      it: 'Rum leggero, essenziale per Mojito e Daiquiri',
    },
    category: { main: 'spirits', sub: 'rum' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RUM_GOLD',
    slug: 'gold-rum',
    name: {
      en: 'Gold Rum',
      it: 'Rum Ambrato',
      vi: 'Rum Vàng',
      ko: '골드 럼',
      ja: 'ゴールドラム',
    },
    description: {
      en: 'Medium-bodied aged rum with caramel notes',
      it: 'Rum invecchiato di corpo medio con note di caramello',
    },
    category: { main: 'spirits', sub: 'rum' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RUM_DARK',
    slug: 'dark-rum',
    name: {
      en: 'Dark Rum',
      it: 'Rum Scuro',
      vi: 'Rum Đen',
      ko: '다크 럼',
      ja: 'ダークラム',
    },
    description: {
      en: 'Full-bodied rum with molasses and spice notes',
      it: 'Rum corposo con note di melassa e spezie',
    },
    category: { main: 'spirits', sub: 'rum' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RUM_SPICED',
    slug: 'spiced-rum',
    name: {
      en: 'Spiced Rum',
      it: 'Rum Speziato',
      vi: 'Rum Gia Vị',
      ko: '스파이스드 럼',
      ja: 'スパイスドラム',
    },
    description: {
      en: 'Rum infused with spices like vanilla, cinnamon, and clove',
      it: 'Rum infuso con spezie come vaniglia, cannella e chiodi di garofano',
    },
    category: { main: 'spirits', sub: 'rum' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RUM_OVERPROOF',
    slug: 'overproof-rum',
    name: {
      en: 'Overproof Rum',
      it: 'Rum Overproof',
      vi: 'Rum Overproof',
      ko: '오버프루프 럼',
      ja: 'オーバープルーフラム',
    },
    description: {
      en: 'High-proof rum (typically 60%+ ABV) for Tiki cocktails',
      it: 'Rum ad alta gradazione (tipicamente 60%+ ABV) per cocktail Tiki',
    },
    category: { main: 'spirits', sub: 'rum' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 140,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RUM_AGRICOLE',
    slug: 'rhum-agricole',
    name: {
      en: 'Rhum Agricole',
      it: 'Rhum Agricole',
      vi: 'Rhum Agricole',
      ko: '럼 아그리콜',
      ja: 'ラム・アグリコール',
    },
    description: {
      en: 'French-style rum made from fresh sugarcane juice',
      it: 'Rum in stile francese fatto con succo di canna fresco',
    },
    category: { main: 'spirits', sub: 'rum' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RUM_COCONUT',
    slug: 'coconut-rum',
    name: {
      en: 'Coconut Rum',
      it: 'Rum al Cocco',
      vi: 'Rum Dừa',
      ko: '코코넛 럼',
      ja: 'ココナッツラム',
    },
    description: {
      en: 'Rum flavored with coconut, popular for tropical drinks',
      it: 'Rum aromatizzato al cocco, popolare per drink tropicali',
    },
    category: { main: 'spirits', sub: 'rum' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 5,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 110,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // WHISKEY - BOURBON
  // ========================================================================
  {
    id: 'ING_BOURBON',
    slug: 'bourbon-whiskey',
    name: {
      en: 'Bourbon Whiskey',
      it: 'Bourbon',
      vi: 'Bourbon',
      ko: '버번 위스키',
      ja: 'バーボンウイスキー',
    },
    description: {
      en: 'American whiskey made primarily from corn, sweet and full-bodied',
      it: 'Whiskey americano fatto principalmente con mais, dolce e corposo',
    },
    category: { main: 'spirits', sub: 'whiskey' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_RYE_WHISKEY',
    slug: 'rye-whiskey',
    name: {
      en: 'Rye Whiskey',
      it: 'Whiskey di Segale',
      vi: 'Whiskey Lúa Mạch Đen',
      ko: '라이 위스키',
      ja: 'ライウイスキー',
    },
    description: {
      en: 'Spicier American whiskey, classic for Manhattans and Sazeracs',
      it: 'Whiskey americano più speziato, classico per Manhattan e Sazerac',
    },
    category: { main: 'spirits', sub: 'whiskey' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // WHISKEY - SCOTCH
  // ========================================================================
  {
    id: 'ING_SCOTCH_BLENDED',
    slug: 'blended-scotch',
    name: {
      en: 'Blended Scotch Whisky',
      it: 'Scotch Blended',
      vi: 'Scotch Blended',
      ko: '블렌디드 스카치',
      ja: 'ブレンデッドスコッチ',
    },
    description: {
      en: 'Blended Scottish whisky, smooth and versatile',
      it: 'Whisky scozzese blended, morbido e versatile',
    },
    category: { main: 'spirits', sub: 'whiskey' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_SCOTCH_SINGLE_MALT',
    slug: 'single-malt-scotch',
    name: {
      en: 'Single Malt Scotch',
      it: 'Scotch Single Malt',
      vi: 'Scotch Single Malt',
      ko: '싱글몰트 스카치',
      ja: 'シングルモルトスコッチ',
    },
    description: {
      en: 'Premium Scottish whisky from a single distillery',
      it: 'Whisky scozzese premium da una singola distilleria',
    },
    category: { main: 'spirits', sub: 'whiskey' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_SCOTCH_ISLAY',
    slug: 'islay-scotch',
    name: {
      en: 'Islay Scotch (Peated)',
      it: 'Scotch Islay (Torbato)',
      vi: 'Scotch Islay',
      ko: '아일라 스카치',
      ja: 'アイラスコッチ',
    },
    description: {
      en: 'Heavily peated smoky Scotch from Islay island',
      it: 'Scotch fortemente torbato e affumicato dall\'isola di Islay',
    },
    category: { main: 'spirits', sub: 'whiskey' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // WHISKEY - IRISH
  // ========================================================================
  {
    id: 'ING_IRISH_WHISKEY',
    slug: 'irish-whiskey',
    name: {
      en: 'Irish Whiskey',
      it: 'Whiskey Irlandese',
      vi: 'Whiskey Ireland',
      ko: '아이리시 위스키',
      ja: 'アイリッシュウイスキー',
    },
    description: {
      en: 'Smooth triple-distilled Irish whiskey',
      it: 'Whiskey irlandese morbido tripla distillazione',
    },
    category: { main: 'spirits', sub: 'whiskey' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // WHISKEY - JAPANESE
  // ========================================================================
  {
    id: 'ING_JAPANESE_WHISKY',
    slug: 'japanese-whisky',
    name: {
      en: 'Japanese Whisky',
      it: 'Whisky Giapponese',
      vi: 'Whisky Nhật',
      ko: '일본 위스키',
      ja: 'ジャパニーズウイスキー',
    },
    description: {
      en: 'Refined Japanese whisky, often inspired by Scotch traditions',
      it: 'Whisky giapponese raffinato, spesso ispirato alle tradizioni scozzesi',
    },
    category: { main: 'spirits', sub: 'whiskey' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // TEQUILA & MEZCAL
  // ========================================================================
  {
    id: 'ING_TEQUILA_BLANCO',
    slug: 'tequila-blanco',
    name: {
      en: 'Tequila Blanco',
      it: 'Tequila Blanco',
      vi: 'Tequila Trắng',
      ko: '테킬라 블랑코',
      ja: 'テキーラブランコ',
    },
    description: {
      en: 'Unaged agave spirit, crisp and essential for Margaritas',
      it: 'Distillato di agave non invecchiato, fresco ed essenziale per Margarita',
    },
    category: { main: 'spirits', sub: 'tequila' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_TEQUILA_REPOSADO',
    slug: 'tequila-reposado',
    name: {
      en: 'Tequila Reposado',
      it: 'Tequila Reposado',
      vi: 'Tequila Reposado',
      ko: '테킬라 레포사도',
      ja: 'テキーラレポサド',
    },
    description: {
      en: 'Aged 2-12 months in oak, smooth with vanilla notes',
      it: 'Invecchiato 2-12 mesi in rovere, morbido con note di vaniglia',
    },
    category: { main: 'spirits', sub: 'tequila' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_TEQUILA_ANEJO',
    slug: 'tequila-anejo',
    name: {
      en: 'Tequila Añejo',
      it: 'Tequila Añejo',
      vi: 'Tequila Añejo',
      ko: '테킬라 아녜호',
      ja: 'テキーラアニェホ',
    },
    description: {
      en: 'Aged 1-3 years, complex with caramel and oak flavors',
      it: 'Invecchiato 1-3 anni, complesso con note di caramello e rovere',
    },
    category: { main: 'spirits', sub: 'tequila' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_MEZCAL',
    slug: 'mezcal',
    name: {
      en: 'Mezcal',
      it: 'Mezcal',
      vi: 'Mezcal',
      ko: '메즈칼',
      ja: 'メスカル',
    },
    description: {
      en: 'Smoky agave spirit, artisanal cousin of tequila',
      it: 'Distillato di agave affumicato, cugino artigianale della tequila',
    },
    category: { main: 'spirits', sub: 'mezcal' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // BRANDY & COGNAC
  // ========================================================================
  {
    id: 'ING_COGNAC',
    slug: 'cognac',
    name: {
      en: 'Cognac',
      it: 'Cognac',
      vi: 'Cognac',
      ko: '코냑',
      ja: 'コニャック',
    },
    description: {
      en: 'French grape brandy from the Cognac region',
      it: 'Brandy di uva francese dalla regione di Cognac',
    },
    category: { main: 'spirits', sub: 'brandy' },
    allergens: {
      sulphites: true, // Grape-derived, may contain sulphites
    },
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_BRANDY',
    slug: 'brandy',
    name: {
      en: 'Brandy',
      it: 'Brandy',
      vi: 'Brandy',
      ko: '브랜디',
      ja: 'ブランデー',
    },
    description: {
      en: 'Grape-based spirit, aged in oak barrels',
      it: 'Distillato di uva, invecchiato in botti di rovere',
    },
    category: { main: 'spirits', sub: 'brandy' },
    allergens: {
      sulphites: true,
    },
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CALVADOS',
    slug: 'calvados',
    name: {
      en: 'Calvados',
      it: 'Calvados',
      vi: 'Calvados',
      ko: '칼바도스',
      ja: 'カルヴァドス',
    },
    description: {
      en: 'French apple brandy from Normandy',
      it: 'Brandy di mele francese dalla Normandia',
    },
    category: { main: 'spirits', sub: 'brandy' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_ARMAGNAC',
    slug: 'armagnac',
    name: {
      en: 'Armagnac',
      it: 'Armagnac',
      vi: 'Armagnac',
      ko: '아르마냑',
      ja: 'アルマニャック',
    },
    description: {
      en: 'French grape brandy from Gascony, earthier than Cognac',
      it: 'Brandy di uva francese dalla Guascogna, più terroso del Cognac',
    },
    category: { main: 'spirits', sub: 'brandy' },
    allergens: {
      sulphites: true,
    },
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // OTHER SPIRITS
  // ========================================================================
  {
    id: 'ING_PISCO',
    slug: 'pisco',
    name: {
      en: 'Pisco',
      it: 'Pisco',
      vi: 'Pisco',
      ko: '피스코',
      ja: 'ピスコ',
    },
    description: {
      en: 'South American grape brandy, essential for Pisco Sour',
      it: 'Brandy di uva sudamericano, essenziale per il Pisco Sour',
    },
    category: { main: 'spirits', sub: 'pisco' },
    allergens: {
      sulphites: true,
    },
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_CACHACA',
    slug: 'cachaca',
    name: {
      en: 'Cachaça',
      it: 'Cachaça',
      vi: 'Cachaça',
      ko: '카샤사',
      ja: 'カシャーサ',
    },
    description: {
      en: 'Brazilian sugarcane spirit, essential for Caipirinha',
      it: 'Distillato di canna brasiliano, essenziale per la Caipirinha',
    },
    category: { main: 'spirits', sub: 'cachaca' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_ABSINTHE',
    slug: 'absinthe',
    name: {
      en: 'Absinthe',
      it: 'Assenzio',
      vi: 'Absinthe',
      ko: '압생트',
      ja: 'アブサン',
    },
    description: {
      en: 'High-proof anise-flavored spirit with wormwood',
      it: 'Distillato ad alta gradazione all\'anice con assenzio',
    },
    category: { main: 'spirits', sub: 'absinthe' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 120,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_GRAPPA',
    slug: 'grappa',
    name: {
      en: 'Grappa',
      it: 'Grappa',
      vi: 'Grappa',
      ko: '그라파',
      ja: 'グラッパ',
    },
    description: {
      en: 'Italian grape pomace brandy',
      it: 'Acquavite italiana di vinaccia',
    },
    category: { main: 'spirits', sub: 'grappa' },
    allergens: {
      sulphites: true,
    },
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_AQUAVIT',
    slug: 'aquavit',
    name: {
      en: 'Aquavit',
      it: 'Aquavit',
      vi: 'Aquavit',
      ko: '아쿠아비트',
      ja: 'アクアビット',
    },
    description: {
      en: 'Scandinavian spirit flavored with caraway or dill',
      it: 'Distillato scandinavo aromatizzato con cumino o aneto',
    },
    category: { main: 'spirits', sub: 'aquavit' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 1 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 97,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_BAIJIU',
    slug: 'baijiu',
    name: {
      en: 'Baijiu',
      it: 'Baijiu',
      vi: 'Bạch Tửu',
      ko: '바이주',
      ja: '白酒',
    },
    description: {
      en: 'Chinese grain spirit, typically very strong and aromatic',
      it: 'Distillato di cereali cinese, tipicamente molto forte e aromatico',
    },
    category: { main: 'spirits', sub: 'baijiu' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 130,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_SOJU',
    slug: 'soju',
    name: {
      en: 'Soju',
      it: 'Soju',
      vi: 'Soju',
      ko: '소주',
      ja: '焼酎',
    },
    description: {
      en: 'Korean distilled spirit, clear and mild',
      it: 'Distillato coreano, chiaro e delicato',
    },
    category: { main: 'spirits', sub: 'soju' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 64, // Lower ABV typically 16-25%
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
  {
    id: 'ING_SHOCHU',
    slug: 'shochu',
    name: {
      en: 'Shochu',
      it: 'Shochu',
      vi: 'Shochu',
      ko: '쇼추',
      ja: '焼酎',
    },
    description: {
      en: 'Japanese distilled spirit made from various ingredients',
      it: 'Distillato giapponese fatto con vari ingredienti',
    },
    category: { main: 'spirits', sub: 'shochu' },
    allergens: {},
    intolerances: { alcohol: true },
    dietary_restrictions: baseSpiritsFlags,
    spice: { level: 0 },
    nutrition: {
      protein_g: 0,
      carbs_g: 0,
      fat_g: 0,
      fiber_g: 0,
      calories_kcal: 70,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
];

// ============================================================================
// EXPORTS
// ============================================================================

export const SPIRITS_COUNT = spiritsIngredients.length;
