-- ============================================
-- LEBANESE DATABASE - Data Import
-- ============================================
-- 84 Lebanese dishes across 10 categories
-- Run AFTER 01-lebanese-missing-ingredients.sql
-- ============================================

INSERT INTO lebanese (id, slug, name, description, arabic_name, arabic_script, category, status, region, protein_type, cooking_method, is_mezze, is_festive, is_street_food, is_lenten, ingredient_ids, allergens, is_gluten_free, is_dairy_free, is_nut_free, is_vegan, is_vegetarian, is_halal, is_pescatarian, spice_level, tags, popularity)
VALUES

-- ============================================
-- MEZZE & DIPS (12 items)
-- ============================================
('LEBANESE_HUMMUS', 'hummus', 'Hummus', 'Creamy chickpea dip with tahini, lemon juice, and garlic, drizzled with olive oil', 'Hummus', 'حمص', 'mezze_dips', 'signature', 'national', 'vegan', 'raw', true, false, false, true, ARRAY['ING_CHICKPEAS', 'ING_TAHINI', 'ING_LEMON', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_CUMIN', 'ING_SEA_SALT'], ARRAY['sesame'], true, true, true, true, true, true, true, 0, ARRAY['iconic', 'vegan', 'healthy', 'dip'], 100),
('LEBANESE_HUMMUS_BEIRUTY', 'hummus-beiruty', 'Hummus Beiruty', 'Beirut-style hummus topped with spiced lamb, pine nuts, and pomegranate', 'Hummus Beiruty', 'حمص بيروتي', 'mezze_dips', 'premium', 'beirut', 'lamb', 'raw', true, true, false, false, ARRAY['ING_CHICKPEAS', 'ING_TAHINI', 'ING_LEMON', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_GROUND_LAMB', 'ING_PINE_NUTS', 'ING_POMEGRANATE_SEEDS', 'ING_SEVEN_SPICE'], ARRAY['sesame', 'tree_nuts'], true, true, false, false, false, true, false, 1, ARRAY['premium', 'beirut-style', 'lamb'], 85),
('LEBANESE_BABA_GANOUSH', 'baba-ganoush', 'Baba Ganoush', 'Smoky roasted eggplant dip with tahini, lemon, and garlic', 'Baba Ghanouj', 'بابا غنوج', 'mezze_dips', 'signature', 'national', 'vegan', 'roasted', true, false, false, true, ARRAY['ING_EGGPLANT', 'ING_TAHINI', 'ING_LEMON', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_PARSLEY', 'ING_SEA_SALT'], ARRAY['sesame'], true, true, true, true, true, true, true, 0, ARRAY['smoky', 'vegan', 'eggplant', 'dip'], 95),
('LEBANESE_MUTABAL', 'mutabal', 'Mutabal', 'Smoky eggplant dip similar to baba ganoush but with more tahini and yogurt', 'Mutabbal', 'متبل', 'mezze_dips', 'classic', 'national', 'vegetarian', 'roasted', true, false, false, false, ARRAY['ING_EGGPLANT', 'ING_TAHINI', 'ING_YOGURT', 'ING_LEMON', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_POMEGRANATE_MOLASSES'], ARRAY['sesame', 'dairy'], true, false, true, false, true, true, true, 0, ARRAY['smoky', 'creamy', 'eggplant'], 80),
('LEBANESE_LABNEH', 'labneh', 'Labneh', 'Thick strained yogurt drizzled with olive oil, often served with za''atar', 'Labneh', 'لبنة', 'mezze_dips', 'signature', 'national', 'vegetarian', 'raw', true, false, false, false, ARRAY['ING_LABNEH', 'ING_OLIVE_OIL', 'ING_ZAATAR', 'ING_SEA_SALT'], ARRAY['dairy'], true, false, true, false, true, true, true, 0, ARRAY['breakfast', 'creamy', 'yogurt', 'healthy'], 95),
('LEBANESE_MUHAMMARA', 'muhammara', 'Muhammara', 'Spicy roasted red pepper and walnut dip with pomegranate molasses', 'Muhammara', 'محمرة', 'mezze_dips', 'classic', 'north_lebanon', 'vegan', 'roasted', true, false, false, true, ARRAY['ING_ROASTED_RED_PEPPER', 'ING_WALNUTS', 'ING_POMEGRANATE_MOLASSES', 'ING_BREADCRUMBS', 'ING_OLIVE_OIL', 'ING_CUMIN', 'ING_ALEPPO_PEPPER', 'ING_GARLIC'], ARRAY['tree_nuts', 'gluten'], false, true, false, true, true, true, true, 2, ARRAY['spicy', 'walnut', 'pepper', 'syrian-influenced'], 75),
('LEBANESE_SHANKLISH', 'shanklish', 'Shanklish', 'Aged cheese balls rolled in za''atar and Aleppo pepper, served with tomato and onion', 'Shanklish', 'شنكليش', 'mezze_dips', 'traditional', 'mount_lebanon', 'vegetarian', 'raw', true, false, false, false, ARRAY['ING_SHANKLISH_CHEESE', 'ING_TOMATO', 'ING_ONION', 'ING_ZAATAR', 'ING_ALEPPO_PEPPER', 'ING_OLIVE_OIL'], ARRAY['dairy'], true, false, true, false, true, true, true, 1, ARRAY['cheese', 'aged', 'traditional'], 65),
('LEBANESE_TOUM', 'toum', 'Toum', 'Fluffy Lebanese garlic sauce emulsified with oil and lemon, served with grilled meats', 'Toum', 'تومية', 'mezze_dips', 'signature', 'national', 'vegan', 'raw', true, false, true, true, ARRAY['ING_GARLIC', 'ING_VEGETABLE_OIL', 'ING_LEMON', 'ING_SEA_SALT'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['garlic', 'sauce', 'condiment', 'essential'], 90),
('LEBANESE_FOUL_MUDAMMAS', 'foul-mudammas', 'Foul Mudammas', 'Slow-cooked fava beans mashed with garlic, lemon, and olive oil', 'Foul Mudammas', 'فول مدمس', 'mezze_dips', 'classic', 'national', 'vegan', 'stewed', true, false, true, true, ARRAY['ING_FAVA_BEANS', 'ING_GARLIC', 'ING_LEMON', 'ING_OLIVE_OIL', 'ING_CUMIN', 'ING_PARSLEY', 'ING_SEA_SALT'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['breakfast', 'protein', 'fava', 'traditional'], 85),
('LEBANESE_FATTEH', 'fatteh', 'Fatteh', 'Layered dish of crispy pita, chickpeas, and yogurt sauce topped with pine nuts', 'Fatteh', 'فتة', 'mezze_dips', 'festive', 'national', 'vegetarian', 'baked', true, true, false, false, ARRAY['ING_PITA_BREAD', 'ING_CHICKPEAS', 'ING_YOGURT', 'ING_TAHINI', 'ING_GARLIC', 'ING_PINE_NUTS', 'ING_BUTTER', 'ING_CUMIN', 'ING_PAPRIKA'], ARRAY['gluten', 'dairy', 'sesame', 'tree_nuts'], false, false, false, false, true, true, true, 0, ARRAY['festive', 'layered', 'breakfast', 'eid'], 80),
('LEBANESE_TARAMOSALATA', 'taramosalata-lebanese', 'Taramosalata', 'Creamy fish roe dip with bread, lemon juice, and olive oil', 'Tarama', 'طراما', 'mezze_dips', 'classic', 'beirut', 'fish', 'raw', true, false, false, true, ARRAY['ING_FISH_ROE', 'ING_BREAD', 'ING_LEMON', 'ING_OLIVE_OIL', 'ING_ONION'], ARRAY['fish', 'gluten'], false, true, true, false, false, true, true, 0, ARRAY['seafood', 'lenten', 'dip'], 60),
('LEBANESE_HUMMUS_KAWARMA', 'hummus-kawarma', 'Hummus Kawarma', 'Hummus topped with spiced lamb confit and toasted pine nuts', 'Hummus bil Awarma', 'حمص بالقوارما', 'mezze_dips', 'premium', 'mount_lebanon', 'lamb', 'raw', true, true, false, false, ARRAY['ING_CHICKPEAS', 'ING_TAHINI', 'ING_LEMON', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_KAWARMA', 'ING_PINE_NUTS'], ARRAY['sesame', 'tree_nuts'], true, true, false, false, false, true, false, 1, ARRAY['premium', 'lamb-confit', 'traditional'], 75),

-- ============================================
-- SALADS (8 items)
-- ============================================
('LEBANESE_TABBOULEH', 'tabbouleh', 'Tabbouleh', 'Fresh parsley salad with bulgur wheat, tomatoes, mint, lemon, and olive oil', 'Tabbouleh', 'تبولة', 'salads', 'signature', 'national', 'vegan', 'raw', true, false, false, true, ARRAY['ING_PARSLEY', 'ING_BULGUR', 'ING_TOMATO', 'ING_MINT', 'ING_SCALLIONS', 'ING_LEMON', 'ING_OLIVE_OIL', 'ING_SEA_SALT'], ARRAY['gluten'], false, true, true, true, true, true, true, 0, ARRAY['iconic', 'fresh', 'healthy', 'parsley'], 100),
('LEBANESE_FATTOUSH', 'fattoush', 'Fattoush', 'Crunchy salad with toasted pita, mixed greens, radishes, and sumac dressing', 'Fattoush', 'فتوش', 'salads', 'signature', 'national', 'vegan', 'raw', true, false, false, true, ARRAY['ING_PITA_BREAD', 'ING_ROMAINE_LETTUCE', 'ING_TOMATO', 'ING_CUCUMBER', 'ING_RADISH', 'ING_SCALLIONS', 'ING_MINT', 'ING_SUMAC', 'ING_POMEGRANATE_MOLASSES', 'ING_OLIVE_OIL', 'ING_LEMON'], ARRAY['gluten'], false, true, true, true, true, true, true, 0, ARRAY['crunchy', 'sumac', 'refreshing'], 95),
('LEBANESE_SALATA_BALADI', 'salata-baladi', 'Salata Baladi', 'Traditional village salad with tomatoes, cucumber, onion, and lemon dressing', 'Salata Baladi', 'سلطة بلدي', 'salads', 'classic', 'national', 'vegan', 'raw', true, false, false, true, ARRAY['ING_TOMATO', 'ING_CUCUMBER', 'ING_ONION', 'ING_PARSLEY', 'ING_MINT', 'ING_OLIVE_OIL', 'ING_LEMON', 'ING_SEA_SALT'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['simple', 'village-style', 'fresh'], 75),
('LEBANESE_ROCCA_SALAD', 'rocca-salad', 'Rocca Salad', 'Peppery arugula salad with halloumi, pomegranate seeds, and balsamic', 'Salatet Rocca', 'سلطة روكا', 'salads', 'popular', 'beirut', 'vegetarian', 'raw', true, false, false, false, ARRAY['ING_ARUGULA', 'ING_HALLOUMI', 'ING_POMEGRANATE_SEEDS', 'ING_WALNUTS', 'ING_BALSAMIC_VINEGAR', 'ING_OLIVE_OIL', 'ING_HONEY'], ARRAY['dairy', 'tree_nuts'], true, false, false, false, true, true, true, 0, ARRAY['modern', 'halloumi', 'pomegranate'], 80),
('LEBANESE_HINDBEH', 'hindbeh', 'Hindbeh', 'Sauteed dandelion greens with caramelized onions and lemon', 'Hindbeh', 'هندباء', 'salads', 'traditional', 'mount_lebanon', 'vegan', 'stewed', true, false, false, true, ARRAY['ING_DANDELION_GREENS', 'ING_ONION', 'ING_OLIVE_OIL', 'ING_LEMON', 'ING_SEA_SALT'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['bitter', 'healthy', 'traditional', 'greens'], 60),
('LEBANESE_LOUBIEH_BZEIT', 'loubieh-bzeit', 'Loubieh bi Zeit', 'Green beans braised in tomato sauce with garlic and onions, served cold', 'Loubieh bi Zeit', 'لوبية بزيت', 'salads', 'classic', 'national', 'vegan', 'stewed', true, false, false, true, ARRAY['ING_GREEN_BEANS', 'ING_TOMATO', 'ING_ONION', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_TOMATO_PASTE', 'ING_SEA_SALT'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['cold-dish', 'lenten', 'green-beans'], 70),
('LEBANESE_BATATA_HARRA', 'batata-harra', 'Batata Harra', 'Spicy Lebanese potatoes with garlic, coriander, and chili peppers', 'Batata Harra', 'بطاطا حرة', 'salads', 'popular', 'beirut', 'vegan', 'fried', true, false, true, true, ARRAY['ING_POTATO', 'ING_GARLIC', 'ING_CILANTRO', 'ING_CHILI_FLAKES', 'ING_OLIVE_OIL', 'ING_LEMON', 'ING_SEA_SALT'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 2, ARRAY['spicy', 'potatoes', 'street-food'], 85),
('LEBANESE_RAHEB_SALAD', 'raheb-salad', 'Raheb Salad', 'Smoky eggplant salad with tomatoes, peppers, onion, and pomegranate molasses', 'Salatet Raheb', 'سلطة الراهب', 'salads', 'classic', 'national', 'vegan', 'roasted', true, false, false, true, ARRAY['ING_EGGPLANT', 'ING_TOMATO', 'ING_BELL_PEPPER', 'ING_ONION', 'ING_PARSLEY', 'ING_POMEGRANATE_MOLASSES', 'ING_OLIVE_OIL', 'ING_LEMON'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['smoky', 'eggplant', 'lenten'], 65),

-- ============================================
-- KIBBEH (8 items)
-- ============================================
('LEBANESE_KIBBEH_NAYEH', 'kibbeh-nayeh', 'Kibbeh Nayeh', 'Raw kibbeh - finest ground lamb mixed with bulgur, spices, served with olive oil and mint', 'Kibbeh Nayeh', 'كبة نية', 'kibbeh', 'signature', 'national', 'lamb', 'raw', true, true, false, false, ARRAY['ING_GROUND_LAMB', 'ING_BULGUR', 'ING_ONION', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_OLIVE_OIL', 'ING_MINT', 'ING_SEA_SALT', 'ING_BLACK_PEPPER'], ARRAY['gluten'], false, true, true, false, false, true, false, 1, ARRAY['raw', 'delicacy', 'national-dish', 'premium'], 90),
('LEBANESE_KIBBEH_MAKLIYEH', 'kibbeh-makliyeh', 'Kibbeh Makliyeh', 'Fried kibbeh torpedoes stuffed with spiced lamb, pine nuts, and onions', 'Kibbeh Maqliyeh', 'كبة مقلية', 'kibbeh', 'signature', 'national', 'lamb', 'fried', true, true, true, false, ARRAY['ING_GROUND_LAMB', 'ING_BULGUR', 'ING_ONION', 'ING_PINE_NUTS', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_VEGETABLE_OIL', 'ING_SEA_SALT'], ARRAY['gluten', 'tree_nuts'], false, true, false, false, false, true, false, 1, ARRAY['fried', 'stuffed', 'iconic', 'appetizer'], 95),
('LEBANESE_KIBBEH_BSAYNIYEH', 'kibbeh-bsayniyeh', 'Kibbeh bil Sayniyeh', 'Baked kibbeh layered in a tray with spiced lamb and pine nut filling', 'Kibbeh bil Sayniyeh', 'كبة بالصينية', 'kibbeh', 'classic', 'national', 'lamb', 'baked', false, true, false, false, ARRAY['ING_GROUND_LAMB', 'ING_BULGUR', 'ING_ONION', 'ING_PINE_NUTS', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_BUTTER', 'ING_SEA_SALT'], ARRAY['gluten', 'tree_nuts', 'dairy'], false, false, false, false, false, true, false, 1, ARRAY['baked', 'casserole', 'sunday-lunch'], 85),
('LEBANESE_KIBBEH_LABANIEH', 'kibbeh-labanieh', 'Kibbeh Labanieh', 'Kibbeh balls cooked in creamy cooked yogurt sauce', 'Kibbeh Labanieh', 'كبة لبنية', 'kibbeh', 'classic', 'national', 'lamb', 'stewed', false, false, false, false, ARRAY['ING_GROUND_LAMB', 'ING_BULGUR', 'ING_YOGURT', 'ING_EGG', 'ING_GARLIC', 'ING_DRIED_MINT', 'ING_CORNSTARCH', 'ING_SEA_SALT'], ARRAY['gluten', 'dairy', 'egg'], false, false, true, false, false, true, false, 0, ARRAY['yogurt-sauce', 'comfort-food', 'creamy'], 80),
('LEBANESE_KIBBEH_SAMAK', 'kibbeh-samak', 'Kibbeh Samak', 'Fish kibbeh made with white fish, bulgur, and citrus, popular in coastal areas', 'Kibbeh Samak', 'كبة سمك', 'kibbeh', 'traditional', 'sidon', 'fish', 'fried', true, false, false, true, ARRAY['ING_WHITE_FISH', 'ING_BULGUR', 'ING_ONION', 'ING_CILANTRO', 'ING_ORANGE_ZEST', 'ING_CUMIN', 'ING_PINE_NUTS', 'ING_VEGETABLE_OIL'], ARRAY['gluten', 'fish', 'tree_nuts'], false, true, false, false, false, true, true, 0, ARRAY['fish', 'coastal', 'lenten', 'sidon-specialty'], 65),
('LEBANESE_KIBBEH_LAKTEEN', 'kibbeh-lakteen', 'Kibbeh Lakteen', 'Pumpkin kibbeh - vegetarian version with butternut squash and bulgur', 'Kibbeh Lakteen', 'كبة لقطين', 'kibbeh', 'traditional', 'mount_lebanon', 'vegan', 'baked', true, false, false, true, ARRAY['ING_BUTTERNUT_SQUASH', 'ING_BULGUR', 'ING_ONION', 'ING_SPINACH', 'ING_CHICKPEAS', 'ING_WALNUTS', 'ING_SEVEN_SPICE', 'ING_OLIVE_OIL'], ARRAY['gluten', 'tree_nuts'], false, true, false, true, true, true, true, 0, ARRAY['vegetarian', 'pumpkin', 'lenten', 'autumn'], 60),
('LEBANESE_KIBBEH_ARNABIYEH', 'kibbeh-arnabiyeh', 'Kibbeh Arnabiyeh', 'Kibbeh cooked in tahini sauce with chickpeas', 'Kibbeh Arnabiyeh', 'كبة أرنبية', 'kibbeh', 'traditional', 'tripoli', 'lamb', 'stewed', false, false, false, false, ARRAY['ING_GROUND_LAMB', 'ING_BULGUR', 'ING_TAHINI', 'ING_CHICKPEAS', 'ING_ONION', 'ING_LEMON', 'ING_GARLIC', 'ING_SEA_SALT'], ARRAY['gluten', 'sesame'], false, true, true, false, false, true, false, 0, ARRAY['tahini-sauce', 'tripoli-style', 'comfort-food'], 55),
('LEBANESE_KIBBEH_BATATA', 'kibbeh-batata', 'Kibbeh Batata', 'Potato kibbeh - a vegetarian version made with mashed potatoes instead of bulgur', 'Kibbeh Batata', 'كبة بطاطا', 'kibbeh', 'classic', 'national', 'vegetarian', 'fried', true, false, true, true, ARRAY['ING_POTATO', 'ING_BULGUR', 'ING_ONION', 'ING_SPINACH', 'ING_WALNUTS', 'ING_SEVEN_SPICE', 'ING_VEGETABLE_OIL', 'ING_SEA_SALT'], ARRAY['gluten', 'tree_nuts'], false, true, false, true, true, true, true, 0, ARRAY['vegetarian', 'potato', 'lenten', 'budget-friendly'], 70),

-- ============================================
-- GRILLED MEATS (10 items)
-- ============================================
('LEBANESE_SHAWARMA_CHICKEN', 'shawarma-chicken', 'Chicken Shawarma', 'Marinated chicken slowly roasted on a vertical spit, sliced thin and served in pita with toum', 'Shawarma Djeij', 'شاورما دجاج', 'grilled_meats', 'signature', 'national', 'chicken', 'roasted', false, false, true, false, ARRAY['ING_CHICKEN_THIGH', 'ING_YOGURT', 'ING_GARLIC', 'ING_SEVEN_SPICE', 'ING_PAPRIKA', 'ING_TURMERIC', 'ING_LEMON', 'ING_OLIVE_OIL', 'ING_PITA_BREAD', 'ING_PICKLES', 'ING_TOUM'], ARRAY['gluten', 'dairy'], false, false, true, false, false, true, false, 1, ARRAY['street-food', 'iconic', 'rotisserie'], 100),
('LEBANESE_SHAWARMA_LAMB', 'shawarma-lamb', 'Lamb Shawarma', 'Spiced lamb slowly roasted on a vertical spit, served with tahini sauce and pickles', 'Shawarma Lahmeh', 'شاورما لحمة', 'grilled_meats', 'signature', 'national', 'lamb', 'roasted', false, false, true, false, ARRAY['ING_LAMB_SHOULDER', 'ING_LAMB_FAT', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_CARDAMOM', 'ING_GARLIC', 'ING_ONION', 'ING_PITA_BREAD', 'ING_TAHINI', 'ING_PICKLES', 'ING_PARSLEY'], ARRAY['gluten', 'sesame'], false, true, true, false, false, true, false, 1, ARRAY['street-food', 'lamb', 'rotisserie'], 95),
('LEBANESE_SHISH_TAWOOK', 'shish-tawook', 'Shish Tawook', 'Marinated chicken breast skewers grilled over charcoal, served with garlic sauce', 'Shish Tawouq', 'شيش طاووق', 'grilled_meats', 'signature', 'national', 'chicken', 'grilled', false, false, true, false, ARRAY['ING_CHICKEN_BREAST', 'ING_YOGURT', 'ING_LEMON', 'ING_GARLIC', 'ING_TOMATO_PASTE', 'ING_PAPRIKA', 'ING_SEVEN_SPICE', 'ING_OLIVE_OIL', 'ING_TOUM'], ARRAY['dairy'], true, false, true, false, false, true, false, 0, ARRAY['skewers', 'grilled', 'popular'], 95),
('LEBANESE_KAFTA_SKEWERS', 'kafta-meshwi', 'Kafta Meshwi', 'Grilled spiced lamb and beef kafta skewers with parsley and onions', 'Kafta Meshwi', 'كفتة مشوية', 'grilled_meats', 'signature', 'national', 'mixed', 'grilled', false, false, true, false, ARRAY['ING_GROUND_LAMB', 'ING_GROUND_BEEF', 'ING_ONION', 'ING_PARSLEY', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_SEA_SALT', 'ING_BLACK_PEPPER'], ARRAY[]::TEXT[], true, true, true, false, false, true, false, 1, ARRAY['skewers', 'grilled', 'iconic'], 95),
('LEBANESE_LAHM_MESHWI', 'lahm-meshwi', 'Lahm Meshwi', 'Grilled lamb cubes marinated in Lebanese spices, served with grilled vegetables', 'Lahm Meshwi', 'لحم مشوي', 'grilled_meats', 'classic', 'national', 'lamb', 'grilled', false, true, false, false, ARRAY['ING_LAMB_SHOULDER', 'ING_ONION', 'ING_BELL_PEPPER', 'ING_TOMATO', 'ING_SEVEN_SPICE', 'ING_OLIVE_OIL', 'ING_LEMON', 'ING_SEA_SALT'], ARRAY[]::TEXT[], true, true, true, false, false, true, false, 1, ARRAY['lamb', 'grilled', 'premium'], 85),
('LEBANESE_LAMB_CHOPS', 'kastaleta', 'Kastaleta', 'Grilled lamb chops marinated in garlic and herbs, served with mint yogurt', 'Kastaleta Ghanam', 'كستليتا غنم', 'grilled_meats', 'premium', 'zahle', 'lamb', 'grilled', false, true, false, false, ARRAY['ING_LAMB_CHOPS', 'ING_GARLIC', 'ING_ROSEMARY', 'ING_THYME', 'ING_OLIVE_OIL', 'ING_LEMON', 'ING_YOGURT', 'ING_MINT', 'ING_SEA_SALT'], ARRAY['dairy'], true, false, true, false, false, true, false, 0, ARRAY['premium', 'lamb-chops', 'zahle-style'], 80),
('LEBANESE_DJAJ_MESHWI', 'djaj-meshwi', 'Djaj Meshwi', 'Whole grilled chicken marinated in Lebanese seven spice and garlic', 'Djaj Meshwi', 'دجاج مشوي', 'grilled_meats', 'classic', 'national', 'chicken', 'grilled', false, false, false, false, ARRAY['ING_WHOLE_CHICKEN', 'ING_GARLIC', 'ING_SEVEN_SPICE', 'ING_PAPRIKA', 'ING_LEMON', 'ING_OLIVE_OIL', 'ING_SEA_SALT', 'ING_TOUM'], ARRAY[]::TEXT[], true, true, true, false, false, true, false, 1, ARRAY['whole-chicken', 'family-style', 'grilled'], 85),
('LEBANESE_KAFTA_POTATO', 'kafta-bil-batata', 'Kafta bil Batata', 'Baked kafta with potatoes and tomatoes in a spiced tomato sauce', 'Kafta bil Batata', 'كفتة بالبطاطا', 'grilled_meats', 'classic', 'national', 'mixed', 'baked', false, false, false, false, ARRAY['ING_GROUND_LAMB', 'ING_GROUND_BEEF', 'ING_POTATO', 'ING_TOMATO', 'ING_ONION', 'ING_PARSLEY', 'ING_TOMATO_PASTE', 'ING_SEVEN_SPICE', 'ING_OLIVE_OIL'], ARRAY[]::TEXT[], true, true, true, false, false, true, false, 1, ARRAY['casserole', 'comfort-food', 'home-style'], 80),
('LEBANESE_KAFTA_TAHINI', 'kafta-bil-tahini', 'Kafta bil Tahini', 'Baked kafta with potatoes covered in tahini sauce', 'Kafta bil Tahini', 'كفتة بالطحينة', 'grilled_meats', 'classic', 'national', 'mixed', 'baked', false, false, false, false, ARRAY['ING_GROUND_LAMB', 'ING_GROUND_BEEF', 'ING_POTATO', 'ING_ONION', 'ING_PARSLEY', 'ING_TAHINI', 'ING_LEMON', 'ING_SEVEN_SPICE'], ARRAY['sesame'], true, true, true, false, false, true, false, 0, ARRAY['casserole', 'tahini-sauce', 'comfort-food'], 75),
('LEBANESE_ARAYES', 'arayes', 'Arayes', 'Grilled pita stuffed with spiced kafta meat, crispy outside and juicy inside', 'Arayes', 'عرايس', 'grilled_meats', 'popular', 'national', 'mixed', 'grilled', true, false, true, false, ARRAY['ING_PITA_BREAD', 'ING_GROUND_LAMB', 'ING_GROUND_BEEF', 'ING_ONION', 'ING_PARSLEY', 'ING_TOMATO', 'ING_SEVEN_SPICE', 'ING_BUTTER'], ARRAY['gluten', 'dairy'], false, false, true, false, false, true, false, 1, ARRAY['street-food', 'stuffed-bread', 'grilled'], 90),

-- ============================================
-- STEWS & MAINS (10 items)
-- ============================================
('LEBANESE_MOLOKHIA', 'molokhia', 'Molokhia', 'Traditional jute leaf stew with chicken, garlic, and coriander, served over rice', 'Molokhia', 'ملوخية', 'stews_mains', 'classic', 'national', 'chicken', 'stewed', false, false, false, false, ARRAY['ING_MOLOKHIA', 'ING_CHICKEN_THIGH', 'ING_GARLIC', 'ING_CORIANDER_SEEDS', 'ING_CHICKEN_STOCK', 'ING_LEMON', 'ING_RICE', 'ING_OLIVE_OIL'], ARRAY[]::TEXT[], true, true, true, false, false, true, false, 0, ARRAY['traditional', 'comfort-food', 'green-stew'], 85),
('LEBANESE_FASOLIA', 'fasolia', 'Fasolia', 'White bean stew with lamb, tomatoes, and seven spice', 'Fasolia', 'فاصوليا', 'stews_mains', 'classic', 'national', 'lamb', 'stewed', false, false, false, false, ARRAY['ING_WHITE_BEANS', 'ING_LAMB_SHOULDER', 'ING_TOMATO', 'ING_TOMATO_PASTE', 'ING_ONION', 'ING_GARLIC', 'ING_SEVEN_SPICE', 'ING_OLIVE_OIL', 'ING_RICE'], ARRAY[]::TEXT[], true, true, true, false, false, true, false, 0, ARRAY['beans', 'comfort-food', 'home-style'], 80),
('LEBANESE_FASOLIA_BZEIT', 'fasolia-bzeit', 'Fasolia bi Zeit', 'Green beans braised in tomato and olive oil, served cold as a meatless main', 'Fasolia bi Zeit', 'فاصوليا بزيت', 'stews_mains', 'classic', 'national', 'vegan', 'stewed', true, false, false, true, ARRAY['ING_GREEN_BEANS', 'ING_TOMATO', 'ING_ONION', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_TOMATO_PASTE', 'ING_SEA_SALT'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['lenten', 'cold-dish', 'vegan'], 70),
('LEBANESE_BAMIEH', 'bamieh', 'Bamieh', 'Okra stew with lamb, tomatoes, garlic, and coriander', 'Bamieh', 'بامية', 'stews_mains', 'classic', 'national', 'lamb', 'stewed', false, false, false, false, ARRAY['ING_OKRA', 'ING_LAMB_SHOULDER', 'ING_TOMATO', 'ING_TOMATO_PASTE', 'ING_ONION', 'ING_GARLIC', 'ING_CILANTRO', 'ING_LEMON', 'ING_RICE'], ARRAY[]::TEXT[], true, true, true, false, false, true, false, 0, ARRAY['okra', 'traditional', 'comfort-food'], 75),
('LEBANESE_YAKHNIT_BATINJANE', 'yakhnit-batinjane', 'Yakhnit Batinjane', 'Eggplant and lamb stew in tomato sauce, served over rice', 'Yakhne Batinjane', 'يخنة باتنجان', 'stews_mains', 'classic', 'national', 'lamb', 'stewed', false, false, false, false, ARRAY['ING_EGGPLANT', 'ING_LAMB_SHOULDER', 'ING_TOMATO', 'ING_TOMATO_PASTE', 'ING_ONION', 'ING_GARLIC', 'ING_SEVEN_SPICE', 'ING_PINE_NUTS', 'ING_RICE'], ARRAY['tree_nuts'], true, true, false, false, false, true, false, 0, ARRAY['eggplant', 'stew', 'home-style'], 75),
('LEBANESE_LABAN_IMMO', 'laban-immo', 'Laban Immo', 'Lamb cooked in its mother''s milk - tender lamb in creamy yogurt sauce with rice', 'Laban Immo', 'لبن إمو', 'stews_mains', 'traditional', 'mount_lebanon', 'lamb', 'stewed', false, true, false, false, ARRAY['ING_LAMB_SHOULDER', 'ING_YOGURT', 'ING_EGG', 'ING_CORNSTARCH', 'ING_GARLIC', 'ING_DRIED_MINT', 'ING_RICE', 'ING_BUTTER'], ARRAY['dairy', 'egg'], true, false, true, false, false, true, false, 0, ARRAY['yogurt', 'traditional', 'douma-specialty'], 65),
('LEBANESE_SHEIKH_MAHSHI', 'sheikh-mahshi', 'Sheikh al Mahshi', 'Stuffed eggplants with spiced meat and pine nuts in tomato sauce, king of stuffed dishes', 'Sheikh al Mahshi', 'شيخ المحشي', 'stews_mains', 'premium', 'national', 'mixed', 'baked', false, true, false, false, ARRAY['ING_EGGPLANT', 'ING_GROUND_LAMB', 'ING_GROUND_BEEF', 'ING_PINE_NUTS', 'ING_ONION', 'ING_TOMATO', 'ING_TOMATO_PASTE', 'ING_SEVEN_SPICE', 'ING_POMEGRANATE_MOLASSES'], ARRAY['tree_nuts'], true, true, false, false, false, true, false, 0, ARRAY['stuffed', 'premium', 'eggplant'], 80),
('LEBANESE_FATTIT_MAKDOUS', 'fattit-makdous', 'Fattit Makdous', 'Stuffed baby eggplants in olive oil with walnuts and red pepper', 'Makdous', 'مكدوس', 'stews_mains', 'traditional', 'national', 'vegan', 'raw', true, false, false, true, ARRAY['ING_BABY_EGGPLANT', 'ING_WALNUTS', 'ING_RED_PEPPER', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_SEA_SALT'], ARRAY['tree_nuts'], true, true, false, true, true, true, true, 1, ARRAY['pickled', 'preserved', 'breakfast'], 75),
('LEBANESE_KOUSSA_ABLAMA', 'koussa-ablama', 'Koussa Ablama', 'Stuffed zucchini in yogurt sauce, a Damascus-influenced dish', 'Koussa Ablama', 'كوسا أبلما', 'stews_mains', 'traditional', 'north_lebanon', 'lamb', 'stewed', false, false, false, false, ARRAY['ING_ZUCCHINI', 'ING_GROUND_LAMB', 'ING_RICE', 'ING_YOGURT', 'ING_EGG', 'ING_GARLIC', 'ING_DRIED_MINT', 'ING_SEVEN_SPICE'], ARRAY['dairy', 'egg'], true, false, true, false, false, true, false, 0, ARRAY['stuffed', 'yogurt-sauce', 'damascus-style'], 60),
('LEBANESE_SAYADEIH', 'sayadieh', 'Sayadieh', 'Famous Sidon fish dish - spiced fish on caramelized onion rice with tahini sauce', 'Sayadieh', 'صيادية', 'stews_mains', 'signature', 'sidon', 'fish', 'fried', false, true, false, true, ARRAY['ING_WHITE_FISH', 'ING_RICE', 'ING_ONION', 'ING_CUMIN', 'ING_SAFFRON', 'ING_PINE_NUTS', 'ING_TAHINI', 'ING_LEMON', 'ING_OLIVE_OIL'], ARRAY['fish', 'sesame', 'tree_nuts'], true, true, false, false, false, true, true, 0, ARRAY['sidon-specialty', 'fish', 'signature'], 85),

-- ============================================
-- RICE & GRAINS (8 items)
-- ============================================
('LEBANESE_MUJADARA', 'mujadara', 'Mujadara', 'Lentils and rice topped with crispy caramelized onions, served with yogurt', 'Mujadara', 'مجدرة', 'rice_grains', 'signature', 'national', 'vegan', 'stewed', false, false, false, true, ARRAY['ING_LENTILS', 'ING_RICE', 'ING_ONION', 'ING_OLIVE_OIL', 'ING_CUMIN', 'ING_SEA_SALT'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['comfort-food', 'lentils', 'budget-friendly', 'iconic'], 95),
('LEBANESE_RIZ_SHARIEH', 'riz-sharieh', 'Riz bi Sha''rieh', 'Lebanese rice pilaf with toasted vermicelli noodles', 'Riz bi Sha''rieh', 'رز بالشعيرية', 'rice_grains', 'classic', 'national', 'vegan', 'steamed', false, false, false, true, ARRAY['ING_RICE', 'ING_VERMICELLI', 'ING_BUTTER', 'ING_SEA_SALT'], ARRAY['gluten', 'dairy'], false, false, true, false, true, true, true, 0, ARRAY['side-dish', 'staple', 'essential'], 90),
('LEBANESE_RIZ_LAHME', 'riz-lahme', 'Riz bi Lahme', 'Spiced rice with lamb, ground beef, and toasted nuts', 'Riz bi Lahme', 'رز باللحمة', 'rice_grains', 'classic', 'national', 'mixed', 'stewed', false, true, false, false, ARRAY['ING_RICE', 'ING_GROUND_LAMB', 'ING_GROUND_BEEF', 'ING_PINE_NUTS', 'ING_ALMONDS', 'ING_ONION', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_BUTTER'], ARRAY['tree_nuts', 'dairy'], true, false, false, false, false, true, false, 0, ARRAY['festive', 'meaty', 'celebratory'], 85),
('LEBANESE_FREEKEH', 'freekeh', 'Freekeh', 'Roasted green wheat with chicken, an ancient grain dish', 'Freekeh', 'فريكة', 'rice_grains', 'traditional', 'north_lebanon', 'chicken', 'stewed', false, true, false, false, ARRAY['ING_FREEKEH', 'ING_CHICKEN_THIGH', 'ING_ONION', 'ING_CHICKEN_STOCK', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_PINE_NUTS', 'ING_BUTTER'], ARRAY['gluten', 'tree_nuts', 'dairy'], false, false, false, false, false, true, false, 0, ARRAY['ancient-grain', 'healthy', 'traditional'], 70),
('LEBANESE_BURGHUL_BANADOURA', 'burghul-banadoura', 'Burghul bi Banadoura', 'Bulgur wheat cooked with tomatoes, onions, and spices', 'Burghul bi Banadoura', 'برغل بالبندورة', 'rice_grains', 'classic', 'national', 'vegan', 'stewed', false, false, false, true, ARRAY['ING_BULGUR', 'ING_TOMATO', 'ING_ONION', 'ING_GARLIC', 'ING_TOMATO_PASTE', 'ING_OLIVE_OIL', 'ING_SEVEN_SPICE', 'ING_SEA_SALT'], ARRAY['gluten'], false, true, true, true, true, true, true, 0, ARRAY['bulgur', 'tomato', 'simple'], 70),
('LEBANESE_HASHWIT_DJAJ', 'hashwit-djaj', 'Hashwit Djaj', 'Spiced rice stuffing with ground meat and nuts, served inside roast chicken', 'Hashwit Djaj', 'حشوة دجاج', 'rice_grains', 'festive', 'national', 'mixed', 'roasted', false, true, false, false, ARRAY['ING_RICE', 'ING_WHOLE_CHICKEN', 'ING_GROUND_LAMB', 'ING_PINE_NUTS', 'ING_ALMONDS', 'ING_ONION', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_BUTTER'], ARRAY['tree_nuts', 'dairy'], true, false, false, false, false, true, false, 0, ARRAY['festive', 'stuffed-chicken', 'sunday-lunch'], 80),
('LEBANESE_KESHEK', 'keshek', 'Keshek', 'Fermented bulgur and yogurt porridge, a traditional winter comfort dish', 'Keshek', 'كشك', 'rice_grains', 'traditional', 'mount_lebanon', 'vegetarian', 'stewed', false, false, false, false, ARRAY['ING_KESHEK', 'ING_ONION', 'ING_GARLIC', 'ING_BUTTER', 'ING_SEA_SALT', 'ING_DRIED_MINT'], ARRAY['gluten', 'dairy'], false, false, true, false, true, true, true, 0, ARRAY['fermented', 'winter', 'traditional', 'porridge'], 55),
('LEBANESE_MANSAF', 'mansaf-lebanese', 'Mansaf', 'Festive lamb cooked in jameed (dried yogurt) sauce, served over rice with flatbread', 'Mansaf', 'منسف', 'rice_grains', 'festive', 'bekaa_valley', 'lamb', 'stewed', false, true, false, false, ARRAY['ING_LAMB_SHOULDER', 'ING_JAMEED', 'ING_RICE', 'ING_PINE_NUTS', 'ING_ALMONDS', 'ING_SHRAK_BREAD', 'ING_TURMERIC', 'ING_BUTTER'], ARRAY['dairy', 'tree_nuts', 'gluten'], false, false, false, false, false, true, false, 0, ARRAY['bedouin', 'festive', 'lamb', 'celebration'], 70),

-- ============================================
-- STUFFED DISHES (8 items)
-- ============================================
('LEBANESE_WARAK_ENAB', 'warak-enab', 'Warak Enab', 'Grape leaves stuffed with rice, tomatoes, and herbs, cooked in lemon juice', 'Warak Enab', 'ورق عنب', 'stuffed_dishes', 'signature', 'national', 'vegan', 'stewed', true, false, false, true, ARRAY['ING_GRAPE_LEAVES', 'ING_RICE', 'ING_TOMATO', 'ING_ONION', 'ING_PARSLEY', 'ING_MINT', 'ING_LEMON', 'ING_OLIVE_OIL', 'ING_SEVEN_SPICE'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['stuffed', 'lenten', 'iconic', 'cold-mezze'], 95),
('LEBANESE_WARAK_ENAB_MEAT', 'warak-enab-lahme', 'Warak Enab bi Lahme', 'Grape leaves stuffed with rice, lamb, and pine nuts, served with yogurt', 'Warak Enab bi Lahme', 'ورق عنب باللحمة', 'stuffed_dishes', 'classic', 'national', 'lamb', 'stewed', false, true, false, false, ARRAY['ING_GRAPE_LEAVES', 'ING_RICE', 'ING_GROUND_LAMB', 'ING_ONION', 'ING_PINE_NUTS', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_YOGURT', 'ING_LEMON'], ARRAY['tree_nuts', 'dairy'], true, false, false, false, false, true, false, 0, ARRAY['stuffed', 'meat', 'festive'], 85),
('LEBANESE_KOUSA_MAHSHI', 'kousa-mahshi', 'Kousa Mahshi', 'Zucchini stuffed with rice and spiced lamb, cooked in tomato broth', 'Kousa Mahshi', 'كوسا محشي', 'stuffed_dishes', 'signature', 'national', 'lamb', 'stewed', false, false, false, false, ARRAY['ING_ZUCCHINI', 'ING_RICE', 'ING_GROUND_LAMB', 'ING_ONION', 'ING_TOMATO', 'ING_TOMATO_PASTE', 'ING_SEVEN_SPICE', 'ING_CINNAMON', 'ING_MINT', 'ING_LEMON'], ARRAY[]::TEXT[], true, true, true, false, false, true, false, 0, ARRAY['stuffed', 'zucchini', 'home-cooking'], 90),
('LEBANESE_BATINJANE_MAHSHI', 'batinjane-mahshi', 'Batinjane Mahshi', 'Baby eggplants stuffed with rice and lamb in tomato sauce', 'Batinjane Mahshi', 'باتنجان محشي', 'stuffed_dishes', 'classic', 'national', 'lamb', 'stewed', false, false, false, false, ARRAY['ING_BABY_EGGPLANT', 'ING_RICE', 'ING_GROUND_LAMB', 'ING_ONION', 'ING_TOMATO', 'ING_TOMATO_PASTE', 'ING_PINE_NUTS', 'ING_SEVEN_SPICE', 'ING_GARLIC'], ARRAY['tree_nuts'], true, true, false, false, false, true, false, 0, ARRAY['stuffed', 'eggplant', 'traditional'], 80),
('LEBANESE_MALFUF_MAHSHI', 'malfuf-mahshi', 'Malfuf Mahshi', 'Cabbage leaves stuffed with rice and lamb, cooked in garlic lemon broth', 'Malfuf Mahshi', 'ملفوف محشي', 'stuffed_dishes', 'classic', 'national', 'lamb', 'stewed', false, false, false, false, ARRAY['ING_CABBAGE', 'ING_RICE', 'ING_GROUND_LAMB', 'ING_ONION', 'ING_GARLIC', 'ING_DRIED_MINT', 'ING_LEMON', 'ING_SEVEN_SPICE'], ARRAY[]::TEXT[], true, true, true, false, false, true, false, 0, ARRAY['stuffed', 'cabbage', 'comfort-food'], 75),
('LEBANESE_SILQ_MAHSHI', 'silq-mahshi', 'Silq Mahshi', 'Swiss chard leaves stuffed with rice, chickpeas, and lemon', 'Silq Mahshi', 'سلق محشي', 'stuffed_dishes', 'traditional', 'mount_lebanon', 'vegan', 'stewed', true, false, false, true, ARRAY['ING_SWISS_CHARD', 'ING_RICE', 'ING_CHICKPEAS', 'ING_ONION', 'ING_LEMON', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_SEVEN_SPICE'], ARRAY[]::TEXT[], true, true, true, true, true, true, true, 0, ARRAY['stuffed', 'lenten', 'vegan', 'swiss-chard'], 60),
('LEBANESE_FILFIL_MAHSHI', 'filfil-mahshi', 'Filfil Mahshi', 'Bell peppers stuffed with spiced rice and lamb', 'Filfil Mahshi', 'فلفل محشي', 'stuffed_dishes', 'classic', 'national', 'lamb', 'baked', false, false, false, false, ARRAY['ING_BELL_PEPPER', 'ING_RICE', 'ING_GROUND_LAMB', 'ING_ONION', 'ING_TOMATO', 'ING_TOMATO_PASTE', 'ING_PINE_NUTS', 'ING_SEVEN_SPICE', 'ING_PARSLEY'], ARRAY['tree_nuts'], true, true, false, false, false, true, false, 0, ARRAY['stuffed', 'peppers', 'colorful'], 70),
('LEBANESE_ABLAMA', 'ablama', 'Ablama', 'Assorted vegetables stuffed with rice and lamb in yogurt sauce', 'Ablama', 'أبلما', 'stuffed_dishes', 'festive', 'national', 'lamb', 'stewed', false, true, false, false, ARRAY['ING_ZUCCHINI', 'ING_BABY_EGGPLANT', 'ING_BELL_PEPPER', 'ING_RICE', 'ING_GROUND_LAMB', 'ING_YOGURT', 'ING_EGG', 'ING_GARLIC', 'ING_DRIED_MINT'], ARRAY['dairy', 'egg'], true, false, true, false, false, true, false, 0, ARRAY['mixed-stuffed', 'yogurt-sauce', 'festive'], 65),

-- ============================================
-- BREADS & PASTRIES (10 items)
-- ============================================
('LEBANESE_MANAKISH_ZAATAR', 'manakish-zaatar', 'Manakish Zaatar', 'Flatbread topped with za''atar mixed with olive oil, the quintessential Lebanese breakfast', 'Manakish Zaatar', 'مناقيش زعتر', 'breads_pastries', 'signature', 'national', 'vegan', 'baked', false, false, true, true, ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_ZAATAR', 'ING_OLIVE_OIL', 'ING_SEA_SALT', 'ING_SUGAR'], ARRAY['gluten'], false, true, true, true, true, true, true, 0, ARRAY['breakfast', 'iconic', 'street-food', 'zaatar'], 100),
('LEBANESE_MANAKISH_CHEESE', 'manakish-jebneh', 'Manakish Jebneh', 'Flatbread topped with melted akawi cheese', 'Manakish Jebneh', 'مناقيش جبنة', 'breads_pastries', 'signature', 'national', 'vegetarian', 'baked', false, false, true, false, ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_AKAWI_CHEESE', 'ING_OLIVE_OIL', 'ING_SEA_SALT'], ARRAY['gluten', 'dairy'], false, false, true, false, true, true, true, 0, ARRAY['breakfast', 'cheese', 'street-food'], 95),
('LEBANESE_MANAKISH_LAHM_BAAJIN', 'lahm-baajin', 'Lahm bi Ajin', 'Lebanese meat pizza with spiced lamb, tomatoes, and pine nuts', 'Lahm bi Ajin', 'لحم بعجين', 'breads_pastries', 'signature', 'national', 'lamb', 'baked', false, false, true, false, ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_GROUND_LAMB', 'ING_TOMATO', 'ING_ONION', 'ING_PINE_NUTS', 'ING_POMEGRANATE_MOLASSES', 'ING_SEVEN_SPICE'], ARRAY['gluten', 'tree_nuts'], false, true, false, false, false, true, false, 1, ARRAY['meat-pizza', 'street-food', 'popular'], 95),
('LEBANESE_FATAYER_SPINACH', 'fatayer-spinach', 'Fatayer bi Sabanekh', 'Triangular spinach pies with sumac and lemon', 'Fatayer bi Sabanekh', 'فطاير بالسبانخ', 'breads_pastries', 'classic', 'national', 'vegan', 'baked', true, false, true, true, ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_SPINACH', 'ING_ONION', 'ING_SUMAC', 'ING_LEMON', 'ING_OLIVE_OIL', 'ING_PINE_NUTS'], ARRAY['gluten', 'tree_nuts'], false, true, false, true, true, true, true, 0, ARRAY['spinach', 'triangular', 'lenten'], 90),
('LEBANESE_FATAYER_CHEESE', 'fatayer-cheese', 'Fatayer bi Jebneh', 'Cheese-filled pastry triangles with akawi or halloumi', 'Fatayer bi Jebneh', 'فطاير بالجبنة', 'breads_pastries', 'classic', 'national', 'vegetarian', 'baked', true, false, true, false, ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_AKAWI_CHEESE', 'ING_HALLOUMI', 'ING_EGG', 'ING_NIGELLA_SEEDS'], ARRAY['gluten', 'dairy', 'egg'], false, false, true, false, true, true, true, 0, ARRAY['cheese', 'triangular', 'snack'], 85),
('LEBANESE_SFIHA', 'sfiha', 'Sfiha', 'Open-faced meat pies from Baalbek with spiced lamb and pine nuts', 'Sfiha', 'صفيحة', 'breads_pastries', 'traditional', 'bekaa_valley', 'lamb', 'baked', true, false, true, false, ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_GROUND_LAMB', 'ING_ONION', 'ING_TOMATO', 'ING_PINE_NUTS', 'ING_POMEGRANATE_MOLASSES', 'ING_SEVEN_SPICE', 'ING_YOGURT'], ARRAY['gluten', 'tree_nuts', 'dairy'], false, false, false, false, false, true, false, 0, ARRAY['baalbek-specialty', 'open-faced', 'meat-pie'], 80),
('LEBANESE_SAMBOUSEK_MEAT', 'sambousek-lahme', 'Sambousek bi Lahme', 'Fried half-moon pastries filled with spiced lamb and pine nuts', 'Sambousek bi Lahme', 'سمبوسك باللحمة', 'breads_pastries', 'classic', 'national', 'lamb', 'fried', true, true, true, false, ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_GROUND_LAMB', 'ING_ONION', 'ING_PINE_NUTS', 'ING_SEVEN_SPICE', 'ING_VEGETABLE_OIL'], ARRAY['gluten', 'dairy', 'tree_nuts'], false, false, false, false, false, true, false, 0, ARRAY['fried', 'appetizer', 'festive'], 85),
('LEBANESE_SAMBOUSEK_CHEESE', 'sambousek-jebneh', 'Sambousek bi Jebneh', 'Fried half-moon pastries filled with halloumi and mint', 'Sambousek bi Jebneh', 'سمبوسك بالجبنة', 'breads_pastries', 'classic', 'national', 'vegetarian', 'fried', true, true, true, false, ARRAY['ING_FLOUR', 'ING_BUTTER', 'ING_HALLOUMI', 'ING_AKAWI_CHEESE', 'ING_MINT', 'ING_VEGETABLE_OIL'], ARRAY['gluten', 'dairy'], false, false, true, false, true, true, true, 0, ARRAY['fried', 'cheese', 'appetizer'], 85),
('LEBANESE_KAAK', 'kaak', 'Kaak', 'Sesame-covered bread rings sold by street vendors, often with cheese or za''atar', 'Kaak', 'كعك', 'breads_pastries', 'street_food', 'beirut', 'vegan', 'baked', false, false, true, true, ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_SESAME_SEEDS', 'ING_MAHLAB', 'ING_ANISE_SEEDS', 'ING_SUGAR', 'ING_SEA_SALT'], ARRAY['gluten', 'sesame'], false, true, true, true, true, true, true, 0, ARRAY['street-food', 'sesame', 'breakfast', 'iconic'], 90),
('LEBANESE_RAKAKAT', 'rakakat', 'Rakakat', 'Crispy phyllo rolls filled with cheese or meat', 'Rakakat', 'رقاقات', 'breads_pastries', 'classic', 'national', 'vegetarian', 'fried', true, true, false, false, ARRAY['ING_PHYLLO', 'ING_HALLOUMI', 'ING_AKAWI_CHEESE', 'ING_PARSLEY', 'ING_BUTTER', 'ING_VEGETABLE_OIL'], ARRAY['gluten', 'dairy'], false, false, true, false, true, true, true, 0, ARRAY['phyllo', 'crispy', 'appetizer'], 75),

-- ============================================
-- SEAFOOD (8 items)
-- ============================================
('LEBANESE_SAMKE_HARRA', 'samke-harra', 'Samke Harra', 'Spicy baked fish in tahini sauce with chili, garlic, and cilantro from Tripoli', 'Samke Harra', 'سمكة حرة', 'seafood', 'signature', 'tripoli', 'fish', 'baked', false, true, false, true, ARRAY['ING_WHITE_FISH', 'ING_TAHINI', 'ING_GARLIC', 'ING_CILANTRO', 'ING_CHILI_FLAKES', 'ING_WALNUTS', 'ING_LEMON', 'ING_OLIVE_OIL', 'ING_PINE_NUTS'], ARRAY['fish', 'sesame', 'tree_nuts'], true, true, false, false, false, true, true, 3, ARRAY['spicy', 'tripoli-specialty', 'tahini', 'signature'], 90),
('LEBANESE_SAMAK_MESHWI', 'samak-meshwi', 'Samak Meshwi', 'Whole grilled fish with lemon, garlic, and herbs', 'Samak Meshwi', 'سمك مشوي', 'seafood', 'classic', 'sidon', 'fish', 'grilled', false, false, false, true, ARRAY['ING_SEA_BREAM', 'ING_LEMON', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_PARSLEY', 'ING_SEA_SALT'], ARRAY['fish'], true, true, true, false, false, true, true, 0, ARRAY['grilled', 'simple', 'coastal'], 85),
('LEBANESE_SAMAK_MAKLI', 'samak-makli', 'Samak Makli', 'Crispy fried fish served with tahini sauce and lemon', 'Samak Makli', 'سمك مقلي', 'seafood', 'classic', 'national', 'fish', 'fried', false, false, true, true, ARRAY['ING_WHITE_FISH', 'ING_FLOUR', 'ING_CUMIN', 'ING_VEGETABLE_OIL', 'ING_TAHINI', 'ING_LEMON', 'ING_GARLIC'], ARRAY['fish', 'gluten', 'sesame'], false, true, true, false, false, true, true, 0, ARRAY['fried', 'crispy', 'street-food'], 80),
('LEBANESE_CALAMARI_MAKLI', 'calamari-makli', 'Calamari Makli', 'Crispy fried calamari rings served with lemon and garlic sauce', 'Habar Makli', 'حبار مقلي', 'seafood', 'popular', 'beirut', 'seafood', 'fried', true, false, false, true, ARRAY['ING_SQUID', 'ING_FLOUR', 'ING_CORNSTARCH', 'ING_VEGETABLE_OIL', 'ING_LEMON', 'ING_TOUM'], ARRAY['mollusk', 'gluten'], false, true, true, false, false, true, true, 0, ARRAY['fried', 'calamari', 'appetizer'], 85),
('LEBANESE_SHRIMP_PROVENCAL', 'kreides-provencal', 'Kreides Provencal', 'Sauteed shrimp in garlic butter, tomato, and white wine sauce', 'قريدس بروفنسال', 'قريدس بروفنسال', 'seafood', 'popular', 'beirut', 'seafood', 'stewed', false, false, false, true, ARRAY['ING_SHRIMP', 'ING_GARLIC', 'ING_BUTTER', 'ING_TOMATO', 'ING_WHITE_WINE', 'ING_PARSLEY', 'ING_CHILI_FLAKES'], ARRAY['shellfish', 'dairy'], true, false, true, false, false, false, true, 1, ARRAY['shrimp', 'french-influenced', 'garlic'], 80),
('LEBANESE_SHRIMP_TAGINE', 'kreides-tagine', 'Kreides bi Tahini', 'Shrimp baked in tahini sauce with pine nuts', 'قريدس بالطحينة', 'قريدس بالطحينة', 'seafood', 'classic', 'sidon', 'seafood', 'baked', false, false, false, true, ARRAY['ING_SHRIMP', 'ING_TAHINI', 'ING_GARLIC', 'ING_LEMON', 'ING_PINE_NUTS', 'ING_PARSLEY', 'ING_OLIVE_OIL'], ARRAY['shellfish', 'sesame', 'tree_nuts'], true, true, false, false, false, true, true, 0, ARRAY['tahini', 'shrimp', 'baked'], 75),
('LEBANESE_OCTOPUS_GRILLED', 'akhtabout-meshwi', 'Akhtabout Meshwi', 'Grilled octopus with lemon, garlic, and olive oil', 'أخطبوط مشوي', 'أخطبوط مشوي', 'seafood', 'premium', 'byblos', 'seafood', 'grilled', true, false, false, true, ARRAY['ING_OCTOPUS', 'ING_LEMON', 'ING_GARLIC', 'ING_OLIVE_OIL', 'ING_PARSLEY', 'ING_CHILI_FLAKES'], ARRAY['mollusk'], true, true, true, false, false, true, true, 1, ARRAY['grilled', 'octopus', 'premium'], 70),
('LEBANESE_SULTAN_IBRAHIM', 'sultan-ibrahim', 'Sultan Ibrahim', 'Fried red mullet fish, a Lebanese coastal favorite', 'سلطان إبراهيم', 'سلطان إبراهيم', 'seafood', 'traditional', 'sidon', 'fish', 'fried', false, false, true, true, ARRAY['ING_RED_MULLET', 'ING_FLOUR', 'ING_VEGETABLE_OIL', 'ING_LEMON', 'ING_SEA_SALT'], ARRAY['fish', 'gluten'], false, true, true, false, false, true, true, 0, ARRAY['fried', 'traditional', 'red-mullet'], 75),

-- ============================================
-- DESSERTS (12 items)
-- ============================================
('LEBANESE_KNAFEH', 'knafeh', 'Knafeh', 'Crispy shredded phyllo pastry filled with sweet cheese, soaked in rose water syrup', 'Knafeh', 'كنافة', 'desserts', 'signature', 'tripoli', 'vegetarian', 'baked', false, true, true, false, ARRAY['ING_KNAFEH_DOUGH', 'ING_AKAWI_CHEESE', 'ING_MOZZARELLA', 'ING_BUTTER', 'ING_SUGAR', 'ING_ROSE_WATER', 'ING_ORANGE_BLOSSOM', 'ING_PISTACHIOS'], ARRAY['gluten', 'dairy', 'tree_nuts'], false, false, false, false, true, true, true, 0, ARRAY['signature', 'cheese', 'syrup', 'iconic'], 100),
('LEBANESE_BAKLAVA', 'baklava-lebanese', 'Baklava', 'Layered phyllo pastry with pistachio or walnut filling, drenched in rose water syrup', 'Baklawa', 'بقلاوة', 'desserts', 'signature', 'tripoli', 'vegetarian', 'baked', false, true, false, false, ARRAY['ING_PHYLLO', 'ING_PISTACHIOS', 'ING_WALNUTS', 'ING_BUTTER', 'ING_SUGAR', 'ING_ROSE_WATER', 'ING_ORANGE_BLOSSOM', 'ING_LEMON'], ARRAY['gluten', 'dairy', 'tree_nuts'], false, false, false, false, true, true, true, 0, ARRAY['classic', 'phyllo', 'nuts', 'festive'], 95),
('LEBANESE_MAAMOUL', 'maamoul', 'Maamoul', 'Shortbread cookies filled with dates, walnuts, or pistachios, dusted with powdered sugar', 'Maamoul', 'معمول', 'desserts', 'festive', 'national', 'vegetarian', 'baked', false, true, false, false, ARRAY['ING_SEMOLINA', 'ING_FLOUR', 'ING_BUTTER', 'ING_DATES', 'ING_WALNUTS', 'ING_PISTACHIOS', 'ING_ROSE_WATER', 'ING_MAHLAB', 'ING_POWDERED_SUGAR'], ARRAY['gluten', 'dairy', 'tree_nuts'], false, false, false, false, true, true, true, 0, ARRAY['easter', 'eid', 'cookies', 'festive'], 90),
('LEBANESE_NAMOURA', 'namoura', 'Namoura', 'Semolina cake soaked in orange blossom syrup, topped with almonds', 'Namoura', 'نمورة', 'desserts', 'classic', 'national', 'vegetarian', 'baked', false, false, false, false, ARRAY['ING_SEMOLINA', 'ING_YOGURT', 'ING_SUGAR', 'ING_BUTTER', 'ING_BAKING_POWDER', 'ING_ORANGE_BLOSSOM', 'ING_TAHINI', 'ING_ALMONDS'], ARRAY['gluten', 'dairy', 'sesame', 'tree_nuts'], false, false, false, false, true, true, true, 0, ARRAY['semolina', 'syrup-soaked', 'simple'], 85),
('LEBANESE_HALAWET_JIBN', 'halawet-el-jibn', 'Halawet el Jibn', 'Sweet cheese rolls filled with clotted cream, topped with pistachios and rose syrup', 'Halawet el Jibn', 'حلاوة الجبن', 'desserts', 'signature', 'homs', 'vegetarian', 'raw', false, true, false, false, ARRAY['ING_MOZZARELLA', 'ING_SEMOLINA', 'ING_ASHTA', 'ING_SUGAR', 'ING_ROSE_WATER', 'ING_PISTACHIOS'], ARRAY['dairy', 'gluten', 'tree_nuts'], false, false, false, false, true, true, true, 0, ARRAY['cheese', 'cream', 'delicate', 'premium'], 85),
('LEBANESE_ATAYEF', 'atayef', 'Atayef', 'Stuffed pancakes with cream or nuts, fried and soaked in syrup', 'Atayef', 'قطايف', 'desserts', 'festive', 'national', 'vegetarian', 'fried', false, true, true, false, ARRAY['ING_FLOUR', 'ING_YEAST', 'ING_ASHTA', 'ING_WALNUTS', 'ING_SUGAR', 'ING_ROSE_WATER', 'ING_ORANGE_BLOSSOM', 'ING_VEGETABLE_OIL'], ARRAY['gluten', 'dairy', 'tree_nuts'], false, false, false, false, true, true, true, 0, ARRAY['ramadan', 'pancakes', 'stuffed'], 85),
('LEBANESE_ASHTA_CREAM', 'ashta', 'Ashta', 'Lebanese clotted cream topped with pistachios and honey', 'Ashta', 'قشطة', 'desserts', 'classic', 'national', 'vegetarian', 'raw', false, false, false, false, ARRAY['ING_ASHTA', 'ING_PISTACHIOS', 'ING_HONEY', 'ING_ROSE_WATER'], ARRAY['dairy', 'tree_nuts'], true, false, false, false, true, true, true, 0, ARRAY['cream', 'simple', 'base-dessert'], 75),
('LEBANESE_MOGHLI', 'moghli', 'Moghli', 'Spiced rice pudding with caraway and anise, traditionally served for new births', 'Moghli', 'مغلي', 'desserts', 'festive', 'national', 'vegan', 'stewed', false, true, false, true, ARRAY['ING_RICE_FLOUR', 'ING_SUGAR', 'ING_CARAWAY', 'ING_ANISE_SEEDS', 'ING_CINNAMON', 'ING_WALNUTS', 'ING_ALMONDS', 'ING_PISTACHIOS', 'ING_COCONUT'], ARRAY['tree_nuts'], true, true, false, true, true, true, true, 0, ARRAY['birth-celebration', 'spiced', 'pudding'], 70),
('LEBANESE_RIZ_BHALIB', 'riz-bhalib', 'Riz bi Haleeb', 'Lebanese rice pudding with rose water and orange blossom', 'Riz bi Haleeb', 'رز بحليب', 'desserts', 'classic', 'national', 'vegetarian', 'stewed', false, false, false, false, ARRAY['ING_RICE', 'ING_MILK', 'ING_SUGAR', 'ING_ROSE_WATER', 'ING_ORANGE_BLOSSOM', 'ING_PISTACHIOS', 'ING_CINNAMON'], ARRAY['dairy', 'tree_nuts'], true, false, false, false, true, true, true, 0, ARRAY['rice-pudding', 'comfort', 'classic'], 80),
('LEBANESE_SFOUF', 'sfouf', 'Sfouf', 'Turmeric-spiced semolina cake, golden yellow and moist', 'Sfouf', 'صفوف', 'desserts', 'traditional', 'national', 'vegan', 'baked', false, false, false, true, ARRAY['ING_SEMOLINA', 'ING_FLOUR', 'ING_SUGAR', 'ING_TURMERIC', 'ING_TAHINI', 'ING_VEGETABLE_OIL', 'ING_BAKING_POWDER', 'ING_PINE_NUTS'], ARRAY['gluten', 'sesame', 'tree_nuts'], false, true, false, true, true, true, true, 0, ARRAY['turmeric', 'vegan', 'golden'], 70),
('LEBANESE_KARABIJ', 'karabij', 'Karabij Halab', 'Semolina cookies filled with pistachios, served with natef (marshmallow cream)', 'Karabij Halab', 'كرابيج حلب', 'desserts', 'traditional', 'north_lebanon', 'vegetarian', 'baked', false, true, false, false, ARRAY['ING_SEMOLINA', 'ING_FLOUR', 'ING_BUTTER', 'ING_PISTACHIOS', 'ING_NATEF', 'ING_ROSE_WATER', 'ING_SUGAR'], ARRAY['gluten', 'dairy', 'tree_nuts', 'egg'], false, false, false, false, true, true, true, 0, ARRAY['aleppo-style', 'cookies', 'natef'], 65),
('LEBANESE_ZNOUD_ELSIT', 'znoud-elsit', 'Znoud el Sit', 'Lady''s upper arms - crispy phyllo rolls filled with cream, fried and soaked in syrup', 'Znoud el Sit', 'زنود الست', 'desserts', 'classic', 'national', 'vegetarian', 'fried', false, false, true, false, ARRAY['ING_PHYLLO', 'ING_ASHTA', 'ING_BUTTER', 'ING_VEGETABLE_OIL', 'ING_SUGAR', 'ING_ROSE_WATER', 'ING_LEMON', 'ING_PISTACHIOS'], ARRAY['gluten', 'dairy', 'tree_nuts'], false, false, false, false, true, true, true, 0, ARRAY['fried', 'cream-filled', 'crispy'], 80)

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  arabic_name = EXCLUDED.arabic_name,
  arabic_script = EXCLUDED.arabic_script,
  category = EXCLUDED.category,
  status = EXCLUDED.status,
  region = EXCLUDED.region,
  protein_type = EXCLUDED.protein_type,
  cooking_method = EXCLUDED.cooking_method,
  is_mezze = EXCLUDED.is_mezze,
  is_festive = EXCLUDED.is_festive,
  is_street_food = EXCLUDED.is_street_food,
  is_lenten = EXCLUDED.is_lenten,
  ingredient_ids = EXCLUDED.ingredient_ids,
  allergens = EXCLUDED.allergens,
  is_gluten_free = EXCLUDED.is_gluten_free,
  is_dairy_free = EXCLUDED.is_dairy_free,
  is_nut_free = EXCLUDED.is_nut_free,
  is_vegan = EXCLUDED.is_vegan,
  is_vegetarian = EXCLUDED.is_vegetarian,
  is_halal = EXCLUDED.is_halal,
  is_pescatarian = EXCLUDED.is_pescatarian,
  spice_level = EXCLUDED.spice_level,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  updated_at = NOW();

-- ============================================
-- 84 Lebanese dishes imported
-- Next: Run 03-lebanese-product-ingredients.sql
-- ============================================
