-- Belgian New Ingredients
-- Generated by inventory-checker v2.3
-- Date: 2025-12-25
-- GUDBRO Database Standards v1.7
-- NOTE: 7 new Belgian-specific ingredients

INSERT INTO ingredients (id, name, slug, category) VALUES
('ING_BELGIAN_BEER', 'Belgian Beer', 'belgian-beer', 'beers'),
('ING_BELGIAN_CHOCOLATE', 'Belgian Chocolate', 'belgian-chocolate', 'chocolate'),
('ING_GREY_SHRIMP', 'Grey Shrimp', 'grey-shrimp', 'seafood'),
('ING_GUEUZE_BEER', 'Gueuze Lambic Beer', 'gueuze-beer', 'beers'),
('ING_GUM_ARABIC', 'Gum Arabic', 'gum-arabic', 'other'),
('ING_SIROP_LIEGE', 'Liège Syrup', 'liege-syrup', 'sweeteners'),
('ING_WHITE_ASPARAGUS', 'White Asparagus', 'white-asparagus', 'vegetables')
ON CONFLICT (id) DO NOTHING;
