-- SANDWICHES Batch 5
-- Items: 41 to 50 of 50
-- Generated: 2025-12-15T12:52:44.859Z

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-bufala-crudo-zucchine', 'piadina-bufala-crudo-zucchine', '{"en":"Buffalo Mozzarella, Prosciutto & Grilled Zucchini Piadina","it":"Piadina Bufala, Crudo e Zucchine Grigliate","vi":"Piadina Mozzarella Trâu, Prosciutto và Bí Nướng"}'::jsonb, '{"en":"Gourmet piadina with DOP buffalo mozzarella, prosciutto crudo, grilled zucchini, tomato, and arugula","it":"Piadina gourmet con mozzarella di bufala DOP, prosciutto crudo, zucchine grigliate, pomodoro e rucola","vi":"Piadina cao cấp với mozzarella trâu DOP, prosciutto, bí nướng, cà chua và arugula"}'::jsonb, NULL, 'modern', 'italian', '{"piadina","gourmet","bufala","DOP","modern","premium"}', 'piadina', false, true, '{"prosciutto_crudo"}', '{"buffalo_mozzarella"}', '{"grilled_zucchini","tomato","arugula"}', '{"olive_oil"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["prosecco","white_wine"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":560,"protein_g":28,"carbs_g":48,"fat_g":28,"fiber_g":3}'::jsonb, NULL, '{}', 88, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-tacchino-brie-tartufo', 'piadina-tacchino-brie-tartufo', '{"en":"Turkey, Brie & Truffle Cream Piadina","it":"Piadina Tacchino, Brie e Crema al Tartufo","vi":"Piadina Gà Tây, Brie và Kem Nấm Truffle"}'::jsonb, '{"en":"Elegant piadina with roast turkey, creamy brie, spinach, and black truffle cream","it":"Piadina elegante con arrosto di tacchino, brie cremoso, spinaci e crema al tartufo nero","vi":"Piadina thanh lịch với gà tây quay, brie kem, rau bina và kem nấm truffle đen"}'::jsonb, NULL, 'signature', 'italian', '{"piadina","gourmet","truffle","brie","tacchino","signature"}', 'piadina', false, true, '{"roast_turkey"}', '{"brie"}', '{"spinach"}', '{"truffle_cream"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["champagne","white_wine"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":540,"protein_g":32,"carbs_g":46,"fat_g":26,"fiber_g":2}'::jsonb, NULL, '{}', 82, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-salmone-philadelphia-rucola', 'piadina-salmone-philadelphia-rucola', '{"en":"Smoked Salmon & Cream Cheese Piadina","it":"Piadina Salmone Affumicato e Philadelphia","vi":"Piadina Cá Hồi Hun Khói và Kem Phô Mai"}'::jsonb, '{"en":"Nordic-inspired piadina with smoked salmon, cream cheese, capers, and fresh arugula","it":"Piadina ispirazione nordica con salmone affumicato, Philadelphia, capperi e rucola fresca","vi":"Piadina cảm hứng Bắc Âu với cá hồi hun khói, kem phô mai, nụ bạch hoa và arugula tươi"}'::jsonb, NULL, 'modern', 'italian', '{"piadina","salmone","modern","seafood","nordic_fusion"}', 'piadina', false, true, '{"smoked_salmon"}', '{"cream_cheese"}', '{"arugula","capers"}', '{"lemon_juice"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["prosecco","white_wine"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","fish"],"calories_estimate":480,"protein_g":26,"carbs_g":44,"fat_g":22,"fiber_g":2}'::jsonb, NULL, '{}', 84, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-sardoncini-burrata', 'piadina-sardoncini-burrata', '{"en":"Fried Sardines & Burrata Piadina","it":"Piadina Sardoncini Fritti e Burrata","vi":"Piadina Cá Mòi Chiên và Burrata"}'::jsonb, '{"en":"Adriatic coast specialty: small fried sardines with creamy burrata and mixed greens","it":"Specialità della costa adriatica: sardoncini infarinati e fritti con burrata cremosa e misticanza","vi":"Đặc sản bờ biển Adriatic: cá mòi nhỏ chiên với burrata kem và rau xanh hỗn hợp"}'::jsonb, NULL, 'traditional', 'italian', '{"piadina","adriatico","sardoncini","burrata","seafood","coastal"}', 'piadina', false, true, '{"fried_sardines"}', '{"burrata"}', '{"mixed_greens"}', '{"olive_oil","lemon"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna","city":"Rimini"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["white_wine","prosecco"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","fish"],"calories_estimate":520,"protein_g":28,"carbs_g":46,"fat_g":26,"fiber_g":2}'::jsonb, NULL, '{}', 78, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-porchetta-pecorino-peperoni', 'piadina-porchetta-pecorino-peperoni', '{"en":"Porchetta, Pecorino & Roasted Peppers Piadina","it":"Piadina Porchetta, Pecorino e Peperoni Grigliati","vi":"Piadina Porchetta, Pecorino và Ớt Chuông Nướng"}'::jsonb, '{"en":"Rich piadina with porchetta, aged pecorino, and sweet roasted peppers","it":"Piadina ricca con porchetta, pecorino stagionato e peperoni dolci grigliati","vi":"Piadina đậm đà với porchetta, pecorino lâu năm và ớt chuông nướng ngọt"}'::jsonb, NULL, 'modern', 'italian', '{"piadina","porchetta","pecorino","peperoni","gourmet"}', 'piadina', false, true, '{"porchetta"}', '{"pecorino"}', '{"roasted_peppers"}', '{}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["red_wine","beer"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":620,"protein_g":36,"carbs_g":48,"fat_g":32,"fiber_g":3}'::jsonb, NULL, '{}', 80, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-gratinati', 'piadina-gratinati', '{"en":"Grilled Vegetables Piadina","it":"Piadina ai Gratinati","vi":"Piadina Rau Nướng"}'::jsonb, '{"en":"Classic vegetarian piadina with grilled mixed vegetables: peppers, zucchini, eggplant, and onion","it":"Classica piadina vegetariana con gratinati misti: peperoni, zucchine, melanzane e cipolla","vi":"Piadina chay cổ điển với rau nướng hỗn hợp: ớt chuông, bí, cà tím và hành"}'::jsonb, NULL, 'classic', 'italian', '{"piadina","vegetarian","gratinati","verdure","healthy"}', 'piadina', false, true, '{}', '{"stracchino"}', '{"grilled_peppers","grilled_zucchini","grilled_eggplant","grilled_onion"}', '{"olive_oil"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["white_wine","prosecco"]}'::jsonb, '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk"],"calories_estimate":420,"protein_g":14,"carbs_g":52,"fat_g":18,"fiber_g":6}'::jsonb, NULL, '{}', 82, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-brie-verdure-grigliate', 'piadina-brie-verdure-grigliate', '{"en":"Brie & Grilled Vegetables Piadina","it":"Piadina Brie e Verdure Grigliate","vi":"Piadina Brie và Rau Nướng"}'::jsonb, '{"en":"Elegant vegetarian piadina with creamy brie and a mix of grilled seasonal vegetables","it":"Piadina vegetariana elegante con brie cremoso e mix di verdure grigliate di stagione","vi":"Piadina chay thanh lịch với brie kem và hỗn hợp rau nướng theo mùa"}'::jsonb, NULL, 'modern', 'italian', '{"piadina","vegetarian","brie","verdure","gourmet"}', 'piadina', false, true, '{}', '{"brie"}', '{"grilled_vegetables_mix","arugula"}', '{"olive_oil","balsamic_glaze"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["white_wine","prosecco"]}'::jsonb, '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk"],"calories_estimate":460,"protein_g":16,"carbs_g":50,"fat_g":22,"fiber_g":5}'::jsonb, NULL, '{}', 78, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-caprese', 'piadina-caprese', '{"en":"Caprese Piadina","it":"Piadina Caprese","vi":"Piadina Caprese"}'::jsonb, '{"en":"Fresh vegetarian piadina with buffalo mozzarella, ripe tomatoes, fresh basil, and extra virgin olive oil","it":"Piadina vegetariana fresca con mozzarella di bufala, pomodori maturi, basilico fresco e olio extravergine","vi":"Piadina chay tươi với mozzarella trâu, cà chua chín, húng quế tươi và dầu olive nguyên chất"}'::jsonb, NULL, 'classic', 'italian', '{"piadina","caprese","vegetarian","bufala","fresh","summer"}', 'piadina', false, true, '{}', '{"buffalo_mozzarella"}', '{"tomato","fresh_basil"}', '{"olive_oil","salt","pepper"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna / Campania"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["white_wine","prosecco"]}'::jsonb, '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk"],"calories_estimate":440,"protein_g":18,"carbs_g":46,"fat_g":20,"fiber_g":3}'::jsonb, NULL, '{}', 86, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-nutella', 'piadina-nutella', '{"en":"Nutella Piadina","it":"Piadina alla Nutella","vi":"Piadina Nutella"}'::jsonb, '{"en":"Sweet piadina filled with warm, melting Nutella hazelnut spread","it":"Piadina dolce farcita con Nutella calda e filante","vi":"Piadina ngọt nhân Nutella hạt phỉ ấm tan chảy"}'::jsonb, NULL, 'classic', 'italian', '{"piadina","dolce","nutella","dessert","sweet"}', 'piadina', false, true, '{}', '{}', '{}', '{"nutella"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":true,"recommended_pairing":["espresso","cappuccino","milk"]}'::jsonb, '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk","tree_nuts","soy"],"calories_estimate":520,"protein_g":8,"carbs_g":68,"fat_g":24,"fiber_g":3}'::jsonb, NULL, '{}', 92, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-marmellata-ricotta', 'piadina-marmellata-ricotta', '{"en":"Jam & Ricotta Piadina","it":"Piadina Marmellata e Ricotta","vi":"Piadina Mứt và Ricotta"}'::jsonb, '{"en":"Traditional sweet piadina with fresh ricotta and seasonal fruit jam","it":"Piadina dolce tradizionale con ricotta fresca e marmellata di frutta di stagione","vi":"Piadina ngọt truyền thống với ricotta tươi và mứt trái cây theo mùa"}'::jsonb, NULL, 'traditional', 'italian', '{"piadina","dolce","marmellata","ricotta","breakfast","dessert"}', 'piadina', false, true, '{}', '{"ricotta"}', '{}', '{"fruit_jam","honey"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":true,"recommended_pairing":["espresso","tea","dessert_wine"]}'::jsonb, '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk"],"calories_estimate":420,"protein_g":12,"carbs_g":62,"fat_g":14,"fiber_g":2}'::jsonb, NULL, '{}', 74, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();