-- SANDWICHES Batch 4
-- Items: 31 to 40 of 50
-- Generated: 2025-12-15T12:52:44.859Z

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-crudo-squacquerone-rucola', 'piadina-crudo-squacquerone-rucola', '{"en":"Prosciutto Crudo, Squacquerone & Arugula Piadina","it":"Piadina Crudo, Squacquerone e Rucola","vi":"Piadina Prosciutto, Squacquerone và Rau Arugula"}'::jsonb, '{"en":"The quintessential Romagnola piadina: aged prosciutto crudo, creamy squacquerone cheese, and peppery arugula","it":"La piadina romagnola per eccellenza: prosciutto crudo stagionato, squacquerone cremoso e rucola piccante","vi":"Piadina Romagnola tinh túy: prosciutto crudo ủ, phô mai squacquerone kem và rau arugula cay"}'::jsonb, NULL, 'classic', 'italian', '{"piadina","romagnola","classic","prosciutto","squacquerone","traditional","IGP"}', 'piadina', false, true, '{"prosciutto_crudo"}', '{"squacquerone"}', '{"arugula"}', '{}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna","city":"Rimini"}'::jsonb, '{"story":{"en":"The most iconic piadina filling, representing the perfect balance of Romagna flavors","it":"La farcitura più iconica, che rappresenta il perfetto equilibrio dei sapori romagnoli","vi":"Nhân piadina biểu tượng nhất, đại diện cho sự cân bằng hoàn hảo của hương vị Romagna"}}'::jsonb, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["sangiovese","lambrusco","prosecco"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":520,"protein_g":26,"carbs_g":48,"fat_g":24,"fiber_g":2}'::jsonb, NULL, '{}', 98, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-salsiccia-cipolla', 'piadina-salsiccia-cipolla', '{"en":"Sausage & Caramelized Onion Piadina","it":"Piadina Salsiccia e Cipolla","vi":"Piadina Xúc Xích và Hành Caramel"}'::jsonb, '{"en":"The queen of Romagna festivals: crumbled Italian sausage with sweet caramelized onions","it":"La regina delle sagre romagnole: salsiccia sbriciolata con cipolle dolci caramellate","vi":"Nữ hoàng của các lễ hội Romagna: xúc xích Ý vụn với hành tây caramel ngọt"}'::jsonb, NULL, 'traditional', 'italian', '{"piadina","romagnola","salsiccia","sagra","street_food","traditional"}', 'piadina', false, true, '{"italian_sausage"}', '{}', '{"caramelized_onions"}', '{}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["sangiovese","lambrusco","beer"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten"],"calories_estimate":580,"protein_g":28,"carbs_g":52,"fat_g":28,"fiber_g":3}'::jsonb, NULL, '{}', 94, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-salsiccia-stracchino', 'piadina-salsiccia-stracchino', '{"en":"Sausage & Stracchino Piadina","it":"Piadina Salsiccia e Stracchino","vi":"Piadina Xúc Xích và Stracchino"}'::jsonb, '{"en":"A timeless classic: savory Italian sausage paired with creamy, melting stracchino cheese","it":"Un classico intramontabile: salsiccia saporita abbinata a stracchino cremoso e filante","vi":"Cổ điển vượt thời gian: xúc xích Ý đậm đà kết hợp với phô mai stracchino kem tan chảy"}'::jsonb, NULL, 'classic', 'italian', '{"piadina","romagnola","salsiccia","stracchino","classic","cheese"}', 'piadina', false, true, '{"italian_sausage"}', '{"stracchino"}', '{}', '{}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["sangiovese","lambrusco"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":620,"protein_g":30,"carbs_g":48,"fat_g":34,"fiber_g":2}'::jsonb, NULL, '{}', 92, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-porchetta', 'piadina-porchetta', '{"en":"Porchetta Piadina","it":"Piadina con Porchetta","vi":"Piadina Porchetta"}'::jsonb, '{"en":"Legendary combination: slow-roasted porchetta with crispy skin, optionally with pecorino","it":"Abbinamento leggendario: porchetta arrosto con pelle croccante, opzionalmente con pecorino","vi":"Kết hợp huyền thoại: porchetta quay chậm với da giòn, tùy chọn với pecorino"}'::jsonb, NULL, 'traditional', 'italian', '{"piadina","porchetta","traditional","etruscan","pork","street_food"}', 'piadina', false, true, '{"porchetta"}', '{"pecorino"}', '{}', '{}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna / Lazio"}'::jsonb, '{"story":{"en":"Porchetta dates back to the ancient Etruscans. It''s said that even vegetarians have capitulated before this delicacy","it":"La porchetta risale agli antichi Etruschi. Si dice che anche i vegetariani siano capitolati davanti a questa prelibatezza","vi":"Porchetta có từ thời người Etruscan cổ đại. Người ta nói rằng ngay cả người ăn chay cũng đã đầu hàng trước món ngon này"}}'::jsonb, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["red_wine","beer"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":650,"protein_g":38,"carbs_g":48,"fat_g":34,"fiber_g":2}'::jsonb, NULL, '{}', 90, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-speck-gorgonzola-noci', 'piadina-speck-gorgonzola-noci', '{"en":"Speck, Gorgonzola & Walnut Piadina","it":"Piadina Speck, Gorgonzola e Noci","vi":"Piadina Speck, Gorgonzola và Óc Chó"}'::jsonb, '{"en":"Refined combination: smoked speck, creamy gorgonzola, and crunchy walnuts","it":"Combinazione raffinata: speck affumicato, gorgonzola cremoso e noci croccanti","vi":"Kết hợp tinh tế: speck hun khói, gorgonzola kem và óc chó giòn"}'::jsonb, NULL, 'classic', 'italian', '{"piadina","speck","gorgonzola","noci","gourmet"}', 'piadina', false, true, '{"speck"}', '{"gorgonzola"}', '{"walnuts"}', '{}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["red_wine","prosecco"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","tree_nuts"],"calories_estimate":580,"protein_g":26,"carbs_g":46,"fat_g":32,"fiber_g":2}'::jsonb, NULL, '{}', 86, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('piadina-prosciutto-parmigiano-balsamico', 'piadina-prosciutto-parmigiano-balsamico', '{"en":"Prosciutto, Parmigiano & Balsamic Piadina","it":"Piadina Prosciutto, Parmigiano e Balsamico","vi":"Piadina Prosciutto, Parmigiano và Giấm Balsamic"}'::jsonb, '{"en":"The most typical Emilia-Romagna combination: Parma ham DOP, aged Parmigiano Reggiano, and balsamic glaze","it":"L''abbinamento più tipico dell''Emilia-Romagna: Prosciutto di Parma DOP, Parmigiano Reggiano stagionato e glassa balsamica","vi":"Kết hợp điển hình nhất của Emilia-Romagna: Giăm bông Parma DOP, Parmigiano Reggiano lâu năm và sốt balsamic"}'::jsonb, NULL, 'classic', 'italian', '{"piadina","emilia_romagna","DOP","prosciutto","parmigiano","balsamico"}', 'piadina', false, true, '{"prosciutto_di_parma"}', '{"parmigiano_reggiano"}', '{}', '{"balsamic_glaze"}', true, false, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["lambrusco","sangiovese"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk"],"calories_estimate":540,"protein_g":30,"carbs_g":46,"fat_g":26,"fiber_g":2}'::jsonb, NULL, '{}', 88, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('crescione-erbette', 'crescione-erbette', '{"en":"Traditional Herb Crescione","it":"Crescione alle Erbette","vi":"Crescione Rau Thơm Truyền Thống"}'::jsonb, '{"en":"The original crescione: half-moon shaped piadina filled with spinach, chard, and garlic, sealed and grilled","it":"Il crescione originale: piadina a mezzaluna ripiena di spinaci, bietole e aglio, sigillata e grigliata","vi":"Crescione nguyên bản: piadina hình bán nguyệt nhân rau bina, cải xanh và tỏi, niêm phong và nướng"}'::jsonb, NULL, 'traditional', 'italian', '{"crescione","cassone","erbette","vegan","traditional","ancient"}', 'piadina', false, true, '{}', '{}', '{"spinach","swiss_chard","garlic"}', '{"olive_oil"}', true, true, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna","city":"Ravenna"}'::jsonb, '{"story":{"en":"The name \"crescione\" derives from watercress, the herb traditionally used for the filling. This is the most ancient recipe.","it":"Il nome \"crescione\" deriva dall''erba crescione d''acqua, tradizionalmente usata per il ripieno. Questa è la ricetta più antica.","vi":"Tên \"crescione\" bắt nguồn từ cải xoong, loại rau truyền thống được dùng làm nhân. Đây là công thức cổ xưa nhất."}}'::jsonb, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["white_wine","sparkling_water"]}'::jsonb, '{"is_vegetarian":true,"is_vegan":true,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten"],"calories_estimate":380,"protein_g":10,"carbs_g":52,"fat_g":14,"fiber_g":6}'::jsonb, NULL, '{}', 82, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('crescione-pomodoro-mozzarella', 'crescione-pomodoro-mozzarella', '{"en":"Tomato & Mozzarella Crescione","it":"Crescione Pomodoro e Mozzarella","vi":"Crescione Cà Chua và Mozzarella"}'::jsonb, '{"en":"Classic crescione with fresh tomato, melting mozzarella, and oregano","it":"Crescione classico con pomodoro fresco, mozzarella filante e origano","vi":"Crescione cổ điển với cà chua tươi, mozzarella tan chảy và oregano"}'::jsonb, NULL, 'classic', 'italian', '{"crescione","vegetarian","tomato","mozzarella","classic"}', 'piadina', false, true, '{}', '{"mozzarella"}', '{"tomato"}', '{"oregano","olive_oil"}', true, true, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["white_wine","beer"]}'::jsonb, '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk"],"calories_estimate":420,"protein_g":16,"carbs_g":50,"fat_g":18,"fiber_g":3}'::jsonb, NULL, '{}', 84, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('crescione-salsiccia-patate', 'crescione-salsiccia-patate', '{"en":"Sausage & Potato Crescione","it":"Crescione Salsiccia e Patate","vi":"Crescione Xúc Xích và Khoai Tây"}'::jsonb, '{"en":"Hearty crescione filled with crumbled sausage and roasted potatoes with rosemary","it":"Crescione sostanzioso ripieno di salsiccia sbriciolata e patate arrosto al rosmarino","vi":"Crescione đầy đặn với xúc xích vụn và khoai tây nướng với hương thảo"}'::jsonb, NULL, 'traditional', 'italian', '{"crescione","salsiccia","patate","hearty","traditional"}', 'piadina', false, true, '{"italian_sausage"}', '{}', '{"roasted_potatoes","rosemary"}', '{}', true, true, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"large","is_shareable":false,"recommended_pairing":["red_wine","beer"]}'::jsonb, '{"is_vegetarian":false,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":true,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten"],"calories_estimate":620,"protein_g":26,"carbs_g":62,"fat_g":28,"fiber_g":4}'::jsonb, NULL, '{}', 80, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();

INSERT INTO sandwiches (id, slug, name, description, tagline, status, style, tags, bread_type, bread_is_toasted, bread_is_grilled, proteins, cheeses, vegetables, condiments, is_hot, is_pressed, origin, history, serving, dietary, customization, variations, popularity, related_sandwiches, media, pricing)
VALUES ('crescione-fichi-pecorino', 'crescione-fichi-pecorino', '{"en":"Fig & Pecorino Crescione","it":"Crescione Fichi e Pecorino","vi":"Crescione Sung và Pecorino"}'::jsonb, '{"en":"Sweet and savory crescione with fresh figs and aged pecorino cheese","it":"Crescione dolce-salato con fichi freschi e pecorino stagionato","vi":"Crescione ngọt mặn với sung tươi và phô mai pecorino lâu năm"}'::jsonb, NULL, 'traditional', 'italian', '{"crescione","fichi","pecorino","sweet_savory","seasonal"}', 'piadina', false, true, '{}', '{"pecorino"}', '{"fresh_figs"}', '{"honey"}', true, true, '{"country":"Italy","country_code":"IT","region":"Emilia-Romagna"}'::jsonb, NULL, '{"portion_size":"regular","is_shareable":false,"recommended_pairing":["dessert_wine","prosecco"]}'::jsonb, '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk"],"calories_estimate":480,"protein_g":14,"carbs_g":58,"fat_g":22,"fiber_g":4}'::jsonb, NULL, '{}', 76, '{}', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  dietary = EXCLUDED.dietary,
  updated_at = NOW();