/**
 * GUDBRO Ingredient Database - Citrus, Herbs & Vegetables
 *
 * Additional ingredients extracted from ROOTS and Coffee House menus
 * Focus: Lemon, Lime, Orange, Ginger, Turmeric, Mint, Vegetables
 */

import type { IngredientMaster } from '../types';

export const citrusHerbsVegetables: IngredientMaster[] = [
  // ========================================================================
  // CITRUS FRUITS
  // ========================================================================
  {
    id: 'ING_LEMON',
    slug: 'lemon',
    name: {
      en: 'Lemon',
      it: 'Limone',
      vi: 'Chanh',
      ko: '레몬',
      ja: 'レモン',
    },
    category: { main: 'fruits', sub: 'citrus' },
    allergens: {},
    intolerances: {
      fodmap: true,
      histamine: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 1.1,
      carbs_g: 9.3,
      fat_g: 0.3,
      fiber_g: 2.8,
      calories_kcal: 29,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_LIME',
    slug: 'lime',
    name: {
      en: 'Lime',
      it: 'Lime',
      vi: 'Chanh Xanh',
      ko: '라임',
      ja: 'ライム',
    },
    category: { main: 'fruits', sub: 'citrus' },
    allergens: {},
    intolerances: {
      fodmap: true,
      histamine: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0.7,
      carbs_g: 10.5,
      fat_g: 0.2,
      fiber_g: 2.8,
      calories_kcal: 30,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_ORANGE',
    slug: 'orange',
    name: {
      en: 'Orange',
      it: 'Arancia',
      vi: 'Cam',
      ko: '오렌지',
      ja: 'オレンジ',
    },
    category: { main: 'fruits', sub: 'citrus' },
    allergens: {
      orange: true, // Japan allergen
    },
    intolerances: {
      fodmap: true,
      histamine: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0.9,
      carbs_g: 11.8,
      fat_g: 0.1,
      fiber_g: 2.4,
      calories_kcal: 47,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // HERBS & SPICES (High-Use)
  // ========================================================================
  {
    id: 'ING_GINGER',
    slug: 'ginger',
    name: {
      en: 'Ginger',
      it: 'Zenzero',
      vi: 'Gừng',
      ko: '생강',
      ja: '生姜',
    },
    category: { main: 'spices', sub: 'root' },
    allergens: {},
    intolerances: {
      fodmap: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 2, scoville: 0, description: { en: 'Warm, pungent', it: 'Caldo, pungente', vi: 'Ấm, hăng' } },
    nutrition: {
      protein_g: 1.8,
      carbs_g: 17.8,
      fat_g: 0.8,
      fiber_g: 2.0,
      calories_kcal: 80,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_TURMERIC',
    slug: 'turmeric',
    name: {
      en: 'Turmeric',
      it: 'Curcuma',
      vi: 'Nghệ',
      ko: '강황',
      ja: 'ターメリック',
    },
    description: {
      en: 'Golden spice, anti-inflammatory superfood',
      it: 'Spezia dorata, superfood anti-infiammatorio',
      vi: 'Gia vị vàng, siêu thực phẩm chống viêm',
    },
    category: { main: 'spices', sub: 'root' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 1 },
    nutrition: {
      protein_g: 7.8,
      carbs_g: 64.9,
      fat_g: 9.9,
      fiber_g: 21.1,
      calories_kcal: 354,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_MINT',
    slug: 'mint',
    name: {
      en: 'Mint',
      it: 'Menta',
      vi: 'Bạc Hà',
      ko: '민트',
      ja: 'ミント',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 3.8,
      carbs_g: 14.9,
      fat_g: 0.9,
      fiber_g: 8.0,
      calories_kcal: 70,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_BASIL',
    slug: 'basil',
    name: {
      en: 'Basil',
      it: 'Basilico',
      vi: 'Húng Quế',
      ko: '바질',
      ja: 'バジル',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {
      salicylates: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 3.2,
      carbs_g: 2.7,
      fat_g: 0.6,
      fiber_g: 1.6,
      calories_kcal: 23,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_PARSLEY',
    slug: 'parsley',
    name: {
      en: 'Parsley',
      it: 'Prezzemolo',
      vi: 'Rau Mùi Tây',
      ko: '파슬리',
      ja: 'パセリ',
    },
    category: { main: 'herbs', sub: 'fresh' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 3.0,
      carbs_g: 6.3,
      fat_g: 0.8,
      fiber_g: 3.3,
      calories_kcal: 36,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  // ========================================================================
  // VEGETABLES (High-Use)
  // ========================================================================
  {
    id: 'ING_BEETROOT',
    slug: 'beetroot',
    name: {
      en: 'Beetroot',
      it: 'Barbabietola',
      vi: 'Củ Dền',
      ko: '비트',
      ja: 'ビートルート',
    },
    category: { main: 'vegetables', sub: 'root' },
    allergens: {},
    intolerances: {
      fodmap: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 1.6,
      carbs_g: 9.6,
      fat_g: 0.2,
      fiber_g: 2.8,
      calories_kcal: 43,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_CARROT',
    slug: 'carrot',
    name: {
      en: 'Carrot',
      it: 'Carota',
      vi: 'Cà Rốt',
      ko: '당근',
      ja: 'ニンジン',
    },
    category: { main: 'vegetables', sub: 'root' },
    allergens: {},
    intolerances: {},
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0.9,
      carbs_g: 9.6,
      fat_g: 0.2,
      fiber_g: 2.8,
      calories_kcal: 41,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_CUCUMBER',
    slug: 'cucumber',
    name: {
      en: 'Cucumber',
      it: 'Cetriolo',
      vi: 'Dưa Chuột',
      ko: '오이',
      ja: 'キュウリ',
    },
    category: { main: 'vegetables', sub: 'fruits' },
    allergens: {},
    intolerances: {
      fodmap: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0.7,
      carbs_g: 3.6,
      fat_g: 0.1,
      fiber_g: 0.5,
      calories_kcal: 15,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_MUSHROOMS',
    slug: 'mushrooms',
    name: {
      en: 'Mushrooms',
      it: 'Funghi',
      vi: 'Nấm',
      ko: '버섯',
      ja: 'きのこ',
    },
    description: {
      en: 'Mixed mushrooms (button, cremini, etc.)',
      it: 'Funghi misti (champignon, cremini, ecc.)',
      vi: 'Nấm hỗn hợp',
    },
    category: { main: 'vegetables', sub: 'fungi' },
    allergens: {},
    intolerances: {
      fodmap: true,
      histamine: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 3.1,
      carbs_g: 3.3,
      fat_g: 0.3,
      fiber_g: 1.0,
      calories_kcal: 22,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_BROCCOLI',
    slug: 'broccoli',
    name: {
      en: 'Broccoli',
      it: 'Broccoli',
      vi: 'Bông Cải Xanh',
      ko: '브로콜리',
      ja: 'ブロッコリー',
    },
    category: { main: 'vegetables', sub: 'cruciferous' },
    allergens: {},
    intolerances: {
      fodmap: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 2.8,
      carbs_g: 6.6,
      fat_g: 0.4,
      fiber_g: 2.6,
      calories_kcal: 34,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_CABBAGE',
    slug: 'cabbage',
    name: {
      en: 'Cabbage',
      it: 'Cavolo',
      vi: 'Bắp Cải',
      ko: '양배추',
      ja: 'キャベツ',
    },
    category: { main: 'vegetables', sub: 'cruciferous' },
    allergens: {},
    intolerances: {
      fodmap: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 1.3,
      carbs_g: 5.8,
      fat_g: 0.1,
      fiber_g: 2.5,
      calories_kcal: 25,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },

  {
    id: 'ING_CELERY',
    slug: 'celery',
    name: {
      en: 'Celery',
      it: 'Sedano',
      vi: 'Cần Tây',
      ko: '셀러리',
      ja: 'セロリ',
    },
    category: { main: 'vegetables', sub: 'stalks' },
    allergens: {
      celery: true, // EU 14 allergen
    },
    intolerances: {
      fodmap: true,
    },
    dietary_restrictions: {
      vegan: true,
      vegetarian: true,
      pescatarian: true,
      gluten_free: true,
      dairy_free: true,
      nut_free: true,
      halal: true,
      kosher: true,
      low_carb: true,
    },
    spice: { level: 0 },
    nutrition: {
      protein_g: 0.7,
      carbs_g: 3.0,
      fat_g: 0.2,
      fiber_g: 1.6,
      calories_kcal: 14,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    version: 1,
  },
];

export const CITRUS_HERBS_VEGETABLES_COUNT = citrusHerbsVegetables.length;
