-- Dutch Cuisine - Insert Dishes
-- GUDBRO Database Standards v1.7
-- Generated: 2025-12-25
-- Total dishes: 38

INSERT INTO dutch (id, slug, name, local_name, description, category, region, status, protein_type, cooking_method, prep_time_min, spice_level, dietary, allergens, tags, popularity) VALUES

-- STAMPPOT (5 dishes)
('DUT_BOERENKOOL', 'boerenkool-stamppot', 'Boerenkool Stamppot', 'Boerenkool met Worst', 'Traditional Dutch mashed potatoes with kale and smoked sausage, served with gravy', 'stamppot', 'nationwide', 'iconic', 'pork', 'boiled', 45, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy'], ARRAY['comfort-food', 'winter', 'traditional'], 95),
('DUT_HUTSPOT', 'hutspot', 'Hutspot', 'Hutspot met Klapstuk', 'Mashed potatoes with carrots and onions, traditionally served with braised beef', 'stamppot', 'holland', 'iconic', 'beef', 'boiled', 60, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy'], ARRAY['comfort-food', 'historical', 'leiden'], 90),
('DUT_ANDIJVIE', 'andijvie-stamppot', 'Andijvie Stamppot', 'Andijviestamppot', 'Creamy mashed potatoes with endive and bacon bits', 'stamppot', 'nationwide', 'classic', 'pork', 'boiled', 35, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy'], ARRAY['comfort-food', 'quick'], 80),
('DUT_ZUURKOOL', 'zuurkool-stamppot', 'Zuurkool Stamppot', 'Zuurkoolstamppot', 'Mashed potatoes with sauerkraut and smoked sausage', 'stamppot', 'nationwide', 'classic', 'pork', 'boiled', 40, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy'], ARRAY['comfort-food', 'winter', 'german-influence'], 75),
('DUT_HETE_BLIKSEM', 'hete-bliksem', 'Hete Bliksem', 'Hete Bliksem', 'Hot Lightning - mashed potatoes with apples and bacon, sweet and savory', 'stamppot', 'limburg', 'traditional', 'pork', 'boiled', 40, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy'], ARRAY['sweet-savory', 'regional', 'autumn'], 65),

-- SNACKS (8 dishes)
('DUT_BITTERBALLEN', 'bitterballen', 'Bitterballen', 'Bitterballen', 'Deep-fried crispy balls filled with beef ragout, served with mustard', 'snacks', 'nationwide', 'iconic', 'beef', 'deep-fried', 60, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['bar-snack', 'fried', 'popular'], 98),
('DUT_KROKET', 'kroket', 'Kroket', 'Kroket', 'Deep-fried oblong croquette with creamy meat ragout filling', 'snacks', 'nationwide', 'iconic', 'beef', 'deep-fried', 60, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['street-food', 'fried', 'automaat'], 95),
('DUT_FRIKANDEL', 'frikandel', 'Frikandel', 'Frikandel', 'Skinless deep-fried minced meat sausage, Dutch fast food staple', 'snacks', 'nationwide', 'iconic', 'mixed', 'deep-fried', 15, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten'], ARRAY['street-food', 'fast-food', 'snackbar'], 92),
('DUT_FRIKANDEL_SPECIAAL', 'frikandel-speciaal', 'Frikandel Speciaal', 'Frikandel Speciaal', 'Frikandel topped with curry ketchup, mayonnaise, and raw onions', 'snacks', 'nationwide', 'iconic', 'mixed', 'deep-fried', 15, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'eggs'], ARRAY['street-food', 'fast-food', 'popular'], 90),
('DUT_KAASSOUFFLE', 'kaassouffle', 'Kaassoufflé', 'Kaassoufflé', 'Deep-fried puff pastry pocket filled with melted Gouda cheese', 'snacks', 'nationwide', 'classic', 'vegetarian', 'deep-fried', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'dairy'], ARRAY['vegetarian', 'fried', 'cheese'], 85),
('DUT_KIPCORN', 'kipcorn', 'Kipcorn', 'Kipcorn', 'Corn-shaped deep-fried snack filled with spiced chicken', 'snacks', 'nationwide', 'classic', 'chicken', 'deep-fried', 15, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten'], ARRAY['street-food', 'chicken', 'snackbar'], 75),
('DUT_BAMISCHIJF', 'bamischijf', 'Bamischijf', 'Bamischijf', 'Deep-fried disc of bami goreng noodles, Indonesian-Dutch fusion', 'snacks', 'nationwide', 'classic', 'mixed', 'deep-fried', 20, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'soy'], ARRAY['fusion', 'indonesian-dutch', 'snackbar'], 70),
('DUT_NASISCHIJF', 'nasischijf', 'Nasischijf', 'Nasischijf', 'Deep-fried disc of nasi goreng rice, Indonesian-Dutch fusion', 'snacks', 'nationwide', 'classic', 'mixed', 'deep-fried', 20, 1, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'soy'], ARRAY['fusion', 'indonesian-dutch', 'snackbar'], 68),

-- MAINS (5 dishes)
('DUT_HACHEE', 'hachee', 'Hachee', 'Hachee', 'Traditional Dutch beef and onion stew with cloves and vinegar', 'mains', 'nationwide', 'classic', 'beef', 'stewed', 120, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY['stew', 'comfort-food', 'traditional'], 80),
('DUT_DRAADJESVLEES', 'draadjesvlees', 'Draadjesvlees', 'Draadjesvlees', 'Slow-cooked stringy beef in rich gravy, fork-tender', 'mains', 'nationwide', 'classic', 'beef', 'braised', 180, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['dairy'], ARRAY['slow-cooked', 'sunday-dinner', 'comfort-food'], 75),
('DUT_BALKENBRIJ', 'balkenbrij', 'Balkenbrij', 'Balkenbrij', 'Traditional buckwheat and pork offal sausage, sliced and pan-fried', 'mains', 'limburg', 'traditional', 'pork', 'pan-fried', 30, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten'], ARRAY['regional', 'breakfast', 'rustic'], 55),
('DUT_SLAVINK', 'slavink', 'Slavink', 'Slavink', 'Minced meat wrapped in bacon, pan-fried until crispy', 'mains', 'nationwide', 'classic', 'mixed', 'pan-fried', 25, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten'], ARRAY['comfort-food', 'weeknight-dinner'], 70),
('DUT_GEHAKTBAL', 'gehaktbal', 'Gehaktbal', 'Gehaktbal', 'Large Dutch meatball in rich gravy, comfort food classic', 'mains', 'nationwide', 'classic', 'mixed', 'braised', 45, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['comfort-food', 'sunday-dinner', 'gravy'], 82),

-- SOUPS (3 dishes)
('DUT_ERWTENSOEP', 'erwtensoep', 'Erwtensoep', 'Snert', 'Thick Dutch split pea soup with smoked sausage, so thick the spoon stands up', 'soups', 'nationwide', 'iconic', 'pork', 'simmered', 120, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY['winter', 'hearty', 'traditional'], 95),
('DUT_BRUINE_BONENSOEP', 'bruine-bonensoep', 'Bruine Bonensoep', 'Bruine Bonensoep', 'Hearty brown bean soup with bacon and vegetables', 'soups', 'nationwide', 'classic', 'pork', 'simmered', 90, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY[]::TEXT[], ARRAY['winter', 'hearty', 'beans'], 70),
('DUT_KONINGINNESOEP', 'koninginnesoep', 'Koninginnesoep', 'Koninginnesoep', 'Queen soup - creamy chicken soup with meatballs and asparagus', 'soups', 'nationwide', 'classic', 'chicken', 'simmered', 60, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['dairy', 'gluten', 'eggs'], ARRAY['elegant', 'creamy', 'special-occasion'], 65),

-- SEAFOOD (5 dishes)
('DUT_HOLLANDSE_HARING', 'hollandse-nieuwe', 'Hollandse Nieuwe', 'Hollandse Nieuwe Haring', 'Fresh raw herring served with onions and pickles, eaten by holding the tail', 'seafood', 'holland', 'iconic', 'fish', 'raw', 5, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['fish'], ARRAY['raw', 'street-food', 'traditional'], 90),
('DUT_KIBBELING', 'kibbeling', 'Kibbeling', 'Kibbeling', 'Deep-fried battered cod chunks served with garlic sauce or ravigote', 'seafood', 'zeeland', 'iconic', 'fish', 'deep-fried', 20, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['fish', 'gluten', 'eggs'], ARRAY['street-food', 'fried', 'fish'], 92),
('DUT_LEKKERBEKJE', 'lekkerbekje', 'Lekkerbekje', 'Lekkerbekje', 'Battered and deep-fried whiting fillet, a Dutch fish shop classic', 'seafood', 'zeeland', 'classic', 'fish', 'deep-fried', 20, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['fish', 'gluten', 'eggs'], ARRAY['fried', 'fish', 'street-food'], 75),
('DUT_GEROOKTE_PALING', 'gerookte-paling', 'Gerookte Paling', 'Gerookte Paling', 'Traditional Dutch smoked eel, a delicacy from the Zuiderzee region', 'seafood', 'holland', 'traditional', 'fish', 'smoked', 10, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['fish'], ARRAY['smoked', 'delicacy', 'traditional'], 60),
('DUT_MOSSELEN', 'zeeuwse-mosselen', 'Zeeuwse Mosselen', 'Zeeuwse Mosselen', 'Zeeland mussels steamed with celery, leeks, and white wine', 'seafood', 'zeeland', 'iconic', 'shellfish', 'steamed', 30, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['shellfish', 'dairy'], ARRAY['shellfish', 'zeeland', 'seasonal'], 85),

-- PANCAKES (4 dishes)
('DUT_PANNENKOEK', 'dutch-pannenkoek', 'Dutch Pannenkoek', 'Pannenkoek', 'Large thin Dutch pancake, larger than crepes, served sweet or savory', 'pancakes', 'nationwide', 'iconic', 'vegetarian', 'pan-fried', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['breakfast', 'family', 'versatile'], 90),
('DUT_PANNENKOEK_SPEK', 'pannenkoek-met-spek', 'Pannenkoek met Spek', 'Spekpannenkoek', 'Dutch pancake with crispy bacon pieces baked in', 'pancakes', 'nationwide', 'classic', 'pork', 'pan-fried', 25, 0, '{"is_vegan": false, "is_vegetarian": false, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['savory', 'bacon', 'popular'], 85),
('DUT_POFFERTJES', 'poffertjes', 'Poffertjes', 'Poffertjes', 'Tiny fluffy Dutch pancakes made with yeast and buckwheat, served with butter and powdered sugar', 'pancakes', 'nationwide', 'iconic', 'vegetarian', 'pan-fried', 30, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['street-food', 'sweet', 'market'], 95),
('DUT_FLENSJES', 'flensjes', 'Flensjes', 'Flensjes', 'Thin Dutch crepes, typically filled with whipped cream and fruit', 'pancakes', 'nationwide', 'classic', 'vegetarian', 'pan-fried', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['dessert', 'thin', 'sweet'], 70),

-- DESSERTS (8 dishes)
('DUT_STROOPWAFEL', 'stroopwafel', 'Stroopwafel', 'Stroopwafel', 'Two thin waffle layers filled with caramel syrup, iconic Dutch treat', 'desserts', 'nationwide', 'iconic', NULL, 'baked', 45, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['cookie', 'caramel', 'street-food'], 98),
('DUT_OLIEBOLLEN', 'oliebollen', 'Oliebollen', 'Oliebollen', 'Traditional Dutch New Year doughnuts with raisins and powdered sugar', 'desserts', 'nationwide', 'iconic', NULL, 'deep-fried', 60, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['new-year', 'fried', 'traditional'], 95),
('DUT_APPELBEIGNETS', 'appelbeignets', 'Appelbeignets', 'Appelbeignets', 'Apple rings dipped in batter and deep-fried, dusted with sugar', 'desserts', 'nationwide', 'classic', NULL, 'deep-fried', 30, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['fried', 'apple', 'dessert'], 75),
('DUT_TOMPOUCE', 'tompouce', 'Tompouce', 'Tompouce', 'Dutch pastry with puff pastry layers, custard filling, and pink icing', 'desserts', 'nationwide', 'iconic', NULL, 'baked', 60, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'dairy', 'eggs'], ARRAY['pastry', 'kings-day', 'pink'], 88),
('DUT_HAAGSE_BLUF', 'haagse-bluf', 'Haagse Bluf', 'Haagse Bluf', 'The Hague bluff - whipped egg whites with redcurrant sauce', 'desserts', 'holland', 'traditional', NULL, 'no-cook', 20, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['eggs'], ARRAY['light', 'the-hague', 'foam'], 55),
('DUT_VLAFLIP', 'vlaflip', 'Vlaflip', 'Vlaflip', 'Layered dessert with vanilla custard, yogurt, and fruit sauce', 'desserts', 'nationwide', 'classic', NULL, 'no-cook', 15, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": false, "is_nut_free": true, "is_halal": true, "is_kosher": false}', ARRAY['dairy'], ARRAY['quick', 'layered', 'dairy'], 65),
('DUT_ADVOCAAT', 'advocaat', 'Advocaat', 'Advocaat', 'Rich Dutch egg liqueur, thick and creamy, often served as dessert', 'desserts', 'nationwide', 'classic', NULL, 'mixed', 30, 0, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": true, "is_dairy_free": true, "is_nut_free": true, "is_halal": false, "is_kosher": false}', ARRAY['eggs'], ARRAY['liqueur', 'christmas', 'rich'], 70),
('DUT_SPECULAAS', 'speculaas', 'Speculaas', 'Speculaas', 'Spiced Dutch shortcrust cookies, traditionally for Sinterklaas', 'desserts', 'nationwide', 'iconic', NULL, 'baked', 45, 1, '{"is_vegan": false, "is_vegetarian": true, "is_gluten_free": false, "is_dairy_free": false, "is_nut_free": false, "is_halal": true, "is_kosher": false}', ARRAY['gluten', 'dairy', 'nuts'], ARRAY['sinterklaas', 'spiced', 'cookie'], 92)

ON CONFLICT (id) DO NOTHING;

-- Verify
SELECT 'Dutch dishes inserted: ' || COUNT(*) AS status FROM dutch;
