-- GUDBRO Desserts Batch 02
-- Records: 11 to 20 of 35
-- Generated: 2025-12-15T22:59:56.673Z

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'baba-rum',
  'baba-rum',
  '{"en":"Baba au Rhum","it":"Baba al Rum","vi":"Banh Baba rum"}'::jsonb,
  '{"en":"Yeast cake soaked in rum syrup, a Neapolitan favorite","it":"Dolce lievitato inzuppato nello sciroppo al rum, un classico napoletano","vi":"Banh men ngam trong xi-ro rum, mon yeu thich cua Naples"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'cake',
  'room_temp',
  '{"flour","yeast","butter","eggs","rum","sugar syrup"}',
  'whipped cream',
  false,
  false,
  false,
  5,
  '{"country":"Italy","country_code":"IT","region":"Campania","city":"Naples"}'::jsonb,
  NULL,
  '{"portion_size":"small","is_shareable":false,"recommended_pairing":["limoncello","espresso"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","egg","milk"],"calories_estimate":290,"protein_g":4,"carbs_g":42,"fat_g":10,"fiber_g":1,"sugar_g":32}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":25,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"italian","naples","rum","yeast","soaked"}',
  78,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'biscotti-cantuccini',
  'biscotti-cantuccini',
  '{"en":"Cantuccini","it":"Cantuccini","vi":"Banh quy Cantuccini"}'::jsonb,
  '{"en":"Traditional Tuscan almond biscotti, twice-baked and perfect for dipping","it":"Tradizionali biscotti toscani alle mandorle, cotti due volte e perfetti da inzuppare","vi":"Banh quy hanh nhan Tuscany truyen thong, nuong hai lan va hoan hao de cham"}'::jsonb,
  NULL,
  'italian',
  'traditional',
  'cookie',
  'room_temp',
  '{"flour","almonds","eggs","sugar","butter"}',
  NULL,
  false,
  false,
  false,
  2,
  '{"country":"Italy","country_code":"IT","region":"Tuscany","city":"Prato"}'::jsonb,
  NULL,
  '{"portion_size":"small","pieces_per_serving":3,"is_shareable":true,"recommended_pairing":["vin santo","espresso","cappuccino"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","egg","milk","tree nuts"],"calories_estimate":140,"protein_g":3,"carbs_g":18,"fat_g":6,"fiber_g":1,"sugar_g":8}'::jsonb,
  '{"prep_time_min":20,"cook_time_min":40,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"italian","tuscan","biscotti","almond","twice-baked"}',
  80,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'semifreddo',
  'semifreddo',
  '{"en":"Semifreddo","it":"Semifreddo","vi":"Kem Semifreddo"}'::jsonb,
  '{"en":"Italian semi-frozen dessert with whipped cream and meringue, lighter than gelato","it":"Dolce italiano semi-ghiacciato con panna montata e meringa, piu leggero del gelato","vi":"Mon trang mieng Y nua dong voi kem tuoi va banh meringue, nhe hon gelato"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'frozen',
  'frozen',
  '{"cream","eggs","sugar","flavor base"}',
  NULL,
  false,
  false,
  true,
  3,
  '{"country":"Italy","country_code":"IT"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["espresso","dessert wine","fresh berries"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["egg","milk"],"calories_estimate":300,"protein_g":5,"carbs_g":28,"fat_g":20,"fiber_g":0,"sugar_g":24}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":0,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"italian","frozen","cream","elegant","no-churn"}',
  75,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'affogato',
  'affogato',
  '{"en":"Affogato","it":"Affogato","vi":"Kem ca phe Affogato"}'::jsonb,
  '{"en":"Vanilla gelato drowned in a shot of hot espresso","it":"Gelato alla vaniglia annegato in un caffe espresso caldo","vi":"Kem vani cham trong mot shot ca phe espresso nong"}'::jsonb,
  NULL,
  'italian',
  'classic',
  'gelato',
  'cold',
  '{"vanilla gelato","espresso"}',
  NULL,
  false,
  false,
  true,
  3,
  '{"country":"Italy","country_code":"IT"}'::jsonb,
  NULL,
  '{"portion_size":"small","is_shareable":false,"recommended_pairing":["biscotti","amaretto liqueur"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["milk"],"calories_estimate":200,"protein_g":4,"carbs_g":24,"fat_g":10,"fiber_g":0,"sugar_g":20}'::jsonb,
  '{"prep_time_min":2,"cook_time_min":0,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"italian","coffee","gelato","quick","elegant"}',
  88,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'creme-brulee',
  'creme-brulee',
  '{"en":"Creme Brulee","it":"Creme Brulee","vi":"Kem Creme Brulee"}'::jsonb,
  '{"en":"Rich vanilla custard with caramelized sugar crust, cracked tableside","it":"Ricca crema alla vaniglia con crosta di zucchero caramellato, rotta al tavolo","vi":"Kem vani dam da voi lop duong caramen, dap tren ban"}'::jsonb,
  NULL,
  'french',
  'classic',
  'custard',
  'cold',
  '{"cream","egg yolks","sugar","vanilla"}',
  'caramelized sugar',
  false,
  false,
  true,
  4,
  '{"country":"France","country_code":"FR"}'::jsonb,
  '{"story":{"en":"Disputed origins between France, England and Spain, but perfected in French cuisine","it":"Origini contestate tra Francia, Inghilterra e Spagna, ma perfezionata nella cucina francese","vi":"Nguon goc tranh cai giua Phap, Anh va Tay Ban Nha, nhung duoc hoan thien trong am thuc Phap"}}'::jsonb,
  '{"portion_size":"small","is_shareable":false,"recommended_pairing":["sauternes","champagne","espresso"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["egg","milk"],"calories_estimate":380,"protein_g":5,"carbs_g":32,"fat_g":28,"fiber_g":0,"sugar_g":28}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":45,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"french","classic","custard","vanilla","elegant"}',
  95,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'chocolate-mousse',
  'chocolate-mousse',
  '{"en":"Chocolate Mousse","it":"Mousse al Cioccolato","vi":"Mousse socola"}'::jsonb,
  '{"en":"Light and airy French chocolate mousse with dark chocolate","it":"Leggera e ariosa mousse francese al cioccolato fondente","vi":"Mousse socola Phap nhe va bong voi socola den"}'::jsonb,
  NULL,
  'french',
  'classic',
  'mousse',
  'cold',
  '{"dark chocolate","eggs","cream","sugar"}',
  NULL,
  true,
  false,
  true,
  3,
  '{"country":"France","country_code":"FR"}'::jsonb,
  NULL,
  '{"portion_size":"small","is_shareable":false,"recommended_pairing":["port wine","espresso","whipped cream"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["egg","milk"],"calories_estimate":340,"protein_g":6,"carbs_g":28,"fat_g":24,"fiber_g":2,"sugar_g":22}'::jsonb,
  '{"prep_time_min":25,"cook_time_min":5,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"french","chocolate","mousse","elegant","airy"}',
  92,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'tarte-tatin',
  'tarte-tatin',
  '{"en":"Tarte Tatin","it":"Tarte Tatin","vi":"Banh tao Tarte Tatin"}'::jsonb,
  '{"en":"Upside-down caramelized apple tart, a French classic","it":"Torta di mele caramellata capovolta, un classico francese","vi":"Banh tart tao caramen lat nguoc, mot mon Phap co dien"}'::jsonb,
  NULL,
  'french',
  'classic',
  'tart',
  'warm',
  '{"apples","butter","sugar","puff pastry"}',
  'creme fraiche',
  false,
  true,
  false,
  4,
  '{"country":"France","country_code":"FR","region":"Centre-Val de Loire","city":"Lamotte-Beuvron"}'::jsonb,
  '{"story":{"en":"Created by accident by the Tatin sisters in the 1880s at their hotel","it":"Creata per caso dalle sorelle Tatin negli anni 1880 nel loro hotel","vi":"Duoc tao ra tinh co boi chi em Tatin vao nhung nam 1880 tai khach san cua ho"},"year_created":1880,"creator":"Tatin Sisters"}'::jsonb,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["calvados","vanilla ice cream","creme fraiche"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk"],"calories_estimate":380,"protein_g":3,"carbs_g":52,"fat_g":18,"fiber_g":3,"sugar_g":36}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":45,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"french","apple","caramel","tart","classic"}',
  85,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'profiteroles',
  'profiteroles',
  '{"en":"Profiteroles","it":"Profiteroles","vi":"Banh su kem"}'::jsonb,
  '{"en":"Choux pastry puffs filled with vanilla ice cream, topped with hot chocolate sauce","it":"Bigne di pasta choux ripieni di gelato alla vaniglia, ricoperti di salsa al cioccolato caldo","vi":"Banh su nhan kem vani, phu sot socola nong"}'::jsonb,
  NULL,
  'french',
  'classic',
  'pastry',
  'cold',
  '{"choux pastry","vanilla ice cream","chocolate sauce"}',
  'hot chocolate sauce',
  true,
  false,
  true,
  4,
  '{"country":"France","country_code":"FR"}'::jsonb,
  NULL,
  '{"portion_size":"medium","pieces_per_serving":3,"is_shareable":true,"recommended_pairing":["dessert wine","champagne"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","egg","milk"],"calories_estimate":420,"protein_g":7,"carbs_g":48,"fat_g":24,"fiber_g":2,"sugar_g":32}'::jsonb,
  '{"prep_time_min":40,"cook_time_min":30,"difficulty":"hard"}'::jsonb,
  NULL,
  '{"french","choux","ice-cream","chocolate","elegant"}',
  88,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'mille-feuille',
  'mille-feuille',
  '{"en":"Mille-Feuille","it":"Millefoglie","vi":"Banh ngan lop"}'::jsonb,
  '{"en":"Thousand layer pastry with vanilla pastry cream and fondant icing","it":"Pasta sfoglia a mille strati con crema pasticcera alla vaniglia e glassa fondente","vi":"Banh ngan lop voi kem pastry vani va lop phu fondant"}'::jsonb,
  NULL,
  'french',
  'classic',
  'pastry',
  'cold',
  '{"puff pastry","pastry cream","fondant"}',
  'fondant icing',
  false,
  false,
  true,
  4,
  '{"country":"France","country_code":"FR"}'::jsonb,
  '{"story":{"en":"Also known as Napoleon, this pastry has been a French classic since the 17th century","it":"Conosciuto anche come Napoleon, questo dolce e un classico francese dal XVII secolo","vi":"Con duoc goi la Napoleon, banh nay la mon co dien Phap tu the ky 17"}}'::jsonb,
  '{"portion_size":"medium","is_shareable":false,"recommended_pairing":["champagne","tea","espresso"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","egg","milk"],"calories_estimate":420,"protein_g":6,"carbs_g":52,"fat_g":22,"fiber_g":1,"sugar_g":28}'::jsonb,
  '{"prep_time_min":60,"cook_time_min":25,"difficulty":"hard"}'::jsonb,
  NULL,
  '{"french","pastry","layered","napoleon","elegant"}',
  82,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'macarons',
  'macarons',
  '{"en":"French Macarons","it":"Macaron Francesi","vi":"Banh Macaron Phap"}'::jsonb,
  '{"en":"Delicate almond meringue cookies with ganache filling in various flavors","it":"Delicati biscotti di meringa alle mandorle con ripieno di ganache in vari gusti","vi":"Banh meringue hanh nhan tinh te voi nhan ganache nhieu huong vi"}'::jsonb,
  NULL,
  'french',
  'classic',
  'cookie',
  'room_temp',
  '{"almond flour","egg whites","sugar","ganache"}',
  NULL,
  false,
  false,
  true,
  4,
  '{"country":"France","country_code":"FR","city":"Paris"}'::jsonb,
  '{"story":{"en":"Perfected by Laduree in Paris, macarons became a symbol of French patisserie","it":"Perfezionati da Laduree a Parigi, i macaron sono diventati un simbolo della pasticceria francese","vi":"Duoc hoan thien boi Laduree o Paris, macaron tro thanh bieu tuong cua banh ngot Phap"}}'::jsonb,
  '{"portion_size":"small","pieces_per_serving":3,"is_shareable":true,"recommended_pairing":["champagne","tea","espresso"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":true,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["egg","tree nuts","milk"],"calories_estimate":220,"protein_g":3,"carbs_g":28,"fat_g":12,"fiber_g":1,"sugar_g":24}'::jsonb,
  '{"prep_time_min":60,"cook_time_min":15,"difficulty":"hard"}'::jsonb,
  NULL,
  '{"french","parisian","almond","colorful","elegant"}',
  94,
  NULL,
  NULL,
  '{"cost_level":"high"}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();