-- GUDBRO Desserts Batch 04
-- Records: 31 to 35 of 35
-- Generated: 2025-12-15T22:59:56.673Z

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'baklava',
  'baklava',
  '{"en":"Baklava","it":"Baklava","vi":"Banh Baklava"}'::jsonb,
  '{"en":"Sweet phyllo pastry filled with chopped nuts and honey syrup","it":"Dolce pasta fillo ripiena di noci tritate e sciroppo di miele","vi":"Banh phyllo ngot nhan hat rang va xi-ro mat ong"}'::jsonb,
  NULL,
  'middle_eastern',
  'classic',
  'pastry',
  'room_temp',
  '{"phyllo dough","pistachios","walnuts","honey","butter"}',
  NULL,
  false,
  false,
  false,
  5,
  '{"country":"Turkey","country_code":"TR"}'::jsonb,
  '{"story":{"en":"Dating back to the Ottoman Empire, baklava is a symbol of celebration across the Middle East","it":"Risalente all Impero Ottomano, il baklava e un simbolo di festa in tutto il Medio Oriente","vi":"Tu thoi De che Ottoman, baklava la bieu tuong cua le hoi khap Trung Dong"}}'::jsonb,
  '{"portion_size":"small","pieces_per_serving":2,"is_shareable":true,"recommended_pairing":["turkish coffee","tea","raki"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","milk","tree nuts"],"calories_estimate":320,"protein_g":5,"carbs_g":38,"fat_g":18,"fiber_g":2,"sugar_g":28}'::jsonb,
  '{"prep_time_min":45,"cook_time_min":50,"difficulty":"hard"}'::jsonb,
  NULL,
  '{"middle-eastern","turkish","phyllo","nuts","honey"}',
  90,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'kunafa',
  'kunafa',
  '{"en":"Kunafa","it":"Kunafa","vi":"Banh Kunafa"}'::jsonb,
  '{"en":"Middle Eastern dessert with shredded phyllo, cheese and sweet syrup","it":"Dolce mediorientale con fillo sfilacciato, formaggio e sciroppo dolce","vi":"Banh Trung Dong voi phyllo cat soi, pho mai va xi-ro ngot"}'::jsonb,
  NULL,
  'middle_eastern',
  'traditional',
  'pastry',
  'warm',
  '{"kataifi dough","cheese","sugar syrup","pistachios"}',
  'crushed pistachios',
  false,
  false,
  true,
  5,
  '{"country":"Palestine","country_code":"PS","city":"Nablus"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["arabic coffee","tea"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":false,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","milk","tree nuts"],"calories_estimate":420,"protein_g":10,"carbs_g":52,"fat_g":20,"fiber_g":1,"sugar_g":36}'::jsonb,
  '{"prep_time_min":30,"cook_time_min":40,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"middle-eastern","palestinian","cheese","syrup","crispy"}',
  85,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'basque-cheesecake',
  'basque-cheesecake',
  '{"en":"Basque Burnt Cheesecake","it":"Cheesecake Basca Bruciata","vi":"Banh pho mai chay Basque"}'::jsonb,
  '{"en":"Crustless cheesecake with caramelized top from San Sebastian","it":"Cheesecake senza crosta con top caramellato da San Sebastian","vi":"Banh pho mai khong vo voi mat caramen tu San Sebastian"}'::jsonb,
  NULL,
  'spanish',
  'modern',
  'cake',
  'room_temp',
  '{"cream cheese","eggs","sugar","cream","flour"}',
  NULL,
  false,
  false,
  true,
  3,
  '{"country":"Spain","country_code":"ES","region":"Basque Country","city":"San Sebastian"}'::jsonb,
  '{"story":{"en":"Created at La Vina restaurant in San Sebastian in the 1990s, now a global sensation","it":"Creato al ristorante La Vina a San Sebastian negli anni 90, ora una sensazione globale","vi":"Duoc tao ra tai nha hang La Vina o San Sebastian vao nhung nam 1990, nay la hien tuong toan cau"},"year_created":1990}'::jsonb,
  '{"portion_size":"medium","is_shareable":true,"recommended_pairing":["txakoli wine","sherry","espresso"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":true,"allergens":["gluten","egg","milk"],"calories_estimate":380,"protein_g":8,"carbs_g":28,"fat_g":28,"fiber_g":0,"sugar_g":22}'::jsonb,
  '{"prep_time_min":15,"cook_time_min":45,"difficulty":"easy"}'::jsonb,
  NULL,
  '{"spanish","basque","cheesecake","burnt","trendy"}',
  92,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'sticky-toffee-pudding',
  'sticky-toffee-pudding',
  '{"en":"Sticky Toffee Pudding","it":"Pudding al Toffee","vi":"Banh pudding toffee"}'::jsonb,
  '{"en":"Moist date sponge cake smothered in toffee sauce, British classic","it":"Morbido pan di spagna ai datteri coperto di salsa toffee, classico britannico","vi":"Banh bong lan choi am uot phu sot toffee, mon Anh co dien"}'::jsonb,
  NULL,
  'british',
  'classic',
  'pudding',
  'warm',
  '{"dates","brown sugar","butter","eggs","flour"}',
  'toffee sauce and vanilla ice cream',
  false,
  true,
  false,
  5,
  '{"country":"United Kingdom","country_code":"GB","region":"Lake District"}'::jsonb,
  NULL,
  '{"portion_size":"medium","is_shareable":false,"recommended_pairing":["custard","vanilla ice cream","cream"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":true,"is_kosher":true,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","egg","milk"],"calories_estimate":480,"protein_g":5,"carbs_g":68,"fat_g":22,"fiber_g":2,"sugar_g":52}'::jsonb,
  '{"prep_time_min":25,"cook_time_min":40,"difficulty":"medium"}'::jsonb,
  NULL,
  '{"british","dates","toffee","comfort","warm"}',
  86,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();

INSERT INTO desserts (
  id, slug, name, description, tagline,
  style, status, category, serving_temp,
  main_ingredients, topping, is_chocolate, is_fruit_based, is_creamy, sweetness_level,
  origin, history, serving, dietary, preparation,
  variations, tags, popularity, related_desserts, media, pricing
) VALUES (
  'black-forest-cake',
  'black-forest-cake',
  '{"en":"Black Forest Cake","it":"Torta Foresta Nera","vi":"Banh Rung Den"}'::jsonb,
  '{"en":"German chocolate sponge with cherries, whipped cream and kirsch","it":"Pan di spagna al cioccolato tedesco con ciliegie, panna montata e kirsch","vi":"Banh bong lan socola Duc voi cherry, kem tuoi va kirsch"}'::jsonb,
  NULL,
  'german',
  'classic',
  'cake',
  'cold',
  '{"chocolate sponge","cherries","whipped cream","kirsch"}',
  'chocolate shavings and cherries',
  true,
  true,
  true,
  4,
  '{"country":"Germany","country_code":"DE","region":"Black Forest"}'::jsonb,
  '{"story":{"en":"Named after the Black Forest region, this cake became internationally famous in the 1930s","it":"Prende il nome dalla regione della Foresta Nera, questa torta e diventata famosa negli anni 30","vi":"Dat theo ten vung Rung Den, banh nay tro nen noi tieng quoc te vao nhung nam 1930"},"year_created":1915}'::jsonb,
  '{"portion_size":"large","is_shareable":true,"recommended_pairing":["kirsch","coffee","cherry liqueur"]}'::jsonb,
  '{"is_vegetarian":true,"is_vegan":false,"is_gluten_free":false,"is_dairy_free":false,"is_nut_free":true,"is_halal":false,"is_kosher":false,"is_low_carb":false,"is_keto_friendly":false,"is_high_protein":false,"allergens":["gluten","egg","milk"],"calories_estimate":420,"protein_g":6,"carbs_g":48,"fat_g":24,"fiber_g":2,"sugar_g":36}'::jsonb,
  '{"prep_time_min":60,"cook_time_min":35,"difficulty":"hard"}'::jsonb,
  NULL,
  '{"german","chocolate","cherry","cream","layered"}',
  88,
  NULL,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  tagline = EXCLUDED.tagline,
  style = EXCLUDED.style,
  status = EXCLUDED.status,
  category = EXCLUDED.category,
  serving_temp = EXCLUDED.serving_temp,
  main_ingredients = EXCLUDED.main_ingredients,
  topping = EXCLUDED.topping,
  is_chocolate = EXCLUDED.is_chocolate,
  is_fruit_based = EXCLUDED.is_fruit_based,
  is_creamy = EXCLUDED.is_creamy,
  sweetness_level = EXCLUDED.sweetness_level,
  origin = EXCLUDED.origin,
  history = EXCLUDED.history,
  serving = EXCLUDED.serving,
  dietary = EXCLUDED.dietary,
  preparation = EXCLUDED.preparation,
  variations = EXCLUDED.variations,
  tags = EXCLUDED.tags,
  popularity = EXCLUDED.popularity,
  related_desserts = EXCLUDED.related_desserts,
  media = EXCLUDED.media,
  pricing = EXCLUDED.pricing,
  updated_at = now();